// GENERATED by tools/mtp_ring_dyn_vehicle.py -- do not edit.
// Route vehicle of the ring-8 DYN table (ot_hdc_v41x_dyn_unit) at the DS ROM full shape: every input and output is a
// pin flop (registered boundary); b_pos = pos_r + ds is the core's own adder.  Read ports in DYI_* order (core).
module ot_dsrom_ring_dyn_vehicle #(
    parameter integer FULL_SHAPE = 1,
    parameter integer NSLOT = 1,
    parameter integer ROLLBACK_RING_DYN = 1,
    parameter integer AW = FULL_SHAPE ? 30 : 24,
    parameter integer NW = FULL_SHAPE ? 21 : 16,
    parameter integer NRD = 17,
    parameter integer RIW = 8
) (
    input  wire              clk,
    input  wire              rst_n,
    input  wire              i_cap,
    input  wire [2:0]        i_ds,
    input  wire [NW-1:0]     i_tok,
    input  wire [NW-1:0]     i_pos,
    input  wire [NRD*3-1:0]  i_rd_slot,
    input  wire [NRD*RIW-1:0] i_rd_idx,
    output reg  [NRD*AW-1:0] o_rd_val
);
    reg              cap_q;
    reg [2:0]        ds_q;
    reg [NW-1:0]     tok_q, pos_q;
    reg [NRD*3-1:0]  slot_q;
    reg [NRD*RIW-1:0] idx_q;
    wire [NRD*AW-1:0] val;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) cap_q <= 1'b0;
        else cap_q <= i_cap;
    end
    always @(posedge clk) begin
        ds_q <= i_ds; tok_q <= i_tok; pos_q <= i_pos; slot_q <= i_rd_slot; idx_q <= i_rd_idx;
        o_rd_val <= val;
    end
    wire [NW-1:0] b_pos = pos_q + ds_q;
    ot_hdc_v41x_dyn_unit #(.FULL_SHAPE(FULL_SHAPE), .AW(AW), .NW(NW), .NSLOT(NSLOT),
                           .ROLLBACK_RING_DYN(ROLLBACK_RING_DYN), .NRD(NRD), .RIW(RIW)) u_dyn (
        .clk(clk), .cap(cap_q), .ds(ds_q), .b_tok(tok_q), .b_pos(b_pos),
        .rd_slot(slot_q), .rd_idx(idx_q), .rd_val(val));
endmodule

// ot_hdc_v41x_dyn_unit: the v41x core sequencer's DYN table (capture at S_DYN + the decode read selectors), moved
// out of ot_hdc_core_v41x VERBATIM (mtp-lead 2026-10-09) so the ring-8 DYN25/26 repair (ROLLBACK_RING_DYN, V36) has a
// routable physical vehicle.  Behaviour and cycles are unchanged: the capture is the same always block on the same
// enable; each read port is the same combinational array read dyn[slot * NDYN + idx] the core's `DY macro made.
// Read ports (core order): 0 ME_D_NOUT 1 ME_D_TILES 2 ME_D_K 3 ME_D_WBASE 4 SU_D_NOUT 5 SU_D_NIN 6 XU_D_N 7 XU_D_K
// 8 ME_D_XBASE 9 ME_D_OBASE 10 A_D 11 B_D 12 C_D 13 D_D 14 O_D 15 QE_D_OBASE 16 rope prefetch position (idx 4).
module ot_hdc_v41x_dyn_unit #(
    parameter integer FULL_SHAPE = 0,
    parameter integer W    = 16,
    parameter integer G    = 4,
    parameter integer AW   = FULL_SHAPE ? 30 : 24,
    parameter integer NW   = FULL_SHAPE ? 21 : 16,
    parameter integer DIM  = FULL_SHAPE ? 5120 : 160,
    parameter integer TOPK = FULL_SHAPE ? 512 : 16,
    parameter integer HDIM = FULL_SHAPE ? 512 : 32,
    parameter integer ROPE_PAIR = FULL_SHAPE ? 32 : 2,
    parameter integer FULL_WINDOW = 128,
    parameter integer FULL_SCAN_CAP = 16384,
    parameter integer FULL_TP = 4,
    parameter integer NSLOT = 1,
    parameter integer ROLLBACK_RING_DYN = 1,
    parameter integer NRD = 17,
    parameter integer RIW = 8
) (
    input  wire              clk,
    input  wire              cap,          // st == S_DYN
    input  wire [2:0]        ds,           // DYN bank being computed
    input  wire [NW-1:0]     b_tok,
    input  wire [NW-1:0]     b_pos,
    input  wire [NRD*3-1:0]  rd_slot,
    input  wire [NRD*RIW-1:0] rd_idx,
    output wire [NRD*AW-1:0] rd_val
);
    // --- inlined rtl/hdc/v41/ot_hdc_isa_v41_profiles.svh ---
// GENERATED by tools/hdc_isa_v41.py --core-profiles -- do not edit.
// Included in ot_hdc_core_v41x; FULL_SHAPE is an elaboration parameter.
localparam integer ISA_INSTR_BITS = FULL_SHAPE ? 2048 : 1536;
localparam integer O_UNIT = FULL_SHAPE ? 0 : 0;
localparam integer W_UNIT = FULL_SHAPE ? 3 : 3;
localparam integer O_WAIT = FULL_SHAPE ? 3 : 3;
localparam integer W_WAIT = FULL_SHAPE ? 6 : 5;
localparam integer O_PRED = FULL_SHAPE ? 9 : 8;
localparam integer W_PRED = FULL_SHAPE ? 2 : 2;
localparam integer O_ME_NOUT = FULL_SHAPE ? 11 : 10;
localparam integer W_ME_NOUT = FULL_SHAPE ? 21 : 16;
localparam integer O_ME_TILES = FULL_SHAPE ? 32 : 26;
localparam integer W_ME_TILES = FULL_SHAPE ? 21 : 16;
localparam integer O_ME_K = FULL_SHAPE ? 53 : 42;
localparam integer W_ME_K = FULL_SHAPE ? 21 : 16;
localparam integer O_ME_WSRC = FULL_SHAPE ? 74 : 58;
localparam integer W_ME_WSRC = FULL_SHAPE ? 1 : 1;
localparam integer O_ME_WBASE = FULL_SHAPE ? 75 : 59;
localparam integer W_ME_WBASE = FULL_SHAPE ? 30 : 24;
localparam integer O_ME_TS = FULL_SHAPE ? 105 : 83;
localparam integer W_ME_TS = FULL_SHAPE ? 30 : 24;
localparam integer O_ME_KS = FULL_SHAPE ? 135 : 107;
localparam integer W_ME_KS = FULL_SHAPE ? 30 : 24;
localparam integer O_ME_JS = FULL_SHAPE ? 165 : 131;
localparam integer W_ME_JS = FULL_SHAPE ? 30 : 24;
localparam integer O_ME_XBASE = FULL_SHAPE ? 195 : 155;
localparam integer W_ME_XBASE = FULL_SHAPE ? 30 : 24;
localparam integer O_ME_ROUND = FULL_SHAPE ? 225 : 179;
localparam integer W_ME_ROUND = FULL_SHAPE ? 1 : 1;
localparam integer O_ME_OBASE = FULL_SHAPE ? 226 : 180;
localparam integer W_ME_OBASE = FULL_SHAPE ? 30 : 24;
localparam integer O_ME_OEN = FULL_SHAPE ? 256 : 204;
localparam integer W_ME_OEN = FULL_SHAPE ? 1 : 1;
localparam integer O_ME_AMAX = FULL_SHAPE ? 257 : 205;
localparam integer W_ME_AMAX = FULL_SHAPE ? 1 : 1;
localparam integer O_ME_D_WBASE = FULL_SHAPE ? 258 : 206;
localparam integer W_ME_D_WBASE = FULL_SHAPE ? 6 : 5;
localparam integer O_ME_D_XBASE = FULL_SHAPE ? 264 : 211;
localparam integer W_ME_D_XBASE = FULL_SHAPE ? 6 : 5;
localparam integer O_ME_D_OBASE = FULL_SHAPE ? 270 : 216;
localparam integer W_ME_D_OBASE = FULL_SHAPE ? 6 : 5;
localparam integer O_ME_D_NOUT = FULL_SHAPE ? 276 : 221;
localparam integer W_ME_D_NOUT = FULL_SHAPE ? 6 : 5;
localparam integer O_ME_D_TILES = FULL_SHAPE ? 282 : 226;
localparam integer W_ME_D_TILES = FULL_SHAPE ? 6 : 5;
localparam integer O_ME_D_K = FULL_SHAPE ? 288 : 231;
localparam integer W_ME_D_K = FULL_SHAPE ? 6 : 5;
localparam integer O_ME_XKS = FULL_SHAPE ? 294 : 236;
localparam integer W_ME_XKS = FULL_SHAPE ? 30 : 24;
localparam integer O_ME_XJS = FULL_SHAPE ? 324 : 260;
localparam integer W_ME_XJS = FULL_SHAPE ? 30 : 24;
localparam integer O_ME_JSH = FULL_SHAPE ? 354 : 284;
localparam integer W_ME_JSH = FULL_SHAPE ? 3 : 3;
localparam integer O_ME_OTS = FULL_SHAPE ? 357 : 287;
localparam integer W_ME_OTS = FULL_SHAPE ? 30 : 24;
localparam integer O_ME_OJS = FULL_SHAPE ? 387 : 311;
localparam integer W_ME_OJS = FULL_SHAPE ? 30 : 24;
localparam integer O_ME_MMODE = FULL_SHAPE ? 417 : 335;
localparam integer W_ME_MMODE = FULL_SHAPE ? 1 : 1;
localparam integer O_ME_SPLIT = FULL_SHAPE ? 418 : 336;
localparam integer W_ME_SPLIT = FULL_SHAPE ? 2 : 2;
localparam integer O_ME_XCS = FULL_SHAPE ? 420 : 338;
localparam integer W_ME_XCS = FULL_SHAPE ? 30 : 24;
localparam integer O_ME_HG = FULL_SHAPE ? 450 : 362;
localparam integer W_ME_HG = FULL_SHAPE ? 2 : 2;
localparam integer O_ME_OGS = FULL_SHAPE ? 452 : 364;
localparam integer W_ME_OGS = FULL_SHAPE ? 30 : 24;
localparam integer O_SU_NOUT = FULL_SHAPE ? 482 : 388;
localparam integer W_SU_NOUT = FULL_SHAPE ? 21 : 16;
localparam integer O_SU_NIN = FULL_SHAPE ? 503 : 404;
localparam integer W_SU_NIN = FULL_SHAPE ? 21 : 16;
localparam integer O_SU_D_NOUT = FULL_SHAPE ? 524 : 420;
localparam integer W_SU_D_NOUT = FULL_SHAPE ? 6 : 5;
localparam integer O_SU_D_NIN = FULL_SHAPE ? 530 : 425;
localparam integer W_SU_D_NIN = FULL_SHAPE ? 6 : 5;
localparam integer O_A_SRC = FULL_SHAPE ? 536 : 430;
localparam integer W_A_SRC = FULL_SHAPE ? 2 : 2;
localparam integer O_A_BASE = FULL_SHAPE ? 538 : 432;
localparam integer W_A_BASE = FULL_SHAPE ? 30 : 24;
localparam integer O_A_SO = FULL_SHAPE ? 568 : 456;
localparam integer W_A_SO = FULL_SHAPE ? 30 : 24;
localparam integer O_A_SI = FULL_SHAPE ? 598 : 480;
localparam integer W_A_SI = FULL_SHAPE ? 30 : 24;
localparam integer O_A_D = FULL_SHAPE ? 628 : 504;
localparam integer W_A_D = FULL_SHAPE ? 6 : 5;
localparam integer O_A_IND = FULL_SHAPE ? 634 : 509;
localparam integer W_A_IND = FULL_SHAPE ? 2 : 2;
localparam integer O_A_IBASE = FULL_SHAPE ? 636 : 511;
localparam integer W_A_IBASE = FULL_SHAPE ? 30 : 24;
localparam integer O_B_SRC = FULL_SHAPE ? 666 : 535;
localparam integer W_B_SRC = FULL_SHAPE ? 2 : 2;
localparam integer O_B_BASE = FULL_SHAPE ? 668 : 537;
localparam integer W_B_BASE = FULL_SHAPE ? 30 : 24;
localparam integer O_B_SO = FULL_SHAPE ? 698 : 561;
localparam integer W_B_SO = FULL_SHAPE ? 30 : 24;
localparam integer O_B_SI = FULL_SHAPE ? 728 : 585;
localparam integer W_B_SI = FULL_SHAPE ? 30 : 24;
localparam integer O_B_D = FULL_SHAPE ? 758 : 609;
localparam integer W_B_D = FULL_SHAPE ? 6 : 5;
localparam integer O_B_HALF = FULL_SHAPE ? 764 : 614;
localparam integer W_B_HALF = FULL_SHAPE ? 1 : 1;
localparam integer O_C_SRC = FULL_SHAPE ? 765 : 615;
localparam integer W_C_SRC = FULL_SHAPE ? 2 : 2;
localparam integer O_C_BASE = FULL_SHAPE ? 767 : 617;
localparam integer W_C_BASE = FULL_SHAPE ? 30 : 24;
localparam integer O_C_SO = FULL_SHAPE ? 797 : 641;
localparam integer W_C_SO = FULL_SHAPE ? 30 : 24;
localparam integer O_C_SI = FULL_SHAPE ? 827 : 665;
localparam integer W_C_SI = FULL_SHAPE ? 30 : 24;
localparam integer O_C_D = FULL_SHAPE ? 857 : 689;
localparam integer W_C_D = FULL_SHAPE ? 6 : 5;
localparam integer O_C_PAIR = FULL_SHAPE ? 863 : 694;
localparam integer W_C_PAIR = FULL_SHAPE ? 1 : 1;
localparam integer O_D_SRC = FULL_SHAPE ? 864 : 695;
localparam integer W_D_SRC = FULL_SHAPE ? 2 : 2;
localparam integer O_D_BASE = FULL_SHAPE ? 866 : 697;
localparam integer W_D_BASE = FULL_SHAPE ? 30 : 24;
localparam integer O_D_SO = FULL_SHAPE ? 896 : 721;
localparam integer W_D_SO = FULL_SHAPE ? 30 : 24;
localparam integer O_D_SI = FULL_SHAPE ? 926 : 745;
localparam integer W_D_SI = FULL_SHAPE ? 30 : 24;
localparam integer O_D_D = FULL_SHAPE ? 956 : 769;
localparam integer W_D_D = FULL_SHAPE ? 6 : 5;
localparam integer O_A_RND = FULL_SHAPE ? 962 : 774;
localparam integer W_A_RND = FULL_SHAPE ? 1 : 1;
localparam integer O_A_RELU = FULL_SHAPE ? 963 : 775;
localparam integer W_A_RELU = FULL_SHAPE ? 1 : 1;
localparam integer O_A_MIN = FULL_SHAPE ? 964 : 776;
localparam integer W_A_MIN = FULL_SHAPE ? 1 : 1;
localparam integer O_C_CLIP = FULL_SHAPE ? 965 : 777;
localparam integer W_C_CLIP = FULL_SHAPE ? 1 : 1;
localparam integer O_M1 = FULL_SHAPE ? 966 : 778;
localparam integer W_M1 = FULL_SHAPE ? 3 : 3;
localparam integer O_M2 = FULL_SHAPE ? 969 : 781;
localparam integer W_M2 = FULL_SHAPE ? 2 : 2;
localparam integer O_QM = FULL_SHAPE ? 971 : 783;
localparam integer W_QM = FULL_SHAPE ? 3 : 3;
localparam integer O_AD = FULL_SHAPE ? 974 : 786;
localparam integer W_AD = FULL_SHAPE ? 3 : 3;
localparam integer O_SFU = FULL_SHAPE ? 977 : 789;
localparam integer W_SFU = FULL_SHAPE ? 3 : 3;
localparam integer O_E1 = FULL_SHAPE ? 980 : 792;
localparam integer W_E1 = FULL_SHAPE ? 3 : 3;
localparam integer O_E2 = FULL_SHAPE ? 983 : 795;
localparam integer W_E2 = FULL_SHAPE ? 2 : 2;
localparam integer O_RND = FULL_SHAPE ? 985 : 797;
localparam integer W_RND = FULL_SHAPE ? 1 : 1;
localparam integer O_DST = FULL_SHAPE ? 986 : 798;
localparam integer W_DST = FULL_SHAPE ? 2 : 2;
localparam integer O_O_BASE = FULL_SHAPE ? 988 : 800;
localparam integer W_O_BASE = FULL_SHAPE ? 30 : 24;
localparam integer O_O_SO = FULL_SHAPE ? 1018 : 824;
localparam integer W_O_SO = FULL_SHAPE ? 30 : 24;
localparam integer O_O_SI = FULL_SHAPE ? 1048 : 848;
localparam integer W_O_SI = FULL_SHAPE ? 30 : 24;
localparam integer O_O_D = FULL_SHAPE ? 1078 : 872;
localparam integer W_O_D = FULL_SHAPE ? 6 : 5;
localparam integer O_RED = FULL_SHAPE ? 1084 : 877;
localparam integer W_RED = FULL_SHAPE ? 2 : 2;
localparam integer O_RED_SQ = FULL_SHAPE ? 1086 : 879;
localparam integer W_RED_SQ = FULL_SHAPE ? 1 : 1;
localparam integer O_RED_WHOLE = FULL_SHAPE ? 1087 : 880;
localparam integer W_RED_WHOLE = FULL_SHAPE ? 1 : 1;
localparam integer O_RED_RND = FULL_SHAPE ? 1088 : 881;
localparam integer W_RED_RND = FULL_SHAPE ? 1 : 1;
localparam integer O_R_BASE = FULL_SHAPE ? 1089 : 882;
localparam integer W_R_BASE = FULL_SHAPE ? 30 : 24;
localparam integer O_R_SO = FULL_SHAPE ? 1119 : 906;
localparam integer W_R_SO = FULL_SHAPE ? 30 : 24;
localparam integer O_IMM1 = FULL_SHAPE ? 1149 : 930;
localparam integer W_IMM1 = FULL_SHAPE ? 32 : 32;
localparam integer O_IMM2 = FULL_SHAPE ? 1181 : 962;
localparam integer W_IMM2 = FULL_SHAPE ? 32 : 32;
localparam integer O_IMM3 = FULL_SHAPE ? 1213 : 994;
localparam integer W_IMM3 = FULL_SHAPE ? 32 : 32;
localparam integer O_QE_MODE = FULL_SHAPE ? 1245 : 1026;
localparam integer W_QE_MODE = FULL_SHAPE ? 2 : 2;
localparam integer O_QE_FP4 = FULL_SHAPE ? 1247 : 1028;
localparam integer W_QE_FP4 = FULL_SHAPE ? 1 : 1;
localparam integer O_QE_XBASE = FULL_SHAPE ? 1248 : 1029;
localparam integer W_QE_XBASE = FULL_SHAPE ? 30 : 24;
localparam integer O_QE_NB = FULL_SHAPE ? 1278 : 1053;
localparam integer W_QE_NB = FULL_SHAPE ? 8 : 8;
localparam integer O_QE_NOUT = FULL_SHAPE ? 1286 : 1061;
localparam integer W_QE_NOUT = FULL_SHAPE ? 21 : 16;
localparam integer O_QE_TILES = FULL_SHAPE ? 1307 : 1077;
localparam integer W_QE_TILES = FULL_SHAPE ? 21 : 16;
localparam integer O_QE_WBASE = FULL_SHAPE ? 1328 : 1093;
localparam integer W_QE_WBASE = FULL_SHAPE ? 30 : 24;
localparam integer O_QE_IND = FULL_SHAPE ? 1358 : 1117;
localparam integer W_QE_IND = FULL_SHAPE ? 1 : 1;
localparam integer O_QE_IBASE = FULL_SHAPE ? 1359 : 1118;
localparam integer W_QE_IBASE = FULL_SHAPE ? 30 : 24;
localparam integer O_QE_ISTRIDE = FULL_SHAPE ? 1389 : 1142;
localparam integer W_QE_ISTRIDE = FULL_SHAPE ? 30 : 24;
localparam integer O_QE_OBASE = FULL_SHAPE ? 1419 : 1166;
localparam integer W_QE_OBASE = FULL_SHAPE ? 30 : 24;
localparam integer O_QE_D_OBASE = FULL_SHAPE ? 1449 : 1190;
localparam integer W_QE_D_OBASE = FULL_SHAPE ? 6 : 5;
localparam integer O_XU_OP = FULL_SHAPE ? 1455 : 1195;
localparam integer W_XU_OP = FULL_SHAPE ? 2 : 2;
localparam integer O_XU_SRC = FULL_SHAPE ? 1457 : 1197;
localparam integer W_XU_SRC = FULL_SHAPE ? 30 : 24;
localparam integer O_XU_DST = FULL_SHAPE ? 1487 : 1221;
localparam integer W_XU_DST = FULL_SHAPE ? 30 : 24;
localparam integer O_XU_N = FULL_SHAPE ? 1517 : 1245;
localparam integer W_XU_N = FULL_SHAPE ? 21 : 16;
localparam integer O_XU_D_N = FULL_SHAPE ? 1538 : 1261;
localparam integer W_XU_D_N = FULL_SHAPE ? 6 : 5;
localparam integer O_XU_K = FULL_SHAPE ? 1544 : 1266;
localparam integer W_XU_K = FULL_SHAPE ? 12 : 5;
localparam integer O_XU_D_K = FULL_SHAPE ? 1556 : 1271;
localparam integer W_XU_D_K = FULL_SHAPE ? 6 : 5;
localparam integer O_XU_LAYER = FULL_SHAPE ? 1562 : 1276;
localparam integer W_XU_LAYER = FULL_SHAPE ? 1 : 1;
localparam integer O_HE_NOUT = FULL_SHAPE ? 1563 : 1277;
localparam integer W_HE_NOUT = FULL_SHAPE ? 21 : 16;
localparam integer O_HE_K = FULL_SHAPE ? 1584 : 1293;
localparam integer W_HE_K = FULL_SHAPE ? 21 : 16;
localparam integer O_HE_WBASE = FULL_SHAPE ? 1605 : 1309;
localparam integer W_HE_WBASE = FULL_SHAPE ? 30 : 24;
localparam integer O_HE_XBASE = FULL_SHAPE ? 1635 : 1333;
localparam integer W_HE_XBASE = FULL_SHAPE ? 30 : 24;
localparam integer O_HE_OBASE = FULL_SHAPE ? 1665 : 1357;
localparam integer W_HE_OBASE = FULL_SHAPE ? 30 : 24;
localparam integer O_SU_VEC = FULL_SHAPE ? 1695 : 1381;
localparam integer W_SU_VEC = FULL_SHAPE ? 2 : 2;
localparam integer O_RED_TREE = FULL_SHAPE ? 1697 : 1383;
localparam integer W_RED_TREE = FULL_SHAPE ? 1 : 1;
localparam integer O_SU_CHASE = FULL_SHAPE ? 1698 : 1384;
localparam integer W_SU_CHASE = FULL_SHAPE ? 21 : 16;
localparam integer O_WREL = FULL_SHAPE ? 1719 : 1400;
localparam integer W_WREL = FULL_SHAPE ? 1 : 1;
localparam integer O_DSLOT = FULL_SHAPE ? 1720 : 1401;
localparam integer W_DSLOT = FULL_SHAPE ? 3 : 3;
localparam integer O_MX_M = FULL_SHAPE ? 1723 : 1404;
localparam integer W_MX_M = FULL_SHAPE ? 3 : 3;
localparam integer O_MX_XPS = FULL_SHAPE ? 1726 : 1407;
localparam integer W_MX_XPS = FULL_SHAPE ? 30 : 24;
localparam integer O_MX_OPS = FULL_SHAPE ? 1756 : 1431;
localparam integer W_MX_OPS = FULL_SHAPE ? 30 : 24;
localparam integer O_CTL = FULL_SHAPE ? 1786 : 1455;
localparam integer W_CTL = FULL_SHAPE ? 3 : 3;
localparam integer O_CTL_SLOT = FULL_SHAPE ? 1789 : 1458;
localparam integer W_CTL_SLOT = FULL_SHAPE ? 3 : 3;
localparam integer O_CTL_LANE = FULL_SHAPE ? 1792 : 1461;
localparam integer W_CTL_LANE = FULL_SHAPE ? 3 : 3;
localparam integer O_ME_FUSE = FULL_SHAPE ? 1795 : 1464;
localparam integer W_ME_FUSE = FULL_SHAPE ? 1 : 1;
localparam integer O_ME_WTS = FULL_SHAPE ? 1796 : 1465;
localparam integer W_ME_WTS = FULL_SHAPE ? 30 : 24;
localparam integer O_COLL_OP = 1826;
localparam integer W_COLL_OP = 2;
localparam integer O_COLL_SRC = 1828;
localparam integer W_COLL_SRC = 30;
localparam integer O_COLL_DST = 1858;
localparam integer W_COLL_DST = 30;
localparam integer O_COLL_N = 1888;
localparam integer W_COLL_N = 21;
localparam integer O_COLL_K = 1909;
localparam integer W_COLL_K = 12;
localparam integer O_COLL_IBASE = 1921;
localparam integer W_COLL_IBASE = 30;
localparam integer O_COLL_SEQ = 1951;
localparam integer W_COLL_SEQ = 8;
localparam integer O_COLL_RND = 1959;
localparam integer W_COLL_RND = 1;
localparam integer O_QE_UNROUNDED = 1960;
localparam integer W_QE_UNROUNDED = 1;
localparam integer O_COLL_D_STRIDE = 2042;
localparam integer W_COLL_D_STRIDE = 6;
localparam integer FDYN_WIN = 28;
localparam integer FDYN_NC1 = 29;
localparam integer FDYN_NC2 = 30;
localparam integer FDYN_NS1 = 31;
localparam integer FDYN_NS2 = 32;
localparam integer FDYN_T0 = 33;
localparam integer FDYN_T1 = 34;
localparam integer FDYN_T2 = 35;
localparam integer FDYN_SC1 = 36;
localparam integer FDYN_SC2 = 37;
localparam integer FDYN_SCR = 38;
localparam integer FDYN_NSL1 = 39;
localparam integer FDYN_NSL2 = 40;
localparam integer FDYN_NSLR = 41;
localparam integer FDYN_CEIL_SC1_16 = 42;
localparam integer FDYN_CEIL_SC1_8 = 43;
localparam integer FDYN_CEIL_SC2_16 = 44;
localparam integer FDYN_CEIL_SCR_16 = 45;
localparam integer FDYN_CEIL_T0_32 = 46;
localparam integer FDYN_CEIL_T1_32 = 47;
localparam integer FDYN_CEIL_T2_32 = 48;
localparam integer FDYN_WINM1 = 49;
localparam integer FDYN_WIN_ROW = 50;
localparam integer FDYN_WINM1_ROW = 51;
localparam integer FDYN_NEWBLK = 52;
// --- end inline ---
    localparam integer LG = $clog2(W * G);
    localparam integer NDYN = FULL_SHAPE ? 64 : 32;
    reg [AW-1:0] dyn [0:NSLOT*NDYN-1];
    genvar gr;
    generate for (gr = 0; gr < NRD; gr = gr + 1) begin : g_rd
        assign rd_val[gr * AW +: AW] = dyn[rd_slot[gr * 3 +: 3] * NDYN + rd_idx[gr * RIW +: RIW]];
    end endgenerate

    wire [NW-1:0] p1 = b_pos + 1'b1;
    wire [NW-1:0] n2 = p1 >> 1;
    wire [NW-1:0] ns1 = (p1 < TOPK) ? p1 : TOPK;
    wire [NW-1:0] ns2 = (n2 < TOPK) ? n2 : TOPK;
    function automatic [AW-1:0] rnds(input [NW-1:0] x);
        rnds = (x == 0) ? 0 : ((x - 1) >> LG) + 1;
    endfunction
    function automatic [AW-1:0] rnd16(input [NW-1:0] x);      // 16-row tiles: head-group KV ops
        rnd16 = (x == 0) ? 0 : ((x - 1) >> $clog2(W)) + 1;
    endfunction
    integer di;
    wire [$clog2(NSLOT*NDYN)-1:0] db = ds * NDYN;
    always @(posedge clk) if (cap) begin
        for (di = 0; di < NDYN; di = di + 1) dyn[db + di] <= 0;
        dyn[db + 1] <= b_tok * DIM;
        dyn[db + 2] <= b_pos * ROPE_PAIR;
        dyn[db + 3] <= (b_pos == 0) ? 0 : (b_pos - 1) * ROPE_PAIR;
        dyn[db + 4] <= b_pos;
        dyn[db + 5] <= p1;
        dyn[db + 6] <= n2;
        dyn[db + 7] <= (n2 == 0) ? 0 : n2 - 1;
        dyn[db + 8] <= ns1;
        dyn[db + 9] <= ns2;
        dyn[db + 10] <= p1 + ns1;
        dyn[db + 11] <= p1 + ns2;
        dyn[db + 12] <= rnds(p1);
        dyn[db + 13] <= rnds(n2);
        dyn[db + 14] <= rnds(p1 + ns1);
        dyn[db + 15] <= rnds(p1 + ns2);
        dyn[db + 16] <= b_pos * HDIM;
        dyn[db + 17] <= p1 * HDIM;
        dyn[db + 18] <= b_pos[0] ? 4 : 0;
        dyn[db + 19] <= b_pos[0] ? 64 : 0;
        dyn[db + 20] <= (n2 == 0) ? 0 : (n2 - 1) * HDIM;
        dyn[db + 21] <= rnd16(p1);
        dyn[db + 22] <= rnd16(n2);
        dyn[db + 23] <= rnd16(p1 + ns1);
        dyn[db + 24] <= rnd16(p1 + ns2);
        if (NSLOT > 1 || ROLLBACK_RING_DYN != 0) begin
            // Ring storage is independent of the number of token slots. A
            // one-position wavefront still needs the current record and pair.
            dyn[db + 25] <= {b_pos[2:0], 2'b00};
            dyn[db + 26] <= {b_pos[2:1], 7'd0};
        end
        if (NSLOT > 1) begin
            dyn[db + 27] <= b_tok * 32;
        end
        if (FULL_SHAPE) begin
            dyn[db + FDYN_WIN] <= (p1 < FULL_WINDOW) ? p1 : FULL_WINDOW;
            dyn[db + FDYN_NC1] <= p1;
            dyn[db + FDYN_NC2] <= n2;
            dyn[db + FDYN_NS1] <= ns1;
            dyn[db + FDYN_NS2] <= ns2;
            dyn[db + FDYN_T0] <= ((p1 < FULL_WINDOW) ? p1 : FULL_WINDOW);
            dyn[db + FDYN_T1] <= ((p1 < FULL_WINDOW) ? p1 : FULL_WINDOW) + ns1;
            dyn[db + FDYN_T2] <= ((p1 < FULL_WINDOW) ? p1 : FULL_WINDOW) + ns2;
            dyn[db + FDYN_SC1] <= (p1 + FULL_TP - 1) / FULL_TP;
            dyn[db + FDYN_SC2] <= (n2 + FULL_TP - 1) / FULL_TP;
            dyn[db + FDYN_SCR] <= (((p1 < FULL_SCAN_CAP) ? p1 : FULL_SCAN_CAP) + FULL_TP - 1) / FULL_TP;
            dyn[db + FDYN_NSL1] <= (((p1 + FULL_TP - 1) / FULL_TP) < TOPK) ?
                                     ((p1 + FULL_TP - 1) / FULL_TP) : TOPK;
            dyn[db + FDYN_NSL2] <= (((n2 + FULL_TP - 1) / FULL_TP) < TOPK) ?
                                     ((n2 + FULL_TP - 1) / FULL_TP) : TOPK;
            dyn[db + FDYN_NSLR] <= (((((p1 < FULL_SCAN_CAP) ? p1 : FULL_SCAN_CAP) + FULL_TP - 1) / FULL_TP) < TOPK) ?
                                     ((((p1 < FULL_SCAN_CAP) ? p1 : FULL_SCAN_CAP) + FULL_TP - 1) / FULL_TP) : TOPK;
            dyn[db + FDYN_CEIL_SC1_16] <= (((p1 + FULL_TP - 1) / FULL_TP) + 15) >> 4;
            dyn[db + FDYN_CEIL_SC1_8] <= (((p1 + FULL_TP - 1) / FULL_TP) + 7) >> 3;
            dyn[db + FDYN_CEIL_SC2_16] <= (((n2 + FULL_TP - 1) / FULL_TP) + 15) >> 4;
            dyn[db + FDYN_CEIL_SCR_16] <= (((((p1 < FULL_SCAN_CAP) ? p1 : FULL_SCAN_CAP) + FULL_TP - 1) / FULL_TP) + 15) >> 4;
            dyn[db + FDYN_CEIL_T0_32] <= (((p1 < FULL_WINDOW) ? p1 : FULL_WINDOW) + 31) >> 5;
            dyn[db + FDYN_CEIL_T1_32] <= (((p1 < FULL_WINDOW) ? p1 : FULL_WINDOW) + ns1 + 31) >> 5;
            dyn[db + FDYN_CEIL_T2_32] <= (((p1 < FULL_WINDOW) ? p1 : FULL_WINDOW) + ns2 + 31) >> 5;
            dyn[db + FDYN_WINM1] <= ((p1 < FULL_WINDOW) ? p1 : FULL_WINDOW) - 1;
            dyn[db + FDYN_WIN_ROW] <= ((p1 < FULL_WINDOW) ? p1 : FULL_WINDOW) * HDIM;
            dyn[db + FDYN_WINM1_ROW] <= (((p1 < FULL_WINDOW) ? p1 : FULL_WINDOW) - 1) * HDIM;
        end
    end
endmodule
