    input wire cfg_layer,
    input wire [1:0] cfg_rank,
    input wire ck,
    output wire fault,
    output wire [30:0] hq_atom,
    input wire hq_cred,
    output wire [2:0] hq_tag,
    output wire hq_v,
    input wire [255:0] hr_d,
    input wire [3:0] hr_idx,
    input wire [2:0] hr_tag,
    input wire hr_v,
    output wire [2:0] o_beat,
    output wire [4:0] o_col,
    input wire o_cred,
    output wire [263:0] o_d,
    output wire [2:0] o_slot,
    output wire o_v,
    input wire [3:0] rel,
    input wire rst_n,
    output wire st_bad,
    output wire [2:0] st_slot,
    output wire st_v,
    output wire win_cred,
    input wire [67:0] win_ids,
    input wire win_v
