# generated by make_vm_split8.py: die port -> face chain depth
set fc_ps(f_su_NE) 3
set fc_ps(f_w_row) 1
set fc_ps(f_w_wr) 1
set fc_ps(t_su_NE) 3
set fc_ps(t_w_ctl) 1
set fc_ps(t_w_row) 1
set fc_ps(t_w_wr) 1
set fc_ps(xNE) 3
set fc_ps(s2n) 1
set fc_ps(n2s) 1
