# generated by make_vm_split8.py: die port -> face chain depth
set fc_ps(f_e_ctl) 1
set fc_ps(f_s_ctl) 1
set fc_ps(f_s_row) 1
set fc_ps(f_s_wr) 1
set fc_ps(iNW) 3
set fc_ps(qNW) 3
set fc_ps(t_s_ctl) 1
set fc_ps(t_s_row) 1
set fc_ps(t_s_wr) 1
set fc_ps(s2n) 1
set fc_ps(n2s) 1
