# generated by make_vm_split8.py: die port -> face chain depth
set fc_ps(f_su_SE) 3
set fc_ps(f_w_ctl) 1
set fc_ps(iSE) 3
set fc_ps(qSE) 3
set fc_ps(t_su_SE) 3
set fc_ps(xSE) 3
set fc_ps(s2n) 1
set fc_ps(n2s) 1
