// GENERATED by vm/split8/make_vm_split8.py: hfd_vm_ne as its two 8-way sub-tiles (bench join; quadrant port list)
module hfd_vm_ne_j8 (
    input wire [0:0] ck,
    input wire [255:0] f_s_ctl,
    input wire [2255:0] f_s_row,
    input wire [2263:0] f_s_wr,
    input wire [2047:0] f_su_NE,
    input wire [255:0] f_w_ctl,
    input wire [2255:0] f_w_row,
    input wire [2263:0] f_w_wr,
    input wire [511:0] iNE,
    output wire [581:0] qNE,
    input wire [0:0] rst,
    output wire [255:0] t_s_ctl,
    output wire [2255:0] t_s_row,
    output wire [2263:0] t_s_wr,
    output wire [2047:0] t_su_NE,
    output wire [255:0] t_w_ctl,
    output wire [2255:0] t_w_row,
    output wire [2263:0] t_w_wr,
    output wire [2067:0] xNE
);
    wire [2062:0] s2n; wire [1398:0] n2s;
    wire [1398:0] n2s_x = n2s;
    hfd_vm_ne_s u_s (.*, .n2s(n2s_x));
    hfd_vm_ne_n u_n (.*);
endmodule
