`timescale 1ns/1ps
module tb;
reg ck=0; always #5 ck=~ck;
reg rst=1;
reg [1818:0] f_hgi_cmdproc=0;
reg [273:0] f_hgi_vmr=0;
reg [71:0] f_sel_co=0;
reg [1:0] f_sel_ev=0;
reg [0:0] f_sel_qbr=0;
reg [611:0] f_sel_to=0;
wire [89:0] t_sel_fs; reg [89:0] drive_t_sel_fs=0; reg [89:0] hist_t_sel_fs[0:2];
wire [1047:0] t_sel_qb; reg [1047:0] drive_t_sel_qb=0; reg [1047:0] hist_t_sel_qb[0:2];
wire [344:0] t_sel_kin; reg [344:0] drive_t_sel_kin=0; reg [344:0] hist_t_sel_kin[0:2];
wire [0:0] t_sel_toc; reg [0:0] drive_t_sel_toc=0; reg [0:0] hist_t_sel_toc[0:2];
wire [0:0] t_sel_coc; reg [0:0] drive_t_sel_coc=0; reg [0:0] hist_t_sel_coc[0:2];
reg [1818:0] hist_f_hgi_cmdproc[0:2];
reg [273:0] hist_f_hgi_vmr[0:2];
reg [71:0] hist_f_sel_co[0:2];
reg [1:0] hist_f_sel_ev[0:2];
reg [0:0] hist_f_sel_qbr[0:2];
reg [611:0] hist_f_sel_to[0:2];
hfd_hgi_idx_native d (.ck(ck),.rst(rst),.f_hgi_cmdproc(f_hgi_cmdproc),.f_hgi_vmr(f_hgi_vmr),.f_sel_co(f_sel_co),.f_sel_ev(f_sel_ev),.f_sel_qbr(f_sel_qbr),.f_sel_to(f_sel_to),.t_sel_fs(t_sel_fs),.t_sel_qb(t_sel_qb),.t_sel_kin(t_sel_kin),.t_sel_toc(t_sel_toc),.t_sel_coc(t_sel_coc));
integer i,b; initial begin
force d.w_ix_sel_fs=drive_t_sel_fs;
force d.w_ix_sel_qb=drive_t_sel_qb;
force d.w_ix_sel_kin=drive_t_sel_kin;
force d.w_ix_sel_toc=drive_t_sel_toc;
force d.w_ix_sel_coc=drive_t_sel_coc;
for(i=0;i<400;i=i+1) begin @(negedge ck);
for(b=0;b<274;b=b+1) f_hgi_vmr[b]=$random;
for(b=0;b<72;b=b+1) f_sel_co[b]=$random;
for(b=0;b<2;b=b+1) f_sel_ev[b]=$random;
for(b=0;b<1;b=b+1) f_sel_qbr[b]=$random;
for(b=0;b<612;b=b+1) f_sel_to[b]=$random;
for(b=0;b<90;b=b+1) drive_t_sel_fs[b]=$random;
for(b=0;b<1048;b=b+1) drive_t_sel_qb[b]=$random;
for(b=0;b<345;b=b+1) drive_t_sel_kin[b]=$random;
for(b=0;b<1;b=b+1) drive_t_sel_toc[b]=$random;
for(b=0;b<1;b=b+1) drive_t_sel_coc[b]=$random;
@(posedge ck); #1;
if(i>=3 && t_sel_fs!==hist_t_sel_fs[1]) $fatal(1,"OUTPUT t_sel_fs cycle%0d",i);
if(i>=3 && t_sel_qb!==hist_t_sel_qb[1]) $fatal(1,"OUTPUT t_sel_qb cycle%0d",i);
if(i>=3 && t_sel_kin!==hist_t_sel_kin[1]) $fatal(1,"OUTPUT t_sel_kin cycle%0d",i);
if(i>=3 && t_sel_toc!==hist_t_sel_toc[1]) $fatal(1,"OUTPUT t_sel_toc cycle%0d",i);
if(i>=3 && t_sel_coc!==hist_t_sel_coc[1]) $fatal(1,"OUTPUT t_sel_coc cycle%0d",i);
if(i>=3 && d.i_f_hgi_cmdproc!==hist_f_hgi_cmdproc[1]) $fatal(1,"INPUT f_hgi_cmdproc cycle%0d",i);
if(i>=3 && d.i_f_hgi_vmr!==hist_f_hgi_vmr[1]) $fatal(1,"INPUT f_hgi_vmr cycle%0d",i);
if(i>=3 && d.w_ix_sel_co!==hist_f_sel_co[1]) $fatal(1,"INPUT f_sel_co cycle%0d",i);
if(i>=3 && d.w_ix_sel_ev!==hist_f_sel_ev[1]) $fatal(1,"INPUT f_sel_ev cycle%0d",i);
if(i>=3 && d.w_ix_sel_qbr!==hist_f_sel_qbr[1]) $fatal(1,"INPUT f_sel_qbr cycle%0d",i);
if(i>=3 && d.w_ix_sel_to!==hist_f_sel_to[1]) $fatal(1,"INPUT f_sel_to cycle%0d",i);
hist_f_hgi_cmdproc[2]=hist_f_hgi_cmdproc[1]; hist_f_hgi_cmdproc[1]=hist_f_hgi_cmdproc[0]; hist_f_hgi_cmdproc[0]=f_hgi_cmdproc;
hist_f_hgi_vmr[2]=hist_f_hgi_vmr[1]; hist_f_hgi_vmr[1]=hist_f_hgi_vmr[0]; hist_f_hgi_vmr[0]=f_hgi_vmr;
hist_f_sel_co[2]=hist_f_sel_co[1]; hist_f_sel_co[1]=hist_f_sel_co[0]; hist_f_sel_co[0]=f_sel_co;
hist_f_sel_ev[2]=hist_f_sel_ev[1]; hist_f_sel_ev[1]=hist_f_sel_ev[0]; hist_f_sel_ev[0]=f_sel_ev;
hist_f_sel_qbr[2]=hist_f_sel_qbr[1]; hist_f_sel_qbr[1]=hist_f_sel_qbr[0]; hist_f_sel_qbr[0]=f_sel_qbr;
hist_f_sel_to[2]=hist_f_sel_to[1]; hist_f_sel_to[1]=hist_f_sel_to[0]; hist_f_sel_to[0]=f_sel_to;
hist_t_sel_fs[2]=hist_t_sel_fs[1]; hist_t_sel_fs[1]=hist_t_sel_fs[0]; hist_t_sel_fs[0]=drive_t_sel_fs;
hist_t_sel_qb[2]=hist_t_sel_qb[1]; hist_t_sel_qb[1]=hist_t_sel_qb[0]; hist_t_sel_qb[0]=drive_t_sel_qb;
hist_t_sel_kin[2]=hist_t_sel_kin[1]; hist_t_sel_kin[1]=hist_t_sel_kin[0]; hist_t_sel_kin[0]=drive_t_sel_kin;
hist_t_sel_toc[2]=hist_t_sel_toc[1]; hist_t_sel_toc[1]=hist_t_sel_toc[0]; hist_t_sel_toc[0]=drive_t_sel_toc;
hist_t_sel_coc[2]=hist_t_sel_coc[1]; hist_t_sel_coc[1]=hist_t_sel_coc[0]; hist_t_sel_coc[0]=drive_t_sel_coc;
end $display("PASS native boundary transport 400 cycles 2172 bits three captures"); $finish; end endmodule
