"""Independent target-semantic reference implementations."""

from .evaluator import ReferenceError, evaluate_reference
from .formats import (
    DENSE_REDUCTION_BLOCK,
    ROUTED_REDUCTION_BLOCK,
    DecodedValue,
    NumericReferenceError,
    QuantizedActivationBlock,
    QuantizedBF16,
    QuantizedE4M3FN,
    binary32_ordered_dot,
    binary32_product_add,
    binary32_bits_to_bf16_rne,
    decode_bf16,
    decode_binary32,
    decode_e2m1,
    decode_e4m3fn,
    decode_e8m0,
    decode_mxfp4_block,
    decode_packed_e2m1,
    encode_binary32_rne,
    encode_e4m3fn_rne,
    fp8_fp8_block_dot,
    mxfp4_fp8_block_dot,
    quantize_bf16_activation_block,
)
from .indexing import (
    INT32_MAX,
    MODEL_SOURCE_SHA256,
    IndexMatrix,
    IndexReferenceError,
    IndexRow,
    IndexTensor,
    compressed_dense_indices,
    dspark_window_indices,
    window_indices,
)

__all__ = [
    "DENSE_REDUCTION_BLOCK",
    "INT32_MAX",
    "MODEL_SOURCE_SHA256",
    "ROUTED_REDUCTION_BLOCK",
    "DecodedValue",
    "IndexMatrix",
    "IndexReferenceError",
    "IndexRow",
    "IndexTensor",
    "NumericReferenceError",
    "QuantizedActivationBlock",
    "QuantizedBF16",
    "QuantizedE4M3FN",
    "ReferenceError",
    "binary32_ordered_dot",
    "binary32_product_add",
    "binary32_bits_to_bf16_rne",
    "compressed_dense_indices",
    "decode_bf16",
    "decode_binary32",
    "decode_e2m1",
    "decode_e4m3fn",
    "decode_e8m0",
    "decode_mxfp4_block",
    "decode_packed_e2m1",
    "dspark_window_indices",
    "encode_binary32_rne",
    "encode_e4m3fn_rne",
    "evaluate_reference",
    "fp8_fp8_block_dot",
    "mxfp4_fp8_block_dot",
    "quantize_bf16_activation_block",
    "window_indices",
]
