# generated by vm/vcut8/pinreg_credit_check.py: FF die-path hold credit (sender PINREG clk->Q 32.2 ps, wire 0)
# ONLY on input bits proven fed by a tap-clocked flop Q direct to a VM8 half pin and captured by flops only
# (lead ruling 2026-10-10, REVIEW_20261009.md).  Read after vclk_corner_true.sdc; FF session only.
if {[llength [get_libs -quiet *_FF_*]] && [llength [get_clocks -quiet vclk]]} {
  set ot_iom_n 0
  set ot_q [get_ports -quiet {f_e_row f_e_row[*]}]; set_input_delay -min 32.2 -clock vclk $ot_q; incr ot_iom_n [llength $ot_q]
  set ot_q [get_ports -quiet {f_e_wr f_e_wr[*]}]; set_input_delay -min 32.2 -clock vclk $ot_q; incr ot_iom_n [llength $ot_q]
  set ot_q [get_ports -quiet {f_n_row f_n_row[*]}]; set_input_delay -min 32.2 -clock vclk $ot_q; incr ot_iom_n [llength $ot_q]
  set ot_q [get_ports -quiet {w2e w2e[*]}]; set_input_delay -min 32.2 -clock vclk $ot_q; incr ot_iom_n [llength $ot_q]
  puts "OT_IOMIN vcut8 hfd_vm_sw_e: PINREG-proven clk->Q credit on $ot_iom_n input bits"
}
