# qfd_hub: multi-clock kit (jobs/mk_mc_kit.py); route over-constrained at 770 ps
create_clock -name ck -period 770 [get_ports {ck}]
create_clock -name fck0 -period 770 [get_ports {fck0}]
create_clock -name fck1 -period 770 [get_ports {fck1}]
create_clock -name fck2 -period 770 [get_ports {fck2}]
create_clock -name fck3 -period 770 [get_ports {fck3}]
set_clock_uncertainty -setup 60 [all_clocks]
set_clock_uncertainty -hold 25 [all_clocks]
# unrelated-clock crossings: one period minus the setup uncertainty, both directions; hold: non-negative
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks ck] -to [get_clocks fck0]
set_min_delay -ignore_clock_latency 0 -from [get_clocks ck] -to [get_clocks fck0]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks ck] -to [get_clocks fck1]
set_min_delay -ignore_clock_latency 0 -from [get_clocks ck] -to [get_clocks fck1]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks ck] -to [get_clocks fck2]
set_min_delay -ignore_clock_latency 0 -from [get_clocks ck] -to [get_clocks fck2]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks ck] -to [get_clocks fck3]
set_min_delay -ignore_clock_latency 0 -from [get_clocks ck] -to [get_clocks fck3]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck0] -to [get_clocks ck]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck0] -to [get_clocks ck]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck0] -to [get_clocks fck1]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck0] -to [get_clocks fck1]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck0] -to [get_clocks fck2]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck0] -to [get_clocks fck2]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck0] -to [get_clocks fck3]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck0] -to [get_clocks fck3]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck1] -to [get_clocks ck]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck1] -to [get_clocks ck]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck1] -to [get_clocks fck0]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck1] -to [get_clocks fck0]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck1] -to [get_clocks fck2]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck1] -to [get_clocks fck2]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck1] -to [get_clocks fck3]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck1] -to [get_clocks fck3]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck2] -to [get_clocks ck]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck2] -to [get_clocks ck]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck2] -to [get_clocks fck0]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck2] -to [get_clocks fck0]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck2] -to [get_clocks fck1]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck2] -to [get_clocks fck1]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck2] -to [get_clocks fck3]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck2] -to [get_clocks fck3]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck3] -to [get_clocks ck]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck3] -to [get_clocks ck]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck3] -to [get_clocks fck0]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck3] -to [get_clocks fck0]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck3] -to [get_clocks fck1]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck3] -to [get_clocks fck1]
set_max_delay -ignore_clock_latency 710.000 -from [get_clocks fck3] -to [get_clocks fck2]
set_min_delay -ignore_clock_latency 0 -from [get_clocks fck3] -to [get_clocks fck2]
set_input_delay 166.667 -clock ck [get_ports {x3_v x3_d[*] x3_tag[*] ar_cr}]
set_output_delay 166.667 -clock ck [get_ports {x3_cr ar_v ar_d[*] fault l0_o[*] l1_o[*] l2_o[*] l3_o[*]}]
set_input_delay 166.667 -clock fck0 [get_ports {l0_i[*]}]
set_input_delay 166.667 -clock fck1 [get_ports {l1_i[*]}]
set_input_delay 166.667 -clock fck2 [get_ports {l2_i[*]}]
set_input_delay 166.667 -clock fck3 [get_ports {l3_i[*]}]
set_false_path -from [get_ports {rst_n}]
set_max_fanout 32 [current_design]
set_load 3.898 [all_outputs]
set_max_transition 260 [current_design]
