# Full digital boot body, separately from the analog PLL. ASAP7 time unit: ps.
unset_input_delay [all_inputs]
unset_output_delay [all_outputs]
delete_clock [all_clocks]
create_clock -name aon -period 3000 [get_ports aon_clk]
create_clock -name stream -period 833.333333 [get_ports clk_stream]
create_clock -name serial -period 1111.111111 [get_ports clk_serial]
create_clock -name hbm -period 1024 [get_ports clk_hbm]
create_clock -name link -period 833.333333 [get_ports clk_link]
set_clock_uncertainty -setup 60 [all_clocks]
set_clock_uncertainty -hold 25 [all_clocks]
# Provisional AON entry obligations; no asynchronous exceptions and no reset
# recovery/removal waiver. Actual POR/lock/readiness providers remain unbound.
set_input_delay -min 25 -clock aon [get_ports {por_n power_good pll_lock phy_ready* links_ready* bist_done bist_pass fatal_error requalify}]
set_input_delay -max 100 -clock aon [get_ports {por_n power_good pll_lock phy_ready* links_ready* bist_done bist_pass fatal_error requalify}]
set_output_delay -min 25 -clock aon [get_ports {pll_reset_n ready state*}]
set_output_delay -max 100 -clock aon [get_ports {pll_reset_n ready state*}]
set_output_delay -min 25 -clock hbm [get_ports phy_reset_n*]
set_output_delay -max 100 -clock hbm [get_ports phy_reset_n*]
set_output_delay -min 25 -clock link [get_ports link_reset_n*]
set_output_delay -max 100 -clock link [get_ports link_reset_n*]
set_output_delay -min 25 -clock stream [get_ports {coll_reset_stream_n cmd_reset_stream_n}]
set_output_delay -max 100 -clock stream [get_ports {coll_reset_stream_n cmd_reset_stream_n}]
set_output_delay -min 25 -clock serial [get_ports {coll_reset_serial_n cmd_reset_serial_n}]
set_output_delay -max 100 -clock serial [get_ports {coll_reset_serial_n cmd_reset_serial_n}]
