`timescale 1ns/1ps
// Minimum finite source producers, separate from Zeno WFC/core/VM and DS-COMBINED.
module ot_dsrom_wfc_producer_context #(parameter integer ENABLE=0)(
 input wire  clk,
 input wire  rst_n,
 input wire  cold_fenced,
 input wire  cmd_v,
 input wire [1:0] cmd_op,
 input wire [9:0] cmd_user,
 input wire [20:0] cmd_pos,
 input wire [20:0] cmd_token,
 input wire [3:0] cmd_block,
 input wire [15:0] cmd_epoch,
 input wire [13:0] cmd_entry,
 output wire  cmd_ready,
 output wire [9:0] cfg_users,
 output wire [20:0] cfg_prompt_len,
 output wire [20:0] cfg_gen_len,
 output wire [15:0] stage_epoch,
 output wire [13:0] stage_entry,
 input wire  pr_re,
 input wire [9:0] pr_user,
 input wire [20:0] pr_pos,
 input wire [3:0] pr_blk,
 output wire [20:0] pr_q,
 output wire  pr_qk,
 output wire  active,
 output wire  initializing,
 output wire  cfg_fault,
 input wire  request_v,
 output wire  request_ready,
 input wire [46:0] request_identity,
 input wire [20:0] request_token,
 input wire [13:0] request_entry,
 input wire [3:0] command_v,
 output wire [3:0] command_ready,
 input wire [187:0] command_identity,
 input wire [83:0] command_token,
 input wire [27:0] command_home,
 input wire [55:0] command_entry,
 input wire [55:0] command_pc,
 input wire [15:0] command_unit,
 input wire [3:0] retire_v,
 input wire [187:0] retire_identity,
 input wire [27:0] retire_home,
 input wire [55:0] retire_entry,
 input wire [23:0] retire_visibility,
 input wire [3:0] retire_quiet,
 input wire [3:0] retire_capture_drained,
 input wire [3:0] retire_fault,
 input wire [3:0] fence_v,
 input wire [187:0] fence_identity,
 input wire [19:0] fence_visibility,
 input wire  result_v,
 input wire [46:0] result_identity,
 input wire [20:0] result_token,
 input wire [31:0] result_value,
 input wire  whole_stage_accepted,
 output wire  whole_stage_v,
 output wire [46:0] whole_stage_identity,
 output wire [20:0] whole_stage_next_token,
 output wire [31:0] whole_stage_value,
 output wire  token_result_valid,
 output wire  stage_handoff,
 output wire  pending,
 output wire  whole_fault
);
ot_dsrom_wfc_cfg_prompt #(.ENABLE(ENABLE)) u_cfg (
 .clk(clk),
 .rst_n(rst_n),
 .cold_fenced(cold_fenced),
 .cmd_v(cmd_v),
 .cmd_op(cmd_op),
 .cmd_user(cmd_user),
 .cmd_pos(cmd_pos),
 .cmd_token(cmd_token),
 .cmd_block(cmd_block),
 .cmd_epoch(cmd_epoch),
 .cmd_entry(cmd_entry),
 .cmd_ready(cmd_ready),
 .cfg_users(cfg_users),
 .cfg_prompt_len(cfg_prompt_len),
 .cfg_gen_len(cfg_gen_len),
 .stage_epoch(stage_epoch),
 .stage_entry(stage_entry),
 .pr_re(pr_re),
 .pr_user(pr_user),
 .pr_pos(pr_pos),
 .pr_blk(pr_blk),
 .pr_q(pr_q),
 .pr_qk(pr_qk),
 .active(active),
 .initializing(initializing),
 .fault(cfg_fault)
);
ot_dsrom_wfc_whole_stage #(.ENABLE(ENABLE)) u_whole (
 .clk(clk),
 .rst_n(rst_n),
 .request_v(request_v),
 .request_ready(request_ready),
 .request_identity(request_identity),
 .request_token(request_token),
 .request_entry(request_entry),
 .configured_epoch(stage_epoch),
 .command_v(command_v),
 .command_ready(command_ready),
 .command_identity(command_identity),
 .command_token(command_token),
 .command_home(command_home),
 .command_entry(command_entry),
 .command_pc(command_pc),
 .command_unit(command_unit),
 .retire_v(retire_v),
 .retire_identity(retire_identity),
 .retire_home(retire_home),
 .retire_entry(retire_entry),
 .retire_visibility(retire_visibility),
 .retire_quiet(retire_quiet),
 .retire_capture_drained(retire_capture_drained),
 .retire_fault(retire_fault),
 .fence_v(fence_v),
 .fence_identity(fence_identity),
 .fence_visibility(fence_visibility),
 .result_v(result_v),
 .result_identity(result_identity),
 .result_token(result_token),
 .result_value(result_value),
 .whole_stage_accepted(whole_stage_accepted),
 .whole_stage_v(whole_stage_v),
 .whole_stage_identity(whole_stage_identity),
 .whole_stage_next_token(whole_stage_next_token),
 .whole_stage_value(whole_stage_value),
 .token_result_valid(token_result_valid),
 .stage_handoff(stage_handoff),
 .pending(pending),
 .fault(whole_fault)
);
endmodule
