// GENERATED by tools/hdc_isa_v41_fuse.py -- do not edit.
// Offsets of the operator-fusion fields (appended after every field of both profiles).
// Included in ot_hdc_core_v41x_kr after ot_hdc_isa_v41_profiles.svh; FULL_SHAPE selects the profile.
localparam integer O_KR_W = FULL_SHAPE ? 1961 : 1489;
localparam integer W_KR_W = 1;
localparam integer O_KR_WB = FULL_SHAPE ? 1962 : 1490;
localparam integer W_KR_WB = 6;
localparam integer O_KR_R = FULL_SHAPE ? 1968 : 1496;
localparam integer W_KR_R = 4;
localparam integer O_KR_RB = FULL_SHAPE ? 1972 : 1500;
localparam integer W_KR_RB = 6;
localparam integer O_KR_LW = FULL_SHAPE ? 1978 : 1506;
localparam integer W_KR_LW = 1;
localparam integer O_XKR = FULL_SHAPE ? 1979 : 1507;
localparam integer W_XKR = 1;
localparam integer O_XKR_WB = FULL_SHAPE ? 1980 : 1508;
localparam integer W_XKR_WB = 6;
localparam integer O_XKR_LW = FULL_SHAPE ? 1986 : 1514;
localparam integer W_XKR_LW = 1;
localparam integer O_XKR_MAP = FULL_SHAPE ? 1987 : 1515;
localparam integer W_XKR_MAP = 2;
localparam integer O_XKR_EPI = FULL_SHAPE ? 1989 : 1517;
localparam integer W_XKR_EPI = 4;
