`timescale 1ns/1ps
// Wire-only actual controller + native-consumer/drain composition. No fake endpoint authorities.
module ot_hbm_accel_kv_native_lifecycle #(parameter ENABLE=0)(
 input wire  clk,
 input wire  por_n,
 input wire  run_enable,
 input wire  quiesce,
 input wire  cmd_valid,
 output wire  cmd_ready,
 input wire [2:0] cmd_op,
 input wire [63:0] cmd_identity,
 input wire [19:0] cmd_key,
 input wire [63:0] cmd_producer,
 input wire [63:0] cmd_sequence,
 input wire [10:0] cmd_PC,
 input wire  cmd_consumer,
 input wire [3:0] cmd_stage_beat,
 input wire [9:0] cmd_stage_base,
 input wire [4:0] cmd_stage_SM,
 input wire [511:0] cmd_stage_data,
 input wire [33:0] cmd_K_base,
 input wire [33:0] cmd_V_base,
 output wire  rsp_valid,
 input wire  rsp_ready,
 output wire  rsp_fault,
 output wire [2:0] rsp_op,
 output wire [63:0] rsp_identity,
 output wire [19:0] rsp_key,
 output wire [63:0] rsp_sequence,
 output wire [10:0] rsp_PC,
 output wire [511:0] rsp_capture,
 output wire [63:0] rsp_producer,
 output wire  rsp_consumer,
 output wire [3:0] rsp_stage_beat,
 output wire  shared_valid,
 output wire  shared_write,
 input wire  shared_ready,
 output wire [9:0] shared_addr,
 output wire [4:0] shared_SM,
 output wire  shared_rank,
 output wire [511:0] shared_wdata,
 input wire  shared_done,
 output wire  shared_done_ready,
 input wire [511:0] shared_rdata,
 output wire  commit_valid,
 input wire  commit_ready,
 output wire [63:0] writer_identity,
 output wire [19:0] writer_key,
 output wire [9:0] writer_stage_base,
 output wire [4:0] writer_stage_SM,
 output wire [33:0] writer_K_base,
 output wire [33:0] writer_V_base,
 input wire  payload_valid,
 output wire  payload_ready,
 input wire [63:0] payload_identity,
 input wire [19:0] payload_key,
 input wire [8:0] payload_sector,
 input wire [33:0] payload_source_addr,
 input wire  payload_visible,
 input wire  payload_reverse,
 input wire  payload_write,
 input wire [255:0] payload_rdata,
 output wire  payload_req_valid,
 input wire  payload_req_ready,
 output wire  payload_req_write,
 output wire [8:0] payload_req_sector,
 output wire [33:0] payload_req_source_addr,
 output wire [255:0] payload_req_data,
 output wire  payload_req_rmw,
 output wire  payload_req_rmw_last,
 input wire  metadata_valid,
 output wire  metadata_ready,
 input wire [63:0] metadata_identity,
 input wire [19:0] metadata_key,
 input wire  metadata_record,
 input wire  reader_metadata_valid,
 output wire  reader_metadata_ready,
 input wire [63:0] reader_metadata_identity,
 input wire [19:0] reader_metadata_key,
 input wire  reader_metadata_stage,
 input wire  hydrate_valid,
 output wire  hydrate_ready,
 input wire [19:0] hydrate_key,
 input wire [63:0] hydrate_producer,
 output wire  fault,
 output wire  writer_retained,
 output wire  idle,
 input wire  rst_n,
 input wire  native_issue_valid,
 output wire  native_issue_ready,
 input wire [229:0] native_issue_tuple,
 input wire  native_complete_valid,
 output wire  native_complete_ready,
 input wire [229:0] native_complete_tuple,
 input wire  native_reverse_valid,
 output wire  native_reverse_ready,
 input wire [229:0] native_reverse_tuple,
 output wire [7:0] cohort_quiesce,
 output wire [7:0] cohort_req_valid,
 input wire [7:0] cohort_req_ready,
 output wire [63:0] cohort_identity,
 output wire [19:0] cohort_key,
 input wire [7:0] cohort_rsp_valid,
 output wire [7:0] cohort_rsp_ready,
 input wire [671:0] cohort_rsp_tuple,
 input wire [7:0] cohort_rsp_empty,
 output wire  native_retained,
 output wire  drain_retained,
 input wire  endpoint_fault
);
 wire controller_fault,bridge_fault;
 wire  consumer_accepted;
 wire [63:0] consumer_identity;
 wire [19:0] consumer_key;
 wire  consumer_ready;
 wire  consumer_reverse;
 wire  consumer_stage;
 wire  consumer_valid;
 wire [7:0] drain_done_allcopies;
 wire [63:0] drain_done_identity;
 wire [19:0] drain_done_key;
 wire  drain_done_ready;
 wire  drain_done_valid;
 wire [63:0] drain_identity;
 wire [19:0] drain_key;
 wire  drain_ready;
 wire  drain_valid;
 assign fault=controller_fault||bridge_fault;
 ot_hbm_accel_kv_lifecycle #(.ENABLE(ENABLE)) lifecycle(
  .clk(clk),
  .por_n(por_n),
  .run_enable(run_enable&&!bridge_fault),
  .quiesce(quiesce),
  .cmd_valid(cmd_valid),
  .cmd_ready(cmd_ready),
  .cmd_op(cmd_op),
  .cmd_identity(cmd_identity),
  .cmd_key(cmd_key),
  .cmd_producer(cmd_producer),
  .cmd_sequence(cmd_sequence),
  .cmd_PC(cmd_PC),
  .cmd_consumer(cmd_consumer),
  .cmd_stage_beat(cmd_stage_beat),
  .cmd_stage_base(cmd_stage_base),
  .cmd_stage_SM(cmd_stage_SM),
  .cmd_stage_data(cmd_stage_data),
  .cmd_K_base(cmd_K_base),
  .cmd_V_base(cmd_V_base),
  .rsp_valid(rsp_valid),
  .rsp_ready(rsp_ready),
  .rsp_fault(rsp_fault),
  .rsp_op(rsp_op),
  .rsp_identity(rsp_identity),
  .rsp_key(rsp_key),
  .rsp_sequence(rsp_sequence),
  .rsp_PC(rsp_PC),
  .rsp_capture(rsp_capture),
  .rsp_producer(rsp_producer),
  .rsp_consumer(rsp_consumer),
  .rsp_stage_beat(rsp_stage_beat),
  .shared_valid(shared_valid),
  .shared_write(shared_write),
  .shared_ready(shared_ready),
  .shared_addr(shared_addr),
  .shared_SM(shared_SM),
  .shared_rank(shared_rank),
  .shared_wdata(shared_wdata),
  .shared_done(shared_done),
  .shared_done_ready(shared_done_ready),
  .shared_rdata(shared_rdata),
  .commit_valid(commit_valid),
  .commit_ready(commit_ready),
  .writer_identity(writer_identity),
  .writer_key(writer_key),
  .writer_stage_base(writer_stage_base),
  .writer_stage_SM(writer_stage_SM),
  .writer_K_base(writer_K_base),
  .writer_V_base(writer_V_base),
  .payload_valid(payload_valid),
  .payload_ready(payload_ready),
  .payload_identity(payload_identity),
  .payload_key(payload_key),
  .payload_sector(payload_sector),
  .payload_source_addr(payload_source_addr),
  .payload_visible(payload_visible),
  .payload_reverse(payload_reverse),
  .payload_write(payload_write),
  .payload_rdata(payload_rdata),
  .payload_req_valid(payload_req_valid),
  .payload_req_ready(payload_req_ready),
  .payload_req_write(payload_req_write),
  .payload_req_sector(payload_req_sector),
  .payload_req_source_addr(payload_req_source_addr),
  .payload_req_data(payload_req_data),
  .payload_req_rmw(payload_req_rmw),
  .payload_req_rmw_last(payload_req_rmw_last),
  .metadata_valid(metadata_valid),
  .metadata_ready(metadata_ready),
  .metadata_identity(metadata_identity),
  .metadata_key(metadata_key),
  .metadata_record(metadata_record),
  .consumer_valid(consumer_valid),
  .consumer_ready(consumer_ready),
  .consumer_identity(consumer_identity),
  .consumer_key(consumer_key),
  .consumer_stage(consumer_stage),
  .consumer_accepted(consumer_accepted),
  .consumer_reverse(consumer_reverse),
  .reader_metadata_valid(reader_metadata_valid),
  .reader_metadata_ready(reader_metadata_ready),
  .reader_metadata_identity(reader_metadata_identity),
  .reader_metadata_key(reader_metadata_key),
  .reader_metadata_stage(reader_metadata_stage),
  .hydrate_valid(hydrate_valid),
  .hydrate_ready(hydrate_ready),
  .hydrate_key(hydrate_key),
  .hydrate_producer(hydrate_producer),
  .drain_valid(drain_valid),
  .drain_ready(drain_ready),
  .drain_identity(drain_identity),
  .drain_key(drain_key),
  .drain_done_valid(drain_done_valid),
  .drain_done_ready(drain_done_ready),
  .drain_done_identity(drain_done_identity),
  .drain_done_key(drain_done_key),
  .drain_done_allcopies(drain_done_allcopies),
  .fault(controller_fault),
  .writer_retained(writer_retained),
  .idle(idle)
 );
 ot_gpu_qwen_native_consumer_drain #(.ENABLE(ENABLE)) consumer_drain(
  .clk(clk),
  .por_n(por_n),
  .rst_n(rst_n),
  .run_enable(run_enable),
  .endpoint_fault(endpoint_fault||controller_fault),
  .native_issue_valid(native_issue_valid),
  .native_issue_ready(native_issue_ready),
  .native_issue_tuple(native_issue_tuple),
  .native_complete_valid(native_complete_valid),
  .native_complete_ready(native_complete_ready),
  .native_complete_tuple(native_complete_tuple),
  .native_reverse_valid(native_reverse_valid),
  .native_reverse_ready(native_reverse_ready),
  .native_reverse_tuple(native_reverse_tuple),
  .consumer_valid(consumer_valid),
  .consumer_ready(consumer_ready),
  .consumer_identity(consumer_identity),
  .consumer_key(consumer_key),
  .consumer_stage(consumer_stage),
  .consumer_accepted(consumer_accepted),
  .consumer_reverse(consumer_reverse),
  .drain_valid(drain_valid),
  .drain_ready(drain_ready),
  .drain_identity(drain_identity),
  .drain_key(drain_key),
  .cohort_quiesce(cohort_quiesce),
  .cohort_req_valid(cohort_req_valid),
  .cohort_req_ready(cohort_req_ready),
  .cohort_identity(cohort_identity),
  .cohort_key(cohort_key),
  .cohort_rsp_valid(cohort_rsp_valid),
  .cohort_rsp_ready(cohort_rsp_ready),
  .cohort_rsp_tuple(cohort_rsp_tuple),
  .cohort_rsp_empty(cohort_rsp_empty),
  .drain_done_valid(drain_done_valid),
  .drain_done_ready(drain_done_ready),
  .drain_done_identity(drain_done_identity),
  .drain_done_key(drain_done_key),
  .drain_done_allcopies(drain_done_allcopies),
  .native_retained(native_retained),
  .drain_retained(drain_retained),
  .fault(bridge_fault)
 );
endmodule
