# Qwen die master hgi_idx_score_tap_lane12: sign-off at 833.333 ps (generated by jobs/signoff_sdc.py)
create_clock -name core_clk -period 833.333 [get_ports clk]
set_propagated_clock [all_clocks]
set_clock_uncertainty -setup 60 [all_clocks]
set_clock_uncertainty -hold 25 [all_clocks]
set ::env(OT_IO_SKEW) 90
set ::env(OT_IO_HOLD_SKEW) 50
set ::env(OT_REF_GLOB) {*_q*}
set ::env(OT_IO_INTER) {*}
set ::env(OT_IO_SKEW_INTER) 150
# Die-context boundary (post-CTS only; OpenROAD 26Q3 crashes on -reference_pin, so it is applied numerically):
# L = propagated clock arrival at a boundary register of this block (OT_REF_GLOB, default *go_q*), measured here.
#   input  max = 166.667 + L_max + skew      min = L_min - hold_skew
#   output max = 166.667 - L_max + skew      min = -L_min - hold_skew
# skew = OT_IO_SKEW (90, same clock region) or OT_IO_SKEW_INTER (150) on the OT_IO_INTER port globs; hold_skew =
# OT_IO_HOLD_SKEW (50).  Margin rule 2026-10-06 (+ clarification: 150 ps only across clock regions).
set ot_sk [expr {[info exists ::env(OT_IO_SKEW)] ? $::env(OT_IO_SKEW) : 90}]
set ot_hk [expr {[info exists ::env(OT_IO_HOLD_SKEW)] ? $::env(OT_IO_HOLD_SKEW) : 50}]
set ot_glob [expr {[info exists ::env(OT_REF_GLOB)] ? $::env(OT_REF_GLOB) : "*go_q*"}]
unset_input_delay [all_inputs]
unset_output_delay [all_outputs]
# PINFLOP-REF (drive-0849 2026-10-10, coordinator class-1 fix: 39 hold floods at CTS/GRT): the IO reference register used
# to be the FIRST register of the design / clock (an arbitrary tree position), so the input min delay sat far from the
# capture flops' clock and CTS / GRT hold repair flooded (ehash / core18 / kvwq closed only after naming the input pin
# flops by hand).  When the block has a REGISTERED input boundary -- input ports reaching register D pins directly or
# through <= 2 buffers ("pin flops") -- the reference is the pin flop of MEDIAN clock arrival.  No pin flops -> the
# previous reference.  An explicit matching OT_REF_GLOB keeps priority; OT_REF_PINFLOP=0 opts out.
proc ot_pf_clks {ports} {
  set seen [dict create]; set out {}
  foreach port $ports {
    set nets [get_nets -quiet [get_full_name $port]]
    for {set hop 0} {$hop < 3 && [llength $nets]} {incr hop} {
      set next {}
      foreach n $nets {
        foreach pin [get_pins -quiet -of_objects $n] {
          if {[string first / [get_full_name $pin]] < 0} { continue }
          if {[get_property $pin direction] ne "input"} { continue }
          set c [get_cells -quiet -of_objects $pin]
          if {![llength $c]} { continue }
          set fn [get_full_name $c]
          set ck [get_pins -quiet "$fn/CLK"]
          if {[llength $ck]} {
            if {[get_property $pin lib_pin_name] ne "CLK" && ![dict exists $seen $fn]} { dict set seen $fn 1; lappend out $ck }
          } elseif {[regexp {^(BUF|HB)} [get_property $c ref_name]]} {
            foreach op [get_pins -quiet -of_objects $c] {
              if {[get_property $op direction] eq "output"} { lappend next [get_nets -quiet -of_objects $op] }
            }
          }
        }
      }
      set nets $next
    }
  }
  return $out
}
proc ot_pf_ref {ports} {
  if {[info exists ::env(OT_REF_PINFLOP)] && $::env(OT_REF_PINFLOP) eq "0"} { return {} }
  catch {sta::worst_slack_cmd max}   ;# arrivals need an updated timing graph (as the QDM reference reads below)
  set pf {}
  foreach p [ot_pf_clks $ports] {
    set a [get_property $p arrival_max_rise]
    if {[string is double -strict $a]} { lappend pf [list $a $p] }
  }
  if {![llength $pf]} { return {} }
  set pf [lsort -real -index 0 $pf]
  set m [lindex $pf [expr {[llength $pf] / 2}]]
  puts "QDM PINFLOP reference: [llength $pf] input pin flops, median arrival [lindex $m 0] (range [lindex [lindex $pf 0] 0] .. [lindex [lindex $pf end] 0])"
  return [lindex $m 1]
}
# GLOB-MEDIAN (drive-0849 2026-10-10): a matching REFGLOB names a register GROUP (usually the input pin flops); the
# reference is its member of median clock arrival, not the first match (an arbitrary tree position).
proc ot_pf_median {pins label} {
  catch {sta::worst_slack_cmd max}
  set pf {}
  foreach p $pins {
    set a [get_property $p arrival_max_rise]
    if {[string is double -strict $a]} { lappend pf [list $a $p] }
  }
  if {![llength $pf]} { return {} }
  set pf [lsort -real -index 0 $pf]
  set m [lindex $pf [expr {[llength $pf] / 2}]]
  puts "QDM $label reference: [llength $pf] registers, median arrival [lindex $m 0] (range [lindex [lindex $pf 0] 0] .. [lindex [lindex $pf end] 0])"
  return [lindex $m 1]
}
set qdm_ref {}
if {$ot_glob ne "" && $ot_glob ne "*"} {   ;# "*" names no reference: PINFLOP default
  set ot_gm {}
  foreach c [get_cells -quiet -hierarchical $ot_glob] {
    set p [get_pins -quiet "[get_full_name $c]/CLK"]
    if {[llength $p]} { lappend ot_gm $p }
  }
  if {[llength $ot_gm]} {
    if {[info exists ::env(OT_REF_PINFLOP)] && $::env(OT_REF_PINFLOP) eq "0"} { set qdm_ref [lindex $ot_gm 0] } else {
      set qdm_ref [ot_pf_median $ot_gm "REFGLOB $ot_glob"] }
  }
}
if {[llength $qdm_ref] == 0} { set qdm_ref [ot_pf_ref [all_inputs -no_clocks]] }
if {[llength $qdm_ref] == 0} { set qdm_ref [lindex [all_registers -clock_pins] 0] }
set qdm_w [sta::worst_slack_cmd max]
set qdm_lmax [get_property $qdm_ref arrival_max_rise]
set qdm_lmin [get_property $qdm_ref arrival_min_rise]
puts "QDM reference pin [get_full_name $qdm_ref] clock arrival max $qdm_lmax min $qdm_lmin skew $ot_sk hold $ot_hk"
set_input_delay [expr 166.667 + $qdm_lmax + $ot_sk] -max -clock core_clk [all_inputs -no_clocks]
# RULE H1 (flow-hold 2026-10-07): a die link's hold budget (die clock-arrival term OT_IO_HOLD_SKEW + hold uncertainty) is
# carried ONCE, by the SENDER's output min delay below.  The receiver's input check keeps only its own tree offset from the
# reference register (+ hold time + uncertainty): input min = L_min - OT_IO_IN_HOLD_SKEW (default 0).  Counting the 50 ps on
# both sides demanded ~150 ps of hold delay per link for a 50 ps skew (the FF -30..-45 ps input band of every master).
set ot_hki [expr {[info exists ::env(OT_IO_IN_HOLD_SKEW)] ? $::env(OT_IO_IN_HOLD_SKEW) : 0}]
set_input_delay [expr $qdm_lmin - $ot_hki] -min -clock core_clk [all_inputs -no_clocks]
set_output_delay [expr 166.667 - $qdm_lmax + $ot_sk] -max -clock core_clk [all_outputs]
set_output_delay [expr 0 - $qdm_lmin - $ot_hk] -min -clock core_clk [all_outputs]
if {[info exists ::env(OT_IO_INTER)] && $::env(OT_IO_INTER) ne ""} {
  set ot_ski [expr {[info exists ::env(OT_IO_SKEW_INTER)] ? $::env(OT_IO_SKEW_INTER) : 150}]
  set ot_ii {}; set ot_io {}
  foreach g [split $::env(OT_IO_INTER) ","] {
    foreach p [get_ports -quiet $g] { if {[get_property $p direction] eq "input"} { lappend ot_ii $p } else { lappend ot_io $p } }
  }
  if {[llength $ot_ii]} { set_input_delay [expr 166.667 + $qdm_lmax + $ot_ski] -max -clock core_clk $ot_ii }
  if {[llength $ot_io]} { set_output_delay [expr 166.667 - $qdm_lmax + $ot_ski] -max -clock core_clk $ot_io }
  puts "OT_IO_INTER [llength $ot_ii] inputs [llength $ot_io] outputs at $ot_ski ps"
}
if {[llength [get_ports -quiet tile_id*]]} { set_false_path -from [get_ports tile_id*] }

