// Default-off real native payload publication followed by physical ACK/W6 source.
module ot_gpu_pc40_native_connector #(parameter bit ENABLE=0)(
 input wire clk,por_n,rst_n,
 input wire publish_valid,output wire publish_ready,input wire[4095:0]publish_data,
 input wire[45:0]publish_owner46,input wire[63:0]publish_native_tag,publish_native_generation,
 input wire source_lease_reserved,workspace_reserved,issuer_namespace_reserved,
 input wire source_release_valid,input wire[54:0]source_release_identity,
 output wire source_release_ready,source_lease_live,workspace_lease_live,source_published,
 input wire issuer_binding_valid,visibility_enable,
 output wire rd_valid,input wire rd_ready,output wire[8:0]rd_a,rd_b,
 input wire rsp_valid,input wire[4095:0]rsp_a,rsp_b,output wire rsp_ready,
 output wire wr_valid,input wire wr_ready,output wire[8:0]wr_addr,output wire[4095:0]wr_data,
 input wire ack_valid,output wire ack_ready,
 input wire[45:0]ack_owner,input wire[8:0]ack_slot,input wire ack_identity_fault,
 output wire[45:0]wr_owner,output wire ack_integration_fault,
 output wire visible_valid,output wire[54:0]visible_identity,
 output wire result_valid,input wire result_ready,output wire[4095:0]result,
 output wire consumer_accepted,output wire[54:0]consumer_identity,
 input wire child_reverse_valid,input wire[54:0]child_reverse_identity,output wire child_reverse_ready,
 input wire parent_reverse_valid,input wire[54:0]parent_reverse_identity,output wire parent_reverse_ready,
 input wire reverse_CDC_valid,input wire[54:0]reverse_CDC_identity,output wire reverse_CDC_ready,
 output wire drain_req_valid,output wire[54:0]drain_req_identity,output wire drain_req_has_owner,drain_req_reset_scope,
 input wire drain_req_ready,drain_rsp_valid,input wire[54:0]drain_rsp_identity,
 input wire drain_rsp_has_owner,drain_rsp_reset_scope,input wire[8:0]alldrain_live,output wire drain_rsp_ready,
 output wire done_valid,input wire done_ready,output wire[63:0]done_native_tag,done_native_generation,
 input wire rearm_valid,admission_stop,issuer_allcopy_fenced,output wire rearm_ready,exclusive_lease,fault
);
 wire c_req_valid,c_req_ready,c_wr_valid,c_wr_ready,c_ack_valid,c_ack_ready,c_ack_fault,c_fault,c_ack_integration_fault,c_done_valid;
 wire c_rd_valid,c_rsp_ready,ingress_fault,c_exclusive_lease,c_rearm_ready,c_result_valid,c_visible_valid;
 wire[45:0]c_owner,c_wr_owner,c_ack_owner;wire[63:0]c_tag,c_gen;
 wire[8:0]c_wr_slot,c_ack_slot;wire[4095:0]c_wr_data;
 assign fault=c_fault||ingress_fault;
 assign ack_integration_fault=c_ack_integration_fault||ingress_fault;
 assign rd_valid=c_rd_valid&&!ingress_fault;assign rsp_ready=c_rsp_ready&&!ingress_fault;
 assign done_valid=c_done_valid&&!ingress_fault;
 assign exclusive_lease=workspace_lease_live||c_exclusive_lease;
 assign rearm_ready=c_rearm_ready&&!ingress_fault;
 assign result_valid=c_result_valid&&!ingress_fault;
 assign visible_valid=c_visible_valid&&!ingress_fault;
 ot_gpu_pc40_native_ingress #(.ENABLE(ENABLE)) ingress(
 .clk(clk),.por_n(por_n),.rst_n(rst_n),.publish_valid(publish_valid),.publish_ready(publish_ready),
 .publish_data(publish_data),.publish_owner46(publish_owner46),.publish_native_tag(publish_native_tag),.publish_native_generation(publish_native_generation),
 .source_lease_reserved(source_lease_reserved),.workspace_reserved(workspace_reserved),.issuer_namespace_reserved(issuer_namespace_reserved),.admission_stop(admission_stop),
 .c_req_valid(c_req_valid),.c_req_ready(c_req_ready),.c_owner46(c_owner),.c_native_tag(c_tag),.c_native_generation(c_gen),
 .c_wr_valid(c_wr_valid),.c_wr_ready(c_wr_ready),.c_wr_slot(c_wr_slot),.c_wr_data(c_wr_data),.c_wr_owner(c_wr_owner),
 .c_ack_valid(c_ack_valid),.c_ack_ready(c_ack_ready),.c_ack_owner(c_ack_owner),.c_ack_slot(c_ack_slot),.c_ack_fault(c_ack_fault),
 .rf_wr_valid(wr_valid),.rf_wr_ready(wr_ready),.rf_wr_slot(wr_addr),.rf_wr_data(wr_data),.rf_wr_owner(wr_owner),
 .rf_ack_valid(ack_valid),.rf_ack_ready(ack_ready),.rf_ack_owner(ack_owner),.rf_ack_slot(ack_slot),.rf_ack_fault(ack_identity_fault),
 .c_done_valid(c_done_valid),.c_done_ready(done_ready&&!ingress_fault),.c_fault(c_fault),
 .source_release_valid(source_release_valid),.source_release_identity(source_release_identity),.source_release_ready(source_release_ready),
 .source_lease_live(source_lease_live),.workspace_lease_live(workspace_lease_live),.source_published(source_published),.fault(ingress_fault));
 ot_gpu_pc40_physical_ack_source_r4 #(.ENABLE(ENABLE)) source(
.clk(clk),
.por_n(por_n),
.rst_n(rst_n),
.req_valid(c_req_valid),
.req_ready(c_req_ready),
.req_owner46(c_owner),
.req_native_tag(c_tag),
.req_native_generation(c_gen),
.issuer_binding_valid((issuer_binding_valid&&!ingress_fault)),
.visibility_enable(visibility_enable),
.rd_valid(c_rd_valid),
.rd_ready((rd_ready&&!ingress_fault)),
.rd_a(rd_a),
.rd_b(rd_b),
.rsp_valid((rsp_valid&&!ingress_fault)),
.rsp_a(rsp_a),
.rsp_b(rsp_b),
.rsp_ready(c_rsp_ready),
.wr_valid(c_wr_valid),
.wr_ready(c_wr_ready),
.wr_addr(c_wr_slot),
.wr_data(c_wr_data),
.ack_valid(c_ack_valid),
.ack_ready(c_ack_ready),
.ack_owner(c_ack_owner),
.ack_slot(c_ack_slot),
.ack_identity_fault(c_ack_fault),
.wr_owner(c_wr_owner),
.ack_integration_fault(c_ack_integration_fault),
.visible_valid(c_visible_valid),
.visible_identity(visible_identity),
.result_valid(c_result_valid),
.result_ready((result_ready&&!ingress_fault)),
.result(result),
.consumer_accepted(consumer_accepted),
.consumer_identity(consumer_identity),
.child_reverse_valid(child_reverse_valid&&!ingress_fault),
.child_reverse_identity(child_reverse_identity),
.child_reverse_ready(child_reverse_ready),
.parent_reverse_valid(parent_reverse_valid&&!ingress_fault),
.parent_reverse_identity(parent_reverse_identity),
.parent_reverse_ready(parent_reverse_ready),
.reverse_CDC_valid(reverse_CDC_valid&&!ingress_fault),
.reverse_CDC_identity(reverse_CDC_identity),
.reverse_CDC_ready(reverse_CDC_ready),
.drain_req_valid(drain_req_valid),
.drain_req_identity(drain_req_identity),
.drain_req_has_owner(drain_req_has_owner),
.drain_req_reset_scope(drain_req_reset_scope),
.drain_req_ready(drain_req_ready),
.drain_rsp_valid(drain_rsp_valid),
.drain_rsp_identity(drain_rsp_identity),
.drain_rsp_has_owner(drain_rsp_has_owner),
.drain_rsp_reset_scope(drain_rsp_reset_scope),
.alldrain_live(alldrain_live),
.drain_rsp_ready(drain_rsp_ready),
.done_valid(c_done_valid),
.done_ready((done_ready&&!ingress_fault)),
.done_native_tag(done_native_tag),
.done_native_generation(done_native_generation),
.rearm_valid(rearm_valid),
.admission_stop((admission_stop||ingress_fault)),
.issuer_allcopy_fenced(issuer_allcopy_fenced),
.rearm_ready(c_rearm_ready),
.exclusive_lease(c_exclusive_lease),
.fault(c_fault)
 );
endmodule
