`timescale 1ns/1ps
// Actual per-die ND1 loader+checked37 formatter+shared-stack movement parent.
// Cold POR and actual owner/provider ports required. Default-off; no private
// controllers, host memcpy, synthetic grants or changed engine/core clock.
module ot_hbm_accel_die_host_join #(parameter integer ENABLE=0,LOCAL_DIE=0,RANK_LIMIT=96)(
 input wire clk_host,rst_host_n,clk_mem,rst_mem_n,
 input wire s_awvalid,output wire s_awready,input wire[11:0] s_awaddr,
 input wire s_wvalid,output wire s_wready,input wire[31:0] s_wdata,input wire[3:0] s_wstrb,
 output wire s_bvalid,input wire s_bready,input wire s_arvalid,output wire s_arready,input wire[11:0] s_araddr,
 output wire s_rvalid,input wire s_rready,output wire[31:0] s_rdata,
 output wire h_awvalid,input wire h_awready,output wire[11:0] h_awaddr,
 output wire h_wvalid,input wire h_wready,output wire[31:0] h_wdata,output wire[3:0] h_wstrb,
 input wire h_bvalid,output wire h_bready,output wire h_arvalid,input wire h_arready,output wire[11:0] h_araddr,
 input wire h_rvalid,output wire h_rready,input wire[31:0] h_rdata,
 input wire h_dma_arvalid,output wire h_dma_arready,input wire[63:0] h_dma_araddr,
 output wire h_dma_rvalid,input wire h_dma_rready,output wire[63:0] h_dma_rdata,output wire[1:0] h_dma_rresp,output wire h_dma_rlast,
 input wire h_dma_awvalid,output wire h_dma_awready,input wire[63:0] h_dma_awaddr,
 input wire h_dma_wvalid,output wire h_dma_wready,input wire[63:0] h_dma_wdata,input wire[7:0] h_dma_wstrb,
 output wire h_dma_bvalid,input wire h_dma_bready,output wire[1:0] h_dma_bresp,
 output wire m_arvalid,input wire m_arready,output wire[63:0] m_araddr,output wire[7:0] m_arlen,output wire[2:0] m_arsize,
 input wire m_rvalid,output wire m_rready,input wire[63:0] m_rdata,input wire[1:0] m_rresp,input wire m_rlast,
 output wire m_awvalid,input wire m_awready,output wire[63:0] m_awaddr,output wire[7:0] m_awlen,output wire[2:0] m_awsize,
 output wire m_wvalid,input wire m_wready,output wire[63:0] m_wdata,output wire[7:0] m_wstrb,output wire m_wlast,
 input wire m_bvalid,output wire m_bready,input wire[1:0] m_bresp,

 output wire irq,fault,
 input wire hardware_owner_valid,input ot_hbm_r14_pkg::identity_t owner_identity,
 input wire[5:0] loader_client,input wire[6:0] global_rank,
 output wire[3:0] stack_req_v,input wire[3:0] stack_req_r,output wire[1819:0] stack_req,
 input wire[3:0] owned_v,output wire[3:0] owned_r,input wire[1859:0] owned,
 input wire[3:0] owned_we,owned_credit,service_fault,
 output wire[3:0] other_owned_v,input wire[3:0] other_owned_r,
 output wire[1859:0] other_owned,output wire[3:0] other_owned_we,other_owned_credit,
 output wire[3:0] credit_v,input wire[3:0] credit_r,output wire[3:0] credit_we,
 output wire[767:0] credit_id,output wire[47:0] credit_tag,output wire[19:0] credit_beat,
 input wire[3:0] other_credit_v,other_credit_we,output wire[3:0] other_credit_r,
 input wire[767:0] other_credit_id,input wire[47:0] other_credit_tag,input wire[19:0] other_credit_beat,
 output wire busy,output wire[6:0] held_global_rank
);
 wire lv,lr,lwe,sv,sr,swe,loader_fault,bridge_fault;
 wire[36:0] la;wire[255:0] ld,sd;wire[31:0] lst;wire[15:0] lt,st;
 ot_hbm_accel_loader_host_addr #(.ENABLE(ENABLE),.ND(1),.ADDR_W(37),.STACK_W(2),.STACK_BYTES(64'd22500000000)) loader(
 .clk_host(clk_host),
 .rst_host_n(rst_host_n),
 .clk_mem(clk_mem),
 .rst_mem_n(rst_mem_n),
 .s_awvalid(s_awvalid),
 .s_awready(s_awready),
 .s_awaddr(s_awaddr),
 .s_wvalid(s_wvalid),
 .s_wready(s_wready),
 .s_wdata(s_wdata),
 .s_wstrb(s_wstrb),
 .s_bvalid(s_bvalid),
 .s_bready(s_bready),
 .s_arvalid(s_arvalid),
 .s_arready(s_arready),
 .s_araddr(s_araddr),
 .s_rvalid(s_rvalid),
 .s_rready(s_rready),
 .s_rdata(s_rdata),
 .h_awvalid(h_awvalid),
 .h_awready(h_awready),
 .h_awaddr(h_awaddr),
 .h_wvalid(h_wvalid),
 .h_wready(h_wready),
 .h_wdata(h_wdata),
 .h_wstrb(h_wstrb),
 .h_bvalid(h_bvalid),
 .h_bready(h_bready),
 .h_arvalid(h_arvalid),
 .h_arready(h_arready),
 .h_araddr(h_araddr),
 .h_rvalid(h_rvalid),
 .h_rready(h_rready),
 .h_rdata(h_rdata),
 .h_dma_arvalid(h_dma_arvalid),
 .h_dma_arready(h_dma_arready),
 .h_dma_araddr(h_dma_araddr),
 .h_dma_rvalid(h_dma_rvalid),
 .h_dma_rready(h_dma_rready),
 .h_dma_rdata(h_dma_rdata),
 .h_dma_rresp(h_dma_rresp),
 .h_dma_rlast(h_dma_rlast),
 .h_dma_awvalid(h_dma_awvalid),
 .h_dma_awready(h_dma_awready),
 .h_dma_awaddr(h_dma_awaddr),
 .h_dma_wvalid(h_dma_wvalid),
 .h_dma_wready(h_dma_wready),
 .h_dma_wdata(h_dma_wdata),
 .h_dma_wstrb(h_dma_wstrb),
 .h_dma_bvalid(h_dma_bvalid),
 .h_dma_bready(h_dma_bready),
 .h_dma_bresp(h_dma_bresp),
 .m_arvalid(m_arvalid),
 .m_arready(m_arready),
 .m_araddr(m_araddr),
 .m_arlen(m_arlen),
 .m_arsize(m_arsize),
 .m_rvalid(m_rvalid),
 .m_rready(m_rready),
 .m_rdata(m_rdata),
 .m_rresp(m_rresp),
 .m_rlast(m_rlast),
 .m_awvalid(m_awvalid),
 .m_awready(m_awready),
 .m_awaddr(m_awaddr),
 .m_awlen(m_awlen),
 .m_awsize(m_awsize),
 .m_wvalid(m_wvalid),
 .m_wready(m_wready),
 .m_wdata(m_wdata),
 .m_wstrb(m_wstrb),
 .m_wlast(m_wlast),
 .m_bvalid(m_bvalid),
 .m_bready(m_bready),
 .m_bresp(m_bresp),
 .req_v(lv),
 .req_rdy(lr),
 .req_we(lwe),
 .req_addr(la),
 .req_wdata(ld),
 .req_wstrb(lst),
 .req_tag(lt),
 .rsp_v(sv),
 .rsp_rdy(sr),
 .rsp_we(swe),
 .rsp_tag(st),
 .rsp_data(sd),
 .irq(irq),
 .fault(loader_fault));
 ot_hbm_loader_service_join #(.ENABLE(ENABLE),.LOCAL_DIE(LOCAL_DIE),.RANK_LIMIT(RANK_LIMIT)) movement(
 .clk(clk_mem),.rst_n(rst_mem_n),.req_v(lv),.req_r(lr),.req_we(lwe),.req_addr(la),.req_data(ld),.req_strb(lst),.req_tag(lt),
 .rsp_v(sv),.rsp_r(sr),.rsp_we(swe),.rsp_tag(st),.rsp_data(sd),.fault(bridge_fault),
 .hardware_owner_valid(hardware_owner_valid),
 .owner_identity(owner_identity),
 .loader_client(loader_client),
 .global_rank(global_rank),
 .stack_req_v(stack_req_v),
 .stack_req_r(stack_req_r),
 .stack_req(stack_req),
 .owned_v(owned_v),
 .owned_r(owned_r),
 .owned(owned),
 .owned_we(owned_we),
 .owned_credit(owned_credit),
 .service_fault(service_fault),
 .other_owned_v(other_owned_v),
 .other_owned_r(other_owned_r),
 .other_owned(other_owned),
 .other_owned_we(other_owned_we),
 .other_owned_credit(other_owned_credit),
 .credit_v(credit_v),
 .credit_r(credit_r),
 .credit_we(credit_we),
 .credit_id(credit_id),
 .credit_tag(credit_tag),
 .credit_beat(credit_beat),
 .other_credit_v(other_credit_v),
 .other_credit_we(other_credit_we),
 .other_credit_r(other_credit_r),
 .other_credit_id(other_credit_id),
 .other_credit_tag(other_credit_tag),
 .other_credit_beat(other_credit_beat),
 .busy(busy),
 .held_global_rank(held_global_rank));
 assign fault=loader_fault||bridge_fault;
endmodule
