import json
CLK=1.2e9
def fin(rows):
    for k in rows:
        k.setdefault('new_gap',True); k.setdefault('known_gap',None)
        m=k.get('margin')
        if 'flag' not in k: k['flag']='UNKNOWN' if m is None else ('OK' if m>=1.1 else ('THIN' if m>=1.0 else 'GAP'))
        if k.get('tok_s_if_as_designed') is not None and 'tok_s_impact' not in k: k['tok_s_impact']=round(k['tok_s_if_as_designed']-k.pop('_tgt'),1)
        k.pop('_tgt',None)
    return rows
QC=249431.0; QT=4810.9
stream=4.19e6/(4*750)
dm=stream*(0.9/0.7985-1); dw=stream*(0.9/0.638-1)
q=[
 dict(id='qrom_kvdie_hbm_model',target='qwen_rom',mode='AR',unit='KV_READ',resource='KV die: 4 stacks x R 8 near-HBM row engines streaming 4.19 MB a die a layer (8K, FP8 KV)',metric='fraction of 1.0 TB/s/stack peak (minimum to hold the measured 1,814-cyc step)',
  work_per_token=36*4.19e6,work_unit='KV bytes per die per token',required=0.9,required_basis='minimum to hold the designed rate: the attention step is stream-bound (row engines consume rows as they land; no other work overlaps it on the per-layer critical path), so the 1,814-cyc measured step needs the bench\'s delivered rate. The measured layer step (1,814 cyc, results/arch/qwen_kv_die_20261009/bench.json) runs on hbm_model "per-engine in-order queues, 750 B/cycle/stack, 16-cycle latency" = 0.9 TB/s/stack = 0.90 of peak with ideal latency, no refresh / bank conflicts',
  measured=0.7985,measured_basis='same sweep size measured on the timing-faithful HBM3E model with REFpb refresh: results/rtl/hbm_system_20261008/svc_kvs.json summary.1024 "Qwen 8K KV sweep (4.19 MB/die/layer = 1,024 sectors a PC)": mean 0.7985, min 0.638 of peak (1,326 ns mean, 1,644 ns max)',
  margin=round(0.7985/0.9,2),critical_path=True,tok_s_if_as_designed=round(CLK/(QC+36*dm),1),_tgt=QT,owner_stream='qwen-1010',
  fix_hint=f'+{dm:.0f} cyc a layer mean / +{dw:.0f} worst (x36): {round(CLK/(QC+36*dm),1)} / {round(CLK/(QC+36*dw),1)} tok/s. Re-run the KV-die layer bench on the timed HBM3E model (ot_hdc_v41x_idx_hbm REFpb) and size per-PC outstanding / refresh pull-in like the DS S81 window stream (which measures this)',confidence='measured'),
 dict(id='qrom_ar_link_fec',target='qwen_rom',mode='AR',unit='LINK',resource='TP4 all-reduce (AR256) between the 4 ROM dies, 2 per layer x 36 = 72 a token (30% of the token: link class 75,600 cyc)',metric='cycles per all-reduce',
  work_per_token=72,work_unit='all-reduces',required=1037,required_basis='token_path qwen_rom.json L*.allreduce1/2: 1,094 / 952 measured (qwen_plain_ar_stream4_P8191_20261005 RT_OPTRACE) + 27 adders',
  measured=1037,measured_basis='same; the stream4 vehicle link model; ot_qfd_link_adapter.sv:17 leaves FEC to the PHY D2D adapter -- no FEC term is visible in the AR cost, while the package pair (2 ROM dies a package) puts half of each TP4 ring on a board SerDes leg; DS charges full RS(544,514) on board legs (+100 cyc a collective, ds_rom.json collective notes; HBM calibration +0.2 us FEC)',
  margin=None,critical_path=True,tok_s_if_as_designed=round(CLK/(QC+72*100),1),_tgt=QT,flag='UNKNOWN',owner_stream='qwen-1010',
  fix_hint='confirm the AR256 measurement carries the board-leg FEC latency; if not, charge +100 cyc (DS full-RS rule) to +240 cyc (HBM 0.2 us rule) per all-reduce: 72 x 100..240 -> 4,676 .. 4,488 tok/s',confidence='derived'),
 dict(id='qrom_treetop',target='qwen_rom',mode='AR',unit='CP.dispatch',resource='ROM die split stations + r22k issue/status relays (tt_si/tt_so 35/34)',metric='cycles per layer',work_per_token=29296,work_unit='cycles a token',
  required=0,required_basis='published TP4 5,492.7 tok/s has no split structure (reprice.json split_structure)',measured=821,measured_basis='reprice.json split_structure layer_delta 821 (token 29,296)',margin=None,critical_path=True,
  tok_s_if_as_designed=QT,_tgt=5492.7,flag='GAP',known_gap='qwen_treetop',new_gap=False,owner_stream='qwen-1010',fix_hint='redesign-qwen tree-top / control-plane redesign',confidence='measured'),
 dict(id='qrom_attn_step',target='qwen_rom',mode='AR',unit='ATT',resource='attention layer step through the UCIe link (ROM faces -> link -> qkd_seq -> near-HBM attention R 8 -> RES to VM)',metric='cycles per layer',work_per_token=36,work_unit='layers',
  required=1816,required_basis='token_path L*.attn_kv',measured=1814,measured_basis='bench.json typical layer_step_8192 (bit-exact, 14 runs); one hard head tile per head (re-cut H: 4 hard head tiles a row engine) -- no head serialisation',margin=1.0,critical_path=True,tok_s_if_as_designed=QT,_tgt=QT,flag='OK',new_gap=False,owner_stream='qwen-1010',
  fix_hint='measured with the idealised HBM model (see qrom_kvdie_hbm_model); near-HBM attention elements not closed physically',confidence='measured'),
 dict(id='qrom_d2d',target='qwen_rom',mode='AR',unit='LINK',resource='UCIe-A x64 ROM<->KV link, per-class credits >= RTT (13/17/25), one word a cycle a class',metric='words/cycle/class',required=1.0,required_basis='CONTRACT.md:69 every class streams one word per cycle; RES 1,024 FP32 words',
  measured=1.0,measured_basis='bench.json 8191_mixed: RES first->last at VM 421 cyc for 1,024 words incl. tree drain; included in the 1,814 measurement',margin=1.0,critical_path=True,tok_s_if_as_designed=QT,_tgt=QT,flag='OK',new_gap=False,owner_stream='qwen-1010',fix_hint='none',confidence='measured'),
]
DC=828878.4; DT=1447.7; MC=1177528.1; MT=4238.4
d=[
 dict(id='dsrom_mtp_draft_hw',target='ds_rom',mode='MTP',unit='MTP',resource='DSpark draft: 3 draft blocks + seed + 5 serial head steps; wavefront controller + accept unit',metric='hardware present',required=1,required_basis='ds_rom_mtp.json: MTP 4,238.4 = tau 4.159 x step 1,177,528 cyc; draft groups D0-D2 (~105k cyc) + DH 42.5k + MC.draft 16k on the step path',
  designed=0,designed_basis='ds_rom_mtp.json notes: "Hatched operators have no closed hardware: the three DSpark stages and the seed run on dies the S81 binding does not contain (mtp.* weights are unowned there) ... wavefront controller and accept unit closed as blocks but are not integrated". (NV5 struck 2026-10-10: the headline prices the draft head as 5 serial sweeps on the CLOSED NV1 head elements A/B, group DH 42,457.5 cyc; L2 NV5 is a rejected optional lever, +2.9% < 5% gate, see mtp-nv5-1010)',
  margin=0.0,critical_path=True,tok_s_if_as_designed=DT,_tgt=MT,flag='INFEASIBLE',owner_stream='bf-mtp-1010',
  fix_hint='bind mtp.* weights to draft dies (mtp-die P2) and integrate WFC + accept on the S81 path; until then the DS ROM MTP row has no hardware (falls back to AR 1,447.7)',confidence='derived'),
 dict(id='dsrom_l20_cand_select',target='ds_rom',mode='AR',unit='IDX',resource='L20 candidate-block select (cand.*) and head 13.63 us in the AR path',metric='cycles',required=None,required_basis='composition.json headline still_modelled',measured=None,measured_basis='modelled terms remain in the AR composition',margin=None,critical_path=True,tok_s_if_as_designed=None,flag='UNKNOWN',owner_stream='ds-1010',
  fix_hint='measure L20 cand.* at 1M on S81 (Codex S81 minimum run owns L20)',confidence='modelled'),
 dict(id='dsrom_engram',target='ds_rom',mode='AR',unit='KV_READ',resource='Engram lookup from layer1e home-die HBM (lead flit + hash + HBM read 200 ns + TP4 row all-gather + wkv)',metric='slack cycles',required=5323,required_basis='ds_rom.json E1.* node sum (modelled): 3,045+17+483+1,422+1,876+602 (lead flit 3 hops)',
  designed=13895,designed_basis='E1 consumer slack 8,572 cyc + its own path; E14 slack 235,129',margin=round(13895/5323,1),critical_path=False,tok_s_if_as_designed=DT,_tgt=DT,new_gap=False,owner_stream='ds-1010',fix_hint='modelled only (campaign record absent); HBM read 200 ns assumed vs measured window rows 122-186 ns: OK',confidence='modelled'),
 dict(id='dsrom_kv_1m',target='ds_rom',mode='AR',unit='KV_READ',resource='window rows + own-row write + index-key scan + CKV gather at 1M',metric='measured',required=None,required_basis='ds_rom.json hbm/select classes 26,085 + 21,811 cyc',measured=None,measured_basis='results/rtl/dsrom_1m_measured_20261004 (index read on timed HBM, select on golden 1M scores, CKV gather lat 259) + dsrom_s81_window_bind_20261004 (REFpb); re-index candidate gather 9db526f58',
  margin=1.0,critical_path=True,tok_s_if_as_designed=DT,_tgt=DT,flag='OK',new_gap=False,owner_stream='ds-1010',fix_hint='none: measured on the timed HBM3E model (the model the HBM die and the Qwen KV die lack)',confidence='measured'),
 dict(id='dsrom_hops_links',target='ds_rom',mode='all',unit='LINK',resource='stage hops (ot_dsrom_link_rt 652 cyc + KP4 PHY vendor 209 ns + UCIe 10 ns + 2x45 wire stages = 1,006 cyc) x 120 stages + 35 extra hops; TP4 collectives with full RS(544,514) board leg',metric='cycles',
  required=123191,required_basis='ds_rom.json hop class',measured=123191,measured_basis='measured RTL + vendor PHY',margin=1.0,critical_path=True,tok_s_if_as_designed=DT,_tgt=DT,flag='OK',new_gap=False,owner_stream='ds-1010',fix_hint='none',confidence='measured'),
 dict(id='dsrom_s81_reach',target='ds_rom',mode='all',unit='LINK',resource='S81 x-lane relay -> q bank i_x1: 768 hops/die over the 504 um SS reach',metric='violations',required=0,required_basis='SS reach rule',measured=768,measured_basis='handoff DeepSeek 1',margin=None,critical_path=True,tok_s_if_as_designed=None,flag='GAP',known_gap='s81_reach',new_gap=False,owner_stream='ds-1010',fix_hint='option B in flight (dsrom-qelem-qs5f-x1b)',confidence='measured'),
 dict(id='dsrom_bf_fullrate',target='ds_rom',mode='all',unit='SM',resource='BF full rate vs HALF_PHL',metric='tok/s',required=None,required_basis='headline is HALF_PHL (owner-accepted cost AR -7.68%, MTP ~-9%)',measured=None,measured_basis='bfa_full_a hold-only miss',margin=None,critical_path=True,tok_s_if_as_designed=DT,_tgt=DT,flag='OK',known_gap='bf_fullrate',new_gap=False,owner_stream='bf-mtp-1010',fix_hint='full-rate would lift MTP to 4,792.2 (ds_rom_mtp notes)',confidence='measured'),
 dict(id='dsrom_coll_split',target='ds_rom',mode='all',unit='COLL',resource='coll_core 3-tile split with credit links',metric='cycles',required=3015,required_basis='current core',measured=3013,measured_basis='handoff DeepSeek 2 bench',margin=1.0,critical_path=True,tok_s_if_as_designed=DT,_tgt=DT,flag='OK',known_gap='coll_split_vch',new_gap=False,owner_stream='ds-1010',fix_hint='VCH capacity -10.5%: owner check if > 1% tok/s',confidence='measured'),
 dict(id='dsrom_cg_wake',target='ds_rom',mode='AR',unit='CG_WAKE',resource='per-pair / per-die ICG (mandatory: ungated idle clock 593 W/die) wake on token arrival at each of 120 stages',metric='cycles per stage',required=0,required_basis='a stage die is idle ~119/120 of an AR token -> a wake per stage per token',designed=None,designed_basis='no wake term found in ds_rom.json or tools/dsrom_1m_allmeasured.py; field phases are measured go->idle per region',
  margin=None,critical_path=True,tok_s_if_as_designed=round(CLK/(DC+120*10),1),_tgt=DT,flag='UNKNOWN',owner_stream='ds-1010',fix_hint='wake the next stage from the hop lead flit (wake ahead of data); each 10 exposed cycles a stage cost 1,200 cyc (-0.14%)',confidence='derived'),
]
for name,rows,tr in (('qwen_rom',q,{'AR':dict(tok_s=QT,source='results/arch/token_path_20261009/qwen_rom.json headline (reprice.json cases.typical)')}),
                     ('ds_rom',d,{'AR':dict(tok_s=DT,source='results/arch/token_path_20261009/ds_rom.json'),'MTP':dict(tok_s=MT,source='ds_rom_mtp.json')})):
    json.dump(dict(fragment=name,target=name,clock_ghz=1.2,target_rates=tr,rows=fin(rows),notes=[]),open(f'/home/ubuntu/claude-takeover-20261007/budget-audit-1010/{name}.json','w'),indent=1)
    for r in rows: print(name,r['id'],r['flag'],r.get('margin'),r.get('tok_s_if_as_designed'),r.get('tok_s_impact'))
