`timescale 1ns/1ps
// The one-PC request slice used by the four-PC K arbiter.  HBM read responses
// bypass this slice and enter the separately registered group receive path.
module ot_chip_v41x_hbm_karb_pc_local #(
    parameter integer AW = 28,
    parameter integer TAGW = 16,
    parameter integer LENW = 4,
    parameter integer BEATW = 4,
    parameter integer DW = 256
) (
    input wire clk,
    input wire rst_n,
    input wire b_v,
    output wire b_rdy,
    input wire [AW-1:0] b_addr,
    input wire [LENW-1:0] b_len,
    input wire [TAGW-1:0] b_tag,
    input wire b_we,
    input wire [DW-1:0] b_wdata,
    input wire [DW/8-1:0] b_wstrb,
    output wire b_wr_done,
    input wire k_v,
    output wire k_rdy,
    input wire [AW-1:0] k_addr,
    input wire [LENW-1:0] k_len,
    input wire [TAGW-1:0] k_tag,
    input wire k_we,
    input wire [DW-1:0] k_wdata,
    input wire [DW/8-1:0] k_wstrb,
    output wire k_wr_done,
    output wire h_v,
    input wire h_rdy,
    output wire [AW-1:0] h_addr,
    output wire [LENW-1:0] h_len,
    output wire [TAGW:0] h_tag,
    output wire h_we,
    output wire [DW-1:0] h_wdata,
    output wire [DW/8-1:0] h_wstrb,
    input wire h_wr_done,
    output wire [31:0] k_grants,
    output wire [31:0] b_grants,
    output wire [31:0] contended
);
    ot_chip_v41x_hbm_karb #(.NPC(1), .AW(AW), .TAGW(TAGW),
        .LENW(LENW), .BEATW(BEATW), .DW(DW), .PIPE_OUT(1)) u_local (
        .clk(clk), .rst_n(rst_n),
        .b_v(b_v), .b_rdy(b_rdy), .b_addr(b_addr), .b_len(b_len),
        .b_tag(b_tag), .b_we(b_we), .b_wdata(b_wdata),
        .b_wstrb(b_wstrb), .b_wr_done(b_wr_done),
        .b_rsp_v(), .b_rsp_rdy(1'b0), .b_rsp_tag(), .b_rsp_beat(),
        .b_rsp_data(),
        .k_v(k_v), .k_rdy(k_rdy), .k_addr(k_addr), .k_len(k_len),
        .k_tag(k_tag), .k_we(k_we), .k_wdata(k_wdata),
        .k_wstrb(k_wstrb), .k_wr_done(k_wr_done),
        .k_rsp_v(), .k_rsp_rdy(1'b0), .k_rsp_tag(), .k_rsp_beat(),
        .k_rsp_data(),
        .h_v(h_v), .h_rdy(h_rdy), .h_addr(h_addr), .h_len(h_len),
        .h_tag(h_tag), .h_we(h_we), .h_wdata(h_wdata),
        .h_wstrb(h_wstrb), .h_wr_done(h_wr_done),
        .r_v(1'b0), .r_rdy(), .r_tag({(TAGW+1){1'b0}}),
        .r_beat({BEATW{1'b0}}), .r_data({DW{1'b0}}),
        .k_grants(k_grants), .b_grants(b_grants), .contended(contended));
endmodule
