// GENERATED by vm/vcut8/make_vm_vcut8.py: hfd_vm_se as its two vertical-cut halves (bench join; quadrant ports)
module hfd_vm_se_jv (
    input wire [0:0] ck,
    input wire [255:0] f_n_ctl,
    input wire [2255:0] f_n_row,
    input wire [2263:0] f_n_wr,
    input wire [2047:0] f_su_SE,
    input wire [255:0] f_w_ctl,
    input wire [2255:0] f_w_row,
    input wire [2263:0] f_w_wr,
    input wire [511:0] iSE,
    output wire [581:0] qSE,
    input wire [0:0] rst,
    output wire [255:0] t_n_ctl,
    output wire [2255:0] t_n_row,
    output wire [2263:0] t_n_wr,
    output wire [2047:0] t_su_SE,
    output wire [255:0] t_w_ctl,
    output wire [2255:0] t_w_row,
    output wire [2263:0] t_w_wr,
    output wire [2067:0] xSE
);
    wire [3292:0] w2e; wire [1590:0] e2w;
`ifdef MUT_SEAM
    wire [3292:0] w2e_x = {w2e[3292:12], w2e[10], w2e[11], w2e[9:0]};   // seam tap bits 10/11 swapped
`else
    wire [3292:0] w2e_x = w2e;
`endif
    hfd_vm_se_w u_w (.*, .ckw0(ck), .ckw1(ck), .ckw2(ck), .ckw3(ck), .ckw4(ck), .ckw5(ck), .ckw6(ck), .ckw7(ck), .ckw8(ck), .ckw9(ck), .ckw10(ck), .ckw11(ck), .ckw12(ck), .ckw13(ck), .ckw14(ck), .ckw15(ck), .ckw16(ck), .ckw17(ck), .ckw18(ck), .ckw19(ck), .ckw20(ck), .ckw21(ck), .ckw22(ck), .ckw23(ck), .ckw24(ck), .ckw25(ck), .ckw26(ck), .ckw27(ck), .ckw28(ck), .ckw29(ck), .ckw30(ck), .ckw31(ck), .ckw32(ck), .ckw33(ck), .ckw34(ck), .ckw35(ck), .ckw36(ck), .ckw37(ck), .ckw38(ck), .ckw39(ck), .ckw40(ck), .ckw41(ck), .ckw42(ck), .ckw43(ck), .ckw44(ck), .ckw45(ck), .ckw46(ck), .ckw47(ck), .cke0(ck), .cke1(ck), .cke2(ck), .cke3(ck), .cke4(ck), .cke5(ck), .cke6(ck), .cke7(ck), .cke8(ck), .cke9(ck), .cke10(ck), .cke11(ck), .cke12(ck), .cke13(ck), .cke14(ck), .cke15(ck), .cke16(ck), .cke17(ck), .cke18(ck), .cke19(ck), .cke20(ck), .cke21(ck), .cke22(ck), .cke23(ck), .cke24(ck), .cke25(ck), .cke26(ck), .cke27(ck), .cke28(ck), .cke29(ck), .cke30(ck), .cke31(ck), .cke32(ck), .cke33(ck), .cke34(ck), .cke35(ck), .cke36(ck), .cke37(ck), .cke38(ck), .cke39(ck), .cke40(ck), .cke41(ck), .cke42(ck), .cke43(ck), .cke44(ck), .cke45(ck), .cke46(ck), .cke47(ck), .ckn0(ck), .ckn1(ck), .ckn2(ck), .ckn3(ck), .ckn4(ck), .ckn5(ck), .ckn6(ck), .ckn7(ck), .ckn8(ck), .ckn9(ck), .ckn10(ck), .ckn11(ck), .ckn12(ck), .ckn13(ck), .ckn14(ck), .ckn15(ck), .ckn16(ck), .ckn17(ck), .ckn18(ck), .ckn19(ck), .ckn20(ck), .ckn21(ck), .ckn22(ck), .ckn23(ck), .ckn24(ck), .ckn25(ck), .ckn26(ck), .ckn27(ck), .ckn28(ck), .ckn29(ck), .ckn30(ck), .ckn31(ck));
    hfd_vm_se_e u_e (.*, .w2e(w2e_x), .ckw0(ck), .ckw1(ck), .ckw2(ck), .ckw3(ck), .ckw4(ck), .ckw5(ck), .ckw6(ck), .ckw7(ck), .ckw8(ck), .ckw9(ck), .ckw10(ck), .ckw11(ck), .ckw12(ck), .ckw13(ck), .ckw14(ck), .ckw15(ck), .ckw16(ck), .ckw17(ck), .ckw18(ck), .ckw19(ck), .ckw20(ck), .ckw21(ck), .ckw22(ck), .ckw23(ck), .ckw24(ck), .ckw25(ck), .ckw26(ck), .ckw27(ck), .ckw28(ck), .ckw29(ck), .ckw30(ck), .ckw31(ck), .ckw32(ck), .ckw33(ck), .ckw34(ck), .ckw35(ck), .ckw36(ck), .ckw37(ck), .ckw38(ck), .ckw39(ck), .ckw40(ck), .ckw41(ck), .ckw42(ck), .ckw43(ck), .ckw44(ck), .ckw45(ck), .ckw46(ck), .ckw47(ck), .cke0(ck), .cke1(ck), .cke2(ck), .cke3(ck), .cke4(ck), .cke5(ck), .cke6(ck), .cke7(ck), .cke8(ck), .cke9(ck), .cke10(ck), .cke11(ck), .cke12(ck), .cke13(ck), .cke14(ck), .cke15(ck), .cke16(ck), .cke17(ck), .cke18(ck), .cke19(ck), .cke20(ck), .cke21(ck), .cke22(ck), .cke23(ck), .cke24(ck), .cke25(ck), .cke26(ck), .cke27(ck), .cke28(ck), .cke29(ck), .cke30(ck), .cke31(ck), .cke32(ck), .cke33(ck), .cke34(ck), .cke35(ck), .cke36(ck), .cke37(ck), .cke38(ck), .cke39(ck), .cke40(ck), .cke41(ck), .cke42(ck), .cke43(ck), .cke44(ck), .cke45(ck), .cke46(ck), .cke47(ck), .ckn0(ck), .ckn1(ck), .ckn2(ck), .ckn3(ck), .ckn4(ck), .ckn5(ck), .ckn6(ck), .ckn7(ck), .ckn8(ck), .ckn9(ck), .ckn10(ck), .ckn11(ck), .ckn12(ck), .ckn13(ck), .ckn14(ck), .ckn15(ck), .ckn16(ck), .ckn17(ck), .ckn18(ck), .ckn19(ck), .ckn20(ck), .ckn21(ck), .ckn22(ck), .ckn23(ck), .ckn24(ck), .ckn25(ck), .ckn26(ck), .ckn27(ck), .ckn28(ck), .ckn29(ck), .ckn30(ck), .ckn31(ck));
endmodule
