// GENERATED by vm/vcut8/make_vm_vcut8.py (see there): 8-way VM half (vertical cut) hfd_vm_se_w
module hfd_vm_se_w (
    input wire [0:0] ck,
    input wire [0:0] ckw0,
    input wire [0:0] ckw1,
    input wire [0:0] ckw2,
    input wire [0:0] ckw3,
    input wire [0:0] ckw4,
    input wire [0:0] ckw5,
    input wire [0:0] ckw6,
    input wire [0:0] ckw7,
    input wire [0:0] ckw8,
    input wire [0:0] ckw9,
    input wire [0:0] ckw10,
    input wire [0:0] ckw11,
    input wire [0:0] ckw12,
    input wire [0:0] ckw13,
    input wire [0:0] ckw14,
    input wire [0:0] ckw15,
    input wire [0:0] ckw16,
    input wire [0:0] ckw17,
    input wire [0:0] ckw18,
    input wire [0:0] ckw19,
    input wire [0:0] ckw20,
    input wire [0:0] ckw21,
    input wire [0:0] ckw22,
    input wire [0:0] ckw23,
    input wire [0:0] ckw24,
    input wire [0:0] ckw25,
    input wire [0:0] ckw26,
    input wire [0:0] ckw27,
    input wire [0:0] ckw28,
    input wire [0:0] ckw29,
    input wire [0:0] ckw30,
    input wire [0:0] ckw31,
    input wire [0:0] ckw32,
    input wire [0:0] ckw33,
    input wire [0:0] ckw34,
    input wire [0:0] ckw35,
    input wire [0:0] ckw36,
    input wire [0:0] ckw37,
    input wire [0:0] ckw38,
    input wire [0:0] ckw39,
    input wire [0:0] ckw40,
    input wire [0:0] ckw41,
    input wire [0:0] ckw42,
    input wire [0:0] ckw43,
    input wire [0:0] ckw44,
    input wire [0:0] ckw45,
    input wire [0:0] ckw46,
    input wire [0:0] ckw47,
    input wire [0:0] cke0,
    input wire [0:0] cke1,
    input wire [0:0] cke2,
    input wire [0:0] cke3,
    input wire [0:0] cke4,
    input wire [0:0] cke5,
    input wire [0:0] cke6,
    input wire [0:0] cke7,
    input wire [0:0] cke8,
    input wire [0:0] cke9,
    input wire [0:0] cke10,
    input wire [0:0] cke11,
    input wire [0:0] cke12,
    input wire [0:0] cke13,
    input wire [0:0] cke14,
    input wire [0:0] cke15,
    input wire [0:0] cke16,
    input wire [0:0] cke17,
    input wire [0:0] cke18,
    input wire [0:0] cke19,
    input wire [0:0] cke20,
    input wire [0:0] cke21,
    input wire [0:0] cke22,
    input wire [0:0] cke23,
    input wire [0:0] cke24,
    input wire [0:0] cke25,
    input wire [0:0] cke26,
    input wire [0:0] cke27,
    input wire [0:0] cke28,
    input wire [0:0] cke29,
    input wire [0:0] cke30,
    input wire [0:0] cke31,
    input wire [0:0] cke32,
    input wire [0:0] cke33,
    input wire [0:0] cke34,
    input wire [0:0] cke35,
    input wire [0:0] cke36,
    input wire [0:0] cke37,
    input wire [0:0] cke38,
    input wire [0:0] cke39,
    input wire [0:0] cke40,
    input wire [0:0] cke41,
    input wire [0:0] cke42,
    input wire [0:0] cke43,
    input wire [0:0] cke44,
    input wire [0:0] cke45,
    input wire [0:0] cke46,
    input wire [0:0] cke47,
    input wire [0:0] ckn0,
    input wire [0:0] ckn1,
    input wire [0:0] ckn2,
    input wire [0:0] ckn3,
    input wire [0:0] ckn4,
    input wire [0:0] ckn5,
    input wire [0:0] ckn6,
    input wire [0:0] ckn7,
    input wire [0:0] ckn8,
    input wire [0:0] ckn9,
    input wire [0:0] ckn10,
    input wire [0:0] ckn11,
    input wire [0:0] ckn12,
    input wire [0:0] ckn13,
    input wire [0:0] ckn14,
    input wire [0:0] ckn15,
    input wire [0:0] ckn16,
    input wire [0:0] ckn17,
    input wire [0:0] ckn18,
    input wire [0:0] ckn19,
    input wire [0:0] ckn20,
    input wire [0:0] ckn21,
    input wire [0:0] ckn22,
    input wire [0:0] ckn23,
    input wire [0:0] ckn24,
    input wire [0:0] ckn25,
    input wire [0:0] ckn26,
    input wire [0:0] ckn27,
    input wire [0:0] ckn28,
    input wire [0:0] ckn29,
    input wire [0:0] ckn30,
    input wire [0:0] ckn31,
    input wire [0:0] rst,
    input wire [255:0] f_n_ctl,
    input wire [2255:0] f_n_row,
    input wire [255:0] f_w_ctl,
    input wire [2255:0] f_w_row,
    input wire [2263:0] f_w_wr,
    output wire [2263:0] t_n_wr,
    output wire [255:0] t_w_ctl,
    output wire [2255:0] t_w_row,
    output wire [2263:0] t_w_wr,
    output wire [3292:0] w2e,
    input wire [1590:0] e2w
);
    wire clk = ck[0];
    wire c_ckw0 = ckw0[0];   // W-face tap leaf (0..21 um)
    wire c_ckw1 = ckw1[0];   // W-face tap leaf (21..42 um)
    wire c_ckw2 = ckw2[0];   // W-face tap leaf (42..63 um)
    wire c_ckw3 = ckw3[0];   // W-face tap leaf (63..83 um)
    wire c_ckw4 = ckw4[0];   // W-face tap leaf (83..104 um)
    wire c_ckw5 = ckw5[0];   // W-face tap leaf (104..125 um)
    wire c_ckw6 = ckw6[0];   // W-face tap leaf (125..146 um)
    wire c_ckw7 = ckw7[0];   // W-face tap leaf (146..167 um)
    wire c_ckw8 = ckw8[0];   // W-face tap leaf (167..188 um)
    wire c_ckw9 = ckw9[0];   // W-face tap leaf (188..208 um)
    wire c_ckw10 = ckw10[0];   // W-face tap leaf (208..229 um)
    wire c_ckw11 = ckw11[0];   // W-face tap leaf (229..250 um)
    wire c_ckw12 = ckw12[0];   // W-face tap leaf (250..271 um)
    wire c_ckw13 = ckw13[0];   // W-face tap leaf (271..292 um)
    wire c_ckw14 = ckw14[0];   // W-face tap leaf (292..313 um)
    wire c_ckw15 = ckw15[0];   // W-face tap leaf (313..333 um)
    wire c_ckw16 = ckw16[0];   // W-face tap leaf (333..354 um)
    wire c_ckw17 = ckw17[0];   // W-face tap leaf (354..375 um)
    wire c_ckw18 = ckw18[0];   // W-face tap leaf (375..396 um)
    wire c_ckw19 = ckw19[0];   // W-face tap leaf (396..417 um)
    wire c_ckw20 = ckw20[0];   // W-face tap leaf (417..438 um)
    wire c_ckw21 = ckw21[0];   // W-face tap leaf (438..458 um)
    wire c_ckw22 = ckw22[0];   // W-face tap leaf (458..479 um)
    wire c_ckw23 = ckw23[0];   // W-face tap leaf (479..500 um)
    wire c_ckw24 = ckw24[0];   // W-face tap leaf (500..521 um)
    wire c_ckw25 = ckw25[0];   // W-face tap leaf (521..542 um)
    wire c_ckw26 = ckw26[0];   // W-face tap leaf (542..563 um)
    wire c_ckw27 = ckw27[0];   // W-face tap leaf (563..583 um)
    wire c_ckw28 = ckw28[0];   // W-face tap leaf (583..604 um)
    wire c_ckw29 = ckw29[0];   // W-face tap leaf (604..625 um)
    wire c_ckw30 = ckw30[0];   // W-face tap leaf (625..646 um)
    wire c_ckw31 = ckw31[0];   // W-face tap leaf (646..667 um)
    wire c_ckw32 = ckw32[0];   // W-face tap leaf (667..688 um)
    wire c_ckw33 = ckw33[0];   // W-face tap leaf (688..708 um)
    wire c_ckw34 = ckw34[0];   // W-face tap leaf (708..729 um)
    wire c_ckw35 = ckw35[0];   // W-face tap leaf (729..750 um)
    wire c_ckw36 = ckw36[0];   // W-face tap leaf (750..771 um)
    wire c_ckw37 = ckw37[0];   // W-face tap leaf (771..792 um)
    wire c_ckw38 = ckw38[0];   // W-face tap leaf (792..813 um)
    wire c_ckw39 = ckw39[0];   // W-face tap leaf (813..833 um)
    wire c_ckw40 = ckw40[0];   // W-face tap leaf (833..854 um)
    wire c_ckw41 = ckw41[0];   // W-face tap leaf (854..875 um)
    wire c_ckw42 = ckw42[0];   // W-face tap leaf (875..896 um)
    wire c_ckw43 = ckw43[0];   // W-face tap leaf (896..917 um)
    wire c_ckw44 = ckw44[0];   // W-face tap leaf (917..938 um)
    wire c_ckw45 = ckw45[0];   // W-face tap leaf (938..958 um)
    wire c_ckw46 = ckw46[0];   // W-face tap leaf (958..979 um)
    wire c_ckw47 = ckw47[0];   // W-face tap leaf (979..1000 um)
    wire c_cke0 = cke0[0];   // E-face tap leaf (0..21 um)
    wire c_cke1 = cke1[0];   // E-face tap leaf (21..42 um)
    wire c_cke2 = cke2[0];   // E-face tap leaf (42..63 um)
    wire c_cke3 = cke3[0];   // E-face tap leaf (63..83 um)
    wire c_cke4 = cke4[0];   // E-face tap leaf (83..104 um)
    wire c_cke5 = cke5[0];   // E-face tap leaf (104..125 um)
    wire c_cke6 = cke6[0];   // E-face tap leaf (125..146 um)
    wire c_cke7 = cke7[0];   // E-face tap leaf (146..167 um)
    wire c_cke8 = cke8[0];   // E-face tap leaf (167..188 um)
    wire c_cke9 = cke9[0];   // E-face tap leaf (188..208 um)
    wire c_cke10 = cke10[0];   // E-face tap leaf (208..229 um)
    wire c_cke11 = cke11[0];   // E-face tap leaf (229..250 um)
    wire c_cke12 = cke12[0];   // E-face tap leaf (250..271 um)
    wire c_cke13 = cke13[0];   // E-face tap leaf (271..292 um)
    wire c_cke14 = cke14[0];   // E-face tap leaf (292..313 um)
    wire c_cke15 = cke15[0];   // E-face tap leaf (313..333 um)
    wire c_cke16 = cke16[0];   // E-face tap leaf (333..354 um)
    wire c_cke17 = cke17[0];   // E-face tap leaf (354..375 um)
    wire c_cke18 = cke18[0];   // E-face tap leaf (375..396 um)
    wire c_cke19 = cke19[0];   // E-face tap leaf (396..417 um)
    wire c_cke20 = cke20[0];   // E-face tap leaf (417..438 um)
    wire c_cke21 = cke21[0];   // E-face tap leaf (438..458 um)
    wire c_cke22 = cke22[0];   // E-face tap leaf (458..479 um)
    wire c_cke23 = cke23[0];   // E-face tap leaf (479..500 um)
    wire c_cke24 = cke24[0];   // E-face tap leaf (500..521 um)
    wire c_cke25 = cke25[0];   // E-face tap leaf (521..542 um)
    wire c_cke26 = cke26[0];   // E-face tap leaf (542..563 um)
    wire c_cke27 = cke27[0];   // E-face tap leaf (563..583 um)
    wire c_cke28 = cke28[0];   // E-face tap leaf (583..604 um)
    wire c_cke29 = cke29[0];   // E-face tap leaf (604..625 um)
    wire c_cke30 = cke30[0];   // E-face tap leaf (625..646 um)
    wire c_cke31 = cke31[0];   // E-face tap leaf (646..667 um)
    wire c_cke32 = cke32[0];   // E-face tap leaf (667..688 um)
    wire c_cke33 = cke33[0];   // E-face tap leaf (688..708 um)
    wire c_cke34 = cke34[0];   // E-face tap leaf (708..729 um)
    wire c_cke35 = cke35[0];   // E-face tap leaf (729..750 um)
    wire c_cke36 = cke36[0];   // E-face tap leaf (750..771 um)
    wire c_cke37 = cke37[0];   // E-face tap leaf (771..792 um)
    wire c_cke38 = cke38[0];   // E-face tap leaf (792..813 um)
    wire c_cke39 = cke39[0];   // E-face tap leaf (813..833 um)
    wire c_cke40 = cke40[0];   // E-face tap leaf (833..854 um)
    wire c_cke41 = cke41[0];   // E-face tap leaf (854..875 um)
    wire c_cke42 = cke42[0];   // E-face tap leaf (875..896 um)
    wire c_cke43 = cke43[0];   // E-face tap leaf (896..917 um)
    wire c_cke44 = cke44[0];   // E-face tap leaf (917..938 um)
    wire c_cke45 = cke45[0];   // E-face tap leaf (938..958 um)
    wire c_cke46 = cke46[0];   // E-face tap leaf (958..979 um)
    wire c_cke47 = cke47[0];   // E-face tap leaf (979..1000 um)
    wire c_ckn0 = ckn0[0];   // N-face tap leaf (0..11 um)
    wire c_ckn1 = ckn1[0];   // N-face tap leaf (11..22 um)
    wire c_ckn2 = ckn2[0];   // N-face tap leaf (22..33 um)
    wire c_ckn3 = ckn3[0];   // N-face tap leaf (33..44 um)
    wire c_ckn4 = ckn4[0];   // N-face tap leaf (44..55 um)
    wire c_ckn5 = ckn5[0];   // N-face tap leaf (55..65 um)
    wire c_ckn6 = ckn6[0];   // N-face tap leaf (65..76 um)
    wire c_ckn7 = ckn7[0];   // N-face tap leaf (76..87 um)
    wire c_ckn8 = ckn8[0];   // N-face tap leaf (87..98 um)
    wire c_ckn9 = ckn9[0];   // N-face tap leaf (98..109 um)
    wire c_ckn10 = ckn10[0];   // N-face tap leaf (109..120 um)
    wire c_ckn11 = ckn11[0];   // N-face tap leaf (120..131 um)
    wire c_ckn12 = ckn12[0];   // N-face tap leaf (131..142 um)
    wire c_ckn13 = ckn13[0];   // N-face tap leaf (142..153 um)
    wire c_ckn14 = ckn14[0];   // N-face tap leaf (153..164 um)
    wire c_ckn15 = ckn15[0];   // N-face tap leaf (164..175 um)
    wire c_ckn16 = ckn16[0];   // N-face tap leaf (175..185 um)
    wire c_ckn17 = ckn17[0];   // N-face tap leaf (185..196 um)
    wire c_ckn18 = ckn18[0];   // N-face tap leaf (196..207 um)
    wire c_ckn19 = ckn19[0];   // N-face tap leaf (207..218 um)
    wire c_ckn20 = ckn20[0];   // N-face tap leaf (218..229 um)
    wire c_ckn21 = ckn21[0];   // N-face tap leaf (229..240 um)
    wire c_ckn22 = ckn22[0];   // N-face tap leaf (240..251 um)
    wire c_ckn23 = ckn23[0];   // N-face tap leaf (251..262 um)
    wire c_ckn24 = ckn24[0];   // N-face tap leaf (262..273 um)
    wire c_ckn25 = ckn25[0];   // N-face tap leaf (273..284 um)
    wire c_ckn26 = ckn26[0];   // N-face tap leaf (284..295 um)
    wire c_ckn27 = ckn27[0];   // N-face tap leaf (295..305 um)
    wire c_ckn28 = ckn28[0];   // N-face tap leaf (305..316 um)
    wire c_ckn29 = ckn29[0];   // N-face tap leaf (316..327 um)
    wire c_ckn30 = ckn30[0];   // N-face tap leaf (327..338 um)
    wire c_ckn31 = ckn31[0];   // N-face tap leaf (338..349 um)
    reg rst_f, rst_l; always @(posedge c_ckw0) rst_f <= rst[0]; always @(negedge c_ckw0) rst_l <= rst_f;
    reg rst_c; always @(posedge clk) rst_c <= rst_l;
    wire rst_n = ~rst_c;
    reg [2263:0] xf_f_w_wr, x_f_w_wr;
    always @(posedge c_ckw1) xf_f_w_wr[7:0] <= f_w_wr[7:0]; always @(negedge c_ckw1) x_f_w_wr[7:0] <= xf_f_w_wr[7:0];   // pin reg + lockup (ckw1)
    always @(posedge c_ckw2) xf_f_w_wr[225:8] <= f_w_wr[225:8]; always @(negedge c_ckw2) x_f_w_wr[225:8] <= xf_f_w_wr[225:8];   // pin reg + lockup (ckw2)
    always @(posedge c_ckw3) xf_f_w_wr[441:226] <= f_w_wr[441:226]; always @(negedge c_ckw3) x_f_w_wr[441:226] <= xf_f_w_wr[441:226];   // pin reg + lockup (ckw3)
    always @(posedge c_ckw4) xf_f_w_wr[650:442] <= f_w_wr[650:442]; always @(negedge c_ckw4) x_f_w_wr[650:442] <= xf_f_w_wr[650:442];   // pin reg + lockup (ckw4)
    always @(posedge c_ckw5) xf_f_w_wr[651:651] <= f_w_wr[651:651]; always @(negedge c_ckw5) x_f_w_wr[651:651] <= xf_f_w_wr[651:651];   // pin reg + lockup (ckw5)
    always @(posedge c_ckw4) xf_f_w_wr[652:652] <= f_w_wr[652:652]; always @(negedge c_ckw4) x_f_w_wr[652:652] <= xf_f_w_wr[652:652];   // pin reg + lockup (ckw4)
    always @(posedge c_ckw5) xf_f_w_wr[653:653] <= f_w_wr[653:653]; always @(negedge c_ckw5) x_f_w_wr[653:653] <= xf_f_w_wr[653:653];   // pin reg + lockup (ckw5)
    always @(posedge c_ckw4) xf_f_w_wr[654:654] <= f_w_wr[654:654]; always @(negedge c_ckw4) x_f_w_wr[654:654] <= xf_f_w_wr[654:654];   // pin reg + lockup (ckw4)
    always @(posedge c_ckw5) xf_f_w_wr[655:655] <= f_w_wr[655:655]; always @(negedge c_ckw5) x_f_w_wr[655:655] <= xf_f_w_wr[655:655];   // pin reg + lockup (ckw5)
    always @(posedge c_ckw4) xf_f_w_wr[656:656] <= f_w_wr[656:656]; always @(negedge c_ckw4) x_f_w_wr[656:656] <= xf_f_w_wr[656:656];   // pin reg + lockup (ckw4)
    always @(posedge c_ckw5) xf_f_w_wr[657:657] <= f_w_wr[657:657]; always @(negedge c_ckw5) x_f_w_wr[657:657] <= xf_f_w_wr[657:657];   // pin reg + lockup (ckw5)
    always @(posedge c_ckw4) xf_f_w_wr[658:658] <= f_w_wr[658:658]; always @(negedge c_ckw4) x_f_w_wr[658:658] <= xf_f_w_wr[658:658];   // pin reg + lockup (ckw4)
    always @(posedge c_ckw5) xf_f_w_wr[874:659] <= f_w_wr[874:659]; always @(negedge c_ckw5) x_f_w_wr[874:659] <= xf_f_w_wr[874:659];   // pin reg + lockup (ckw5)
    always @(posedge c_ckw6) xf_f_w_wr[875:875] <= f_w_wr[875:875]; always @(negedge c_ckw6) x_f_w_wr[875:875] <= xf_f_w_wr[875:875];   // pin reg + lockup (ckw6)
    always @(posedge c_ckw5) xf_f_w_wr[876:876] <= f_w_wr[876:876]; always @(negedge c_ckw5) x_f_w_wr[876:876] <= xf_f_w_wr[876:876];   // pin reg + lockup (ckw5)
    always @(posedge c_ckw6) xf_f_w_wr[1093:877] <= f_w_wr[1093:877]; always @(negedge c_ckw6) x_f_w_wr[1093:877] <= xf_f_w_wr[1093:877];   // pin reg + lockup (ckw6)
    always @(posedge c_ckw7) xf_f_w_wr[1311:1094] <= f_w_wr[1311:1094]; always @(negedge c_ckw7) x_f_w_wr[1311:1094] <= xf_f_w_wr[1311:1094];   // pin reg + lockup (ckw7)
    always @(posedge c_ckw8) xf_f_w_wr[1527:1312] <= f_w_wr[1527:1312]; always @(negedge c_ckw8) x_f_w_wr[1527:1312] <= xf_f_w_wr[1527:1312];   // pin reg + lockup (ckw8)
    always @(posedge c_ckw9) xf_f_w_wr[1745:1528] <= f_w_wr[1745:1528]; always @(negedge c_ckw9) x_f_w_wr[1745:1528] <= xf_f_w_wr[1745:1528];   // pin reg + lockup (ckw9)
    always @(posedge c_ckw10) xf_f_w_wr[1961:1746] <= f_w_wr[1961:1746]; always @(negedge c_ckw10) x_f_w_wr[1961:1746] <= xf_f_w_wr[1961:1746];   // pin reg + lockup (ckw10)
    always @(posedge c_ckw11) xf_f_w_wr[2172:1962] <= f_w_wr[2172:1962]; always @(negedge c_ckw11) x_f_w_wr[2172:1962] <= xf_f_w_wr[2172:1962];   // pin reg + lockup (ckw11)
    always @(posedge c_ckw12) xf_f_w_wr[2173:2173] <= f_w_wr[2173:2173]; always @(negedge c_ckw12) x_f_w_wr[2173:2173] <= xf_f_w_wr[2173:2173];   // pin reg + lockup (ckw12)
    always @(posedge c_ckw11) xf_f_w_wr[2174:2174] <= f_w_wr[2174:2174]; always @(negedge c_ckw11) x_f_w_wr[2174:2174] <= xf_f_w_wr[2174:2174];   // pin reg + lockup (ckw11)
    always @(posedge c_ckw12) xf_f_w_wr[2175:2175] <= f_w_wr[2175:2175]; always @(negedge c_ckw12) x_f_w_wr[2175:2175] <= xf_f_w_wr[2175:2175];   // pin reg + lockup (ckw12)
    always @(posedge c_ckw11) xf_f_w_wr[2176:2176] <= f_w_wr[2176:2176]; always @(negedge c_ckw11) x_f_w_wr[2176:2176] <= xf_f_w_wr[2176:2176];   // pin reg + lockup (ckw11)
    always @(posedge c_ckw12) xf_f_w_wr[2177:2177] <= f_w_wr[2177:2177]; always @(negedge c_ckw12) x_f_w_wr[2177:2177] <= xf_f_w_wr[2177:2177];   // pin reg + lockup (ckw12)
    always @(posedge c_ckw11) xf_f_w_wr[2178:2178] <= f_w_wr[2178:2178]; always @(negedge c_ckw11) x_f_w_wr[2178:2178] <= xf_f_w_wr[2178:2178];   // pin reg + lockup (ckw11)
    always @(posedge c_ckw12) xf_f_w_wr[2263:2179] <= f_w_wr[2263:2179]; always @(negedge c_ckw12) x_f_w_wr[2263:2179] <= xf_f_w_wr[2263:2179];   // pin reg + lockup (ckw12)
    reg [2255:0] xf_f_w_row, x_f_w_row;
    always @(posedge c_ckw12) xf_f_w_row[126:0] <= f_w_row[126:0]; always @(negedge c_ckw12) x_f_w_row[126:0] <= xf_f_w_row[126:0];   // pin reg + lockup (ckw12)
    always @(posedge c_ckw13) xf_f_w_row[127:127] <= f_w_row[127:127]; always @(negedge c_ckw13) x_f_w_row[127:127] <= xf_f_w_row[127:127];   // pin reg + lockup (ckw13)
    always @(posedge c_ckw12) xf_f_w_row[128:128] <= f_w_row[128:128]; always @(negedge c_ckw12) x_f_w_row[128:128] <= xf_f_w_row[128:128];   // pin reg + lockup (ckw12)
    always @(posedge c_ckw13) xf_f_w_row[345:129] <= f_w_row[345:129]; always @(negedge c_ckw13) x_f_w_row[345:129] <= xf_f_w_row[345:129];   // pin reg + lockup (ckw13)
    always @(posedge c_ckw14) xf_f_w_row[563:346] <= f_w_row[563:346]; always @(negedge c_ckw14) x_f_w_row[563:346] <= xf_f_w_row[563:346];   // pin reg + lockup (ckw14)
    always @(posedge c_ckw15) xf_f_w_row[779:564] <= f_w_row[779:564]; always @(negedge c_ckw15) x_f_w_row[779:564] <= xf_f_w_row[779:564];   // pin reg + lockup (ckw15)
    always @(posedge c_ckw16) xf_f_w_row[997:780] <= f_w_row[997:780]; always @(negedge c_ckw16) x_f_w_row[997:780] <= xf_f_w_row[997:780];   // pin reg + lockup (ckw16)
    always @(posedge c_ckw17) xf_f_w_row[1213:998] <= f_w_row[1213:998]; always @(negedge c_ckw17) x_f_w_row[1213:998] <= xf_f_w_row[1213:998];   // pin reg + lockup (ckw17)
    always @(posedge c_ckw18) xf_f_w_row[1424:1214] <= f_w_row[1424:1214]; always @(negedge c_ckw18) x_f_w_row[1424:1214] <= xf_f_w_row[1424:1214];   // pin reg + lockup (ckw18)
    always @(posedge c_ckw19) xf_f_w_row[1425:1425] <= f_w_row[1425:1425]; always @(negedge c_ckw19) x_f_w_row[1425:1425] <= xf_f_w_row[1425:1425];   // pin reg + lockup (ckw19)
    always @(posedge c_ckw18) xf_f_w_row[1426:1426] <= f_w_row[1426:1426]; always @(negedge c_ckw18) x_f_w_row[1426:1426] <= xf_f_w_row[1426:1426];   // pin reg + lockup (ckw18)
    always @(posedge c_ckw19) xf_f_w_row[1427:1427] <= f_w_row[1427:1427]; always @(negedge c_ckw19) x_f_w_row[1427:1427] <= xf_f_w_row[1427:1427];   // pin reg + lockup (ckw19)
    always @(posedge c_ckw18) xf_f_w_row[1428:1428] <= f_w_row[1428:1428]; always @(negedge c_ckw18) x_f_w_row[1428:1428] <= xf_f_w_row[1428:1428];   // pin reg + lockup (ckw18)
    always @(posedge c_ckw19) xf_f_w_row[1429:1429] <= f_w_row[1429:1429]; always @(negedge c_ckw19) x_f_w_row[1429:1429] <= xf_f_w_row[1429:1429];   // pin reg + lockup (ckw19)
    always @(posedge c_ckw18) xf_f_w_row[1430:1430] <= f_w_row[1430:1430]; always @(negedge c_ckw18) x_f_w_row[1430:1430] <= xf_f_w_row[1430:1430];   // pin reg + lockup (ckw18)
    always @(posedge c_ckw19) xf_f_w_row[1644:1431] <= f_w_row[1644:1431]; always @(negedge c_ckw19) x_f_w_row[1644:1431] <= xf_f_w_row[1644:1431];   // pin reg + lockup (ckw19)
    always @(posedge c_ckw20) xf_f_w_row[1645:1645] <= f_w_row[1645:1645]; always @(negedge c_ckw20) x_f_w_row[1645:1645] <= xf_f_w_row[1645:1645];   // pin reg + lockup (ckw20)
    always @(posedge c_ckw19) xf_f_w_row[1646:1646] <= f_w_row[1646:1646]; always @(negedge c_ckw19) x_f_w_row[1646:1646] <= xf_f_w_row[1646:1646];   // pin reg + lockup (ckw19)
    always @(posedge c_ckw20) xf_f_w_row[1865:1647] <= f_w_row[1865:1647]; always @(negedge c_ckw20) x_f_w_row[1865:1647] <= xf_f_w_row[1865:1647];   // pin reg + lockup (ckw20)
    always @(posedge c_ckw21) xf_f_w_row[2081:1866] <= f_w_row[2081:1866]; always @(negedge c_ckw21) x_f_w_row[2081:1866] <= xf_f_w_row[2081:1866];   // pin reg + lockup (ckw21)
    always @(posedge c_ckw22) xf_f_w_row[2255:2082] <= f_w_row[2255:2082]; always @(negedge c_ckw22) x_f_w_row[2255:2082] <= xf_f_w_row[2255:2082];   // pin reg + lockup (ckw22)
    reg [255:0] xf_f_w_ctl, x_f_w_ctl;
    always @(posedge c_ckw22) xf_f_w_ctl[39:0] <= f_w_ctl[39:0]; always @(negedge c_ckw22) x_f_w_ctl[39:0] <= xf_f_w_ctl[39:0];   // pin reg + lockup (ckw22)
    always @(posedge c_ckw23) xf_f_w_ctl[40:40] <= f_w_ctl[40:40]; always @(negedge c_ckw23) x_f_w_ctl[40:40] <= xf_f_w_ctl[40:40];   // pin reg + lockup (ckw23)
    always @(posedge c_ckw22) xf_f_w_ctl[41:41] <= f_w_ctl[41:41]; always @(negedge c_ckw22) x_f_w_ctl[41:41] <= xf_f_w_ctl[41:41];   // pin reg + lockup (ckw22)
    always @(posedge c_ckw23) xf_f_w_ctl[255:42] <= f_w_ctl[255:42]; always @(negedge c_ckw23) x_f_w_ctl[255:42] <= xf_f_w_ctl[255:42];   // pin reg + lockup (ckw23)
    reg [2255:0] xf_f_n_row, x_f_n_row;
    always @(posedge c_ckn15) xf_f_n_row[122:0] <= f_n_row[122:0]; always @(negedge c_ckn15) x_f_n_row[122:0] <= xf_f_n_row[122:0];   // pin reg + lockup (ckn15)
    always @(posedge c_ckn16) xf_f_n_row[293:123] <= f_n_row[293:123]; always @(negedge c_ckn16) x_f_n_row[293:123] <= xf_f_n_row[293:123];   // pin reg + lockup (ckn16)
    always @(posedge c_ckn17) xf_f_n_row[465:294] <= f_n_row[465:294]; always @(negedge c_ckn17) x_f_n_row[465:294] <= xf_f_n_row[465:294];   // pin reg + lockup (ckn17)
    always @(posedge c_ckn18) xf_f_n_row[635:466] <= f_n_row[635:466]; always @(negedge c_ckn18) x_f_n_row[635:466] <= xf_f_n_row[635:466];   // pin reg + lockup (ckn18)
    always @(posedge c_ckn19) xf_f_n_row[805:636] <= f_n_row[805:636]; always @(negedge c_ckn19) x_f_n_row[805:636] <= xf_f_n_row[805:636];   // pin reg + lockup (ckn19)
    always @(posedge c_ckn20) xf_f_n_row[975:806] <= f_n_row[975:806]; always @(negedge c_ckn20) x_f_n_row[975:806] <= xf_f_n_row[975:806];   // pin reg + lockup (ckn20)
    always @(posedge c_ckn21) xf_f_n_row[1147:976] <= f_n_row[1147:976]; always @(negedge c_ckn21) x_f_n_row[1147:976] <= xf_f_n_row[1147:976];   // pin reg + lockup (ckn21)
    always @(posedge c_ckn22) xf_f_n_row[1317:1148] <= f_n_row[1317:1148]; always @(negedge c_ckn22) x_f_n_row[1317:1148] <= xf_f_n_row[1317:1148];   // pin reg + lockup (ckn22)
    always @(posedge c_ckn23) xf_f_n_row[1487:1318] <= f_n_row[1487:1318]; always @(negedge c_ckn23) x_f_n_row[1487:1318] <= xf_f_n_row[1487:1318];   // pin reg + lockup (ckn23)
    always @(posedge c_ckn24) xf_f_n_row[1657:1488] <= f_n_row[1657:1488]; always @(negedge c_ckn24) x_f_n_row[1657:1488] <= xf_f_n_row[1657:1488];   // pin reg + lockup (ckn24)
    always @(posedge c_ckn25) xf_f_n_row[1829:1658] <= f_n_row[1829:1658]; always @(negedge c_ckn25) x_f_n_row[1829:1658] <= xf_f_n_row[1829:1658];   // pin reg + lockup (ckn25)
    always @(posedge c_ckn26) xf_f_n_row[1999:1830] <= f_n_row[1999:1830]; always @(negedge c_ckn26) x_f_n_row[1999:1830] <= xf_f_n_row[1999:1830];   // pin reg + lockup (ckn26)
    always @(posedge c_ckn27) xf_f_n_row[2169:2000] <= f_n_row[2169:2000]; always @(negedge c_ckn27) x_f_n_row[2169:2000] <= xf_f_n_row[2169:2000];   // pin reg + lockup (ckn27)
    always @(posedge c_ckn28) xf_f_n_row[2255:2170] <= f_n_row[2255:2170]; always @(negedge c_ckn28) x_f_n_row[2255:2170] <= xf_f_n_row[2255:2170];   // pin reg + lockup (ckn28)
    reg [1590:0] xf_e2w, x_e2w;
    always @(posedge c_cke31) xf_e2w[17:0] <= e2w[17:0]; always @(negedge c_cke31) x_e2w[17:0] <= xf_e2w[17:0];   // pin reg + lockup (cke31)
    always @(posedge c_cke32) xf_e2w[124:18] <= e2w[124:18]; always @(negedge c_cke32) x_e2w[124:18] <= xf_e2w[124:18];   // pin reg + lockup (cke32)
    always @(posedge c_cke33) xf_e2w[232:125] <= e2w[232:125]; always @(negedge c_cke33) x_e2w[232:125] <= xf_e2w[232:125];   // pin reg + lockup (cke33)
    always @(posedge c_cke34) xf_e2w[341:233] <= e2w[341:233]; always @(negedge c_cke34) x_e2w[341:233] <= xf_e2w[341:233];   // pin reg + lockup (cke34)
    always @(posedge c_cke35) xf_e2w[451:342] <= e2w[451:342]; always @(negedge c_cke35) x_e2w[451:342] <= xf_e2w[451:342];   // pin reg + lockup (cke35)
    always @(posedge c_cke36) xf_e2w[559:452] <= e2w[559:452]; always @(negedge c_cke36) x_e2w[559:452] <= xf_e2w[559:452];   // pin reg + lockup (cke36)
    always @(posedge c_cke37) xf_e2w[667:560] <= e2w[667:560]; always @(negedge c_cke37) x_e2w[667:560] <= xf_e2w[667:560];   // pin reg + lockup (cke37)
    always @(posedge c_cke38) xf_e2w[775:668] <= e2w[775:668]; always @(negedge c_cke38) x_e2w[775:668] <= xf_e2w[775:668];   // pin reg + lockup (cke38)
    always @(posedge c_cke39) xf_e2w[885:776] <= e2w[885:776]; always @(negedge c_cke39) x_e2w[885:776] <= xf_e2w[885:776];   // pin reg + lockup (cke39)
    always @(posedge c_cke40) xf_e2w[992:886] <= e2w[992:886]; always @(negedge c_cke40) x_e2w[992:886] <= xf_e2w[992:886];   // pin reg + lockup (cke40)
    always @(posedge c_cke41) xf_e2w[1101:993] <= e2w[1101:993]; always @(negedge c_cke41) x_e2w[1101:993] <= xf_e2w[1101:993];   // pin reg + lockup (cke41)
    always @(posedge c_cke42) xf_e2w[1209:1102] <= e2w[1209:1102]; always @(negedge c_cke42) x_e2w[1209:1102] <= xf_e2w[1209:1102];   // pin reg + lockup (cke42)
    always @(posedge c_cke43) xf_e2w[1319:1210] <= e2w[1319:1210]; always @(negedge c_cke43) x_e2w[1319:1210] <= xf_e2w[1319:1210];   // pin reg + lockup (cke43)
    always @(posedge c_cke44) xf_e2w[1427:1320] <= e2w[1427:1320]; always @(negedge c_cke44) x_e2w[1427:1320] <= xf_e2w[1427:1320];   // pin reg + lockup (cke44)
    always @(posedge c_cke45) xf_e2w[1535:1428] <= e2w[1535:1428]; always @(negedge c_cke45) x_e2w[1535:1428] <= xf_e2w[1535:1428];   // pin reg + lockup (cke45)
    always @(posedge c_cke46) xf_e2w[1590:1536] <= e2w[1590:1536]; always @(negedge c_cke46) x_e2w[1590:1536] <= xf_e2w[1590:1536];   // pin reg + lockup (cke46)
    // e2w: [1077:0] f_su_SE[1077:0] (read request [200:0] + placeholders), [1590:1078] NE write bus x_f_n_wr[512:0]
    wire sv; wire [767:0] sd;
    ot_hfd_vm_slice #(.NM(3)) u_slice (.clk(clk), .rst_n(rst_n), .cmd_v(x_f_w_wr[0]), .we(x_f_w_wr[1]), .bank(x_f_w_wr[2]), .addr(x_f_w_wr[9:3]), .wd(x_f_w_wr[777:10]), .rv(sv), .rd(sd));
    wire [2263:0] od_t_n_wr = {1742'd0, x_f_w_wr[1289:778], x_f_w_wr[9:0]};
    wire [2263:0] o_t_n_wr;
    for (genvar k = 0; k <= 5; k = k + 1) begin : g_o_t_n_wr_0
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn1), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 6; k <= 173; k = k + 1) begin : g_o_t_n_wr_6
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn2), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 174; k <= 174; k = k + 1) begin : g_o_t_n_wr_174
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn3), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 175; k <= 175; k = k + 1) begin : g_o_t_n_wr_175
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn2), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 176; k <= 176; k = k + 1) begin : g_o_t_n_wr_176
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn3), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 177; k <= 177; k = k + 1) begin : g_o_t_n_wr_177
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn2), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 178; k <= 343; k = k + 1) begin : g_o_t_n_wr_178
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn3), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 344; k <= 344; k = k + 1) begin : g_o_t_n_wr_344
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn4), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 345; k <= 345; k = k + 1) begin : g_o_t_n_wr_345
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn3), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 346; k <= 346; k = k + 1) begin : g_o_t_n_wr_346
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn4), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 347; k <= 347; k = k + 1) begin : g_o_t_n_wr_347
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn3), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 348; k <= 511; k = k + 1) begin : g_o_t_n_wr_348
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn4), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 512; k <= 512; k = k + 1) begin : g_o_t_n_wr_512
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn5), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 513; k <= 513; k = k + 1) begin : g_o_t_n_wr_513
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn4), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 514; k <= 514; k = k + 1) begin : g_o_t_n_wr_514
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn5), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 515; k <= 515; k = k + 1) begin : g_o_t_n_wr_515
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn4), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 516; k <= 516; k = k + 1) begin : g_o_t_n_wr_516
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn5), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 517; k <= 517; k = k + 1) begin : g_o_t_n_wr_517
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn4), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 518; k <= 521; k = k + 1) begin : g_o_t_n_wr_518
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckn5), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 522; k <= 679; k = k + 1) begin : g_o_t_n_wr_522
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn5), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 680; k <= 680; k = k + 1) begin : g_o_t_n_wr_680
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn6), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 681; k <= 681; k = k + 1) begin : g_o_t_n_wr_681
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn5), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 682; k <= 682; k = k + 1) begin : g_o_t_n_wr_682
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn6), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 683; k <= 683; k = k + 1) begin : g_o_t_n_wr_683
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn5), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 684; k <= 684; k = k + 1) begin : g_o_t_n_wr_684
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn6), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 685; k <= 685; k = k + 1) begin : g_o_t_n_wr_685
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn5), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 686; k <= 686; k = k + 1) begin : g_o_t_n_wr_686
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn6), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 687; k <= 687; k = k + 1) begin : g_o_t_n_wr_687
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn5), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 688; k <= 851; k = k + 1) begin : g_o_t_n_wr_688
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn6), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 852; k <= 852; k = k + 1) begin : g_o_t_n_wr_852
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn7), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 853; k <= 853; k = k + 1) begin : g_o_t_n_wr_853
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn6), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 854; k <= 854; k = k + 1) begin : g_o_t_n_wr_854
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn7), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 855; k <= 855; k = k + 1) begin : g_o_t_n_wr_855
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn6), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 856; k <= 856; k = k + 1) begin : g_o_t_n_wr_856
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn7), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 857; k <= 857; k = k + 1) begin : g_o_t_n_wr_857
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn6), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 858; k <= 1023; k = k + 1) begin : g_o_t_n_wr_858
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn7), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1024; k <= 1024; k = k + 1) begin : g_o_t_n_wr_1024
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn8), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1025; k <= 1025; k = k + 1) begin : g_o_t_n_wr_1025
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn7), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1026; k <= 1026; k = k + 1) begin : g_o_t_n_wr_1026
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn8), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1027; k <= 1027; k = k + 1) begin : g_o_t_n_wr_1027
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn7), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1028; k <= 1028; k = k + 1) begin : g_o_t_n_wr_1028
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn8), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1029; k <= 1029; k = k + 1) begin : g_o_t_n_wr_1029
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn7), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1030; k <= 1197; k = k + 1) begin : g_o_t_n_wr_1030
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn8), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1198; k <= 1368; k = k + 1) begin : g_o_t_n_wr_1198
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn9), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1369; k <= 1536; k = k + 1) begin : g_o_t_n_wr_1369
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn10), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1537; k <= 1537; k = k + 1) begin : g_o_t_n_wr_1537
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn11), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1538; k <= 1538; k = k + 1) begin : g_o_t_n_wr_1538
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn10), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1539; k <= 1704; k = k + 1) begin : g_o_t_n_wr_1539
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn11), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1705; k <= 1705; k = k + 1) begin : g_o_t_n_wr_1705
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn12), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1706; k <= 1706; k = k + 1) begin : g_o_t_n_wr_1706
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn11), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1707; k <= 1707; k = k + 1) begin : g_o_t_n_wr_1707
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn12), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1708; k <= 1708; k = k + 1) begin : g_o_t_n_wr_1708
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn11), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1709; k <= 1874; k = k + 1) begin : g_o_t_n_wr_1709
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn12), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1875; k <= 1875; k = k + 1) begin : g_o_t_n_wr_1875
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn13), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1876; k <= 1876; k = k + 1) begin : g_o_t_n_wr_1876
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn12), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1877; k <= 1877; k = k + 1) begin : g_o_t_n_wr_1877
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn13), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1878; k <= 1878; k = k + 1) begin : g_o_t_n_wr_1878
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn12), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 1879; k <= 2044; k = k + 1) begin : g_o_t_n_wr_1879
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn13), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 2045; k <= 2045; k = k + 1) begin : g_o_t_n_wr_2045
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn14), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 2046; k <= 2046; k = k + 1) begin : g_o_t_n_wr_2046
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn13), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 2047; k <= 2047; k = k + 1) begin : g_o_t_n_wr_2047
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn14), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 2048; k <= 2048; k = k + 1) begin : g_o_t_n_wr_2048
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn13), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 2049; k <= 2049; k = k + 1) begin : g_o_t_n_wr_2049
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn14), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 2050; k <= 2050; k = k + 1) begin : g_o_t_n_wr_2050
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn13), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 2051; k <= 2218; k = k + 1) begin : g_o_t_n_wr_2051
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn14), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 2219; k <= 2219; k = k + 1) begin : g_o_t_n_wr_2219
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn15), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 2220; k <= 2220; k = k + 1) begin : g_o_t_n_wr_2220
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn14), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    for (genvar k = 2221; k <= 2263; k = k + 1) begin : g_o_t_n_wr_2221
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckn15), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    assign t_n_wr = o_t_n_wr;
    wire [2263:0] od_t_w_wr = {472'd0, x_e2w[1590], x_e2w[1589:1078], x_e2w[1077:0], x_e2w[200:0]};
    wire [2263:0] o_t_w_wr;
    for (genvar k = 0; k <= 215; k = k + 1) begin : g_o_t_w_wr_0
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw24), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 216; k <= 426; k = k + 1) begin : g_o_t_w_wr_216
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw25), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 427; k <= 427; k = k + 1) begin : g_o_t_w_wr_427
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw26), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 428; k <= 428; k = k + 1) begin : g_o_t_w_wr_428
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw25), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 429; k <= 429; k = k + 1) begin : g_o_t_w_wr_429
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw26), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 430; k <= 430; k = k + 1) begin : g_o_t_w_wr_430
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw25), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 431; k <= 431; k = k + 1) begin : g_o_t_w_wr_431
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw26), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 432; k <= 432; k = k + 1) begin : g_o_t_w_wr_432
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw25), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 433; k <= 646; k = k + 1) begin : g_o_t_w_wr_433
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw26), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 647; k <= 647; k = k + 1) begin : g_o_t_w_wr_647
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw27), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 648; k <= 648; k = k + 1) begin : g_o_t_w_wr_648
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw26), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 649; k <= 867; k = k + 1) begin : g_o_t_w_wr_649
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw27), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 868; k <= 1083; k = k + 1) begin : g_o_t_w_wr_868
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw28), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1084; k <= 1301; k = k + 1) begin : g_o_t_w_wr_1084
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw29), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1302; k <= 1517; k = k + 1) begin : g_o_t_w_wr_1302
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw30), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1518; k <= 1735; k = k + 1) begin : g_o_t_w_wr_1518
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw31), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1736; k <= 1791; k = k + 1) begin : g_o_t_w_wr_1736
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw32), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1792; k <= 1944; k = k + 1) begin : g_o_t_w_wr_1792
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw32), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1945; k <= 1945; k = k + 1) begin : g_o_t_w_wr_1945
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw33), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1946; k <= 1946; k = k + 1) begin : g_o_t_w_wr_1946
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw32), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1947; k <= 1947; k = k + 1) begin : g_o_t_w_wr_1947
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw33), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1948; k <= 1948; k = k + 1) begin : g_o_t_w_wr_1948
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw32), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1949; k <= 1949; k = k + 1) begin : g_o_t_w_wr_1949
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw33), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1950; k <= 1950; k = k + 1) begin : g_o_t_w_wr_1950
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw32), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 1951; k <= 2164; k = k + 1) begin : g_o_t_w_wr_1951
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw33), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 2165; k <= 2165; k = k + 1) begin : g_o_t_w_wr_2165
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw34), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 2166; k <= 2166; k = k + 1) begin : g_o_t_w_wr_2166
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw33), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 2167; k <= 2167; k = k + 1) begin : g_o_t_w_wr_2167
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw34), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 2168; k <= 2168; k = k + 1) begin : g_o_t_w_wr_2168
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw33), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    for (genvar k = 2169; k <= 2263; k = k + 1) begin : g_o_t_w_wr_2169
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw34), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    assign t_w_wr = o_t_w_wr;
    wire [2255:0] od_t_w_row = {974'd0, x_f_n_row[512:1], x_f_n_row[0], sd, sv};
    wire [2255:0] o_t_w_row;
    for (genvar k = 0; k <= 119; k = k + 1) begin : g_o_t_w_row_0
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw34), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 120; k <= 337; k = k + 1) begin : g_o_t_w_row_120
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw35), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 338; k <= 553; k = k + 1) begin : g_o_t_w_row_338
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw36), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 554; k <= 768; k = k + 1) begin : g_o_t_w_row_554
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw37), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 769; k <= 771; k = k + 1) begin : g_o_t_w_row_769
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw37), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 772; k <= 987; k = k + 1) begin : g_o_t_w_row_772
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw38), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 988; k <= 1200; k = k + 1) begin : g_o_t_w_row_988
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw39), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1201; k <= 1201; k = k + 1) begin : g_o_t_w_row_1201
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw40), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1202; k <= 1202; k = k + 1) begin : g_o_t_w_row_1202
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw39), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1203; k <= 1203; k = k + 1) begin : g_o_t_w_row_1203
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw40), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1204; k <= 1204; k = k + 1) begin : g_o_t_w_row_1204
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw39), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1205; k <= 1281; k = k + 1) begin : g_o_t_w_row_1205
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw40), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1282; k <= 1416; k = k + 1) begin : g_o_t_w_row_1282
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw40), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1417; k <= 1417; k = k + 1) begin : g_o_t_w_row_1417
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw41), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1418; k <= 1418; k = k + 1) begin : g_o_t_w_row_1418
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw40), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1419; k <= 1419; k = k + 1) begin : g_o_t_w_row_1419
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw41), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1420; k <= 1420; k = k + 1) begin : g_o_t_w_row_1420
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw40), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1421; k <= 1639; k = k + 1) begin : g_o_t_w_row_1421
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw41), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1640; k <= 1855; k = k + 1) begin : g_o_t_w_row_1640
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw42), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 1856; k <= 2073; k = k + 1) begin : g_o_t_w_row_1856
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw43), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 2074; k <= 2255; k = k + 1) begin : g_o_t_w_row_2074
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw44), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    assign t_w_row = o_t_w_row;
    assign t_w_ctl = 256'd0;
    // w2e: [2062:0] tap row (SW -> SE x face and -> NE), [3036:2063] x_f_w_wr[2263:1290], [3292:3037] x_f_w_ctl
    wire [3292:0] od_w2e = {x_f_w_ctl[255:0], x_f_w_wr[2263:1290], x_f_w_row[2062:0]};
    wire [3292:0] o_w2e;
    for (genvar k = 0; k <= 57; k = k + 1) begin : g_o_w2e_0
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke1), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 58; k <= 165; k = k + 1) begin : g_o_w2e_58
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke2), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 166; k <= 273; k = k + 1) begin : g_o_w2e_166
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke3), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 274; k <= 380; k = k + 1) begin : g_o_w2e_274
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke4), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 381; k <= 490; k = k + 1) begin : g_o_w2e_381
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke5), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 491; k <= 599; k = k + 1) begin : g_o_w2e_491
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke6), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 600; k <= 707; k = k + 1) begin : g_o_w2e_600
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke7), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 708; k <= 815; k = k + 1) begin : g_o_w2e_708
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke8), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 816; k <= 925; k = k + 1) begin : g_o_w2e_816
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke9), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 926; k <= 1033; k = k + 1) begin : g_o_w2e_926
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke10), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 1034; k <= 1140; k = k + 1) begin : g_o_w2e_1034
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke11), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 1141; k <= 1249; k = k + 1) begin : g_o_w2e_1141
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke12), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 1250; k <= 1359; k = k + 1) begin : g_o_w2e_1250
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke13), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 1360; k <= 1467; k = k + 1) begin : g_o_w2e_1360
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke14), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 1468; k <= 1575; k = k + 1) begin : g_o_w2e_1468
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke15), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 1576; k <= 1683; k = k + 1) begin : g_o_w2e_1576
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke16), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 1684; k <= 1793; k = k + 1) begin : g_o_w2e_1684
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke17), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 1794; k <= 1900; k = k + 1) begin : g_o_w2e_1794
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke18), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 1901; k <= 2008; k = k + 1) begin : g_o_w2e_1901
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke19), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2009; k <= 2117; k = k + 1) begin : g_o_w2e_2009
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke20), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2118; k <= 2118; k = k + 1) begin : g_o_w2e_2118
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke21), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2119; k <= 2119; k = k + 1) begin : g_o_w2e_2119
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke20), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2120; k <= 2227; k = k + 1) begin : g_o_w2e_2120
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke21), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2228; k <= 2335; k = k + 1) begin : g_o_w2e_2228
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke22), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2336; k <= 2443; k = k + 1) begin : g_o_w2e_2336
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke23), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2444; k <= 2553; k = k + 1) begin : g_o_w2e_2444
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke24), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2554; k <= 2661; k = k + 1) begin : g_o_w2e_2554
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke25), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2662; k <= 2768; k = k + 1) begin : g_o_w2e_2662
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke26), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2769; k <= 2877; k = k + 1) begin : g_o_w2e_2769
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke27), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2878; k <= 2987; k = k + 1) begin : g_o_w2e_2878
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke28), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2988; k <= 3095; k = k + 1) begin : g_o_w2e_2988
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke29), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 3096; k <= 3203; k = k + 1) begin : g_o_w2e_3096
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke30), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 3204; k <= 3292; k = k + 1) begin : g_o_w2e_3204
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke31), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    assign w2e = o_w2e;
endmodule
