# generated by make_vm_vcut8.py: die port -> face chain depth
set fc_ps(f_s_ctl) 2
set fc_ps(f_s_row) 2
set fc_ps(f_su_NE) 4
set fc_ps(iNE) 4
set fc_ps(qNE) 4
set fc_ps(t_s_wr) 2
set fc_ps(t_su_NE) 4
set fc_ps(xNE) 4
set fc_ps(w2e) 2
set fc_ps(e2w) 2
