// GENERATED by vm/vcut8/make_vm_vcut8.py (see there): 8-way VM half (vertical cut) hfd_vm_ne_w
module hfd_vm_ne_w (
    input wire [0:0] ck,
    input wire [0:0] ckw0,
    input wire [0:0] ckw1,
    input wire [0:0] ckw2,
    input wire [0:0] ckw3,
    input wire [0:0] cke0,
    input wire [0:0] cke1,
    input wire [0:0] cke2,
    input wire [0:0] cke3,
    input wire [0:0] cks0,
    input wire [0:0] cks1,
    input wire [0:0] rst,
    input wire [2263:0] f_s_wr,
    input wire [255:0] f_w_ctl,
    input wire [2255:0] f_w_row,
    input wire [2263:0] f_w_wr,
    output wire [255:0] t_s_ctl,
    output wire [2255:0] t_s_row,
    output wire [255:0] t_w_ctl,
    output wire [2255:0] t_w_row,
    output wire [2263:0] t_w_wr,
    output wire [2865:0] w2e,
    input wire [2047:0] e2w
);
    wire clk = ck[0];
    wire c_ckw0 = ckw0[0];   // W-face tap leaf (0..250 um)
    wire c_ckw1 = ckw1[0];   // W-face tap leaf (250..500 um)
    wire c_ckw2 = ckw2[0];   // W-face tap leaf (500..750 um)
    wire c_ckw3 = ckw3[0];   // W-face tap leaf (750..1000 um)
    wire c_cke0 = cke0[0];   // E-face tap leaf (0..250 um)
    wire c_cke1 = cke1[0];   // E-face tap leaf (250..500 um)
    wire c_cke2 = cke2[0];   // E-face tap leaf (500..750 um)
    wire c_cke3 = cke3[0];   // E-face tap leaf (750..1000 um)
    wire c_cks0 = cks0[0];   // S-face tap leaf (0..175 um)
    wire c_cks1 = cks1[0];   // S-face tap leaf (175..349 um)
    reg rst_f, rst_l; always @(posedge c_ckw0) rst_f <= rst[0]; always @(negedge c_ckw0) rst_l <= rst_f;
    reg rst_c; always @(posedge clk) rst_c <= rst_l;
    wire rst_n = ~rst_c;
    reg [2263:0] xf_f_s_wr, x_f_s_wr;
    always @(posedge c_cks0) xf_f_s_wr[2263:0] <= f_s_wr[2263:0]; always @(negedge c_cks0) x_f_s_wr[2263:0] <= xf_f_s_wr[2263:0];   // pin reg + lockup (cks0)
    reg [2263:0] xf_f_w_wr, x_f_w_wr;
    always @(posedge c_ckw0) xf_f_w_wr[2172:0] <= f_w_wr[2172:0]; always @(negedge c_ckw0) x_f_w_wr[2172:0] <= xf_f_w_wr[2172:0];   // pin reg + lockup (ckw0)
    always @(posedge c_ckw1) xf_f_w_wr[2173:2173] <= f_w_wr[2173:2173]; always @(negedge c_ckw1) x_f_w_wr[2173:2173] <= xf_f_w_wr[2173:2173];   // pin reg + lockup (ckw1)
    always @(posedge c_ckw0) xf_f_w_wr[2174:2174] <= f_w_wr[2174:2174]; always @(negedge c_ckw0) x_f_w_wr[2174:2174] <= xf_f_w_wr[2174:2174];   // pin reg + lockup (ckw0)
    always @(posedge c_ckw1) xf_f_w_wr[2175:2175] <= f_w_wr[2175:2175]; always @(negedge c_ckw1) x_f_w_wr[2175:2175] <= xf_f_w_wr[2175:2175];   // pin reg + lockup (ckw1)
    always @(posedge c_ckw0) xf_f_w_wr[2176:2176] <= f_w_wr[2176:2176]; always @(negedge c_ckw0) x_f_w_wr[2176:2176] <= xf_f_w_wr[2176:2176];   // pin reg + lockup (ckw0)
    always @(posedge c_ckw1) xf_f_w_wr[2177:2177] <= f_w_wr[2177:2177]; always @(negedge c_ckw1) x_f_w_wr[2177:2177] <= xf_f_w_wr[2177:2177];   // pin reg + lockup (ckw1)
    always @(posedge c_ckw0) xf_f_w_wr[2178:2178] <= f_w_wr[2178:2178]; always @(negedge c_ckw0) x_f_w_wr[2178:2178] <= xf_f_w_wr[2178:2178];   // pin reg + lockup (ckw0)
    always @(posedge c_ckw1) xf_f_w_wr[2263:2179] <= f_w_wr[2263:2179]; always @(negedge c_ckw1) x_f_w_wr[2263:2179] <= xf_f_w_wr[2263:2179];   // pin reg + lockup (ckw1)
    reg [2255:0] xf_f_w_row, x_f_w_row;
    always @(posedge c_ckw1) xf_f_w_row[2255:0] <= f_w_row[2255:0]; always @(negedge c_ckw1) x_f_w_row[2255:0] <= xf_f_w_row[2255:0];   // pin reg + lockup (ckw1)
    reg [2047:0] xf_e2w, x_e2w;
    always @(posedge c_cke2) xf_e2w[893:0] <= e2w[893:0]; always @(negedge c_cke2) x_e2w[893:0] <= xf_e2w[893:0];   // pin reg + lockup (cke2)
    always @(posedge c_cke3) xf_e2w[2047:894] <= e2w[2047:894]; always @(negedge c_cke3) x_e2w[2047:894] <= xf_e2w[2047:894];   // pin reg + lockup (cke3)
    // e2w: [2047:0] f_su_NE after its face chain (east) + the seam: the t_w_row placeholder to NW
    wire sv; wire [511:0] sd;
    ot_hfd_vm_slice #(.NM(2)) u_slice (.clk(clk), .rst_n(rst_n), .cmd_v(x_f_s_wr[0]), .we(x_f_s_wr[1]), .bank(x_f_s_wr[2]), .addr(x_f_s_wr[9:3]), .wd(x_f_s_wr[521:10]), .rv(sv), .rd(sd));
    wire [2255:0] od_t_s_row = {1743'd0, sd, sv};
    wire [2255:0] o_t_s_row;
    for (genvar k = 0; k <= 122; k = k + 1) begin : g_o_t_s_row_0
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cks0), .d(od_t_s_row[k]), .q(o_t_s_row[k]));
    end
    for (genvar k = 123; k <= 2255; k = k + 1) begin : g_o_t_s_row_123
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cks1), .d(od_t_s_row[k]), .q(o_t_s_row[k]));
    end
    assign t_s_row = o_t_s_row;
    wire [2255:0] od_t_w_row = {208'd0, x_e2w[2047:0]};
    wire [2255:0] o_t_w_row;
    for (genvar k = 0; k <= 337; k = k + 1) begin : g_o_t_w_row_0
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw2), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 338; k <= 2047; k = k + 1) begin : g_o_t_w_row_338
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw3), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    for (genvar k = 2048; k <= 2255; k = k + 1) begin : g_o_t_w_row_2048
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw3), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    assign t_w_row = o_t_w_row;
    assign t_s_ctl = 256'd0;
    assign t_w_ctl = 256'd0;
    assign t_w_wr = 2264'd0;
    // w2e: [817:0] x_f_w_wr[817:0] (NW wr placeholder -> t_s_wr), [2865:818] x_f_w_row[2047:0] (-> t_su_NE)
    wire [2865:0] od_w2e = {x_f_w_row[2047:0], x_f_w_wr[817:0]};
    wire [2865:0] o_w2e;
    for (genvar k = 0; k <= 1154; k = k + 1) begin : g_o_w2e_0
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke0), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 1155; k <= 2457; k = k + 1) begin : g_o_w2e_1155
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke1), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 2458; k <= 2865; k = k + 1) begin : g_o_w2e_2458
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke2), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    assign w2e = o_w2e;
endmodule
