// GENERATED by vm/vcut8/make_vm_vcut8.py (see there): 8-way VM half (vertical cut) hfd_vm_se_w
module hfd_vm_se_w (
    input wire [0:0] ck,
    input wire [0:0] rst,
    input wire [255:0] f_n_ctl,
    input wire [2255:0] f_n_row,
    input wire [255:0] f_w_ctl,
    input wire [2255:0] f_w_row,
    input wire [2263:0] f_w_wr,
    output wire [2263:0] t_n_wr,
    output wire [255:0] t_w_ctl,
    output wire [2255:0] t_w_row,
    output wire [2263:0] t_w_wr,
    output wire [3292:0] w2e,
    input wire [1590:0] e2w
);
    wire clk = ck[0];
    reg [1:0] rst_s; always @(posedge clk) rst_s <= {rst_s[0], rst[0]};
    wire rst_n = ~rst_s[1];
    reg [2263:0] x_f_w_wr; always @(posedge clk) x_f_w_wr <= f_w_wr;
    reg [2255:0] x_f_w_row; always @(posedge clk) x_f_w_row <= f_w_row;
    reg [255:0] x_f_w_ctl; always @(posedge clk) x_f_w_ctl <= f_w_ctl;
    reg [2255:0] x_f_n_row; always @(posedge clk) x_f_n_row <= f_n_row;
    reg [1590:0] x_e2w; always @(posedge clk) x_e2w <= e2w;
    // e2w: [1077:0] f_su_SE[1077:0] (read request [200:0] + placeholders), [1590:1078] NE write bus x_f_n_wr[512:0]
    wire sv; wire [767:0] sd;
    ot_hfd_vm_slice #(.NM(3)) u_slice (.clk(clk), .rst_n(rst_n), .cmd_v(x_f_w_wr[0]), .we(x_f_w_wr[1]), .bank(x_f_w_wr[2]), .addr(x_f_w_wr[9:3]), .wd(x_f_w_wr[777:10]), .rv(sv), .rd(sd));
    wire [2263:0] od_t_n_wr = {1742'd0, x_f_w_wr[1289:778], x_f_w_wr[9:0]};
    wire [2263:0] o_t_n_wr;
    for (genvar k = 0; k < 2264; k = k + 1) begin : g_o_t_n_wr
        ot_hfd_oreg1 u (.clk(clk), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    assign t_n_wr = o_t_n_wr;
    wire [2263:0] od_t_w_wr = {472'd0, x_e2w[1590], x_e2w[1589:1078], x_e2w[1077:0], x_e2w[200:0]};
    wire [2263:0] o_t_w_wr;
    for (genvar k = 0; k < 2264; k = k + 1) begin : g_o_t_w_wr
        ot_hfd_oreg1 u (.clk(clk), .d(od_t_w_wr[k]), .q(o_t_w_wr[k]));
    end
    assign t_w_wr = o_t_w_wr;
    wire [2255:0] od_t_w_row = {974'd0, x_f_n_row[512:1], x_f_n_row[0], sd, sv};
    wire [2255:0] o_t_w_row;
    for (genvar k = 0; k < 2256; k = k + 1) begin : g_o_t_w_row
        ot_hfd_oreg1 u (.clk(clk), .d(od_t_w_row[k]), .q(o_t_w_row[k]));
    end
    assign t_w_row = o_t_w_row;
    assign t_w_ctl = 256'd0;
    // w2e: [2062:0] tap row (SW -> SE x face and -> NE), [3036:2063] x_f_w_wr[2263:1290], [3292:3037] x_f_w_ctl
    wire [3292:0] od_w2e = {x_f_w_ctl[255:0], x_f_w_wr[2263:1290], x_f_w_row[2062:0]};
    wire [3292:0] o_w2e;
    for (genvar k = 0; k < 3293; k = k + 1) begin : g_o_w2e
        ot_hfd_oreg1 u (.clk(clk), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    assign w2e = o_w2e;
endmodule
