// GENERATED by vm/vcut8/make_vm_vcut8.py (see there): 8-way VM half (vertical cut) hfd_vm_nw_e
module hfd_vm_nw_e (
    input wire [0:0] ck,
    input wire [0:0] ckw0,
    input wire [0:0] ckw1,
    input wire [0:0] ckw2,
    input wire [0:0] ckw3,
    input wire [0:0] cke0,
    input wire [0:0] cke1,
    input wire [0:0] cke2,
    input wire [0:0] cke3,
    input wire [0:0] ckn0,
    input wire [0:0] ckn1,
    input wire [0:0] cks0,
    input wire [0:0] cks1,
    input wire [0:0] rst,
    input wire [255:0] f_e_ctl,
    input wire [2255:0] f_e_row,
    input wire [2263:0] f_e_wr,
    input wire [2263:0] f_s_wr,
    output wire [255:0] t_e_ctl,
    output wire [2255:0] t_e_row,
    output wire [2263:0] t_e_wr,
    output wire [1023:0] t_quant,
    output wire [255:0] t_s_ctl,
    output wire [2255:0] t_s_row,
    input wire [2047:0] w2e,
    output wire [2047:0] e2w
);
    wire clk = ck[0];
    wire c_ckw0 = ckw0[0];   // W-face tap leaf (0..250 um)
    wire c_ckw1 = ckw1[0];   // W-face tap leaf (250..500 um)
    wire c_ckw2 = ckw2[0];   // W-face tap leaf (500..750 um)
    wire c_ckw3 = ckw3[0];   // W-face tap leaf (750..1000 um)
    wire c_cke0 = cke0[0];   // E-face tap leaf (0..250 um)
    wire c_cke1 = cke1[0];   // E-face tap leaf (250..500 um)
    wire c_cke2 = cke2[0];   // E-face tap leaf (500..750 um)
    wire c_cke3 = cke3[0];   // E-face tap leaf (750..1000 um)
    wire c_ckn0 = ckn0[0];   // N-face tap leaf (0..175 um)
    wire c_ckn1 = ckn1[0];   // N-face tap leaf (175..351 um)
    wire c_cks0 = cks0[0];   // S-face tap leaf (0..175 um)
    wire c_cks1 = cks1[0];   // S-face tap leaf (175..351 um)
    reg rst_f, rst_l; always @(posedge c_ckw0) rst_f <= rst[0]; always @(negedge c_ckw0) rst_l <= rst_f;
    reg rst_c; always @(posedge clk) rst_c <= rst_l;
    wire rst_n = ~rst_c;
    reg [2263:0] xf_f_s_wr, x_f_s_wr;
    always @(posedge c_cks0) xf_f_s_wr[2263:0] <= f_s_wr[2263:0]; always @(negedge c_cks0) x_f_s_wr[2263:0] <= xf_f_s_wr[2263:0];   // pin reg + lockup (cks0)
    reg [2255:0] xf_f_e_row, x_f_e_row;
    always @(posedge c_cke2) xf_f_e_row[337:0] <= f_e_row[337:0]; always @(negedge c_cke2) x_f_e_row[337:0] <= xf_f_e_row[337:0];   // pin reg + lockup (cke2)
    always @(posedge c_cke3) xf_f_e_row[2255:338] <= f_e_row[2255:338]; always @(negedge c_cke3) x_f_e_row[2255:338] <= xf_f_e_row[2255:338];   // pin reg + lockup (cke3)
    reg [2047:0] xf_w2e, x_w2e;
    always @(posedge c_ckw0) xf_w2e[932:0] <= w2e[932:0]; always @(negedge c_ckw0) x_w2e[932:0] <= xf_w2e[932:0];   // pin reg + lockup (ckw0)
    always @(posedge c_ckw1) xf_w2e[2047:933] <= w2e[2047:933]; always @(negedge c_ckw1) x_w2e[2047:933] <= xf_w2e[2047:933];   // pin reg + lockup (ckw1)
    // w2e: [2047:0] f_su_NW after its face chain (west) + the seam: the t_e_row placeholder to NE
    wire sv; wire [767:0] sd;
    ot_hfd_vm_slice #(.NM(3)) u_slice (.clk(clk), .rst_n(rst_n), .cmd_v(x_f_s_wr[0]), .we(x_f_s_wr[1]), .bank(x_f_s_wr[2]), .addr(x_f_s_wr[9:3]), .wd(x_f_s_wr[777:10]), .rv(sv), .rd(sd));
    wire [2255:0] od_t_s_row = {1487'd0, sd, sv};
    wire [2255:0] o_t_s_row;
    for (genvar k = 0; k <= 123; k = k + 1) begin : g_o_t_s_row_0
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cks0), .d(od_t_s_row[k]), .q(o_t_s_row[k]));
    end
    for (genvar k = 124; k <= 2255; k = k + 1) begin : g_o_t_s_row_124
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cks1), .d(od_t_s_row[k]), .q(o_t_s_row[k]));
    end
    assign t_s_row = o_t_s_row;
    wire [2263:0] od_t_e_wr = {1446'd0, x_f_s_wr[1595:778]};
    wire [2263:0] o_t_e_wr;
    for (genvar k = 0; k <= 817; k = k + 1) begin : g_o_t_e_wr_0
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke0), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 818; k <= 2172; k = k + 1) begin : g_o_t_e_wr_818
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cke0), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2173; k <= 2173; k = k + 1) begin : g_o_t_e_wr_2173
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cke1), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2174; k <= 2174; k = k + 1) begin : g_o_t_e_wr_2174
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cke0), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2175; k <= 2175; k = k + 1) begin : g_o_t_e_wr_2175
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cke1), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2176; k <= 2176; k = k + 1) begin : g_o_t_e_wr_2176
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cke0), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2177; k <= 2177; k = k + 1) begin : g_o_t_e_wr_2177
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cke1), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2178; k <= 2178; k = k + 1) begin : g_o_t_e_wr_2178
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cke0), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2179; k <= 2263; k = k + 1) begin : g_o_t_e_wr_2179
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cke1), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    assign t_e_wr = o_t_e_wr;
    wire [2255:0] od_t_e_row = {208'd0, x_w2e[2047:0]};
    wire [2255:0] o_t_e_row;
    for (genvar k = 0; k <= 2047; k = k + 1) begin : g_o_t_e_row_0
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cke1), .d(od_t_e_row[k]), .q(o_t_e_row[k]));
    end
    for (genvar k = 2048; k <= 2255; k = k + 1) begin : g_o_t_e_row_2048
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cke1), .d(od_t_e_row[k]), .q(o_t_e_row[k]));
    end
    assign t_e_row = o_t_e_row;
    assign t_s_ctl = 256'd0;
    assign t_e_ctl = 256'd0;
    wire [1023:0] od_t_quant = x_f_e_row[1023:0];
    wire [1023:0] o_t_quant;
    for (genvar k = 0; k <= 511; k = k + 1) begin : g_o_t_quant_0
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_ckn0), .d(od_t_quant[k]), .q(o_t_quant[k]));
    end
    for (genvar k = 512; k <= 1023; k = k + 1) begin : g_o_t_quant_512
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_ckn1), .d(od_t_quant[k]), .q(o_t_quant[k]));
    end
    assign t_quant = o_t_quant;
    wire [2047:0] od_e2w = x_f_e_row[2047:0];
    wire [2047:0] o_e2w;
    for (genvar k = 0; k <= 1115; k = k + 1) begin : g_o_e2w_0
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw2), .d(od_e2w[k]), .q(o_e2w[k]));
    end
    for (genvar k = 1116; k <= 2047; k = k + 1) begin : g_o_e2w_1116
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_ckw3), .d(od_e2w[k]), .q(o_e2w[k]));
    end
    assign e2w = o_e2w;
endmodule
