// GENERATED by vm/vcut8/make_vm_vcut8.py (see there): 8-way VM half (vertical cut) hfd_vm_nw_w
module hfd_vm_nw_w (
    input wire [0:0] ck,
    input wire [0:0] ckw0,
    input wire [0:0] ckw1,
    input wire [0:0] ckw2,
    input wire [0:0] ckw3,
    input wire [0:0] cke0,
    input wire [0:0] cke1,
    input wire [0:0] cke2,
    input wire [0:0] cke3,
    input wire [0:0] cks0,
    input wire [0:0] cks1,
    input wire [0:0] rst,
    input wire [255:0] f_s_ctl,
    input wire [2255:0] f_s_row,
    input wire [2047:0] f_su_NW,
    input wire [511:0] iNW,
    output wire [581:0] qNW,
    output wire [2263:0] t_s_wr,
    output wire [2047:0] t_su_NW,
    output wire [2067:0] xNW,
    output wire [2047:0] w2e,
    input wire [2047:0] e2w
);
    wire clk = ck[0];
    wire c_ckw0 = ckw0[0];   // W-face tap leaf (0..250 um)
    wire c_ckw1 = ckw1[0];   // W-face tap leaf (250..500 um)
    wire c_ckw2 = ckw2[0];   // W-face tap leaf (500..750 um)
    wire c_ckw3 = ckw3[0];   // W-face tap leaf (750..1000 um)
    wire c_cke0 = cke0[0];   // E-face tap leaf (0..250 um)
    wire c_cke1 = cke1[0];   // E-face tap leaf (250..500 um)
    wire c_cke2 = cke2[0];   // E-face tap leaf (500..750 um)
    wire c_cke3 = cke3[0];   // E-face tap leaf (750..1000 um)
    wire c_cks0 = cks0[0];   // S-face tap leaf (0..175 um)
    wire c_cks1 = cks1[0];   // S-face tap leaf (175..349 um)
    reg rst_f, rst_l; always @(posedge c_ckw0) rst_f <= rst[0]; always @(negedge c_ckw0) rst_l <= rst_f;
    reg rst_c; always @(posedge clk) rst_c <= rst_l;
    wire rst_n = ~rst_c;
    reg [2047:0] i0_f_su_NW, il_f_su_NW;
    always @(posedge c_ckw1) i0_f_su_NW[465:0] <= f_su_NW[465:0]; always @(negedge c_ckw1) il_f_su_NW[465:0] <= i0_f_su_NW[465:0];   // pin reg + lockup (ckw1)
    always @(posedge c_ckw2) i0_f_su_NW[2047:466] <= f_su_NW[2047:466]; always @(negedge c_ckw2) il_f_su_NW[2047:466] <= i0_f_su_NW[2047:466];   // pin reg + lockup (ckw2)
    reg [2047:0] i1_f_su_NW; always @(posedge clk) i1_f_su_NW <= il_f_su_NW;
    reg [2047:0] i_f_su_NW; always @(posedge clk) i_f_su_NW <= i1_f_su_NW;
    reg [511:0] i0_iNW, il_iNW;
    always @(posedge c_ckw0) i0_iNW[511:0] <= iNW[511:0]; always @(negedge c_ckw0) il_iNW[511:0] <= i0_iNW[511:0];   // pin reg + lockup (ckw0)
    reg [511:0] i1_iNW; always @(posedge clk) i1_iNW <= il_iNW;
    reg [511:0] i_iNW; always @(posedge clk) i_iNW <= i1_iNW;
    reg [2255:0] xf_f_s_row, x_f_s_row;
    always @(posedge c_cks0) xf_f_s_row[2255:0] <= f_s_row[2255:0]; always @(negedge c_cks0) x_f_s_row[2255:0] <= xf_f_s_row[2255:0];   // pin reg + lockup (cks0)
    reg [2047:0] xf_e2w, x_e2w;
    always @(posedge c_cke2) xf_e2w[1115:0] <= e2w[1115:0]; always @(negedge c_cke2) x_e2w[1115:0] <= xf_e2w[1115:0];   // pin reg + lockup (cke2)
    always @(posedge c_cke3) xf_e2w[2047:1116] <= e2w[2047:1116]; always @(negedge c_cke3) x_e2w[2047:1116] <= xf_e2w[2047:1116];   // pin reg + lockup (cke3)
    // e2w: [2047:0] x_f_e_row[2047:0] (NE -> NW row placeholder: t_su_NW)
    wire [2263:0] od_t_s_wr = {2047'd0, i_f_su_NW[216:0]};
    wire [2263:0] o_t_s_wr;
    for (genvar k = 0; k <= 130; k = k + 1) begin : g_o_t_s_wr_0
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cks0), .d(od_t_s_wr[k]), .q(o_t_s_wr[k]));
    end
    for (genvar k = 131; k <= 2263; k = k + 1) begin : g_o_t_s_wr_131
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cks1), .d(od_t_s_wr[k]), .q(o_t_s_wr[k]));
    end
    assign t_s_wr = o_t_s_wr;
    wire [2067:0] od_xNW = {5'd0, x_f_s_row[2062:0]};
    wire [2067:0] o_xNW;
    for (genvar k = 0; k <= 578; k = k + 1) begin : g_o_xNW_0
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_ckw0), .d(od_xNW[k]), .q(o_xNW[k]));
    end
    for (genvar k = 579; k <= 579; k = k + 1) begin : g_o_xNW_579
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_ckw1), .d(od_xNW[k]), .q(o_xNW[k]));
    end
    for (genvar k = 580; k <= 580; k = k + 1) begin : g_o_xNW_580
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_ckw0), .d(od_xNW[k]), .q(o_xNW[k]));
    end
    for (genvar k = 581; k <= 2067; k = k + 1) begin : g_o_xNW_581
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_ckw1), .d(od_xNW[k]), .q(o_xNW[k]));
    end
    wire fclk_1; ot_fwd_clk_inv u_fclk_1 (.a(c_ckw1), .y(fclk_1)); assign xNW[2063] = fclk_1;
    wire fclk_2; ot_fwd_clk_inv u_fclk_2 (.a(c_ckw1), .y(fclk_2)); assign xNW[2064] = fclk_2;
    wire fclk_3; ot_fwd_clk_inv u_fclk_3 (.a(c_ckw1), .y(fclk_3)); assign xNW[2065] = fclk_3;
    wire fclk_4; ot_fwd_clk_inv u_fclk_4 (.a(c_ckw1), .y(fclk_4)); assign xNW[2066] = fclk_4;
    wire fclk_5; ot_fwd_clk_inv u_fclk_5 (.a(c_ckw1), .y(fclk_5)); assign xNW[2067] = fclk_5;
    for (genvar k = 0; k < 2063; k = k + 1) begin : g_a_xNW assign xNW[k] = o_xNW[k]; end
    wire [581:0] od_qNW = {2'd0, i_f_su_NW[2047:1980], i_iNW[511:0]};
    wire [581:0] o_qNW;
    for (genvar k = 0; k <= 581; k = k + 1) begin : g_o_qNW_0
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_ckw0), .d(od_qNW[k]), .q(o_qNW[k]));
    end
    wire fclk_6; ot_fwd_clk_inv u_fclk_6 (.a(c_ckw0), .y(fclk_6)); assign qNW[580] = fclk_6;
    wire fclk_7; ot_fwd_clk_inv u_fclk_7 (.a(c_ckw0), .y(fclk_7)); assign qNW[581] = fclk_7;
    for (genvar k = 0; k < 580; k = k + 1) begin : g_a_qNW assign qNW[k] = o_qNW[k]; end
    wire [2047:0] od_t_su_NW = x_e2w[2047:0];
    wire [2047:0] o_t_su_NW;
    for (genvar k = 0; k <= 369; k = k + 1) begin : g_o_t_su_NW_0
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_ckw2), .d(od_t_su_NW[k]), .q(o_t_su_NW[k]));
    end
    for (genvar k = 370; k <= 2047; k = k + 1) begin : g_o_t_su_NW_370
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_ckw3), .d(od_t_su_NW[k]), .q(o_t_su_NW[k]));
    end
    assign t_su_NW = o_t_su_NW;
    wire [2047:0] od_w2e = i_f_su_NW;
    wire [2047:0] o_w2e;
    for (genvar k = 0; k <= 932; k = k + 1) begin : g_o_w2e_0
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cke0), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    for (genvar k = 933; k <= 2047; k = k + 1) begin : g_o_w2e_933
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cke1), .d(od_w2e[k]), .q(o_w2e[k]));
    end
    assign w2e = o_w2e;
endmodule
