// GENERATED by vm/vcut8/make_vm_vcut8.py (see there): 8-way VM half (vertical cut) hfd_vm_sw_e
module hfd_vm_sw_e (
    input wire [0:0] ck,
    input wire [0:0] ckw0,
    input wire [0:0] ckw1,
    input wire [0:0] ckw2,
    input wire [0:0] ckw3,
    input wire [0:0] cke0,
    input wire [0:0] cke1,
    input wire [0:0] cke2,
    input wire [0:0] cke3,
    input wire [0:0] ckn0,
    input wire [0:0] ckn1,
    input wire [0:0] rst,
    input wire [255:0] f_e_ctl,
    input wire [2255:0] f_e_row,
    input wire [2263:0] f_e_wr,
    input wire [255:0] f_n_ctl,
    input wire [2255:0] f_n_row,
    output wire [255:0] t_e_ctl,
    output wire [2255:0] t_e_row,
    output wire [2263:0] t_e_wr,
    output wire [2263:0] t_n_wr,
    input wire [3033:0] w2e,
    output wire [5400:0] e2w
);
    wire clk = ck[0];
    wire c_ckw0 = ckw0[0];   // W-face tap leaf (0..250 um)
    wire c_ckw1 = ckw1[0];   // W-face tap leaf (250..500 um)
    wire c_ckw2 = ckw2[0];   // W-face tap leaf (500..750 um)
    wire c_ckw3 = ckw3[0];   // W-face tap leaf (750..1000 um)
    wire c_cke0 = cke0[0];   // E-face tap leaf (0..250 um)
    wire c_cke1 = cke1[0];   // E-face tap leaf (250..500 um)
    wire c_cke2 = cke2[0];   // E-face tap leaf (500..750 um)
    wire c_cke3 = cke3[0];   // E-face tap leaf (750..1000 um)
    wire c_ckn0 = ckn0[0];   // N-face tap leaf (0..175 um)
    wire c_ckn1 = ckn1[0];   // N-face tap leaf (175..351 um)
    reg rst_f, rst_l; always @(posedge c_ckw0) rst_f <= rst[0]; always @(negedge c_ckw0) rst_l <= rst_f;
    reg rst_c; always @(posedge clk) rst_c <= rst_l;
    wire rst_n = ~rst_c;
    reg [2255:0] xf_f_n_row, xl_f_n_row;
    always @(posedge c_ckn0) xf_f_n_row[123:0] <= f_n_row[123:0]; always @(negedge c_ckn0) xl_f_n_row[123:0] <= xf_f_n_row[123:0];   // pin reg + lockup (ckn0)
    always @(posedge c_ckn1) xf_f_n_row[2255:124] <= f_n_row[2255:124]; always @(negedge c_ckn1) xl_f_n_row[2255:124] <= xf_f_n_row[2255:124];   // pin reg + lockup (ckn1)
    reg [2255:0] x_f_n_row; always @(posedge clk) x_f_n_row <= xl_f_n_row;
    reg [2263:0] xf_f_e_wr, xl_f_e_wr;
    always @(posedge c_cke2) xf_f_e_wr[2263:0] <= f_e_wr[2263:0]; always @(negedge c_cke2) xl_f_e_wr[2263:0] <= xf_f_e_wr[2263:0];   // pin reg + lockup (cke2)
    reg [2263:0] x_f_e_wr; always @(posedge clk) x_f_e_wr <= xl_f_e_wr;
    reg [2255:0] xf_f_e_row, xl_f_e_row;
    always @(posedge c_cke2) xf_f_e_row[337:0] <= f_e_row[337:0]; always @(negedge c_cke2) xl_f_e_row[337:0] <= xf_f_e_row[337:0];   // pin reg + lockup (cke2)
    always @(posedge c_cke3) xf_f_e_row[2255:338] <= f_e_row[2255:338]; always @(negedge c_cke3) xl_f_e_row[2255:338] <= xf_f_e_row[2255:338];   // pin reg + lockup (cke3)
    reg [2255:0] x_f_e_row; always @(posedge clk) x_f_e_row <= xl_f_e_row;
    reg [3033:0] xf_w2e, xl_w2e;
    always @(posedge c_ckw0) xf_w2e[1982:0] <= w2e[1982:0]; always @(negedge c_ckw0) xl_w2e[1982:0] <= xf_w2e[1982:0];   // pin reg + lockup (ckw0)
    always @(posedge c_ckw1) xf_w2e[1983:1983] <= w2e[1983:1983]; always @(negedge c_ckw1) xl_w2e[1983:1983] <= xf_w2e[1983:1983];   // pin reg + lockup (ckw1)
    always @(posedge c_ckw0) xf_w2e[1984:1984] <= w2e[1984:1984]; always @(negedge c_ckw0) xl_w2e[1984:1984] <= xf_w2e[1984:1984];   // pin reg + lockup (ckw0)
    always @(posedge c_ckw1) xf_w2e[1985:1985] <= w2e[1985:1985]; always @(negedge c_ckw1) xl_w2e[1985:1985] <= xf_w2e[1985:1985];   // pin reg + lockup (ckw1)
    always @(posedge c_ckw0) xf_w2e[1986:1986] <= w2e[1986:1986]; always @(negedge c_ckw0) xl_w2e[1986:1986] <= xf_w2e[1986:1986];   // pin reg + lockup (ckw0)
    always @(posedge c_ckw1) xf_w2e[3033:1987] <= w2e[3033:1987]; always @(negedge c_ckw1) xl_w2e[3033:1987] <= xf_w2e[3033:1987];   // pin reg + lockup (ckw1)
    reg [3033:0] x_w2e; always @(posedge clk) x_w2e <= xl_w2e;
    wire [2047:0] fs = x_w2e[2047:0];   // f_su_SW after its face chain (west) + the seam (+2)
    wire [216:0] wq = x_w2e[2264:2048];   // NW write request (f_n_wr[216:0]) after its pin register (west) + the seam (+2)
    wire s0_v = x_w2e[2265]; wire [767:0] s0_d = x_w2e[3033:2266];   // SW slice return (west, over the seam)
    reg [771:0] cfg; always @(posedge clk) cfg <= {cfg[770:0], x_f_e_wr[1791]};
    // write port ONE depth (7): wr_v & co cross the SW seam (+2) after their NW face, wr_data[2047:0] the same seam (+2)
    // after the SW face chain + the two r20 balance regs
    reg [2047:0] wd0_f_su_SW, wd_f_su_SW; always @(posedge clk) begin wd0_f_su_SW <= fs; wd_f_su_SW <= wd0_f_su_SW; end
    wire m_v, m_we, m_bank; wire [6:0] m_addr; wire [2815:0] m_wd; wire m_rd_v; wire [2815:0] m_rd;
    wire wr_ready, wr_ACK_v, rd_ready, native_release, drained, fault; wire [3:0] tap_v; wire [191:0] wr_ACK_owner;
    wire [767:0] tap_owner; wire [4*2063-1:0] tap_data;
    ot_hfd_vm_root_x #(.ENABLE(1), .SEATP(1), .FREG(1)) u_mr (.clk(clk), .por_n(rst_n), .mem_cmd_v(m_v), .mem_cmd_we(m_we), .mem_cmd_bank(m_bank), .mem_cmd_addr(m_addr), .mem_wd(m_wd), .mem_rd_v(m_rd_v), .mem_rd(m_rd), .wr_v(wq[15]), .wr_ready(wr_ready), .wr_bank(wq[16]), .wr_addr(wq[23:17]), .wr_data({wq[14:0], wd_f_su_SW[2047:0]}), .wr_owner(wq[215:24]), .wr_ACK_v(wr_ACK_v), .wr_ACK_ready(wq[216]), .wr_ACK_owner(wr_ACK_owner), .rd_v(x_f_e_wr[0]), .rd_ready(rd_ready), .rd_bank(x_f_e_wr[1]), .rd_addr(x_f_e_wr[8:2]), .rd_owner(x_f_e_wr[200:9]), .tap_v(tap_v), .tap_ready(4'd15), .tap_data(tap_data), .tap_owner(tap_owner), .tap_ACK_v(cfg[3:0]), .tap_ACK_owner(cfg[771:4]), .native_release(native_release), .drained(drained), .fault(fault));
    reg c_v, c_we, c_bank; reg [6:0] c_addr; reg [767:0] c_wd;
    always @(posedge clk) begin c_v <= m_v && rst_n; c_we <= m_we; c_bank <= m_bank; c_addr <= m_addr; c_wd <= m_wd[767:0]; end
    reg [3:0] got; reg [2815:0] hold;
    wire [3:0] arr = {x_f_e_row[769], x_f_e_row[0], x_f_n_row[0], s0_v};
    wire [3:0] got_nx = got | arr;
    assign m_rd_v = &got_nx;
    assign m_rd = {arr[3] ? x_f_e_row[1281:770] : hold[2815:2304], arr[2] ? x_f_e_row[768:1] : hold[2303:1536], arr[1] ? x_f_n_row[768:1] : hold[1535:768], arr[0] ? s0_d : hold[767:0]};
    always @(posedge clk or negedge rst_n) if (!rst_n) got <= 0; else got <= m_rd_v ? 4'd0 : got_nx;
    always @(posedge clk) hold <= m_rd;
    wire [2263:0] od_t_n_wr = {668'd0, fs[2047:1230], m_wd[1535:768], m_addr, m_bank, m_we, m_v};
    wire [2263:0] o_t_n_wr;
    for (genvar k = 0; k <= 2263; k = k + 1) begin : g_o_t_n_wr_0
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_ckn0), .d(od_t_n_wr[k]), .q(o_t_n_wr[k]));
    end
    assign t_n_wr = o_t_n_wr;
    wire [2263:0] od_t_e_wr = {fs[973:0], m_wd[2815:2304], m_wd[2303:1536], m_addr, m_bank, m_we, m_v};
    wire [2263:0] o_t_e_wr;
    for (genvar k = 0; k <= 2172; k = k + 1) begin : g_o_t_e_wr_0
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_cke0), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2173; k <= 2173; k = k + 1) begin : g_o_t_e_wr_2173
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_cke1), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2174; k <= 2174; k = k + 1) begin : g_o_t_e_wr_2174
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_cke0), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2175; k <= 2175; k = k + 1) begin : g_o_t_e_wr_2175
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_cke1), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2176; k <= 2176; k = k + 1) begin : g_o_t_e_wr_2176
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_cke0), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2177; k <= 2177; k = k + 1) begin : g_o_t_e_wr_2177
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_cke1), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2178; k <= 2178; k = k + 1) begin : g_o_t_e_wr_2178
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_cke0), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    for (genvar k = 2179; k <= 2263; k = k + 1) begin : g_o_t_e_wr_2179
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_cke1), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    assign t_e_wr = o_t_e_wr;
    wire [255:0] od_t_e_ctl = fs[1229:974];
    wire [255:0] o_t_e_ctl;
    for (genvar k = 0; k <= 255; k = k + 1) begin : g_o_t_e_ctl_0
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_cke1), .d(od_t_e_ctl[k]), .q(o_t_e_ctl[k]));
    end
    assign t_e_ctl = o_t_e_ctl;
    wire [2255:0] od_t_e_row = {193'd0, tap_data[2062:0]};
    wire [2255:0] o_t_e_row;
    for (genvar k = 0; k <= 2255; k = k + 1) begin : g_o_t_e_row_0
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_cke1), .d(od_t_e_row[k]), .q(o_t_e_row[k]));
    end
    assign t_e_row = o_t_e_row;
    wire [5400:0] od_e2w = {c_wd, c_addr, c_bank, c_we, c_v, x_f_e_wr[1790:1279], {x_f_e_wr[1278:201], tap_owner[767:0], wr_ACK_owner[191:0], tap_v[3:0], fault, drained, native_release, rd_ready, wr_ACK_v, wr_ready}, tap_data[2062:0]};
    wire [5400:0] o_e2w;
    for (genvar k = 0; k <= 1183; k = k + 1) begin : g_o_e2w_0
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_ckw1), .d(od_e2w[k]), .q(o_e2w[k]));
    end
    for (genvar k = 1184; k <= 3415; k = k + 1) begin : g_o_e2w_1184
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_ckw2), .d(od_e2w[k]), .q(o_e2w[k]));
    end
    for (genvar k = 3416; k <= 5400; k = k + 1) begin : g_o_e2w_3416
        ot_hfd_oreg2x u (.clk(clk), .clkf(c_ckw3), .d(od_e2w[k]), .q(o_e2w[k]));
    end
    assign e2w = o_e2w;
endmodule
