// GENERATED by vm/vcut8/make_vm_vcut8.py (see there): 8-way VM half (vertical cut) hfd_vm_ne_e
module hfd_vm_ne_e (
    input wire [0:0] ck,
    input wire [0:0] ckw0,
    input wire [0:0] ckw1,
    input wire [0:0] ckw2,
    input wire [0:0] ckw3,
    input wire [0:0] cke0,
    input wire [0:0] cke1,
    input wire [0:0] cke2,
    input wire [0:0] cke3,
    input wire [0:0] cks0,
    input wire [0:0] cks1,
    input wire [0:0] rst,
    input wire [255:0] f_s_ctl,
    input wire [2255:0] f_s_row,
    input wire [2047:0] f_su_NE,
    input wire [511:0] iNE,
    output wire [581:0] qNE,
    output wire [2263:0] t_s_wr,
    output wire [2047:0] t_su_NE,
    output wire [2067:0] xNE,
    input wire [2865:0] w2e,
    output wire [2047:0] e2w
);
    wire clk = ck[0];
    wire c_ckw0 = ckw0[0];   // W-face tap leaf (0..250 um)
    wire c_ckw1 = ckw1[0];   // W-face tap leaf (250..500 um)
    wire c_ckw2 = ckw2[0];   // W-face tap leaf (500..750 um)
    wire c_ckw3 = ckw3[0];   // W-face tap leaf (750..1000 um)
    wire c_cke0 = cke0[0];   // E-face tap leaf (0..250 um)
    wire c_cke1 = cke1[0];   // E-face tap leaf (250..500 um)
    wire c_cke2 = cke2[0];   // E-face tap leaf (500..750 um)
    wire c_cke3 = cke3[0];   // E-face tap leaf (750..1000 um)
    wire c_cks0 = cks0[0];   // S-face tap leaf (0..175 um)
    wire c_cks1 = cks1[0];   // S-face tap leaf (175..351 um)
    reg rst_f, rst_l; always @(posedge c_ckw0) rst_f <= rst[0]; always @(negedge c_ckw0) rst_l <= rst_f;
    reg rst_c; always @(posedge clk) rst_c <= rst_l;
    wire rst_n = ~rst_c;
    reg [2047:0] i0_f_su_NE, il_f_su_NE;
    always @(posedge c_cke1) i0_f_su_NE[465:0] <= f_su_NE[465:0]; always @(negedge c_cke1) il_f_su_NE[465:0] <= i0_f_su_NE[465:0];   // pin reg + lockup (cke1)
    always @(posedge c_cke2) i0_f_su_NE[2047:466] <= f_su_NE[2047:466]; always @(negedge c_cke2) il_f_su_NE[2047:466] <= i0_f_su_NE[2047:466];   // pin reg + lockup (cke2)
    reg [2047:0] i1_f_su_NE; always @(posedge clk) i1_f_su_NE <= il_f_su_NE;
    reg [2047:0] i_f_su_NE; always @(posedge clk) i_f_su_NE <= i1_f_su_NE;
    reg [511:0] i0_iNE, il_iNE;
    always @(posedge c_cke0) i0_iNE[511:0] <= iNE[511:0]; always @(negedge c_cke0) il_iNE[511:0] <= i0_iNE[511:0];   // pin reg + lockup (cke0)
    reg [511:0] i1_iNE; always @(posedge clk) i1_iNE <= il_iNE;
    reg [511:0] i_iNE; always @(posedge clk) i_iNE <= i1_iNE;
    reg [2255:0] xf_f_s_row, x_f_s_row;
    always @(posedge c_cks0) xf_f_s_row[2255:0] <= f_s_row[2255:0]; always @(negedge c_cks0) x_f_s_row[2255:0] <= xf_f_s_row[2255:0];   // pin reg + lockup (cks0)
    reg [2865:0] xf_w2e, x_w2e;
    always @(posedge c_ckw0) xf_w2e[1154:0] <= w2e[1154:0]; always @(negedge c_ckw0) x_w2e[1154:0] <= xf_w2e[1154:0];   // pin reg + lockup (ckw0)
    always @(posedge c_ckw1) xf_w2e[2457:1155] <= w2e[2457:1155]; always @(negedge c_ckw1) x_w2e[2457:1155] <= xf_w2e[2457:1155];   // pin reg + lockup (ckw1)
    always @(posedge c_ckw2) xf_w2e[2865:2458] <= w2e[2865:2458]; always @(negedge c_ckw2) x_w2e[2865:2458] <= xf_w2e[2865:2458];   // pin reg + lockup (ckw2)
    wire [2067:0] od_xNE = {5'd0, x_f_s_row[2062:0]};
    wire [2067:0] o_xNE;
    for (genvar k = 0; k <= 578; k = k + 1) begin : g_o_xNE_0
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_cke0), .d(od_xNE[k]), .q(o_xNE[k]));
    end
    for (genvar k = 579; k <= 579; k = k + 1) begin : g_o_xNE_579
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_cke1), .d(od_xNE[k]), .q(o_xNE[k]));
    end
    for (genvar k = 580; k <= 580; k = k + 1) begin : g_o_xNE_580
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_cke0), .d(od_xNE[k]), .q(o_xNE[k]));
    end
    for (genvar k = 581; k <= 2067; k = k + 1) begin : g_o_xNE_581
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_cke1), .d(od_xNE[k]), .q(o_xNE[k]));
    end
    wire fclk_1; ot_fwd_clk_inv u_fclk_1 (.a(c_cke1), .y(fclk_1)); assign xNE[2063] = fclk_1;
    wire fclk_2; ot_fwd_clk_inv u_fclk_2 (.a(c_cke1), .y(fclk_2)); assign xNE[2064] = fclk_2;
    wire fclk_3; ot_fwd_clk_inv u_fclk_3 (.a(c_cke1), .y(fclk_3)); assign xNE[2065] = fclk_3;
    wire fclk_4; ot_fwd_clk_inv u_fclk_4 (.a(c_cke1), .y(fclk_4)); assign xNE[2066] = fclk_4;
    wire fclk_5; ot_fwd_clk_inv u_fclk_5 (.a(c_cke1), .y(fclk_5)); assign xNE[2067] = fclk_5;
    for (genvar k = 0; k < 2063; k = k + 1) begin : g_a_xNE assign xNE[k] = o_xNE[k]; end
    wire [581:0] od_qNE = {2'd0, i_f_su_NE[2047:1980], i_iNE[511:0]};
    wire [581:0] o_qNE;
    for (genvar k = 0; k <= 581; k = k + 1) begin : g_o_qNE_0
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_cke0), .d(od_qNE[k]), .q(o_qNE[k]));
    end
    wire fclk_6; ot_fwd_clk_inv u_fclk_6 (.a(c_cke0), .y(fclk_6)); assign qNE[580] = fclk_6;
    wire fclk_7; ot_fwd_clk_inv u_fclk_7 (.a(c_cke0), .y(fclk_7)); assign qNE[581] = fclk_7;
    for (genvar k = 0; k < 580; k = k + 1) begin : g_a_qNE assign qNE[k] = o_qNE[k]; end
    wire [2047:0] od_t_su_NE = x_w2e[2865:818];
    wire [2047:0] o_t_su_NE;
    for (genvar k = 0; k <= 369; k = k + 1) begin : g_o_t_su_NE_0
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_cke2), .d(od_t_su_NE[k]), .q(o_t_su_NE[k]));
    end
    for (genvar k = 370; k <= 2047; k = k + 1) begin : g_o_t_su_NE_370
        ot_hfd_oreg3x u (.clk(clk), .clkf(c_cke3), .d(od_t_su_NE[k]), .q(o_t_su_NE[k]));
    end
    assign t_su_NE = o_t_su_NE;
    wire [2263:0] od_t_s_wr = {933'd0, x_w2e[817:0], i_f_su_NE[0], i_f_su_NE[1535:1024]};
    wire [2263:0] o_t_s_wr;
    for (genvar k = 0; k <= 131; k = k + 1) begin : g_o_t_s_wr_0
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cks0), .d(od_t_s_wr[k]), .q(o_t_s_wr[k]));
    end
    for (genvar k = 132; k <= 512; k = k + 1) begin : g_o_t_s_wr_132
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cks1), .d(od_t_s_wr[k]), .q(o_t_s_wr[k]));
    end
    for (genvar k = 513; k <= 1330; k = k + 1) begin : g_o_t_s_wr_513
        ot_hfd_oreg1y u (.clk(clk), .clkf(c_cks1), .d(od_t_s_wr[k]), .q(o_t_s_wr[k]));
    end
    for (genvar k = 1331; k <= 2263; k = k + 1) begin : g_o_t_s_wr_1331
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_cks1), .d(od_t_s_wr[k]), .q(o_t_s_wr[k]));
    end
    assign t_s_wr = o_t_s_wr;
    wire [2047:0] od_e2w = i_f_su_NE;
    wire [2047:0] o_e2w;
    for (genvar k = 0; k <= 893; k = k + 1) begin : g_o_e2w_0
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw2), .d(od_e2w[k]), .q(o_e2w[k]));
    end
    for (genvar k = 894; k <= 2047; k = k + 1) begin : g_o_e2w_894
        ot_hfd_oreg1x u (.clk(clk), .clkf(c_ckw3), .d(od_e2w[k]), .q(o_e2w[k]));
    end
    assign e2w = o_e2w;
endmodule
