// GENERATED by vm/vcut8/make_vm_vcut8.py (see there): 8-way VM half (vertical cut) hfd_vm_nw_e
module hfd_vm_nw_e (
    input wire [0:0] ck,
    input wire [0:0] rst,
    input wire [255:0] f_e_ctl,
    input wire [2255:0] f_e_row,
    input wire [2263:0] f_e_wr,
    input wire [2263:0] f_s_wr,
    output wire [255:0] t_e_ctl,
    output wire [2255:0] t_e_row,
    output wire [2263:0] t_e_wr,
    output wire [1023:0] t_quant,
    output wire [255:0] t_s_ctl,
    output wire [2255:0] t_s_row,
    input wire [2047:0] w2e,
    output wire [2047:0] e2w
);
    wire clk = ck[0];
    reg [1:0] rst_s; always @(posedge clk) rst_s <= {rst_s[0], rst[0]};
    wire rst_n = ~rst_s[1];
    reg [2263:0] x_f_s_wr; always @(posedge clk) x_f_s_wr <= f_s_wr;
    reg [2255:0] x_f_e_row; always @(posedge clk) x_f_e_row <= f_e_row;
    reg [2047:0] x_w2e; always @(posedge clk) x_w2e <= w2e;
    // w2e: [2047:0] f_su_NW after its face chain (west) + the seam: the t_e_row placeholder to NE
    wire sv; wire [767:0] sd;
    ot_hfd_vm_slice #(.NM(3)) u_slice (.clk(clk), .rst_n(rst_n), .cmd_v(x_f_s_wr[0]), .we(x_f_s_wr[1]), .bank(x_f_s_wr[2]), .addr(x_f_s_wr[9:3]), .wd(x_f_s_wr[777:10]), .rv(sv), .rd(sd));
    wire [2255:0] od_t_s_row = {1487'd0, sd, sv};
    wire [2255:0] o_t_s_row;
    for (genvar k = 0; k < 2256; k = k + 1) begin : g_o_t_s_row
        ot_hfd_oreg1 u (.clk(clk), .d(od_t_s_row[k]), .q(o_t_s_row[k]));
    end
    assign t_s_row = o_t_s_row;
    wire [2263:0] od_t_e_wr = {1446'd0, x_f_s_wr[1595:778]};
    wire [2263:0] o_t_e_wr;
    for (genvar k = 0; k < 2264; k = k + 1) begin : g_o_t_e_wr
        ot_hfd_oreg1 u (.clk(clk), .d(od_t_e_wr[k]), .q(o_t_e_wr[k]));
    end
    assign t_e_wr = o_t_e_wr;
    wire [2255:0] od_t_e_row = {208'd0, x_w2e[2047:0]};
    wire [2255:0] o_t_e_row;
    for (genvar k = 0; k < 2256; k = k + 1) begin : g_o_t_e_row
        ot_hfd_oreg1 u (.clk(clk), .d(od_t_e_row[k]), .q(o_t_e_row[k]));
    end
    assign t_e_row = o_t_e_row;
    assign t_s_ctl = 256'd0;
    assign t_e_ctl = 256'd0;
    wire [1023:0] od_t_quant = x_f_e_row[1023:0];
    wire [1023:0] o_t_quant;
    for (genvar k = 0; k < 1024; k = k + 1) begin : g_o_t_quant
        ot_hfd_oreg3 u (.clk(clk), .d(od_t_quant[k]), .q(o_t_quant[k]));
    end
    assign t_quant = o_t_quant;
    wire [2047:0] od_e2w = x_f_e_row[2047:0];
    wire [2047:0] o_e2w;
    for (genvar k = 0; k < 2048; k = k + 1) begin : g_o_e2w
        ot_hfd_oreg1 u (.clk(clk), .d(od_e2w[k]), .q(o_e2w[k]));
    end
    assign e2w = o_e2w;
endmodule
