// Full36+head source join to the actual finite protected transport.
// Reuses the priced protected model; adds no storage/controller/latency.
// Loaded physical context remains unqualified. Descartes supplies the genuine
// numerical provider at these literal PHY pins; no constant completion/ready.
`timescale 1ns/1ps
module ot_qwen_p0_full_transport_join #(

    parameter integer PROTECTED_STREAM4 = 0, // source candidate, opt-in until owner gates pass
    parameter integer CDC_CONSUMER_JOIN = 0, // existing protected port join only; not raw CDC qualification
    parameter integer BASELINE_AR = 0, // explicit owner selection; off by default
    parameter integer CORE_FS = 833333, CTL_FS = 1024000,
    parameter integer G = 6144,
    parameter integer NW = 18,
    parameter integer SNW = 18,
    parameter integer QWEN_FULLSHAPE = 1,
    parameter integer ME_IDLE_GATE = 1,
    parameter integer SW = 64,
    parameter integer LV = 7,
    parameter integer SMIN = 7,
    parameter integer SMAX = 11,
    parameter integer TCUT = 7,
    parameter integer BD = 1,
    parameter integer XVM = 0,
    parameter integer NWS = 0,
    parameter integer TWS = 0,
    parameter integer ORD = 0,
    parameter integer SCALE_LOCAL = 0,
    parameter integer MEM_EXTRA = 0,
    parameter integer ACC_LAT = 5,
    parameter integer TREE_LAT = 3,
    parameter integer MUL_LAT = 5,
    parameter integer FAST_ISSUE = 0,
    parameter integer KV_PREP = 0,
    parameter integer ENABLE_AR256 = 0,
    parameter integer D = 4,
    // REAL_MEM
    parameter integer REAL_MEM = 1,
    parameter integer SCALE_BANKS = 13,      // 4096-word macros per scale port (>= scale words / 4096)
    parameter integer CROM_WORDS = 1048576,
    parameter integer VM_ELEMS = 177808,
    parameter integer NSTK = 4,                // HBM3E stacks a die
    parameter integer NPC = 32 * NSTK,
    parameter integer HBM_LAYERS = 3,
    parameter integer FILL_LAT = 8,
    parameter integer NRD = 256,
    parameter integer LKA = 512,              // unused (fill-service parameter, kept for the driver)
    parameter integer WBW = 1,                // token write-backs a cycle (distinct PCs)
    parameter integer HBM_PHASE = 0,          // refresh phase of the stack's REFpb schedule
    parameter integer HBM_PULLIN = 0,         // controller refresh pull-in (ot_hbm_r14_stream_pc PULLIN)
    parameter integer EMBED_ROM = 1         // the token's X from the INT8 embedding ROM (stage E); 0: X preloaded
) (
    // Actual registered HCLK PHY return and completion inputs.
    input wire [127:0] h_lv, h_av,
    input wire [128*17-1:0] h_lsec,
    input wire [128*8-1:0] h_lrow,
    input wire [128*256-1:0] h_ldata,
    input wire [128*9-1:0] h_atag,
    input wire phy_fault,
    output wire [127:0] row_v, col_v, col_we, busy,
    output wire [128*3-1:0] row_op,
    output wire [128*5-1:0] row_bank, col_bank, col_col,
    output wire [128*19-1:0] row_row,
    // The actual WR capture follows the column command by one HCLK edge.
    output wire [127:0] h_cv,
    output wire [128*24-1:0] h_csec,
    output wire [128*256-1:0] h_cdata,
    output wire [128*9-1:0] h_ctag,
    output wire [383:0] h_cred_ret,
    output wire [3:0] h_desc_commit, h_go_commit,
    output wire [11:0] h_desc_ordinal, h_go_ordinal,
    output wire transport_quiet,
    input  wire              clk,
    input  wire              hclk, // independent periodic 1024ps controller root
    input  wire              warm_rst_n, // admission pause only; cold POR is rt_rst_n
    output reg               rt_rst_n,
    output reg  [31:0]       cyc,
    output reg               start,
    input  wire [SNW-1:0]    tp_token,
    input  wire [SNW-1:0]    tp_pos,
    input  wire              rm_kv_ideal,       // A/B reference: KV service HBM bypassed (run-time strap)
    input  wire [7:0]        rm_layer,          // the stage's layer (its HBM KV region); 255: no KV (embedding stage)
    input  wire [7:0]        rm_next_layer,     // the layer of the next stage (notice); 255: none
    input  wire              rm_early_go,       // strap: release the next layer's stream at this layer's kv_free
    input  wire              rm_posted_wb,      // strap: posted token write-back
    output wire              kv_wb_busy,        // write-backs outstanding (the host drains before reading HBM)
    input  wire              h_start,
    output wire              me_clk_en,
    output wire              s_done,
    output wire              s_fault,
    output wire              core_fault,
    output wire [SNW-1:0]    seq_ntok,
    output wire [31:0]       seq_nval,
    output wire [31:0]       core_cycles,
    output wire              c_valid,
    input  wire              c_ready,
    output wire [511:0]      c_data,
    output wire              c_last,
    output wire              c_mode,
    output wire [31:0]       c_tag,
    input  wire              r_valid,
    input  wire [511:0]      r_data,
    input  wire              r_last,
    input  wire [((D > 2) ? 2 : 1)-1:0] r_rank,
    input  wire              r_err,
    output wire [11:0]       prog_base,
    // array spine: tile fabric
    output wire              tgo,
    output wire [3*NW+13*24+13-1:0] tb,
    output wire [(1<<SMAX)*32-1:0] xl_d,
    input  wire [(G >> TCUT)*16*32-1:0] t_lvl,
    input  wire              fab_fault,
    // tile KV slice write ports (to ot_qwen_rom_tile_w12 kvw_*)
    output wire [G/4-1:0]     kvw_ce,
    output wire [G/4*7-1:0]   kvw_addr,
    output wire [G/4*512-1:0] kvw_data,
    output wire [G/4*512-1:0] kvw_mask,
    // memory-service status
    output wire              mem_fault,
    output wire [15:0]       kv_fault_code,
    output wire              kv_ok_o,
    output wire              kv_drained_o,
    output wire [31:0]       st_fill_cycles, st_fill_sectors, st_wr_sectors, st_rsp_stall,
    output wire [31:0]       st_kvok_low_desc, st_drain_low, st_wr_lat_max, st_fill_exposed,
    output reg  [31:0]       st_stall_kv, st_stall_drain, st_stall_bridge, st_stall_retire, st_stall_mem
);
    wire producer_clk, producer_hclk, producer_por_n, producer_warm_rst_n;
    wire stream_d_v, stream_go;
    wire stream_d_rdy;
    wire [18:0] stream_d_row;
    wire [10:0] stream_d_n;
    wire [NPC-1:0] stream_l_v, stream_w_room, stream_wd_v;
    wire [NPC-1:0] stream_l_pop, stream_w_v, stream_wd_accept;
    wire [NPC*17-1:0] stream_l_sec;
    wire [NPC*8-1:0] stream_l_row;
    wire [NPC*256-1:0] stream_l_data;
    wire [NPC*24-1:0] stream_w_sec;
    wire [NPC*256-1:0] stream_w_data;
    wire [NPC*9-1:0] stream_w_tag;
    wire [NPC*9-1:0] stream_wd_tag;
    wire producer_fault;
    ot_qwen_p0_full_consumer_exports #(
        .PROTECTED_STREAM4(PROTECTED_STREAM4),
        .BASELINE_AR(BASELINE_AR),
        .CORE_FS(CORE_FS),
        .CTL_FS(CTL_FS),
        .G(G),
        .NW(NW),
        .SNW(SNW),
        .QWEN_FULLSHAPE(QWEN_FULLSHAPE),
        .ME_IDLE_GATE(ME_IDLE_GATE),
        .SW(SW),
        .LV(LV),
        .SMIN(SMIN),
        .SMAX(SMAX),
        .TCUT(TCUT),
        .BD(BD),
        .XVM(XVM),
        .NWS(NWS),
        .TWS(TWS),
        .ORD(ORD),
        .SCALE_LOCAL(SCALE_LOCAL),
        .MEM_EXTRA(MEM_EXTRA),
        .ACC_LAT(ACC_LAT),
        .TREE_LAT(TREE_LAT),
        .MUL_LAT(MUL_LAT),
        .FAST_ISSUE(FAST_ISSUE),
        .KV_PREP(KV_PREP),
        .ENABLE_AR256(ENABLE_AR256),
        .D(D),
        .REAL_MEM(REAL_MEM),
        .SCALE_BANKS(SCALE_BANKS),
        .CROM_WORDS(CROM_WORDS),
        .VM_ELEMS(VM_ELEMS),
        .NSTK(NSTK),
        .NPC(NPC),
        .HBM_LAYERS(HBM_LAYERS),
        .FILL_LAT(FILL_LAT),
        .NRD(NRD),
        .LKA(LKA),
        .WBW(WBW),
        .HBM_PHASE(HBM_PHASE),
        .HBM_PULLIN(HBM_PULLIN),
        .EMBED_ROM(EMBED_ROM)
    ) u_consumer (
        .producer_clk(producer_clk),
        .producer_hclk(producer_hclk),
        .producer_por_n(producer_por_n),
        .producer_warm_rst_n(producer_warm_rst_n),
        .stream_d_v(stream_d_v),
        .stream_go(stream_go),
        .stream_d_rdy(stream_d_rdy),
        .stream_d_row(stream_d_row),
        .stream_d_n(stream_d_n),
        .stream_l_v(stream_l_v),
        .stream_w_room(stream_w_room),
        .stream_wd_v(stream_wd_v),
        .stream_l_pop(stream_l_pop),
        .stream_w_v(stream_w_v),
        .stream_wd_accept(stream_wd_accept),
        .stream_l_sec(stream_l_sec),
        .stream_l_row(stream_l_row),
        .stream_l_data(stream_l_data),
        .stream_w_sec(stream_w_sec),
        .stream_w_data(stream_w_data),
        .stream_w_tag(stream_w_tag),
        .stream_wd_tag(stream_wd_tag),
        .producer_fault(producer_fault),
        .clk(clk),
        .hclk(hclk),
        .warm_rst_n(warm_rst_n),
        .rt_rst_n(rt_rst_n),
        .cyc(cyc),
        .start(start),
        .tp_token(tp_token),
        .tp_pos(tp_pos),
        .rm_kv_ideal(rm_kv_ideal),
        .rm_layer(rm_layer),
        .rm_next_layer(rm_next_layer),
        .rm_early_go(rm_early_go),
        .rm_posted_wb(rm_posted_wb),
        .kv_wb_busy(kv_wb_busy),
        .h_start(h_start),
        .me_clk_en(me_clk_en),
        .s_done(s_done),
        .s_fault(s_fault),
        .core_fault(core_fault),
        .seq_ntok(seq_ntok),
        .seq_nval(seq_nval),
        .core_cycles(core_cycles),
        .c_valid(c_valid),
        .c_ready(c_ready),
        .c_data(c_data),
        .c_last(c_last),
        .c_mode(c_mode),
        .c_tag(c_tag),
        .r_valid(r_valid),
        .r_data(r_data),
        .r_last(r_last),
        .r_rank(r_rank),
        .r_err(r_err),
        .prog_base(prog_base),
        .tgo(tgo),
        .tb(tb),
        .xl_d(xl_d),
        .t_lvl(t_lvl),
        .fab_fault(fab_fault),
        .kvw_ce(kvw_ce),
        .kvw_addr(kvw_addr),
        .kvw_data(kvw_data),
        .kvw_mask(kvw_mask),
        .mem_fault(mem_fault),
        .kv_fault_code(kv_fault_code),
        .kv_ok_o(kv_ok_o),
        .kv_drained_o(kv_drained_o),
        .st_fill_cycles(st_fill_cycles),
        .st_fill_sectors(st_fill_sectors),
        .st_wr_sectors(st_wr_sectors),
        .st_rsp_stall(st_rsp_stall),
        .st_kvok_low_desc(st_kvok_low_desc),
        .st_drain_low(st_drain_low),
        .st_wr_lat_max(st_wr_lat_max),
        .st_fill_exposed(st_fill_exposed),
        .st_stall_kv(st_stall_kv),
        .st_stall_drain(st_stall_drain),
        .st_stall_bridge(st_stall_bridge),
        .st_stall_retire(st_stall_retire),
        .st_stall_mem(st_stall_mem)
    );
    ot_qwen_s4_transport_context #(.ENABLE(PROTECTED_STREAM4),
        .CDC_CONSUMER_JOIN(CDC_CONSUMER_JOIN),
        .MEM_WORDS(HBM_LAYERS*131072), .PHASE(HBM_PHASE)) u_transport (
        .clk(producer_clk),
        .hclk(producer_hclk),
        .rst_n(producer_por_n),
        .warm_rst_n(producer_warm_rst_n),
        .d_v(stream_d_v),
        .go(stream_go),
        .d_row(stream_d_row),
        .d_n(stream_d_n),
        .d_rdy(stream_d_rdy),
        .fault(producer_fault),
        .quiet(transport_quiet),
        .l_v(stream_l_v),
        .l_sec(stream_l_sec),
        .l_row(stream_l_row),
        .l_data(stream_l_data),
        .l_pop(stream_l_pop),
        .w_v(stream_w_v),
        .w_sec(stream_w_sec),
        .w_data(stream_w_data),
        .w_tag(stream_w_tag),
        .w_room(stream_w_room),
        .wd_v(stream_wd_v),
        .wd_tag(stream_wd_tag),
        .wd_accept(stream_wd_accept),
        .h_lv(h_lv),
        .h_av(h_av),
        .h_lsec(h_lsec),
        .h_lrow(h_lrow),
        .h_ldata(h_ldata),
        .h_atag(h_atag),
        .phy_fault(phy_fault),
        .row_v(row_v),
        .col_v(col_v),
        .col_we(col_we),
        .busy(busy),
        .row_op(row_op),
        .row_bank(row_bank),
        .col_bank(col_bank),
        .col_col(col_col),
        .row_row(row_row),
        .h_cv(h_cv),
        .h_csec(h_csec),
        .h_cdata(h_cdata),
        .h_ctag(h_ctag),
        .h_cred_ret(h_cred_ret),
        .h_desc_commit(h_desc_commit),
        .h_go_commit(h_go_commit),
        .h_desc_ordinal(h_desc_ordinal),
        .h_go_ordinal(h_go_ordinal)
    );
endmodule
