`timescale 1ns/1ps
// lockstep bench of hfd_loader (tools/hbm_die_wrap.py --tb): one seed 20261006
module tb_hfd_loader;
    reg [0:0] ck;
    wire [513:0] h;
    reg [513:0] drv_h;
    reg [0:0] rst;
    wire [340:0] t_cmdproc;
    hfd_loader dut(.ck(ck), .h(h), .rst(rst), .t_cmdproc(t_cmdproc));
    assign h[256] = drv_h[256];
    assign h[257] = drv_h[257];
    assign h[258] = drv_h[258];
    assign h[259] = drv_h[259];
    assign h[260] = drv_h[260];
    assign h[261] = drv_h[261];
    assign h[262] = drv_h[262];
    assign h[263] = drv_h[263];
    assign h[264] = drv_h[264];
    assign h[265] = drv_h[265];
    assign h[266] = drv_h[266];
    assign h[267] = drv_h[267];
    assign h[268] = drv_h[268];
    assign h[269] = drv_h[269];
    assign h[270] = drv_h[270];
    assign h[271] = drv_h[271];
    assign h[272] = drv_h[272];
    assign h[273] = drv_h[273];
    assign h[274] = drv_h[274];
    assign h[275] = drv_h[275];
    assign h[276] = drv_h[276];
    assign h[277] = drv_h[277];
    assign h[278] = drv_h[278];
    assign h[279] = drv_h[279];
    assign h[280] = drv_h[280];
    assign h[281] = drv_h[281];
    assign h[282] = drv_h[282];
    assign h[283] = drv_h[283];
    assign h[284] = drv_h[284];
    assign h[285] = drv_h[285];
    assign h[286] = drv_h[286];
    assign h[287] = drv_h[287];
    assign h[288] = drv_h[288];
    assign h[289] = drv_h[289];
    assign h[290] = drv_h[290];
    assign h[291] = drv_h[291];
    assign h[292] = drv_h[292];
    assign h[293] = drv_h[293];
    assign h[294] = drv_h[294];
    assign h[295] = drv_h[295];
    assign h[296] = drv_h[296];
    assign h[297] = drv_h[297];
    assign h[298] = drv_h[298];
    assign h[299] = drv_h[299];
    assign h[300] = drv_h[300];
    assign h[301] = drv_h[301];
    assign h[302] = drv_h[302];
    assign h[303] = drv_h[303];
    assign h[304] = drv_h[304];
    assign h[305] = drv_h[305];
    assign h[306] = drv_h[306];
    assign h[307] = drv_h[307];
    assign h[308] = drv_h[308];
    assign h[309] = drv_h[309];
    assign h[310] = drv_h[310];
    assign h[311] = drv_h[311];
    assign h[312] = drv_h[312];
    assign h[313] = drv_h[313];
    assign h[314] = drv_h[314];
    assign h[315] = drv_h[315];
    assign h[316] = drv_h[316];
    assign h[317] = drv_h[317];
    assign h[318] = drv_h[318];
    assign h[319] = drv_h[319];
    assign h[320] = drv_h[320];
    assign h[321] = drv_h[321];
    assign h[322] = drv_h[322];
    assign h[323] = drv_h[323];
    assign h[324] = drv_h[324];
    assign h[325] = drv_h[325];
    assign h[326] = drv_h[326];
    assign h[327] = drv_h[327];
    assign h[328] = drv_h[328];
    assign h[329] = drv_h[329];
    assign h[330] = drv_h[330];
    assign h[331] = drv_h[331];
    assign h[332] = drv_h[332];
    assign h[333] = drv_h[333];
    assign h[334] = drv_h[334];
    assign h[335] = drv_h[335];
    assign h[336] = drv_h[336];
    assign h[337] = drv_h[337];
    assign h[338] = drv_h[338];
    assign h[339] = drv_h[339];
    assign h[340] = drv_h[340];
    assign h[341] = drv_h[341];
    assign h[342] = drv_h[342];
    assign h[343] = drv_h[343];
    assign h[344] = drv_h[344];
    assign h[345] = drv_h[345];
    assign h[346] = drv_h[346];
    assign h[347] = drv_h[347];
    assign h[348] = drv_h[348];
    assign h[349] = drv_h[349];
    assign h[350] = drv_h[350];
    assign h[351] = drv_h[351];
    assign h[352] = drv_h[352];
    assign h[353] = drv_h[353];
    assign h[354] = drv_h[354];
    assign h[355] = drv_h[355];
    assign h[356] = drv_h[356];
    assign h[357] = drv_h[357];
    assign h[358] = drv_h[358];
    assign h[359] = drv_h[359];
    assign h[360] = drv_h[360];
    assign h[361] = drv_h[361];
    assign h[362] = drv_h[362];
    assign h[363] = drv_h[363];
    assign h[364] = drv_h[364];
    assign h[365] = drv_h[365];
    assign h[366] = drv_h[366];
    assign h[367] = drv_h[367];
    assign h[368] = drv_h[368];
    assign h[369] = drv_h[369];
    assign h[370] = drv_h[370];
    assign h[371] = drv_h[371];
    assign h[372] = drv_h[372];
    assign h[373] = drv_h[373];
    assign h[374] = drv_h[374];
    assign h[375] = drv_h[375];
    assign h[376] = drv_h[376];
    assign h[377] = drv_h[377];
    assign h[378] = drv_h[378];
    assign h[379] = drv_h[379];
    assign h[380] = drv_h[380];
    assign h[381] = drv_h[381];
    assign h[382] = drv_h[382];
    assign h[383] = drv_h[383];
    assign h[384] = drv_h[384];
    assign h[385] = drv_h[385];
    assign h[386] = drv_h[386];
    assign h[387] = drv_h[387];
    assign h[388] = drv_h[388];
    assign h[389] = drv_h[389];
    assign h[390] = drv_h[390];
    assign h[391] = drv_h[391];
    assign h[392] = drv_h[392];
    assign h[393] = drv_h[393];
    assign h[394] = drv_h[394];
    assign h[395] = drv_h[395];
    assign h[396] = drv_h[396];
    assign h[397] = drv_h[397];
    assign h[398] = drv_h[398];
    assign h[399] = drv_h[399];
    assign h[400] = drv_h[400];
    assign h[401] = drv_h[401];
    assign h[402] = drv_h[402];
    assign h[403] = drv_h[403];
    assign h[404] = drv_h[404];
    assign h[405] = drv_h[405];
    assign h[406] = drv_h[406];
    assign h[407] = drv_h[407];
    assign h[408] = drv_h[408];
    assign h[409] = drv_h[409];
    assign h[410] = drv_h[410];
    assign h[411] = drv_h[411];
    assign h[412] = drv_h[412];
    assign h[413] = drv_h[413];
    assign h[414] = drv_h[414];
    assign h[415] = drv_h[415];
    assign h[416] = drv_h[416];
    assign h[417] = drv_h[417];
    assign h[418] = drv_h[418];
    assign h[419] = drv_h[419];
    assign h[420] = drv_h[420];
    assign h[421] = drv_h[421];
    assign h[422] = drv_h[422];
    assign h[423] = drv_h[423];
    assign h[424] = drv_h[424];
    assign h[425] = drv_h[425];
    assign h[426] = drv_h[426];
    assign h[427] = drv_h[427];
    assign h[428] = drv_h[428];
    assign h[429] = drv_h[429];
    assign h[430] = drv_h[430];
    assign h[431] = drv_h[431];
    assign h[432] = drv_h[432];
    assign h[433] = drv_h[433];
    assign h[434] = drv_h[434];
    assign h[435] = drv_h[435];
    assign h[436] = drv_h[436];
    assign h[437] = drv_h[437];
    assign h[438] = drv_h[438];
    assign h[439] = drv_h[439];
    assign h[440] = drv_h[440];
    assign h[441] = drv_h[441];
    assign h[442] = drv_h[442];
    assign h[443] = drv_h[443];
    assign h[444] = drv_h[444];
    assign h[445] = drv_h[445];
    assign h[446] = drv_h[446];
    assign h[447] = drv_h[447];
    assign h[448] = drv_h[448];
    assign h[449] = drv_h[449];
    assign h[450] = drv_h[450];
    assign h[451] = drv_h[451];
    assign h[452] = drv_h[452];
    assign h[453] = drv_h[453];
    assign h[454] = drv_h[454];
    assign h[455] = drv_h[455];
    assign h[456] = drv_h[456];
    assign h[457] = drv_h[457];
    assign h[458] = drv_h[458];
    assign h[459] = drv_h[459];
    assign h[460] = drv_h[460];
    assign h[461] = drv_h[461];
    assign h[462] = drv_h[462];
    assign h[463] = drv_h[463];
    assign h[464] = drv_h[464];
    assign h[465] = drv_h[465];
    assign h[466] = drv_h[466];
    assign h[467] = drv_h[467];
    assign h[468] = drv_h[468];
    assign h[469] = drv_h[469];
    assign h[470] = drv_h[470];
    assign h[471] = drv_h[471];
    assign h[472] = drv_h[472];
    assign h[473] = drv_h[473];
    assign h[474] = drv_h[474];
    assign h[475] = drv_h[475];
    assign h[476] = drv_h[476];
    assign h[477] = drv_h[477];
    assign h[478] = drv_h[478];
    assign h[479] = drv_h[479];
    assign h[480] = drv_h[480];
    assign h[481] = drv_h[481];
    assign h[482] = drv_h[482];
    assign h[483] = drv_h[483];
    assign h[484] = drv_h[484];
    assign h[485] = drv_h[485];
    assign h[486] = drv_h[486];
    assign h[487] = drv_h[487];
    assign h[488] = drv_h[488];
    assign h[489] = drv_h[489];
    assign h[490] = drv_h[490];
    assign h[491] = drv_h[491];
    assign h[492] = drv_h[492];
    assign h[493] = drv_h[493];
    assign h[494] = drv_h[494];
    assign h[495] = drv_h[495];
    assign h[496] = drv_h[496];
    assign h[497] = drv_h[497];
    assign h[498] = drv_h[498];
    assign h[499] = drv_h[499];
    assign h[500] = drv_h[500];
    assign h[501] = drv_h[501];
    assign h[502] = drv_h[502];
    assign h[503] = drv_h[503];
    assign h[504] = drv_h[504];
    assign h[505] = drv_h[505];
    assign h[506] = drv_h[506];
    assign h[507] = drv_h[507];
    assign h[508] = drv_h[508];
    assign h[509] = drv_h[509];
    assign h[510] = drv_h[510];
    assign h[511] = drv_h[511];
    assign h[513] = drv_h[513];
    reg clk = 0; always #0.4165 clk = ~clk;
    always @* ck[0] = clk;
    reg [0:0] d0_ck; always @(posedge clk) d0_ck <= ck;
    reg [0:0] d1_ck; always @(posedge clk) d1_ck <= d0_ck;
    reg [0:0] d_ck; always @(posedge clk) d_ck <= d1_ck;
    reg [513:0] d0_h; always @(posedge clk) d0_h <= drv_h;
    reg [513:0] d1_h; always @(posedge clk) d1_h <= d0_h;
    reg [513:0] d_h; always @(posedge clk) d_h <= d1_h;
    reg [0:0] d0_rst; always @(posedge clk) d0_rst <= rst;
    reg [0:0] d1_rst; always @(posedge clk) d1_rst <= d0_rst;
    reg [0:0] d_rst; always @(posedge clk) d_rst <= d1_rst;
    wire [0:0] r_ld_clk_host;
    assign r_ld_clk_host = dut.w_ld_clk_host;
    wire [0:0] r_ld_rst_host_n;
    assign r_ld_rst_host_n = dut.w_ld_rst_host_n;
    wire [0:0] r_ld_clk_mem;
    assign r_ld_clk_mem = dut.w_ld_clk_mem;
    wire [0:0] r_ld_rst_mem_n;
    assign r_ld_rst_mem_n = dut.w_ld_rst_mem_n;
    wire [0:0] r_ld_s_awvalid;
    assign r_ld_s_awvalid = {d_h[256:256]};
    wire [0:0] r_ld_s_awready;
    reg [0:0] q0_ld_s_awready; always @(posedge clk) q0_ld_s_awready <= r_ld_s_awready;
    reg [0:0] q1_ld_s_awready; always @(posedge clk) q1_ld_s_awready <= q0_ld_s_awready;
    reg [0:0] q_ld_s_awready; always @(posedge clk) q_ld_s_awready <= q1_ld_s_awready;
    wire [11:0] r_ld_s_awaddr;
    assign r_ld_s_awaddr = {d_h[268:257]};
    wire [0:0] r_ld_s_wvalid;
    assign r_ld_s_wvalid = {d_h[269:269]};
    wire [0:0] r_ld_s_wready;
    reg [0:0] q0_ld_s_wready; always @(posedge clk) q0_ld_s_wready <= r_ld_s_wready;
    reg [0:0] q1_ld_s_wready; always @(posedge clk) q1_ld_s_wready <= q0_ld_s_wready;
    reg [0:0] q_ld_s_wready; always @(posedge clk) q_ld_s_wready <= q1_ld_s_wready;
    wire [31:0] r_ld_s_wdata;
    assign r_ld_s_wdata = {d_h[301:270]};
    wire [3:0] r_ld_s_wstrb;
    assign r_ld_s_wstrb = {d_h[305:302]};
    wire [0:0] r_ld_s_bvalid;
    reg [0:0] q0_ld_s_bvalid; always @(posedge clk) q0_ld_s_bvalid <= r_ld_s_bvalid;
    reg [0:0] q1_ld_s_bvalid; always @(posedge clk) q1_ld_s_bvalid <= q0_ld_s_bvalid;
    reg [0:0] q_ld_s_bvalid; always @(posedge clk) q_ld_s_bvalid <= q1_ld_s_bvalid;
    wire [0:0] r_ld_s_bready;
    assign r_ld_s_bready = {d_h[306:306]};
    wire [0:0] r_ld_s_arvalid;
    assign r_ld_s_arvalid = {d_h[307:307]};
    wire [0:0] r_ld_s_arready;
    reg [0:0] q0_ld_s_arready; always @(posedge clk) q0_ld_s_arready <= r_ld_s_arready;
    reg [0:0] q1_ld_s_arready; always @(posedge clk) q1_ld_s_arready <= q0_ld_s_arready;
    reg [0:0] q_ld_s_arready; always @(posedge clk) q_ld_s_arready <= q1_ld_s_arready;
    wire [11:0] r_ld_s_araddr;
    assign r_ld_s_araddr = {d_h[319:308]};
    wire [0:0] r_ld_s_rvalid;
    reg [0:0] q0_ld_s_rvalid; always @(posedge clk) q0_ld_s_rvalid <= r_ld_s_rvalid;
    reg [0:0] q1_ld_s_rvalid; always @(posedge clk) q1_ld_s_rvalid <= q0_ld_s_rvalid;
    reg [0:0] q_ld_s_rvalid; always @(posedge clk) q_ld_s_rvalid <= q1_ld_s_rvalid;
    wire [0:0] r_ld_s_rready;
    assign r_ld_s_rready = {d_h[320:320]};
    wire [31:0] r_ld_s_rdata;
    reg [31:0] q0_ld_s_rdata; always @(posedge clk) q0_ld_s_rdata <= r_ld_s_rdata;
    reg [31:0] q1_ld_s_rdata; always @(posedge clk) q1_ld_s_rdata <= q0_ld_s_rdata;
    reg [31:0] q_ld_s_rdata; always @(posedge clk) q_ld_s_rdata <= q1_ld_s_rdata;
    wire [0:0] r_ld_h_awvalid;
    reg [0:0] q0_ld_h_awvalid; always @(posedge clk) q0_ld_h_awvalid <= r_ld_h_awvalid;
    reg [0:0] q1_ld_h_awvalid; always @(posedge clk) q1_ld_h_awvalid <= q0_ld_h_awvalid;
    reg [0:0] q_ld_h_awvalid; always @(posedge clk) q_ld_h_awvalid <= q1_ld_h_awvalid;
    wire [0:0] r_ld_h_awready;
    assign r_ld_h_awready = {d_h[321:321]};
    wire [11:0] r_ld_h_awaddr;
    reg [11:0] q0_ld_h_awaddr; always @(posedge clk) q0_ld_h_awaddr <= r_ld_h_awaddr;
    reg [11:0] q1_ld_h_awaddr; always @(posedge clk) q1_ld_h_awaddr <= q0_ld_h_awaddr;
    reg [11:0] q_ld_h_awaddr; always @(posedge clk) q_ld_h_awaddr <= q1_ld_h_awaddr;
    wire [0:0] r_ld_h_wvalid;
    reg [0:0] q0_ld_h_wvalid; always @(posedge clk) q0_ld_h_wvalid <= r_ld_h_wvalid;
    reg [0:0] q1_ld_h_wvalid; always @(posedge clk) q1_ld_h_wvalid <= q0_ld_h_wvalid;
    reg [0:0] q_ld_h_wvalid; always @(posedge clk) q_ld_h_wvalid <= q1_ld_h_wvalid;
    wire [0:0] r_ld_h_wready;
    assign r_ld_h_wready = {d_h[322:322]};
    wire [31:0] r_ld_h_wdata;
    reg [31:0] q0_ld_h_wdata; always @(posedge clk) q0_ld_h_wdata <= r_ld_h_wdata;
    reg [31:0] q1_ld_h_wdata; always @(posedge clk) q1_ld_h_wdata <= q0_ld_h_wdata;
    reg [31:0] q_ld_h_wdata; always @(posedge clk) q_ld_h_wdata <= q1_ld_h_wdata;
    wire [3:0] r_ld_h_wstrb;
    reg [3:0] q0_ld_h_wstrb; always @(posedge clk) q0_ld_h_wstrb <= r_ld_h_wstrb;
    reg [3:0] q1_ld_h_wstrb; always @(posedge clk) q1_ld_h_wstrb <= q0_ld_h_wstrb;
    reg [3:0] q_ld_h_wstrb; always @(posedge clk) q_ld_h_wstrb <= q1_ld_h_wstrb;
    wire [0:0] r_ld_h_bvalid;
    assign r_ld_h_bvalid = {d_h[323:323]};
    wire [0:0] r_ld_h_bready;
    reg [0:0] q0_ld_h_bready; always @(posedge clk) q0_ld_h_bready <= r_ld_h_bready;
    reg [0:0] q1_ld_h_bready; always @(posedge clk) q1_ld_h_bready <= q0_ld_h_bready;
    reg [0:0] q_ld_h_bready; always @(posedge clk) q_ld_h_bready <= q1_ld_h_bready;
    wire [0:0] r_ld_h_arvalid;
    reg [0:0] q0_ld_h_arvalid; always @(posedge clk) q0_ld_h_arvalid <= r_ld_h_arvalid;
    reg [0:0] q1_ld_h_arvalid; always @(posedge clk) q1_ld_h_arvalid <= q0_ld_h_arvalid;
    reg [0:0] q_ld_h_arvalid; always @(posedge clk) q_ld_h_arvalid <= q1_ld_h_arvalid;
    wire [0:0] r_ld_h_arready;
    assign r_ld_h_arready = {d_h[324:324]};
    wire [11:0] r_ld_h_araddr;
    reg [11:0] q0_ld_h_araddr; always @(posedge clk) q0_ld_h_araddr <= r_ld_h_araddr;
    reg [11:0] q1_ld_h_araddr; always @(posedge clk) q1_ld_h_araddr <= q0_ld_h_araddr;
    reg [11:0] q_ld_h_araddr; always @(posedge clk) q_ld_h_araddr <= q1_ld_h_araddr;
    wire [0:0] r_ld_h_rvalid;
    assign r_ld_h_rvalid = {d_h[325:325]};
    wire [0:0] r_ld_h_rready;
    reg [0:0] q0_ld_h_rready; always @(posedge clk) q0_ld_h_rready <= r_ld_h_rready;
    reg [0:0] q1_ld_h_rready; always @(posedge clk) q1_ld_h_rready <= q0_ld_h_rready;
    reg [0:0] q_ld_h_rready; always @(posedge clk) q_ld_h_rready <= q1_ld_h_rready;
    wire [31:0] r_ld_h_rdata;
    assign r_ld_h_rdata = {d_h[357:326]};
    wire [0:0] r_ld_h_dma_arvalid;
    assign r_ld_h_dma_arvalid = {d_h[358:358]};
    wire [0:0] r_ld_h_dma_arready;
    reg [0:0] q0_ld_h_dma_arready; always @(posedge clk) q0_ld_h_dma_arready <= r_ld_h_dma_arready;
    reg [0:0] q1_ld_h_dma_arready; always @(posedge clk) q1_ld_h_dma_arready <= q0_ld_h_dma_arready;
    reg [0:0] q_ld_h_dma_arready; always @(posedge clk) q_ld_h_dma_arready <= q1_ld_h_dma_arready;
    wire [63:0] r_ld_h_dma_araddr;
    assign r_ld_h_dma_araddr = {d_h[422:359]};
    wire [0:0] r_ld_h_dma_rvalid;
    reg [0:0] q0_ld_h_dma_rvalid; always @(posedge clk) q0_ld_h_dma_rvalid <= r_ld_h_dma_rvalid;
    reg [0:0] q1_ld_h_dma_rvalid; always @(posedge clk) q1_ld_h_dma_rvalid <= q0_ld_h_dma_rvalid;
    reg [0:0] q_ld_h_dma_rvalid; always @(posedge clk) q_ld_h_dma_rvalid <= q1_ld_h_dma_rvalid;
    wire [0:0] r_ld_h_dma_rready;
    assign r_ld_h_dma_rready = {d_h[423:423]};
    wire [63:0] r_ld_h_dma_rdata;
    reg [63:0] q0_ld_h_dma_rdata; always @(posedge clk) q0_ld_h_dma_rdata <= r_ld_h_dma_rdata;
    reg [63:0] q1_ld_h_dma_rdata; always @(posedge clk) q1_ld_h_dma_rdata <= q0_ld_h_dma_rdata;
    reg [63:0] q_ld_h_dma_rdata; always @(posedge clk) q_ld_h_dma_rdata <= q1_ld_h_dma_rdata;
    wire [1:0] r_ld_h_dma_rresp;
    reg [1:0] q0_ld_h_dma_rresp; always @(posedge clk) q0_ld_h_dma_rresp <= r_ld_h_dma_rresp;
    reg [1:0] q1_ld_h_dma_rresp; always @(posedge clk) q1_ld_h_dma_rresp <= q0_ld_h_dma_rresp;
    reg [1:0] q_ld_h_dma_rresp; always @(posedge clk) q_ld_h_dma_rresp <= q1_ld_h_dma_rresp;
    wire [0:0] r_ld_h_dma_rlast;
    reg [0:0] q0_ld_h_dma_rlast; always @(posedge clk) q0_ld_h_dma_rlast <= r_ld_h_dma_rlast;
    reg [0:0] q1_ld_h_dma_rlast; always @(posedge clk) q1_ld_h_dma_rlast <= q0_ld_h_dma_rlast;
    reg [0:0] q_ld_h_dma_rlast; always @(posedge clk) q_ld_h_dma_rlast <= q1_ld_h_dma_rlast;
    wire [0:0] r_ld_h_dma_awvalid;
    assign r_ld_h_dma_awvalid = {d_h[424:424]};
    wire [0:0] r_ld_h_dma_awready;
    reg [0:0] q0_ld_h_dma_awready; always @(posedge clk) q0_ld_h_dma_awready <= r_ld_h_dma_awready;
    reg [0:0] q1_ld_h_dma_awready; always @(posedge clk) q1_ld_h_dma_awready <= q0_ld_h_dma_awready;
    reg [0:0] q_ld_h_dma_awready; always @(posedge clk) q_ld_h_dma_awready <= q1_ld_h_dma_awready;
    wire [63:0] r_ld_h_dma_awaddr;
    assign r_ld_h_dma_awaddr = {d_h[488:425]};
    wire [0:0] r_ld_h_dma_wvalid;
    assign r_ld_h_dma_wvalid = {d_h[489:489]};
    wire [0:0] r_ld_h_dma_wready;
    reg [0:0] q0_ld_h_dma_wready; always @(posedge clk) q0_ld_h_dma_wready <= r_ld_h_dma_wready;
    reg [0:0] q1_ld_h_dma_wready; always @(posedge clk) q1_ld_h_dma_wready <= q0_ld_h_dma_wready;
    reg [0:0] q_ld_h_dma_wready; always @(posedge clk) q_ld_h_dma_wready <= q1_ld_h_dma_wready;
    wire [63:0] r_ld_h_dma_wdata;
    assign r_ld_h_dma_wdata = dut.w_ld_h_dma_wdata;
    wire [7:0] r_ld_h_dma_wstrb;
    assign r_ld_h_dma_wstrb = {d_h[497:490]};
    wire [0:0] r_ld_h_dma_bvalid;
    reg [0:0] q0_ld_h_dma_bvalid; always @(posedge clk) q0_ld_h_dma_bvalid <= r_ld_h_dma_bvalid;
    reg [0:0] q1_ld_h_dma_bvalid; always @(posedge clk) q1_ld_h_dma_bvalid <= q0_ld_h_dma_bvalid;
    reg [0:0] q_ld_h_dma_bvalid; always @(posedge clk) q_ld_h_dma_bvalid <= q1_ld_h_dma_bvalid;
    wire [0:0] r_ld_h_dma_bready;
    assign r_ld_h_dma_bready = {d_h[498:498]};
    wire [1:0] r_ld_h_dma_bresp;
    reg [1:0] q0_ld_h_dma_bresp; always @(posedge clk) q0_ld_h_dma_bresp <= r_ld_h_dma_bresp;
    reg [1:0] q1_ld_h_dma_bresp; always @(posedge clk) q1_ld_h_dma_bresp <= q0_ld_h_dma_bresp;
    reg [1:0] q_ld_h_dma_bresp; always @(posedge clk) q_ld_h_dma_bresp <= q1_ld_h_dma_bresp;
    wire [0:0] r_ld_m_arvalid;
    reg [0:0] q0_ld_m_arvalid; always @(posedge clk) q0_ld_m_arvalid <= r_ld_m_arvalid;
    reg [0:0] q1_ld_m_arvalid; always @(posedge clk) q1_ld_m_arvalid <= q0_ld_m_arvalid;
    reg [0:0] q_ld_m_arvalid; always @(posedge clk) q_ld_m_arvalid <= q1_ld_m_arvalid;
    wire [0:0] r_ld_m_arready;
    assign r_ld_m_arready = dut.w_ld_m_arready;
    wire [63:0] r_ld_m_araddr;
    reg [63:0] q0_ld_m_araddr; always @(posedge clk) q0_ld_m_araddr <= r_ld_m_araddr;
    reg [63:0] q1_ld_m_araddr; always @(posedge clk) q1_ld_m_araddr <= q0_ld_m_araddr;
    reg [63:0] q_ld_m_araddr; always @(posedge clk) q_ld_m_araddr <= q1_ld_m_araddr;
    wire [7:0] r_ld_m_arlen;
    reg [7:0] q0_ld_m_arlen; always @(posedge clk) q0_ld_m_arlen <= r_ld_m_arlen;
    reg [7:0] q1_ld_m_arlen; always @(posedge clk) q1_ld_m_arlen <= q0_ld_m_arlen;
    reg [7:0] q_ld_m_arlen; always @(posedge clk) q_ld_m_arlen <= q1_ld_m_arlen;
    wire [2:0] r_ld_m_arsize;
    reg [2:0] q0_ld_m_arsize; always @(posedge clk) q0_ld_m_arsize <= r_ld_m_arsize;
    reg [2:0] q1_ld_m_arsize; always @(posedge clk) q1_ld_m_arsize <= q0_ld_m_arsize;
    reg [2:0] q_ld_m_arsize; always @(posedge clk) q_ld_m_arsize <= q1_ld_m_arsize;
    wire [0:0] r_ld_m_rvalid;
    assign r_ld_m_rvalid = dut.w_ld_m_rvalid;
    wire [0:0] r_ld_m_rready;
    reg [0:0] q0_ld_m_rready; always @(posedge clk) q0_ld_m_rready <= r_ld_m_rready;
    reg [0:0] q1_ld_m_rready; always @(posedge clk) q1_ld_m_rready <= q0_ld_m_rready;
    reg [0:0] q_ld_m_rready; always @(posedge clk) q_ld_m_rready <= q1_ld_m_rready;
    wire [63:0] r_ld_m_rdata;
    assign r_ld_m_rdata = dut.w_ld_m_rdata;
    wire [1:0] r_ld_m_rresp;
    assign r_ld_m_rresp = dut.w_ld_m_rresp;
    wire [0:0] r_ld_m_rlast;
    assign r_ld_m_rlast = dut.w_ld_m_rlast;
    wire [0:0] r_ld_m_awvalid;
    reg [0:0] q0_ld_m_awvalid; always @(posedge clk) q0_ld_m_awvalid <= r_ld_m_awvalid;
    reg [0:0] q1_ld_m_awvalid; always @(posedge clk) q1_ld_m_awvalid <= q0_ld_m_awvalid;
    reg [0:0] q_ld_m_awvalid; always @(posedge clk) q_ld_m_awvalid <= q1_ld_m_awvalid;
    wire [0:0] r_ld_m_awready;
    assign r_ld_m_awready = dut.w_ld_m_awready;
    wire [63:0] r_ld_m_awaddr;
    reg [63:0] q0_ld_m_awaddr; always @(posedge clk) q0_ld_m_awaddr <= r_ld_m_awaddr;
    reg [63:0] q1_ld_m_awaddr; always @(posedge clk) q1_ld_m_awaddr <= q0_ld_m_awaddr;
    reg [63:0] q_ld_m_awaddr; always @(posedge clk) q_ld_m_awaddr <= q1_ld_m_awaddr;
    wire [7:0] r_ld_m_awlen;
    reg [7:0] q0_ld_m_awlen; always @(posedge clk) q0_ld_m_awlen <= r_ld_m_awlen;
    reg [7:0] q1_ld_m_awlen; always @(posedge clk) q1_ld_m_awlen <= q0_ld_m_awlen;
    reg [7:0] q_ld_m_awlen; always @(posedge clk) q_ld_m_awlen <= q1_ld_m_awlen;
    wire [2:0] r_ld_m_awsize;
    reg [2:0] q0_ld_m_awsize; always @(posedge clk) q0_ld_m_awsize <= r_ld_m_awsize;
    reg [2:0] q1_ld_m_awsize; always @(posedge clk) q1_ld_m_awsize <= q0_ld_m_awsize;
    reg [2:0] q_ld_m_awsize; always @(posedge clk) q_ld_m_awsize <= q1_ld_m_awsize;
    wire [0:0] r_ld_m_wvalid;
    reg [0:0] q0_ld_m_wvalid; always @(posedge clk) q0_ld_m_wvalid <= r_ld_m_wvalid;
    reg [0:0] q1_ld_m_wvalid; always @(posedge clk) q1_ld_m_wvalid <= q0_ld_m_wvalid;
    reg [0:0] q_ld_m_wvalid; always @(posedge clk) q_ld_m_wvalid <= q1_ld_m_wvalid;
    wire [0:0] r_ld_m_wready;
    assign r_ld_m_wready = dut.w_ld_m_wready;
    wire [63:0] r_ld_m_wdata;
    reg [63:0] q0_ld_m_wdata; always @(posedge clk) q0_ld_m_wdata <= r_ld_m_wdata;
    reg [63:0] q1_ld_m_wdata; always @(posedge clk) q1_ld_m_wdata <= q0_ld_m_wdata;
    reg [63:0] q_ld_m_wdata; always @(posedge clk) q_ld_m_wdata <= q1_ld_m_wdata;
    wire [7:0] r_ld_m_wstrb;
    reg [7:0] q0_ld_m_wstrb; always @(posedge clk) q0_ld_m_wstrb <= r_ld_m_wstrb;
    reg [7:0] q1_ld_m_wstrb; always @(posedge clk) q1_ld_m_wstrb <= q0_ld_m_wstrb;
    reg [7:0] q_ld_m_wstrb; always @(posedge clk) q_ld_m_wstrb <= q1_ld_m_wstrb;
    wire [0:0] r_ld_m_wlast;
    reg [0:0] q0_ld_m_wlast; always @(posedge clk) q0_ld_m_wlast <= r_ld_m_wlast;
    reg [0:0] q1_ld_m_wlast; always @(posedge clk) q1_ld_m_wlast <= q0_ld_m_wlast;
    reg [0:0] q_ld_m_wlast; always @(posedge clk) q_ld_m_wlast <= q1_ld_m_wlast;
    wire [0:0] r_ld_m_bvalid;
    assign r_ld_m_bvalid = dut.w_ld_m_bvalid;
    wire [0:0] r_ld_m_bready;
    reg [0:0] q0_ld_m_bready; always @(posedge clk) q0_ld_m_bready <= r_ld_m_bready;
    reg [0:0] q1_ld_m_bready; always @(posedge clk) q1_ld_m_bready <= q0_ld_m_bready;
    reg [0:0] q_ld_m_bready; always @(posedge clk) q_ld_m_bready <= q1_ld_m_bready;
    wire [1:0] r_ld_m_bresp;
    assign r_ld_m_bresp = dut.w_ld_m_bresp;
    wire [1:0] r_ld_req_v;
    reg [1:0] q0_ld_req_v; always @(posedge clk) q0_ld_req_v <= r_ld_req_v;
    reg [1:0] q1_ld_req_v; always @(posedge clk) q1_ld_req_v <= q0_ld_req_v;
    reg [1:0] q_ld_req_v; always @(posedge clk) q_ld_req_v <= q1_ld_req_v;
    wire [1:0] r_ld_req_rdy;
    assign r_ld_req_rdy = dut.w_ld_req_rdy;
    wire [1:0] r_ld_req_we;
    reg [1:0] q0_ld_req_we; always @(posedge clk) q0_ld_req_we <= r_ld_req_we;
    reg [1:0] q1_ld_req_we; always @(posedge clk) q1_ld_req_we <= q0_ld_req_we;
    reg [1:0] q_ld_req_we; always @(posedge clk) q_ld_req_we <= q1_ld_req_we;
    wire [63:0] r_ld_req_addr;
    reg [63:0] q0_ld_req_addr; always @(posedge clk) q0_ld_req_addr <= r_ld_req_addr;
    reg [63:0] q1_ld_req_addr; always @(posedge clk) q1_ld_req_addr <= q0_ld_req_addr;
    reg [63:0] q_ld_req_addr; always @(posedge clk) q_ld_req_addr <= q1_ld_req_addr;
    wire [511:0] r_ld_req_wdata;
    reg [511:0] q0_ld_req_wdata; always @(posedge clk) q0_ld_req_wdata <= r_ld_req_wdata;
    reg [511:0] q1_ld_req_wdata; always @(posedge clk) q1_ld_req_wdata <= q0_ld_req_wdata;
    reg [511:0] q_ld_req_wdata; always @(posedge clk) q_ld_req_wdata <= q1_ld_req_wdata;
    wire [63:0] r_ld_req_wstrb;
    reg [63:0] q0_ld_req_wstrb; always @(posedge clk) q0_ld_req_wstrb <= r_ld_req_wstrb;
    reg [63:0] q1_ld_req_wstrb; always @(posedge clk) q1_ld_req_wstrb <= q0_ld_req_wstrb;
    reg [63:0] q_ld_req_wstrb; always @(posedge clk) q_ld_req_wstrb <= q1_ld_req_wstrb;
    wire [31:0] r_ld_req_tag;
    reg [31:0] q0_ld_req_tag; always @(posedge clk) q0_ld_req_tag <= r_ld_req_tag;
    reg [31:0] q1_ld_req_tag; always @(posedge clk) q1_ld_req_tag <= q0_ld_req_tag;
    reg [31:0] q_ld_req_tag; always @(posedge clk) q_ld_req_tag <= q1_ld_req_tag;
    wire [1:0] r_ld_rsp_v;
    assign r_ld_rsp_v = dut.w_ld_rsp_v;
    wire [1:0] r_ld_rsp_rdy;
    reg [1:0] q0_ld_rsp_rdy; always @(posedge clk) q0_ld_rsp_rdy <= r_ld_rsp_rdy;
    reg [1:0] q1_ld_rsp_rdy; always @(posedge clk) q1_ld_rsp_rdy <= q0_ld_rsp_rdy;
    reg [1:0] q_ld_rsp_rdy; always @(posedge clk) q_ld_rsp_rdy <= q1_ld_rsp_rdy;
    wire [1:0] r_ld_rsp_we;
    assign r_ld_rsp_we = dut.w_ld_rsp_we;
    wire [31:0] r_ld_rsp_tag;
    assign r_ld_rsp_tag = dut.w_ld_rsp_tag;
    wire [511:0] r_ld_rsp_data;
    assign r_ld_rsp_data = dut.w_ld_rsp_data;
    wire [0:0] r_ld_irq;
    reg [0:0] q0_ld_irq; always @(posedge clk) q0_ld_irq <= r_ld_irq;
    reg [0:0] q1_ld_irq; always @(posedge clk) q1_ld_irq <= q0_ld_irq;
    reg [0:0] q_ld_irq; always @(posedge clk) q_ld_irq <= q1_ld_irq;
    wire [0:0] r_ld_fault;
    reg [0:0] q0_ld_fault; always @(posedge clk) q0_ld_fault <= r_ld_fault;
    reg [0:0] q1_ld_fault; always @(posedge clk) q1_ld_fault <= q0_ld_fault;
    reg [0:0] q_ld_fault; always @(posedge clk) q_ld_fault <= q1_ld_fault;
    ot_hfd_loader_host_m #(.ENABLE(1), .ND(2)) ref_ld (.clk_host(r_ld_clk_host), .rst_host_n(r_ld_rst_host_n), .clk_mem(r_ld_clk_mem), .rst_mem_n(r_ld_rst_mem_n), .s_awvalid(r_ld_s_awvalid), .s_awready(r_ld_s_awready), .s_awaddr(r_ld_s_awaddr), .s_wvalid(r_ld_s_wvalid), .s_wready(r_ld_s_wready), .s_wdata(r_ld_s_wdata), .s_wstrb(r_ld_s_wstrb), .s_bvalid(r_ld_s_bvalid), .s_bready(r_ld_s_bready), .s_arvalid(r_ld_s_arvalid), .s_arready(r_ld_s_arready), .s_araddr(r_ld_s_araddr), .s_rvalid(r_ld_s_rvalid), .s_rready(r_ld_s_rready), .s_rdata(r_ld_s_rdata), .h_awvalid(r_ld_h_awvalid), .h_awready(r_ld_h_awready), .h_awaddr(r_ld_h_awaddr), .h_wvalid(r_ld_h_wvalid), .h_wready(r_ld_h_wready), .h_wdata(r_ld_h_wdata), .h_wstrb(r_ld_h_wstrb), .h_bvalid(r_ld_h_bvalid), .h_bready(r_ld_h_bready), .h_arvalid(r_ld_h_arvalid), .h_arready(r_ld_h_arready), .h_araddr(r_ld_h_araddr), .h_rvalid(r_ld_h_rvalid), .h_rready(r_ld_h_rready), .h_rdata(r_ld_h_rdata), .h_dma_arvalid(r_ld_h_dma_arvalid), .h_dma_arready(r_ld_h_dma_arready), .h_dma_araddr(r_ld_h_dma_araddr), .h_dma_rvalid(r_ld_h_dma_rvalid), .h_dma_rready(r_ld_h_dma_rready), .h_dma_rdata(r_ld_h_dma_rdata), .h_dma_rresp(r_ld_h_dma_rresp), .h_dma_rlast(r_ld_h_dma_rlast), .h_dma_awvalid(r_ld_h_dma_awvalid), .h_dma_awready(r_ld_h_dma_awready), .h_dma_awaddr(r_ld_h_dma_awaddr), .h_dma_wvalid(r_ld_h_dma_wvalid), .h_dma_wready(r_ld_h_dma_wready), .h_dma_wdata(r_ld_h_dma_wdata), .h_dma_wstrb(r_ld_h_dma_wstrb), .h_dma_bvalid(r_ld_h_dma_bvalid), .h_dma_bready(r_ld_h_dma_bready), .h_dma_bresp(r_ld_h_dma_bresp), .m_arvalid(r_ld_m_arvalid), .m_arready(r_ld_m_arready), .m_araddr(r_ld_m_araddr), .m_arlen(r_ld_m_arlen), .m_arsize(r_ld_m_arsize), .m_rvalid(r_ld_m_rvalid), .m_rready(r_ld_m_rready), .m_rdata(r_ld_m_rdata), .m_rresp(r_ld_m_rresp), .m_rlast(r_ld_m_rlast), .m_awvalid(r_ld_m_awvalid), .m_awready(r_ld_m_awready), .m_awaddr(r_ld_m_awaddr), .m_awlen(r_ld_m_awlen), .m_awsize(r_ld_m_awsize), .m_wvalid(r_ld_m_wvalid), .m_wready(r_ld_m_wready), .m_wdata(r_ld_m_wdata), .m_wstrb(r_ld_m_wstrb), .m_wlast(r_ld_m_wlast), .m_bvalid(r_ld_m_bvalid), .m_bready(r_ld_m_bready), .m_bresp(r_ld_m_bresp), .req_v(r_ld_req_v), .req_rdy(r_ld_req_rdy), .req_we(r_ld_req_we), .req_addr(r_ld_req_addr), .req_wdata(r_ld_req_wdata), .req_wstrb(r_ld_req_wstrb), .req_tag(r_ld_req_tag), .rsp_v(r_ld_rsp_v), .rsp_rdy(r_ld_rsp_rdy), .rsp_we(r_ld_rsp_we), .rsp_tag(r_ld_rsp_tag), .rsp_data(r_ld_rsp_data), .irq(r_ld_irq), .fault(r_ld_fault));
    integer err = 0, nchk = 0, cyc;
    integer seed = 20261006;
    task automatic randomize_inputs; begin
        drv_h[31:0] = $urandom(seed); seed = seed + 1;
        drv_h[63:32] = $urandom(seed); seed = seed + 1;
        drv_h[95:64] = $urandom(seed); seed = seed + 1;
        drv_h[127:96] = $urandom(seed); seed = seed + 1;
        drv_h[159:128] = $urandom(seed); seed = seed + 1;
        drv_h[191:160] = $urandom(seed); seed = seed + 1;
        drv_h[223:192] = $urandom(seed); seed = seed + 1;
        drv_h[255:224] = $urandom(seed); seed = seed + 1;
        drv_h[287:256] = $urandom(seed); seed = seed + 1;
        drv_h[319:288] = $urandom(seed); seed = seed + 1;
        drv_h[351:320] = $urandom(seed); seed = seed + 1;
        drv_h[383:352] = $urandom(seed); seed = seed + 1;
        drv_h[415:384] = $urandom(seed); seed = seed + 1;
        drv_h[447:416] = $urandom(seed); seed = seed + 1;
        drv_h[479:448] = $urandom(seed); seed = seed + 1;
        drv_h[511:480] = $urandom(seed); seed = seed + 1;
        drv_h[513:512] = $urandom(seed); seed = seed + 1;
    end endtask
    initial begin
        rst = 1;
        randomize_inputs;
        repeat (8) @(posedge clk);
        #0.05 rst = 0;
        for (cyc = 0; cyc < 400; cyc = cyc + 1) begin
            @(negedge clk);
            nchk = nchk + 1; if (h[0:0] !== q_ld_s_awready[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[0:0] %h ref %h cyc %0d", h[0:0], q_ld_s_awready[0:0], cyc); end
            nchk = nchk + 1; if (h[1:1] !== q_ld_s_wready[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[1:1] %h ref %h cyc %0d", h[1:1], q_ld_s_wready[0:0], cyc); end
            nchk = nchk + 1; if (h[2:2] !== q_ld_s_bvalid[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[2:2] %h ref %h cyc %0d", h[2:2], q_ld_s_bvalid[0:0], cyc); end
            nchk = nchk + 1; if (h[3:3] !== q_ld_s_arready[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[3:3] %h ref %h cyc %0d", h[3:3], q_ld_s_arready[0:0], cyc); end
            nchk = nchk + 1; if (h[4:4] !== q_ld_s_rvalid[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[4:4] %h ref %h cyc %0d", h[4:4], q_ld_s_rvalid[0:0], cyc); end
            nchk = nchk + 1; if (h[36:5] !== q_ld_s_rdata[31:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[36:5] %h ref %h cyc %0d", h[36:5], q_ld_s_rdata[31:0], cyc); end
            nchk = nchk + 1; if (h[37:37] !== q_ld_h_awvalid[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[37:37] %h ref %h cyc %0d", h[37:37], q_ld_h_awvalid[0:0], cyc); end
            nchk = nchk + 1; if (h[49:38] !== q_ld_h_awaddr[11:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[49:38] %h ref %h cyc %0d", h[49:38], q_ld_h_awaddr[11:0], cyc); end
            nchk = nchk + 1; if (h[50:50] !== q_ld_h_wvalid[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[50:50] %h ref %h cyc %0d", h[50:50], q_ld_h_wvalid[0:0], cyc); end
            nchk = nchk + 1; if (h[82:51] !== q_ld_h_wdata[31:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[82:51] %h ref %h cyc %0d", h[82:51], q_ld_h_wdata[31:0], cyc); end
            nchk = nchk + 1; if (h[86:83] !== q_ld_h_wstrb[3:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[86:83] %h ref %h cyc %0d", h[86:83], q_ld_h_wstrb[3:0], cyc); end
            nchk = nchk + 1; if (h[87:87] !== q_ld_h_bready[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[87:87] %h ref %h cyc %0d", h[87:87], q_ld_h_bready[0:0], cyc); end
            nchk = nchk + 1; if (h[88:88] !== q_ld_h_arvalid[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[88:88] %h ref %h cyc %0d", h[88:88], q_ld_h_arvalid[0:0], cyc); end
            nchk = nchk + 1; if (h[100:89] !== q_ld_h_araddr[11:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[100:89] %h ref %h cyc %0d", h[100:89], q_ld_h_araddr[11:0], cyc); end
            nchk = nchk + 1; if (h[101:101] !== q_ld_h_rready[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[101:101] %h ref %h cyc %0d", h[101:101], q_ld_h_rready[0:0], cyc); end
            nchk = nchk + 1; if (h[102:102] !== q_ld_h_dma_arready[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[102:102] %h ref %h cyc %0d", h[102:102], q_ld_h_dma_arready[0:0], cyc); end
            nchk = nchk + 1; if (h[103:103] !== q_ld_h_dma_rvalid[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[103:103] %h ref %h cyc %0d", h[103:103], q_ld_h_dma_rvalid[0:0], cyc); end
            nchk = nchk + 1; if (h[167:104] !== q_ld_h_dma_rdata[63:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[167:104] %h ref %h cyc %0d", h[167:104], q_ld_h_dma_rdata[63:0], cyc); end
            nchk = nchk + 1; if (h[169:168] !== q_ld_h_dma_rresp[1:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[169:168] %h ref %h cyc %0d", h[169:168], q_ld_h_dma_rresp[1:0], cyc); end
            nchk = nchk + 1; if (h[170:170] !== q_ld_h_dma_rlast[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[170:170] %h ref %h cyc %0d", h[170:170], q_ld_h_dma_rlast[0:0], cyc); end
            nchk = nchk + 1; if (h[171:171] !== q_ld_h_dma_awready[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[171:171] %h ref %h cyc %0d", h[171:171], q_ld_h_dma_awready[0:0], cyc); end
            nchk = nchk + 1; if (h[172:172] !== q_ld_h_dma_wready[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[172:172] %h ref %h cyc %0d", h[172:172], q_ld_h_dma_wready[0:0], cyc); end
            nchk = nchk + 1; if (h[173:173] !== q_ld_h_dma_bvalid[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[173:173] %h ref %h cyc %0d", h[173:173], q_ld_h_dma_bvalid[0:0], cyc); end
            nchk = nchk + 1; if (h[175:174] !== q_ld_h_dma_bresp[1:0]) begin err = err + 1; if (err < 10) $display("MISMATCH h[175:174] %h ref %h cyc %0d", h[175:174], q_ld_h_dma_bresp[1:0], cyc); end
            randomize_inputs;
        end
        $display("TB_hfd_loader checks=%0d mismatches=%0d", nchk, err);
        if (err != 0 || nchk == 0) $fatal(1, "FAIL");
        $finish;
    end
endmodule
