export DESIGN_NAME = ot_ha2_relay_tx_internal
export DESIGN_NICKNAME = ha2_relay_tx_internal
export PLATFORM = asap7
export VERILOG_FILES = /src/rtl/hbm_accel/ha2_ar/ot_ha2_parent_quiet_prims.sv /src/rtl/hbm_accel/ha2_ar/ot_ha2_hub_launch_single.sv /src/rtl/hbm_accel/ha2_ar/ot_ha2_truecredit_sender_capture.sv /src/physical/ha2_relay_tx_internal_20261007/wrapper.sv
export VERILOG_DEFINES = -DSYNTHESIS
export SYNTH_HDL_FRONTEND = slang
export SYNTH_HIERARCHICAL = 0
export ADDER_MAP_FILE =
export SDC_FILE = /src/physical/ha2_relay_tx_internal_20261007/internal.sdc
export DIE_AREA = 0 0 840.024 40.176
export CORE_AREA = 1.08 1.08 838.944 39.096
export PLACE_DENSITY = 0.55
export NUM_CORES = 8
export MIN_ROUTING_LAYER = M2
export MAX_ROUTING_LAYER = M9
export CORNER = WC
export CORNERS = WC BC
export WC_LIB_FILES = $(WC_NLDM_LIB_FILES)
export BC_LIB_FILES = $(BC_NLDM_LIB_FILES)
export HOLD_SLACK_MARGIN = 15
export SETUP_SLACK_MARGIN = 0
export TNS_END_PERCENT = 100
export REPORT_CLOCK_SKEW = 1
export PRE_IO_PLACEMENT_TCL = /src/physical/ha2_relay_tx_internal_20261007/pins.tcl
export POST_IO_PLACEMENT_TCL = /src/physical/ha2_relay_tx_internal_20261007/check_pins.tcl
export POST_PDN_TCL = /src/physical/ha2_relay_tx_internal_20261007/regions.tcl
