`timescale 1ns/1ps
module tb_qfd_sequencer_sys;
localparam W=16,G=6144,AW=24,NW=18,PAW=12,SW=64,LV=7,D=4;
reg clk=0; always #5 clk=~clk; reg rst_n=0;
reg d_start=0; reg [17:0] d_token=151000,d_pos=0; reg [1:0] d_gen=0;
wire d_done,d_drained,d_fault; wire [1:0] d_done_gen; wire [17:0] d_next_token;
wire [31:0] d_next_val,d_cycles; wire [3:0] d_fault_code;
wire [5:0] stage,st_layer,st_next_layer,st_crom;
wire h_start=dut.h_start; wire [17:0] tp_token=dut.tp_token,tp_pos=dut.tp_pos;
wire po_me_clk;
wire r_po_me_clk;
reg [1-1:0] kv_write_drained=0;
reg [1-1:0] kv_ok=0;
reg [1-1:0] me_mem_ok=0;
reg [512-1:0] vm_rq=0;
reg [1-1:0] c_ready=0;
reg [1-1:0] r_valid=0;
reg [512-1:0] r_data=0;
reg [1-1:0] r_last=0;
reg [2-1:0] r_rank=0;
reg [1-1:0] r_err=0;
reg [1-1:0] pw_v=0;
reg [10-1:0] pw_addr=0;
reg [64-1:0] pw_data=0;
reg [1-1:0] dw_v=0;
reg [3-1:0] dw_addr=0;
reg [64-1:0] dw_data=0;
reg [1-1:0] pi_me_ready=0;
reg [1-1:0] pi_me_idle=0;
reg [1-1:0] pi_me_wrom_re=0;
reg [AW-1:0] pi_me_wrom_addr=0;
reg [NW-1:0] pi_me_am_idx=0;
reg [32-1:0] pi_me_am_val=0;
reg [1-1:0] pi_me_am_any=0;
reg [16-1:0] pi_me_progress=0;
reg [1-1:0] pi_me_fault=0;
reg [1-1:0] pi_su_rt_active=0;
reg [8-1:0] pi_su_rt_inflight=0;
reg [1-1:0] pi_su_ready=0;
reg [1-1:0] pi_su_idle=0;
reg [1-1:0] pi_su_wrom_re=0;
reg [AW-1:0] pi_su_wrom_addr=0;
reg [SW-1:0] pi_su_kv_we=0;
reg [16-1:0] pi_su_progress=0;
reg [16-1:0] pi_su_progress_rows=0;
reg [1-1:0] pi_su_fault=0;
wire [1-1:0] s_done;
wire [1-1:0] r_s_done;
wire [NW-1:0] seq_ntok;
wire [NW-1:0] r_seq_ntok;
wire [32-1:0] seq_nval;
wire [32-1:0] r_seq_nval;
wire [1-1:0] s_fault;
wire [1-1:0] r_s_fault;
wire [1-1:0] core_fault;
wire [1-1:0] r_core_fault;
wire [1-1:0] coll_busy;
wire [1-1:0] r_coll_busy;
wire [1-1:0] kv_write_flush;
wire [1-1:0] r_kv_write_flush;
wire [1-1:0] kvd_v;
wire [1-1:0] r_kvd_v;
wire [AW-1:0] kvd_wbase;
wire [AW-1:0] r_kvd_wbase;
wire [AW-1:0] kvd_ts;
wire [AW-1:0] r_kvd_ts;
wire [AW-1:0] kvd_ks;
wire [AW-1:0] r_kvd_ks;
wire [AW-1:0] kvd_js;
wire [AW-1:0] r_kvd_js;
wire [AW-1:0] kvd_wcs;
wire [AW-1:0] r_kvd_wcs;
wire [4-1:0] kvd_split;
wire [4-1:0] r_kvd_split;
wire [3-1:0] kvd_jsh;
wire [3-1:0] r_kvd_jsh;
wire [NW-1:0] kvd_tiles;
wire [NW-1:0] r_kvd_tiles;
wire [NW-1:0] kvd_k;
wire [NW-1:0] r_kvd_k;
wire [NW-1:0] kvd_nout;
wire [NW-1:0] r_kvd_nout;
wire [1-1:0] kvd_kindk;
wire [1-1:0] r_kvd_kindk;
wire [NW-1:0] kvd_pos;
wire [NW-1:0] r_kvd_pos;
wire [1-1:0] me_clk_en;
wire [1-1:0] r_me_clk_en;
wire [1-1:0] vm_re;
wire [1-1:0] r_vm_re;
wire [8-1:0] vm_raddr;
wire [8-1:0] r_vm_raddr;
wire [1-1:0] vm_we;
wire [1-1:0] r_vm_we;
wire [8-1:0] vm_waddr;
wire [8-1:0] r_vm_waddr;
wire [512-1:0] vm_wdata;
wire [512-1:0] r_vm_wdata;
wire [1-1:0] c_valid;
wire [1-1:0] r_c_valid;
wire [512-1:0] c_data;
wire [512-1:0] r_c_data;
wire [1-1:0] c_last;
wire [1-1:0] r_c_last;
wire [1-1:0] c_mode;
wire [1-1:0] r_c_mode;
wire [32-1:0] c_tag;
wire [32-1:0] r_c_tag;
wire [1-1:0] rom_fault;
wire [1-1:0] r_rom_fault;
wire [1-1:0] su_asrc;
wire [1-1:0] r_su_asrc;
wire [NW-1:0] su_tok;
wire [NW-1:0] r_su_tok;
wire [1-1:0] po_me_go;
wire [1-1:0] r_po_me_go;
wire [NW-1:0] po_me_i_nout;
wire [NW-1:0] r_po_me_i_nout;
wire [NW-1:0] po_me_i_tiles;
wire [NW-1:0] r_po_me_i_tiles;
wire [NW-1:0] po_me_i_k;
wire [NW-1:0] r_po_me_i_k;
wire [1-1:0] po_me_i_wsrc;
wire [1-1:0] r_po_me_i_wsrc;
wire [AW-1:0] po_me_i_wbase;
wire [AW-1:0] r_po_me_i_wbase;
wire [AW-1:0] po_me_i_ts;
wire [AW-1:0] r_po_me_i_ts;
wire [AW-1:0] po_me_i_ks;
wire [AW-1:0] r_po_me_i_ks;
wire [AW-1:0] po_me_i_js;
wire [AW-1:0] r_po_me_i_js;
wire [AW-1:0] po_me_i_xbase;
wire [AW-1:0] r_po_me_i_xbase;
wire [AW-1:0] po_me_i_xks;
wire [AW-1:0] r_po_me_i_xks;
wire [AW-1:0] po_me_i_xjs;
wire [AW-1:0] r_po_me_i_xjs;
wire [AW-1:0] po_me_i_xcs;
wire [AW-1:0] r_po_me_i_xcs;
wire [3-1:0] po_me_i_jsh;
wire [3-1:0] r_po_me_i_jsh;
wire [4-1:0] po_me_i_split;
wire [4-1:0] r_po_me_i_split;
wire [AW-1:0] po_me_i_wcs;
wire [AW-1:0] r_po_me_i_wcs;
wire [1-1:0] po_me_i_round;
wire [1-1:0] r_po_me_i_round;
wire [AW-1:0] po_me_i_obase;
wire [AW-1:0] r_po_me_i_obase;
wire [AW-1:0] po_me_i_ots;
wire [AW-1:0] r_po_me_i_ots;
wire [AW-1:0] po_me_i_ojs;
wire [AW-1:0] r_po_me_i_ojs;
wire [1-1:0] po_me_i_mmode;
wire [1-1:0] r_po_me_i_mmode;
wire [1-1:0] po_me_i_oen;
wire [1-1:0] r_po_me_i_oen;
wire [1-1:0] po_me_i_amax;
wire [1-1:0] r_po_me_i_amax;
wire [1-1:0] po_me_i_rmax;
wire [1-1:0] r_po_me_i_rmax;
wire [AW-1:0] po_me_i_mbase;
wire [AW-1:0] r_po_me_i_mbase;
wire [1-1:0] po_su_go;
wire [1-1:0] r_po_su_go;
wire [NW-1:0] po_su_i_nout;
wire [NW-1:0] r_po_su_i_nout;
wire [NW-1:0] po_su_i_nin;
wire [NW-1:0] r_po_su_i_nin;
wire [1-1:0] po_su_i_asrc;
wire [1-1:0] r_po_su_i_asrc;
wire [AW-1:0] po_su_i_abase;
wire [AW-1:0] r_po_su_i_abase;
wire [AW-1:0] po_su_i_aso;
wire [AW-1:0] r_po_su_i_aso;
wire [AW-1:0] po_su_i_asi;
wire [AW-1:0] r_po_su_i_asi;
wire [1-1:0] po_su_i_bsrc;
wire [1-1:0] r_po_su_i_bsrc;
wire [AW-1:0] po_su_i_bbase;
wire [AW-1:0] r_po_su_i_bbase;
wire [AW-1:0] po_su_i_bso;
wire [AW-1:0] r_po_su_i_bso;
wire [AW-1:0] po_su_i_bsi;
wire [AW-1:0] r_po_su_i_bsi;
wire [1-1:0] po_su_i_csrc;
wire [1-1:0] r_po_su_i_csrc;
wire [AW-1:0] po_su_i_cbase;
wire [AW-1:0] r_po_su_i_cbase;
wire [AW-1:0] po_su_i_cso;
wire [AW-1:0] r_po_su_i_cso;
wire [AW-1:0] po_su_i_csi;
wire [AW-1:0] r_po_su_i_csi;
wire [2-1:0] po_su_i_ma;
wire [2-1:0] r_po_su_i_ma;
wire [2-1:0] po_su_i_mb;
wire [2-1:0] r_po_su_i_mb;
wire [3-1:0] po_su_i_ad;
wire [3-1:0] r_po_su_i_ad;
wire [3-1:0] po_su_i_sfu;
wire [3-1:0] r_po_su_i_sfu;
wire [1-1:0] po_su_i_mc;
wire [1-1:0] r_po_su_i_mc;
wire [1-1:0] po_su_i_md;
wire [1-1:0] r_po_su_i_md;
wire [2-1:0] po_su_i_dst;
wire [2-1:0] r_po_su_i_dst;
wire [AW-1:0] po_su_i_dbase;
wire [AW-1:0] r_po_su_i_dbase;
wire [AW-1:0] po_su_i_dso;
wire [AW-1:0] r_po_su_i_dso;
wire [AW-1:0] po_su_i_dsi;
wire [AW-1:0] r_po_su_i_dsi;
wire [2-1:0] po_su_i_red;
wire [2-1:0] r_po_su_i_red;
wire [1-1:0] po_su_i_redsq;
wire [1-1:0] r_po_su_i_redsq;
wire [AW-1:0] po_su_i_rbase;
wire [AW-1:0] r_po_su_i_rbase;
wire [AW-1:0] po_su_i_rso;
wire [AW-1:0] r_po_su_i_rso;
wire [32-1:0] po_su_i_imm1;
wire [32-1:0] r_po_su_i_imm1;
wire [32-1:0] po_su_i_imm2;
wire [32-1:0] r_po_su_i_imm2;
ot_qfd_sp_constants_sequencer_sys #(.SYS_ENABLE(1),.SYS_BASE_MUT(`SYS_MUT),.WDOG(200000)) dut (.clk(clk),.rst_n(rst_n),.d_start(d_start),.d_token(d_token),.d_pos(d_pos),.d_gen(d_gen),.po_me_clk(po_me_clk),.kv_write_drained(kv_write_drained),.kv_ok(kv_ok),.me_mem_ok(me_mem_ok),.vm_rq(vm_rq),.c_ready(c_ready),.r_valid(r_valid),.r_data(r_data),.r_last(r_last),.r_rank(r_rank),.r_err(r_err),.pi_me_ready(pi_me_ready),.pi_me_idle(pi_me_idle),.pi_me_wrom_re(pi_me_wrom_re),.pi_me_wrom_addr(pi_me_wrom_addr),.pi_me_am_idx(pi_me_am_idx),.pi_me_am_val(pi_me_am_val),.pi_me_am_any(pi_me_am_any),.pi_me_progress(pi_me_progress),.pi_me_fault(pi_me_fault),.pi_su_rt_active(pi_su_rt_active),.pi_su_rt_inflight(pi_su_rt_inflight),.pi_su_ready(pi_su_ready),.pi_su_idle(pi_su_idle),.pi_su_wrom_re(pi_su_wrom_re),.pi_su_wrom_addr(pi_su_wrom_addr),.pi_su_kv_we(pi_su_kv_we),.pi_su_progress(pi_su_progress),.pi_su_progress_rows(pi_su_progress_rows),.pi_su_fault(pi_su_fault),.s_done(s_done),.seq_ntok(seq_ntok),.seq_nval(seq_nval),.s_fault(s_fault),.core_fault(core_fault),.coll_busy(coll_busy),.kv_write_flush(kv_write_flush),.kvd_v(kvd_v),.kvd_wbase(kvd_wbase),.kvd_ts(kvd_ts),.kvd_ks(kvd_ks),.kvd_js(kvd_js),.kvd_wcs(kvd_wcs),.kvd_split(kvd_split),.kvd_jsh(kvd_jsh),.kvd_tiles(kvd_tiles),.kvd_k(kvd_k),.kvd_nout(kvd_nout),.kvd_kindk(kvd_kindk),.kvd_pos(kvd_pos),.me_clk_en(me_clk_en),.vm_re(vm_re),.vm_raddr(vm_raddr),.vm_we(vm_we),.vm_waddr(vm_waddr),.vm_wdata(vm_wdata),.c_valid(c_valid),.c_data(c_data),.c_last(c_last),.c_mode(c_mode),.c_tag(c_tag),.rom_fault(rom_fault),.su_asrc(su_asrc),.su_tok(su_tok),.po_me_go(po_me_go),.po_me_i_nout(po_me_i_nout),.po_me_i_tiles(po_me_i_tiles),.po_me_i_k(po_me_i_k),.po_me_i_wsrc(po_me_i_wsrc),.po_me_i_wbase(po_me_i_wbase),.po_me_i_ts(po_me_i_ts),.po_me_i_ks(po_me_i_ks),.po_me_i_js(po_me_i_js),.po_me_i_xbase(po_me_i_xbase),.po_me_i_xks(po_me_i_xks),.po_me_i_xjs(po_me_i_xjs),.po_me_i_xcs(po_me_i_xcs),.po_me_i_jsh(po_me_i_jsh),.po_me_i_split(po_me_i_split),.po_me_i_wcs(po_me_i_wcs),.po_me_i_round(po_me_i_round),.po_me_i_obase(po_me_i_obase),.po_me_i_ots(po_me_i_ots),.po_me_i_ojs(po_me_i_ojs),.po_me_i_mmode(po_me_i_mmode),.po_me_i_oen(po_me_i_oen),.po_me_i_amax(po_me_i_amax),.po_me_i_rmax(po_me_i_rmax),.po_me_i_mbase(po_me_i_mbase),.po_su_go(po_su_go),.po_su_i_nout(po_su_i_nout),.po_su_i_nin(po_su_i_nin),.po_su_i_asrc(po_su_i_asrc),.po_su_i_abase(po_su_i_abase),.po_su_i_aso(po_su_i_aso),.po_su_i_asi(po_su_i_asi),.po_su_i_bsrc(po_su_i_bsrc),.po_su_i_bbase(po_su_i_bbase),.po_su_i_bso(po_su_i_bso),.po_su_i_bsi(po_su_i_bsi),.po_su_i_csrc(po_su_i_csrc),.po_su_i_cbase(po_su_i_cbase),.po_su_i_cso(po_su_i_cso),.po_su_i_csi(po_su_i_csi),.po_su_i_ma(po_su_i_ma),.po_su_i_mb(po_su_i_mb),.po_su_i_ad(po_su_i_ad),.po_su_i_sfu(po_su_i_sfu),.po_su_i_mc(po_su_i_mc),.po_su_i_md(po_su_i_md),.po_su_i_dst(po_su_i_dst),.po_su_i_dbase(po_su_i_dbase),.po_su_i_dso(po_su_i_dso),.po_su_i_dsi(po_su_i_dsi),.po_su_i_red(po_su_i_red),.po_su_i_redsq(po_su_i_redsq),.po_su_i_rbase(po_su_i_rbase),.po_su_i_rso(po_su_i_rso),.po_su_i_imm1(po_su_i_imm1),.po_su_i_imm2(po_su_i_imm2),.d_done(d_done),.d_drained(d_drained),.d_fault(d_fault),.d_done_gen(d_done_gen),.d_next_token(d_next_token),.d_next_val(d_next_val),.d_cycles(d_cycles),.d_fault_code(d_fault_code),.stage(stage),.st_layer(st_layer),.st_next_layer(st_next_layer),.st_crom(st_crom));
ot_qfd_sp_constants_sequencer #(.FQ_HEAD(1),.MSTN(1)) reference_master (.clk(clk),.rst_n(rst_n),.po_me_clk(r_po_me_clk),.h_start(h_start),.tp_token(tp_token),.tp_pos(tp_pos),.kv_write_drained(kv_write_drained),.kv_ok(kv_ok),.me_mem_ok(me_mem_ok),.vm_rq(vm_rq),.c_ready(c_ready),.r_valid(r_valid),.r_data(r_data),.r_last(r_last),.r_rank(r_rank),.r_err(r_err),.pw_v(pw_v),.pw_addr(pw_addr),.pw_data(pw_data),.dw_v(dw_v),.dw_addr(dw_addr),.dw_data(dw_data),.pi_me_ready(pi_me_ready),.pi_me_idle(pi_me_idle),.pi_me_wrom_re(pi_me_wrom_re),.pi_me_wrom_addr(pi_me_wrom_addr),.pi_me_am_idx(pi_me_am_idx),.pi_me_am_val(pi_me_am_val),.pi_me_am_any(pi_me_am_any),.pi_me_progress(pi_me_progress),.pi_me_fault(pi_me_fault),.pi_su_rt_active(pi_su_rt_active),.pi_su_rt_inflight(pi_su_rt_inflight),.pi_su_ready(pi_su_ready),.pi_su_idle(pi_su_idle),.pi_su_wrom_re(pi_su_wrom_re),.pi_su_wrom_addr(pi_su_wrom_addr),.pi_su_kv_we(pi_su_kv_we),.pi_su_progress(pi_su_progress),.pi_su_progress_rows(pi_su_progress_rows),.pi_su_fault(pi_su_fault),.s_done(r_s_done),.seq_ntok(r_seq_ntok),.seq_nval(r_seq_nval),.s_fault(r_s_fault),.core_fault(r_core_fault),.coll_busy(r_coll_busy),.kv_write_flush(r_kv_write_flush),.kvd_v(r_kvd_v),.kvd_wbase(r_kvd_wbase),.kvd_ts(r_kvd_ts),.kvd_ks(r_kvd_ks),.kvd_js(r_kvd_js),.kvd_wcs(r_kvd_wcs),.kvd_split(r_kvd_split),.kvd_jsh(r_kvd_jsh),.kvd_tiles(r_kvd_tiles),.kvd_k(r_kvd_k),.kvd_nout(r_kvd_nout),.kvd_kindk(r_kvd_kindk),.kvd_pos(r_kvd_pos),.me_clk_en(r_me_clk_en),.vm_re(r_vm_re),.vm_raddr(r_vm_raddr),.vm_we(r_vm_we),.vm_waddr(r_vm_waddr),.vm_wdata(r_vm_wdata),.c_valid(r_c_valid),.c_data(r_c_data),.c_last(r_c_last),.c_mode(r_c_mode),.c_tag(r_c_tag),.rom_fault(r_rom_fault),.su_asrc(r_su_asrc),.su_tok(r_su_tok),.po_me_go(r_po_me_go),.po_me_i_nout(r_po_me_i_nout),.po_me_i_tiles(r_po_me_i_tiles),.po_me_i_k(r_po_me_i_k),.po_me_i_wsrc(r_po_me_i_wsrc),.po_me_i_wbase(r_po_me_i_wbase),.po_me_i_ts(r_po_me_i_ts),.po_me_i_ks(r_po_me_i_ks),.po_me_i_js(r_po_me_i_js),.po_me_i_xbase(r_po_me_i_xbase),.po_me_i_xks(r_po_me_i_xks),.po_me_i_xjs(r_po_me_i_xjs),.po_me_i_xcs(r_po_me_i_xcs),.po_me_i_jsh(r_po_me_i_jsh),.po_me_i_split(r_po_me_i_split),.po_me_i_wcs(r_po_me_i_wcs),.po_me_i_round(r_po_me_i_round),.po_me_i_obase(r_po_me_i_obase),.po_me_i_ots(r_po_me_i_ots),.po_me_i_ojs(r_po_me_i_ojs),.po_me_i_mmode(r_po_me_i_mmode),.po_me_i_oen(r_po_me_i_oen),.po_me_i_amax(r_po_me_i_amax),.po_me_i_rmax(r_po_me_i_rmax),.po_me_i_mbase(r_po_me_i_mbase),.po_su_go(r_po_su_go),.po_su_i_nout(r_po_su_i_nout),.po_su_i_nin(r_po_su_i_nin),.po_su_i_asrc(r_po_su_i_asrc),.po_su_i_abase(r_po_su_i_abase),.po_su_i_aso(r_po_su_i_aso),.po_su_i_asi(r_po_su_i_asi),.po_su_i_bsrc(r_po_su_i_bsrc),.po_su_i_bbase(r_po_su_i_bbase),.po_su_i_bso(r_po_su_i_bso),.po_su_i_bsi(r_po_su_i_bsi),.po_su_i_csrc(r_po_su_i_csrc),.po_su_i_cbase(r_po_su_i_cbase),.po_su_i_cso(r_po_su_i_cso),.po_su_i_csi(r_po_su_i_csi),.po_su_i_ma(r_po_su_i_ma),.po_su_i_mb(r_po_su_i_mb),.po_su_i_ad(r_po_su_i_ad),.po_su_i_sfu(r_po_su_i_sfu),.po_su_i_mc(r_po_su_i_mc),.po_su_i_md(r_po_su_i_md),.po_su_i_dst(r_po_su_i_dst),.po_su_i_dbase(r_po_su_i_dbase),.po_su_i_dso(r_po_su_i_dso),.po_su_i_dsi(r_po_su_i_dsi),.po_su_i_red(r_po_su_i_red),.po_su_i_redsq(r_po_su_i_redsq),.po_su_i_rbase(r_po_su_i_rbase),.po_su_i_rso(r_po_su_i_rso),.po_su_i_imm1(r_po_su_i_imm1),.po_su_i_imm2(r_po_su_i_imm2));
integer errors=0, cycles=0, starts=0, me_ops=0,su_ops=0,coll_ops=0,i,bank,j,rx_left=0,rx_rank=0,case_no=0;
reg check_commands=1,previous_done=0; reg [23:0] expected_code,expected_scale; reg [1:0] expected_prog;
always @(posedge clk) begin expected_code<=(stage==0?0:stage==37?36:stage-1)*512; expected_scale<=(stage==0?0:stage==37?36:stage-1)*1056; end
task bad(input [255:0] what); begin errors=errors+1; if(errors<20)$display("SYS_BAD cycle=%0d stage=%0d what=%0s",cycles,stage,what); end endtask
always @(negedge clk) if(rst_n && check_commands) begin
 cycles=cycles+1;
 if(h_start)begin
  $display("SYS_START stage=%0d cycle=%0d",stage,cycles);
  if(stage!==starts || st_layer!==(starts==0 || starts==37 ? 63 : starts-1)) bad("stage traversal");
  if(st_crom!==(starts==0 ? 63 : starts==37 ? 36 : starts-1))bad("constant stage");
  if(st_next_layer!==(starts<36 ? starts : 63))bad("next layer");
  expected_prog=starts==0?0:starts==37?2:1;
  for(i=0;i<64;i=i+1)reference_master.prog_mem[i]=dut.sys_program(expected_prog,i);
  for(i=0;i<8;i=i+1)reference_master.desc_mem[i]=dut.sys_descriptor(expected_prog,i);
  starts=starts+1;
 end
 if(po_me_go)begin me_ops=me_ops+1;
 if(po_me_go !== (r_po_me_go))bad("po_me_go");
 if(po_me_i_nout !== (r_po_me_i_nout))bad("po_me_i_nout");
 if(po_me_i_tiles !== (r_po_me_i_tiles))bad("po_me_i_tiles");
 if(po_me_i_k !== (r_po_me_i_k))bad("po_me_i_k");
 if(po_me_i_wsrc !== (r_po_me_i_wsrc))bad("po_me_i_wsrc");
 if(po_me_i_wbase !== (r_po_me_i_wbase+(po_me_i_wsrc?0:expected_code)))bad("po_me_i_wbase");
 if(po_me_i_ts !== (r_po_me_i_ts))bad("po_me_i_ts");
 if(po_me_i_ks !== (r_po_me_i_ks))bad("po_me_i_ks");
 if(po_me_i_js !== (r_po_me_i_js))bad("po_me_i_js");
 if(po_me_i_xbase !== (r_po_me_i_xbase))bad("po_me_i_xbase");
 if(po_me_i_xks !== (r_po_me_i_xks))bad("po_me_i_xks");
 if(po_me_i_xjs !== (r_po_me_i_xjs))bad("po_me_i_xjs");
 if(po_me_i_xcs !== (r_po_me_i_xcs))bad("po_me_i_xcs");
 if(po_me_i_jsh !== (r_po_me_i_jsh))bad("po_me_i_jsh");
 if(po_me_i_split !== (r_po_me_i_split))bad("po_me_i_split");
 if(po_me_i_wcs !== (r_po_me_i_wcs+(po_me_i_wsrc?0:expected_scale)))bad("po_me_i_wcs");
 if(po_me_i_round !== (r_po_me_i_round))bad("po_me_i_round");
 if(po_me_i_obase !== (r_po_me_i_obase))bad("po_me_i_obase");
 if(po_me_i_ots !== (r_po_me_i_ots))bad("po_me_i_ots");
 if(po_me_i_ojs !== (r_po_me_i_ojs))bad("po_me_i_ojs");
 if(po_me_i_mmode !== (r_po_me_i_mmode))bad("po_me_i_mmode");
 if(po_me_i_oen !== (r_po_me_i_oen))bad("po_me_i_oen");
 if(po_me_i_amax !== (r_po_me_i_amax))bad("po_me_i_amax");
 if(po_me_i_rmax !== (r_po_me_i_rmax))bad("po_me_i_rmax");
 if(po_me_i_mbase !== (r_po_me_i_mbase))bad("po_me_i_mbase");
 end
 if(po_su_go)begin su_ops=su_ops+1;
 if(po_su_go !== r_po_su_go)bad("po_su_go");
 if(po_su_i_nout !== r_po_su_i_nout)bad("po_su_i_nout");
 if(po_su_i_nin !== r_po_su_i_nin)bad("po_su_i_nin");
 if(po_su_i_asrc !== r_po_su_i_asrc)bad("po_su_i_asrc");
 if(po_su_i_abase !== r_po_su_i_abase)bad("po_su_i_abase");
 if(po_su_i_aso !== r_po_su_i_aso)bad("po_su_i_aso");
 if(po_su_i_asi !== r_po_su_i_asi)bad("po_su_i_asi");
 if(po_su_i_bsrc !== r_po_su_i_bsrc)bad("po_su_i_bsrc");
 if(po_su_i_bbase !== r_po_su_i_bbase)bad("po_su_i_bbase");
 if(po_su_i_bso !== r_po_su_i_bso)bad("po_su_i_bso");
 if(po_su_i_bsi !== r_po_su_i_bsi)bad("po_su_i_bsi");
 if(po_su_i_csrc !== r_po_su_i_csrc)bad("po_su_i_csrc");
 if(po_su_i_cbase !== r_po_su_i_cbase)bad("po_su_i_cbase");
 if(po_su_i_cso !== r_po_su_i_cso)bad("po_su_i_cso");
 if(po_su_i_csi !== r_po_su_i_csi)bad("po_su_i_csi");
 if(po_su_i_ma !== r_po_su_i_ma)bad("po_su_i_ma");
 if(po_su_i_mb !== r_po_su_i_mb)bad("po_su_i_mb");
 if(po_su_i_ad !== r_po_su_i_ad)bad("po_su_i_ad");
 if(po_su_i_sfu !== r_po_su_i_sfu)bad("po_su_i_sfu");
 if(po_su_i_mc !== r_po_su_i_mc)bad("po_su_i_mc");
 if(po_su_i_md !== r_po_su_i_md)bad("po_su_i_md");
 if(po_su_i_dst !== r_po_su_i_dst)bad("po_su_i_dst");
 if(po_su_i_dbase !== r_po_su_i_dbase)bad("po_su_i_dbase");
 if(po_su_i_dso !== r_po_su_i_dso)bad("po_su_i_dso");
 if(po_su_i_dsi !== r_po_su_i_dsi)bad("po_su_i_dsi");
 if(po_su_i_red !== r_po_su_i_red)bad("po_su_i_red");
 if(po_su_i_redsq !== r_po_su_i_redsq)bad("po_su_i_redsq");
 if(po_su_i_rbase !== r_po_su_i_rbase)bad("po_su_i_rbase");
 if(po_su_i_rso !== r_po_su_i_rso)bad("po_su_i_rso");
 if(po_su_i_imm1 !== r_po_su_i_imm1)bad("po_su_i_imm1");
 if(po_su_i_imm2 !== r_po_su_i_imm2)bad("po_su_i_imm2");
 end
 if(s_done!==r_s_done || s_fault!==r_s_fault || core_fault!==r_core_fault)bad("sequencer status");
 if(s_done && !previous_done)$display("SYS_STAGE_DONE stage=%0d cycle=%0d",stage,cycles); previous_done=s_done;
 if(c_valid)begin
  if(c_tag!=={d_gen,stage,d_pos[12:0],d_token[7:0],reference_master.b_c_tag[2:0]})bad("fullshape tag");
  if(c_data!==r_c_data || c_last!==r_c_last || c_mode!==r_c_mode)bad("collective packet");
 end
 r_valid=0;r_last=0;
 if(rx_left>0)begin
  r_valid=1;r_last=(rx_left==1);r_rank=rx_rank;r_data=0;
  if(c_mode)r_data={462'd0,18'd17+rx_rank*18'd37984,32'h3f800000};
  rx_left=rx_left-1;rx_rank=rx_rank+1;
 end else if(c_valid && c_ready && c_last)begin rx_left=c_mode?4:256;rx_rank=0;coll_ops=coll_ops+1;end
 if(cycles>200000)begin $display("SYS_TIMEOUT stage=%0d seq=%0d core=%0d",stage,dut.u_seq.u_base.st,dut.u_ctrl.st);$fatal;end
end
initial begin
 kv_write_drained=1;kv_ok=1;me_mem_ok=1;c_ready=1;pi_me_ready=1;pi_me_idle=1;pi_me_am_idx=17;pi_me_am_val=32'h3f800000;pi_me_am_any=1;pi_me_progress=16'hffff;
 pi_su_ready=1;pi_su_idle=1;pi_su_progress=16'hffff;pi_su_progress_rows=16'hffff;
 repeat(5)@(negedge clk);rst_n=1;repeat(5)@(negedge clk);
 for(case_no=0;case_no<2;case_no=case_no+1)begin
  d_pos=case_no==0?0:8191;d_gen=case_no;starts=0;
  @(negedge clk);d_start=1;@(negedge clk);d_start=0;
  wait(!d_done);wait(d_done);@(negedge clk);
  if(starts!=38 || !d_drained || d_fault || d_done_gen!=d_gen || d_next_token!=17 || d_next_val!=32'h3f800000)bad("final report");
  $display("SYS_CASE pos=%0d starts=%0d me=%0d su=%0d coll=%0d cycles=%0d bad=%0d",d_pos,starts,me_ops,su_ops,coll_ops,d_cycles,errors);
  repeat(5)@(negedge clk);
 end
 check_commands=0;rst_n=0;repeat(5)@(negedge clk);rst_n=1;repeat(5)@(negedge clk);
 d_start=1;@(negedge clk);d_start=0;
 wait(dut.prog_re);force dut.prog_addr=12'd64;repeat(2)@(negedge clk);release dut.prog_addr;
 wait(d_done);@(negedge clk);if(!d_fault || d_fault_code!=2 || d_drained)bad("program bounds fault");
 $display("SYS_BOUNDS_FAULT pass=%0d code=%0d",d_fault && d_fault_code==2 && !d_drained,d_fault_code);
 $display("SEQUENCER_SYS_RESULT pass=%0d cases=2 stages=76 me=%0d su=%0d coll=%0d bad=%0d",errors==0,me_ops,su_ops,coll_ops,errors);
 if(errors)$fatal(1,"control/command mismatch");$finish;
end endmodule
