// Generated by tools/hbm_sm_program_provider_build.py.
// Existing service source SHA256: 580a0490e2fde6ea8923174d441da927d5f5b465f4bd4c7c18a57344fd0e1f7d
// Explicit real issuer identity; issuer sees the actual sector/tag request.
// This is a shared-service client binding, not a new memory controller.
// Installation/identity inputs must originate in protected source-owned providers.
module ot_hbm_sm_program_service_join #(parameter integer ENABLE=0,LOCAL_DIE=0,RANK_LIMIT=96)(
 input wire clk,rst_n,
 input wire region_valid,input wire[31:0] virtual_base,input wire[32:0] virtual_limit,
 input wire[36:0] physical_base,input wire[15:0] request_tag,
 input wire mem_req_valid,output wire mem_req_ready,input wire[31:0] mem_req_addr,
 output wire mem_rsp_valid,input wire mem_rsp_ready,output wire[31:0] mem_rsp_addr,mem_rsp_data,
 output wire mem_rsp_error,
 output wire issuer_req_valid,output wire[36:0] issuer_req_addr,output wire[15:0] issuer_req_tag,
 input wire hardware_owner_valid,input ot_hbm_r14_pkg::identity_t owner_identity,
 input wire[5:0] loader_client,input wire[6:0] global_rank,
 output wire[3:0] stack_req_v,input wire[3:0] stack_req_r,output wire[1819:0] stack_req,
 input wire[3:0] owned_v,output wire[3:0] owned_r,input wire[1859:0] owned,
 input wire[3:0] owned_we,owned_credit,service_fault,
 output wire[3:0] other_owned_v,input wire[3:0] other_owned_r,
 output wire[1859:0] other_owned,output wire[3:0] other_owned_we,other_owned_credit,
 output wire[3:0] credit_v,input wire[3:0] credit_r,output wire[3:0] credit_we,
 output wire[767:0] credit_id,output wire[47:0] credit_tag,output wire[19:0] credit_beat,
 input wire[3:0] other_credit_v,other_credit_we,output wire[3:0] other_credit_r,
 input wire[767:0] other_credit_id,input wire[47:0] other_credit_tag,input wire[19:0] other_credit_beat,
 output wire busy,output wire[6:0] held_global_rank,output wire fault
);
 wire req_v,req_r,rsp_v,rsp_r,rsp_we;
 wire[36:0] req_addr;wire[15:0] req_tag,rsp_tag;wire[255:0] rsp_data;
 wire req_we=1'b0;wire[255:0] req_data=256'b0;wire[31:0] req_strb=32'b0;
 wire adapter_fault,join_fault;
 assign issuer_req_valid=req_v;assign issuer_req_addr=req_addr;assign issuer_req_tag=req_tag;
 assign fault=adapter_fault||join_fault;
 ot_hbm_sm_program_word #(.ENABLE(ENABLE)) words(
 .clk(clk),.rst_n(rst_n),.region_valid(region_valid),.virtual_base(virtual_base),.virtual_limit(virtual_limit),
 .physical_base(physical_base),.request_tag(request_tag),
 .mem_req_valid(mem_req_valid),.mem_req_ready(mem_req_ready),.mem_req_addr(mem_req_addr),
 .mem_rsp_valid(mem_rsp_valid),.mem_rsp_ready(mem_rsp_ready),.mem_rsp_addr(mem_rsp_addr),.mem_rsp_data(mem_rsp_data),.mem_rsp_error(mem_rsp_error),
 .service_req_valid(req_v),.service_req_ready(req_r),.service_req_addr(req_addr),.service_req_tag(req_tag),
 .service_rsp_valid(rsp_v),.service_rsp_ready(rsp_r),.service_rsp_we(rsp_we),.service_rsp_tag(rsp_tag),.service_rsp_data(rsp_data),.service_fault(join_fault),.fault(adapter_fault));
 ot_hbm_loader_service_join #(.ENABLE(ENABLE),.LOCAL_DIE(LOCAL_DIE),.RANK_LIMIT(RANK_LIMIT)) service(.fault(join_fault),.*);
endmodule
