# generated by make_vm_tiles.py: die port -> face chain depth
set fc_ps(f_n_ctl) 1
set fc_ps(f_n_row) 1
set fc_ps(f_n_wr) 1
set fc_ps(f_su_SE) 3
set fc_ps(f_w_ctl) 1
set fc_ps(f_w_row) 1
set fc_ps(f_w_wr) 1
set fc_ps(iSE) 3
set fc_ps(qSE) 3
set fc_ps(t_n_ctl) 1
set fc_ps(t_n_row) 1
set fc_ps(t_n_wr) 1
set fc_ps(t_su_SE) 3
set fc_ps(t_w_ctl) 1
set fc_ps(t_w_row) 1
set fc_ps(t_w_wr) 1
set fc_ps(xSE) 3
