# generated by make_vm_tiles.py: die port -> face chain depth
set fc_ps(f_s_ctl) 1
set fc_ps(f_s_row) 1
set fc_ps(f_s_wr) 1
set fc_ps(f_su_NE) 3
set fc_ps(f_w_ctl) 1
set fc_ps(f_w_row) 1
set fc_ps(f_w_wr) 1
set fc_ps(iNE) 3
set fc_ps(qNE) 3
set fc_ps(t_s_ctl) 1
set fc_ps(t_s_row) 1
set fc_ps(t_s_wr) 1
set fc_ps(t_su_NE) 3
set fc_ps(t_w_ctl) 1
set fc_ps(t_w_row) 1
set fc_ps(t_w_wr) 1
set fc_ps(xNE) 3
