// Select the actual W6 hardware in the caller SM context. Baseline by default.
// LIVE_STATE is unqualified; neither branch claims the 429MHz defect repaired.
module ot_hbm_w6_source_select #(
  parameter bit ENABLE=1'b0,parameter bit LIVE_STATE=1'b0
)(
  input wire clk, por_n, rst_n,
  input wire req_valid, input wire [54:0] req_identity,
  input wire req_internal_SIMD, output wire req_ready,
  input wire host_ack_valid, input wire [54:0] host_ack_identity,
  output wire host_ack_ready,
  input wire simd_ack_retire_valid, input wire [54:0] simd_ack_retire_identity,
  output wire simd_ack_retire_ready,
  output wire visible_valid, output wire [54:0] visible_identity,
  input wire visible_ready,
  input wire consumer_valid, input wire [54:0] consumer_identity,
  output wire consumer_ready,
  input wire child_reverse_valid, input wire [54:0] child_reverse_identity,
  output wire child_reverse_ready,
  input wire parent_reverse_valid, input wire [54:0] parent_reverse_identity,
  output wire parent_reverse_ready,
  input wire reverse_CDC_valid, input wire [54:0] reverse_CDC_identity,
  output wire reverse_CDC_ready,
  output wire drain_req_valid, output wire [54:0] drain_req_identity,
  output wire drain_req_has_owner, drain_req_reset_scope,
  input wire drain_req_ready,
  input wire drain_rsp_valid, input wire [54:0] drain_rsp_identity,
  input wire drain_rsp_has_owner, drain_rsp_reset_scope,
  input wire [8:0] alldrain_live, output wire drain_rsp_ready,
  output wire retire_valid, output wire [54:0] retire_identity,
  input wire retire_ready,
  output wire fault, quarantine
);
generate if(LIVE_STATE)begin:live
 ot_hbm_rf_visibility_fence_live #(.ENABLE(ENABLE)) actual(
 .clk(clk),
 .por_n(por_n),
 .rst_n(rst_n),
 .req_valid(req_valid),
 .req_identity(req_identity),
 .req_internal_SIMD(req_internal_SIMD),
 .req_ready(req_ready),
 .host_ack_valid(host_ack_valid),
 .host_ack_identity(host_ack_identity),
 .host_ack_ready(host_ack_ready),
 .simd_ack_retire_valid(simd_ack_retire_valid),
 .simd_ack_retire_identity(simd_ack_retire_identity),
 .simd_ack_retire_ready(simd_ack_retire_ready),
 .visible_valid(visible_valid),
 .visible_identity(visible_identity),
 .visible_ready(visible_ready),
 .consumer_valid(consumer_valid),
 .consumer_identity(consumer_identity),
 .consumer_ready(consumer_ready),
 .child_reverse_valid(child_reverse_valid),
 .child_reverse_identity(child_reverse_identity),
 .child_reverse_ready(child_reverse_ready),
 .parent_reverse_valid(parent_reverse_valid),
 .parent_reverse_identity(parent_reverse_identity),
 .parent_reverse_ready(parent_reverse_ready),
 .reverse_CDC_valid(reverse_CDC_valid),
 .reverse_CDC_identity(reverse_CDC_identity),
 .reverse_CDC_ready(reverse_CDC_ready),
 .drain_req_valid(drain_req_valid),
 .drain_req_identity(drain_req_identity),
 .drain_req_has_owner(drain_req_has_owner),
 .drain_req_reset_scope(drain_req_reset_scope),
 .drain_req_ready(drain_req_ready),
 .drain_rsp_valid(drain_rsp_valid),
 .drain_rsp_identity(drain_rsp_identity),
 .drain_rsp_has_owner(drain_rsp_has_owner),
 .drain_rsp_reset_scope(drain_rsp_reset_scope),
 .alldrain_live(alldrain_live),
 .drain_rsp_ready(drain_rsp_ready),
 .retire_valid(retire_valid),
 .retire_identity(retire_identity),
 .retire_ready(retire_ready),
 .fault(fault),
 .quarantine(quarantine));
end else begin:baseline
 ot_gpu_rf_visibility_fence_w6 #(.ENABLE(ENABLE)) actual(
 .clk(clk),
 .por_n(por_n),
 .rst_n(rst_n),
 .req_valid(req_valid),
 .req_identity(req_identity),
 .req_internal_SIMD(req_internal_SIMD),
 .req_ready(req_ready),
 .host_ack_valid(host_ack_valid),
 .host_ack_identity(host_ack_identity),
 .host_ack_ready(host_ack_ready),
 .simd_ack_retire_valid(simd_ack_retire_valid),
 .simd_ack_retire_identity(simd_ack_retire_identity),
 .simd_ack_retire_ready(simd_ack_retire_ready),
 .visible_valid(visible_valid),
 .visible_identity(visible_identity),
 .visible_ready(visible_ready),
 .consumer_valid(consumer_valid),
 .consumer_identity(consumer_identity),
 .consumer_ready(consumer_ready),
 .child_reverse_valid(child_reverse_valid),
 .child_reverse_identity(child_reverse_identity),
 .child_reverse_ready(child_reverse_ready),
 .parent_reverse_valid(parent_reverse_valid),
 .parent_reverse_identity(parent_reverse_identity),
 .parent_reverse_ready(parent_reverse_ready),
 .reverse_CDC_valid(reverse_CDC_valid),
 .reverse_CDC_identity(reverse_CDC_identity),
 .reverse_CDC_ready(reverse_CDC_ready),
 .drain_req_valid(drain_req_valid),
 .drain_req_identity(drain_req_identity),
 .drain_req_has_owner(drain_req_has_owner),
 .drain_req_reset_scope(drain_req_reset_scope),
 .drain_req_ready(drain_req_ready),
 .drain_rsp_valid(drain_rsp_valid),
 .drain_rsp_identity(drain_rsp_identity),
 .drain_rsp_has_owner(drain_rsp_has_owner),
 .drain_rsp_reset_scope(drain_rsp_reset_scope),
 .alldrain_live(alldrain_live),
 .drain_rsp_ready(drain_rsp_ready),
 .retire_valid(retire_valid),
 .retire_identity(retire_identity),
 .retire_ready(retire_ready),
 .fault(fault),
 .quarantine(quarantine));
end endgenerate
endmodule
