rtl/hdc/ot_hdc_delay.sv
rtl/hdc/ot_hdc_sfu.sv
rtl/hdc/ot_hdc_fpu.sv
rtl/hdc/ot_hdc_fp32_mul_pipe.sv
rtl/proto/ot_fp32_add_rne_pipe.sv
rtl/hdc/ot_hdc_fastfp_lat_f12.sv
rtl/hdc/v41/ot_hdc_fsqrt.sv
rtl/hdc/v41/ot_hdc_fdiv.sv
rtl/hdc/v41/ot_hdc_softplus.sv
rtl/hdc/v41x/ot_hdc_v41x_sfu.sv
rtl/hdc/v41/ot_hdc_actquant.sv
rtl/hdc/v41x/ot_dsrom_aq12.sv
rtl/hdc/v41x/ot_dsrom_divc.sv
rtl/hdc/ot_hdc_fastfp.sv
rtl/hdc/ot_hdc_fp32_f12.sv
rtl/hdc/ot_hdc_fp32_mul_lat.sv
rtl/hdc/ot_hdc_fp32_add_lat.sv
rtl/hdc/ot_hdc_prefix.sv
rtl/hdc/v41x/ot_dsrom_fp32_add_l6.sv
rtl/hdc/v41x/ot_dsrom_su_norm.sv
physical/hbm_norm_engine_view_mem1_20261007/ot_hbm_norm_engine_view.sv
