// Generated by tools/emb_hbm_port_sources.py. Wire aliases; no new latency.
`timescale 1ns/1ps
// Composite physical vehicle in the existing controller reservation.
// The KV command and raw landing interfaces remain separate from embedding.
// PHY must supply the full 288-bit protected codeword (provider still OPEN).
module ot_qfd_emb_pc_bus #(
 parameter integer ENABLE=0,PC=0,PHASE=0,SQD=4,S_STARVE=8,TWIN=0,TWIN_ROFF=0
)(
 input wire clk,rst_n,hclk,hrst_n,
 input wire cmd_v,input wire [31:0] cmd,input wire [2:0] read_credit,
 output wire cmd_credit,
 input wire [287:0] emb_cmd, output wire [259:0] emb_ret,
 output wire row_v,output wire [2:0] row_op,output wire [4:0] row_bank,
 output wire [18:0] row_row,output wire col_v,col_we,col_sr,
 output wire [4:0] col_bank,col_col,output wire busy,
 input wire r_v,input wire [287:0] r_d,output wire [287:0] wd,
 output wire kv_v,output wire [287:0] kv_d,
 output wire fault_core,fault_hbm
);
 ot_qfd_emb_pc #(.ENABLE(ENABLE),.PC(PC),.PHASE(PHASE),.SQD(SQD),.S_STARVE(S_STARVE),.TWIN(TWIN),.TWIN_ROFF(TWIN_ROFF)) core(
 .clk(clk),
 .rst_n(rst_n),
 .hclk(hclk),
 .hrst_n(hrst_n),
 .cmd_v(cmd_v),
 .cmd(cmd),
 .read_credit(read_credit),
 .cmd_credit(cmd_credit),
 .row_v(row_v),
 .row_op(row_op),
 .row_bank(row_bank),
 .row_row(row_row),
 .col_v(col_v),
 .col_we(col_we),
 .col_sr(col_sr),
 .col_bank(col_bank),
 .col_col(col_col),
 .busy(busy),
 .r_v(r_v),
 .r_d(r_d),
 .wd(wd),
 .kv_v(kv_v),
 .kv_d(kv_d),
 .fault_core(fault_core),
 .fault_hbm(fault_hbm),
 .s_v(emb_cmd[287]),
 .w_v(emb_cmd[286]),
 .s_we(emb_cmd[285]),
 .s_bank(emb_cmd[284:280]),
 .s_col(emb_cmd[279:275]),
 .s_row(emb_cmd[274:256]),
 .w_d(emb_cmd[255:0]),
 .s_credit(emb_ret[259]),
 .e_v(emb_ret[258]),
 .e_d(emb_ret[257:0])
 );
endmodule
