// Generated by tools/emb_hbm_port_sources.py. Wire aliases; no new latency.
module ot_qfd_emb_strip_bus_crc #(parameter integer CRC_PIPE=0,CRC_MUT=0,ENABLE=0, STK=0, SQD=4, PFD=4, TXQ=4, OCR=4, ROW0=24427, TWIN=0, TWIN_ROFF=0, MUT=0)(
 input wire clk, rst_n,
 input wire [524:0] link_i,
 output wire [524:0] link_o,
 output wire [287:0] cmd0,
 output wire [287:0] cmd1,
 output wire [287:0] cmd2,
 output wire [287:0] cmd3,
 output wire [287:0] cmd4,
 output wire [287:0] cmd5,
 output wire [287:0] cmd6,
 output wire [287:0] cmd7,
 output wire [287:0] cmd8,
 output wire [287:0] cmd9,
 output wire [287:0] cmd10,
 output wire [287:0] cmd11,
 output wire [287:0] cmd12,
 output wire [287:0] cmd13,
 output wire [287:0] cmd14,
 output wire [287:0] cmd15,
 output wire [287:0] cmd16,
 output wire [287:0] cmd17,
 output wire [287:0] cmd18,
 output wire [287:0] cmd19,
 output wire [287:0] cmd20,
 output wire [287:0] cmd21,
 output wire [287:0] cmd22,
 output wire [287:0] cmd23,
 output wire [287:0] cmd24,
 output wire [287:0] cmd25,
 output wire [287:0] cmd26,
 output wire [287:0] cmd27,
 output wire [287:0] cmd28,
 output wire [287:0] cmd29,
 output wire [287:0] cmd30,
 output wire [287:0] cmd31,
 input wire [259:0] ret0,
 input wire [259:0] ret1,
 input wire [259:0] ret2,
 input wire [259:0] ret3,
 input wire [259:0] ret4,
 input wire [259:0] ret5,
 input wire [259:0] ret6,
 input wire [259:0] ret7,
 input wire [259:0] ret8,
 input wire [259:0] ret9,
 input wire [259:0] ret10,
 input wire [259:0] ret11,
 input wire [259:0] ret12,
 input wire [259:0] ret13,
 input wire [259:0] ret14,
 input wire [259:0] ret15,
 input wire [259:0] ret16,
 input wire [259:0] ret17,
 input wire [259:0] ret18,
 input wire [259:0] ret19,
 input wire [259:0] ret20,
 input wire [259:0] ret21,
 input wire [259:0] ret22,
 input wire [259:0] ret23,
 input wire [259:0] ret24,
 input wire [259:0] ret25,
 input wire [259:0] ret26,
 input wire [259:0] ret27,
 input wire [259:0] ret28,
 input wire [259:0] ret29,
 input wire [259:0] ret30,
 input wire [259:0] ret31,
 output wire fault,
 output wire [7:0] fault_code,
 output wire [31:0] ce_cnt, ue_info
);
generate if (ENABLE != 0) begin: enabled
 wire [31:0] s_m,w_m,s_cr,e_v; wire s_we; wire [4:0] s_bank,s_col; wire [18:0] s_row; wire [255:0] w_d; wire [8255:0] e_d;
 assign cmd0={s_m[0],w_m[0],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[0],e_v[0],e_d[0*258+:258]}=ret0;
 assign cmd1={s_m[1],w_m[1],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[1],e_v[1],e_d[1*258+:258]}=ret1;
 assign cmd2={s_m[2],w_m[2],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[2],e_v[2],e_d[2*258+:258]}=ret2;
 assign cmd3={s_m[3],w_m[3],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[3],e_v[3],e_d[3*258+:258]}=ret3;
 assign cmd4={s_m[4],w_m[4],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[4],e_v[4],e_d[4*258+:258]}=ret4;
 assign cmd5={s_m[5],w_m[5],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[5],e_v[5],e_d[5*258+:258]}=ret5;
 assign cmd6={s_m[6],w_m[6],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[6],e_v[6],e_d[6*258+:258]}=ret6;
 assign cmd7={s_m[7],w_m[7],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[7],e_v[7],e_d[7*258+:258]}=ret7;
 assign cmd8={s_m[8],w_m[8],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[8],e_v[8],e_d[8*258+:258]}=ret8;
 assign cmd9={s_m[9],w_m[9],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[9],e_v[9],e_d[9*258+:258]}=ret9;
 assign cmd10={s_m[10],w_m[10],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[10],e_v[10],e_d[10*258+:258]}=ret10;
 assign cmd11={s_m[11],w_m[11],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[11],e_v[11],e_d[11*258+:258]}=ret11;
 assign cmd12={s_m[12],w_m[12],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[12],e_v[12],e_d[12*258+:258]}=ret12;
 assign cmd13={s_m[13],w_m[13],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[13],e_v[13],e_d[13*258+:258]}=ret13;
 assign cmd14={s_m[14],w_m[14],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[14],e_v[14],e_d[14*258+:258]}=ret14;
 assign cmd15={s_m[15],w_m[15],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[15],e_v[15],e_d[15*258+:258]}=ret15;
 assign cmd16={s_m[16],w_m[16],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[16],e_v[16],e_d[16*258+:258]}=ret16;
 assign cmd17={s_m[17],w_m[17],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[17],e_v[17],e_d[17*258+:258]}=ret17;
 assign cmd18={s_m[18],w_m[18],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[18],e_v[18],e_d[18*258+:258]}=ret18;
 assign cmd19={s_m[19],w_m[19],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[19],e_v[19],e_d[19*258+:258]}=ret19;
 assign cmd20={s_m[20],w_m[20],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[20],e_v[20],e_d[20*258+:258]}=ret20;
 assign cmd21={s_m[21],w_m[21],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[21],e_v[21],e_d[21*258+:258]}=ret21;
 assign cmd22={s_m[22],w_m[22],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[22],e_v[22],e_d[22*258+:258]}=ret22;
 assign cmd23={s_m[23],w_m[23],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[23],e_v[23],e_d[23*258+:258]}=ret23;
 assign cmd24={s_m[24],w_m[24],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[24],e_v[24],e_d[24*258+:258]}=ret24;
 assign cmd25={s_m[25],w_m[25],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[25],e_v[25],e_d[25*258+:258]}=ret25;
 assign cmd26={s_m[26],w_m[26],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[26],e_v[26],e_d[26*258+:258]}=ret26;
 assign cmd27={s_m[27],w_m[27],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[27],e_v[27],e_d[27*258+:258]}=ret27;
 assign cmd28={s_m[28],w_m[28],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[28],e_v[28],e_d[28*258+:258]}=ret28;
 assign cmd29={s_m[29],w_m[29],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[29],e_v[29],e_d[29*258+:258]}=ret29;
 assign cmd30={s_m[30],w_m[30],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[30],e_v[30],e_d[30*258+:258]}=ret30;
 assign cmd31={s_m[31],w_m[31],s_we,s_bank,s_col,s_row,w_d};
 assign {s_cr[31],e_v[31],e_d[31*258+:258]}=ret31;
 ot_qfd_emb_strip_crc #(.CRC_PIPE(CRC_PIPE),.CRC_MUT(CRC_MUT),.STK(STK),.NPC(32),.SQD(SQD),.PFD(PFD),.TXQ(TXQ),.OCR(OCR),.ROW0(ROW0),.TWIN(TWIN),.TWIN_ROFF(TWIN_ROFF),.MUT(MUT)) core(
 .clk(clk),.rst_n(rst_n),.i_v(link_i[524]),.i_d(link_i[523:1]),.o_cr(link_i[0]),
 .o_v(link_o[524]),.o_d(link_o[523:1]),.i_cr(link_o[0]),
 .s_m(s_m),.w_m(w_m),.s_we(s_we),.s_bank(s_bank),.s_col(s_col),.s_row(s_row),.w_d(w_d),
 .s_cr(s_cr),.e_v(e_v),.e_d(e_d),.fault(fault),.fault_code(fault_code),.ce_cnt(ce_cnt),.ue_info(ue_info));
 end else begin: disabled
 assign cmd0=288'b0;
 assign cmd1=288'b0;
 assign cmd2=288'b0;
 assign cmd3=288'b0;
 assign cmd4=288'b0;
 assign cmd5=288'b0;
 assign cmd6=288'b0;
 assign cmd7=288'b0;
 assign cmd8=288'b0;
 assign cmd9=288'b0;
 assign cmd10=288'b0;
 assign cmd11=288'b0;
 assign cmd12=288'b0;
 assign cmd13=288'b0;
 assign cmd14=288'b0;
 assign cmd15=288'b0;
 assign cmd16=288'b0;
 assign cmd17=288'b0;
 assign cmd18=288'b0;
 assign cmd19=288'b0;
 assign cmd20=288'b0;
 assign cmd21=288'b0;
 assign cmd22=288'b0;
 assign cmd23=288'b0;
 assign cmd24=288'b0;
 assign cmd25=288'b0;
 assign cmd26=288'b0;
 assign cmd27=288'b0;
 assign cmd28=288'b0;
 assign cmd29=288'b0;
 assign cmd30=288'b0;
 assign cmd31=288'b0;
 assign link_o=525'b0; assign fault=1'b0; assign fault_code=8'b0; assign ce_cnt=32'b0; assign ue_info=32'b0;
 end endgenerate
endmodule
