# generated by physical/hbm_accel_die_views/common/spine_io_min.py for hfd_cmdproc_n (die master hfd_cmdproc):
# FF hold credit of the connected die path per port (read after vclk_corner_true.sdc; FF session only)
if {[llength [get_libs -quiet *_FF_*]] && [llength [get_clocks -quiet vclk]]} {
  sta::redirect_string_begin
  report_clock_latency -clocks core_clk
  set ot_s [sta::redirect_string_end]
  if {[regexp {rise -> rise.*?([0-9.]+)\s+([0-9.]+)\s+latency} $ot_s -> ot_lo ot_hi]} {
    foreach ot_q [get_ports -quiet {cNE cNE[*]}] { if {[get_property $ot_q direction] eq "input"} { set_input_delay -min [expr {$ot_hi - $ot_lo + 172.2}] -clock vclk $ot_q } elseif {[get_property $ot_q direction] eq "output"} { set_output_delay -min 140.0 -clock vclk $ot_q } }
    foreach ot_q [get_ports -quiet {cNW cNW[*]}] { if {[get_property $ot_q direction] eq "input"} { set_input_delay -min [expr {$ot_hi - $ot_lo + 172.25}] -clock vclk $ot_q } elseif {[get_property $ot_q direction] eq "output"} { set_output_delay -min 140.05 -clock vclk $ot_q } }
    foreach ot_q [get_ports -quiet {f_barrier f_barrier[*]}] { if {[get_property $ot_q direction] eq "input"} { set_input_delay -min [expr {$ot_hi - $ot_lo + 472.92}] -clock vclk $ot_q } elseif {[get_property $ot_q direction] eq "output"} { set_output_delay -min 440.72 -clock vclk $ot_q } }
    foreach ot_q [get_ports -quiet {f_coll f_coll[*]}] { if {[get_property $ot_q direction] eq "input"} { set_input_delay -min [expr {$ot_hi - $ot_lo + 80.23}] -clock vclk $ot_q } elseif {[get_property $ot_q direction] eq "output"} { set_output_delay -min 48.03 -clock vclk $ot_q } }
    foreach ot_q [get_ports -quiet {t_barrier t_barrier[*]}] { if {[get_property $ot_q direction] eq "input"} { set_input_delay -min [expr {$ot_hi - $ot_lo + 472.92}] -clock vclk $ot_q } elseif {[get_property $ot_q direction] eq "output"} { set_output_delay -min 440.72 -clock vclk $ot_q } }
    foreach ot_q [get_ports -quiet {t_coll t_coll[*]}] { if {[get_property $ot_q direction] eq "input"} { set_input_delay -min [expr {$ot_hi - $ot_lo + 84.66}] -clock vclk $ot_q } elseif {[get_property $ot_q direction] eq "output"} { set_output_delay -min 52.46 -clock vclk $ot_q } }
    foreach ot_q [get_ports -quiet {t_su_NE t_su_NE[*]}] { if {[get_property $ot_q direction] eq "input"} { set_input_delay -min [expr {$ot_hi - $ot_lo + 293.1}] -clock vclk $ot_q } elseif {[get_property $ot_q direction] eq "output"} { set_output_delay -min 260.9 -clock vclk $ot_q } }
    foreach ot_q [get_ports -quiet {t_su_NW t_su_NW[*]}] { if {[get_property $ot_q direction] eq "input"} { set_input_delay -min [expr {$ot_hi - $ot_lo + 293.1}] -clock vclk $ot_q } elseif {[get_property $ot_q direction] eq "output"} { set_output_delay -min 260.9 -clock vclk $ot_q } }
    foreach ot_q [get_ports -quiet {xb xb[*]}] { if {[get_property $ot_q direction] eq "input"} { set_input_delay -min [expr {$ot_hi - $ot_lo + 32.2}] -clock vclk $ot_q } elseif {[get_property $ot_q direction] eq "output"} { set_output_delay -min 0.0 -clock vclk $ot_q } }
    foreach ot_q [get_ports -quiet {xl xl[*]}] { if {[get_property $ot_q direction] eq "input"} { set_input_delay -min [expr {$ot_hi - $ot_lo + 32.2}] -clock vclk $ot_q } elseif {[get_property $ot_q direction] eq "output"} { set_output_delay -min 0.0 -clock vclk $ot_q } }
    foreach ot_q [get_ports -quiet {xt xt[*]}] { if {[get_property $ot_q direction] eq "input"} { set_input_delay -min [expr {$ot_hi - $ot_lo + 32.2}] -clock vclk $ot_q } elseif {[get_property $ot_q direction] eq "output"} { set_output_delay -min 0.0 -clock vclk $ot_q } }
    puts "OT_IOMIN: per-port die-path hold credit applied"
  }
}
