// GENERATED by tools/hgi_seq_vectors.py
localparam integer SEQ_NW = 1754;
localparam integer SEQ_NCASE = 38;
localparam integer SEQ_NCASE_STALE = 1;
localparam integer SEQ_NEXP = 28402;
localparam integer SEQ_NEXP_STALE = 528;
localparam integer SEQ_NVM0 = 37;
