# Generated by tools/dsrom_v9_parent_loads.py; actual measured family envelopes in fF.
set_load 8.81198 [get_ports {engine_cfg*}]
set_load 0.577042 [get_ports {engine_cdec*}]
set_load 2.3397 [get_ports {engine_xs*}]
set_load 5.123972 [get_ports {engine_go*}]
set_load 11.708225 [get_ports {engine_reset_n*}]
set_load 5.2147 [get_ports {engine_clk}]
set_load 0.577042 [get_ports {f_bus* node_v node_e node_t* node_d* busy fault captured_root*}]
