// Candidate native partition. Compile pinned native source with OT_PQ_ROM_PORTS.
// External ROMs require real two-cycle macro adapters; no screen memory or quantiser stub.
module ot_s81_pq_native_partition (
    input wire clk,
    input wire rst_n,
    input wire go,
    input wire [8:0] i_ph,
    input wire [2:0] i_np,
    input wire [18:0] i_xbase,
    input wire [18:0] i_xps,
    input wire [18:0] i_obase,
    input wire [18:0] i_ops,
    input wire [1:0] i_fmt,
    output wire ready,
    output wire idle,
    output wire x_re,
    output wire [18:0] x_addr,
    input wire [2047:0] x_q,
    output wire [127:0] w_we,
    output wire [2431:0] w_addr,
    output wire [4095:0] w_data,
    input wire [127:0] r_v,
    input wire [2047:0] r_row,
    input wire [383:0] r_pos,
    input wire [4095:0] r_fp32,
    input wire [2047:0] r_bf16,
    input wire [127:0] r_e,
    output wire [1632:0] f_bus,
    input wire f_fault,
    output wire fault,
    output wire [31:0] phase_cycles,
    output wire ev_go,
    output wire ev_end,
    output wire [1:0] ev_tag,
    output wire [9:0] rom_pa0,
    output wire [9:0] rom_pa1,
    input wire [63:0] rom_pq0,
    input wire [63:0] rom_pq1,
    output wire [10:0] rom_sa,
    input wire [47:0] rom_sq
);
  ot_v41_spine_pqc_w17w10 #( .PHW(9), .SAW(11), .KMAX(6144), .R(128), .VAW(19), .VRD(64), .PQ(1) ) u_sp (
    .clk(clk),
    .rst_n(rst_n),
    .go(go),
    .i_ph(i_ph),
    .i_np(i_np),
    .i_xbase(i_xbase),
    .i_xps(i_xps),
    .i_obase(i_obase),
    .i_ops(i_ops),
    .i_fmt(i_fmt),
    .ready(ready),
    .idle(idle),
    .x_re(x_re),
    .x_addr(x_addr),
    .x_q(x_q),
    .w_we(w_we),
    .w_addr(w_addr),
    .w_data(w_data),
    .r_v(r_v),
    .r_row(r_row),
    .r_pos(r_pos),
    .r_fp32(r_fp32),
    .r_bf16(r_bf16),
    .r_e(r_e),
    .f_bus(f_bus),
    .f_fault(f_fault),
    .fault(fault),
    .phase_cycles(phase_cycles),
    .ev_go(ev_go),
    .ev_end(ev_end),
    .ev_tag(ev_tag),
    .rom_pa0(rom_pa0),
    .rom_pa1(rom_pa1),
    .rom_pq0(rom_pq0),
    .rom_pq1(rom_pq1),
    .rom_sa(rom_sa),
    .rom_sq(rom_sq),
    .f_cfg_go(),
    .f_cfg_ph(),
    .f_cfg_np(),
    .f_go(),
    .f_go_bf(),
    .f_go_tag(),
    .f_xs_v(),
    .f_xs_p(),
    .f_xs_b(),
    .f_xs_sv(),
    .f_xs_q0(),
    .f_xs_e0(),
    .f_xs_q1(),
    .f_xs_e1(),
    .f_xs_pos(),
    .f_xb_pos(),
    .f_xb_v(),
    .f_xb_b(),
    .f_xb_sv(),
    .f_xb_u(),
    .f_xb_d()
  );
endmodule
