// Isolated preserved Claude control-family snapshot. Defaults remain off.
// FAST state/router paths remain experimental and physically unqualified.
`timescale 1ns/1ps
// ---------------------------------------------------------------------------
// DSpark (V4.1 MTP) control plane of the V4.1 HBM comparator: default-off build top.
//
// Composes the new blocks with the W19 router selector:
//   ot_dshbm_dspark_ctl_ctl_snapshot     the speculative loop (accept through ot_dshbm_accept_port: ot_hdc_accept
//                           or Codex's protected DS MTP accept leaf, ACCEPT_LEAF = 1),
//                            (prefill, draft, Markov chain, verify,
//                           accept, commit = rollback), commands to the SM cluster;
//   ot_dshbm_spec_state     position-indexed state addressing (rings sized for exact
//                           rollback), the token-history ring;
//   ot_dshbm_argmax         the SM epilogue argmax (verify targets; Markov bias add);
//   ot_gpu_router_topk x 2  W19's exact top-K selector: the backbone's top-KV of NEXP
//                           per verify position, the drafter's top-KD of NDEXP per block row;
//   ot_dshbm_expert_union_ctl_snapshot   the union of a pass's per-column selections, ascending by id,
//                           with per-expert column masks -> ot_gpu_expert_fetch (outside).
// Router vectors arrive RP values a beat with their column number; a union flush waits
// until every vector in the selectors has come out.
// Nothing here is instantiated by any existing top: the build is opt-in.
// ---------------------------------------------------------------------------
module ot_hbm_ctl_sm_join #(
    parameter integer B      = 5,
    parameter integer PMAX   = 8,
    parameter integer TW     = 17,
    parameter integer NL     = 40,
    parameter integer NST    = 3,
    parameter integer MAXPOS = 128,
    parameter integer W      = 128,
    parameter integer WR     = 136,
    parameter integer SR     = 10,
    parameter integer TR     = 16,
    parameter integer NG     = 4,
    parameter integer NSRC   = 4,
    parameter [NSRC*4-1:0] RLOG = 16'h0111,
    parameter integer CKMAX  = 1 << 16,
    parameter integer AW     = 32,
    parameter integer LP     = 8,
    parameter integer FLAT   = 7,
    parameter integer NEXP   = 12,
    parameter integer KV     = 6,
    parameter integer NDEXP  = 4,
    parameter integer KD     = 3,
    parameter integer RP     = 4,
    parameter integer IW     = 9,
    parameter integer MUT    = 0,
    parameter integer ACCEPT_LEAF = 0,
    parameter integer CTL_FAST = 0, // Independent control-only opt-in; no state/router latency change.
    parameter integer SM_ENABLE = 0,
    parameter integer NC = 8,
    parameter integer RMAX = 4096,
    parameter integer XD = 128
) (
    input  wire               clk,
    input  wire               rst_n,
    // host
    input  wire               start,
    input  wire [3:0]         cfg_gamma,
    input  wire               cfg_force,
    input  wire [15:0]        cfg_ngen,
    input  wire [15:0]        cfg_plen,
    output wire [15:0]        p_addr,
    input  wire [TW-1:0]      p_tok,
    output wire [15:0]        f_addr,
    input  wire [TW-1:0]      f_tok,
    output wire               e_v,
    output wire [TW-1:0]      e_tok,
    output wire [15:0]        e_idx,
    output wire               done,
    // engine commands
    output wire               cmd_v,
    output wire               cmd_ready,
    output wire [3:0]         cmd_op,
    output wire [7:0]         cmd_idx,
    output wire [3:0]         cmd_ncol,
    output wire [31:0]        cmd_pos,
    output wire [TW-1:0]      cmd_tok1,
    output wire [PMAX*TW-1:0] cmd_toks,
    output wire               eng_done,
    // logit rows into the epilogue
    input  wire               lg_v,
    input  wire               lg_last,
    input  wire               lg_bias_en,
    input  wire [LP-1:0]      lg_mask,
    input  wire [LP*32-1:0]   lg_vals,
    input  wire [LP*32-1:0]   lg_bias,
    output wire               am_v,
    output wire [TW-1:0]      am_idx,
    output wire               am_fault,
    // spec-state requests
    input  wire               sr_v,
    output wire               sr_ready,
    input  wire [3:0]         sr_kind,
    input  wire [15:0]        sr_idx,
    input  wire [31:0]        sr_pos,
    output wire               sa_v,
    output wire [AW-1:0]      sa_addr,
    output wire [TW-1:0]      sa_tok,
    output wire               sa_pad,
    output wire               sa_last,
    output wire               sa_err,
    output wire [31:0]        n_committed,
    // router vectors
    input  wire               rv_v,
    input  wire               rv_draft,
    input  wire [RP*32-1:0]   rv_vals,
    input  wire               rv_last,
    input  wire [2:0]         rv_col,
    output wire               t_v,
    output wire [KV*IW-1:0]   t_ids,
    output wire [2:0]         t_col,
    // expert union
    input  wire               u_clr,
    input  wire               u_flush,
    output wire               u_v,
    input  wire               u_ready,
    output wire [IW-1:0]      u_id,
    output wire [PMAX-1:0]    u_mask,
    output wire               u_last,
    // observation
    output wire               step_v,
    output wire [2:0]         step_a,
    output wire [3:0]         step_g,
    output wire [15:0]        steps,
    output wire [31:0]        cyc_total,
    output wire [31:0]        cyc_engine,
    output wire [31:0]        cyc_markov,
    // Prepared native SM passes for the current held control command. No command replay/host eng_done.
    input wire plan_v, output wire plan_ready,
    input wire [3:0] plan_cmd_op, input wire [7:0] plan_cmd_idx,
    input wire [31:0] plan_cmd_pos,
    input wire [$clog2(RMAX):0] plan_rows,
    input wire [7:0] plan_g, input wire plan_gs, input wire [1:0] plan_fmt,
    input wire [31:0] plan_base, input wire [23:0] plan_lines,
    input wire plan_last, input wire result_reserved,
    output wire req_v, input wire req_ready, output wire [31:0] req_addr,
    output wire [9:0] req_tag, input wire rsp_v, input wire [9:0] rsp_tag,
    input wire [1087:0] rsp_data,
    input wire xw_en, input wire [$clog2(XD)-1:0] xw_addr,
    input wire [6:0] xw_grp, input wire [2047:0] xw_data,
    output wire rv, output wire [$clog2(RMAX)-1:0] rrow,
    output wire [NC*32-1:0] rdata, output wire sm_busy, output wire fault,
    output wire arrive, input wire release_in, output wire released
);
    ot_dshbm_dspark_top_ctl_snapshot #(.B(B),.PMAX(PMAX),.TW(TW),.NL(NL),.NST(NST),
      .MAXPOS(MAXPOS),.W(W),.WR(WR),.SR(SR),.TR(TR),.NG(NG),.NSRC(NSRC),.RLOG(RLOG),
      .CKMAX(CKMAX),.AW(AW),.LP(LP),.FLAT(FLAT),.NEXP(NEXP),.KV(KV),.NDEXP(NDEXP),
      .KD(KD),.RP(RP),.IW(IW),.MUT(MUT),.ACCEPT_LEAF(ACCEPT_LEAF),.CTL_FAST(CTL_FAST),.FAST(0)) u_ctl (
      .clk(clk),
      .rst_n(rst_n),
      .start(start),
      .cfg_gamma(cfg_gamma),
      .cfg_force(cfg_force),
      .cfg_ngen(cfg_ngen),
      .cfg_plen(cfg_plen),
      .p_addr(p_addr),
      .p_tok(p_tok),
      .f_addr(f_addr),
      .f_tok(f_tok),
      .e_v(e_v),
      .e_tok(e_tok),
      .e_idx(e_idx),
      .done(done),
      .cmd_v(cmd_v),
      .cmd_ready(cmd_ready),
      .cmd_op(cmd_op),
      .cmd_idx(cmd_idx),
      .cmd_ncol(cmd_ncol),
      .cmd_pos(cmd_pos),
      .cmd_tok1(cmd_tok1),
      .cmd_toks(cmd_toks),
      .eng_done(eng_done),
      .lg_v(lg_v),
      .lg_last(lg_last),
      .lg_bias_en(lg_bias_en),
      .lg_mask(lg_mask),
      .lg_vals(lg_vals),
      .lg_bias(lg_bias),
      .am_v(am_v),
      .am_idx(am_idx),
      .am_fault(am_fault),
      .sr_v(sr_v),
      .sr_ready(sr_ready),
      .sr_kind(sr_kind),
      .sr_idx(sr_idx),
      .sr_pos(sr_pos),
      .sa_v(sa_v),
      .sa_addr(sa_addr),
      .sa_tok(sa_tok),
      .sa_pad(sa_pad),
      .sa_last(sa_last),
      .sa_err(sa_err),
      .n_committed(n_committed),
      .rv_v(rv_v),
      .rv_draft(rv_draft),
      .rv_vals(rv_vals),
      .rv_last(rv_last),
      .rv_col(rv_col),
      .t_v(t_v),
      .t_ids(t_ids),
      .t_col(t_col),
      .u_clr(u_clr),
      .u_flush(u_flush),
      .u_v(u_v),
      .u_ready(u_ready),
      .u_id(u_id),
      .u_mask(u_mask),
      .u_last(u_last),
      .step_v(step_v),
      .step_a(step_a),
      .step_g(step_g),
      .steps(steps),
      .cyc_total(cyc_total),
      .cyc_engine(cyc_engine),
      .cyc_markov(cyc_markov));
    ot_hbm_ctl_sm_bridge #(.SM_ENABLE(SM_ENABLE),.NC(NC),.RMAX(RMAX),.XD(XD)) u_engine (.*);
endmodule
