rtl/gpu/w6/ot_gpu_w6_secded_pkg.sv
rtl/experimental/ds_mtp_accept_20261003/ot_hdc_mtp_accept_guarded.sv
rtl/hdc/ot_hdc_accept.sv
rtl/gpu/ot_gpu_router_topk.sv
rtl/gpu/ot_gpu_fadd.sv
rtl/hdc/ot_hdc_fp32_add_lat.sv
rtl/hdc/ot_hdc_fp32_mul_lat.sv
rtl/hdc/ot_hdc_fastfp.sv
rtl/hdc/ot_hdc_prefix.sv
rtl/gpu/dshbm/ot_dshbm_accept_port.sv
rtl/gpu/dshbm/ot_dshbm_argmax.sv
rtl/gpu/dshbm/ot_dshbm_expert_union.sv
rtl/gpu/dshbm/ot_dshbm_spec_state.sv
rtl/gpu/dshbm/ot_dshbm_dspark_ctl.sv
rtl/gpu/dshbm/ot_dshbm_dspark_top.sv
rtl/v41rom/ot_v41_bterm.sv
rtl/v41rom/ot_v41_bterm2.sv
rtl/gpu/ot_gpu_tree.sv
rtl/gpu/ot_gpu_issue.sv
rtl/gpu/ot_gpu_stack.sv
rtl/gpu/ot_gpu_tc_col.sv
rtl/gpu/ot_gpu_bd_col.sv
rtl/hdc/v41/ot_hdc_blockdot.sv
rtl/gpu/ot_gpu_bulk_copy.sv
rtl/gpu/ot_gpu_sm_v.sv
rtl/hdc/ot_hdc_fpu.sv
rtl/hdc/ot_hdc_fp32_mul_pipe.sv
rtl/proto/ot_fp32_add_rne_pipe.sv
rtl/hdc/ot_hdc_sfu.sv
rtl/hdc/ot_hdc_delay.sv
physical/asap7_memory_macros/ot_sram_1r1w_1024x256_m2_r2c2/ot_sram_1r1w_1024x256_m2_r2c2.v
physical/asap7_memory_macros/ot_sram_1r1w_128x256_m1_r2c2/ot_sram_1r1w_128x256_m1_r2c2.v
rtl/hbm_accel/epilogue/ot_hbm_accel_issue.sv
rtl/hbm_accel/epilogue/ot_hbm_accel_bulk_copy.sv
physical/hbm_accel_macros/ot_sram_1r1w_512x256_m1_r2c2/ot_sram_1r1w_512x256_m1_r2c2.v
rtl/hbm_accel/sm/ot_hbm_accel_tc16.sv
rtl/hbm_accel/sm/ot_hbm_accel_stack.sv
rtl/hbm_accel/sm/ot_hbm_accel_sm_v.sv
rtl/experimental/hbm_ctl_fmax_20261004/ot_dshbm_dspark_ctl_ctl_snapshot.sv
rtl/experimental/hbm_ctl_fmax_20261004/ot_dshbm_dspark_top_ctl_snapshot.sv
rtl/experimental/hbm_ctl_fmax_20261004/ot_dshbm_expert_union_ctl_snapshot.sv
rtl/experimental/hbm_ctl_fmax_20261004/ot_dshbm_spec_state_f_ctl_snapshot.sv
rtl/experimental/hbm_ctl_fmax_20261004/ot_gpu_router_topk_f_ctl_snapshot.sv
rtl/experimental/hbm_ctl_sm_join_20261004/ot_hbm_ctl_sm_bridge.sv
rtl/experimental/hbm_ctl_sm_join_20261004/ot_hbm_ctl_sm_join.sv
