`timescale 1ps/1ps
// Source-only installed hierarchy: physical producer ports must be joined.
module ot_gpu_qwen_native_aperture_cluster #(parameter bit ENABLE=0)(
 input wire [0:0] clk,
 input wire [63:0] por_n,
 input wire [63:0] warm_reset,
 input wire [63:0] issuer_held_valid,
 input wire [63:0] issuer_held_fault,
 input wire [15295:0] issuer_held_tuple,
 input wire [3519:0] issuer_held_owner,
 input wire [63:0] profile_valid,
 input wire [15295:0] profile_tuple,
 input wire [703:0] profile_PC,
 input wire [4095:0] profile_sequence,
 input wire [16383:0] profile_shape,
 input wire [255:0] profile_present,
 input wire [255:0] profile_double,
 input wire [63:0] profile_result_double,
 input wire [63:0] cursor_load_valid,
 output wire [63:0] cursor_load_ready,
 input wire [15295:0] cursor_load_tuple,
 input wire [3519:0] cursor_load_owner,
 input wire [4095:0] cursor_load_sequence,
 input wire [511:0] cursor_load_descriptor,
 input wire [191:0] cursor_load_operands,
 input wire [511:0] cursor_load_types,
 input wire [255:0] cursor_load_signed_i8,
 input wire [2047:0] cursor_load_counts,
 input wire [255:0] cursor_load_vector_mask,
 input wire [255:0] cursor_load_template,
 input wire [383:0] cursor_load_step,
 input wire [127:0] cursor_load_substep,
 input wire [255:0] cursor_load_scalars,
 input wire [511:0] cursor_load_tail,
 output wire [63:0] source_cursor_valid,
 output wire [63:0] source_cursor_advance_valid,
 input wire [63:0] source_cursor_advance_ready,
 output wire [511:0] source_descriptor,
 output wire [511:0] source_types,
 output wire [511:0] source_tail,
 output wire [191:0] source_operands,
 output wire [255:0] source_signed_i8_mask,
 output wire [255:0] source_vector_mask,
 output wire [255:0] source_template,
 output wire [255:0] source_scalars,
 output wire [2047:0] source_counts,
 output wire [383:0] source_ordered_step,
 output wire [127:0] source_substep,
 input wire [63:0] frame_accept,
 input wire [15295:0] frame_tuple,
 input wire [3519:0] frame_owner,
 input wire [63:0] terminal_accept,
 input wire [15295:0] terminal_tuple,
 input wire [3519:0] terminal_owner,
 input wire [4095:0] terminal_sequence,
 input wire [63:0] begin_valid,
 output wire [63:0] begin_ready,
 input wire [63:0] capture_valid,
 output wire [63:0] capture_ready,
 input wire [191:0] capture_aperture,
 input wire [383:0] capture_bank,
 input wire [1151:0] capture_slots,
 input wire [703:0] capture_version,
 input wire [63:0] capture_workspace,
 input wire [63:0] query_valid,
 input wire [63:0] query_retained,
 input wire [63:0] query_write,
 input wire [63:0] query_workspace,
 input wire [63:0] bank_fault,
 input wire [15295:0] query_tuple,
 input wire [575:0] query_slot,
 input wire [2943:0] query_owner,
 input wire [703:0] query_version,
 input wire [575:0] query_first,
 input wire [639:0] query_end,
 output wire [76479:0] lease_tuple,
 output wire [3519:0] lease_version,
 output wire [5759:0] lease_slots,
 output wire [14719:0] lease_owner,
 output wire [1919:0] lease_bank,
 output wire [319:0] lease_workspace,
 output wire [319:0] lease_write,
 output wire [319:0] lease_double,
 input wire [63:0] bank_scope_valid,
 input wire [63:0] bank_scope_writable,
 input wire [63:0] bank_scope_workspace,
 input wire [15295:0] bank_scope_tuple,
 input wire [3519:0] bank_scope_owner,
 input wire [63:0] ack_accept,
 input wire [575:0] ack_slot,
 input wire [2943:0] ack_owner,
 input wire [63:0] visibility_valid,
 input wire [15295:0] visibility_tuple,
 input wire [3519:0] visibility_owner,
 input wire [4095:0] visibility_sequence,
 input wire [63:0] reverse_accept,
 input wire [15295:0] reverse_tuple,
 input wire [3519:0] reverse_owner,
 input wire [4095:0] reverse_sequence,
 output wire [63:0] read_route_valid,
 output wire [63:0] write_route_valid,
 output wire [383:0] read_bank,
 output wire [383:0] write_bank,
 output wire [575:0] read_slot,
 output wire [575:0] write_slot,
 output wire [2943:0] read_owner,
 output wire [2943:0] write_owner,
 output wire [63:0] authority_valid,
 output wire [15295:0] authority_tuple,
 output wire [3519:0] authority_owner,
 output wire [703:0] authority_PC,
 output wire [4095:0] authority_sequence,
 output wire [16383:0] authority_shape_sha,
 output wire [4607:0] authority_source_slots,
 output wire [11775:0] authority_source_owners,
 output wire [1151:0] authority_result_slots,
 output wire [2943:0] authority_result_owner,
 output wire [1535:0] authority_source_banks,
 output wire [383:0] authority_result_bank,
 output wire [255:0] source_owner_held,
 output wire [63:0] result_owner_held,
 output wire [63:0] output_visible,
 output wire [63:0] fault,
 output wire [63:0] context_live,
 input wire [63:0] rfroute_bank_port_owned,
 input wire [63:0] rfroute_actor_busy,
 input wire [63:0] rfroute_actor_fault,
 input wire [63:0] rfroute_actor_rd_valid,
 input wire [63:0] rfroute_actor_wr_valid,
 input wire [575:0] rfroute_actor_a,
 input wire [575:0] rfroute_actor_b,
 input wire [575:0] rfroute_actor_dst,
 input wire [262143:0] rfroute_actor_wdata,
 input wire [2943:0] rfroute_actor_wowner,
 input wire [63:0] rfroute_actor_rsp_ready,
 input wire [63:0] rfroute_actor_ack_ready,
 output wire [63:0] rfroute_actor_rd_ready,
 output wire [63:0] rfroute_actor_wr_ready,
 output wire [63:0] rfroute_actor_rsp_valid,
 output wire [63:0] rfroute_actor_ack_valid,
 output wire [262143:0] rfroute_actor_rsp_a,
 output wire [262143:0] rfroute_actor_rsp_b,
 output wire [575:0] rfroute_actor_ack_slot,
 output wire [2943:0] rfroute_actor_ack_owner,
 output wire [63:0] rfroute_actor_routes_drained,
 output wire [63:0] rfroute_bank_routes_drained,
 output wire [63:0] rfroute_route_fault,
 output wire [63:0] rfroute_bank_pending_read,
 output wire [63:0] rfroute_bank_pending_write,
 output wire [575:0] rfroute_bank_saved_read_slot,
 output wire [2943:0] rfroute_bank_saved_read_owner,
 output wire [63:0] rfroute_bank_rd_valid,
 output wire [63:0] rfroute_bank_wr_valid,
 output wire [63:0] rfroute_bank_rsp_ready,
 output wire [63:0] rfroute_bank_ack_ready,
 output wire [575:0] rfroute_bank_a,
 output wire [575:0] rfroute_bank_b,
 output wire [575:0] rfroute_bank_dst,
 output wire [262143:0] rfroute_bank_wdata,
 output wire [2943:0] rfroute_bank_wowner,
 output wire [15295:0] rfroute_bank_root_tuple,
 output wire [3519:0] rfroute_bank_root_owner,
 input wire [63:0] rfroute_bank_rd_ready,
 input wire [63:0] rfroute_bank_wr_ready,
 input wire [63:0] rfroute_bank_rsp_valid,
 input wire [63:0] rfroute_bank_ack_valid,
 input wire [262143:0] rfroute_bank_rsp_a,
 input wire [262143:0] rfroute_bank_rsp_b,
 input wire [575:0] rfroute_bank_ack_slot,
 input wire [2943:0] rfroute_bank_ack_owner,
 input wire [63:0] query_empty,
 input wire [127:0] controller_read_operand,
 input wire [63:0] controller_read_page,
 input wire [63:0] controller_write_page,
 input wire [63:0] controller_private_RF_quiescent
);
wire [63:0] actor_Q_pending[0:63];
for(genvar i=0;i<64;i=i+1)begin:actual_collectors
 for(genvar b=0;b<64;b=b+1)begin:actual_Q_debt
  assign actor_Q_pending[i][b]=query_valid[b] && query_tuple[b*239+:239]==issuer_held_tuple[i*239+:239];
 end
ot_gpu_qwen_native_aperture_collector #(.ENABLE(ENABLE),.ACTOR_INDEX(i)) u_collector(
 .clk(clk),
 .por_n(por_n[i]),
 .warm_reset(warm_reset[i]),
 .issuer_held_valid(issuer_held_valid[i]),
 .issuer_held_fault(issuer_held_fault[i]),
 .issuer_held_tuple(issuer_held_tuple[i*239+:239]),
 .issuer_held_owner(issuer_held_owner[i*55+:55]),
 .profile_valid(profile_valid[i]),
 .profile_tuple(profile_tuple[i*239+:239]),
 .profile_PC(profile_PC[i*11+:11]),
 .profile_sequence(profile_sequence[i*64+:64]),
 .profile_shape(profile_shape[i*256+:256]),
 .profile_present(profile_present[i*4+:4]),
 .profile_double(profile_double[i*4+:4]),
 .profile_result_double(profile_result_double[i]),
 .cursor_load_valid(cursor_load_valid[i]),
 .cursor_load_ready(cursor_load_ready[i]),
 .cursor_load_tuple(cursor_load_tuple[i*239+:239]),
 .cursor_load_owner(cursor_load_owner[i*55+:55]),
 .cursor_load_sequence(cursor_load_sequence[i*64+:64]),
 .cursor_load_descriptor(cursor_load_descriptor[i*8+:8]),
 .cursor_load_operands(cursor_load_operands[i*3+:3]),
 .cursor_load_types(cursor_load_types[i*8+:8]),
 .cursor_load_signed_i8(cursor_load_signed_i8[i*4+:4]),
 .cursor_load_counts(cursor_load_counts[i*32+:32]),
 .cursor_load_vector_mask(cursor_load_vector_mask[i*4+:4]),
 .cursor_load_template(cursor_load_template[i*4+:4]),
 .cursor_load_step(cursor_load_step[i*6+:6]),
 .cursor_load_substep(cursor_load_substep[i*2+:2]),
 .cursor_load_scalars(cursor_load_scalars[i*4+:4]),
 .cursor_load_tail(cursor_load_tail[i*8+:8]),
 .source_cursor_valid(source_cursor_valid[i]),
 .source_cursor_advance_valid(source_cursor_advance_valid[i]),
 .source_cursor_advance_ready(source_cursor_advance_ready[i]),
 .source_descriptor(source_descriptor[i*8+:8]),
 .source_types(source_types[i*8+:8]),
 .source_tail(source_tail[i*8+:8]),
 .source_operands(source_operands[i*3+:3]),
 .source_signed_i8_mask(source_signed_i8_mask[i*4+:4]),
 .source_vector_mask(source_vector_mask[i*4+:4]),
 .source_template(source_template[i*4+:4]),
 .source_scalars(source_scalars[i*4+:4]),
 .source_counts(source_counts[i*32+:32]),
 .source_ordered_step(source_ordered_step[i*6+:6]),
 .source_substep(source_substep[i*2+:2]),
 .frame_accept(frame_accept[i]),
 .frame_tuple(frame_tuple[i*239+:239]),
 .frame_owner(frame_owner[i*55+:55]),
 .terminal_accept(terminal_accept[i]),
 .terminal_tuple(terminal_tuple[i*239+:239]),
 .terminal_owner(terminal_owner[i*55+:55]),
 .terminal_sequence(terminal_sequence[i*64+:64]),
 .begin_valid(begin_valid[i]),
 .begin_ready(begin_ready[i]),
 .capture_valid(capture_valid[i]),
 .capture_ready(capture_ready[i]),
 .capture_aperture(capture_aperture[i*3+:3]),
 .capture_bank(capture_bank[i*6+:6]),
 .capture_slots(capture_slots[i*18+:18]),
 .capture_version(capture_version[i*11+:11]),
 .capture_workspace(capture_workspace[i]),
 .query_valid(query_valid),
 .query_retained(query_retained),
 .query_write(query_write),
 .query_workspace(query_workspace),
 .bank_fault(bank_fault),
 .query_tuple(query_tuple),
 .query_slot(query_slot),
 .query_owner(query_owner),
 .query_version(query_version),
 .query_first(query_first),
 .query_end(query_end),
 .lease_tuple(lease_tuple[i*1195+:1195]),
 .lease_version(lease_version[i*55+:55]),
 .lease_slots(lease_slots[i*90+:90]),
 .lease_owner(lease_owner[i*230+:230]),
 .lease_bank(lease_bank[i*30+:30]),
 .lease_workspace(lease_workspace[i*5+:5]),
 .lease_write(lease_write[i*5+:5]),
 .lease_double(lease_double[i*5+:5]),
 .bank_scope_valid(bank_scope_valid),
 .bank_scope_writable(bank_scope_writable),
 .bank_scope_workspace(bank_scope_workspace),
 .bank_scope_tuple(bank_scope_tuple),
 .bank_scope_owner(bank_scope_owner),
 .ack_accept(ack_accept),
 .ack_slot(ack_slot),
 .ack_owner(ack_owner),
 .visibility_valid(visibility_valid[i]),
 .visibility_tuple(visibility_tuple[i*239+:239]),
 .visibility_owner(visibility_owner[i*55+:55]),
 .visibility_sequence(visibility_sequence[i*64+:64]),
 .reverse_accept(reverse_accept[i]),
 .reverse_tuple(reverse_tuple[i*239+:239]),
 .reverse_owner(reverse_owner[i*55+:55]),
 .reverse_sequence(reverse_sequence[i*64+:64]),
 .read_route_valid(read_route_valid[i]),
 .write_route_valid(write_route_valid[i]),
 .read_bank(read_bank[i*6+:6]),
 .write_bank(write_bank[i*6+:6]),
 .read_slot(read_slot[i*9+:9]),
 .write_slot(write_slot[i*9+:9]),
 .read_owner(read_owner[i*46+:46]),
 .write_owner(write_owner[i*46+:46]),
 .authority_valid(authority_valid[i]),
 .authority_tuple(authority_tuple[i*239+:239]),
 .authority_owner(authority_owner[i*55+:55]),
 .authority_PC(authority_PC[i*11+:11]),
 .authority_sequence(authority_sequence[i*64+:64]),
 .authority_shape_sha(authority_shape_sha[i*256+:256]),
 .authority_source_slots(authority_source_slots[i*72+:72]),
 .authority_source_owners(authority_source_owners[i*184+:184]),
 .authority_result_slots(authority_result_slots[i*18+:18]),
 .authority_result_owner(authority_result_owner[i*46+:46]),
 .authority_source_banks(authority_source_banks[i*24+:24]),
 .authority_result_bank(authority_result_bank[i*6+:6]),
 .source_owner_held(source_owner_held[i*4+:4]),
 .result_owner_held(result_owner_held[i]),
 .output_visible(output_visible[i]),
 .fault(fault[i]),
 .context_live(context_live[i]),
 .read_operand(controller_read_operand[i*2+:2]),
 .read_page(controller_read_page[i]),
 .write_page(controller_write_page[i]),
 .controller_idle(!rfroute_actor_busy[i] && !rfroute_actor_fault[i] && controller_private_RF_quiescent[i]),
 .selected_routes_drained(rfroute_actor_routes_drained[i] && (&query_empty))
);
end
ot_gpu_qwen_native_rf_route_r2 #(.ENABLE(ENABLE)) u_actual_RF_route(
 .clk(clk),
 .por_n(por_n),
 .warm_reset(warm_reset),
 .bank_port_owned(rfroute_bank_port_owned),
 .actor_busy(rfroute_actor_busy),
 .actor_fault(rfroute_actor_fault),
 .authority_valid(authority_valid),
 .authority_tuple(authority_tuple),
 .authority_owner(authority_owner),
 .read_route_valid(read_route_valid),
 .write_route_valid(write_route_valid),
 .read_bank(read_bank),
 .write_bank(write_bank),
 .read_slot(read_slot),
 .write_slot(write_slot),
 .read_owner(read_owner),
 .write_owner(write_owner),
 .actor_rd_valid(rfroute_actor_rd_valid),
 .actor_wr_valid(rfroute_actor_wr_valid),
 .actor_a(rfroute_actor_a),
 .actor_b(rfroute_actor_b),
 .actor_dst(rfroute_actor_dst),
 .actor_wdata(rfroute_actor_wdata),
 .actor_wowner(rfroute_actor_wowner),
 .actor_rsp_ready(rfroute_actor_rsp_ready),
 .actor_ack_ready(rfroute_actor_ack_ready),
 .actor_rd_ready(rfroute_actor_rd_ready),
 .actor_wr_ready(rfroute_actor_wr_ready),
 .actor_rsp_valid(rfroute_actor_rsp_valid),
 .actor_ack_valid(rfroute_actor_ack_valid),
 .actor_rsp_a(rfroute_actor_rsp_a),
 .actor_rsp_b(rfroute_actor_rsp_b),
 .actor_ack_slot(rfroute_actor_ack_slot),
 .actor_ack_owner(rfroute_actor_ack_owner),
 .actor_routes_drained(rfroute_actor_routes_drained),
 .bank_routes_drained(rfroute_bank_routes_drained),
 .route_fault(rfroute_route_fault),
 .bank_pending_read(rfroute_bank_pending_read),
 .bank_pending_write(rfroute_bank_pending_write),
 .bank_saved_read_slot(rfroute_bank_saved_read_slot),
 .bank_saved_read_owner(rfroute_bank_saved_read_owner),
 .bank_rd_valid(rfroute_bank_rd_valid),
 .bank_wr_valid(rfroute_bank_wr_valid),
 .bank_rsp_ready(rfroute_bank_rsp_ready),
 .bank_ack_ready(rfroute_bank_ack_ready),
 .bank_a(rfroute_bank_a),
 .bank_b(rfroute_bank_b),
 .bank_dst(rfroute_bank_dst),
 .bank_wdata(rfroute_bank_wdata),
 .bank_wowner(rfroute_bank_wowner),
 .bank_root_tuple(rfroute_bank_root_tuple),
 .bank_root_owner(rfroute_bank_root_owner),
 .bank_rd_ready(rfroute_bank_rd_ready),
 .bank_wr_ready(rfroute_bank_wr_ready),
 .bank_rsp_valid(rfroute_bank_rsp_valid),
 .bank_ack_valid(rfroute_bank_ack_valid),
 .bank_rsp_a(rfroute_bank_rsp_a),
 .bank_rsp_b(rfroute_bank_rsp_b),
 .bank_ack_slot(rfroute_bank_ack_slot),
 .bank_ack_owner(rfroute_bank_ack_owner)
);
endmodule
