export DESIGN_NAME = ot_dsrom_wfc_protected_stage
export DESIGN_NICKNAME = zeno_wfc_protected_r4_$(FLOW_VARIANT)
export PLATFORM = asap7
export VERILOG_FILES = /src/rtl/gpu/w6/ot_gpu_w6_secded_pkg.sv /src/rtl/dsrom_sys/protected_vm/ot_dsrom_vm_pkg.sv /src/rtl/dsrom_sys/protected_vm/ot_dsrom_vm_codec.sv /src/rtl/dsrom_sys/protected_vm/ot_dsrom_vm_ratio_fifo.sv /src/rtl/dsrom_sys/protected_vm/ot_dsrom_vm_backend.sv /src/rtl/dsrom_sys/protected_vm/ot_dsrom_protected_vm.sv /src/rtl/rom/wavefront/context/ot_dsrom_wfc_vm_caller_adapter.sv /src/rtl/rom/wavefront/context/ot_dsrom_wfc_protected_stage.sv /src/rtl/rom/wavefront/context/protected_20261006/ot_dsrom_wfc_enclosing_vm_stage.sv /src/rtl/rom/wavefront/context/protected_20261006/ot_dsrom_wfc_parent_enclosed_vm.sv /src/rtl/rom/wavefront/context/protected_20261006/ot_rom_pkg_ctrl_wfc_enclosed_vm.sv /src/rtl/rom/wavefront/context/ot_dsrom_wfc_vm_port.sv /src/rtl/rom/wavefront/context/ot_dsrom_wfc_router_cut.sv /src/rtl/rom/ot_rom_fabric_router.sv /src/rtl/dsrom_sys/c8/ot_dsrom_c8_stage_context.sv /src/rtl/dsrom_sys/wfc_producers/ot_dsrom_wfc_cfg_prompt.sv /src/rtl/dsrom_sys/wfc_producers/ot_dsrom_wfc_whole_stage.sv /src/rtl/dft/ot_rom_secded_dec.sv /src/physical/asap7_memory_macros_v2/ot_sram_1r1w_512x128_m4_r2c2/ot_sram_1r1w_512x128_m4_r2c2_bb.v /src/physical/asap7_memory_macros_v2/ot_rom_4096x72_m8/ot_rom_4096x72_m8_bb.v
export VERILOG_DEFINES = -DSYNTHESIS
export VERILOG_TOP_PARAMS = ENABLE 1 STRUCTURAL 1
export SYNTH_HDL_FRONTEND = slang
export SYNTH_HIERARCHICAL = 0
export SYNTH_REPEATABLE_BUILD = 1
export ADDER_MAP_FILE =
export SDC_FILE = /src/physical/dsrom_wfc_protected_context/constraint.sdc
export DIE_AREA = 0 0 1015.2 3242.16
export CORE_AREA = 17.28 17.28 997.92 3224.88
export PLACE_DENSITY ?= 0.55
export NUM_CORES = 16
export MIN_ROUTING_LAYER = M2
export MAX_ROUTING_LAYER = M9
export MACRO_PLACEMENT_TCL = /src/physical/dsrom_wfc_protected_context/macro_placement.tcl
export MACRO_PLACE_HALO = 2 2
export CORNER = WC
export CORNERS = WC BC
export ADDITIONAL_LEFS = /src/physical/asap7_memory_macros_v2/ot_sram_1r1w_512x128_m4_r2c2/ot_sram_1r1w_512x128_m4_r2c2.lef /src/physical/asap7_memory_macros_v2/ot_rom_4096x72_m8/ot_rom_4096x72_m8.lef
export ADDITIONAL_LIBS = /src/physical/asap7_memory_macros_v2/ot_sram_1r1w_512x128_m4_r2c2/ot_sram_1r1w_512x128_m4_r2c2_ss.lib /src/physical/asap7_memory_macros_v2/ot_rom_4096x72_m8/ot_rom_4096x72_m8_ss.lib
export WC_LIB_FILES = $(WC_NLDM_LIB_FILES) /src/physical/asap7_memory_macros_v2/ot_sram_1r1w_512x128_m4_r2c2/ot_sram_1r1w_512x128_m4_r2c2_ss.lib /src/physical/asap7_memory_macros_v2/ot_rom_4096x72_m8/ot_rom_4096x72_m8_ss.lib
export BC_LIB_FILES = $(BC_NLDM_LIB_FILES) /src/physical/asap7_memory_macros_v2/ot_sram_1r1w_512x128_m4_r2c2/ot_sram_1r1w_512x128_m4_r2c2_ff.lib /src/physical/asap7_memory_macros_v2/ot_rom_4096x72_m8/ot_rom_4096x72_m8_ff.lib
export HOLD_SLACK_MARGIN = 0
export SETUP_SLACK_MARGIN = 0
export REPORT_CLOCK_SKEW = 1
export SKIP_REPORT_METRICS = 0
export LEC_CHECK = 0
