`timescale 1ps/1fs
// Physical loaded R4 body: explicit external fast_clk/slow_clk input boundaries.
// This top contains NO failed divider and supplies NO clock-source qualification.
// Cold-POR-only sticky clock fault vetoes enrollment/ready and exposes quarantine;
// pending provider state and consumer/fence ports are never reset or tied off.
module ot_dsrom_wfc_protected_inputclock_stage #(parameter ENABLE=0, STRUCTURAL=0, DISTRIBUTED_CMD=0)(
 input wire fast_clk,slow_clk,cold_n,slow_rst_n,
 input wire fast_rst_n,
 input wire  cold_fenced,
 input wire  cmd_v,
 input wire [1:0] cmd_op,
 input wire [9:0] cmd_user,
 input wire [20:0] cmd_pos,
 input wire [20:0] cmd_token,
 input wire [3:0] cmd_block,
 input wire [15:0] cmd_epoch,
 input wire [13:0] cmd_entry,
 output wire  cmd_ready,
 output wire  producer_active,
 output wire  producer_initializing,
 output wire  cfg_fault,
 input wire [3:0] command_v,
 output wire [3:0] command_ready,
 input wire [187:0] command_identity,
 input wire [83:0] command_token,
 input wire [27:0] command_home,
 input wire [55:0] command_entry,
 input wire [55:0] command_pc,
 input wire [15:0] command_unit,
 input wire [3:0] retire_v,
 input wire [187:0] retire_identity,
 input wire [27:0] retire_home,
 input wire [55:0] retire_entry,
 input wire [23:0] retire_visibility,
 input wire [3:0] retire_quiet,
 input wire [3:0] retire_capture_drained,
 input wire [3:0] retire_fault,
 input wire [3:0] fence_v,
 input wire [187:0] fence_identity,
 input wire [19:0] fence_visibility,
 input wire  result_v,
 input wire [46:0] result_identity,
 input wire [20:0] result_token,
 input wire [31:0] result_value,
 output wire  token_result_valid,
 output wire  stage_handoff,
 output wire  producer_pending,
 output wire  whole_fault,
 input wire  in_valid,
 input wire  in_last,
 input wire  out_ready,
 input wire [511:0] in_data,
 output wire  in_ready,
 output wire  out_valid,
 output wire  out_last,
 output wire [511:0] out_data,
 input wire  bl_rx_valid,
 input wire  bl_rx_last,
 input wire  bl_tx_ready,
 input wire [511:0] bl_rx_data,
 output wire  bl_rx_ready,
 output wire  bl_tx_valid,
 output wire  bl_tx_last,
 output wire [511:0] bl_tx_data,
 input wire  rcfg_we,
 input wire [7:0] rcfg_dest,
 input wire [2:0] rcfg_mask,
 input wire  context_restored,
 input wire  native_idle,
 input wire  native_fragment_done,
 input wire  c8_write_quiet,
 input wire  c8_write_quarantine,
 input wire  c8_write_fault,
 input wire  coll_busy,
 input wire [3:0] xb_we4,
 input wire [59:0] xb_waddr4,
 input wire [2047:0] xb_wdata4,
 input wire  xb_re,
 input wire [14:0] xb_raddr,
 output wire [511:0] xb_rq,
 input wire xb_v,
 input wire [46:0]xb_owner,xb_consume_owner,
 input wire xb_consume_v,
 output wire xb_ready,xb_reply_v,xb_port_retired,
 output wire [46:0]xb_reply_owner,
 output wire [3:0]xb_row_visible,
 output wire vm_pending,vm_initializing,vm_fault,vm_quarantined,vm_port_retired,
 output wire [3:0]vm_phase,
 output wire  context_v,
 output wire [46:0] context_identity,
 output wire [20:0] context_token,
 output wire [13:0] context_entry,
 output wire  native_start,
 output wire [20:0] native_token,
 output wire [20:0] native_pos,
 output wire [13:0] native_entry,
 output wire [9:0] native_user,
 output wire [46:0] native_identity,
 output wire [20:0] captured_token,
 output wire [20:0] captured_pos,
 output wire [13:0] captured_pc,
 output wire  c8_retire_v,
 output wire [46:0] c8_retire_identity,
 output wire  tok_valid,
 output wire [9:0] tok_user,
 output wire [9:0] users_done,
 output wire [20:0] tok_pos,
 output wire [20:0] tok_id,
 output wire  busy,
 output wire  wfc_fault,
 input wire clock_source_fault
);
 wire  raw_cmd_ready;
 assign cmd_ready = raw_cmd_ready & !clock_source_fault;
 wire  raw_cfg_fault;
 assign cfg_fault = raw_cfg_fault | clock_source_fault;
 wire [3:0] raw_command_ready;
 assign command_ready = raw_command_ready & {4{!clock_source_fault}};
 wire  raw_whole_fault;
 assign whole_fault = raw_whole_fault | clock_source_fault;
 wire  raw_in_ready;
 assign in_ready = raw_in_ready & !clock_source_fault;
 wire  raw_bl_rx_ready;
 assign bl_rx_ready = raw_bl_rx_ready & !clock_source_fault;
 wire  raw_xb_ready;
 assign xb_ready = raw_xb_ready & !clock_source_fault;
 wire  raw_vm_fault;
 assign vm_fault = raw_vm_fault | clock_source_fault;
 wire  raw_vm_quarantined;
 assign vm_quarantined = raw_vm_quarantined | clock_source_fault;
 wire  raw_wfc_fault;
 assign wfc_fault = raw_wfc_fault | clock_source_fault;
 ot_dsrom_wfc_protected_stage #(.ENABLE(ENABLE),.STRUCTURAL(STRUCTURAL),.DISTRIBUTED_CMD(DISTRIBUTED_CMD)) u_r4(
 .fast_clk(fast_clk),
 .slow_clk(slow_clk),
 .cold_n(cold_n),
 .slow_rst_n(slow_rst_n),
 .fast_rst_n(fast_rst_n),
 .cold_fenced(cold_fenced),
 .cmd_v(cmd_v && !clock_source_fault),
 .cmd_op(cmd_op),
 .cmd_user(cmd_user),
 .cmd_pos(cmd_pos),
 .cmd_token(cmd_token),
 .cmd_block(cmd_block),
 .cmd_epoch(cmd_epoch),
 .cmd_entry(cmd_entry),
 .cmd_ready(raw_cmd_ready),
 .producer_active(producer_active),
 .producer_initializing(producer_initializing),
 .cfg_fault(raw_cfg_fault),
 .command_v(command_v & {4{!clock_source_fault}}),
 .command_ready(raw_command_ready),
 .command_identity(command_identity),
 .command_token(command_token),
 .command_home(command_home),
 .command_entry(command_entry),
 .command_pc(command_pc),
 .command_unit(command_unit),
 .retire_v(retire_v),
 .retire_identity(retire_identity),
 .retire_home(retire_home),
 .retire_entry(retire_entry),
 .retire_visibility(retire_visibility),
 .retire_quiet(retire_quiet),
 .retire_capture_drained(retire_capture_drained),
 .retire_fault(retire_fault),
 .fence_v(fence_v),
 .fence_identity(fence_identity),
 .fence_visibility(fence_visibility),
 .result_v(result_v),
 .result_identity(result_identity),
 .result_token(result_token),
 .result_value(result_value),
 .token_result_valid(token_result_valid),
 .stage_handoff(stage_handoff),
 .producer_pending(producer_pending),
 .whole_fault(raw_whole_fault),
 .in_valid(in_valid),
 .in_last(in_last),
 .out_ready(out_ready),
 .in_data(in_data),
 .in_ready(raw_in_ready),
 .out_valid(out_valid),
 .out_last(out_last),
 .out_data(out_data),
 .bl_rx_valid(bl_rx_valid),
 .bl_rx_last(bl_rx_last),
 .bl_tx_ready(bl_tx_ready),
 .bl_rx_data(bl_rx_data),
 .bl_rx_ready(raw_bl_rx_ready),
 .bl_tx_valid(bl_tx_valid),
 .bl_tx_last(bl_tx_last),
 .bl_tx_data(bl_tx_data),
 .rcfg_we(rcfg_we),
 .rcfg_dest(rcfg_dest),
 .rcfg_mask(rcfg_mask),
 .context_restored(context_restored),
 .native_idle(native_idle),
 .native_fragment_done(native_fragment_done),
 .c8_write_quiet(c8_write_quiet),
 .c8_write_quarantine(c8_write_quarantine || clock_source_fault),
 .c8_write_fault(c8_write_fault),
 .coll_busy(coll_busy),
 .xb_we4(xb_we4),
 .xb_waddr4(xb_waddr4),
 .xb_wdata4(xb_wdata4),
 .xb_re(xb_re),
 .xb_raddr(xb_raddr),
 .xb_rq(xb_rq),
 .xb_v(xb_v && !clock_source_fault),
 .xb_owner(xb_owner),
 .xb_consume_owner(xb_consume_owner),
 .xb_consume_v(xb_consume_v),
 .xb_ready(raw_xb_ready),
 .xb_reply_v(xb_reply_v),
 .xb_port_retired(xb_port_retired),
 .xb_reply_owner(xb_reply_owner),
 .xb_row_visible(xb_row_visible),
 .vm_pending(vm_pending),
 .vm_initializing(vm_initializing),
 .vm_fault(raw_vm_fault),
 .vm_quarantined(raw_vm_quarantined),
 .vm_port_retired(vm_port_retired),
 .vm_phase(vm_phase),
 .context_v(context_v),
 .context_identity(context_identity),
 .context_token(context_token),
 .context_entry(context_entry),
 .native_start(native_start),
 .native_token(native_token),
 .native_pos(native_pos),
 .native_entry(native_entry),
 .native_user(native_user),
 .native_identity(native_identity),
 .captured_token(captured_token),
 .captured_pos(captured_pos),
 .captured_pc(captured_pc),
 .c8_retire_v(c8_retire_v),
 .c8_retire_identity(c8_retire_identity),
 .tok_valid(tok_valid),
 .tok_user(tok_user),
 .users_done(users_done),
 .tok_pos(tok_pos),
 .tok_id(tok_id),
 .busy(busy),
 .wfc_fault(raw_wfc_fault)
 );
endmodule
