`timescale 1ns/1ps
// lockstep bench of hfd_hgi_su (tools/hbm_die_wrap.py --tb): one seed 20261006
module tb_hfd_hgi_su;
    reg [0:0] ck;
    reg [0:0] f_am_rdy;
    reg [938:0] f_hgi_cmdproc_hc;
    reg [1173:0] f_hgi_cmdproc_sfu;
    reg [2197:0] f_hgi_cmdproc_su;
    reg [256:0] f_hgi_hcmr;
    reg [273:0] f_hgi_vmr_hc;
    reg [273:0] f_hgi_vmr_sfu;
    reg [273:0] f_hgi_vmr_su;
    reg [0:0] rst;
    wire [255:0] t_am_in_bias;
    wire [0:0] t_am_in_bias_en;
    wire [0:0] t_am_in_last;
    wire [7:0] t_am_in_mask;
    wire [0:0] t_am_in_v;
    wire [255:0] t_am_in_vals;
    wire [2:0] t_hgi_cmdproc_hc;
    wire [2:0] t_hgi_cmdproc_sfu;
    wire [2:0] t_hgi_cmdproc_su;
    wire [37:0] t_hgi_hcmq;
    wire [337:0] t_hgi_vmq_hc;
    wire [337:0] t_hgi_vmq_sfu;
    wire [337:0] t_hgi_vmq_su;
    hfd_hgi_su dut(.ck(ck), .f_am_rdy(f_am_rdy), .f_hgi_cmdproc_hc(f_hgi_cmdproc_hc), .f_hgi_cmdproc_sfu(f_hgi_cmdproc_sfu), .f_hgi_cmdproc_su(f_hgi_cmdproc_su), .f_hgi_hcmr(f_hgi_hcmr), .f_hgi_vmr_hc(f_hgi_vmr_hc), .f_hgi_vmr_sfu(f_hgi_vmr_sfu), .f_hgi_vmr_su(f_hgi_vmr_su), .rst(rst), .t_am_in_bias(t_am_in_bias), .t_am_in_bias_en(t_am_in_bias_en), .t_am_in_last(t_am_in_last), .t_am_in_mask(t_am_in_mask), .t_am_in_v(t_am_in_v), .t_am_in_vals(t_am_in_vals), .t_hgi_cmdproc_hc(t_hgi_cmdproc_hc), .t_hgi_cmdproc_sfu(t_hgi_cmdproc_sfu), .t_hgi_cmdproc_su(t_hgi_cmdproc_su), .t_hgi_hcmq(t_hgi_hcmq), .t_hgi_vmq_hc(t_hgi_vmq_hc), .t_hgi_vmq_sfu(t_hgi_vmq_sfu), .t_hgi_vmq_su(t_hgi_vmq_su));
    reg clk = 0; always #0.4165 clk = ~clk;
    always @* ck[0] = clk;
    reg [0:0] d0_ck; always @(posedge clk) d0_ck <= ck;
    reg [0:0] d1_ck; always @(posedge clk) d1_ck <= d0_ck;
    reg [0:0] d_ck; always @(posedge clk) d_ck <= d1_ck;
    reg [0:0] d0_f_am_rdy; always @(posedge clk) d0_f_am_rdy <= f_am_rdy;
    reg [0:0] d1_f_am_rdy; always @(posedge clk) d1_f_am_rdy <= d0_f_am_rdy;
    reg [0:0] d_f_am_rdy; always @(posedge clk) d_f_am_rdy <= d1_f_am_rdy;
    reg [938:0] d0_f_hgi_cmdproc_hc; always @(posedge clk) d0_f_hgi_cmdproc_hc <= f_hgi_cmdproc_hc;
    reg [938:0] d1_f_hgi_cmdproc_hc; always @(posedge clk) d1_f_hgi_cmdproc_hc <= d0_f_hgi_cmdproc_hc;
    reg [938:0] d_f_hgi_cmdproc_hc; always @(posedge clk) d_f_hgi_cmdproc_hc <= d1_f_hgi_cmdproc_hc;
    reg [1173:0] d0_f_hgi_cmdproc_sfu; always @(posedge clk) d0_f_hgi_cmdproc_sfu <= f_hgi_cmdproc_sfu;
    reg [1173:0] d1_f_hgi_cmdproc_sfu; always @(posedge clk) d1_f_hgi_cmdproc_sfu <= d0_f_hgi_cmdproc_sfu;
    reg [1173:0] d_f_hgi_cmdproc_sfu; always @(posedge clk) d_f_hgi_cmdproc_sfu <= d1_f_hgi_cmdproc_sfu;
    reg [2197:0] d0_f_hgi_cmdproc_su; always @(posedge clk) d0_f_hgi_cmdproc_su <= f_hgi_cmdproc_su;
    reg [2197:0] d1_f_hgi_cmdproc_su; always @(posedge clk) d1_f_hgi_cmdproc_su <= d0_f_hgi_cmdproc_su;
    reg [2197:0] d_f_hgi_cmdproc_su; always @(posedge clk) d_f_hgi_cmdproc_su <= d1_f_hgi_cmdproc_su;
    reg [256:0] d0_f_hgi_hcmr; always @(posedge clk) d0_f_hgi_hcmr <= f_hgi_hcmr;
    reg [256:0] d1_f_hgi_hcmr; always @(posedge clk) d1_f_hgi_hcmr <= d0_f_hgi_hcmr;
    reg [256:0] d_f_hgi_hcmr; always @(posedge clk) d_f_hgi_hcmr <= d1_f_hgi_hcmr;
    reg [273:0] d0_f_hgi_vmr_hc; always @(posedge clk) d0_f_hgi_vmr_hc <= f_hgi_vmr_hc;
    reg [273:0] d1_f_hgi_vmr_hc; always @(posedge clk) d1_f_hgi_vmr_hc <= d0_f_hgi_vmr_hc;
    reg [273:0] d_f_hgi_vmr_hc; always @(posedge clk) d_f_hgi_vmr_hc <= d1_f_hgi_vmr_hc;
    reg [273:0] d0_f_hgi_vmr_sfu; always @(posedge clk) d0_f_hgi_vmr_sfu <= f_hgi_vmr_sfu;
    reg [273:0] d1_f_hgi_vmr_sfu; always @(posedge clk) d1_f_hgi_vmr_sfu <= d0_f_hgi_vmr_sfu;
    reg [273:0] d_f_hgi_vmr_sfu; always @(posedge clk) d_f_hgi_vmr_sfu <= d1_f_hgi_vmr_sfu;
    reg [273:0] d0_f_hgi_vmr_su; always @(posedge clk) d0_f_hgi_vmr_su <= f_hgi_vmr_su;
    reg [273:0] d1_f_hgi_vmr_su; always @(posedge clk) d1_f_hgi_vmr_su <= d0_f_hgi_vmr_su;
    reg [273:0] d_f_hgi_vmr_su; always @(posedge clk) d_f_hgi_vmr_su <= d1_f_hgi_vmr_su;
    reg [0:0] d0_rst; always @(posedge clk) d0_rst <= rst;
    reg [0:0] d1_rst; always @(posedge clk) d1_rst <= d0_rst;
    reg [0:0] d_rst; always @(posedge clk) d_rst <= d1_rst;
    wire [0:0] r_su_clk;
    assign r_su_clk = dut.w_su_clk;
    wire [0:0] r_su_rst_n;
    assign r_su_rst_n = dut.w_su_rst_n;
    wire [0:0] r_su_rec_v;
    assign r_su_rec_v = {d_f_hgi_cmdproc_su[0:0]};
    wire [0:0] r_su_rec_rdy;
    reg [0:0] q1_su_rec_rdy; always @(posedge clk) q1_su_rec_rdy <= r_su_rec_rdy;
    reg [0:0] q2_su_rec_rdy; always @(posedge clk) q2_su_rec_rdy <= q1_su_rec_rdy;
    reg [0:0] q3_su_rec_rdy; always @(posedge clk) q3_su_rec_rdy <= q2_su_rec_rdy;
    wire [127:0] r_su_rec_hdr;
    assign r_su_rec_hdr = {d_f_hgi_cmdproc_su[128:1]};
    wire [255:0] r_su_rec_sut;
    assign r_su_rec_sut = {d_f_hgi_cmdproc_su[384:129]};
    wire [255:0] r_su_rec_a;
    assign r_su_rec_a = {d_f_hgi_cmdproc_su[640:385]};
    wire [255:0] r_su_rec_b;
    assign r_su_rec_b = {d_f_hgi_cmdproc_su[896:641]};
    wire [255:0] r_su_rec_c;
    assign r_su_rec_c = {d_f_hgi_cmdproc_su[1152:897]};
    wire [255:0] r_su_rec_d;
    assign r_su_rec_d = {d_f_hgi_cmdproc_su[1408:1153]};
    wire [255:0] r_su_rec_o;
    assign r_su_rec_o = {d_f_hgi_cmdproc_su[1664:1409]};
    wire [255:0] r_su_rec_r;
    assign r_su_rec_r = {d_f_hgi_cmdproc_su[1920:1665]};
    wire [255:0] r_su_rec_i;
    assign r_su_rec_i = {d_f_hgi_cmdproc_su[2176:1921]};
    wire [20:0] r_su_rec_n_a;
    assign r_su_rec_n_a = {d_f_hgi_cmdproc_su[2197:2177]};
    wire [0:0] r_su_rec_done;
    reg [0:0] q1_su_rec_done; always @(posedge clk) q1_su_rec_done <= r_su_rec_done;
    reg [0:0] q2_su_rec_done; always @(posedge clk) q2_su_rec_done <= q1_su_rec_done;
    reg [0:0] q3_su_rec_done; always @(posedge clk) q3_su_rec_done <= q2_su_rec_done;
    wire [0:0] r_su_rec_fault;
    reg [0:0] q1_su_rec_fault; always @(posedge clk) q1_su_rec_fault <= r_su_rec_fault;
    reg [0:0] q2_su_rec_fault; always @(posedge clk) q2_su_rec_fault <= q1_su_rec_fault;
    reg [0:0] q3_su_rec_fault; always @(posedge clk) q3_su_rec_fault <= q2_su_rec_fault;
    wire [0:0] r_su_halted;
    reg [0:0] q1_su_halted; always @(posedge clk) q1_su_halted <= r_su_halted;
    reg [0:0] q2_su_halted; always @(posedge clk) q2_su_halted <= q1_su_halted;
    reg [0:0] q3_su_halted; always @(posedge clk) q3_su_halted <= q2_su_halted;
    wire [337:0] r_su_vmq;
    reg [337:0] q1_su_vmq; always @(posedge clk) q1_su_vmq <= r_su_vmq;
    reg [337:0] q2_su_vmq; always @(posedge clk) q2_su_vmq <= q1_su_vmq;
    reg [337:0] q3_su_vmq; always @(posedge clk) q3_su_vmq <= q2_su_vmq;
    wire [273:0] r_su_vmr;
    assign r_su_vmr = {d_f_hgi_vmr_su[273:0]};
    wire [0:0] r_su_s0_v;
    assign r_su_s0_v = dut.w_su_s0_v;
    wire [19:0] r_su_s0_idx;
    assign r_su_s0_idx = dut.w_su_s0_idx;
    wire [31:0] r_su_s0_data;
    assign r_su_s0_data = dut.w_su_s0_data;
    wire [522:0] r_su_am_stream;
    reg [522:0] q1_su_am_stream; always @(posedge clk) q1_su_am_stream <= r_su_am_stream;
    reg [522:0] q2_su_am_stream; always @(posedge clk) q2_su_am_stream <= q1_su_am_stream;
    reg [522:0] q3_su_am_stream; always @(posedge clk) q3_su_am_stream <= q2_su_am_stream;
    wire [0:0] r_su_am_rdy;
    assign r_su_am_rdy = {d_f_am_rdy[0:0]};
    ot_hgi_su_unit #(.N(16), .M(8), .LV(6), .LWB(17), .LG1(16), .LG2(15), .LG3(14), .SLB(16), .GLU(0), .MACRO(1)) ref_su (.clk(r_su_clk), .rst_n(r_su_rst_n), .rec_v(r_su_rec_v), .rec_rdy(r_su_rec_rdy), .rec_hdr(r_su_rec_hdr), .rec_sut(r_su_rec_sut), .rec_a(r_su_rec_a), .rec_b(r_su_rec_b), .rec_c(r_su_rec_c), .rec_d(r_su_rec_d), .rec_o(r_su_rec_o), .rec_r(r_su_rec_r), .rec_i(r_su_rec_i), .rec_n_a(r_su_rec_n_a), .rec_done(r_su_rec_done), .rec_fault(r_su_rec_fault), .halted(r_su_halted), .vmq(r_su_vmq), .vmr(r_su_vmr), .s0_v(r_su_s0_v), .s0_idx(r_su_s0_idx), .s0_data(r_su_s0_data), .am_stream(r_su_am_stream), .am_rdy(r_su_am_rdy));
    wire [0:0] r_sfu_clk;
    assign r_sfu_clk = dut.w_sfu_clk;
    wire [0:0] r_sfu_rst_n;
    assign r_sfu_rst_n = dut.w_sfu_rst_n;
    wire [0:0] r_sfu_rec_v;
    assign r_sfu_rec_v = {d_f_hgi_cmdproc_sfu[0:0]};
    wire [0:0] r_sfu_rec_rdy;
    reg [0:0] q1_sfu_rec_rdy; always @(posedge clk) q1_sfu_rec_rdy <= r_sfu_rec_rdy;
    reg [0:0] q2_sfu_rec_rdy; always @(posedge clk) q2_sfu_rec_rdy <= q1_sfu_rec_rdy;
    reg [0:0] q3_sfu_rec_rdy; always @(posedge clk) q3_sfu_rec_rdy <= q2_sfu_rec_rdy;
    wire [127:0] r_sfu_rec_hdr;
    assign r_sfu_rec_hdr = {d_f_hgi_cmdproc_sfu[128:1]};
    wire [255:0] r_sfu_rec_sut;
    assign r_sfu_rec_sut = dut.w_sfu_rec_sut;
    wire [255:0] r_sfu_rec_a;
    assign r_sfu_rec_a = {d_f_hgi_cmdproc_sfu[384:129]};
    wire [255:0] r_sfu_rec_b;
    assign r_sfu_rec_b = {d_f_hgi_cmdproc_sfu[640:385]};
    wire [255:0] r_sfu_rec_c;
    assign r_sfu_rec_c = {d_f_hgi_cmdproc_sfu[896:641]};
    wire [255:0] r_sfu_rec_d;
    assign r_sfu_rec_d = dut.w_sfu_rec_d;
    wire [255:0] r_sfu_rec_o;
    assign r_sfu_rec_o = {d_f_hgi_cmdproc_sfu[1152:897]};
    wire [255:0] r_sfu_rec_r;
    assign r_sfu_rec_r = dut.w_sfu_rec_r;
    wire [255:0] r_sfu_rec_i;
    assign r_sfu_rec_i = dut.w_sfu_rec_i;
    wire [20:0] r_sfu_rec_n_a;
    assign r_sfu_rec_n_a = {d_f_hgi_cmdproc_sfu[1173:1153]};
    wire [0:0] r_sfu_rec_done;
    reg [0:0] q1_sfu_rec_done; always @(posedge clk) q1_sfu_rec_done <= r_sfu_rec_done;
    reg [0:0] q2_sfu_rec_done; always @(posedge clk) q2_sfu_rec_done <= q1_sfu_rec_done;
    reg [0:0] q3_sfu_rec_done; always @(posedge clk) q3_sfu_rec_done <= q2_sfu_rec_done;
    wire [0:0] r_sfu_rec_fault;
    reg [0:0] q1_sfu_rec_fault; always @(posedge clk) q1_sfu_rec_fault <= r_sfu_rec_fault;
    reg [0:0] q2_sfu_rec_fault; always @(posedge clk) q2_sfu_rec_fault <= q1_sfu_rec_fault;
    reg [0:0] q3_sfu_rec_fault; always @(posedge clk) q3_sfu_rec_fault <= q2_sfu_rec_fault;
    wire [0:0] r_sfu_halted;
    reg [0:0] q1_sfu_halted; always @(posedge clk) q1_sfu_halted <= r_sfu_halted;
    reg [0:0] q2_sfu_halted; always @(posedge clk) q2_sfu_halted <= q1_sfu_halted;
    reg [0:0] q3_sfu_halted; always @(posedge clk) q3_sfu_halted <= q2_sfu_halted;
    wire [337:0] r_sfu_vmq;
    reg [337:0] q1_sfu_vmq; always @(posedge clk) q1_sfu_vmq <= r_sfu_vmq;
    reg [337:0] q2_sfu_vmq; always @(posedge clk) q2_sfu_vmq <= q1_sfu_vmq;
    reg [337:0] q3_sfu_vmq; always @(posedge clk) q3_sfu_vmq <= q2_sfu_vmq;
    wire [273:0] r_sfu_vmr;
    assign r_sfu_vmr = {d_f_hgi_vmr_sfu[273:0]};
    wire [0:0] r_sfu_s0_v;
    assign r_sfu_s0_v = dut.w_sfu_s0_v;
    wire [19:0] r_sfu_s0_idx;
    assign r_sfu_s0_idx = dut.w_sfu_s0_idx;
    wire [31:0] r_sfu_s0_data;
    assign r_sfu_s0_data = dut.w_sfu_s0_data;
    wire [522:0] r_sfu_am_stream;
    reg [522:0] q1_sfu_am_stream; always @(posedge clk) q1_sfu_am_stream <= r_sfu_am_stream;
    reg [522:0] q2_sfu_am_stream; always @(posedge clk) q2_sfu_am_stream <= q1_sfu_am_stream;
    reg [522:0] q3_sfu_am_stream; always @(posedge clk) q3_sfu_am_stream <= q2_sfu_am_stream;
    wire [0:0] r_sfu_am_rdy;
    assign r_sfu_am_rdy = dut.w_sfu_am_rdy;
    ot_hgi_su_unit #(.N(16), .M(8), .LV(6), .LWB(14), .LG1(14), .LG2(14), .LG3(14), .SLB(4), .GLU(1), .MACRO(1)) ref_sfu (.clk(r_sfu_clk), .rst_n(r_sfu_rst_n), .rec_v(r_sfu_rec_v), .rec_rdy(r_sfu_rec_rdy), .rec_hdr(r_sfu_rec_hdr), .rec_sut(r_sfu_rec_sut), .rec_a(r_sfu_rec_a), .rec_b(r_sfu_rec_b), .rec_c(r_sfu_rec_c), .rec_d(r_sfu_rec_d), .rec_o(r_sfu_rec_o), .rec_r(r_sfu_rec_r), .rec_i(r_sfu_rec_i), .rec_n_a(r_sfu_rec_n_a), .rec_done(r_sfu_rec_done), .rec_fault(r_sfu_rec_fault), .halted(r_sfu_halted), .vmq(r_sfu_vmq), .vmr(r_sfu_vmr), .s0_v(r_sfu_s0_v), .s0_idx(r_sfu_s0_idx), .s0_data(r_sfu_s0_data), .am_stream(r_sfu_am_stream), .am_rdy(r_sfu_am_rdy));
    wire [0:0] r_hc_clk;
    assign r_hc_clk = dut.w_hc_clk;
    wire [0:0] r_hc_rst_n;
    assign r_hc_rst_n = dut.w_hc_rst_n;
    wire [0:0] r_hc_rec_v;
    assign r_hc_rec_v = {d_f_hgi_cmdproc_hc[0:0]};
    wire [0:0] r_hc_rec_rdy;
    reg [0:0] q1_hc_rec_rdy; always @(posedge clk) q1_hc_rec_rdy <= r_hc_rec_rdy;
    reg [0:0] q2_hc_rec_rdy; always @(posedge clk) q2_hc_rec_rdy <= q1_hc_rec_rdy;
    reg [0:0] q3_hc_rec_rdy; always @(posedge clk) q3_hc_rec_rdy <= q2_hc_rec_rdy;
    wire [127:0] r_hc_rec_hdr;
    assign r_hc_rec_hdr = {d_f_hgi_cmdproc_hc[128:1]};
    wire [255:0] r_hc_rec_a;
    assign r_hc_rec_a = {d_f_hgi_cmdproc_hc[384:129]};
    wire [255:0] r_hc_rec_b;
    assign r_hc_rec_b = {d_f_hgi_cmdproc_hc[640:385]};
    wire [255:0] r_hc_rec_o;
    assign r_hc_rec_o = {d_f_hgi_cmdproc_hc[896:641]};
    wire [20:0] r_hc_rec_n_a;
    assign r_hc_rec_n_a = {d_f_hgi_cmdproc_hc[917:897]};
    wire [20:0] r_hc_rec_n_o;
    assign r_hc_rec_n_o = {d_f_hgi_cmdproc_hc[938:918]};
    wire [0:0] r_hc_rec_done;
    reg [0:0] q1_hc_rec_done; always @(posedge clk) q1_hc_rec_done <= r_hc_rec_done;
    reg [0:0] q2_hc_rec_done; always @(posedge clk) q2_hc_rec_done <= q1_hc_rec_done;
    reg [0:0] q3_hc_rec_done; always @(posedge clk) q3_hc_rec_done <= q2_hc_rec_done;
    wire [0:0] r_hc_rec_fault;
    reg [0:0] q1_hc_rec_fault; always @(posedge clk) q1_hc_rec_fault <= r_hc_rec_fault;
    reg [0:0] q2_hc_rec_fault; always @(posedge clk) q2_hc_rec_fault <= q1_hc_rec_fault;
    reg [0:0] q3_hc_rec_fault; always @(posedge clk) q3_hc_rec_fault <= q2_hc_rec_fault;
    wire [0:0] r_hc_halted;
    reg [0:0] q1_hc_halted; always @(posedge clk) q1_hc_halted <= r_hc_halted;
    reg [0:0] q2_hc_halted; always @(posedge clk) q2_hc_halted <= q1_hc_halted;
    reg [0:0] q3_hc_halted; always @(posedge clk) q3_hc_halted <= q2_hc_halted;
    wire [337:0] r_hc_vmq;
    reg [337:0] q1_hc_vmq; always @(posedge clk) q1_hc_vmq <= r_hc_vmq;
    reg [337:0] q2_hc_vmq; always @(posedge clk) q2_hc_vmq <= q1_hc_vmq;
    reg [337:0] q3_hc_vmq; always @(posedge clk) q3_hc_vmq <= q2_hc_vmq;
    wire [273:0] r_hc_vmr;
    assign r_hc_vmr = {d_f_hgi_vmr_hc[273:0]};
    wire [37:0] r_hc_xq;
    reg [37:0] q1_hc_xq; always @(posedge clk) q1_hc_xq <= r_hc_xq;
    reg [37:0] q2_hc_xq; always @(posedge clk) q2_hc_xq <= q1_hc_xq;
    reg [37:0] q3_hc_xq; always @(posedge clk) q3_hc_xq <= q2_hc_xq;
    wire [256:0] r_hc_xr;
    assign r_hc_xr = {d_f_hgi_hcmr[256:0]};
    ot_hgi_hc_die #(.W(32), .RMAX(128), .WMACRO(1)) ref_hc (.clk(r_hc_clk), .rst_n(r_hc_rst_n), .rec_v(r_hc_rec_v), .rec_rdy(r_hc_rec_rdy), .rec_hdr(r_hc_rec_hdr), .rec_a(r_hc_rec_a), .rec_b(r_hc_rec_b), .rec_o(r_hc_rec_o), .rec_n_a(r_hc_rec_n_a), .rec_n_o(r_hc_rec_n_o), .rec_done(r_hc_rec_done), .rec_fault(r_hc_rec_fault), .halted(r_hc_halted), .vmq(r_hc_vmq), .vmr(r_hc_vmr), .xq(r_hc_xq), .xr(r_hc_xr));
    integer err = 0, nchk = 0, cyc;
    integer seed = 20261006;
    task automatic randomize_inputs; begin
        f_am_rdy[0:0] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[31:0] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[63:32] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[95:64] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[127:96] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[159:128] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[191:160] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[223:192] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[255:224] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[287:256] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[319:288] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[351:320] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[383:352] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[415:384] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[447:416] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[479:448] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[511:480] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[543:512] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[575:544] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[607:576] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[639:608] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[671:640] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[703:672] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[735:704] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[767:736] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[799:768] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[831:800] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[863:832] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[895:864] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[927:896] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_hc[938:928] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[31:0] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[63:32] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[95:64] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[127:96] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[159:128] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[191:160] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[223:192] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[255:224] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[287:256] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[319:288] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[351:320] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[383:352] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[415:384] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[447:416] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[479:448] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[511:480] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[543:512] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[575:544] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[607:576] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[639:608] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[671:640] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[703:672] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[735:704] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[767:736] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[799:768] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[831:800] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[863:832] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[895:864] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[927:896] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[959:928] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[991:960] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[1023:992] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[1055:1024] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[1087:1056] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[1119:1088] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[1151:1120] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_sfu[1173:1152] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[31:0] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[63:32] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[95:64] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[127:96] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[159:128] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[191:160] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[223:192] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[255:224] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[287:256] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[319:288] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[351:320] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[383:352] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[415:384] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[447:416] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[479:448] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[511:480] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[543:512] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[575:544] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[607:576] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[639:608] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[671:640] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[703:672] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[735:704] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[767:736] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[799:768] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[831:800] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[863:832] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[895:864] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[927:896] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[959:928] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[991:960] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1023:992] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1055:1024] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1087:1056] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1119:1088] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1151:1120] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1183:1152] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1215:1184] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1247:1216] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1279:1248] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1311:1280] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1343:1312] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1375:1344] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1407:1376] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1439:1408] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1471:1440] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1503:1472] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1535:1504] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1567:1536] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1599:1568] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1631:1600] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1663:1632] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1695:1664] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1727:1696] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1759:1728] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1791:1760] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1823:1792] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1855:1824] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1887:1856] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1919:1888] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1951:1920] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[1983:1952] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[2015:1984] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[2047:2016] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[2079:2048] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[2111:2080] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[2143:2112] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[2175:2144] = $urandom(seed); seed = seed + 1;
        f_hgi_cmdproc_su[2197:2176] = $urandom(seed); seed = seed + 1;
        f_hgi_hcmr[31:0] = $urandom(seed); seed = seed + 1;
        f_hgi_hcmr[63:32] = $urandom(seed); seed = seed + 1;
        f_hgi_hcmr[95:64] = $urandom(seed); seed = seed + 1;
        f_hgi_hcmr[127:96] = $urandom(seed); seed = seed + 1;
        f_hgi_hcmr[159:128] = $urandom(seed); seed = seed + 1;
        f_hgi_hcmr[191:160] = $urandom(seed); seed = seed + 1;
        f_hgi_hcmr[223:192] = $urandom(seed); seed = seed + 1;
        f_hgi_hcmr[255:224] = $urandom(seed); seed = seed + 1;
        f_hgi_hcmr[256:256] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_hc[31:0] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_hc[63:32] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_hc[95:64] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_hc[127:96] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_hc[159:128] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_hc[191:160] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_hc[223:192] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_hc[255:224] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_hc[273:256] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_sfu[31:0] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_sfu[63:32] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_sfu[95:64] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_sfu[127:96] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_sfu[159:128] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_sfu[191:160] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_sfu[223:192] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_sfu[255:224] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_sfu[273:256] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_su[31:0] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_su[63:32] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_su[95:64] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_su[127:96] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_su[159:128] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_su[191:160] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_su[223:192] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_su[255:224] = $urandom(seed); seed = seed + 1;
        f_hgi_vmr_su[273:256] = $urandom(seed); seed = seed + 1;
    end endtask
    initial begin
        rst = 1;
        randomize_inputs;
        repeat (8) @(posedge clk);
        #0.05 rst = 0;
        for (cyc = 0; cyc < 2000; cyc = cyc + 1) begin
            @(negedge clk);
            nchk = nchk + 1; if (t_hgi_cmdproc_su[0:0] !== q3_su_rec_rdy[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_cmdproc_su[0:0] %h ref %h cyc %0d", t_hgi_cmdproc_su[0:0], q3_su_rec_rdy[0:0], cyc); end
            nchk = nchk + 1; if (t_hgi_cmdproc_su[1:1] !== q3_su_rec_done[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_cmdproc_su[1:1] %h ref %h cyc %0d", t_hgi_cmdproc_su[1:1], q3_su_rec_done[0:0], cyc); end
            nchk = nchk + 1; if (t_hgi_cmdproc_su[2:2] !== q3_su_rec_fault[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_cmdproc_su[2:2] %h ref %h cyc %0d", t_hgi_cmdproc_su[2:2], q3_su_rec_fault[0:0], cyc); end
            nchk = nchk + 1; if (t_hgi_vmq_su[337:0] !== q3_su_vmq[337:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_vmq_su[337:0] %h ref %h cyc %0d", t_hgi_vmq_su[337:0], q3_su_vmq[337:0], cyc); end
            nchk = nchk + 1; if (t_am_in_v[0:0] !== q3_su_am_stream[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_am_in_v[0:0] %h ref %h cyc %0d", t_am_in_v[0:0], q3_su_am_stream[0:0], cyc); end
            nchk = nchk + 1; if (t_am_in_last[0:0] !== q3_su_am_stream[1:1]) begin err = err + 1; if (err < 10) $display("MISMATCH t_am_in_last[0:0] %h ref %h cyc %0d", t_am_in_last[0:0], q3_su_am_stream[1:1], cyc); end
            nchk = nchk + 1; if (t_am_in_mask[7:0] !== q3_su_am_stream[9:2]) begin err = err + 1; if (err < 10) $display("MISMATCH t_am_in_mask[7:0] %h ref %h cyc %0d", t_am_in_mask[7:0], q3_su_am_stream[9:2], cyc); end
            nchk = nchk + 1; if (t_am_in_vals[255:0] !== q3_su_am_stream[265:10]) begin err = err + 1; if (err < 10) $display("MISMATCH t_am_in_vals[255:0] %h ref %h cyc %0d", t_am_in_vals[255:0], q3_su_am_stream[265:10], cyc); end
            nchk = nchk + 1; if (t_am_in_bias[255:0] !== q3_su_am_stream[521:266]) begin err = err + 1; if (err < 10) $display("MISMATCH t_am_in_bias[255:0] %h ref %h cyc %0d", t_am_in_bias[255:0], q3_su_am_stream[521:266], cyc); end
            nchk = nchk + 1; if (t_am_in_bias_en[0:0] !== q3_su_am_stream[522:522]) begin err = err + 1; if (err < 10) $display("MISMATCH t_am_in_bias_en[0:0] %h ref %h cyc %0d", t_am_in_bias_en[0:0], q3_su_am_stream[522:522], cyc); end
            nchk = nchk + 1; if (t_hgi_cmdproc_sfu[0:0] !== q3_sfu_rec_rdy[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_cmdproc_sfu[0:0] %h ref %h cyc %0d", t_hgi_cmdproc_sfu[0:0], q3_sfu_rec_rdy[0:0], cyc); end
            nchk = nchk + 1; if (t_hgi_cmdproc_sfu[1:1] !== q3_sfu_rec_done[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_cmdproc_sfu[1:1] %h ref %h cyc %0d", t_hgi_cmdproc_sfu[1:1], q3_sfu_rec_done[0:0], cyc); end
            nchk = nchk + 1; if (t_hgi_cmdproc_sfu[2:2] !== q3_sfu_rec_fault[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_cmdproc_sfu[2:2] %h ref %h cyc %0d", t_hgi_cmdproc_sfu[2:2], q3_sfu_rec_fault[0:0], cyc); end
            nchk = nchk + 1; if (t_hgi_vmq_sfu[337:0] !== q3_sfu_vmq[337:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_vmq_sfu[337:0] %h ref %h cyc %0d", t_hgi_vmq_sfu[337:0], q3_sfu_vmq[337:0], cyc); end
            nchk = nchk + 1; if (t_hgi_cmdproc_hc[0:0] !== q3_hc_rec_rdy[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_cmdproc_hc[0:0] %h ref %h cyc %0d", t_hgi_cmdproc_hc[0:0], q3_hc_rec_rdy[0:0], cyc); end
            nchk = nchk + 1; if (t_hgi_cmdproc_hc[1:1] !== q3_hc_rec_done[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_cmdproc_hc[1:1] %h ref %h cyc %0d", t_hgi_cmdproc_hc[1:1], q3_hc_rec_done[0:0], cyc); end
            nchk = nchk + 1; if (t_hgi_cmdproc_hc[2:2] !== q3_hc_rec_fault[0:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_cmdproc_hc[2:2] %h ref %h cyc %0d", t_hgi_cmdproc_hc[2:2], q3_hc_rec_fault[0:0], cyc); end
            nchk = nchk + 1; if (t_hgi_vmq_hc[337:0] !== q3_hc_vmq[337:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_vmq_hc[337:0] %h ref %h cyc %0d", t_hgi_vmq_hc[337:0], q3_hc_vmq[337:0], cyc); end
            nchk = nchk + 1; if (t_hgi_hcmq[37:0] !== q3_hc_xq[37:0]) begin err = err + 1; if (err < 10) $display("MISMATCH t_hgi_hcmq[37:0] %h ref %h cyc %0d", t_hgi_hcmq[37:0], q3_hc_xq[37:0], cyc); end
            randomize_inputs;
        end
        $display("TB_hfd_hgi_su checks=%0d mismatches=%0d", nchk, err);
        if (err != 0 || nchk == 0) $fatal(1, "FAIL");
        $finish;
    end
endmodule
