#!/usr/bin/env python3
"""kv-die 2026-10-09 (review-0528 item 3, CRITICAL PATH): generate rtl/hdc/nearhbm/ot_qwen_nearhbm_attn_stack_c.sv, the
near-HBM stack RE-CUT at the row engine <-> stack aggregator boundary, from the timing successor
rtl/hdc/nearhbm/ot_qwen_nearhbm_attn_stack_p.sv (every module suffixed _c; the _p file is untouched).

Why: an _p row engine element has 16,385 q input bits (the stack's q registers, broadcast) and 16,392 P.V-leaf output
bits (one 512-lane FP32 leaf a cycle): 34 k IO bits per engine, 8 engines on one aggregator.
The re-cut (same arithmetic, same order -- only where values are held and how they move):
  q      the engine holds its own copy of the 1,024 BF16 q values: the aggregator broadcasts the 32 registered q beats
         (q_valid + 6-b beat + 512 b) and each engine writes them into its q registers; q_ready is local (its beat
         count).  Engine q input: 519 bits instead of 16,385.
  leaves the engine LATCHES a finished leaf (its loop value at the leaf's offer turn, slot order within its group) into
         a leaf register, which frees the slot exactly as the tree's take did, and streams it to the aggregator as LFB
         beats of 16,384 / LFB bits {beat, g, gam, slot, data}; the aggregator assembles it into an LBD-leaf staging
         FIFO per engine (credit flow: one credit a leaf, returned when the P.V tree takes the leaf).  The P.V tree
         consumes the staged leaves in the same residue order as before.  Engine leaf output: 16,384 / LFB + 10 bits.
Every added register is priced by the bench (cycles per layer), not assumed.

    python3 tools/qwen_kv_die/stack_c_gen.py [--check]
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'rtl/hdc/nearhbm/ot_qwen_nearhbm_attn_stack_p.sv'
DST = ROOT / 'rtl/hdc/nearhbm/ot_qwen_nearhbm_attn_stack_c.sv'


def rep(s, a, b, n=1):
    if a not in s:
        raise SystemExit(f'stack_c_gen: anchor not found: {a[:80]!r}')
    return s.replace(a, b, n)


def generate():
    s = SRC.read_text()
    head = ('`timescale 1ns/1ps\n'
            '// ---------------------------------------------------------------------------------------------------------------------\n'
            '// GENERATED by tools/qwen_kv_die/stack_c_gen.py from rtl/hdc/nearhbm/ot_qwen_nearhbm_attn_stack_p.sv (do not edit by\n'
            '// hand).  RE-CUT of the near-HBM stack at the row engine <-> aggregator boundary (kv-die 2026-10-09, review-0528):\n'
            '// q held in each engine (519-bit q beat broadcast), P.V leaves latched in the engine and streamed in LFB beats into\n'
            '// an LBD-leaf staging FIFO per engine at the aggregator (credit flow).  Same arithmetic, same order.  NEW,\n'
            '// DEFAULT-OFF: only the KV-die element (qkd_reng / qkd_astk) and its benches use it.\n'
            '// ---------------------------------------------------------------------------------------------------------------------\n')
    s = s.split('\n', 1)[1]                     # drop the _p timescale line; the _p header comment stays below as history
    mods = re.findall(r'(?m)^module\s+(\w+)_p\b', s)            # only the modules this file defines
    s = re.sub(r'\b(' + '|'.join(map(re.escape, mods)) + r')_p\b', r'\1_c', s)
    # ---------------- row engine: ports ----------------
    s = rep(s, """    input  wire                 q_ready,      // q registers loaded
    input  wire [8*HD*16-1:0]   q_bf16,       // q[h][d] at [(h*HD+d)*16 +: 16]
""", """    input  wire                 q_valid_in,   // re-cut: the aggregator's registered q beat broadcast
    input  wire [5:0]           q_beat_in,
    input  wire [511:0]         q_data_in,
""")
    s = rep(s, """    output wire                 lf_valid,
    output wire                 lf_g,
    output wire [3:0]           lf_gam,
    output wire [2:0]           lf_slot,
    output wire [4*HD*32-1:0]   lf_data,
    input  wire                 lf_take,
""", """    output reg                  lb_valid,     // re-cut: a leaf beat {beat, g, gam, slot, data} to the staging FIFO
    output reg  [1:0]           lb_beat,
    output reg                  lb_g,
    output reg  [3:0]           lb_gam,
    output reg  [2:0]           lb_slot,
    output reg  [4*HD*32/LFB-1:0] lb_data,
    input  wire                 lb_cr,        // one staging credit returned (the tree took a leaf)
""")
    s = rep(s, """    parameter integer DQ = 32,           // row / e FIFO depth = outstanding-request credit
    parameter [31:0]  SCALE = 32'h3DB504F3
) (
    input  wire                 clk,
    input  wire                 rst_n,
    input  wire                 start_in,""", """    parameter integer DQ = 32,           // row / e FIFO depth = outstanding-request credit
    parameter [31:0]  SCALE = 32'h3DB504F3,
    parameter integer LFB = 4,           // re-cut: leaf beats
    parameter integer LBD = 2            // re-cut: staging leaves a engine at the aggregator (= the engine's credits)
) (
    input  wire                 clk,
    input  wire                 rst_n,
    input  wire                 start_in,""")
    # ---------------- row engine: local q registers ----------------
    s = rep(s, """    always @(posedge clk) begin T <= T_in; cyc8_r <= cyc8_in; rsp_data <= rsp_data_in; end
""", """    always @(posedge clk) begin T <= T_in; cyc8_r <= cyc8_in; rsp_data <= rsp_data_in; end
    // re-cut: this engine's q registers, written from the registered beat broadcast (q_ready = all 32 beats in)
    localparam integer NQB = 8 * HD * 16 / 512;
    reg               qv_r;
    reg  [5:0]        qb_r;
    reg  [511:0]      qd_r;
    reg  [8*HD*16-1:0] q_bf16;
    reg  [6:0]        qcnt;
    always @(posedge clk or negedge rst_n) if (!rst_n) qv_r <= 1'b0; else qv_r <= q_valid_in;
    always @(posedge clk) begin qb_r <= q_beat_in; qd_r <= q_data_in; if (qv_r) q_bf16[512*qb_r +: 512] <= qd_r; end
    always @(posedge clk or negedge rst_n)
        if (!rst_n) qcnt <= 7'd0;
        else if (start) qcnt <= 7'd0;
        else if (qv_r) qcnt <= qcnt + 7'd1;
    wire q_ready = (qcnt == NQB);
""")
    # ---------------- row engine: leaf latch + beat stream ----------------
    s = rep(s, """    wire        take = offer && lf_take;
""", """    // re-cut: the leaf of slot os is taken into the leaf register (slot order within the group, one at a time, with a
    // staging credit in hand); the slot is freed exactly as by the tree's take before.
    reg  [2:0]  nxt_slot;
    reg  [2:0]  lcnt;                                   // beats still to send (0: register free)
    reg  [$clog2(LBD+1)-1:0] lcred;
    reg         lcr_q;
    wire        take = offer && (os == nxt_slot) && (lcnt == 3'd0) && (lcred != 0);
""")
    s = rep(s, """    assign lf_valid = offer;
    assign lf_g = pend_g[os];
    assign lf_gam = pend_gam[os];
    assign lf_slot = os;
    assign lf_data = fb;
""", """    reg  [4*HD*32-1:0] lreg;
    reg         lg;
    reg  [3:0]  lgam;
    reg  [2:0]  lslot;
    always @(posedge clk) if (take) begin lreg <= fb; lg <= pend_g[os]; lgam <= pend_gam[os]; lslot <= os; end
    always @(posedge clk or negedge rc) begin
        if (!rc) begin nxt_slot <= 3'd0; lcnt <= 3'd0; lcred <= LBD; lcr_q <= 1'b0; lb_valid <= 1'b0; end
        else begin
            lcr_q <= lb_cr;
            lb_valid <= 1'b0;
            if (start) nxt_slot <= 3'd0;
            if (take) begin nxt_slot <= nxt_slot + 3'd1; lcnt <= LFB; end
            else if (lcnt != 3'd0) begin
                lb_valid <= 1'b1; lb_beat <= 2'(LFB - lcnt); lb_g <= lg; lb_gam <= lgam; lb_slot <= lslot;
                lcnt <= lcnt - 3'd1;
            end
            lcred <= lcred - (take ? 1'b1 : 1'b0) + (lcr_q ? 1'b1 : 1'b0);
        end
    end
    always @(posedge clk) if (lcnt != 3'd0) lb_data <= lreg[(4*HD*32/LFB)*(LFB - lcnt) +: 4*HD*32/LFB];
""")
    # ---------------- stack: q broadcast, staging FIFOs ----------------
    s = rep(s, """    // q registers
    reg [8*HD*16-1:0] qr;
    reg [6:0] qcnt;
    wire q_ready = (qcnt == NQB);
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) qcnt <= 0;
        else if (start) qcnt <= 0;
        else if (q_valid) qcnt <= qcnt + 7'd1;
    end
    always @(posedge clk) if (q_valid) qr[512*q_beat +: 512] <= q_data;
""", """    // re-cut: no stack q registers; the q beats are registered once and broadcast to the engines (q_ready: the bench
    // marker only -- every engine counts its own beats)
    reg [6:0] qcnt;
    wire q_ready = (qcnt == NQB);
    reg        qv_b;
    reg [5:0]  qb_b;
    reg [511:0] qd_b;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin qcnt <= 0; qv_b <= 1'b0; end
        else begin
            qv_b <= q_valid;
            if (start) qcnt <= 0;
            else if (q_valid) qcnt <= qcnt + 7'd1;
        end
    end
    always @(posedge clk) begin qb_b <= q_beat; qd_b <= q_data; end
""")
    i = s.index('module ot_qwen_nearhbm_attn_stack_c #(')
    j = s.index('    parameter integer ZW = 4,\n', i)
    s = s[:j] + ('    parameter integer ZW = 4,\n    parameter integer LFB = 4,           // re-cut: leaf beats\n'
                 '    parameter integer LBD = 2,           // re-cut: staging leaves a engine\n') + s[j + len('    parameter integer ZW = 4,\n'):]
    s = rep(s, """    wire [LN*32*R-1:0] lf_data;
    reg  [31:0] exp_done;""", """    wire [LN*32*R-1:0] lf_data;
    wire [R-1:0] lb_valid, lb_g;
    wire [2*R-1:0] lb_beat;
    wire [4*R-1:0] lb_gam;
    wire [3*R-1:0] lb_slot;
    wire [LN*32/LFB*R-1:0] lb_data;
    reg  [R-1:0] lb_cr;
    reg  [31:0] exp_done;""")
    s = rep(s, """                                     .MUL_LAT(MUL_LAT), .DQ(DQ), .SCALE(SCALE)) u_eng (
            .clk(clk), .rst_n(rst_n), .start_in(start), .T_in(T), .cyc8_in(cyc8), .q_ready(q_ready), .q_bf16(qr),""",
               """                                     .MUL_LAT(MUL_LAT), .DQ(DQ), .SCALE(SCALE), .LFB(LFB), .LBD(LBD)) u_eng (
            .clk(clk), .rst_n(rst_n), .start_in(start), .T_in(T), .cyc8_in(cyc8), .q_valid_in(qv_b), .q_beat_in(qb_b),
            .q_data_in(qd_b),""")
    s = rep(s, """            .lf_valid(lf_valid[e]), .lf_g(lf_g[e]), .lf_gam(lf_gam[4*e +: 4]), .lf_slot(lf_slot[3*e +: 3]),
            .lf_data(lf_data[LN*32*e +: LN*32]),
            .lf_take(take[e]), .k_done(k_done[e]),""", """            .lb_valid(lb_valid[e]), .lb_beat(lb_beat[2*e +: 2]), .lb_g(lb_g[e]), .lb_gam(lb_gam[4*e +: 4]),
            .lb_slot(lb_slot[3*e +: 3]), .lb_data(lb_data[LN*32/LFB*e +: LN*32/LFB]), .lb_cr(lb_cr[e]),
            .k_done(k_done[e]),""")
    s = rep(s, """        assign req_valid[e] = rv; assign req_v[e] = rvv; assign req_g[e] = rg; assign req_t[13*e +: 13] = rt;
    end endgenerate""", """        assign req_valid[e] = rv; assign req_v[e] = rvv; assign req_g[e] = rg; assign req_t[13*e +: 13] = rt;
        // re-cut: this engine's leaf staging FIFO (LBD leaves), assembled from the registered beats
        reg            bv;
        reg  [1:0]     bb;
        reg            bg;
        reg  [3:0]     bgam;
        reg  [2:0]     bslot;
        reg  [LN*32/LFB-1:0] bd;
        always @(posedge clk or negedge rst_n) if (!rst_n) bv <= 1'b0; else bv <= lb_valid[e];
        always @(posedge clk) begin bb <= lb_beat[2*e +: 2]; bg <= lb_g[e]; bgam <= lb_gam[4*e +: 4];
                                     bslot <= lb_slot[3*e +: 3]; bd <= lb_data[LN*32/LFB*e +: LN*32/LFB]; end
        localparam integer SA = (LBD > 1) ? $clog2(LBD) : 1;
        reg  [LN*32-1:0] stg [0:LBD-1];
        reg  [7:0]       smeta [0:LBD-1];
        reg  [SA-1:0]    swp, srp;
        reg  [$clog2(LBD+1)-1:0] scnt;
        wire             last_beat = bv && (bb == 2'(LFB - 1));
        always @(posedge clk) if (bv) begin
            stg[swp][(LN*32/LFB)*bb +: LN*32/LFB] <= bd;
            smeta[swp] <= {bg, bgam, bslot};
        end
        always @(posedge clk or negedge rst_n) begin
            if (!rst_n) begin swp <= 0; srp <= 0; scnt <= 0; lb_cr[e] <= 1'b0; end
            else begin
                if (last_beat) swp <= (swp == SA'(LBD - 1)) ? {SA{1'b0}} : swp + 1'b1;
                if (take[e]) srp <= (srp == SA'(LBD - 1)) ? {SA{1'b0}} : srp + 1'b1;
                scnt <= scnt + (last_beat ? 1'b1 : 1'b0) - (take[e] ? 1'b1 : 1'b0);
                lb_cr[e] <= take[e];
            end
        end
        assign lf_valid[e] = (scnt != 0);
        assign lf_g[e] = smeta[srp][7];
        assign lf_gam[4*e +: 4] = smeta[srp][6:3];
        assign lf_slot[3*e +: 3] = smeta[srp][2:0];
        assign lf_data[LN*32*e +: LN*32] = stg[srp];
    end endgenerate""")
    return head + s


def main():
    txt = generate()
    if '--check' in sys.argv:
        sys.exit(0 if DST.exists() and DST.read_text() == txt else 1)
    DST.write_text(txt)
    print(DST)


if __name__ == '__main__':
    main()
