# generated by physical/dsrom_fh_safe/cl_route.sh (ctl): insertion SS 427 / FF 278 ps
create_clock -name core_clk -period 833.333 [get_ports clk]
set_propagated_clock [all_clocks]
set_clock_uncertainty -setup 60 [all_clocks]
set_clock_uncertainty -hold 25 [all_clocks]
set_input_delay -max 677 -clock core_clk [all_inputs -no_clocks]
set_input_delay -min 278 -clock core_clk [all_inputs -no_clocks]
set_output_delay -max -177 -clock core_clk [all_outputs]
set_output_delay -min -328 -clock core_clk [all_outputs]
set_load 3.898 [all_outputs]
set_false_path -from [get_ports rst_n]

