// GENERATED by tools/qwen_missing/emit_partition.py from the emitted ot_qwen_rom_core (tools/qwen_rom_rt_core_emit_w12.py). The core minus its matrix-engine spine and stream unit.
// GENERATED by tools/qwen_rom_rt_core_emit_w12.py from rtl/hdc/ot_hdc_core_vector_weight.sv (sha256 702807d4db28a2881caebe02c42595f53d8eac48934b71be1941cec44106615f).
`timescale 1ns/1ps
// ---------------------------------------------------------------------------
// Hardwired decode core (HDC): decodes one token of a fixed model.
//
// A static program (tools/hdc_program.py, format tools/hdc_isa.py) of
// macro-operations drives two units, the matrix-vector engine (ot_hdc_matvec)
// and the stream unit (ot_hdc_stream).  The sequencer fetches an instruction,
// adds the per-token DYN offsets (token row, RoPE row, KV write slot, context
// length) and issues it when the unit is ready; an instruction marked `barrier`
// first waits for both units to drain.  There is no descriptor queue, no
// admission and no interpretation: the program is the schedule.
//
// ISSUE PIPELINE.  Fetch runs ahead of issue: program words stream from the
// program ROM (a read every cycle while fewer than NFQ words are held or in
// flight) into a small word FIFO; the head is decoded (DYN offsets added) into
// the NEXT register set whenever it is empty or being issued.  An instruction
// issues from NEXT in the cycle its conditions hold: `me_go` / `su_go` are
// combinational and the unit latches NEXT's fields on that edge, the same edge
// that decodes the following instruction into NEXT -- so independent
// instructions issue on consecutive cycles (the issue gap is 1, was 5).
//
// Memories sit outside the core behind synchronous-read ports: program ROM,
// BF16 stream/embedding ROM, optional signed INT8 matrix ROM and per-row BF16
// scale ROM, constant ROM (FP32 pairs), KV SRAM (W x FP32 per word, element
// write) and vector memory (FP32 elements).
// ---------------------------------------------------------------------------
module ot_qwen_rom_core_ctrl_x #(
    parameter integer OWN = 2,        // redesign-qwen: this controller's unit (1 ME, 2 SU)
    parameter integer XW = 24,        // other-unit op counter width
    parameter integer XMUT = 0,       // negative controls (split_ctrl.py MUT)
    parameter integer FQ_HEAD = 0,   // safe-qwen S-A6: registered FIFO head word (decode reads a flop)
    parameter integer INSTR_BITS = 1024,   // must equal ISA_INSTR_BITS (tools/hdc_isa.py)
    parameter integer W    = 16,
    parameter integer G    = 4,
    parameter integer IL   = 8,
    parameter integer AW   = 24,
    parameter integer NW   = 16,
    parameter integer PAW  = 12,      // program address bits
    // model constants for the DYN offsets
    parameter integer HID  = 128,
    parameter integer HALF = 8,
    parameter integer HD   = 16,
    // KV_HBM = 1: the KV cache lives in HBM behind ot_hdc_kv_stream.  A
    // KV-sourced matrix op then announces its descriptor (kvd_*) when the
    // sequencer reaches it and issues only once the streamer raises kv_ok
    // (its prefetch window covers the op; the engine never stalls).  With
    // KV_HBM = 0 the kvd_* outputs are unused and kv_ok is ignored.
    parameter integer KV_HBM = 0,
    // The stream unit.  SU_VEC = 1: the vector stream unit (ot_hdc_vstream) of
    // SW lanes (a multiple of 8) with the R-ARITH reducer (segments of up to
    // 2^LV vectors); every stream port is SW elements wide.  SU_VEC = 0: the
    // scalar stream unit (ot_hdc_stream, SW must be 1) and its P=8 reducer --
    // the configurations not yet moved (the KV-in-HBM streamer).
    parameter integer SU_VEC = 0,
    parameter integer SW     = 1,
    parameter integer LV     = 4,
    parameter integer KV_FP8 = (SU_VEC != 0),
    parameter integer KV_VEC_WRITE_BRIDGE = 0,
    parameter integer W_HBM = 0,
    // INT8_WEIGHT replaces only matrix ROM products. The embedding stream
    // still reads BF16 until its own INT8 dequantisation path is integrated.
    parameter integer INT8_WEIGHT = 0,
    parameter integer INT8_SCALE_WCS_BASE = 0,
    parameter integer INT8_EMBED = 0,
    // Opt-in Qwen full-vocabulary encoding: two ME row-offset bits live just
    // above the legacy 16-bit field in the otherwise unused ISA tail.
    parameter integer QWEN_FULLSHAPE = 0,
    // ME_STALL = 1: an HBM weight supply may hold the matrix engine for a
    // cycle (bounded within-round continuation).  The engine and its memory
    // write enables are clocked only on edges where me_mem_ok was high during
    // the preceding low phase (ot_hdc_cg), so a held cycle is an exact pause:
    // no element, product or sum order changes.  The supply must hold its
    // engine read-response registers on the same edges (me_clk_en).
    // ME_STALL = 0 ties the enable high: the ROM core is unchanged.
    parameter integer ME_STALL = 0,
    // ME_IDLE_GATE = 1: also stop the engine clock while it is idle and no
    // engine instruction waits in NEXT (unit clock gating).  An idle engine
    // holds only registered, drained outputs; it is re-enabled on the edge an
    // engine instruction reaches NEXT, before its go, so issue timing is
    // unchanged.  0 keeps the engine clock free-running.
    parameter integer ME_IDLE_GATE = 0,
    parameter integer EMB_CODE_LANES = 64,
    parameter integer EMB_ADDR_BASE = 0, // element address of embedding row 0 in the program
    parameter integer SMIN = 0,
    parameter integer SMAX = 0,
    parameter integer TCUT = 0,
    parameter integer BD = 0,
    parameter integer XVM = 0,
    parameter integer NWS = 0,
    parameter integer TWS = 0,
    parameter integer ORD = 0,
    parameter integer SCALE_LOCAL = 0,
    parameter integer MEM_EXTRA = 0,
    parameter integer ACC_LAT = 5,
    parameter integer TREE_LAT = 3,
    parameter integer MUL_LAT = 5,
    parameter integer FAST_ISSUE = 0,
    parameter integer KV_PREP = 0
) (
    input  wire              clk,
    input  wire              rst_n,
    input  wire              start,
    input  wire [NW-1:0]     token,
    input  wire [NW-1:0]     pos,
    output reg               done,
    output reg  [NW-1:0]     next_token,
    output reg  [31:0]       next_val,        // its logit (for an argmax combined across packages)
    output reg  [31:0]       cycles,
    output reg               fault,
    // program ROM
    output reg               prog_re,
    output reg  [PAW-1:0]    prog_addr,
    input  wire [INSTR_BITS-1:0] prog_q,
    // weight ROM
    output wire              wrom_re,
    output wire [AW-1:0]     wrom_addr,
    input  wire [G*W*16-1:0] wrom_q,
    // Separate matrix code and scale banks avoid aliasing the stream's BF16
    // embedding reads. Both are synchronous, with one-cycle read latency.
    output wire              int8_wrom_re,
    output wire [AW-1:0]     int8_wrom_addr,
    output wire              scale_re,
    output wire [(G >> SMIN)-1:0] scale_gre,
    output wire [(G >> SMIN)*AW-1:0] scale_addr,
    input  wire [(G >> SMIN)*W*16-1:0] scale_q,
    // Independent 8-bit embedding bank and one BF16 scale per token row.
    output wire              embed_code_re,
    output wire [AW-1:0]     embed_code_addr,
    input  wire [EMB_CODE_LANES*8-1:0] embed_code_q,
    output wire              embed_scale_re,
    output wire [NW-1:0]     embed_scale_addr,
    input  wire [15:0]       embed_scale_q,
    // constant ROM
    output wire [SW-1:0]     crom_re,
    output wire [SW*AW-1:0]  crom_addr,
    input  wire [SW*64-1:0]  crom_q,
    // KV SRAM
    output wire              kv_re,
    output wire [SW-1:0]     kv_we,
    output wire [SW*AW-1:0]  kv_waddr,
    output wire [SW*32-1:0]  kv_wdata,
    // Optional vector KV bridge drain. The vector stream cannot stall once
    // issued, so the bridge buffers one whole KV-write op and drains before
    // the sequencer starts another stream op or retires the token.
    input  wire              kv_write_drained,
    output wire              kv_write_flush, // finish a partial V sector while SU is idle
    // vector memory: G + 3 element read ports, G + 2 write ports
    output wire [SW-1:0]     va_re,
    output wire [SW*AW-1:0]  va_addr,
    input  wire [SW*32-1:0]  va_q,
    output wire [SW-1:0]     vb_re,
    output wire [SW*AW-1:0]  vb_addr,
    input  wire [SW*32-1:0]  vb_q,
    output wire [SW-1:0]     vc_re,
    output wire [SW*AW-1:0]  vc_addr,
    input  wire [SW*32-1:0]  vc_q,
    output wire [(G >> SMIN)-1:0] vw_me_we,
    output wire [(G >> SMIN)*AW-1:0] vw_me_addr,       // words
    output wire [(G >> SMIN)*W-1:0] vw_me_mask,
    output wire [(G >> SMIN)*W*32-1:0] vw_me_data,
    output wire [SW-1:0]     vw_su_we,
    output wire [SW*AW-1:0]  vw_su_addr,
    output wire [SW*32-1:0]  vw_su_data,
    output wire              vw_rd_we,
    output wire [AW-1:0]     vw_rd_addr,
    output wire [31:0]       vw_rd_data,
    // the engine's per-slot maxima (one masked word; me_rmax)
    output wire              vw_mx_we,
    output wire [AW-1:0]     vw_mx_addr,
    output wire [W-1:0]      vw_mx_mask,
    output wire [W*32-1:0]   vw_mx_data,
    // observation: every matrix-vector result word
    output wire              me_ov,
    // KV-streaming handshake (KV_HBM = 1 only)
    output reg               kvd_v,           // descriptor of the KV op now waiting to issue
    output wire [AW-1:0]     kvd_wbase, kvd_ts, kvd_ks, kvd_js,
    output wire [AW-1:0]     kvd_wcs,
    output wire [3:0]        kvd_split,
    output wire [2:0]        kvd_jsh,
    output wire [NW-1:0]     kvd_tiles, kvd_k, kvd_nout,
    output wire              kvd_kindk,       // positions tile the lanes (scores); else positions are k (weighted sum)
    output wire [NW-1:0]     kvd_pos,
    input  wire              kv_ok,
    // Weight supply handshake. Both comparator modes use this same FIFO/vector
    // controller and chunked program; W_HBM selects only the weight source.
    output wire              wrom_su,
    output reg               wd_v,
    output wire [AW-1:0]     wd_wbase,
    output wire [AW-1:0]     wd_sbase,
    output wire [NW-1:0]     wd_tiles, wd_k, wd_nout,
    // W12 array spine: the vector memory's x chunk port and the tile fabric
    output wire [(1<<SMAX)-1:0]    vx_re,
    output wire [(1<<SMAX)*AW-1:0] vx_addr,
    input  wire [(1<<SMAX)*32-1:0] vx_q,
    output wire              tgo,
    output wire [3*NW+13*AW+13-1:0] tb,
    output wire [(1<<SMAX)*32-1:0] xl_d,
    input  wire [(G >> TCUT)*W*32-1:0] t_lvl,
    input  wire              fab_fault,
    input  wire              w_ok, emb_ok,
    input  wire              me_mem_ok,      // ME_STALL: every engine read presented now is served at the next edge
    output wire              me_clk_en,      // ME_STALL: this edge clocks the engine (pre-edge value)
    // -- partition ports (tools/qwen_missing/emit_partition.py) --
    output wire [1-1:0] po_me_clk,
    output wire [1-1:0] po_me_go,
    input  wire [1-1:0] pi_me_ready,
    input  wire [1-1:0] pi_me_idle,
    output wire [NW-1:0] po_me_i_nout,
    output wire [NW-1:0] po_me_i_tiles,
    output wire [NW-1:0] po_me_i_k,
    output wire [1-1:0] po_me_i_wsrc,
    output wire [AW-1:0] po_me_i_wbase,
    output wire [AW-1:0] po_me_i_ts,
    output wire [AW-1:0] po_me_i_ks,
    output wire [AW-1:0] po_me_i_js,
    output wire [AW-1:0] po_me_i_xbase,
    output wire [AW-1:0] po_me_i_xks,
    output wire [AW-1:0] po_me_i_xjs,
    output wire [AW-1:0] po_me_i_xcs,
    output wire [3-1:0] po_me_i_jsh,
    output wire [4-1:0] po_me_i_split,
    output wire [AW-1:0] po_me_i_wcs,
    output wire [1-1:0] po_me_i_round,
    output wire [AW-1:0] po_me_i_obase,
    output wire [AW-1:0] po_me_i_ots,
    output wire [AW-1:0] po_me_i_ojs,
    output wire [1-1:0] po_me_i_mmode,
    output wire [1-1:0] po_me_i_oen,
    output wire [1-1:0] po_me_i_amax,
    output wire [1-1:0] po_me_i_rmax,
    output wire [AW-1:0] po_me_i_mbase,
    input  wire [1-1:0] pi_me_mx_we,
    input  wire [1-1:0] pi_me_wrom_re,
    input  wire [AW-1:0] pi_me_wrom_addr,
    input  wire [(G >> SMIN)-1:0] pi_me_o_we,
    input  wire [NW-1:0] pi_me_am_idx,
    input  wire [32-1:0] pi_me_am_val,
    input  wire [1-1:0] pi_me_am_any,
    input  wire [16-1:0] pi_me_progress,
    input  wire [1-1:0] pi_me_fault,
    input  wire [1-1:0] pi_su_rt_active,
    input  wire [8-1:0] pi_su_rt_inflight,
    output wire [1-1:0] po_su_go,
    input  wire [1-1:0] pi_su_ready,
    input  wire [1-1:0] pi_su_idle,
    output wire [NW-1:0] po_su_i_nout,
    output wire [NW-1:0] po_su_i_nin,
    output wire [1-1:0] po_su_i_asrc,
    output wire [AW-1:0] po_su_i_abase,
    output wire [AW-1:0] po_su_i_aso,
    output wire [AW-1:0] po_su_i_asi,
    output wire [1-1:0] po_su_i_bsrc,
    output wire [AW-1:0] po_su_i_bbase,
    output wire [AW-1:0] po_su_i_bso,
    output wire [AW-1:0] po_su_i_bsi,
    output wire [1-1:0] po_su_i_csrc,
    output wire [AW-1:0] po_su_i_cbase,
    output wire [AW-1:0] po_su_i_cso,
    output wire [AW-1:0] po_su_i_csi,
    output wire [2-1:0] po_su_i_ma,
    output wire [2-1:0] po_su_i_mb,
    output wire [3-1:0] po_su_i_ad,
    output wire [3-1:0] po_su_i_sfu,
    output wire [1-1:0] po_su_i_mc,
    output wire [1-1:0] po_su_i_md,
    output wire [2-1:0] po_su_i_dst,
    output wire [AW-1:0] po_su_i_dbase,
    output wire [AW-1:0] po_su_i_dso,
    output wire [AW-1:0] po_su_i_dsi,
    output wire [2-1:0] po_su_i_red,
    output wire [1-1:0] po_su_i_redsq,
    output wire [AW-1:0] po_su_i_rbase,
    output wire [AW-1:0] po_su_i_rso,
    output wire [32-1:0] po_su_i_imm1,
    output wire [32-1:0] po_su_i_imm2,
    input  wire [SW-1:0] pi_su_va_re,
    input  wire [SW*AW-1:0] pi_su_va_addr,
    output wire [SW*32-1:0] po_su_va_q,
    input  wire [1-1:0] pi_su_wrom_re,
    input  wire [AW-1:0] pi_su_wrom_addr,
    input  wire [SW-1:0] pi_su_kv_we,
    input  wire [16-1:0] pi_su_progress,
    input  wire [16-1:0] pi_su_progress_rows,
    input  wire [1-1:0] pi_su_fault,
    output wire [1-1:0] po_su_asrc_raw,
    // -- redesign-qwen two-controller ports --
    input  wire [XW-1:0] x_oacc,          // other unit: ops accepted (snapshot)
    input  wire          x_oidle,
    input  wire [15:0]   x_oprog,
    input  wire [15:0]   x_orows,
    input  wire          x_ofin,          // ME side reached END (its fold final): SU side only
    input  wire [NW-1:0] x_fidx,
    input  wire [31:0]   x_fval,
    output wire          o_fin,
    output wire [NW-1:0] o_fidx,
    output wire [31:0]   o_fval
);
    // ---- inlined rtl/hdc/ot_hdc_isa.svh ----
// GENERATED by tools/hdc_isa.py -- do not edit.
// Field offsets of one HDC instruction word; see the tool for semantics.
// Included inside a module body.
localparam integer ISA_INSTR_BITS = 1024;
localparam integer O_UNIT = 0;
localparam integer W_UNIT = 2;
localparam integer O_BARRIER = 2;
localparam integer W_BARRIER = 1;
localparam integer O_CHASE = 3;
localparam integer W_CHASE = 1;
localparam integer O_CHASE_N = 4;
localparam integer W_CHASE_N = 16;
localparam integer O_WAIT_ME = 20;
localparam integer W_WAIT_ME = 1;
localparam integer O_WAIT_SU = 21;
localparam integer W_WAIT_SU = 1;
localparam integer O_CHASE_ROWS = 22;
localparam integer W_CHASE_ROWS = 1;
localparam integer O_ME_NOUT = 23;
localparam integer W_ME_NOUT = 16;
localparam integer O_ME_TILES = 39;
localparam integer W_ME_TILES = 16;
localparam integer O_ME_K = 55;
localparam integer W_ME_K = 16;
localparam integer O_ME_WSRC = 71;
localparam integer W_ME_WSRC = 1;
localparam integer O_ME_WBASE = 72;
localparam integer W_ME_WBASE = 24;
localparam integer O_ME_TS = 96;
localparam integer W_ME_TS = 24;
localparam integer O_ME_KS = 120;
localparam integer W_ME_KS = 24;
localparam integer O_ME_JS = 144;
localparam integer W_ME_JS = 24;
localparam integer O_ME_XBASE = 168;
localparam integer W_ME_XBASE = 24;
localparam integer O_ME_ROUND = 192;
localparam integer W_ME_ROUND = 1;
localparam integer O_ME_OBASE = 193;
localparam integer W_ME_OBASE = 24;
localparam integer O_ME_OEN = 217;
localparam integer W_ME_OEN = 1;
localparam integer O_ME_AMAX = 218;
localparam integer W_ME_AMAX = 1;
localparam integer O_ME_D_WBASE = 219;
localparam integer W_ME_D_WBASE = 3;
localparam integer O_ME_D_XBASE = 222;
localparam integer W_ME_D_XBASE = 3;
localparam integer O_ME_D_OBASE = 225;
localparam integer W_ME_D_OBASE = 3;
localparam integer O_ME_D_NOUT = 228;
localparam integer W_ME_D_NOUT = 3;
localparam integer O_ME_D_TILES = 231;
localparam integer W_ME_D_TILES = 3;
localparam integer O_ME_D_K = 234;
localparam integer W_ME_D_K = 3;
localparam integer O_ME_XKS = 237;
localparam integer W_ME_XKS = 24;
localparam integer O_ME_XJS = 261;
localparam integer W_ME_XJS = 24;
localparam integer O_ME_JSH = 285;
localparam integer W_ME_JSH = 3;
localparam integer O_ME_OTS = 288;
localparam integer W_ME_OTS = 24;
localparam integer O_ME_OJS = 312;
localparam integer W_ME_OJS = 24;
localparam integer O_ME_MMODE = 336;
localparam integer W_ME_MMODE = 1;
localparam integer O_ME_SPLIT = 337;
localparam integer W_ME_SPLIT = 4;
localparam integer O_ME_XCS = 341;
localparam integer W_ME_XCS = 24;
localparam integer O_ME_WCS = 365;
localparam integer W_ME_WCS = 24;
localparam integer O_ME_RMAX = 389;
localparam integer W_ME_RMAX = 1;
localparam integer O_ME_MBASE = 390;
localparam integer W_ME_MBASE = 24;
localparam integer O_SU_NOUT = 414;
localparam integer W_SU_NOUT = 16;
localparam integer O_SU_NIN = 430;
localparam integer W_SU_NIN = 16;
localparam integer O_SU_D_NIN = 446;
localparam integer W_SU_D_NIN = 3;
localparam integer O_A_SRC = 449;
localparam integer W_A_SRC = 1;
localparam integer O_A_BASE = 450;
localparam integer W_A_BASE = 24;
localparam integer O_A_SO = 474;
localparam integer W_A_SO = 24;
localparam integer O_A_SI = 498;
localparam integer W_A_SI = 24;
localparam integer O_A_D = 522;
localparam integer W_A_D = 3;
localparam integer O_B_SRC = 525;
localparam integer W_B_SRC = 1;
localparam integer O_B_BASE = 526;
localparam integer W_B_BASE = 24;
localparam integer O_B_SO = 550;
localparam integer W_B_SO = 24;
localparam integer O_B_SI = 574;
localparam integer W_B_SI = 24;
localparam integer O_B_D = 598;
localparam integer W_B_D = 3;
localparam integer O_C_SRC = 601;
localparam integer W_C_SRC = 1;
localparam integer O_C_BASE = 602;
localparam integer W_C_BASE = 24;
localparam integer O_C_SO = 626;
localparam integer W_C_SO = 24;
localparam integer O_C_SI = 650;
localparam integer W_C_SI = 24;
localparam integer O_C_D = 674;
localparam integer W_C_D = 3;
localparam integer O_MA = 677;
localparam integer W_MA = 2;
localparam integer O_MB = 679;
localparam integer W_MB = 2;
localparam integer O_AD = 681;
localparam integer W_AD = 3;
localparam integer O_SFU = 684;
localparam integer W_SFU = 3;
localparam integer O_MC = 687;
localparam integer W_MC = 1;
localparam integer O_MD = 688;
localparam integer W_MD = 1;
localparam integer O_DST = 689;
localparam integer W_DST = 2;
localparam integer O_D_BASE = 691;
localparam integer W_D_BASE = 24;
localparam integer O_D_SO = 715;
localparam integer W_D_SO = 24;
localparam integer O_D_SI = 739;
localparam integer W_D_SI = 24;
localparam integer O_D_D = 763;
localparam integer W_D_D = 3;
localparam integer O_RED = 766;
localparam integer W_RED = 2;
localparam integer O_R_BASE = 768;
localparam integer W_R_BASE = 24;
localparam integer O_R_SO = 792;
localparam integer W_R_SO = 24;
localparam integer O_RED_SQ = 816;
localparam integer W_RED_SQ = 1;
localparam integer O_IMM1 = 817;
localparam integer W_IMM1 = 32;
localparam integer O_IMM2 = 849;
localparam integer W_IMM2 = 32;
localparam integer O_ME_ROW0 = 881;
localparam integer W_ME_ROW0 = 16;
localparam integer O_ME_AMC = 897;
localparam integer W_ME_AMC = 1;

    localparam integer LW = $clog2(W);
    localparam integer LT = $clog2(W * IL);

    // -- sequencer ----------------------------------------------------------------
    localparam [1:0] S_IDLE = 0, S_DYN = 1, S_RUN = 2;
    localparam integer NFQ = 4;           // program words held or in flight
    reg [1:0]  st;
    reg [PAW-1:0] pc;                     // index of the instruction in NEXT
    reg [PAW-1:0] fpc;                    // next word to fetch
    reg [NW-1:0] tok_r, pos_r;
    reg [AW-1:0] dyn [0:7];
    wire [NW-1:0] dyn_tiles_zero, dyn_tiles_split;
    wire dyn_tiles_invalid;
    reg [INSTR_BITS-1:0] fq [0:NFQ-1];
    reg [1:0]  fq_rd, fq_wr;
    reg [2:0]  fq_n;
    reg        pend1;                     // a program read whose word arrives this cycle
    reg  [INSTR_BITS-1:0] hq;            // FQ_HEAD: registered head word
    reg                   hq_v;
    wire [INSTR_BITS-1:0] ir = (FQ_HEAD != 0) ? hq : fq[fq_rd]; // FIFO head: the word decode reads
    reg        nx_v;                      // NEXT holds a decoded instruction
    wire       me_go, su_go;
    wire       me_ready, me_idle, su_ready, su_idle;
    wire       me_fault, su_fault;
    wire [NW-1:0] am_idx;
    wire [31:0] am_val;
    wire       am_any;

    `define F(name) ir[O_``name +: W_``name]
    ot_hdc_dyn_ttiles #(.W(W),.G(G),.NW(NW)) u_dyn_tiles_zero (
        .pos(pos_r),.split_log2(4'd0),.rounds(dyn_tiles_zero),.invalid_split());
    ot_hdc_dyn_ttiles #(.W(W),.G(G),.NW(NW)) u_dyn_tiles_split (
        .pos(pos_r),.split_log2(`F(ME_SPLIT)),.rounds(dyn_tiles_split),
        .invalid_split(dyn_tiles_invalid));
    wire dyn_tiles_bad_instruction = load && `F(ME_D_TILES) == 3'd6 && dyn_tiles_invalid;

    // decoded, DYN-adjusted fields
    reg [1:0]    d_unit;
    reg          d_barrier;
    reg [NW-1:0] me_nout, me_tiles, me_k;
    reg          me_wsrc, me_round, me_oen, me_amax, me_mmode, d_chase, d_wait_me, d_wait_su, me_rmax, me_amc;
    reg [NW-1:0] me_row0;
    reg [AW-1:0] me_mbase;
    reg [15:0]   d_chase_n;
    reg [AW-1:0] me_wbase, me_ts, me_ks, me_js, me_xbase, me_obase, me_xks, me_xjs, me_ots, me_ojs;
    reg [2:0]    me_jsh;
    reg [3:0]    me_split;
    reg [AW-1:0] me_xcs, me_wcs;
    reg [NW-1:0] su_nout, su_nin;
    reg          a_src, b_src, c_src, mc;
    reg [AW-1:0] a_base, a_so, a_si, b_base, b_so, b_si, c_base, c_so, c_si;
    reg [AW-1:0] d_base, d_so, d_si, r_base, r_so;
    reg [1:0]    ma, mb, dst, red;
    reg [2:0]    sfu;
    reg          redsq, md;
    reg [2:0]    ad;
    reg [31:0]   imm1, imm2;

    wire [15:0] su_progress, me_progress, su_rows;
    reg          d_chase_rows;
    reg          me_kindk;
    wire me_en;
    wire unit_ready = (d_unit == 2'd1) ? (me_ready && me_en) :
                      (su_ready && (!KV_VEC_WRITE_BRIDGE || (su_idle && kv_write_drained)));
    //: KV_HBM: a KV op waits for the streamer; never on the cycle its
    //: descriptor is announced, when kv_ok may still describe the previous op.
    wire kv_gate = (KV_HBM == 0) || !(d_unit == 2'd1 && me_wsrc) || (kv_ok && !kvd_v);
    wire w_gate = (W_HBM == 0) || ((d_unit == 2'd1) ?
                  (me_wsrc || (w_ok && !wd_v)) : (!a_src || emb_ok));
    //: the units' idle and progress are registered and cleared on the edge
    //: that accepts an op, so a go needs no guard term here
    wire drained = me_idle && su_idle && (!KV_VEC_WRITE_BRIDGE || kv_write_drained);
    assign kv_write_flush = su_idle && !(|kv_we);
    //: A chasing op waits only until the OTHER unit's latest op has made
    //: chase_n progress.
    // redesign-qwen two controllers: own / other unit, the other side's snapshot, the dependency hold
    reg  [XW-1:0] o_cnt;                       // other-unit instructions passed so far
    wire own = (d_unit == OWN[1:0]);
    wire oth = (d_unit != 2'd0) && !own;
    wire [XW-1:0] o_dif = x_oacc - o_cnt;
    wire osync = (o_dif == {XW{1'b0}});        // the other unit accepted exactly its earlier ops
    wire opast = !osync && !o_dif[XW-1];       // ... and the one at NEXT
    wire own_idle = (OWN == 1) ? me_idle : su_idle;
    wire o_drained = osync && x_oidle;
    wire x_drained = own_idle && o_drained && (!KV_VEC_WRITE_BRIDGE || kv_write_drained);
    wire [15:0] x_och = (OWN == 1) ? (d_chase_rows ? x_orows : x_oprog) : x_oprog;
    wire chased = osync && (x_och >= d_chase_n);
    wire wait_o = (OWN == 1) ? d_wait_su : d_wait_me;
    wire wait_u = (OWN == 1) ? d_wait_me : d_wait_su;
    wire xdep_ok = (XMUT == 1 && OWN == 1) ? 1'b1 :
                   (d_barrier ? x_drained : ((!d_chase || chased) && (!wait_u || own_idle) && (!wait_o || o_drained)));
    wire odep = (XMUT == 2) ? 1'b0 : (d_barrier || d_chase || ((OWN == 1) ? d_wait_me : d_wait_su));
    wire skip = (st == S_RUN) && nx_v && oth && (!odep || opast);
    //: issue NEXT this cycle; the unit latches its fields on this edge
    wire issue = (st == S_RUN) && nx_v && own && xdep_ok
                 && unit_ready && kv_gate && w_gate;
    assign me_go = issue && (d_unit == 2'd1);
    assign su_go = issue && (d_unit == 2'd2);
    wire fin = (st == S_RUN) && nx_v && (d_unit == 2'd0) && x_drained && ((OWN == 1) || x_ofin);
    reg fin_seen;                              // this controller reached END in this run
    always @(posedge clk or negedge rst_n)
        if (!rst_n) fin_seen <= 1'b0;
        else if (start && st == S_IDLE) fin_seen <= 1'b0;
        else if (fin) fin_seen <= 1'b1;
    assign o_fin = fin_seen;
    always @(posedge clk or negedge rst_n)
        if (!rst_n) o_cnt <= {XW{1'b0}};
        else if (skip) o_cnt <= o_cnt + 1'b1;
    //: decode the FIFO head into NEXT when NEXT is empty or issuing
    wire load = (st == S_RUN) && ((FQ_HEAD != 0) ? hq_v : (fq_n != 0)) && (!nx_v || issue || skip);
    // FQ_HEAD: the FIFO pops into hq when hq is empty or being loaded into NEXT
    wire hq_fill = (FQ_HEAD != 0) && (st == S_RUN) && (fq_n != 0) && (!hq_v || load);
    wire fq_pop = (FQ_HEAD != 0) ? hq_fill : load;
    wire push = (st == S_RUN) && pend1;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            st <= S_IDLE; pc <= 0; fpc <= 0; done <= 1'b0; prog_re <= 1'b0; pend1 <= 1'b0;
            fq_rd <= 0; fq_wr <= 0; fq_n <= 0; nx_v <= 1'b0; hq_v <= 1'b0;
            cycles <= 0; next_token <= 0;
        end else begin
            if (st != S_IDLE) cycles <= cycles + 1;
            pend1 <= prog_re && (st != S_IDLE);
            prog_re <= 1'b0;
            case (st)
                S_IDLE: if (start) begin
                    tok_r <= token; pos_r <= pos; pc <= 0; fpc <= 0; done <= 1'b0; cycles <= 0;
                    fq_rd <= 0; fq_wr <= 0; fq_n <= 0; nx_v <= 1'b0; pend1 <= 1'b0; hq_v <= 1'b0;
                    st <= S_DYN;
                end
                S_DYN: st <= S_RUN;
                S_RUN: begin
                    // fetch: one word a cycle while fewer than NFQ are held or in flight
                    if ({1'b0, fq_n} + ((FQ_HEAD != 0) ? hq_v : 1'b0) + prog_re + pend1 < NFQ) begin
                        prog_re <= 1'b1; prog_addr <= fpc; fpc <= fpc + 1'b1;
                    end
                    if (push) begin fq[fq_wr] <= prog_q; fq_wr <= fq_wr + 1'b1; end
                    if (fq_pop) fq_rd <= fq_rd + 1'b1;
                    fq_n <= fq_n + (push ? 3'd1 : 3'd0) - (fq_pop ? 3'd1 : 3'd0);
                    if (hq_fill) begin hq <= fq[fq_rd]; hq_v <= 1'b1; end
                    else if (load && FQ_HEAD != 0) hq_v <= 1'b0;
                    if (issue || skip) pc <= pc + 1'b1;
                    if (load) nx_v <= 1'b1;
                    else if (issue || skip) nx_v <= 1'b0;
                    if (fin) begin
                        done <= 1'b1; next_token <= (OWN == 2) ? x_fidx : fin_idx; next_val <= (OWN == 2) ? x_fval : fin_val; st <= S_IDLE; nx_v <= 1'b0;
                        prog_re <= 1'b0;
                    end
                end
                default: st <= S_IDLE;
            endcase
        end
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin kvd_v <= 1'b0; wd_v <= 1'b0; end
        else begin
            kvd_v <= load && ir[O_UNIT +: W_UNIT] == 2'd1 && ir[O_ME_WSRC];
            wd_v <= (W_HBM != 0) && load && ir[O_UNIT +: W_UNIT] == 2'd1 && !ir[O_ME_WSRC];
        end
    end
    assign kvd_wbase = me_wbase; assign kvd_ts = me_ts; assign kvd_ks = me_ks; assign kvd_js = me_js;
    assign kvd_wcs = me_wcs; assign kvd_split = me_split;
    assign kvd_jsh = me_jsh; assign kvd_tiles = me_tiles; assign kvd_k = me_k; assign kvd_nout = me_nout;
    assign kvd_kindk = me_kindk; assign kvd_pos = pos_r;
    assign wd_wbase = me_wbase; assign wd_tiles = me_tiles; assign wd_k = me_k;
    assign wd_sbase = (INT8_WEIGHT != 0 && INT8_SCALE_WCS_BASE != 0) ? me_wcs : me_wbase;
    assign wd_nout = me_nout; // useful BF16 row scales to preload from HBM

    // The chunked weight program divides lm_head into bounded streams. Fold
    // each completed chunk's argmax before issuing the next one. The final
    // chunk remains in u_me and is included exactly once at END.
    function automatic [31:0] okey(input [31:0] v);
        okey = v[31] ? ~v : {1'b1, v[30:0]};
    endfunction
    reg run_any;
    reg [31:0] run_key,run_val;
    reg [NW-1:0] run_idx,last_row0;
    wire am_wins = am_any && (!run_any || okey(am_val) > run_key);
    wire [NW-1:0] fin_idx = am_wins ? am_idx + last_row0 : run_idx;
    wire [31:0] fin_val = am_wins ? am_val : run_val;
    assign o_fidx = fin_idx; assign o_fval = fin_val;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin run_any<=1'b0; last_row0<=0; end
        else if (start && st==S_IDLE) begin run_any<=1'b0; last_row0<=0; end
        else if (me_go && me_amax) begin
            last_row0<=me_row0;
            if (!me_amc) run_any<=1'b0;
            else if (am_wins) begin
                run_any<=1'b1; run_key<=okey(am_val);
                run_idx<=am_idx+last_row0; run_val<=am_val;
            end
        end
    end

    // DYN offsets derived once per token.
    always @(posedge clk) if (st == S_DYN) begin
        dyn[0] <= 0;
        dyn[1] <= tok_r * HID;
        dyn[2] <= pos_r * HALF;
        dyn[3] <= (pos_r >> LW) * (HD * W) + (pos_r & (W - 1));
        dyn[4] <= pos_r * HD;
        dyn[5] <= pos_r + 1;
        dyn[6] <= dyn_tiles_zero;                 // rounds of G position tiles (split 0)
        dyn[7] <= 0;
    end

    // Decode: every base and count may add one DYN value.
    always @(posedge clk) if (load) begin
        d_unit <= `F(UNIT); d_barrier <= `F(BARRIER);
        me_nout <= `F(ME_NOUT) + dyn[`F(ME_D_NOUT)];
        //: DYN_TTILES counts exact rounds of G/S position tiles (S = 2^split)
        me_tiles <= `F(ME_TILES) + ((`F(ME_D_TILES) == 3'd6) ? dyn_tiles_split
                                                               : dyn[`F(ME_D_TILES)]);
        me_k <= `F(ME_K) + dyn[`F(ME_D_K)];
        me_kindk <= (`F(ME_D_TILES) == 3'd6);        // DYN_TTILES: rounds of position tiles
        me_wsrc <= `F(ME_WSRC); me_round <= `F(ME_ROUND); me_oen <= `F(ME_OEN); me_amax <= `F(ME_AMAX);
        me_amc <= `F(ME_AMC);
        me_row0 <= `F(ME_ROW0) |
                   ((QWEN_FULLSHAPE != 0) ?
                    ({{(NW-2){1'b0}}, ir[O_ME_ROW0+W_ME_ROW0+W_ME_AMC +: 2]} << 16) : '0);
        me_wbase <= `F(ME_WBASE) + dyn[`F(ME_D_WBASE)];
        me_ts <= `F(ME_TS); me_ks <= `F(ME_KS); me_js <= `F(ME_JS);
        me_xbase <= `F(ME_XBASE) + dyn[`F(ME_D_XBASE)];
        me_obase <= `F(ME_OBASE) + dyn[`F(ME_D_OBASE)];
        me_xks <= `F(ME_XKS); me_xjs <= `F(ME_XJS); me_jsh <= `F(ME_JSH);
        me_ots <= `F(ME_OTS); me_ojs <= `F(ME_OJS); me_mmode <= `F(ME_MMODE);
        d_chase <= `F(CHASE); d_chase_n <= `F(CHASE_N); d_wait_me <= `F(WAIT_ME); d_wait_su <= `F(WAIT_SU);
        d_chase_rows <= `F(CHASE_ROWS);
        me_split <= `F(ME_SPLIT); me_xcs <= `F(ME_XCS); me_wcs <= `F(ME_WCS);
        me_rmax <= `F(ME_RMAX); me_mbase <= `F(ME_MBASE);
        su_nout <= `F(SU_NOUT);
        su_nin <= `F(SU_NIN) + dyn[`F(SU_D_NIN)];
        a_src <= `F(A_SRC); a_base <= `F(A_BASE) + dyn[`F(A_D)]; a_so <= `F(A_SO); a_si <= `F(A_SI);
        b_src <= `F(B_SRC); b_base <= `F(B_BASE) + dyn[`F(B_D)]; b_so <= `F(B_SO); b_si <= `F(B_SI);
        c_src <= `F(C_SRC); c_base <= `F(C_BASE) + dyn[`F(C_D)]; c_so <= `F(C_SO); c_si <= `F(C_SI);
        ma <= `F(MA); mb <= `F(MB); ad <= `F(AD); sfu <= `F(SFU); mc <= `F(MC); md <= `F(MD);
        dst <= `F(DST); d_base <= `F(D_BASE) + dyn[`F(D_D)]; d_so <= `F(D_SO); d_si <= `F(D_SI);
        red <= `F(RED); redsq <= `F(RED_SQ); r_base <= `F(R_BASE); r_so <= `F(R_SO);
        imm1 <= `F(IMM1); imm2 <= `F(IMM2);
    end
    `undef F

    // -- units ----------------------------------------------------------------------
    wire me_wrom_re, su_wrom_re;
    wire [AW-1:0] me_wrom_addr, su_wrom_addr;
    wire [SW-1:0] su_va_re;
    wire [SW*AW-1:0] su_va_addr;
    wire [SW*32-1:0] su_va_q;
    reg embed_active, embed_scale_pending;
    reg [15:0] embed_scale_hold;
    reg [SW-1:0] embed_sel;
    reg [SW*$clog2(EMB_CODE_LANES)-1:0] embed_lanes;
    wire [SW-1:0] embed_faults;
    assign embed_scale_re = (INT8_EMBED != 0) && start && st == S_IDLE;
    assign embed_scale_addr = token;
    assign embed_code_re = (INT8_EMBED != 0) && (|(su_va_re & {SW{embed_active}}));
    // The stream's element address is AW bits; token*HID wraps for vocab
    // rows >= 2^(AW-log2(HID)). Recover the in-row offset from those low
    // bits, then form the code-word address from the full NW-bit token.
    assign embed_code_addr = (QWEN_FULLSHAPE != 0) ?
        ((tok_r * (HID / EMB_CODE_LANES)) +
         (((su_va_addr[0 +: AW] - EMB_ADDR_BASE) & (HID - 1)) /
          EMB_CODE_LANES)) :
        ((su_va_addr[0 +: AW] - EMB_ADDR_BASE) >> $clog2(EMB_CODE_LANES));
    assign va_re = su_va_re & ~({SW{(INT8_EMBED != 0) && embed_active}});
    assign va_addr = su_va_addr;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            embed_active <= 1'b0;
            embed_scale_pending <= 1'b0;
            embed_sel <= 0;
        end else begin
            if (su_go) embed_active <= (INT8_EMBED != 0) && a_src;
            embed_scale_pending <= embed_scale_re;
            embed_sel <= su_va_re & {SW{(INT8_EMBED != 0) && embed_active}};
        end
    end
    always @(posedge clk) begin
        if (embed_scale_pending) embed_scale_hold <= embed_scale_q;
    end
    genvar el;
    generate if (INT8_EMBED != 0) begin : g_int8_embed
    for (el = 0; el < SW; el = el + 1) begin : g_embed_decode
        localparam integer ELI = $clog2(EMB_CODE_LANES);
        always @(posedge clk) embed_lanes[el*ELI +: ELI] <= su_va_addr[el*AW +: ELI];
        wire [31:0] decoded;
        wire bad;
        ot_hdc_qwen_int8_embed_decode u_decode (
            .code(embed_code_q[8*embed_lanes[el*ELI +: ELI] +: 8]),
            .scale(embed_scale_hold), .value(decoded), .fault(bad));
        assign su_va_q[el*32 +: 32] = embed_sel[el] ? decoded : va_q[el*32 +: 32];
        assign embed_faults[el] = embed_sel[el] && bad;
    end
    end else begin : g_plain_embed
        assign su_va_q = va_q;
        assign embed_faults = 0;
    end endgenerate
    // -- engine clock enable (ME_STALL) ------------------------------------------
    //: rst_n forces the enable so the gated registers see reset edges (see
    //: ot_hdc_cg).  The enable is combinational from the supply's view of the
    //: engine's registered requests; it never depends on me_go.
    wire me_wake = (st == S_RUN) && nx_v && (d_unit == 2'd1);
    assign me_en = !rst_n || (((ME_STALL == 0) || me_mem_ok) &&
                              ((ME_IDLE_GATE == 0) || !me_idle || me_wake));
    assign me_clk_en = me_en;
    wire me_clk;
    generate if (ME_STALL != 0 || ME_IDLE_GATE != 0) begin : g_me_cg
        ot_hdc_cg u_me_cg (.clk(clk), .en(me_en), .gclk(me_clk));
    end else begin : g_me_clk
        assign me_clk = clk;
    end endgenerate
    wire [(G >> SMIN)-1:0] me_o_we;
    wire         me_mx_we;
    //: a held engine keeps its write strobes high; write once per engine edge
    assign vw_me_we = me_o_we & {(G >> SMIN){me_en}};
    assign vw_mx_we = me_mx_we & me_en;
    // ---- matrix engine spine (die master qfd_sp_tree_top): ports ----
    assign po_me_clk = me_clk;
    assign po_me_go = me_go;
    assign me_ready = pi_me_ready;
    assign me_idle = pi_me_idle;
    assign po_me_i_nout = me_nout;
    assign po_me_i_tiles = me_tiles;
    assign po_me_i_k = me_k;
    assign po_me_i_wsrc = me_wsrc;
    assign po_me_i_wbase = me_wbase;
    assign po_me_i_ts = me_ts;
    assign po_me_i_ks = me_ks;
    assign po_me_i_js = me_js;
    assign po_me_i_xbase = me_xbase;
    assign po_me_i_xks = me_xks;
    assign po_me_i_xjs = me_xjs;
    assign po_me_i_xcs = me_xcs;
    assign po_me_i_jsh = me_jsh;
    assign po_me_i_split = me_split;
    assign po_me_i_wcs = me_wcs;
    assign po_me_i_round = me_round;
    assign po_me_i_obase = me_obase;
    assign po_me_i_ots = me_ots;
    assign po_me_i_ojs = me_ojs;
    assign po_me_i_mmode = me_mmode;
    assign po_me_i_oen = me_oen;
    assign po_me_i_amax = me_amax;
    assign po_me_i_rmax = me_rmax;
    assign po_me_i_mbase = me_mbase;
    assign me_mx_we = pi_me_mx_we;
    assign vw_mx_addr = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign vw_mx_mask = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign vw_mx_data = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign me_wrom_re = pi_me_wrom_re;
    assign me_wrom_addr = pi_me_wrom_addr;
    assign scale_re = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign scale_gre = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign scale_addr = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign kv_re = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign vx_re = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign vx_addr = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign tgo = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign tb = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign xl_d = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign me_ov = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign me_o_we = pi_me_o_we;
    assign vw_me_addr = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign vw_me_mask = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign vw_me_data = '0;   // driven by the spine in ot_qwen_rom_core_part
    assign am_idx = pi_me_am_idx;
    assign am_val = pi_me_am_val;
    assign am_any = pi_me_am_any;
    assign me_progress = pi_me_progress;
    assign me_fault = pi_me_fault;

    wire       su_active;             // observation (test benches)
    wire [7:0] su_inflight;
    // ---- vector stream unit (die master qfd_sp_su64_sfu): ports (SU_VEC = 1 only) ----
    assign po_su_asrc_raw = a_src;   // split-exact: the embedding selector travels with the go
    assign su_active = pi_su_rt_active;
    assign su_inflight = pi_su_rt_inflight;
    assign po_su_go = su_go;
    assign su_ready = pi_su_ready;
    assign su_idle = pi_su_idle;
    assign po_su_i_nout = su_nout;
    assign po_su_i_nin = su_nin;
    assign po_su_i_asrc = (INT8_EMBED != 0) ? 1'b0 : a_src;
    assign po_su_i_abase = a_base;
    assign po_su_i_aso = a_so;
    assign po_su_i_asi = a_si;
    assign po_su_i_bsrc = b_src;
    assign po_su_i_bbase = b_base;
    assign po_su_i_bso = b_so;
    assign po_su_i_bsi = b_si;
    assign po_su_i_csrc = c_src;
    assign po_su_i_cbase = c_base;
    assign po_su_i_cso = c_so;
    assign po_su_i_csi = c_si;
    assign po_su_i_ma = ma;
    assign po_su_i_mb = mb;
    assign po_su_i_ad = ad;
    assign po_su_i_sfu = sfu;
    assign po_su_i_mc = mc;
    assign po_su_i_md = md;
    assign po_su_i_dst = dst;
    assign po_su_i_dbase = d_base;
    assign po_su_i_dso = d_so;
    assign po_su_i_dsi = d_si;
    assign po_su_i_red = red;
    assign po_su_i_redsq = redsq;
    assign po_su_i_rbase = r_base;
    assign po_su_i_rso = r_so;
    assign po_su_i_imm1 = imm1;
    assign po_su_i_imm2 = imm2;
    assign su_va_re = pi_su_va_re;
    assign su_va_addr = pi_su_va_addr;
    assign po_su_va_q = su_va_q;
    assign vb_re = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign vb_addr = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign vc_re = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign vc_addr = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign su_wrom_re = pi_su_wrom_re;
    assign su_wrom_addr = pi_su_wrom_addr;
    assign crom_re = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign crom_addr = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign vw_su_we = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign vw_su_addr = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign vw_su_data = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign kv_we = pi_su_kv_we;   // also read by the controller (kv_write_flush)
    assign kv_waddr = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign kv_wdata = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign vw_rd_we = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign vw_rd_addr = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign vw_rd_data = '0;   // driven by the stream unit in ot_qwen_rom_core_part
    assign su_progress = pi_su_progress;
    assign su_rows = pi_su_progress_rows;
    assign su_fault = pi_su_fault;

    // The embedding read is the only stream use of the weight ROM; a barrier
    // keeps it apart from matrix-vector reads.
    assign wrom_re = ((INT8_WEIGHT != 0) ? 1'b0 : me_wrom_re) |
                     ((INT8_EMBED != 0) ? 1'b0 : su_wrom_re);
    assign int8_wrom_re = (INT8_WEIGHT != 0) ? me_wrom_re : 1'b0;
    assign int8_wrom_addr = me_wrom_addr;
    assign wrom_su = su_wrom_re;
    assign wrom_addr = su_wrom_re ? su_wrom_addr : me_wrom_addr;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) fault <= 1'b0;
        else if (start && st == S_IDLE) fault <= 1'b0;
        else if (me_fault || su_fault || (|embed_faults) || dyn_tiles_bad_instruction) fault <= 1'b1;
    end
endmodule

`timescale 1ns/1ps
// GENERATED by tools/redesign_qwen/split_ctrl.py emit_tt_ctlm(): die master qfd_tt_ctlm -- the tree-top control
// tile with the ME-side controller inside (see the comment above emit_tt_ctlm).
module ot_qfd_tt_ctlm #(
    parameter integer DCU_M = 2, parameter integer DUC_M = 2,   // in-tile issue / status stations
    parameter integer XW = 24, parameter integer IS = 1, parameter integer OS = 1
) (
    input  wire clk, input wire rst_n,
    // token start, program writes (the program-store copy), the SU snapshot, KV / supply readiness
    input  wire h_start, input wire [18-1:0] token, input wire [18-1:0] pos, input wire [11:0] prog_base,
    input  wire pw_v, input wire [9:0] pw_addr, input wire [63:0] pw_data,
    input  wire [XW-1:0] x_oacc, input wire x_oidle, input wire [15:0] x_oprog, input wire [15:0] x_orows,
    input  wire kv_ok, input wire kv_write_drained, input wire me_mem_ok,
    // the ME snapshot, the KV descriptor, the engine clock enable
    output wire [XW-1:0] me_acc_o, output wire me_idle_o, output wire [15:0] me_prog_o, output wire m_fin_o,
    output wire [18-1:0] m_fidx_o, output wire [31:0] m_fval_o,
    output wire kvd_v, output wire [24-1:0] kvd_wbase, kvd_ts, kvd_ks, kvd_js, kvd_wcs, output wire [3:0] kvd_split,
    output wire [2:0] kvd_jsh, output wire [18-1:0] kvd_tiles, kvd_k, kvd_nout, output wire kvd_kindk,
    output wire [18-1:0] kvd_pos, output wire me_clk_en, output wire c_fault,
    // ot_qfd_tt_ctl's non-issue ports
    input  wire up_fault, input wire [15:0] land_cnt,
    output wire scale_re, output wire [48-1:0] scale_gre, output wire [48*24-1:0] scale_addr,
    input  wire x_rdy, output wire x_dv, output wire [24-1:0] x_dc, x_dcs, output wire [3:0] x_dsp,
    output wire [13:0] t_sel_e, t_tv_e, input wire [16-1:0] tr_fault,
    output wire p_v_e2, output wire [113-1:0] p_f_e2, input wire [12*51-1:0] p_am,
    input  wire [12-1:0] p_fault, input wire fab_fault,
    output wire ov, output wire mx_we, output wire [24-1:0] mx_addr, output wire [16-1:0] mx_mask,
    output wire [16*32-1:0] mx_data
);
    wire rs;
    ot_qfd_rst_stn #(.D(IS)) u_rs (.clk(clk), .rst_n(rst_n), .rst_q(rs));
    // die-facing input pin stations (registered boundary); kv_ok / kv_write_drained / me_mem_ok stay direct (readiness
    // the controller pairs with its own same-edge state, and the ICG enable path)
    wire q_h_start; wire [18-1:0] q_token, q_pos; wire [11:0] q_prog_base; wire q_pw_v; wire [9:0] q_pw_addr; wire [63:0] q_pw_data;
    wire [XW-1:0] q_x_oacc; wire q_x_oidle; wire [15:0] q_x_oprog, q_x_orows;
    ot_hdc_delay #(.W(3), .D(IS), .RESET(1)) u_is1 (.clk(clk), .rst_n(rst_n), .d({h_start, pw_v, x_oidle}), .q({q_h_start, q_pw_v, q_x_oidle}));
    ot_hdc_delay #(.W(2*18 + 12 + 10 + 64 + XW + 32), .D(IS)) u_isd (.clk(clk), .rst_n(rst_n),
        .d({token, pos, prog_base, pw_addr, pw_data, x_oacc, x_oprog, x_orows}),
        .q({q_token, q_pos, q_prog_base, q_pw_addr, q_pw_data, q_x_oacc, q_x_oprog, q_x_orows}));
    // program-store copy (the sequencer master's semantics)
    wire prog_re; wire [11:0] prog_addr; reg [1023:0] prog_q; reg [1023:0] prog_mem [0:63];
    wire [11:0] prog_a = q_prog_base + prog_addr;
    always @(posedge clk) begin
        if (q_pw_v) prog_mem[q_pw_addr[9:4]][q_pw_addr[3:0]*64 +: 64] <= q_pw_data;
        if (prog_re) prog_q <= (prog_a < 64) ? prog_mem[prog_a[5:0]] : 1024'd0;
    end
    wire [1-1:0] c_me_clk, u_me_clk;
    wire [1-1:0] c_me_go, u_me_go;
    wire [1-1:0] c_me_ready, u_me_ready;
    wire [1-1:0] c_me_idle, u_me_idle;
    wire [18-1:0] c_me_i_nout, u_me_i_nout;
    wire [18-1:0] c_me_i_tiles, u_me_i_tiles;
    wire [18-1:0] c_me_i_k, u_me_i_k;
    wire [1-1:0] c_me_i_wsrc, u_me_i_wsrc;
    wire [24-1:0] c_me_i_wbase, u_me_i_wbase;
    wire [24-1:0] c_me_i_ts, u_me_i_ts;
    wire [24-1:0] c_me_i_ks, u_me_i_ks;
    wire [24-1:0] c_me_i_js, u_me_i_js;
    wire [24-1:0] c_me_i_xbase, u_me_i_xbase;
    wire [24-1:0] c_me_i_xks, u_me_i_xks;
    wire [24-1:0] c_me_i_xjs, u_me_i_xjs;
    wire [24-1:0] c_me_i_xcs, u_me_i_xcs;
    wire [3-1:0] c_me_i_jsh, u_me_i_jsh;
    wire [4-1:0] c_me_i_split, u_me_i_split;
    wire [24-1:0] c_me_i_wcs, u_me_i_wcs;
    wire [1-1:0] c_me_i_round, u_me_i_round;
    wire [24-1:0] c_me_i_obase, u_me_i_obase;
    wire [24-1:0] c_me_i_ots, u_me_i_ots;
    wire [24-1:0] c_me_i_ojs, u_me_i_ojs;
    wire [1-1:0] c_me_i_mmode, u_me_i_mmode;
    wire [1-1:0] c_me_i_oen, u_me_i_oen;
    wire [1-1:0] c_me_i_amax, u_me_i_amax;
    wire [1-1:0] c_me_i_rmax, u_me_i_rmax;
    wire [24-1:0] c_me_i_mbase, u_me_i_mbase;
    wire [1-1:0] c_me_mx_we, u_me_mx_we;
    wire [1-1:0] c_me_wrom_re, u_me_wrom_re;
    wire [24-1:0] c_me_wrom_addr, u_me_wrom_addr;
    wire [(6144 >> 7)-1:0] c_me_o_we, u_me_o_we;
    wire [18-1:0] c_me_am_idx, u_me_am_idx;
    wire [32-1:0] c_me_am_val, u_me_am_val;
    wire [1-1:0] c_me_am_any, u_me_am_any;
    wire [16-1:0] c_me_progress, u_me_progress;
    wire [1-1:0] c_me_fault, u_me_fault;
    wire s_me_ready, s_me_idle; wire [15:0] s_me_progress; wire m_fin; wire [18-1:0] m_fidx; wire [31:0] m_fval;
    ot_qwen_rom_core_ctrl_x #(.OWN(1), .XW(XW), .XMUT(0), .W(16), .G(6144), .AW(24), .NW(18), .PAW(12), .SU_VEC(1), .SW(64), .LV(7), .KV_FP8(1), .INT8_WEIGHT(1), .INT8_SCALE_WCS_BASE(1), .INT8_EMBED(1), .QWEN_FULLSHAPE(1), .HID(4096), .HALF(64), .HD(128), .EMB_CODE_LANES(64), .EMB_ADDR_BASE(0), .KV_HBM(1), .KV_VEC_WRITE_BRIDGE(1), .ME_STALL(1), .ME_IDLE_GATE(1), .SMIN(7), .SMAX(11), .TCUT(7), .FQ_HEAD(1)) u_ctrl_me (
        .clk(clk),
        .rst_n(rs),
        .start(q_h_start),
        .token(q_token),
        .pos(q_pos),
        .done(),
        .next_token(),
        .next_val(),
        .cycles(),
        .fault(c_fault),
        .prog_re(prog_re),
        .prog_addr(prog_addr),
        .prog_q(prog_q),
        .wrom_re(),
        .wrom_addr(),
        .wrom_q('0),
        .int8_wrom_re(),
        .int8_wrom_addr(),
        .scale_re(),
        .scale_gre(),
        .scale_addr(),
        .scale_q('0),
        .embed_code_re(),
        .embed_code_addr(),
        .embed_code_q('0),
        .embed_scale_re(),
        .embed_scale_addr(),
        .embed_scale_q('0),
        .crom_re(),
        .crom_addr(),
        .crom_q('0),
        .kv_re(),
        .kv_we(),
        .kv_waddr(),
        .kv_wdata(),
        .kv_write_drained(kv_write_drained),
        .kv_write_flush(),
        .va_re(),
        .va_addr(),
        .va_q('0),
        .vb_re(),
        .vb_addr(),
        .vb_q('0),
        .vc_re(),
        .vc_addr(),
        .vc_q('0),
        .vw_me_we(),
        .vw_me_addr(),
        .vw_me_mask(),
        .vw_me_data(),
        .vw_su_we(),
        .vw_su_addr(),
        .vw_su_data(),
        .vw_rd_we(),
        .vw_rd_addr(),
        .vw_rd_data(),
        .vw_mx_we(),
        .vw_mx_addr(),
        .vw_mx_mask(),
        .vw_mx_data(),
        .me_ov(),
        .kvd_v(kvd_v),
        .kvd_wbase(kvd_wbase),
        .kvd_ts(kvd_ts),
        .kvd_ks(kvd_ks),
        .kvd_js(kvd_js),
        .kvd_wcs(kvd_wcs),
        .kvd_split(kvd_split),
        .kvd_jsh(kvd_jsh),
        .kvd_tiles(kvd_tiles),
        .kvd_k(kvd_k),
        .kvd_nout(kvd_nout),
        .kvd_kindk(kvd_kindk),
        .kvd_pos(kvd_pos),
        .kv_ok(kv_ok),
        .wrom_su(),
        .wd_v(),
        .wd_wbase(),
        .wd_sbase(),
        .wd_tiles(),
        .wd_k(),
        .wd_nout(),
        .vx_re(),
        .vx_addr(),
        .vx_q('0),
        .tgo(),
        .tb(),
        .xl_d(),
        .t_lvl('0),
        .fab_fault(1'b0),
        .w_ok(1'b1),
        .emb_ok(1'b1),
        .me_mem_ok(me_mem_ok),
        .me_clk_en(me_clk_en),
        .po_me_clk(c_me_clk),
        .po_me_go(c_me_go),
        .pi_me_ready(s_me_ready),
        .pi_me_idle(s_me_idle),
        .po_me_i_nout(c_me_i_nout),
        .po_me_i_tiles(c_me_i_tiles),
        .po_me_i_k(c_me_i_k),
        .po_me_i_wsrc(c_me_i_wsrc),
        .po_me_i_wbase(c_me_i_wbase),
        .po_me_i_ts(c_me_i_ts),
        .po_me_i_ks(c_me_i_ks),
        .po_me_i_js(c_me_i_js),
        .po_me_i_xbase(c_me_i_xbase),
        .po_me_i_xks(c_me_i_xks),
        .po_me_i_xjs(c_me_i_xjs),
        .po_me_i_xcs(c_me_i_xcs),
        .po_me_i_jsh(c_me_i_jsh),
        .po_me_i_split(c_me_i_split),
        .po_me_i_wcs(c_me_i_wcs),
        .po_me_i_round(c_me_i_round),
        .po_me_i_obase(c_me_i_obase),
        .po_me_i_ots(c_me_i_ots),
        .po_me_i_ojs(c_me_i_ojs),
        .po_me_i_mmode(c_me_i_mmode),
        .po_me_i_oen(c_me_i_oen),
        .po_me_i_amax(c_me_i_amax),
        .po_me_i_rmax(c_me_i_rmax),
        .po_me_i_mbase(c_me_i_mbase),
        .pi_me_mx_we('0),
        .pi_me_wrom_re(c_me_wrom_re),
        .pi_me_wrom_addr(c_me_wrom_addr),
        .pi_me_o_we('0),
        .pi_me_am_idx(c_me_am_idx),
        .pi_me_am_val(c_me_am_val),
        .pi_me_am_any(c_me_am_any),
        .pi_me_progress(s_me_progress),
        .pi_me_fault(c_me_fault),
        .pi_su_rt_active('0),
        .pi_su_rt_inflight('0),
        .po_su_go(),
        .pi_su_ready('0),
        .pi_su_idle('0),
        .po_su_i_nout(),
        .po_su_i_nin(),
        .po_su_i_asrc(),
        .po_su_i_abase(),
        .po_su_i_aso(),
        .po_su_i_asi(),
        .po_su_i_bsrc(),
        .po_su_i_bbase(),
        .po_su_i_bso(),
        .po_su_i_bsi(),
        .po_su_i_csrc(),
        .po_su_i_cbase(),
        .po_su_i_cso(),
        .po_su_i_csi(),
        .po_su_i_ma(),
        .po_su_i_mb(),
        .po_su_i_ad(),
        .po_su_i_sfu(),
        .po_su_i_mc(),
        .po_su_i_md(),
        .po_su_i_dst(),
        .po_su_i_dbase(),
        .po_su_i_dso(),
        .po_su_i_dsi(),
        .po_su_i_red(),
        .po_su_i_redsq(),
        .po_su_i_rbase(),
        .po_su_i_rso(),
        .po_su_i_imm1(),
        .po_su_i_imm2(),
        .pi_su_va_re('0),
        .pi_su_va_addr('0),
        .po_su_va_q(),
        .pi_su_wrom_re('0),
        .pi_su_wrom_addr('0),
        .pi_su_kv_we('0),
        .pi_su_progress('0),
        .pi_su_progress_rows('0),
        .pi_su_fault('0),
        .po_su_asrc_raw(),
        .x_oacc(q_x_oacc),
        .x_oidle(q_x_oidle),
        .x_oprog(q_x_oprog),
        .x_orows(q_x_orows),
        .x_ofin(1'b1),
        .x_fidx('0),
        .x_fval('0),
        .o_fin(m_fin),
        .o_fidx(m_fidx),
        .o_fval(m_fval));
    ot_qfd_issue_shell #(.RT_ME(DCU_M + DUC_M), .RT_SU(0), .COMP(1)) u_shell_me (.clk(clk), .rst_n(rs),
        .me_go(c_me_go), .su_go(1'b0), .me_en(me_clk_en), .su_sfu(3'd0), .me_amax(c_me_i_amax),
        .d_me_ready(c_me_ready), .d_me_idle(c_me_idle), .d_me_progress(c_me_progress),
        .d_su_ready(1'b0), .d_su_idle(1'b0), .d_su_active(1'b0), .d_su_inflight(8'd0), .d_su_progress(16'd0), .d_su_rows(16'd0),
        .c_me_ready(s_me_ready), .c_me_idle(s_me_idle), .c_me_progress(s_me_progress),
        .c_su_ready(), .c_su_idle(), .c_su_progress(), .c_su_rows());
    ot_hdc_delay #(.W(1), .D(DCU_M), .RESET(1)) u_sd_me_go (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_go), .q(u_me_go));
    ot_hdc_delay #(.W(1), .D(DUC_M), .RESET(1)) u_su_me_ready (.clk(c_me_clk), .rst_n(rst_n), .d(u_me_ready), .q(c_me_ready));
    ot_hdc_delay #(.W(1), .D(DUC_M), .RESET(1)) u_su_me_idle (.clk(c_me_clk), .rst_n(rst_n), .d(u_me_idle), .q(c_me_idle));
    ot_hdc_delay #(.W(18), .D(DCU_M)) u_sd_me_i_nout (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_nout), .q(u_me_i_nout));
    ot_hdc_delay #(.W(18), .D(DCU_M)) u_sd_me_i_tiles (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_tiles), .q(u_me_i_tiles));
    ot_hdc_delay #(.W(18), .D(DCU_M)) u_sd_me_i_k (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_k), .q(u_me_i_k));
    ot_hdc_delay #(.W(1), .D(DCU_M)) u_sd_me_i_wsrc (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_wsrc), .q(u_me_i_wsrc));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_wbase (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_wbase), .q(u_me_i_wbase));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_ts (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_ts), .q(u_me_i_ts));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_ks (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_ks), .q(u_me_i_ks));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_js (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_js), .q(u_me_i_js));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_xbase (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_xbase), .q(u_me_i_xbase));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_xks (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_xks), .q(u_me_i_xks));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_xjs (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_xjs), .q(u_me_i_xjs));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_xcs (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_xcs), .q(u_me_i_xcs));
    ot_hdc_delay #(.W(3), .D(DCU_M)) u_sd_me_i_jsh (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_jsh), .q(u_me_i_jsh));
    ot_hdc_delay #(.W(4), .D(DCU_M)) u_sd_me_i_split (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_split), .q(u_me_i_split));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_wcs (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_wcs), .q(u_me_i_wcs));
    ot_hdc_delay #(.W(1), .D(DCU_M)) u_sd_me_i_round (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_round), .q(u_me_i_round));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_obase (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_obase), .q(u_me_i_obase));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_ots (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_ots), .q(u_me_i_ots));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_ojs (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_ojs), .q(u_me_i_ojs));
    ot_hdc_delay #(.W(1), .D(DCU_M)) u_sd_me_i_mmode (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_mmode), .q(u_me_i_mmode));
    ot_hdc_delay #(.W(1), .D(DCU_M)) u_sd_me_i_oen (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_oen), .q(u_me_i_oen));
    ot_hdc_delay #(.W(1), .D(DCU_M)) u_sd_me_i_amax (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_amax), .q(u_me_i_amax));
    ot_hdc_delay #(.W(1), .D(DCU_M)) u_sd_me_i_rmax (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_rmax), .q(u_me_i_rmax));
    ot_hdc_delay #(.W(24), .D(DCU_M)) u_sd_me_i_mbase (.clk(c_me_clk), .rst_n(rst_n), .d(c_me_i_mbase), .q(u_me_i_mbase));
    ot_hdc_delay #(.W(1), .D(DUC_M), .RESET(1)) u_su_me_wrom_re (.clk(c_me_clk), .rst_n(rst_n), .d(u_me_wrom_re), .q(c_me_wrom_re));
    ot_hdc_delay #(.W(24), .D(DUC_M)) u_su_me_wrom_addr (.clk(c_me_clk), .rst_n(rst_n), .d(u_me_wrom_addr), .q(c_me_wrom_addr));
    ot_hdc_delay #(.W(18), .D(DUC_M)) u_su_me_am_idx (.clk(c_me_clk), .rst_n(rst_n), .d(u_me_am_idx), .q(c_me_am_idx));
    ot_hdc_delay #(.W(32), .D(DUC_M)) u_su_me_am_val (.clk(c_me_clk), .rst_n(rst_n), .d(u_me_am_val), .q(c_me_am_val));
    ot_hdc_delay #(.W(1), .D(DUC_M), .RESET(1)) u_su_me_am_any (.clk(c_me_clk), .rst_n(rst_n), .d(u_me_am_any), .q(c_me_am_any));
    ot_hdc_delay #(.W(16), .D(DUC_M), .RESET(1)) u_su_me_progress (.clk(c_me_clk), .rst_n(rst_n), .d(u_me_progress), .q(c_me_progress));
    ot_hdc_delay #(.W(1), .D(DUC_M), .RESET(1)) u_su_me_fault (.clk(c_me_clk), .rst_n(rst_n), .d(u_me_fault), .q(c_me_fault));
    reg [XW-1:0] me_acc;
    always @(posedge c_me_clk or negedge rst_n) if (!rst_n) me_acc <= {XW{1'b0}}; else if (u_me_go) me_acc <= me_acc + 1'b1;
    ot_hdc_delay #(.W(XW + 18), .D(OS), .RESET(1)) u_os_snap (.clk(clk), .rst_n(rs), .d({me_acc, u_me_idle, u_me_progress, m_fin}),
        .q({me_acc_o, me_idle_o, me_prog_o, m_fin_o}));
    ot_hdc_delay #(.W(18 + 32), .D(OS)) u_os_f (.clk(clk), .rst_n(rs), .d({m_fidx, m_fval}), .q({m_fidx_o, m_fval_o}));
    ot_qfd_tt_ctl #(.W(16), .IL(8), .AW(24), .NW(18), .GT(6144), .TG(4), .SMIN(7), .SMAX(11), .TCUT(7), .XD(105), .XVM(15), .ORD(7), .ACC_LAT(7), .TREE_LAT(7), .MUL_LAT(6), .FAST_ISSUE(1), .KV_PREP(3), .SCALE_LAT(6), .LANDED(1), .BAND(1), .LNK(0), .CLNK(0), .AMR(1), .SPRE(2), .IS(0), .OS(OS)) u_tt (
        .clk(c_me_clk), .rst_n(rs), .up_fault(up_fault), .land_cnt(land_cnt), .go(u_me_go), .ready(u_me_ready),
        .idle(u_me_idle), .i_nout(u_me_i_nout), .i_tiles(u_me_i_tiles), .i_k(u_me_i_k), .i_wsrc(u_me_i_wsrc), .i_wbase(u_me_i_wbase), .i_ts(u_me_i_ts), .i_ks(u_me_i_ks), .i_js(u_me_i_js), .i_xbase(u_me_i_xbase), .i_xks(u_me_i_xks), .i_xjs(u_me_i_xjs), .i_xcs(u_me_i_xcs), .i_jsh(u_me_i_jsh), .i_split(u_me_i_split), .i_wcs(u_me_i_wcs), .i_round(u_me_i_round), .i_obase(u_me_i_obase), .i_ots(u_me_i_ots), .i_ojs(u_me_i_ojs), .i_mmode(u_me_i_mmode), .i_oen(u_me_i_oen), .i_amax(u_me_i_amax), .i_rmax(u_me_i_rmax), .i_mbase(u_me_i_mbase),
        .wrom_re(u_me_wrom_re), .wrom_addr(u_me_wrom_addr), .kv_re(),
        .scale_re(scale_re), .scale_gre(scale_gre), .scale_addr(scale_addr),
        .x_rdy(x_rdy), .x_dv(x_dv), .x_dc(x_dc), .x_dcs(x_dcs), .x_dsp(x_dsp),
        .t_sel_e(t_sel_e), .t_tv_e(t_tv_e), .tr_fault(tr_fault),
        .p_v_e2(p_v_e2), .p_f_e2(p_f_e2), .p_am(p_am), .p_fault(p_fault), .fab_fault(fab_fault),
        .ov(ov), .am_idx(u_me_am_idx), .am_val(u_me_am_val), .am_any(u_me_am_any),
        .mx_we(mx_we), .mx_addr(mx_addr), .mx_mask(mx_mask), .mx_data(mx_data),
        .progress(u_me_progress), .fault(u_me_fault));
    assign u_me_mx_we = 1'b0; assign u_me_o_we = '0;
endmodule
