// GENERATED by tools/generate_a3_semantic_record_collector.py.
// Do not edit: regenerate, and `--check` fails if this drifts from the ABI.
//
// One function per record block, each reading a 192-byte raw descriptor
// (64-byte header then payload) at the byte offsets
// runtime/abi3/descriptors.py declares. The word order is the record's
// contract with the engines and comes from runtime/abi3/semantic_record.py,
// which tests/abi3/test_semantic_record.py proves equal to the decoded
// assembly on both shipped stores.

// OPERATOR: 18 words
function automatic [18*32-1:0] a3_record_operator_words;
    input [1535:0] raw;
    begin
        a3_record_operator_words[0*32 +: 32] = {24'd0, raw[512 +: 8]}; // engine_family
        a3_record_operator_words[1*32 +: 32] = {24'd0, raw[520 +: 8]}; // engine_sub
        a3_record_operator_words[2*32 +: 32] = {16'd0, raw[528 +: 16]}; // flags
        a3_record_operator_words[3*32 +: 32] = raw[544 +: 32]; // source_graph_operation_id
        a3_record_operator_words[4*32 +: 32] = raw[576 +: 32]; // source_kernel_id
        a3_record_operator_words[5*32 +: 32] = raw[608 +: 32]; // counter_class_id
        a3_record_operator_words[6*32 +: 32] = raw[640 +: 32]; // numeric_profile_id
        a3_record_operator_words[7*32 +: 32] = raw[672 +: 32]; // schedule_id
        a3_record_operator_words[8*32 +: 32] = raw[704 +: 32]; // input_view_0
        a3_record_operator_words[9*32 +: 32] = raw[736 +: 32]; // input_view_1
        a3_record_operator_words[10*32 +: 32] = raw[768 +: 32]; // input_view_2
        a3_record_operator_words[11*32 +: 32] = raw[800 +: 32]; // input_view_3
        a3_record_operator_words[12*32 +: 32] = raw[832 +: 32]; // output_view_0
        a3_record_operator_words[13*32 +: 32] = raw[864 +: 32]; // output_view_1
        a3_record_operator_words[14*32 +: 32] = raw[896 +: 32]; // aux_id_0
        a3_record_operator_words[15*32 +: 32] = raw[928 +: 32]; // aux_id_1
        a3_record_operator_words[16*32 +: 32] = raw[960 +: 32]; // aux_id_2
        a3_record_operator_words[17*32 +: 32] = raw[992 +: 32]; // aux_id_3
    end
endfunction

// COUNTER_CLASS: 5 words
function automatic [5*32-1:0] a3_record_counter_words;
    input [1535:0] raw;
    begin
        a3_record_counter_words[0*32 +: 32] = {24'd0, raw[512 +: 8]}; // group
        a3_record_counter_words[1*32 +: 32] = {24'd0, raw[520 +: 8]}; // event_count
        a3_record_counter_words[2*32 +: 32] = raw[576 +: 32]; // counter_0
        a3_record_counter_words[3*32 +: 32] = raw[608 +: 32]; // counter_1
        a3_record_counter_words[4*32 +: 32] = raw[640 +: 32]; // counter_2
    end
endfunction

// NUMERIC: 11 words
function automatic [11*32-1:0] a3_record_numeric_words;
    input [1535:0] raw;
    begin
        a3_record_numeric_words[0*32 +: 32] = {24'd0, raw[512 +: 8]}; // input_dtype
        a3_record_numeric_words[1*32 +: 32] = {24'd0, raw[520 +: 8]}; // second_input_dtype
        a3_record_numeric_words[2*32 +: 32] = {24'd0, raw[528 +: 8]}; // accumulator_dtype
        a3_record_numeric_words[3*32 +: 32] = {24'd0, raw[536 +: 8]}; // output_dtype
        a3_record_numeric_words[4*32 +: 32] = {24'd0, raw[544 +: 8]}; // rounding_mode
        a3_record_numeric_words[5*32 +: 32] = {24'd0, raw[552 +: 8]}; // reduction_order
        a3_record_numeric_words[6*32 +: 32] = {24'd0, raw[560 +: 8]}; // saturate
        a3_record_numeric_words[7*32 +: 32] = {24'd0, raw[568 +: 8]}; // nan_policy
        a3_record_numeric_words[8*32 +: 32] = raw[576 +: 32]; // epsilon_bits
        a3_record_numeric_words[9*32 +: 32] = raw[608 +: 32]; // scale_bits
        a3_record_numeric_words[10*32 +: 32] = raw[640 +: 32]; // flags
    end
endfunction

// SCHEDULE: 12 words
function automatic [12*32-1:0] a3_record_schedule_words;
    input [1535:0] raw;
    begin
        a3_record_schedule_words[0*32 +: 32] = {24'd0, raw[512 +: 8]}; // engine_family
        a3_record_schedule_words[1*32 +: 32] = {24'd0, raw[520 +: 8]}; // queue_index
        a3_record_schedule_words[2*32 +: 32] = {16'd0, raw[528 +: 16]}; // issue_window
        a3_record_schedule_words[3*32 +: 32] = raw[544 +: 32]; // tile_rows
        a3_record_schedule_words[4*32 +: 32] = raw[576 +: 32]; // tile_cols
        a3_record_schedule_words[5*32 +: 32] = raw[608 +: 32]; // tile_depth
        a3_record_schedule_words[6*32 +: 32] = raw[640 +: 32]; // bank_mask
        a3_record_schedule_words[7*32 +: 32] = raw[672 +: 32]; // port_mask
        a3_record_schedule_words[8*32 +: 32] = raw[704 +: 32]; // noc_route_class
        a3_record_schedule_words[9*32 +: 32] = raw[736 +: 32]; // resource_bound
        a3_record_schedule_words[10*32 +: 32] = raw[768 +: 32]; // max_outstanding
        a3_record_schedule_words[11*32 +: 32] = raw[800 +: 32]; // priority
    end
endfunction

// NUMERIC contract digest: 256 bits as eight little-endian words
function automatic [8*32-1:0] a3_record_digest_words;
    input [1535:0] raw;
    begin
        a3_record_digest_words[0*32 +: 32] = raw[768 +: 32];
        a3_record_digest_words[1*32 +: 32] = raw[800 +: 32];
        a3_record_digest_words[2*32 +: 32] = raw[832 +: 32];
        a3_record_digest_words[3*32 +: 32] = raw[864 +: 32];
        a3_record_digest_words[4*32 +: 32] = raw[896 +: 32];
        a3_record_digest_words[5*32 +: 32] = raw[928 +: 32];
        a3_record_digest_words[6*32 +: 32] = raw[960 +: 32];
        a3_record_digest_words[7*32 +: 32] = raw[992 +: 32];
    end
endfunction

// TENSOR_VIEW: 2 header words then 8 payload words
function automatic [10*32-1:0] a3_record_view_words;
    input [1535:0] raw;
    begin
        a3_record_view_words[0*32 +: 32] = raw[128 +: 32]; // primary_object_id
        a3_record_view_words[1*32 +: 32] = raw[256 +: 32]; // permissions
        a3_record_view_words[2*32 +: 32] = {24'd0, raw[512 +: 8]}; // dtype
        a3_record_view_words[3*32 +: 32] = {24'd0, raw[520 +: 8]}; // rank
        a3_record_view_words[4*32 +: 32] = raw[704 +: 32]; // dim0
        a3_record_view_words[5*32 +: 32] = raw[736 +: 32]; // dim1
        a3_record_view_words[6*32 +: 32] = raw[768 +: 32]; // dim2
        a3_record_view_words[7*32 +: 32] = raw[896 +: 32]; // stride0
        a3_record_view_words[8*32 +: 32] = raw[928 +: 32]; // stride1
        a3_record_view_words[9*32 +: 32] = raw[960 +: 32]; // stride2
    end
endfunction

// EVENT_WAIT_SET: the sole producer the record carries at word 6.
function automatic [31:0] a3_record_wait_producer_0;
    input [1535:0] raw;
    begin a3_record_wait_producer_0 = raw[576 +: 32]; end
endfunction

// The header fields a collector matches descriptors by.
function automatic [31:0] a3_record_descriptor_type;
    input [1535:0] raw;
    begin a3_record_descriptor_type = {16'd0, raw[32 +: 16]}; end
endfunction
