// Additive default-off actual full RF plus W4/W6/matcher/consumer physical context.
// Original frozen modules byte-identical; external issuer/reverse/drain remain real ports.
module ot_gpu_rf_w6_physical_context #(parameter bit ENABLE=0)(
 input wire  clk,
 input wire  por_n,
 input wire  rst_n,
 input wire  req_valid,
 output wire  req_ready,
 input wire [45:0] req_owner46,
 input wire [63:0] req_native_tag,
 input wire [63:0] req_native_generation,
 input wire  issuer_binding_valid,
 input wire  visibility_enable,
 output wire  ack_integration_fault,
 output wire  visible_valid,
 output wire [54:0] visible_identity,
 output wire  result_valid,
 input wire  result_ready,
 output wire [4095:0] result,
 output wire  consumer_accepted,
 output wire [54:0] consumer_identity,
 input wire  child_reverse_valid,
 input wire [54:0] child_reverse_identity,
 output wire  child_reverse_ready,
 input wire  parent_reverse_valid,
 input wire [54:0] parent_reverse_identity,
 output wire  parent_reverse_ready,
 input wire  reverse_CDC_valid,
 input wire [54:0] reverse_CDC_identity,
 output wire  reverse_CDC_ready,
 output wire  drain_req_valid,
 output wire [54:0] drain_req_identity,
 output wire  drain_req_has_owner,
 output wire  drain_req_reset_scope,
 input wire  drain_req_ready,
 input wire  drain_rsp_valid,
 input wire [54:0] drain_rsp_identity,
 input wire  drain_rsp_has_owner,
 input wire  drain_rsp_reset_scope,
 input wire [8:0] alldrain_live,
 output wire  drain_rsp_ready,
 output wire  done_valid,
 input wire  done_ready,
 output wire [63:0] done_native_tag,
 output wire [63:0] done_native_generation,
 input wire  rearm_valid,
 input wire  admission_stop,
 input wire  issuer_allcopy_fenced,
 output wire  rearm_ready,
 output wire  exclusive_lease,
 output wire  fault
);
 wire  ack_identity_fault;
 wire [45:0] ack_owner;
 wire  ack_ready;
 wire [8:0] ack_slot;
 wire  ack_valid;
 wire [8:0] rd_a;
 wire [8:0] rd_b;
 wire  rd_ready;
 wire  rd_valid;
 wire [4095:0] rsp_a;
 wire [4095:0] rsp_b;
 wire  rsp_ready;
 wire  rsp_valid;
 wire [8:0] wr_addr;
 wire [4095:0] wr_data;
 wire [45:0] wr_owner;
 wire  wr_ready;
 wire  wr_valid;
ot_gpu_pc40_physical_ack_source #(.ENABLE(ENABLE)) joined(
.clk(clk),
.por_n(por_n),
.rst_n(rst_n),
.req_valid(req_valid),
.req_ready(req_ready),
.req_owner46(req_owner46),
.req_native_tag(req_native_tag),
.req_native_generation(req_native_generation),
.issuer_binding_valid(issuer_binding_valid),
.visibility_enable(visibility_enable),
.rd_valid(rd_valid),
.rd_ready(rd_ready),
.rd_a(rd_a),
.rd_b(rd_b),
.rsp_valid(rsp_valid),
.rsp_a(rsp_a),
.rsp_b(rsp_b),
.rsp_ready(rsp_ready),
.wr_valid(wr_valid),
.wr_ready(wr_ready),
.wr_addr(wr_addr),
.wr_data(wr_data),
.ack_valid(ack_valid),
.ack_ready(ack_ready),
.ack_owner(ack_owner),
.ack_slot(ack_slot),
.ack_identity_fault(ack_identity_fault),
.wr_owner(wr_owner),
.ack_integration_fault(ack_integration_fault),
.visible_valid(visible_valid),
.visible_identity(visible_identity),
.result_valid(result_valid),
.result_ready(result_ready),
.result(result),
.consumer_accepted(consumer_accepted),
.consumer_identity(consumer_identity),
.child_reverse_valid(child_reverse_valid),
.child_reverse_identity(child_reverse_identity),
.child_reverse_ready(child_reverse_ready),
.parent_reverse_valid(parent_reverse_valid),
.parent_reverse_identity(parent_reverse_identity),
.parent_reverse_ready(parent_reverse_ready),
.reverse_CDC_valid(reverse_CDC_valid),
.reverse_CDC_identity(reverse_CDC_identity),
.reverse_CDC_ready(reverse_CDC_ready),
.drain_req_valid(drain_req_valid),
.drain_req_identity(drain_req_identity),
.drain_req_has_owner(drain_req_has_owner),
.drain_req_reset_scope(drain_req_reset_scope),
.drain_req_ready(drain_req_ready),
.drain_rsp_valid(drain_rsp_valid),
.drain_rsp_identity(drain_rsp_identity),
.drain_rsp_has_owner(drain_rsp_has_owner),
.drain_rsp_reset_scope(drain_rsp_reset_scope),
.alldrain_live(alldrain_live),
.drain_rsp_ready(drain_rsp_ready),
.done_valid(done_valid),
.done_ready(done_ready),
.done_native_tag(done_native_tag),
.done_native_generation(done_native_generation),
.rearm_valid(rearm_valid),
.admission_stop(admission_stop),
.issuer_allcopy_fenced(issuer_allcopy_fenced),
.rearm_ready(rearm_ready),
.exclusive_lease(exclusive_lease),
.fault(fault)
);
(* keep_hierarchy = "yes" *) ot_gpu_rf_service #(.ACK_ID(1)) provider(
.clk(clk),
.rst_n(rst_n),
.rd_valid(rd_valid),
.rd_ready(rd_ready),
.rd_a(rd_a),
.rd_b(rd_b),
.rsp_valid(rsp_valid),
.rsp_ready(rsp_ready),
.rsp_a(rsp_a),
.rsp_b(rsp_b),
.wr_valid(wr_valid),
.wr_ready(wr_ready),
.wr_addr(wr_addr),
.wr_data(wr_data),
.ack_valid(ack_valid),
.ack_ready(ack_ready),
.wr_owner(wr_owner),
.ack_owner(ack_owner),
.ack_slot(ack_slot),
.ack_identity_fault(ack_identity_fault)
);
endmodule
