`timescale 1ps/1fs
`default_nettype none
// GENERATED by physical/hbm_accel_die_views/index_q/gen_split.py (CLAUDE HBM-ABSTRACTS svcidx, segment split of the
// INTERIM index-quarter view hfd_index_q; NOT the indexer).  Every die input lands in a chain's first (face) register,
// every die output leaves a chain's last register or a pin register; each band synchronises its own reset.
module hfd_index_q_b0 (
    input wire [528:0] a0, input wire [0:0] ck, input wire [1025:0] k, input wire [0:0] rst,
    output wire [512:0] kout, output wire [528:0] a0o);
  wire c = ck[0];
  reg rs1, rs2;
  always @(posedge c or negedge rst[0]) if (!rst[0]) {rs2, rs1} <= 2'b00; else {rs2, rs1} <= {rs1, 1'b1};
  wire rn = rs2;
  // forwarded keys: capture on the forwarded clock's falling edge at the pin, two-clock FIFOs (8 deep), kf
  wire [511:0] kh [0:1]; wire [1:0] ke;
  genvar g;
  generate for (g = 0; g < 2; g = g + 1) begin : gk
    wire full_; wire [2:0] fr_;
    wire wck = ~k[1024+g];
    reg [511:0] kc;
    always @(posedge wck) kc <= k[g*512 +: 512];
    ot_hbm_accel_cdc_fifo #(.W(512), .AW(3)) u_x (.wclk(wck), .wrst_n(rst[0]), .we(1'b1),
      .wdata(kc), .full(full_), .rd_freed(fr_), .rclk(c), .rrst_n(rn), .re(1'b1), .rdata(kh[g]),
      .empty(ke[g]));
  end endgenerate
  reg kv; reg [511:0] kf;
  always @(posedge c or negedge rn) if (!rn) kv <= 1'b0; else kv <= !ke[0] && !ke[1];
  always @(posedge c) kf <= kh[0] ^ kh[1];
  wire kpv; wire [511:0] kpq;
  ot_svc_vpipe #(.W(512), .N(5)) u_kp (.ck(c), .rst_n(rn), .v(kv), .d(kf), .qv(kpv), .q(kpq));
  assign kout = {kpq, kpv};
  wire a0v; wire [527:0] a0q;
  ot_svc_vpipe #(.W(528), .N(3)) u_a0 (.ck(c), .rst_n(rn), .v(a0[0]), .d(a0[528:1]), .qv(a0v), .q(a0q));
  assign a0o = {a0q, a0v};
endmodule
`default_nettype wire
