namespace eval ::qcg {

# Generated by tools/qwen_corridor_gate.py.  Do not edit.
proc qcg_block {} { return [ord::get_db_block] }
proc qcg_dbu {} { return [[qcg_block] getDbUnitsPerMicron] }
proc qcg_um {v} { return [expr {int(round($v * [qcg_dbu]))}] }
# zone membership: instance name prefix before the first '_' (qs<k>, qr<k><j>)
proc qcg_zone_of {name} { return [lindex [split $name _] 0] }
proc qcg_chain_of {name} { return [lindex [split $name _] 1] }

# PRE_GLOBAL_ROUTE: r2 layer assignment.  The non-assigned same-direction layers ['M3', 'M5'] get zero capacity
# between the slabs (kept 2.0 um clear of every slab so pin access inside a slab is untouched).
set qcg_axis y
set qcg_zones {{qs0 2.16 10.8} {qr01 111.78 116.37} {qr02 219.51 224.1} {qr03 327.24 331.56} {qs1 432.54 441.45} {qr11 542.43 547.02} {qr12 650.16 654.48} {qr13 757.62 762.21} {qs2 863.19 872.1} {qr21 973.08 977.4} {qr22 1080.54 1085.13} {qr23 1188.27 1192.86} {qs3 1293.84 1302.48}}
set qcg_blocked {M3 M5}
set qcg_keep 2.0
set qcg_margin 1.08

set die [[qcg_block] getDieArea]
set dbu [qcg_dbu]
set W [expr {[$die xMax] / double($dbu)}]; set H [expr {[$die yMax] / double($dbu)}]
set zs [lsort -real -index 1 $qcg_zones]
set n 0
for {set i 0} {$i < [llength $zs] - 1} {incr i} {
  set a [expr {[lindex [lindex $zs $i] 2] + $qcg_keep}]
  set b [expr {[lindex [lindex $zs [expr {$i + 1}]] 1] - $qcg_keep}]
  if {$b <= $a} continue
  foreach l $qcg_blocked {
    if {$qcg_axis eq "x"} {
      set_global_routing_region_adjustment [list $a 0 $b $H] -layer $l -adjustment 1.0
    } else {
      set_global_routing_region_adjustment [list 0 $a $W $b] -layer $l -adjustment 1.0
    }
    incr n
  }
}
puts "QCG region adjustments: $n"
# FastRoute leaves the gcells on the die margin outside the core unadjusted (measured: edge chains detoured on the
# blocked layers there), so the margin strips between slabs also get physical obstructions.  The margin lies outside
# the core, where no PG shape exists.
set tech [ord::get_db_tech]
set blk [qcg_block]
set m [qcg_um $qcg_margin]
set no 0
for {set i 0} {$i < [llength $zs] - 1} {incr i} {
  set a [qcg_um [lindex [lindex $zs $i] 2]]
  set b [qcg_um [lindex [lindex $zs [expr {$i + 1}]] 1]]
  foreach l $qcg_blocked {
    set L [$tech findLayer $l]
    if {$qcg_axis eq "x"} {
      odb::dbObstruction_create $blk $L $a 0 $b $m
      odb::dbObstruction_create $blk $L $a [expr {[$die yMax] - $m}] $b [$die yMax]
    } else {
      odb::dbObstruction_create $blk $L 0 $a $m $b
      odb::dbObstruction_create $blk $L [expr {[$die xMax] - $m}] $a [$die xMax] $b
    }
    incr no 2
  }
}
puts "QCG margin obstructions: $no"

}
