namespace eval ::qcg {

# Generated by tools/qwen_corridor_gate.py.  Do not edit.
proc qcg_block {} { return [ord::get_db_block] }
proc qcg_dbu {} { return [[qcg_block] getDbUnitsPerMicron] }
proc qcg_um {v} { return [expr {int(round($v * [qcg_dbu]))}] }
# zone membership: instance name prefix before the first '_' (qs<k>, qr<k><j>)
proc qcg_zone_of {name} { return [lindex [split $name _] 0] }
proc qcg_chain_of {name} { return [lindex [split $name _] 1] }

# PRE_IO_PLACEMENT: bus ports on the corridor ends, tile-edge pin row on the east edge (B); no ordering is forced,
# so the placer matches each pin to its fixed station flop.
proc qcg_ports {pattern} {
  set names {}
  foreach bt [[qcg_block] getBTerms] { if {[regexp -- $pattern [$bt getName]]} { lappend names [$bt getName] } }
  if {[llength $names] == 0} { error "QCG no port matches $pattern" }
  return $names
}
set_io_pin_constraint -pin_names [qcg_ports {^bd\[}] -region bottom:*
set_io_pin_constraint -pin_names [qcg_ports {^bq\[}] -region top:*
set_io_pin_constraint -pin_names [concat [qcg_ports {^tq\[}] {rdy_t}] -region right:10.78-50.78
set_io_pin_constraint -pin_names {clk} -region bottom:*

}
