namespace eval ::qcg {

# Generated by tools/qwen_corridor_gate.py.  Do not edit.
proc qcg_block {} { return [ord::get_db_block] }
proc qcg_dbu {} { return [[qcg_block] getDbUnitsPerMicron] }
proc qcg_um {v} { return [expr {int(round($v * [qcg_dbu]))}] }
# zone membership: instance name prefix before the first '_' (qs<k>, qr<k><j>)
proc qcg_zone_of {name} { return [lindex [split $name _] 0] }
proc qcg_chain_of {name} { return [lindex [split $name _] 1] }

# PRE_RESIZE: global placement (which calls remove_buffers when timing driven) is over; release the r2 stations and
# repeaters to the resizer (sizing, buffering their nets) and to the legaliser.  Kept dont_touch, rsz fails with
# RSZ-3006 when it buffers a station -> repeater net (measured: A_strip_r2 and B_tile_r0362 attempts).
set n 0
foreach inst [[qcg_block] getInsts] {
  if {[regexp {^q[sr][0-9]+_[0-9]+$} [$inst getName]]} {
    $inst setDoNotTouch 0
    $inst setPlacementStatus PLACED
    incr n
  }
}
puts "QCG released $n station/repeater cells to resize and legalisation"

}
