// Source-derived join: Dewey73d8 individual modules + Popperdf414 bridge; ONE controller.
`timescale 1ns/1ps
// Canonical callback ports remain unchanged. This adds REAL shared-service,
// protected state-write observation and native parent/drain connections.
// No memories, W2 replacement, command generator or numerical fallback here.
// All native/shared/W2/reset/CDC authority inputs must come from actual source.
module ot_gpu_qwen_joined_kv #(parameter ENABLE=0)(
 input wire  clk,
 input wire  por_n,
 input wire  run_enable,
 input wire  quiesce,
 input wire  cmd_valid,
 output wire  cmd_ready,
 input wire [2:0] cmd_op,
 input wire [63:0] cmd_identity,
 input wire [19:0] cmd_key,
 input wire [63:0] cmd_producer,
 input wire [63:0] cmd_sequence,
 input wire [10:0] cmd_PC,
 input wire  cmd_consumer,
 input wire [3:0] cmd_stage_beat,
 input wire [9:0] cmd_stage_base,
 input wire [4:0] cmd_stage_SM,
 input wire [511:0] cmd_stage_data,
 input wire [33:0] cmd_K_base,
 input wire [33:0] cmd_V_base,
 output wire  rsp_valid,
 input wire  rsp_ready,
 output wire  rsp_fault,
 output wire [2:0] rsp_op,
 output wire [63:0] rsp_identity,
 output wire [19:0] rsp_key,
 output wire [63:0] rsp_sequence,
 output wire [10:0] rsp_PC,
 output wire [511:0] rsp_capture,
 output wire [63:0] rsp_producer,
 output wire  rsp_consumer,
 output wire [3:0] rsp_stage_beat,
 output wire  commit_valid,
 input wire  commit_ready,
 output wire [63:0] writer_identity,
 output wire [19:0] writer_key,
 output wire [9:0] writer_stage_base,
 output wire [4:0] writer_stage_SM,
 output wire [33:0] writer_K_base,
 output wire [33:0] writer_V_base,
 input wire  payload_valid,
 output wire  payload_ready,
 input wire [63:0] payload_identity,
 input wire [19:0] payload_key,
 input wire [8:0] payload_sector,
 input wire [33:0] payload_source_addr,
 input wire  payload_visible,
 input wire  payload_reverse,
 input wire  payload_write,
 input wire [255:0] payload_rdata,
 output wire  payload_req_valid,
 input wire  payload_req_ready,
 output wire  payload_req_write,
 output wire [8:0] payload_req_sector,
 output wire [33:0] payload_req_source_addr,
 output wire [255:0] payload_req_data,
 output wire  payload_req_rmw,
 output wire  payload_req_rmw_last,
 input wire  hydrate_valid,
 output wire  hydrate_ready,
 input wire [19:0] hydrate_key,
 input wire [63:0] hydrate_producer,
 output wire  writer_retained,
 output wire  idle,
 input wire [63:0] native_valid,
 input wire [63:0] native_write,
 input wire [639:0] native_addr,
 input wire [32767:0] native_wdata,
 output wire [63:0] native_ready,
 output wire [63:0] native_done,
 input wire [63:0] native_done_ready,
 output wire [32767:0] native_rdata,
 output wire [63:0] service_valid,
 output wire [63:0] service_write,
 output wire [639:0] service_addr,
 output wire [32767:0] service_wdata,
 input wire [63:0] service_ready,
 input wire [63:0] service_done,
 input wire [32767:0] service_rdata,
 output wire [63:0] service_done_ready,
 output wire  shared_drained,
 input wire  source_bound,
 input wire [33:0] state_base_rank0,
 input wire [33:0] state_base_rank1,
 input wire  observe_valid,
 output wire  observe_ready,
 input wire  observe_rank,
 input wire [33:0] observe_source_addr,
 input wire [33:0] observe_physical_addr,
 input wire [45:0] observe_owner,
 input wire [255:0] observe_old_data,
 input wire [255:0] observe_new_data,
 input wire  observe_old_captured,
 input wire  ACK_valid,
 output wire  ACK_ready,
 input wire [45:0] ACK_owner,
 input wire [33:0] ACK_physical_addr,
 input wire  ACK_visible,
 input wire  ACK_reverse,
 output wire  state_observer_drained,
 input wire rst_n,
 input wire endpoint_fault,
 input wire native_issue_valid,
 output wire native_issue_ready,
 input wire [229:0] native_issue_tuple,
 input wire native_complete_valid,
 output wire native_complete_ready,
 input wire [229:0] native_complete_tuple,
 input wire native_reverse_valid,
 output wire native_reverse_ready,
 input wire [229:0] native_reverse_tuple,
 output wire [7:0] cohort_quiesce,
 output wire [7:0] cohort_req_valid,
 input wire [7:0] cohort_req_ready,
 output wire [63:0] cohort_identity,
 output wire [19:0] cohort_key,
 input wire [7:0] cohort_rsp_valid,
 output wire [7:0] cohort_rsp_ready,
 input wire [671:0] cohort_rsp_tuple,
 input wire [7:0] cohort_rsp_empty,
 output wire native_retained,
 output wire drain_retained,
 output wire  fault
);
 wire  core_cmd_valid;
 wire  core_cmd_ready;
 wire  c_shared_valid;
 wire  c_shared_write;
 wire  c_shared_ready;
 wire [9:0] c_shared_addr;
 wire [4:0] c_shared_SM;
 wire  c_shared_rank;
 wire [511:0] c_shared_wdata;
 wire  c_shared_done;
 wire  c_shared_done_ready;
 wire [511:0] c_shared_rdata;
 wire  c_metadata_valid;
 wire  c_metadata_ready;
 wire [63:0] c_metadata_identity;
 wire [19:0] c_metadata_key;
 wire  c_metadata_record;
 wire  c_consumer_valid;
 wire  c_consumer_ready;
 wire [63:0] c_consumer_identity;
 wire [19:0] c_consumer_key;
 wire  c_consumer_stage;
 wire  c_consumer_accepted;
 wire  c_consumer_reverse;
 wire  c_reader_metadata_valid;
 wire  c_reader_metadata_ready;
 wire [63:0] c_reader_metadata_identity;
 wire [19:0] c_reader_metadata_key;
 wire  c_reader_metadata_stage;
 wire  c_drain_valid;
 wire  c_drain_ready;
 wire [63:0] c_drain_identity;
 wire [19:0] c_drain_key;
 wire  c_drain_done_valid;
 wire  c_drain_done_ready;
 wire [63:0] c_drain_done_identity;
 wire [19:0] c_drain_done_key;
 wire [7:0] c_drain_done_allcopies;
 wire  core_fault;
 wire  router_fault;
 wire  event_valid;
 wire  event_ready;
 wire [2:0] event_kind;
 wire [63:0] event_identity;
 wire [63:0] event_producer;
 wire [19:0] event_key;
 wire [10:0] event_PC;
 wire  observer_fault;
 wire  command_allow;
 wire  join_fault;
 wire  reader_fault;
 wire  effective_enable;
 reg [10:0] writer_PC;
 assign fault=core_fault | router_fault | observer_fault | join_fault | reader_fault;
 assign effective_enable=run_enable && !fault;
 assign core_cmd_valid=cmd_valid && command_allow && source_bound;
 assign cmd_ready=core_cmd_ready && command_allow && source_bound;
 always @(posedge clk or negedge por_n) begin
  if(!por_n) writer_PC<=0;
  else if(core_cmd_valid && core_cmd_ready && cmd_op==0) writer_PC<=cmd_PC;
 end
 ot_gpu_qwen_kv_lifecycle_controller #(.ENABLE(ENABLE)) kv_controller (
  .clk(clk),
  .por_n(por_n),
  .run_enable(effective_enable),
  .quiesce(quiesce),
  .cmd_valid(core_cmd_valid),
  .cmd_ready(core_cmd_ready),
  .cmd_op(cmd_op),
  .cmd_identity(cmd_identity),
  .cmd_key(cmd_key),
  .cmd_producer(cmd_producer),
  .cmd_sequence(cmd_sequence),
  .cmd_PC(cmd_PC),
  .cmd_consumer(cmd_consumer),
  .cmd_stage_beat(cmd_stage_beat),
  .cmd_stage_base(cmd_stage_base),
  .cmd_stage_SM(cmd_stage_SM),
  .cmd_stage_data(cmd_stage_data),
  .cmd_K_base(cmd_K_base),
  .cmd_V_base(cmd_V_base),
  .rsp_valid(rsp_valid),
  .rsp_ready(rsp_ready),
  .rsp_fault(rsp_fault),
  .rsp_op(rsp_op),
  .rsp_identity(rsp_identity),
  .rsp_key(rsp_key),
  .rsp_sequence(rsp_sequence),
  .rsp_PC(rsp_PC),
  .rsp_capture(rsp_capture),
  .rsp_producer(rsp_producer),
  .rsp_consumer(rsp_consumer),
  .rsp_stage_beat(rsp_stage_beat),
  .shared_valid(c_shared_valid),
  .shared_write(c_shared_write),
  .shared_ready(c_shared_ready),
  .shared_addr(c_shared_addr),
  .shared_SM(c_shared_SM),
  .shared_rank(c_shared_rank),
  .shared_wdata(c_shared_wdata),
  .shared_done(c_shared_done),
  .shared_done_ready(c_shared_done_ready),
  .shared_rdata(c_shared_rdata),
  .commit_valid(commit_valid),
  .commit_ready(commit_ready),
  .writer_identity(writer_identity),
  .writer_key(writer_key),
  .writer_stage_base(writer_stage_base),
  .writer_stage_SM(writer_stage_SM),
  .writer_K_base(writer_K_base),
  .writer_V_base(writer_V_base),
  .payload_valid(payload_valid),
  .payload_ready(payload_ready),
  .payload_identity(payload_identity),
  .payload_key(payload_key),
  .payload_sector(payload_sector),
  .payload_source_addr(payload_source_addr),
  .payload_visible(payload_visible),
  .payload_reverse(payload_reverse),
  .payload_write(payload_write),
  .payload_rdata(payload_rdata),
  .payload_req_valid(payload_req_valid),
  .payload_req_ready(payload_req_ready),
  .payload_req_write(payload_req_write),
  .payload_req_sector(payload_req_sector),
  .payload_req_source_addr(payload_req_source_addr),
  .payload_req_data(payload_req_data),
  .payload_req_rmw(payload_req_rmw),
  .payload_req_rmw_last(payload_req_rmw_last),
  .metadata_valid(c_metadata_valid),
  .metadata_ready(c_metadata_ready),
  .metadata_identity(c_metadata_identity),
  .metadata_key(c_metadata_key),
  .metadata_record(c_metadata_record),
  .consumer_valid(c_consumer_valid),
  .consumer_ready(c_consumer_ready),
  .consumer_identity(c_consumer_identity),
  .consumer_key(c_consumer_key),
  .consumer_stage(c_consumer_stage),
  .consumer_accepted(c_consumer_accepted),
  .consumer_reverse(c_consumer_reverse),
  .reader_metadata_valid(c_reader_metadata_valid),
  .reader_metadata_ready(c_reader_metadata_ready),
  .reader_metadata_identity(c_reader_metadata_identity),
  .reader_metadata_key(c_reader_metadata_key),
  .reader_metadata_stage(c_reader_metadata_stage),
  .hydrate_valid(hydrate_valid),
  .hydrate_ready(hydrate_ready),
  .hydrate_key(hydrate_key),
  .hydrate_producer(hydrate_producer),
  .drain_valid(c_drain_valid),
  .drain_ready(c_drain_ready),
  .drain_identity(c_drain_identity),
  .drain_key(c_drain_key),
  .drain_done_valid(c_drain_done_valid),
  .drain_done_ready(c_drain_done_ready),
  .drain_done_identity(c_drain_done_identity),
  .drain_done_key(c_drain_done_key),
  .drain_done_allcopies(c_drain_done_allcopies),
  .fault(core_fault),
  .writer_retained(writer_retained),
  .idle(idle)
 );
 ot_gpu_qwen_kv_shared_router #(.ENABLE(ENABLE)) shared_router (
  .clk(clk),
  .por_n(por_n),
  .run_enable(effective_enable),
  .kv_valid(c_shared_valid),
  .kv_write(c_shared_write),
  .kv_rank(c_shared_rank),
  .kv_SM(c_shared_SM),
  .kv_addr(c_shared_addr),
  .kv_wdata(c_shared_wdata),
  .kv_ready(c_shared_ready),
  .kv_done(c_shared_done),
  .kv_done_ready(c_shared_done_ready),
  .kv_rdata(c_shared_rdata),
  .native_valid(native_valid),
  .native_write(native_write),
  .native_addr(native_addr),
  .native_wdata(native_wdata),
  .native_ready(native_ready),
  .native_done(native_done),
  .native_done_ready(native_done_ready),
  .native_rdata(native_rdata),
  .service_valid(service_valid),
  .service_write(service_write),
  .service_addr(service_addr),
  .service_wdata(service_wdata),
  .service_ready(service_ready),
  .service_done(service_done),
  .service_rdata(service_rdata),
  .service_done_ready(service_done_ready),
  .fault(router_fault),
  .drained(shared_drained)
 );
 ot_gpu_qwen_kv_state_observer #(.ENABLE(ENABLE)) state_observer (
  .clk(clk),
  .por_n(por_n),
  .run_enable(effective_enable),
  .source_bound(source_bound),
  .state_base_rank0(state_base_rank0),
  .state_base_rank1(state_base_rank1),
  .observe_valid(observe_valid),
  .observe_ready(observe_ready),
  .observe_rank(observe_rank),
  .observe_source_addr(observe_source_addr),
  .observe_physical_addr(observe_physical_addr),
  .observe_owner(observe_owner),
  .observe_old_data(observe_old_data),
  .observe_new_data(observe_new_data),
  .observe_old_captured(observe_old_captured),
  .writer_retained(writer_retained),
  .writer_identity(writer_identity),
  .writer_key(writer_key),
  .writer_PC(writer_PC),
  .ACK_valid(ACK_valid),
  .ACK_ready(ACK_ready),
  .ACK_owner(ACK_owner),
  .ACK_physical_addr(ACK_physical_addr),
  .ACK_visible(ACK_visible),
  .ACK_reverse(ACK_reverse),
  .event_valid(event_valid),
  .event_ready(event_ready),
  .event_kind(event_kind),
  .event_identity(event_identity),
  .event_producer(event_producer),
  .event_key(event_key),
  .event_PC(event_PC),
  .fault(observer_fault),
  .drained(state_observer_drained)
 );
 ot_gpu_qwen_kv_metadata_join #(.ENABLE(ENABLE)) metadata_join (
  .clk(clk),
  .por_n(por_n),
  .run_enable(effective_enable),
  .event_valid(event_valid),
  .event_ready(event_ready),
  .event_kind(event_kind),
  .event_identity(event_identity),
  .event_producer(event_producer),
  .event_key(event_key),
  .command_valid(cmd_valid),
  .controller_command_ready(core_cmd_ready),
  .command_op(cmd_op),
  .command_identity(cmd_identity),
  .command_producer(cmd_producer),
  .command_key(cmd_key),
  .command_allow(command_allow),
  .metadata_valid(c_metadata_valid),
  .metadata_ready(c_metadata_ready),
  .metadata_identity(c_metadata_identity),
  .metadata_key(c_metadata_key),
  .metadata_record(c_metadata_record),
  .reader_metadata_valid(c_reader_metadata_valid),
  .reader_metadata_ready(c_reader_metadata_ready),
  .reader_metadata_identity(c_reader_metadata_identity),
  .reader_metadata_key(c_reader_metadata_key),
  .reader_metadata_stage(c_reader_metadata_stage),
  .fault(join_fault)
 );
 ot_gpu_qwen_native_consumer_drain #(.ENABLE(ENABLE)) native_consumer_drain(
  .clk(clk),
  .por_n(por_n),
  .rst_n(rst_n),
  .run_enable(effective_enable),
  .endpoint_fault(endpoint_fault || core_fault || router_fault || observer_fault || join_fault),
  .native_issue_valid(native_issue_valid),
  .native_issue_ready(native_issue_ready),
  .native_issue_tuple(native_issue_tuple),
  .native_complete_valid(native_complete_valid),
  .native_complete_ready(native_complete_ready),
  .native_complete_tuple(native_complete_tuple),
  .native_reverse_valid(native_reverse_valid),
  .native_reverse_ready(native_reverse_ready),
  .native_reverse_tuple(native_reverse_tuple),
  .consumer_valid(c_consumer_valid),
  .consumer_ready(c_consumer_ready),
  .consumer_identity(c_consumer_identity),
  .consumer_key(c_consumer_key),
  .consumer_stage(c_consumer_stage),
  .consumer_accepted(c_consumer_accepted),
  .consumer_reverse(c_consumer_reverse),
  .drain_valid(c_drain_valid),
  .drain_ready(c_drain_ready),
  .drain_identity(c_drain_identity),
  .drain_key(c_drain_key),
  .cohort_quiesce(cohort_quiesce),
  .cohort_req_valid(cohort_req_valid),
  .cohort_req_ready(cohort_req_ready),
  .cohort_identity(cohort_identity),
  .cohort_key(cohort_key),
  .cohort_rsp_valid(cohort_rsp_valid),
  .cohort_rsp_ready(cohort_rsp_ready),
  .cohort_rsp_tuple(cohort_rsp_tuple),
  .cohort_rsp_empty(cohort_rsp_empty),
  .drain_done_valid(c_drain_done_valid),
  .drain_done_ready(c_drain_done_ready),
  .drain_done_identity(c_drain_done_identity),
  .drain_done_key(c_drain_done_key),
  .drain_done_allcopies(c_drain_done_allcopies),
  .native_retained(native_retained),
  .drain_retained(drain_retained),
  .fault(reader_fault)
 );
endmodule
