// Existing-engine assembly only; external authority ports are intentionally explicit.
// ENABLE=0 by default. No external fence/ready/ACK is tied to a constant.
`timescale 1ps/1ps
module ot_gpu_qwen_hbm_integrated #(parameter bit ENABLE=0)(
 input wire stream_clk,
 output wire assembly_enabled,
 input wire sector_por_n,
 input wire sector_run_enable,
 input wire sector_local_reset,
 input wire sector_alloc_valid,
 output wire sector_alloc_ready,
 input wire [126:0] sector_alloc_source,
 input wire sector_alloc_rmw,
 input wire sector_map_valid,
 input wire sector_map_sector_clear,
 input wire [33:0] sector_map_addr,
 input wire [6:0] sector_map_PC,
 input wire [2:0] sector_map_client,
 input wire [31:0] sector_map_tag,
 input wire [3:0] sector_map_gen,
 output wire sector_grant_live,
 output wire [206:0] sector_grant_identity,
 output wire sector_grant_rmw,
 output wire [2:0] sector_grant_phase,
 output wire [5:0] sector_req_permit,
 output wire [5:0] sector_capture_permit,
 input wire sector_reverse_valid,
 output wire sector_reverse_ready,
 input wire [79:0] sector_reverse_route,
 input wire sector_reverse_write,
 input wire sector_release_valid,
 output wire sector_release_ready,
 input wire [206:0] sector_release_identity,
 output wire sector_fault,
 output wire sector_issue_ready,
 input wire kv_por_n,
 input wire kv_run_enable,
 input wire kv_quiesce,
 input wire kv_cmd_valid,
 output wire kv_cmd_ready,
 input wire [2:0] kv_cmd_op,
 input wire [63:0] kv_cmd_identity,
 input wire [19:0] kv_cmd_key,
 input wire [63:0] kv_cmd_producer,
 input wire [63:0] kv_cmd_sequence,
 input wire [10:0] kv_cmd_PC,
 input wire kv_cmd_consumer,
 input wire [3:0] kv_cmd_stage_beat,
 input wire [9:0] kv_cmd_stage_base,
 input wire [4:0] kv_cmd_stage_SM,
 input wire [511:0] kv_cmd_stage_data,
 input wire [33:0] kv_cmd_K_base,
 input wire [33:0] kv_cmd_V_base,
 output wire kv_rsp_valid,
 input wire kv_rsp_ready,
 output wire kv_rsp_fault,
 output wire [2:0] kv_rsp_op,
 output wire [63:0] kv_rsp_identity,
 output wire [19:0] kv_rsp_key,
 output wire [63:0] kv_rsp_sequence,
 output wire [10:0] kv_rsp_PC,
 output wire [511:0] kv_rsp_capture,
 output wire [63:0] kv_rsp_producer,
 output wire kv_rsp_consumer,
 output wire [3:0] kv_rsp_stage_beat,
 output wire kv_commit_valid,
 input wire kv_commit_ready,
 output wire [63:0] kv_writer_identity,
 output wire [19:0] kv_writer_key,
 output wire [9:0] kv_writer_stage_base,
 output wire [4:0] kv_writer_stage_SM,
 output wire [33:0] kv_writer_K_base,
 output wire [33:0] kv_writer_V_base,
 input wire kv_payload_valid,
 output wire kv_payload_ready,
 input wire [63:0] kv_payload_identity,
 input wire [19:0] kv_payload_key,
 input wire [8:0] kv_payload_sector,
 input wire [33:0] kv_payload_source_addr,
 input wire kv_payload_visible,
 input wire kv_payload_reverse,
 input wire kv_payload_write,
 input wire [255:0] kv_payload_rdata,
 output wire kv_payload_req_valid,
 input wire kv_payload_req_ready,
 output wire kv_payload_req_write,
 output wire [8:0] kv_payload_req_sector,
 output wire [33:0] kv_payload_req_source_addr,
 output wire [255:0] kv_payload_req_data,
 output wire kv_payload_req_rmw,
 output wire kv_payload_req_rmw_last,
 input wire kv_hydrate_valid,
 output wire kv_hydrate_ready,
 input wire [19:0] kv_hydrate_key,
 input wire [63:0] kv_hydrate_producer,
 output wire kv_writer_retained,
 output wire kv_idle,
 input wire [63:0] kv_native_valid,
 input wire [63:0] kv_native_write,
 input wire [639:0] kv_native_addr,
 input wire [32767:0] kv_native_wdata,
 output wire [63:0] kv_native_ready,
 output wire [63:0] kv_native_done,
 input wire [63:0] kv_native_done_ready,
 output wire [32767:0] kv_native_rdata,
 output wire kv_shared_drained,
 input wire kv_source_bound,
 input wire [33:0] kv_state_base_rank0,
 input wire [33:0] kv_state_base_rank1,
 input wire kv_observe_valid,
 output wire kv_observe_ready,
 input wire kv_observe_rank,
 input wire [33:0] kv_observe_source_addr,
 input wire [33:0] kv_observe_physical_addr,
 input wire [45:0] kv_observe_owner,
 input wire [255:0] kv_observe_old_data,
 input wire [255:0] kv_observe_new_data,
 input wire kv_observe_old_captured,
 input wire kv_ACK_valid,
 output wire kv_ACK_ready,
 input wire [45:0] kv_ACK_owner,
 input wire [33:0] kv_ACK_physical_addr,
 input wire kv_ACK_visible,
 input wire kv_ACK_reverse,
 output wire kv_state_observer_drained,
 input wire kv_rst_n,
 input wire kv_endpoint_fault,
 input wire kv_native_issue_valid,
 output wire kv_native_issue_ready,
 input wire [229:0] kv_native_issue_tuple,
 input wire kv_native_complete_valid,
 output wire kv_native_complete_ready,
 input wire [229:0] kv_native_complete_tuple,
 input wire kv_native_reverse_valid,
 output wire kv_native_reverse_ready,
 input wire [229:0] kv_native_reverse_tuple,
 output wire [7:0] kv_cohort_quiesce,
 output wire [7:0] kv_cohort_req_valid,
 input wire [7:0] kv_cohort_req_ready,
 output wire [63:0] kv_cohort_identity,
 output wire [19:0] kv_cohort_key,
 input wire [7:0] kv_cohort_rsp_valid,
 output wire [7:0] kv_cohort_rsp_ready,
 input wire [671:0] kv_cohort_rsp_tuple,
 input wire [7:0] kv_cohort_rsp_empty,
 output wire kv_native_retained,
 output wire kv_drain_retained,
 output wire kv_fault,
 input wire native_por_n,
 input wire native_rst_n,
 input wire native_publish_valid,
 output wire native_publish_ready,
 input wire [4095:0] native_publish_data,
 input wire [45:0] native_publish_owner46,
 input wire [63:0] native_publish_native_tag,
 input wire [63:0] native_publish_native_generation,
 input wire native_source_lease_reserved,
 input wire native_workspace_reserved,
 input wire native_issuer_namespace_reserved,
 input wire native_source_release_valid,
 input wire [54:0] native_source_release_identity,
 output wire native_source_release_ready,
 output wire native_source_lease_live,
 output wire native_workspace_lease_live,
 output wire native_source_published,
 input wire native_issuer_binding_valid,
 input wire native_visibility_enable,
 output wire native_rd_valid,
 input wire native_rd_ready,
 output wire [8:0] native_rd_a,
 output wire [8:0] native_rd_b,
 input wire native_rsp_valid,
 input wire [4095:0] native_rsp_a,
 input wire [4095:0] native_rsp_b,
 output wire native_rsp_ready,
 output wire native_wr_valid,
 input wire native_wr_ready,
 output wire [8:0] native_wr_addr,
 output wire [4095:0] native_wr_data,
 input wire native_ack_valid,
 output wire native_ack_ready,
 input wire [45:0] native_ack_owner,
 input wire [8:0] native_ack_slot,
 input wire native_ack_identity_fault,
 output wire [45:0] native_wr_owner,
 output wire native_ack_integration_fault,
 output wire native_visible_valid,
 output wire [54:0] native_visible_identity,
 output wire native_result_valid,
 input wire native_result_ready,
 output wire [4095:0] native_result,
 output wire native_consumer_accepted,
 output wire [54:0] native_consumer_identity,
 input wire native_child_reverse_valid,
 input wire [54:0] native_child_reverse_identity,
 output wire native_child_reverse_ready,
 input wire native_parent_reverse_valid,
 input wire [54:0] native_parent_reverse_identity,
 output wire native_parent_reverse_ready,
 input wire native_reverse_CDC_valid,
 input wire [54:0] native_reverse_CDC_identity,
 output wire native_reverse_CDC_ready,
 output wire native_drain_req_valid,
 output wire [54:0] native_drain_req_identity,
 output wire native_drain_req_has_owner,
 output wire native_drain_req_reset_scope,
 input wire native_drain_req_ready,
 input wire native_drain_rsp_valid,
 input wire [54:0] native_drain_rsp_identity,
 input wire native_drain_rsp_has_owner,
 input wire native_drain_rsp_reset_scope,
 input wire [8:0] native_alldrain_live,
 output wire native_drain_rsp_ready,
 output wire native_done_valid,
 input wire native_done_ready,
 output wire [63:0] native_done_native_tag,
 output wire [63:0] native_done_native_generation,
 input wire native_rearm_valid,
 input wire native_admission_stop,
 input wire native_issuer_allcopy_fenced,
 output wire native_rearm_ready,
 output wire native_exclusive_lease,
 output wire native_fault,
 input wire [63:0] sm_rst_n,
 input wire [63:0] sm_host_rd_valid,
 output wire [63:0] sm_host_rd_ready,
 input wire [575:0] sm_host_a,
 input wire [575:0] sm_host_b,
 output wire [63:0] sm_host_rsp_valid,
 input wire [63:0] sm_host_rsp_ready,
 output wire [262143:0] sm_host_rsp_a,
 output wire [262143:0] sm_host_rsp_b,
 input wire [63:0] sm_host_wr_valid,
 output wire [63:0] sm_host_wr_ready,
 input wire [575:0] sm_host_dst,
 input wire [262143:0] sm_host_wdata,
 output wire [63:0] sm_host_ack_valid,
 input wire [63:0] sm_host_ack_ready,
 input wire [63:0] sm_simd_valid,
 output wire [63:0] sm_simd_ready,
 input wire [63:0] sm_simd_mul,
 input wire [575:0] sm_simd_a,
 input wire [575:0] sm_simd_b,
 input wire [575:0] sm_simd_dst,
 output wire [63:0] sm_simd_done,
 input wire [63:0] sm_simd_done_ready,
 output wire [63:0] sm_simd_fault,
 output wire [63:0] sm_scratch_valid,
 output wire [63:0] sm_scratch_write,
 output wire [63:0] sm_scratch_ready,
 output wire [639:0] sm_scratch_addr,
 output wire [32767:0] sm_scratch_wdata,
 output wire [63:0] sm_scratch_done,
 output wire [63:0] sm_scratch_done_ready,
 output wire [32767:0] sm_scratch_rdata,
 input wire [2943:0] sm_host_owner,
 input wire [2943:0] sm_simd_owner,
 output wire [2943:0] sm_host_ack_owner,
 output wire [2943:0] sm_simd_done_owner,
 output wire [575:0] sm_host_ack_slot,
 output wire [575:0] sm_simd_done_slot,
 output wire [63:0] sm_identity_fault,
 input wire [127:0] w2_rst_n,
 input wire [127:0] w2_admission_stop,
 input wire [127:0] w2_rearm_v,
 input wire [127:0] w2_provider_fenced,
 input wire [127:0] w2_reset_fenced,
 output wire [127:0] w2_rearm_rdy,
 output wire [127:0] w2_idle,
 input wire [767:0] w2_c_req_v,
 input wire [767:0] w2_c_req_we,
 output wire [767:0] w2_c_req_rdy,
 input wire [26111:0] w2_c_req_addr,
 input wire [24575:0] w2_c_req_tag,
 input wire [3071:0] w2_c_req_gen,
 input wire [196607:0] w2_c_req_data,
 output wire [767:0] w2_c_rsp_v,
 output wire [767:0] w2_c_wr_done_v,
 input wire [767:0] w2_c_rsp_rdy,
 input wire [767:0] w2_c_wr_done_rdy,
 output wire [24575:0] w2_c_rsp_tag,
 output wire [24575:0] w2_c_wr_done_tag,
 output wire [3071:0] w2_c_rsp_gen,
 output wire [3071:0] w2_c_wr_done_gen,
 output wire [196607:0] w2_c_rsp_data,
 output wire [127:0] w2_p_req_v,
 output wire [127:0] w2_p_req_we,
 input wire [127:0] w2_p_req_rdy,
 output wire [4351:0] w2_p_req_addr,
 output wire [4479:0] w2_p_req_tag,
 output wire [511:0] w2_p_req_gen,
 output wire [32767:0] w2_p_req_data,
 input wire [127:0] w2_p_rsp_v,
 input wire [127:0] w2_p_wr_done_v,
 output wire [127:0] w2_p_rsp_rdy,
 output wire [127:0] w2_p_wr_done_ready,
 input wire [4479:0] w2_p_rsp_tag,
 input wire [4479:0] w2_p_wr_done_tag,
 input wire [511:0] w2_p_rsp_gen,
 input wire [511:0] w2_p_wr_done_gen,
 input wire [32767:0] w2_p_rsp_data,
 output wire [127:0] w2_fault,
 output wire [127:0] w2_repair_busy,
 input wire [127:0] w2_reverse_fenced
);
assign assembly_enabled=ENABLE;
wire [6:0] selected_PC = sector_grant_live ? sector_grant_identity[45:39] : sector_map_PC;
wire [767:0] raw_w2_req_rdy,guarded_c_req_v,guarded_c_rsp_rdy,guarded_c_wr_done_rdy;
for(genvar p=0;p<128;p=p+1)begin:g_guard
 wire [5:0] req_mask = selected_PC==p ? sector_req_permit : 6'b111111;
 wire [5:0] cap_mask = selected_PC==p ? sector_capture_permit : 6'b111111;
 assign guarded_c_req_v[p*6+:6]=w2_c_req_v[p*6+:6]&req_mask;
 assign w2_c_req_rdy[p*6+:6]=raw_w2_req_rdy[p*6+:6]&req_mask;
 assign guarded_c_rsp_rdy[p*6+:6]=w2_c_rsp_rdy[p*6+:6]&cap_mask;
 assign guarded_c_wr_done_rdy[p*6+:6]=w2_c_wr_done_rdy[p*6+:6]&cap_mask;
end
ot_gpu_qwen_payload_w2_authority #(.ENABLE(ENABLE),.IDENTW(207)) u_sector(
  .clk(stream_clk),
  .por_n(sector_por_n),
  .run_enable(sector_run_enable),
  .local_reset(sector_local_reset),
  .alloc_valid(sector_alloc_valid),
  .alloc_ready(sector_alloc_ready),
  .alloc_source(sector_alloc_source),
  .alloc_rmw(sector_alloc_rmw),
  .map_valid(sector_map_valid),
  .map_sector_clear(sector_map_sector_clear),
  .map_addr(sector_map_addr),
  .map_PC(sector_map_PC),
  .map_client(sector_map_client),
  .map_tag(sector_map_tag),
  .map_gen(sector_map_gen),
  .grant_live(sector_grant_live),
  .grant_identity(sector_grant_identity),
  .grant_rmw(sector_grant_rmw),
  .grant_phase(sector_grant_phase),
  .bus_PC(selected_PC),
  .caller_req_v(w2_c_req_v[selected_PC*6 +: 6]),
  .caller_req_we(w2_c_req_we[selected_PC*6 +: 6]),
  .raw_req_rdy(raw_w2_req_rdy[selected_PC*6 +: 6]),
  .caller_req_addr(w2_c_req_addr[selected_PC*204 +: 204]),
  .caller_req_tag(w2_c_req_tag[selected_PC*192 +: 192]),
  .caller_req_gen(w2_c_req_gen[selected_PC*24 +: 24]),
  .req_permit(sector_req_permit),
  .raw_rsp_v(w2_c_rsp_v[selected_PC*6 +: 6]),
  .raw_wr_done_v(w2_c_wr_done_v[selected_PC*6 +: 6]),
  .raw_rsp_tag(w2_c_rsp_tag[selected_PC*192 +: 192]),
  .raw_wr_done_tag(w2_c_wr_done_tag[selected_PC*192 +: 192]),
  .raw_rsp_gen(w2_c_rsp_gen[selected_PC*24 +: 24]),
  .raw_wr_done_gen(w2_c_wr_done_gen[selected_PC*24 +: 24]),
  .caller_rsp_rdy(w2_c_rsp_rdy[selected_PC*6 +: 6]),
  .caller_wr_done_rdy(w2_c_wr_done_rdy[selected_PC*6 +: 6]),
  .capture_permit(sector_capture_permit),
  .reverse_valid(sector_reverse_valid),
  .reverse_ready(sector_reverse_ready),
  .reverse_route(sector_reverse_route),
  .reverse_write(sector_reverse_write),
  .release_valid(sector_release_valid),
  .release_ready(sector_release_ready),
  .release_identity(sector_release_identity),
  .fault(sector_fault),
  .issue_ready(sector_issue_ready)
 );
ot_gpu_qwen_joined_kv #(.ENABLE(ENABLE)) u_kv(
  .clk(stream_clk),
  .por_n(kv_por_n),
  .run_enable(kv_run_enable),
  .quiesce(kv_quiesce),
  .cmd_valid(kv_cmd_valid),
  .cmd_ready(kv_cmd_ready),
  .cmd_op(kv_cmd_op),
  .cmd_identity(kv_cmd_identity),
  .cmd_key(kv_cmd_key),
  .cmd_producer(kv_cmd_producer),
  .cmd_sequence(kv_cmd_sequence),
  .cmd_PC(kv_cmd_PC),
  .cmd_consumer(kv_cmd_consumer),
  .cmd_stage_beat(kv_cmd_stage_beat),
  .cmd_stage_base(kv_cmd_stage_base),
  .cmd_stage_SM(kv_cmd_stage_SM),
  .cmd_stage_data(kv_cmd_stage_data),
  .cmd_K_base(kv_cmd_K_base),
  .cmd_V_base(kv_cmd_V_base),
  .rsp_valid(kv_rsp_valid),
  .rsp_ready(kv_rsp_ready),
  .rsp_fault(kv_rsp_fault),
  .rsp_op(kv_rsp_op),
  .rsp_identity(kv_rsp_identity),
  .rsp_key(kv_rsp_key),
  .rsp_sequence(kv_rsp_sequence),
  .rsp_PC(kv_rsp_PC),
  .rsp_capture(kv_rsp_capture),
  .rsp_producer(kv_rsp_producer),
  .rsp_consumer(kv_rsp_consumer),
  .rsp_stage_beat(kv_rsp_stage_beat),
  .commit_valid(kv_commit_valid),
  .commit_ready(kv_commit_ready),
  .writer_identity(kv_writer_identity),
  .writer_key(kv_writer_key),
  .writer_stage_base(kv_writer_stage_base),
  .writer_stage_SM(kv_writer_stage_SM),
  .writer_K_base(kv_writer_K_base),
  .writer_V_base(kv_writer_V_base),
  .payload_valid(kv_payload_valid),
  .payload_ready(kv_payload_ready),
  .payload_identity(kv_payload_identity),
  .payload_key(kv_payload_key),
  .payload_sector(kv_payload_sector),
  .payload_source_addr(kv_payload_source_addr),
  .payload_visible(kv_payload_visible),
  .payload_reverse(kv_payload_reverse),
  .payload_write(kv_payload_write),
  .payload_rdata(kv_payload_rdata),
  .payload_req_valid(kv_payload_req_valid),
  .payload_req_ready(kv_payload_req_ready),
  .payload_req_write(kv_payload_req_write),
  .payload_req_sector(kv_payload_req_sector),
  .payload_req_source_addr(kv_payload_req_source_addr),
  .payload_req_data(kv_payload_req_data),
  .payload_req_rmw(kv_payload_req_rmw),
  .payload_req_rmw_last(kv_payload_req_rmw_last),
  .hydrate_valid(kv_hydrate_valid),
  .hydrate_ready(kv_hydrate_ready),
  .hydrate_key(kv_hydrate_key),
  .hydrate_producer(kv_hydrate_producer),
  .writer_retained(kv_writer_retained),
  .idle(kv_idle),
  .native_valid(kv_native_valid),
  .native_write(kv_native_write),
  .native_addr(kv_native_addr),
  .native_wdata(kv_native_wdata),
  .native_ready(kv_native_ready),
  .native_done(kv_native_done),
  .native_done_ready(kv_native_done_ready),
  .native_rdata(kv_native_rdata),
  .service_valid(sm_scratch_valid),
  .service_write(sm_scratch_write),
  .service_addr(sm_scratch_addr),
  .service_wdata(sm_scratch_wdata),
  .service_ready(sm_scratch_ready),
  .service_done(sm_scratch_done),
  .service_rdata(sm_scratch_rdata),
  .service_done_ready(sm_scratch_done_ready),
  .shared_drained(kv_shared_drained),
  .source_bound(kv_source_bound),
  .state_base_rank0(kv_state_base_rank0),
  .state_base_rank1(kv_state_base_rank1),
  .observe_valid(kv_observe_valid),
  .observe_ready(kv_observe_ready),
  .observe_rank(kv_observe_rank),
  .observe_source_addr(kv_observe_source_addr),
  .observe_physical_addr(kv_observe_physical_addr),
  .observe_owner(kv_observe_owner),
  .observe_old_data(kv_observe_old_data),
  .observe_new_data(kv_observe_new_data),
  .observe_old_captured(kv_observe_old_captured),
  .ACK_valid(kv_ACK_valid),
  .ACK_ready(kv_ACK_ready),
  .ACK_owner(kv_ACK_owner),
  .ACK_physical_addr(kv_ACK_physical_addr),
  .ACK_visible(kv_ACK_visible),
  .ACK_reverse(kv_ACK_reverse),
  .state_observer_drained(kv_state_observer_drained),
  .rst_n(kv_rst_n),
  .endpoint_fault(kv_endpoint_fault),
  .native_issue_valid(kv_native_issue_valid),
  .native_issue_ready(kv_native_issue_ready),
  .native_issue_tuple(kv_native_issue_tuple),
  .native_complete_valid(kv_native_complete_valid),
  .native_complete_ready(kv_native_complete_ready),
  .native_complete_tuple(kv_native_complete_tuple),
  .native_reverse_valid(kv_native_reverse_valid),
  .native_reverse_ready(kv_native_reverse_ready),
  .native_reverse_tuple(kv_native_reverse_tuple),
  .cohort_quiesce(kv_cohort_quiesce),
  .cohort_req_valid(kv_cohort_req_valid),
  .cohort_req_ready(kv_cohort_req_ready),
  .cohort_identity(kv_cohort_identity),
  .cohort_key(kv_cohort_key),
  .cohort_rsp_valid(kv_cohort_rsp_valid),
  .cohort_rsp_ready(kv_cohort_rsp_ready),
  .cohort_rsp_tuple(kv_cohort_rsp_tuple),
  .cohort_rsp_empty(kv_cohort_rsp_empty),
  .native_retained(kv_native_retained),
  .drain_retained(kv_drain_retained),
  .fault(kv_fault)
 );
ot_gpu_pc40_native_connector_r5 #(.ENABLE(ENABLE)) u_native(
  .clk(stream_clk),
  .por_n(native_por_n),
  .rst_n(native_rst_n),
  .publish_valid(native_publish_valid),
  .publish_ready(native_publish_ready),
  .publish_data(native_publish_data),
  .publish_owner46(native_publish_owner46),
  .publish_native_tag(native_publish_native_tag),
  .publish_native_generation(native_publish_native_generation),
  .source_lease_reserved(native_source_lease_reserved),
  .workspace_reserved(native_workspace_reserved),
  .issuer_namespace_reserved(native_issuer_namespace_reserved),
  .source_release_valid(native_source_release_valid),
  .source_release_identity(native_source_release_identity),
  .source_release_ready(native_source_release_ready),
  .source_lease_live(native_source_lease_live),
  .workspace_lease_live(native_workspace_lease_live),
  .source_published(native_source_published),
  .issuer_binding_valid(native_issuer_binding_valid),
  .visibility_enable(native_visibility_enable),
  .rd_valid(native_rd_valid),
  .rd_ready(native_rd_ready),
  .rd_a(native_rd_a),
  .rd_b(native_rd_b),
  .rsp_valid(native_rsp_valid),
  .rsp_a(native_rsp_a),
  .rsp_b(native_rsp_b),
  .rsp_ready(native_rsp_ready),
  .wr_valid(native_wr_valid),
  .wr_ready(native_wr_ready),
  .wr_addr(native_wr_addr),
  .wr_data(native_wr_data),
  .ack_valid(native_ack_valid),
  .ack_ready(native_ack_ready),
  .ack_owner(native_ack_owner),
  .ack_slot(native_ack_slot),
  .ack_identity_fault(native_ack_identity_fault),
  .wr_owner(native_wr_owner),
  .ack_integration_fault(native_ack_integration_fault),
  .visible_valid(native_visible_valid),
  .visible_identity(native_visible_identity),
  .result_valid(native_result_valid),
  .result_ready(native_result_ready),
  .result(native_result),
  .consumer_accepted(native_consumer_accepted),
  .consumer_identity(native_consumer_identity),
  .child_reverse_valid(native_child_reverse_valid),
  .child_reverse_identity(native_child_reverse_identity),
  .child_reverse_ready(native_child_reverse_ready),
  .parent_reverse_valid(native_parent_reverse_valid),
  .parent_reverse_identity(native_parent_reverse_identity),
  .parent_reverse_ready(native_parent_reverse_ready),
  .reverse_CDC_valid(native_reverse_CDC_valid),
  .reverse_CDC_identity(native_reverse_CDC_identity),
  .reverse_CDC_ready(native_reverse_CDC_ready),
  .drain_req_valid(native_drain_req_valid),
  .drain_req_identity(native_drain_req_identity),
  .drain_req_has_owner(native_drain_req_has_owner),
  .drain_req_reset_scope(native_drain_req_reset_scope),
  .drain_req_ready(native_drain_req_ready),
  .drain_rsp_valid(native_drain_rsp_valid),
  .drain_rsp_identity(native_drain_rsp_identity),
  .drain_rsp_has_owner(native_drain_rsp_has_owner),
  .drain_rsp_reset_scope(native_drain_rsp_reset_scope),
  .alldrain_live(native_alldrain_live),
  .drain_rsp_ready(native_drain_rsp_ready),
  .done_valid(native_done_valid),
  .done_ready(native_done_ready),
  .done_native_tag(native_done_native_tag),
  .done_native_generation(native_done_native_generation),
  .rearm_valid(native_rearm_valid),
  .admission_stop(native_admission_stop),
  .issuer_allcopy_fenced(native_issuer_allcopy_fenced),
  .rearm_ready(native_rearm_ready),
  .exclusive_lease(native_exclusive_lease),
  .fault(native_fault)
 );
for(genvar i=0;i<64;i=i+1) begin:g_sm
 ot_gpu_full_sm_service #(.ENABLE(ENABLE),.ACK_ID(1)) u_sm(
  .clk(stream_clk),
  .rst_n(sm_rst_n[i]),
  .host_rd_valid(sm_host_rd_valid[i]),
  .host_rd_ready(sm_host_rd_ready[i]),
  .host_a(sm_host_a[i*9 +: 9]),
  .host_b(sm_host_b[i*9 +: 9]),
  .host_rsp_valid(sm_host_rsp_valid[i]),
  .host_rsp_ready(sm_host_rsp_ready[i]),
  .host_rsp_a(sm_host_rsp_a[i*4096 +: 4096]),
  .host_rsp_b(sm_host_rsp_b[i*4096 +: 4096]),
  .host_wr_valid(sm_host_wr_valid[i]),
  .host_wr_ready(sm_host_wr_ready[i]),
  .host_dst(sm_host_dst[i*9 +: 9]),
  .host_wdata(sm_host_wdata[i*4096 +: 4096]),
  .host_ack_valid(sm_host_ack_valid[i]),
  .host_ack_ready(sm_host_ack_ready[i]),
  .simd_valid(sm_simd_valid[i]),
  .simd_ready(sm_simd_ready[i]),
  .simd_mul(sm_simd_mul[i]),
  .simd_a(sm_simd_a[i*9 +: 9]),
  .simd_b(sm_simd_b[i*9 +: 9]),
  .simd_dst(sm_simd_dst[i*9 +: 9]),
  .simd_done(sm_simd_done[i]),
  .simd_done_ready(sm_simd_done_ready[i]),
  .simd_fault(sm_simd_fault[i]),
  .scratch_valid(sm_scratch_valid[i]),
  .scratch_write(sm_scratch_write[i]),
  .scratch_ready(sm_scratch_ready[i]),
  .scratch_addr(sm_scratch_addr[i*10 +: 10]),
  .scratch_wdata(sm_scratch_wdata[i*512 +: 512]),
  .scratch_done(sm_scratch_done[i]),
  .scratch_done_ready(sm_scratch_done_ready[i]),
  .scratch_rdata(sm_scratch_rdata[i*512 +: 512]),
  .host_owner(sm_host_owner[i*46 +: 46]),
  .simd_owner(sm_simd_owner[i*46 +: 46]),
  .host_ack_owner(sm_host_ack_owner[i*46 +: 46]),
  .simd_done_owner(sm_simd_done_owner[i*46 +: 46]),
  .host_ack_slot(sm_host_ack_slot[i*9 +: 9]),
  .simd_done_slot(sm_simd_done_slot[i*9 +: 9]),
  .identity_fault(sm_identity_fault[i])
 );
 end
for(genvar i=0;i<128;i=i+1) begin:g_w2
 ot_w2_nc6_protected_completion_reset_quarantine #(.OPT_EXACT(ENABLE),.OPT_RESET_QUARANTINE(ENABLE),.PC_ID(7'(i))) u_w2(
  .clk(stream_clk),
  .rst_n(w2_rst_n[i]),
  .admission_stop(w2_admission_stop[i]),
  .rearm_v(w2_rearm_v[i]),
  .provider_fenced(w2_provider_fenced[i]),
  .reset_fenced(w2_reset_fenced[i]),
  .rearm_rdy(w2_rearm_rdy[i]),
  .idle(w2_idle[i]),
  .c_req_v(guarded_c_req_v[i*6 +: 6]),
  .c_req_we(w2_c_req_we[i*6 +: 6]),
  .c_req_rdy(raw_w2_req_rdy[i*6 +: 6]),
  .c_req_addr(w2_c_req_addr[i*204 +: 204]),
  .c_req_tag(w2_c_req_tag[i*192 +: 192]),
  .c_req_gen(w2_c_req_gen[i*24 +: 24]),
  .c_req_data(w2_c_req_data[i*1536 +: 1536]),
  .c_rsp_v(w2_c_rsp_v[i*6 +: 6]),
  .c_wr_done_v(w2_c_wr_done_v[i*6 +: 6]),
  .c_rsp_rdy(guarded_c_rsp_rdy[i*6 +: 6]),
  .c_wr_done_rdy(guarded_c_wr_done_rdy[i*6 +: 6]),
  .c_rsp_tag(w2_c_rsp_tag[i*192 +: 192]),
  .c_wr_done_tag(w2_c_wr_done_tag[i*192 +: 192]),
  .c_rsp_gen(w2_c_rsp_gen[i*24 +: 24]),
  .c_wr_done_gen(w2_c_wr_done_gen[i*24 +: 24]),
  .c_rsp_data(w2_c_rsp_data[i*1536 +: 1536]),
  .p_req_v(w2_p_req_v[i]),
  .p_req_we(w2_p_req_we[i]),
  .p_req_rdy(w2_p_req_rdy[i]),
  .p_req_addr(w2_p_req_addr[i*34 +: 34]),
  .p_req_tag(w2_p_req_tag[i*35 +: 35]),
  .p_req_gen(w2_p_req_gen[i*4 +: 4]),
  .p_req_data(w2_p_req_data[i*256 +: 256]),
  .p_rsp_v(w2_p_rsp_v[i]),
  .p_wr_done_v(w2_p_wr_done_v[i]),
  .p_rsp_rdy(w2_p_rsp_rdy[i]),
  .p_wr_done_ready(w2_p_wr_done_ready[i]),
  .p_rsp_tag(w2_p_rsp_tag[i*35 +: 35]),
  .p_wr_done_tag(w2_p_wr_done_tag[i*35 +: 35]),
  .p_rsp_gen(w2_p_rsp_gen[i*4 +: 4]),
  .p_wr_done_gen(w2_p_wr_done_gen[i*4 +: 4]),
  .p_rsp_data(w2_p_rsp_data[i*256 +: 256]),
  .fault(w2_fault[i]),
  .repair_busy(w2_repair_busy[i]),
  .reverse_fenced(w2_reverse_fenced[i])
 );
 end
endmodule
