`timescale 1ns/1ps
`default_nettype none
// Default-off wiring facade. Physical x-master closure does not qualify these bus pins.
module hfd_mtp_native_cp_stop #(parameter integer ENABLE=0) (
  input wire clk, input wire rst_n,
  input wire [196:0] f_cmdproc,
  output wire [516:0] t_cmdproc,
  input wire [522:0] f_su_red,
  input wire [58:0] f_router,
  output wire [57:0] t_router,
  output wire [18:0] t_coll,
  input wire [0:0] f_coll
);
  generate if (ENABLE == 0) begin: off
    assign t_cmdproc = '0;
    assign t_router = '0;
    assign t_coll = '0;
  end else begin: on
    hfd_mtp_x_cp_stop #(.EXTERNAL_AM(1)) core (
      .clk(clk), .rst_n(rst_n),
      .start(f_cmdproc[0 +: 1]),
      .cfg_gamma(f_cmdproc[1 +: 4]),
      .cfg_force(f_cmdproc[5 +: 1]),
      .cfg_ngen(f_cmdproc[6 +: 21]),
      .cfg_plen(f_cmdproc[27 +: 21]),
      .p_tok(f_cmdproc[48 +: 17]),
      .f_tok(f_cmdproc[65 +: 17]),
      .cmd_ready(f_cmdproc[82 +: 1]),
      .eng_done(f_cmdproc[83 +: 1]),
      .sr_v(f_cmdproc[84 +: 1]),
      .sr_kind(f_cmdproc[85 +: 4]),
      .sr_idx(f_cmdproc[89 +: 16]),
      .sr_pos(f_cmdproc[105 +: 32]),
      .u_clr(f_cmdproc[137 +: 1]),
      .u_flush(f_cmdproc[138 +: 1]),
      .e_ready(f_cmdproc[139 +: 1]),
      .cfg_eos_en(f_cmdproc[140 +: 1]),
      .cfg_eos(f_cmdproc[141 +: 17]),
      .cfg_maxpos(f_cmdproc[158 +: 21]),
      .cp_am_v(f_cmdproc[179 +: 1]),
      .cp_am_idx(f_cmdproc[180 +: 17]),
      .p_addr(t_cmdproc[0 +: 20]),
      .f_addr(t_cmdproc[20 +: 23]),
      .e_v(t_cmdproc[43 +: 1]),
      .e_tok(t_cmdproc[44 +: 17]),
      .e_idx(t_cmdproc[61 +: 20]),
      .done(t_cmdproc[81 +: 1]),
      .cmd_v(t_cmdproc[82 +: 1]),
      .cmd_op(t_cmdproc[83 +: 4]),
      .cmd_idx(t_cmdproc[87 +: 8]),
      .cmd_ncol(t_cmdproc[95 +: 4]),
      .cmd_pos(t_cmdproc[99 +: 32]),
      .cmd_tok1(t_cmdproc[131 +: 17]),
      .cmd_toks(t_cmdproc[148 +: 136]),
      .am_v(t_cmdproc[284 +: 1]),
      .am_idx(t_cmdproc[285 +: 17]),
      .am_fault(t_cmdproc[302 +: 1]),
      .sr_ready(t_cmdproc[303 +: 1]),
      .sa_v(t_cmdproc[304 +: 1]),
      .sa_addr(t_cmdproc[305 +: 32]),
      .sa_tok(t_cmdproc[337 +: 17]),
      .sa_pad(t_cmdproc[354 +: 1]),
      .sa_last(t_cmdproc[355 +: 1]),
      .sa_err(t_cmdproc[356 +: 1]),
      .n_committed(t_cmdproc[357 +: 32]),
      .step_v(t_cmdproc[389 +: 1]),
      .step_a(t_cmdproc[390 +: 3]),
      .step_g(t_cmdproc[393 +: 4]),
      .steps(t_cmdproc[397 +: 21]),
      .cyc_total(t_cmdproc[418 +: 32]),
      .cyc_engine(t_cmdproc[450 +: 32]),
      .cyc_markov(t_cmdproc[482 +: 32]),
      .stop_status(t_cmdproc[514 +: 3]),
      .lg_v(f_su_red[0 +: 1]),
      .lg_last(f_su_red[1 +: 1]),
      .lg_bias_en(f_su_red[2 +: 1]),
      .lg_mask(f_su_red[3 +: 8]),
      .lg_vals(f_su_red[11 +: 256]),
      .lg_bias(f_su_red[267 +: 256]),
      .x_v(f_router[0 +: 1]),
      .x_draft(f_router[1 +: 1]),
      .x_ids(f_router[2 +: 54]),
      .x_col(f_router[56 +: 3]),
      .t_v(t_router[0 +: 1]),
      .t_ids(t_router[1 +: 54]),
      .t_col(t_router[55 +: 3]),
      .u_v(t_coll[0 +: 1]),
      .u_id(t_coll[1 +: 9]),
      .u_mask(t_coll[10 +: 8]),
      .u_last(t_coll[18 +: 1]),
      .u_ready(f_coll[0 +: 1])
    );
  end endgenerate
endmodule
`default_nettype wire
