// PIN-ACCURATE BLACK BOX (tools/hbm_phy_bb.py): host PHY / controller, digital-facing side only
(* blackbox *)
module ot_hbm_host_phy (
    input  wire clk,
    output wire s_awvalid,
    input  wire s_awready,
    output wire [11:0] s_awaddr,
    output wire s_wvalid,
    input  wire s_wready,
    output wire [31:0] s_wdata,
    output wire [3:0] s_wstrb,
    input  wire s_bvalid,
    output wire s_bready,
    output wire s_arvalid,
    input  wire s_arready,
    output wire [11:0] s_araddr,
    input  wire s_rvalid,
    output wire s_rready,
    input  wire [31:0] s_rdata,
    output wire h_dma_arvalid,
    input  wire h_dma_arready,
    output wire [63:0] h_dma_araddr,
    input  wire h_dma_rvalid,
    output wire h_dma_rready,
    input  wire [63:0] h_dma_rdata,
    input  wire [1:0] h_dma_rresp,
    input  wire h_dma_rlast,
    output wire h_dma_awvalid,
    input  wire h_dma_awready,
    output wire [63:0] h_dma_awaddr,
    output wire h_dma_wvalid,
    input  wire h_dma_wready,
    output wire [63:0] h_dma_wdata,
    output wire [7:0] h_dma_wstrb,
    input  wire h_dma_bvalid,
    output wire h_dma_bready,
    input  wire [1:0] h_dma_bresp
);
endmodule
