#!/bin/bash
# CLAUDE S81-RERUN: route SDC of a forwarded-link station die view (dsfd_stnh_* / dsfd_stnv_*: one ot_fwd_link_stage
# per lane slice, data flops on the FALLING edge of the forwarded clock fi0, fo0 = kept inverter of fi0).
# usage: make_sdc_stn.sh <L_ps> <out.sdc>.  L = the calibrated SS insertion (closure loop CK_SS_MEAN); POST_CTS
# (common/post_cts_vclk.tcl) re-sets vclk to the measured WC midpoint, output min delay from the BC tree.
# A hop is half-cycle by construction: the upstream station launches on its falling edge = this station's fi0 rising
# edge (inverted forwarded clock, travelling beside the data), this station captures on the falling edge; so input and
# output budgets are against vclk RISE with the capture/launch on core_clk FALL (T/2 paths).  The clock travels with
# the data (same forwarded clock, no die clock-arrival difference): IO 0.2 T (clk->q + wire mismatch of the hop).
# fo0 is a forwarded clock, not a data output (false path as data).  Routed at 123 ps setup uncertainty (770 ps
# effective), signed off at 60 ps (common/signoff_unc60.sdc).
L=${1:?L}; O=${2:?out}
cat > $O <<EOT
# generated by physical/s81_die_views/glue/make_sdc_stn.sh $L
create_clock -name core_clk -period 833.333 [get_ports {fi0[0]}]
create_clock -name vclk -period 833.333
set_clock_latency $L [get_clocks vclk]
set_clock_uncertainty -setup 123 [all_clocks]
set_clock_uncertainty -hold 25 [all_clocks]
set_input_delay 166.667 -clock vclk [get_ports {di*}]
set_input_delay -min 0 -clock vclk [get_ports {di*}]
set_output_delay 166.667 -clock vclk [get_ports {do*}]
set_output_delay -min 0 -clock vclk [get_ports {do*}]
set_false_path -to [get_ports {fo*}]
set_max_fanout 32 [current_design]
EOT
