export DESIGN_NICKNAME = hgi_quant_config_audit
export DESIGN_NAME = ot_hgi_quant_decode
export PLATFORM = asap7
export VERILOG_FILES = /src/rtl/hbm_accel/generic/ot_hgi_quant_decode.sv /src/physical/hbm_accel_die_views/common/ot_hfd_oreg1.sv /src/physical/hbm_accel_die_views/quant/rtl/ot_hfd_actquant_m.sv /src/rtl/hbm_accel/generic/ot_hgi_fp4qdq.sv /src/rtl/hdc/ot_hdc_delay.sv /src/rtl/hdc/ot_hdc_fpu.sv /src/rtl/hdc/ot_hdc_fp32_mul_pipe.sv /src/rtl/hdc/ot_hdc_sfu.sv /src/rtl/hdc/ot_hdc_fastfp.sv /src/rtl/hdc/ot_hdc_fastfp_lat_f12.sv /src/rtl/hdc/ot_hdc_fp32_f12.sv /src/rtl/hdc/ot_hdc_prefix.sv
export VERILOG_DEFINES = -DSYNTHESIS
export SDC_FILE = /work/constraint.sdc
export CORE_UTILIZATION = 20
export CORE_ASPECT_RATIO = 1
export CORE_MARGIN = 2
export PLACE_DENSITY = 0.5
export PLACE_DENSITY_LB_ADDON = 0.05
export SYNTH_REPEATABLE_BUILD = 1
export SYNTH_HIERARCHICAL = 0
export SYNTH_MEMORY_MAX_BITS = 65536
export LEC_CHECK = 0
export TNS_END_PERCENT = 100
export HOLD_SLACK_MARGIN = 0
export SETUP_SLACK_MARGIN = 0
export SKIP_REPORT_METRICS = 0
export REPORT_CLOCK_SKEW = 1
export CORNER = WC
export NUM_CORES = 12
export OT_HOLD_MM = 1
export WC_NLDM_LIB_FILES = $(TC_NLDM_LIB_FILES)
export HOLD_SLACK_MARGIN = 10
export CORNERS = WC BC
export WC_LIB_FILES = $(WC_NLDM_LIB_FILES)
export BC_LIB_FILES = $(BC_NLDM_LIB_FILES)
