`timescale 1ns/1ps
// Synthesis declaration for the full NPC32 WINDOW leaf at source81ce7328c.
// Ports copied from the actual component top. This has no simulation behavior.
// Parent P&R must supply that leaf's actual LEF and its own SS/FF timing views;
// this declaration supplies no area, memory, clock/load, or closure credit.
// Use only the measured default parameter shape; no native S81 wiring.
(* blackbox *)
module ot_dsrom_window_pipeline_context #(
    parameter integer NPC=32, AW=30, TAGW=16, STAGW=17, LENW=4, BEATW=4, DW=256, WTAGW=13,
    parameter integer SEC_W=30, HAW=30, POS_W=21, USER_W=10
) (
    input wire clk, rst_n,
    input wire retain_qk, retain_pv, retain_complete, retain_invalidate,
    input wire [15:0] retain_generation,
    input wire [SEC_W-1:0] region_base_sector, region_sector_count,
    input wire prime_v,
    output wire prime_ready,
    input wire [USER_W-1:0] prime_user,
    input wire [POS_W-1:0] prime_row,
    input wire blk_v,
    output wire blk_ready,
    input wire [USER_W-1:0] blk_user,
    input wire [POS_W-1:0] blk_row,
    input wire [3:0] blk_idx,
    input wire [255:0] blk_codes,
    input wire [7:0] blk_scale,
    input wire start_v,
    output wire start_ready,
    input wire [USER_W-1:0] start_user,
    input wire [POS_W-1:0] start_first,
    input wire [7:0] start_count,
    output wire staged_v,
    input wire stream_go,
    output wire busy, done, fault,
    output wire [4:0] fault_code,
    output wire [31:0] refill_cycles, sectors_read,
    output wire [31:0] rows_fetched, blocks_written, sectors_written,
    output wire [7:0] rows_refilled,
    output wire kv_v,
    input wire kv_ready,
    output wire [3:0] kv_m,
    output wire [4*16*265-1:0] kv_w,
    output wire [3:0] m_v,
    input wire [3:0] m_rdy,
    output wire [4*HAW-1:0] m_addr,
    output wire [15:0] m_len,
    output wire [4*TAGW-1:0] m_tag,
    output wire [3:0] m_we,
    output wire [1023:0] m_wdata,
    output wire [127:0] m_wstrb,
    input wire [3:0] m_wr_done,
    input wire [3:0] s_v,
    output wire [3:0] s_rdy,
    input wire [4*TAGW-1:0] s_tag,
    input wire [15:0] s_beat,
    input wire [1023:0] s_data,
    input wire [NPC-1:0] a_v, a_rsp_rdy, g_v, g_rsp_rdy, h_rdy, h_wr_done, r_v,
    input wire [NPC*AW-1:0] a_addr, g_addr,
    input wire [NPC*LENW-1:0] a_len, g_len,
    input wire [NPC*STAGW-1:0] a_tag, r_tag,
    input wire [NPC*WTAGW-1:0] g_tag,
    input wire [NPC-1:0] a_we,
    input wire [NPC*DW-1:0] a_wdata, r_data,
    input wire [NPC*DW/8-1:0] a_wstrb,
    input wire [NPC*BEATW-1:0] r_beat,
    output wire [NPC-1:0] a_rdy, a_wr_done, a_rsp_v, g_rdy, g_rsp_v, h_v, h_we, r_rdy,
    output wire [NPC*STAGW-1:0] a_rsp_tag, h_tag,
    output wire [NPC*BEATW-1:0] a_rsp_beat, g_rsp_beat,
    output wire [NPC*DW-1:0] a_rsp_data, g_rsp_data, h_wdata,
    output wire [NPC*WTAGW-1:0] g_rsp_tag,
    output wire [NPC*AW-1:0] h_addr,
    output wire [NPC*LENW-1:0] h_len,
    output wire [NPC*DW/8-1:0] h_wstrb,
    output wire [31:0] la_load_cycles, wg, ah,
    output wire wm_fault
);
endmodule
