`timescale 1ns/1ps
// Verification-only visibility wrapper.  The qualified adapter source remains
// byte-for-byte unchanged; this wrapper promotes its actual scheduled tree
// parent to the independent shipped-prefix checker.
module ot_a3_shipped_prefix_multicast_adapter_wrapper (
    input  wire          clk,
    input  wire          rst_n,
    input  wire          start,
    input  wire [31:0]   issue_pc,
    input  wire [7:0]    issue_major,
    input  wire [7:0]    issue_sub,
    input  wire [31:0]   issue_descriptor_id,
    input  wire [31:0]   observed_view_count,
    input  wire [31:0]   state_descriptor_count,
    input  wire [31:0]   topology_descriptor_id,
    input  wire [31:0]   local_object_descriptor_id,
    input  wire [31:0]   remote_object_descriptor_id,
    input  wire [31:0]   counter_descriptor_id,
    input  wire [1535:0] communication_record,
    input  wire [2047:0] topology_record,
    input  wire [1023:0] local_object_record,
    input  wire [1023:0] remote_object_record,
    input  wire [1023:0] counter_record,
    output wire          source_read_valid,
    input  wire          source_read_ready,
    output wire [31:0]   source_read_object_id,
    output wire [63:0]   source_read_offset,
    input  wire          source_response_valid,
    output wire          source_response_ready,
    input  wire [31:0]   source_response_data,
    input  wire          source_response_error,
    output wire          remote_write_valid,
    input  wire          remote_write_ready,
    output wire [31:0]   remote_write_object_id,
    output wire [15:0]   remote_write_participant,
    output wire [63:0]   remote_write_offset,
    output wire [31:0]   remote_write_data,
    input  wire          inject_crc_error,
    output wire          busy,
    output wire          done,
    output wire          failed,
    output wire [15:0]   trap_class,
    output wire [7:0]    refusal_reason,
    output wire [31:0]   messages_sent,
    output wire [31:0]   messages_received,
    output wire [63:0]   bytes_sent,
    output wire [63:0]   bytes_received,
    output wire [31:0]   remote_write_count,
    output wire [31:0]   payload_flits_delivered,
    output wire [31:0]   wire_flits_transmitted,
    output wire [31:0]   replayed_flits,
    output wire [31:0]   retry_events,
    output wire [31:0]   credit_stall_cycles,
    output wire [31:0]   crc_errors,
    output wire [31:0]   sequence_errors,
    output wire [7:0]    tree_source
);
    ot_a3_wafer_multicast_adapter u_adapter (
        .clk(clk), .rst_n(rst_n), .start(start),
        .issue_pc(issue_pc), .issue_major(issue_major),
        .issue_sub(issue_sub), .issue_descriptor_id(issue_descriptor_id),
        .observed_view_count(observed_view_count),
        .state_descriptor_count(state_descriptor_count),
        .topology_descriptor_id(topology_descriptor_id),
        .local_object_descriptor_id(local_object_descriptor_id),
        .remote_object_descriptor_id(remote_object_descriptor_id),
        .counter_descriptor_id(counter_descriptor_id),
        .communication_record(communication_record),
        .topology_record(topology_record),
        .local_object_record(local_object_record),
        .remote_object_record(remote_object_record),
        .counter_record(counter_record),
        .source_read_valid(source_read_valid),
        .source_read_ready(source_read_ready),
        .source_read_object_id(source_read_object_id),
        .source_read_offset(source_read_offset),
        .source_response_valid(source_response_valid),
        .source_response_ready(source_response_ready),
        .source_response_data(source_response_data),
        .source_response_error(source_response_error),
        .remote_write_valid(remote_write_valid),
        .remote_write_ready(remote_write_ready),
        .remote_write_object_id(remote_write_object_id),
        .remote_write_participant(remote_write_participant),
        .remote_write_offset(remote_write_offset),
        .remote_write_data(remote_write_data),
        .inject_crc_error(inject_crc_error),
        .busy(busy), .done(done), .failed(failed),
        .trap_class(trap_class), .refusal_reason(refusal_reason),
        .messages_sent(messages_sent), .messages_received(messages_received),
        .bytes_sent(bytes_sent), .bytes_received(bytes_received),
        .remote_write_count(remote_write_count),
        .payload_flits_delivered(payload_flits_delivered),
        .wire_flits_transmitted(wire_flits_transmitted),
        .replayed_flits(replayed_flits), .retry_events(retry_events),
        .credit_stall_cycles(credit_stall_cycles), .crc_errors(crc_errors),
        .sequence_errors(sequence_errors)
    );

    assign tree_source = u_adapter.tree_source;
endmodule
