// Host-side connections of ot_host_if in the tb_host_*.sv tops (see tb_host_ports.svh).
        .clk(clk), .rst_n(rst_n),
        .s_awvalid(s_awvalid), .s_awready(s_awready), .s_awaddr(s_awaddr),
        .s_wvalid(s_wvalid), .s_wready(s_wready), .s_wdata(s_wdata), .s_wstrb(4'hF),
        .s_bvalid(s_bvalid), .s_bready(s_bready), .s_bresp(),
        .s_arvalid(s_arvalid), .s_arready(s_arready), .s_araddr(s_araddr),
        .s_rvalid(s_rvalid), .s_rready(s_rready), .s_rdata(s_rdata), .s_rresp(),
        .m_arvalid(m_arvalid), .m_arready(m_arready), .m_araddr(m_araddr), .m_arlen(), .m_arsize(),
        .m_rvalid(m_rvalid), .m_rready(), .m_rdata(m_rdata), .m_rresp(m_rresp), .m_rlast(1'b1),
        .m_awvalid(m_awvalid), .m_awready(m_awready), .m_awaddr(m_awaddr), .m_awlen(), .m_awsize(),
        .m_wvalid(m_wvalid), .m_wready(m_wready), .m_wdata(m_wdata), .m_wstrb(m_wstrb), .m_wlast(),
        .m_bvalid(m_bvalid), .m_bready(), .m_bresp(m_bresp),
        .irq(irq),
        .pb_we(pb_we), .pb_waddr(pb_waddr), .pb_wdata(pb_wdata), .pb_re(pb_re), .pb_raddr(pb_raddr), .pb_q(pb_q),
