`timescale 1ns/1ps
module tb_s81_kvt_source_stride;
    reg clk=0, rst_n=0, ld=1;
    reg [23:0] ni=128, dim=0;
    reg [29:0] row=0;
    integer checks=0;
    ot_hdc_v41x_vec_lane #(.AW(30), .CW(24), .KIND(0), .LN(3), .KVT_SOURCE_STRIDE(1), .LEAF(0)) dynamic (
        .clk(clk),
        .rst_n(rst_n),
        .lane_id(11'd0),
        .ld(ld),
        .ld_bank('0),
        .ld_c('0),
        .emit(1'b1),
        .bank('0),
        .o_v('0),
        .i_v(dim),
        .no(24'd1),
        .ni(ni),
        .ls(4'd10),
        .lvw(4'd1),
        .vb('0),
        .krow(row),
        .obase(30'd64),
        .aibase('0),
        .aind('0),
        .gsh('0),
        .cpair('0),
        .dst(2'd3),
        .srcs('0),
        .vi_re(),
        .vi_addr(),
        .vi_q('0),
        .rd_addr(),
        .rd_re(),
        .rd_src(),
        .rd_q('0),
        .cx_srcs('0),
        .cx_arnd('0),
        .cx_arelu('0),
        .cx_amin('0),
        .cx_cclip('0),
        .cx_imm3('0),
        .cp_m1('0),
        .cp_imm1('0),
        .cm_m1('0),
        .cm_m2('0),
        .cm_qm('0),
        .cm_imm1('0),
        .ca_ad('0),
        .ca_imm2('0),
        .ci_sfu('0),
        .cs_sfu('0),
        .cs_e1('0),
        .cs_imm2('0),
        .ce_e2('0),
        .ce_imm1('0),
        .co_rnd('0),
        .co_dst('0),
        .side_v(),
        .side_x(),
        .side_y('0),
        .vm_we(),
        .vm_waddr(),
        .vm_wdata(),
        .kv_we(),
        .kv_waddr(),
        .kv_wdata(),
        .ro_v(),
        .ro_x(),
        .fault(),
        .coll()
    );
    ot_hdc_v41x_vec_lane #(.AW(30), .CW(24), .KIND(0), .LN(3), .KVT_SOURCE_STRIDE(1), .LEAF(1)) captured (
        .clk(clk),
        .rst_n(rst_n),
        .lane_id(11'd0),
        .ld(ld),
        .ld_bank('0),
        .ld_c('0),
        .emit(1'b1),
        .bank('0),
        .o_v('0),
        .i_v(dim),
        .no(24'd1),
        .ni(ni),
        .ls(4'd10),
        .lvw(4'd1),
        .vb('0),
        .krow(row),
        .obase(30'd64),
        .aibase('0),
        .aind('0),
        .gsh('0),
        .cpair('0),
        .dst(2'd3),
        .srcs('0),
        .vi_re(),
        .vi_addr(),
        .vi_q('0),
        .rd_addr(),
        .rd_re(),
        .rd_src(),
        .rd_q('0),
        .cx_srcs('0),
        .cx_arnd('0),
        .cx_arelu('0),
        .cx_amin('0),
        .cx_cclip('0),
        .cx_imm3('0),
        .cp_m1('0),
        .cp_imm1('0),
        .cm_m1('0),
        .cm_m2('0),
        .cm_qm('0),
        .cm_imm1('0),
        .ca_ad('0),
        .ca_imm2('0),
        .ci_sfu('0),
        .cs_sfu('0),
        .cs_e1('0),
        .cs_imm2('0),
        .ce_e2('0),
        .ce_imm1('0),
        .co_rnd('0),
        .co_dst('0),
        .side_v(),
        .side_x(),
        .side_y('0),
        .vm_we(),
        .vm_waddr(),
        .vm_wdata(),
        .kv_we(),
        .kv_waddr(),
        .kv_wdata(),
        .ro_v(),
        .ro_x(),
        .fault(),
        .coll()
    );
    ot_hdc_v41x_vec_lane #(.AW(30), .CW(24), .KIND(0), .LN(3), .KVT_SOURCE_STRIDE(0), .LEAF(0)) legacy (
        .clk(clk),
        .rst_n(rst_n),
        .lane_id(11'd0),
        .ld(ld),
        .ld_bank('0),
        .ld_c('0),
        .emit(1'b1),
        .bank('0),
        .o_v('0),
        .i_v(dim),
        .no(24'd1),
        .ni(ni),
        .ls(4'd10),
        .lvw(4'd1),
        .vb('0),
        .krow(row),
        .obase(30'd64),
        .aibase('0),
        .aind('0),
        .gsh('0),
        .cpair('0),
        .dst(2'd3),
        .srcs('0),
        .vi_re(),
        .vi_addr(),
        .vi_q('0),
        .rd_addr(),
        .rd_re(),
        .rd_src(),
        .rd_q('0),
        .cx_srcs('0),
        .cx_arnd('0),
        .cx_arelu('0),
        .cx_amin('0),
        .cx_cclip('0),
        .cx_imm3('0),
        .cp_m1('0),
        .cp_imm1('0),
        .cm_m1('0),
        .cm_m2('0),
        .cm_qm('0),
        .cm_imm1('0),
        .ca_ad('0),
        .ca_imm2('0),
        .ci_sfu('0),
        .cs_sfu('0),
        .cs_e1('0),
        .cs_imm2('0),
        .ce_e2('0),
        .ce_imm1('0),
        .co_rnd('0),
        .co_dst('0),
        .side_v(),
        .side_x(),
        .side_y('0),
        .vm_we(),
        .vm_waddr(),
        .vm_wdata(),
        .kv_we(),
        .kv_waddr(),
        .kv_wdata(),
        .ro_v(),
        .ro_x(),
        .fault(),
        .coll()
    );
    task tick;
        begin #5; clk=1; #1; clk=0; #1; end
    endtask
    reg [29:0] want, oldwant, legacywant;
    integer i,j,k;
    integer rows[0:5];
    integer widths[0:2];
    initial begin
        rows[0]=0;rows[1]=15;rows[2]=16;rows[3]=31;
        rows[4]=262143;rows[5]=1048575;
        widths[0]=128;widths[1]=512;widths[2]=64;
        tick();rst_n=1;tick();ld=0;tick();tick();
        oldwant=captured.f_o;
        for (i=0;i<6;i=i+1) for (j=0;j<3;j=j+1) for (k=0;k<2;k=k+1) begin
            row=rows[i];ni=widths[j];dim=k ? widths[j]-1 : 0;
            want=64+((row>>4)<<(ni==128?11:13))+(dim<<4)+(row&15);
            legacywant=64+((row>>4)<<9)+(dim<<4)+(row&15);
            tick();
            if(dynamic.f_o!==want || legacy.f_o!==legacywant || captured.f_o!==oldwant)
                $fatal(1,"address/captured control mismatch row=%0d ni=%0d dim=%0d dynamic=%0d expected=%0d captured=%0d prior=%0d",row,ni,dim,dynamic.f_o,want,captured.f_o,oldwant);
            if(!dynamic.f_v || !legacy.f_v || !captured.f_v) $fatal(1,"liveness changed");
            oldwant=want;checks=checks+1;
        end
        tick(); if(captured.f_o!==oldwant) $fatal(1,"last captured address");
        $display("PASS %0d source KVT registered-address cases: D128, D512, SH13 compatibility; leaf and default-off",checks);
        $finish;
    end
endmodule
