`timescale 1ns/1ps
// Protected provider-connected canonical L19 cfg/prompt/whole-stage producers wired to the
// retained fullMAXU866 WFC/C8/core-capture context. SOURCE0 only: the book's
// STAGE_HANDOFF does not authorize SOURCE1 HEAD/argmax/token completion.
// Backend command/retirement/restore/visibility/fence ports are real inputs;
// this top does not fabricate engine completion or memory publication.
// Actual Copernicus288-SRAM provider owns the 3:4 transport and service.
// XB must hold its tuple until xb_v&&xb_ready and consume its protected reply;
// neither whole-stage ACK nor row visibility alone retires provider debt.
module ot_dsrom_wfc_protected_stage #(
 parameter ENABLE=0, STRUCTURAL=0,
 parameter string BOOK0="results/uarch/dsrom_wfc_producers_20261005/book/rank0.viamap.hex",
 parameter string BOOK1="results/uarch/dsrom_wfc_producers_20261005/book/rank1.viamap.hex",
 parameter string BOOK2="results/uarch/dsrom_wfc_producers_20261005/book/rank2.viamap.hex",
 parameter string BOOK3="results/uarch/dsrom_wfc_producers_20261005/book/rank3.viamap.hex"
)(
 input wire fast_clk,slow_clk,cold_n,slow_rst_n,
 input wire fast_rst_n,
 input wire  cold_fenced,
 input wire  cmd_v,
 input wire [1:0] cmd_op,
 input wire [9:0] cmd_user,
 input wire [20:0] cmd_pos,
 input wire [20:0] cmd_token,
 input wire [3:0] cmd_block,
 input wire [15:0] cmd_epoch,
 input wire [13:0] cmd_entry,
 output wire  cmd_ready,
 output wire  producer_active,
 output wire  producer_initializing,
 output wire  cfg_fault,
 input wire [3:0] command_v,
 output wire [3:0] command_ready,
 input wire [187:0] command_identity,
 input wire [83:0] command_token,
 input wire [27:0] command_home,
 input wire [55:0] command_entry,
 input wire [55:0] command_pc,
 input wire [15:0] command_unit,
 input wire [3:0] retire_v,
 input wire [187:0] retire_identity,
 input wire [27:0] retire_home,
 input wire [55:0] retire_entry,
 input wire [23:0] retire_visibility,
 input wire [3:0] retire_quiet,
 input wire [3:0] retire_capture_drained,
 input wire [3:0] retire_fault,
 input wire [3:0] fence_v,
 input wire [187:0] fence_identity,
 input wire [19:0] fence_visibility,
 input wire  result_v,
 input wire [46:0] result_identity,
 input wire [20:0] result_token,
 input wire [31:0] result_value,
 output wire  token_result_valid,
 output wire  stage_handoff,
 output wire  producer_pending,
 output wire  whole_fault,
 input wire  in_valid,
 input wire  in_last,
 input wire  out_ready,
 input wire [511:0] in_data,
 output wire  in_ready,
 output wire  out_valid,
 output wire  out_last,
 output wire [511:0] out_data,
 input wire  bl_rx_valid,
 input wire  bl_rx_last,
 input wire  bl_tx_ready,
 input wire [511:0] bl_rx_data,
 output wire  bl_rx_ready,
 output wire  bl_tx_valid,
 output wire  bl_tx_last,
 output wire [511:0] bl_tx_data,
 input wire  rcfg_we,
 input wire [7:0] rcfg_dest,
 input wire [2:0] rcfg_mask,
 input wire  context_restored,
 input wire  native_idle,
 input wire  native_fragment_done,
 input wire  c8_write_quiet,
 input wire  c8_write_quarantine,
 input wire  c8_write_fault,
 input wire  coll_busy,
 input wire [3:0] xb_we4,
 input wire [59:0] xb_waddr4,
 input wire [2047:0] xb_wdata4,
 input wire  xb_re,
 input wire [14:0] xb_raddr,
 output wire [511:0] xb_rq,
 input wire xb_v,
 input wire [46:0]xb_owner,xb_consume_owner,
 input wire xb_consume_v,
 output wire xb_ready,xb_reply_v,xb_port_retired,
 output wire [46:0]xb_reply_owner,
 output wire [3:0]xb_row_visible,
 output wire vm_pending,vm_initializing,vm_fault,vm_quarantined,vm_port_retired,
 output wire [3:0]vm_phase,
 output wire  context_v,
 output wire [46:0] context_identity,
 output wire [20:0] context_token,
 output wire [13:0] context_entry,
 output wire  native_start,
 output wire [20:0] native_token,
 output wire [20:0] native_pos,
 output wire [13:0] native_entry,
 output wire [9:0] native_user,
 output wire [46:0] native_identity,
 output wire [20:0] captured_token,
 output wire [20:0] captured_pos,
 output wire [13:0] captured_pc,
 output wire  c8_retire_v,
 output wire [46:0] c8_retire_identity,
 output wire  tok_valid,
 output wire [9:0] tok_user,
 output wire [9:0] users_done,
 output wire [20:0] tok_pos,
 output wire [20:0] tok_id,
 output wire  busy,
 output wire  wfc_fault
);
 wire [9:0] cfg_users;
 wire [20:0] cfg_prompt_len;
 wire [20:0] cfg_gen_len;
 wire [15:0] stage_epoch;
 wire [13:0] stage_entry;
 wire  pr_re;
 wire [9:0] pr_user;
 wire [20:0] pr_pos;
 wire [3:0] pr_blk;
 wire [20:0] pr_q;
 wire  pr_qk;
 wire  stage_request_v;
 wire  stage_request_ready;
 wire [46:0] stage_request_identity;
 wire [20:0] stage_request_token;
 wire [13:0] stage_request_entry;
 wire  whole_stage_accepted;
 wire  whole_stage_v;
 wire [46:0] whole_stage_identity;
 wire [20:0] whole_stage_token;
 wire [31:0] whole_stage_value;
 wire advance,memory_step,read_step,write_step,memory_write_quiet,adapter_fault,xa_read_capture,vm_owner_conflict;
 wire xa_we,xa_re;wire[14:0]xa_waddr,xa_raddr;wire[511:0]xa_wdata;
 wire[9:0]vm_owner_user,vm_read_owner_user;wire[20:0]vm_owner_pos,vm_read_owner_pos;
 wire[46:0]xa_read_owner={stage_epoch,vm_read_owner_user,vm_read_owner_pos};
 wire[46:0]xa_owner={stage_epoch,vm_owner_user,vm_owner_pos};
 wire provider_request_v,provider_request_ready,provider_reply_v,provider_corrected;
 wire[46:0]provider_request_owner,provider_reply_owner,provider_consume_owner;
 wire[1:0]provider_read_enable;wire[29:0]provider_read_addr;
 wire[4:0]provider_write_enable,provider_row_visible;wire[74:0]provider_write_addr,provider_visible_addr;
 wire[2559:0]provider_write_data;wire[79:0]provider_write_mask,provider_visible_mask;
 wire[1023:0]provider_read_data;
 wire provider_consume_v,provider_allcopies_fenced;
 ot_dsrom_wfc_vm_caller_adapter #(.ENABLE(ENABLE)) u_adapter(
  .fast_clk(fast_clk),.cold_n(cold_n),.fast_rst_n(fast_rst_n),.slow_rst_n(slow_rst_n),
  .xa_we(xa_we),.xa_re(xa_re),.xa_waddr(xa_waddr),.xa_raddr(xa_raddr),.xa_wdata(xa_wdata),.xa_owner(xa_owner),
  .xa_read_capture(xa_read_capture),.xa_owner_conflict(vm_owner_conflict),.xa_read_owner(xa_read_owner),.advance(advance),.memory_step(memory_step),.read_step(read_step),.write_step(write_step),.write_quiet(memory_write_quiet),
  .xb_v(xb_v),.xb_ready(xb_ready),.xb_owner(xb_owner),.xb_we4(xb_we4),.xb_waddr4(xb_waddr4),.xb_wdata4(xb_wdata4),
  .xb_re(xb_re),.xb_raddr(xb_raddr),.xb_reply_v(xb_reply_v),.xb_reply_owner(xb_reply_owner),.xb_read_data(xb_rq),
  .xb_row_visible(xb_row_visible),.xb_consume_v(xb_consume_v),.xb_consume_owner(xb_consume_owner),.xb_port_retired(xb_port_retired),
  .request_v(provider_request_v),.request_ready(provider_request_ready),.request_owner(provider_request_owner),
  .read_enable(provider_read_enable),.read_addr(provider_read_addr),.write_enable(provider_write_enable),
  .write_addr(provider_write_addr),.write_data(provider_write_data),.write_mask(provider_write_mask),
  .reply_v(provider_reply_v),.reply_owner(provider_reply_owner),.read_data(provider_read_data),.row_visible(provider_row_visible),
  .port_retired(vm_port_retired),.pending(vm_pending),.provider_fault(vm_fault),.initializing(vm_initializing),
  .consume_v(provider_consume_v),.consume_owner(provider_consume_owner),.allcopies_fenced(provider_allcopies_fenced),
  .fault(adapter_fault),.phase(vm_phase));
 ot_dsrom_protected_vm #(.ENABLE(ENABLE)) u_memory(
  .fast_clk(fast_clk),.slow_clk(slow_clk),.cold_n(cold_n),.fast_rst_n(fast_rst_n),.slow_rst_n(slow_rst_n),
  .request_v(provider_request_v),.request_ready(provider_request_ready),.request_owner(provider_request_owner),
  .read_enable(provider_read_enable),.read_addr(provider_read_addr),.write_enable(provider_write_enable),
  .write_addr(provider_write_addr),.write_data(provider_write_data),.write_mask(provider_write_mask),
  .reply_v(provider_reply_v),.reply_owner(provider_reply_owner),.read_data(provider_read_data),
  .row_visible(provider_row_visible),.visible_addr(provider_visible_addr),.visible_mask(provider_visible_mask),.corrected(provider_corrected),
  .consume_v(provider_consume_v),.consume_owner(provider_consume_owner),.allcopies_fenced(provider_allcopies_fenced),
  .port_retired(vm_port_retired),.pending(vm_pending),.quarantined(vm_quarantined),.fault(vm_fault),.initializing(vm_initializing));

ot_dsrom_wfc_cfg_prompt #(.ENABLE(ENABLE)) u_cfg (
 .clk(fast_clk),
 .rst_n(fast_rst_n),
 .cold_fenced(cold_fenced),
 .cmd_v(cmd_v),
 .cmd_op(cmd_op),
 .cmd_user(cmd_user),
 .cmd_pos(cmd_pos),
 .cmd_token(cmd_token),
 .cmd_block(cmd_block),
 .cmd_epoch(cmd_epoch),
 .cmd_entry(cmd_entry),
 .cmd_ready(cmd_ready),
 .cfg_users(cfg_users),
 .cfg_prompt_len(cfg_prompt_len),
 .cfg_gen_len(cfg_gen_len),
 .stage_epoch(stage_epoch),
 .stage_entry(stage_entry),
 .pr_re(pr_re),
 .pr_user(pr_user),
 .pr_pos(pr_pos),
 .pr_blk(pr_blk),
 .pr_q(pr_q),
 .pr_qk(pr_qk),
 .active(producer_active),
 .initializing(producer_initializing),
 .fault(cfg_fault)
);
ot_dsrom_wfc_whole_stage #(.ENABLE(ENABLE),.BOOK0(BOOK0),.BOOK1(BOOK1),.BOOK2(BOOK2),.BOOK3(BOOK3)) u_whole (
 .clk(fast_clk),
 .rst_n(fast_rst_n),
 .request_v(stage_request_v),
 .request_ready(stage_request_ready),
 .request_identity(stage_request_identity),
 .request_token(stage_request_token),
 .request_entry(stage_request_entry),
 .configured_epoch(stage_epoch),
 .command_v(command_v),
 .command_ready(command_ready),
 .command_identity(command_identity),
 .command_token(command_token),
 .command_home(command_home),
 .command_entry(command_entry),
 .command_pc(command_pc),
 .command_unit(command_unit),
 .retire_v(retire_v),
 .retire_identity(retire_identity),
 .retire_home(retire_home),
 .retire_entry(retire_entry),
 .retire_visibility(retire_visibility),
 .retire_quiet(retire_quiet),
 .retire_capture_drained(retire_capture_drained),
 .retire_fault(retire_fault),
 .fence_v(fence_v),
 .fence_identity(fence_identity),
 .fence_visibility(fence_visibility),
 .result_v(result_v),
 .result_identity(result_identity),
 .result_token(result_token),
 .result_value(result_value),
 .whole_stage_accepted(whole_stage_accepted),
 .whole_stage_v(whole_stage_v),
 .whole_stage_identity(whole_stage_identity),
 .whole_stage_next_token(whole_stage_token),
 .whole_stage_value(whole_stage_value),
 .token_result_valid(token_result_valid),
 .stage_handoff(stage_handoff),
 .pending(producer_pending),
 .fault(whole_fault)
);

 ot_dsrom_wfc_enclosing_vm_stage #(.ENABLE(ENABLE),.SOURCE(0),.STRUCTURAL(STRUCTURAL)) u_stage(
  .clk(fast_clk),
  .rst_n(fast_rst_n),
  .advance(advance),.memory_step(memory_step),.read_step(read_step),.write_step(write_step),
  .vm_we(xa_we),.vm_re(xa_re),.vm_waddr(xa_waddr),.vm_raddr(xa_raddr),.vm_wdata(xa_wdata),.vm_rq(provider_read_data[511:0]),
  .vm_owner_user(vm_owner_user),.vm_owner_pos(vm_owner_pos),.vm_read_capture(xa_read_capture),.vm_owner_conflict(vm_owner_conflict),.vm_read_owner_user(vm_read_owner_user),.vm_read_owner_pos(vm_read_owner_pos),
  .cfg_users(cfg_users),
  .cfg_prompt_len(cfg_prompt_len),
  .cfg_gen_len(cfg_gen_len),
  .pr_q(pr_q),
  .pr_qk(pr_qk),
  .pr_re(pr_re),
  .pr_user(pr_user),
  .pr_pos(pr_pos),
  .pr_blk(pr_blk),
  .in_valid(in_valid),
  .in_last(in_last),
  .out_ready(out_ready),
  .in_data(in_data),
  .in_ready(in_ready),
  .out_valid(out_valid),
  .out_last(out_last),
  .out_data(out_data),
  .bl_rx_valid(bl_rx_valid),
  .bl_rx_last(bl_rx_last),
  .bl_tx_ready(bl_tx_ready),
  .bl_rx_data(bl_rx_data),
  .bl_rx_ready(bl_rx_ready),
  .bl_tx_valid(bl_tx_valid),
  .bl_tx_last(bl_tx_last),
  .bl_tx_data(bl_tx_data),
  .rcfg_we(rcfg_we),
  .rcfg_dest(rcfg_dest),
  .rcfg_mask(rcfg_mask),
  .stage_epoch(stage_epoch),
  .stage_entry(stage_entry),
  .stage_request_v(stage_request_v),
  .stage_request_ready(stage_request_ready),
  .stage_request_identity(stage_request_identity),
  .stage_request_token(stage_request_token),
  .stage_request_entry(stage_request_entry),
  .whole_stage_v(whole_stage_v),
  .whole_stage_identity(whole_stage_identity),
  .whole_stage_token(whole_stage_token),
  .whole_stage_value(whole_stage_value),
  .whole_stage_accepted(whole_stage_accepted),
  .context_restored(context_restored),
  .native_idle(native_idle),
  .native_fragment_done(native_fragment_done),
  .c8_write_quiet(c8_write_quiet&&memory_write_quiet),
  .c8_write_quarantine(c8_write_quarantine||vm_quarantined),
  .c8_write_fault(c8_write_fault||vm_fault||adapter_fault),
  .coll_busy(coll_busy),
  .context_v(context_v),
  .context_identity(context_identity),
  .context_token(context_token),
  .context_entry(context_entry),
  .native_start(native_start),
  .native_token(native_token),
  .native_pos(native_pos),
  .native_entry(native_entry),
  .native_user(native_user),
  .native_identity(native_identity),
  .captured_token(captured_token),
  .captured_pos(captured_pos),
  .captured_pc(captured_pc),
  .c8_retire_v(c8_retire_v),
  .c8_retire_identity(c8_retire_identity),
  .tok_valid(tok_valid),
  .tok_user(tok_user),
  .users_done(users_done),
  .tok_pos(tok_pos),
  .tok_id(tok_id),
  .busy(busy),
  .fault(wfc_fault)
 );
endmodule
