`timescale 1ns/1ps
// Source-only borrowed WINDOW model. No private HBM, clock, grant or payload.
// STREAM_LA is off by default. Selected native emission explicitly sets it to 1.
// Aggregate C8 writes retain actual m_wr_done; wl_* is read-only client0 of
// the SAME backend's WIN_STACK wmux. Caller owns shared reset/clock/lifecycle.
module DsromS81WindowLa #(
    parameter bit STREAM_LA = 0,
    parameter bit REFILL_OWNER_SAFE = 0,
    parameter integer POS_W = 21, USER_W = 10, SEC_W = 30, HAW = 30, TAGW = 16,
    parameter bit RETAIN_L0 = 0,
    parameter integer WIN_STACK = 0, STREAM_II1 = 0, REFILL_CREDITS = 1,
    parameter integer NPC = 32, WTAGW = 13, WLENW = 4, BEATW = 4, LA_IW = 8,
    parameter integer MAX_CONTEXT = 1048576
) (
    input wire clk, rst_n,
    input wire retain_qk, retain_pv, retain_complete, retain_invalidate,
    input wire [15:0] retain_generation,
    input wire [SEC_W-1:0] region_base_sector, region_sector_count,
    input wire prime_v,
    output wire prime_ready,
    input wire [USER_W-1:0] prime_user,
    input wire [POS_W-1:0] prime_row,
    input wire blk_v,
    output wire blk_ready,
    input wire [USER_W-1:0] blk_user,
    input wire [POS_W-1:0] blk_row,
    input wire [3:0] blk_idx,
    input wire [255:0] blk_codes,
    input wire [7:0] blk_scale,
    input wire start_v,
    output wire start_ready,
    input wire [USER_W-1:0] start_user,
    input wire [POS_W-1:0] start_first,
    input wire [7:0] start_count,
    output wire staged_v,
    input wire stream_go,
    output wire busy, done, fault,
    output wire [4:0] fault_code,
    output wire [31:0] refill_cycles, sectors_read,
    output wire [31:0] rows_fetched, blocks_written, sectors_written,
    output wire [7:0] rows_refilled,
    output wire kv_v,
    input wire kv_ready,
    output wire [3:0] kv_m,
    output wire [4*16*265-1:0] kv_w,
    output wire [3:0] m_v,
    input wire [3:0] m_rdy,
    output wire [4*HAW-1:0] m_addr,
    output wire [15:0] m_len,
    output wire [4*TAGW-1:0] m_tag,
    output wire [3:0] m_we,
    output wire [1023:0] m_wdata,
    output wire [127:0] m_wstrb,
    input wire [3:0] m_wr_done,
    input wire [3:0] s_v,
    output wire [3:0] s_rdy,
    input wire [4*TAGW-1:0] s_tag,
    input wire [15:0] s_beat,
    input wire [1023:0] s_data,
    // wide port: client 0 of the WIN_STACK stack's ot_dsrom_hbm_wmux
    output wire [NPC-1:0] wl_req_v,
    input wire [NPC-1:0] wl_req_rdy,
    output wire [NPC*HAW-1:0] wl_req_addr,
    output wire [NPC*WLENW-1:0] wl_req_len,
    output wire [NPC*WTAGW-1:0] wl_req_tag,
    input wire [NPC-1:0] wl_rsp_v,
    output wire [NPC-1:0] wl_rsp_rdy,
    input wire [NPC*WTAGW-1:0] wl_rsp_tag,
    input wire [NPC*BEATW-1:0] wl_rsp_beat,
    input wire [NPC*256-1:0] wl_rsp_data,
    // measurement: cycles from job acceptance to every job row staged (LA), 0 when STREAM_LA = 0
    output wire [31:0] la_load_cycles
);
    ot_dsrom_window_attn_source_la #(
        .STREAM_LA(STREAM_LA),
        .REFILL_OWNER_SAFE(REFILL_OWNER_SAFE),
        .POS_W(POS_W),
        .USER_W(USER_W),
        .SEC_W(SEC_W),
        .HAW(HAW),
        .TAGW(TAGW),
        .RETAIN_L0(RETAIN_L0),
        .WIN_STACK(WIN_STACK),
        .STREAM_II1(STREAM_II1),
        .REFILL_CREDITS(REFILL_CREDITS),
        .NPC(NPC),
        .WTAGW(WTAGW),
        .WLENW(WLENW),
        .BEATW(BEATW),
        .LA_IW(LA_IW),
        .MAX_CONTEXT(MAX_CONTEXT)
    ) u_source (
        .clk(clk),
        .rst_n(rst_n),
        .retain_qk(retain_qk),
        .retain_pv(retain_pv),
        .retain_complete(retain_complete),
        .retain_invalidate(retain_invalidate),
        .retain_generation(retain_generation),
        .region_base_sector(region_base_sector),
        .region_sector_count(region_sector_count),
        .prime_v(prime_v),
        .prime_ready(prime_ready),
        .prime_user(prime_user),
        .prime_row(prime_row),
        .blk_v(blk_v),
        .blk_ready(blk_ready),
        .blk_user(blk_user),
        .blk_row(blk_row),
        .blk_idx(blk_idx),
        .blk_codes(blk_codes),
        .blk_scale(blk_scale),
        .start_v(start_v),
        .start_ready(start_ready),
        .start_user(start_user),
        .start_first(start_first),
        .start_count(start_count),
        .staged_v(staged_v),
        .stream_go(stream_go),
        .busy(busy),
        .done(done),
        .fault(fault),
        .fault_code(fault_code),
        .refill_cycles(refill_cycles),
        .sectors_read(sectors_read),
        .rows_fetched(rows_fetched),
        .blocks_written(blocks_written),
        .sectors_written(sectors_written),
        .rows_refilled(rows_refilled),
        .kv_v(kv_v),
        .kv_ready(kv_ready),
        .kv_m(kv_m),
        .kv_w(kv_w),
        .m_v(m_v),
        .m_rdy(m_rdy),
        .m_addr(m_addr),
        .m_len(m_len),
        .m_tag(m_tag),
        .m_we(m_we),
        .m_wdata(m_wdata),
        .m_wstrb(m_wstrb),
        .m_wr_done(m_wr_done),
        .s_v(s_v),
        .s_rdy(s_rdy),
        .s_tag(s_tag),
        .s_beat(s_beat),
        .s_data(s_data),
        .wl_req_v(wl_req_v),
        .wl_req_rdy(wl_req_rdy),
        .wl_req_addr(wl_req_addr),
        .wl_req_len(wl_req_len),
        .wl_req_tag(wl_req_tag),
        .wl_rsp_v(wl_rsp_v),
        .wl_rsp_rdy(wl_rsp_rdy),
        .wl_rsp_tag(wl_rsp_tag),
        .wl_rsp_beat(wl_rsp_beat),
        .wl_rsp_data(wl_rsp_data),
        .la_load_cycles(la_load_cycles)
    );
endmodule
