#!/usr/bin/env python3
"""The iso-area position of the datapath that actually runs a token.

results/derived/iso_area_vehicle_is_not_the_token_datapath.json established that the
published A100 ratios are measured on ot_compute_unit -- three modules under
rtl/proto -- while tokens are generated by ot_a3_engine_array, fourteen modules under
rtl/abi3 that share no module with it. results/derived/arithmetic_width_by_vehicle.json
established the size of the gap: the array is ONE MAC per cycle where the compute unit
is sixteen.

This computes the array's own position rather than waiting for its umbrella route,
which has now timed out twice at fifteen hours. Two things make that legitimate and
one makes it a bound rather than a measurement:

  * the CLOCK is the design limiter from the fmax inventory, which is the honest
    whole-design operating point and is what the array would run at;
  * the ARITHMETIC is one multiply-accumulate per cycle, which is a structural fact
    of the netlist and not an assumption: ot_a3_mac_lane_pipe instantiates exactly one
    ot_mac_bf16_fp32_pipe and its LANES_IF is an interleave factor;
  * the AREA is the sum of the members' own routed standard-cell areas, which OMITS
    the array's glue -- the issue decode, the operand multiplexing, the completion
    logic -- so it is a LOWER bound on area and therefore an UPPER bound on the
    ratio. A member with no routed record is reported as missing rather than
    estimated, which makes the bound looser still and says so.

Peak arithmetic only, like the three-level audit: one MAC retired every cycle. That
assumption is measured elsewhere in this repository and does not hold; the sustained
de-rating belongs to the record that measured it.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import subprocess
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = "opentallas.derived.engine_array_iso_area.v1"
TOOL = "tools/audit_engine_array_iso_area.py"
COVERAGE = ROOT / "results/physical_abi3/asap7/datapath_coverage.json"
INVENTORY = ROOT / "results/physical_abi3/asap7/frequency_inventory/asap7_fmax_inventory.json"
RECORDS = ROOT / "results/physical_abi3/asap7"


def _git_commit() -> str:
    return subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=ROOT,
        capture_output=True, text=True, check=True,
    ).stdout.strip()


def _comparator() -> dict[str, Any]:
    """The A100 side, from tools/audit_abi3_iso_area_three_level.py itself.

    Imported rather than restated: a second statement of a comparator is a second
    thing to get wrong, and every figure in it is read from a recorded config key.
    """
    spec = importlib.util.spec_from_file_location(
        "_three_level", ROOT / "tools/audit_abi3_iso_area_three_level.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.comparator()


def _routed(top: str, closed_only: bool = True) -> dict[str, Any] | None:
    """The DENSITY-optimal routed record for a top: the one maximising fmax/area.

    Smallest area is the wrong criterion for an iso-area statement and it silently
    chose the wrong operating point: ot_a3_lq8's smallest closed record is a 16 ns
    route at 140.3 MHz, while a 2 ns route of the same module closes at 512.8 MHz for
    2% more area. Throughput per unit silicon is what the comparison is about, so
    that is what selects.
    """
    found: list[dict[str, Any]] = []
    for path in sorted(RECORDS.rglob("*.json")):
        try:
            record = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        design = record.get("design")
        if not isinstance(design, dict):
            continue
        if (design.get("top") or design.get("block")) != top:
            continue
        if not design.get("area_um2") or (closed_only and not design.get("closed")):
            continue
        found.append({
            "record": str(path.relative_to(ROOT)),
            "area_um2": float(design["area_um2"]),
            "fmax_hz": float(design.get("fmax_hz") or 0),
            "cells": design.get("cells"),
        })
    if not found:
        return None
    return max(found, key=lambda r: r["fmax_hz"] / r["area_um2"])


def _projection(
    best: dict[str, Any], area_um2: float, clock_hz: float, a100: dict[str, Any]
) -> dict[str, Any]:
    """Steps whose every input is a routed record in this repository."""
    lane = _routed("ot_mac_bf16_fp32_pipe")
    tile = _routed("ot_mac_tile")
    unit = _routed("ot_compute_unit")
    #: The ABI 3.0 lane family, which is what the datapath would actually
    #: instantiate: one lane, and the eight-lane quad ot_a3_tile64 is built from.
    abi3_lane = _routed("ot_a3_lane_pipelined")
    abi3_quad = _routed("ot_a3_lq8")
    if not (lane and tile and unit):
        return {"unavailable": "a routed record for the one-lane MAC, the 16-lane "
                               "tile or the compute unit is missing"}

    def step(label: str, macs: int, replacement_um2: float, hz: float,
             basis: str) -> dict[str, Any]:
        area = area_um2 - lane["area_um2"] + replacement_um2
        ops = macs * 2 * hz
        density = ops / (area / 1e6)
        return {
            "step": label,
            "macs_per_cycle": macs,
            "clock_hz": hz,
            "area_um2": area,
            "bf16_ops_s": ops,
            "ops_s_per_mm2": density,
            "ratio_against_a100_logic_area": density / a100["logic_level_ops_s_per_mm2"],
            "basis": basis,
        }

    per_lane = tile["area_um2"] / 16.0
    #: THE DENSITY GAP, measured. The proto tile shares its operand broadcast tree
    #: and accumulators across sixteen lanes; the ABI 3.0 lane carries its own
    #: admission, block-scale handling and accumulator slots. That difference is
    #: what caps the ratio, and it is not an estimate.
    density = {
        "bare_mac_um2": lane["area_um2"],
        "proto_tile_um2_per_lane": per_lane,
        "abi3_lane_um2": abi3_lane["area_um2"] if abi3_lane else None,
        "abi3_quad_um2_per_lane": (
            abi3_quad["area_um2"] / 8.0 if abi3_quad else None
        ),
        "abi3_lane_over_proto_tile_per_lane": (
            (abi3_quad["area_um2"] / 8.0) / per_lane if abi3_quad else None
        ),
        "abi3_lane_over_bare_mac": (
            abi3_lane["area_um2"] / lane["area_um2"] if abi3_lane else None
        ),
        "what_it_means": (
            "an ABI 3.0 lane is this many times the silicon of the bare MAC it "
            "contains, so buying width in the ABI 3.0 family costs that multiple of "
            "the arithmetic. It is the reason width alone does not reach the A100 "
            "here, and the proto tile's number is what sharing the operand tree and "
            "the accumulators is worth."
        ),
    }
    return {
        "inputs": {
            "one_lane": lane, "sixteen_lane_tile": tile, "compute_unit": unit,
            "abi3_one_lane": abi3_lane, "abi3_eight_lane_quad": abi3_quad,
            "tile_area_per_lane_um2": per_lane,
        },
        "density_gap": density,
        "steps": [
            step("swap the single MAC for the 16-lane ot_mac_tile, same clock", 16,
                 tile["area_um2"], clock_hz,
                 "both areas are routed records; the clock is unchanged"),
            step("and run it at the MAC datapath's own routed clock", 16,
                 tile["area_um2"], unit["fmax_hz"],
                 "ot_compute_unit's routed closed frequency, which is what a "
                 "16-lane tile with its operand delivery has been measured at"),
            step("64 lanes at that clock, tile area scaled per lane", 64,
                 per_lane * 64, unit["fmax_hz"],
                 "ot_a3_tile64 is 64 lanes and has NEVER been routed, so its area "
                 "is projected from ot_mac_tile's measured area per lane -- the one "
                 "estimated quantity in this table, and it is an estimate of AREA "
                 "which makes the ratio optimistic"),
        ] + ([
            step("the ABI 3.0 eight-lane quad, at its own routed closed clock", 8,
                 abi3_quad["area_um2"], abi3_quad["fmax_hz"],
                 "ot_a3_lq8: EVERY number measured, an ABI 3.0 module rather than a "
                 "proto, routed and closed. This is what the datapath would get by "
                 "instantiating a part that already exists"),
            step("sixty-four ABI 3.0 lanes as eight of those quads", 64,
                 abi3_quad["area_um2"] * 8, abi3_quad["fmax_hz"],
                 "ot_a3_tile64's own composition -- eight ot_a3_lq8 -- with the "
                 "quad's measured area and clock; only the assumption that eight "
                 "quads cost eight quads is unmeasured"),
        ] if abi3_quad else []),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top", default="ot_a3_engine_array")
    parser.add_argument("--macs-per-cycle", type=int, default=1)
    parser.add_argument(
        "--output", type=Path,
        default=ROOT / "results/derived/engine_array_iso_area.json",
    )
    args = parser.parse_args()

    coverage = json.loads(COVERAGE.read_text())
    graph = coverage["instantiation_graph"]

    def closure(root: str, seen: set[str] | None = None) -> set[str]:
        seen = seen if seen is not None else set()
        for child in graph.get(root, ()):
            if child not in seen:
                seen.add(child)
                closure(child, seen)
        return seen

    members = sorted(closure(args.top) | {args.top})

    #: The best routed area per top: the smallest CLOSED record if there is one,
    #: else the smallest routed record, because a smaller netlist of the same
    #: module is the same function in less silicon.
    best: dict[str, dict[str, Any]] = {}
    for path in sorted(RECORDS.rglob("*.json")):
        try:
            record = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        design = record.get("design")
        if not isinstance(design, dict):
            continue
        top = design.get("top") or design.get("block")
        area = design.get("area_um2")
        if top not in members or not area:
            continue
        entry = {
            "record": str(path.relative_to(ROOT)),
            "closed": bool(design.get("closed")),
            "area_um2": float(area),
            "cells": design.get("cells"),
            "fmax_mhz": round((design.get("fmax_hz") or 0) / 1e6, 1),
        }
        held = best.get(top)
        if held is None:
            best[top] = entry
        elif (entry["closed"], -entry["area_um2"]) > (held["closed"], -held["area_um2"]):
            best[top] = entry

    #: A member inside another member's closure is already counted in that
    #: member's own routed area, so only the TOP-LEVEL members are summed.
    counted: list[str] = []
    for name in members:
        if name == args.top:
            continue
        if any(name in closure(other) for other in members
               if other not in (name, args.top) and other in best):
            continue
        counted.append(name)

    measured = [n for n in counted if n in best]
    missing = [n for n in counted if n not in best]
    area_um2 = sum(best[n]["area_um2"] for n in measured)

    inventory = json.loads(INVENTORY.read_text())
    limiter = inventory["clock_limiter"]
    clock_hz = float(limiter["fmax_hz"])

    ops_s = args.macs_per_cycle * 2 * clock_hz
    area_mm2 = area_um2 / 1e6
    device = ops_s / area_mm2 if area_mm2 else None
    a100 = _comparator()

    report = {
        "schema": SCHEMA,
        "producer": {"tool": TOOL, "git": {"commit": _git_commit()}},
        "question": (
            "what is the iso-area position of ot_a3_engine_array -- the datapath the "
            "nine-cell token matrix runs on -- rather than of ot_compute_unit?"
        ),
        "top": args.top,
        "arithmetic": {
            "macs_per_cycle": args.macs_per_cycle,
            "bf16_ops_per_cycle": args.macs_per_cycle * 2,
            "basis": (
                "ot_a3_mac_lane_pipe instantiates exactly ONE ot_mac_bf16_fp32_pipe; "
                "its LANES_IF of 8 interleaves eight output columns through that one "
                "unit to hide a five-stage latency and is not eight multipliers. The "
                "legacy ot_a3_mac_lane beside it retires one every five cycles."
            ),
        },
        "clock": {
            "hz": clock_hz,
            "block": limiter["block"],
            "basis": "the fmax inventory's clock_limiter: the slowest ABI 3.0 block "
                     "with a closed routed record, which is the whole-design "
                     "operating point",
        },
        "area": {
            "standard_cell_um2_lower_bound": area_um2,
            "mm2_lower_bound": area_mm2,
            "members_counted": {n: best[n] for n in measured},
            "members_with_no_routed_record": missing,
            "why_a_lower_bound": (
                "the sum omits ot_a3_engine_array's own glue -- issue decode, operand "
                "multiplexing, completion logic -- and omits every member with no "
                "routed record, so the ratio below is an UPPER bound"
            ),
        },
        "device_bf16_ops_s": ops_s,
        "device_bf16_ops_s_per_mm2": device,
        "a100": a100,
        "ratio_against_a100_logic_area_UPPER_BOUND": (
            device / a100["logic_level_ops_s_per_mm2"] if device else None
        ),
        "ratio_against_a100_whole_die_UPPER_BOUND": (
            device / a100["device_level_ops_s_per_mm2"] if device else None
        ),
        #: WHAT WOULD CLOSE THE GAP, from measured areas and measured clocks only.
        #: Each step replaces the array's single ot_mac_bf16_fp32_pipe with a wider
        #: unit that has its OWN routed record, so the area arithmetic is
        #: subtraction and addition of measured numbers rather than a model.
        "projection_from_measured_records": _projection(best, area_um2, clock_hz, a100),
        "not_a_claim": [
            "this is not a routed measurement of ot_a3_engine_array: it has no routed "
            "record, and the area here is a sum of its members' records",
            "peak arithmetic only -- one MAC retired every cycle -- which this "
            "repository has measured and found does not hold",
            "an UPPER bound on the ratio: the area is a lower bound, so the true "
            "ratio is lower than the number printed",
        ],
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")

    print(f"{args.top}: {args.macs_per_cycle} MAC/cycle at "
          f"{clock_hz/1e6:.1f} MHz = {ops_s/1e9:.3f} Gop/s")
    print(f"  area lower bound {area_um2:,.1f} um2 from {len(measured)} routed members"
          f"; {len(missing)} without a record: {', '.join(missing) or 'none'}")
    print(f"  {device/1e9:.3f} Gop/s per mm2 against the A100's "
          f"{a100['logic_level_ops_s_per_mm2']/1e9:.3f} over logic area")
    print(f"  UPPER BOUND ratio: {report['ratio_against_a100_logic_area_UPPER_BOUND']:.4f}x "
          f"logic-area, {report['ratio_against_a100_whole_die_UPPER_BOUND']:.4f}x whole-die")
    print(f"-> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
