from pathlib import Path
import gzip,json,hashlib,sqlite3,zlib,collections,ast
R=Path(__file__).resolve().parents[1];D=R/'results/uarch/ds_hbm_history_provider_r36_20261002'
def put(name,obj):(D/name).write_text(json.dumps(obj,sort_keys=True,indent=2)+'\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
model={'scope':'software data provider and addressed completion directed gate; not full native numerical execution','history_source_digest':'b59a99c8294625778d28306924067d5bbf706979068579280d6ee40cb24e6782','seeded_reference_state_not_decoded_prefix':True,'historical_F32_bytes':6710876160,'additional_held_append_bytes':4*(512+128)*4,'query_fields':{'producer_query_codes':'U32[32,64]','producer_query_exp':'U32[32,4] two-complement signed exponent bits','consumer_query_exp':'I64[32,4] explicit sign extension','per_rank_added_bytes':69632,'ranks':96,'all_added_bytes':69632*96,'max_state_occupied_bytes_per_rank':29355520,'state_capacity_bytes_per_rank':33554432,'remaining_min_bytes_per_rank':33554432-29355520},'actual_journal_fixture_inventory':{'RF_data_bytes':16384,'RF_mirrored_WR_sectors':1024,'RF_readback_sectors':512,'query_WR_sectors':272,'query_consumer_RD_sectors':272,'direct_exp_control_RD_sectors':16,'total_sector_transactions':2096,'aligned_full_sectors_RMW_RD':0,'per_admission_guard_bytes':65536,'metadata_guard_bytes':2*131072,'capacity_bytes':2096*65536+2*131072,'scope':'this directed gate; full token inherited journal capacity is not a generated journal'},'full_rank0_index_operand_host_bytes':5464*(128*4+64*4+4*8),'selected_KV_encoded_host_bytes':512*(256*4+32*4+8),'selected_KV_F32_host_bytes':512*512*4,'hardware_area_credit':0,'physical_AW34_extent_translation':None,'PHY_domain_or_measured_cycles':None,'finite_64KiB_shared_tile_mapping':None,'group_workspace_bytes':524288,'physical_shared_slice_bytes':65536,'movement_costs':'existing positive provisional software ticks only; not physical costs','full_token_GO':False,'Sagan_owned_next_join':['bounded operand spans','PC18 producer extent and sparse ownership','ordered source view/tile leases and reverse ACK','remaining native reference bindings'],'Kepler_owned_next_join':['actual compressor/index_q source numerical outputs accepted into these endpoints','versioned history source physical homes and finite codec tiling','remaining checkpoint Engram/expert/state payload joins']}
put('model_and_split.json',model)
receipts=[]
import argparse
p=argparse.ArgumentParser();p.add_argument('--journals-root',type=Path,required=True);p.add_argument('--prepared-manifest',type=Path,required=True);evidence_args=p.parse_args();latest=evidence_args.journals_root.resolve()
for p in sorted(latest.rglob('events.sqlite')):
 if not any(name in str(p) for name in ('test_actual_compound_query','test_actual_writer_receipts')):continue
 db=sqlite3.connect(str(p));counts=collections.Counter();writes=reads=0;ticks={};dig=hashlib.sha256();alloc=set();maxencoded=0
 for jid,seq,raw in db.execute('select journal,seq,value from event order by journal,seq'):
  e=json.loads(zlib.decompress(raw));counts[e['event']]+=1;dig.update(jid.to_bytes(8,'little'));dig.update(seq.to_bytes(8,'little'));dig.update(raw);maxencoded=max(maxencoded,len(raw));ticks[jid]=max(ticks.get(jid,0),e.get('tick',0));a=e.get('allocation_identity');
  if a:alloc.add(json.dumps(a,sort_keys=True))
 receipts.append(dict(path=str(p),sqlite_bytes=p.stat().st_size,compressed_ordered_event_sha256=dig.hexdigest(),event_counts=dict(counts),max_provisional_tick_by_journal=ticks,allocation_identities=[json.loads(a) for a in sorted(alloc)],max_compressed_event_bytes=maxencoded,PHY_qualified=False));db.close()
put('actual_directed_journals.json',receipts)
# Recursive dependency graph, not private unstated worktree tools.
roots=[p for p in (R/'tools').glob('*r36.py') if p.name.startswith(('ds_hbm','h3_ds'))];todo=list(roots)+[R/'tests/test_ds_hbm_history_provider_r36.py'];seen=set()
while todo:
 p=todo.pop()
 if p in seen:continue
 seen.add(p)
 for node in ast.walk(ast.parse(p.read_text())):
  names=[]
  if isinstance(node,ast.ImportFrom) and node.module:names=[node.module.split('.')[0]]
  if isinstance(node,ast.Import):names=[n.name.split('.')[0] for n in node.names]
  for name in names:
   dep=R/'tools'/(name+'.py')
   if dep.exists() and dep not in seen:todo.append(dep)
for path in json.loads((R/'results/uarch/ds_hbm_checkpoint_payloads_r35_20261002/source_sha256.json').read_text()):seen.add(R/path)
put('source_sha256.json',{str(p.relative_to(R)):sha(p) for p in sorted(seen)})
put('handoff.json',dict(status='READY_DIRECTED_SOFTWARE_HISTORY_QUERY_GATE_NOT_FULL_GO',provider='tools/h3_ds_query_provider_r36.py:create_provider',manifest_composer='tools/ds_hbm_history_manifest_r36.py',prepared_manifest=str(evidence_args.prepared_manifest),prepared_manifest_sha256=sha(evidence_args.prepared_manifest),tests='8 directed tests plus predecessor regressions recorded separately',actual_directed_scope='L2 PC121 paired writer and PC128 native KV LOAD/gather; PC124 compound RF/state publication and PC125 typed query/key reads. Control payloads are real retained rows, not claimed actual trained compressor/query outputs.',full_metadata_scope='8 index_q operators /1536 addressed field homes; all index_scores/KV gather dynamic binding contracts snapshotted',negative_controls=['stale generation','paired append incomplete','duplicate writer before backing/journal mutation','leased version release','stale reverse identity','wrong query dtype','missing RF parent homes','RF word-count mismatch before any backing mutation','nonrepresentable/nonfinite FP4 payload','empty images cannot instantiate actual provider'],preserved_failures=['draft_query_fixture_return_failure.log','draft_query_journal_capacity_failure.log','draft_query_stream_slice_failure.log'],full_token_GO=False,hardware_credit=False,physical_translation_unknown=True,remaining_aux_refs_not_claimed_closed=288,coordination='Sagan owns bounded PC18 producer/local sparse/ordered views. Mix QueryMixin and HistoryMixin above reviewed Sagan provider without replacing his module; integrated mixin gate still required.',reproduce_commands=['OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python -m pytest -q tests/test_ds_hbm_history_provider_r36.py','python tools/ds_hbm_history_manifest_r36.py --base /tmp/kepler-ds-r35-rich-provider-state-manifest.json --state-receipt results/uarch/ds_hbm_checkpoint_payloads_r35_20261002/entering_state_terminal.json --state-root /tmp/kepler-ds-hbm-r35-entering-state --homes results/uarch/ds_hbm_history_provider_r36_20261002/query_field_homes.json.gz --out <fresh-manifest.json>'],prerequisites=['actual released checkpoint48 shards retained r30 index pin','all actual r35 state images+images.json under DS_HBM_STATE_ROOT; no synthetic fallback','rich reconciled r35 runtime manifest','r34 actual patched native/dispatch/home directory for full integration; directed source projections retained here'],owned_live_jobs=[],no_remote_launch=True))
