"""Mandatory DSpark seed capture, sized before implementation; no adoption credit."""
def model():
    return {
        'schema': 'opentallas.dsrom.hc-mean-capture.v1',
        'source': 'tools/hdc_golden_v41.py:main_hidden_part; input residuals L37,L38,L39',
        'capture_jobs': [{'id':f'L{layer}.mtp.input_hc_capture','layer':layer,
                          'capture':capture,'rank_replicas':4,
                          'ordering':'after this layer Engram, before attn hc_pre or H overwrite',
                          'source_program':'tools/hdc_program_v41.py Program.position_body/mh_capture',
                          'whole_token_DAG_binding':'pending'}
                         for capture,layer in enumerate((37,38,39))],
        'shape': {'hidden': 5120, 'HC': 4, 'TP': 4, 'rank_dimensions': 1280,
                  'captures': 3, 'lanes': 8, 'input_beats_per_capture': 160,
                  'output_flits_per_capture': 40, 'output_flits_per_rank': 120},
        'arithmetic': 'RN(RN(RN(h0+h1)+h2)+h3); RN(sum*0.25); BF16 RNE',
        'MACs_per_cycle': 0,
        'compute_intensity': {'FP32_adds_per_input_byte': 3/8,
                              'FP32_multiplies_per_input_byte': 1/8},
        'ports_bytes_per_cycle': {'HC_input_when_accepted': 64, 'mean_SRAM_write': 72,
                                 'mean_SRAM_read': 72, 'seed_output': 64},
        'boundary_bits_per_cycle': {'HC_input': 512, 'seed_output': 512,
                                   'identity': 37, 'stage': 2, 'beat': 8},
        'replicas': {'proximal_source_units': 12, 'protected_head_join_units': 4,
                     'adders_per_source': 8, 'multipliers_per_source': 8,
                     'SRAM256x256_per_source': 3, 'SRAM256x256_per_head_join': 3,
                     'total_SRAM256x256': 48},
        'mux_demux': {'adder_inputs': '4 residual copies, registered stage select',
                     'SRAM_address': 'capture*40+frame, 0..119'},
        'fanout': {'clock_arithmetic_lanes': 16, 'identity_local_sinks': 8},
        'routing': {'input_tracks': 560, 'output_tracks': 560,
                    'floorplan_pin_capacity_per_face': 2400,
                    'pin_pitch_um': 0.4, 'face_um': 960},
        'area': {'slot_um': [1000, 1000], 'planning_cells_um2': 300000,
                 'cell_utilization_limit': 0.55, 'slot_fit_planning': True,
                 'SRAM_macro_area_um2': 3*172.824*41.064,
                 'qualification': 'planning bound; synthesis and contextual floorplan must confirm'},
        'storage': {'payload_bytes': 7680, 'protected_bits_per_flit': 576,
                    'physical_bits': 3*256*256, 'rows_used': 120,
                    'ECC': '8 SECDED(72,64) per 512b frame; CE corrected, UE stops delivery'},
        'distributed_homes': {'sources':'selected stage_join homes of L37,L38,L39, one per TP4 rank',
                              'source_home_mapping':'pending ds_control selected executable mapping',
                              'joins':'one per TP4 head rank; actual slot pending mtp_die',
                              'source_output_flits':40,'joined_output_flits':120,
                              'VM_input_bytes_per_capture_per_rank':20480,
                              'VM_input_bytes_three_captures_per_rank':61440,
                              'VM_input_bytes_global':245760,
                              'BF16_exact_copy_transport_bytes_if_separately_priced':122880,
                              'mean_publication_bytes_global':30720,
                              'identity_header_flits_global':12,
                              'identity_header_bytes_global':768,
                              'total_publication_flits_per_rank':123,
                              'link_contract':'registered finite-credit endpoint and explicit identity header pending; no far combinational-ready closure claim',
                              'system_slot_area_planning_mm2':15.4},
        'latency': {'adder_stages': 7, 'multiplier_stages': 7,
                    'chunk_cycles_upper': 48, 'three_captures_cycles_upper': 3*160*48,
                    'drain_cycles_upper': 120*8,
                    'ECC_PIPE_increment_cycles_per_frame': 2,
                    'ECC_PIPE_register_bits_per_endpoint': 8*(72+7+1+64+2),
                    'ECC_PIPE_reason': 'measured held_code to output SECDED path 924ps; split syndrome and registered correction',
                    'total_unoverlapped_cycles_upper': 24000,
                    'total_unoverlapped_us_at_1p2GHz': 20.0,
                    'composition': 'mandatory added seed cost; HC input VM reads and CDC not included'},
        'clock': {'domain': 'stream', 'frequency_GHz': 1.2,
                  'setup_uncertainty_ps': 60, 'hold_uncertainty_ps': 25,
                  'acceptance': 'TT setup>=0, FF hold>=0, DRC0; SS sensitivity'},
        'integration': {'default_enabled': False, 'adopted': False,
                        'pending': ['actual pre-hc_pre H VM read adapter',
                                    'layer37/38/39 stage dispatch', 'seed QX delivery',
                                    'exact released h_in gate', 'negative controls',
                                    'contextual physical closure']}}

def seed_join_model():
    return {'schema':'opentallas.dsrom.hc-seed-join.v1',
        'shape':{'captures':3,'frames_per_capture':40,'frame_bits':512,
                 'payload_bytes_per_rank':7680,'TP4_ranks':4},
        'MACs_per_cycle':0,'compute_intensity':0,
        'ports_bytes_per_cycle':{'arrival':64,'SRAM_write':72,'SRAM_read':72,'seed_delivery':64},
        'boundary_bits_per_cycle':{'arrival_data':512,'identity':35,'capture_and_frame':8,'delivery_data':512},
        'replicas':{'head_joins':4,'SRAM256x256_per_join':3},
        'mux_demux':'one registered arrival stream; capture*40+frame address; ordered delivery',
        'fanout':{'identity_register':8,'write_clock':3},
        'routing':{'arrival_tracks':560,'delivery_tracks':560,'face_capacity':1200},
        'area':{'slot_um':[500,500],'planning_cells_um2':15000,'SRAM_macro_area_um2':3*172.824*41.064,'slot_fit_planning':True},
        'latency':{'write_commit_cycles':1,'arrival_frame_II':2,'drain_120_frames_cycles_upper':840,
                   'ECC_PIPE_increment_cycles_per_frame':2,'ECC_PIPE_register_bits':1168,
                   'registered_link_cycles':'pending actual selected source/head homes and finite-credit relays'},
        'integration':{'default_enabled':False,'adopted':False,
                       'pending':['registered link/header binding','actual head slot','golden/negative gate','physical closure']}}

def input_reader_model():
    return {'schema':'opentallas.dsrom.hc-input-reader.v1',
        'shape':{'copies':4,'TP4_rank_dimensions':1280,'words_per_VM_row':16,
                 'rows_read_per_copy_per_rank':80,'read_requests_per_capture':320,
                 'resident_H_dimensions_per_copy':5120,'resident_H_VM_rows':1280,
                 'resident_copy_stride_rows':320,'TP4_rank_offset_rows':80,
                 'address_source':'tools/hdc_replay_v41.py ShapeLayout H=hc*dim even tp_exact=True'},
        'native_port':{'read_slots_required':1,'outstanding_reads':1,
                       'qualification':'existing reserved/shared NP8 slot; owner arbiter and compiler mapping pending'},
        'MACs_per_cycle':0,'compute_intensity':0,
        'ports_bytes_per_cycle':{'VM_read':64,'mean_input':64},
        'boundary_bits_per_cycle':{'VM_request':16,'VM_response':514,'mean_input':521},
        'replicas':{'proximal_readers':12,'protected_hold_register_bits':2304,
                    'ECC_PIPE_additional_register_bits':4*1168},
        'mux_demux':'four response buffers, two contiguous8-dimension halves',
        'fanout':{'clock_protected_bits':2304,'response_selection':4},
        'routing':{'input_tracks':560,'output_tracks':560,'capacity_per_face':1200},
        'area':{'planning_cells_um2':10000,'slot_um':[500,400],'slot_fit_planning':True},
        'latency':{'unoverlapped_control_cycles_upper_per_capture':2240,
                   'ECC_PIPE_increment_per_16_dimensions':3,
                   'ECC_PIPE_increment_cycles_per_capture':240,
                   'ECC_PIPE_encode_increment_cycles_per_response':2,
                   'ECC_PIPE_encode_increment_cycles_per_capture':640,
                   'ECC_PIPE_total_increment_cycles_per_capture':880,
                   'ECC_PIPE_encode_register_bits':8*(64+7+72),
                   'actual_VM_wait_cycles':'sum of320 admitted request-to-real-rvalid waits',
                   'input_reader_cycles_not_in_capture_cost':True},
        'integration':{'adopted':False,'default_enabled':False,
                       'pending':['actual H TP-rank row mapping','native port owner arbitration','exactness','physical closure']}}
