"""Exact P2 expert-return budget; individual FP32 rows retain golden id order."""
import math


def model():
    rank_width = 5120//4
    expert_bytes = rank_width*4
    flits = math.ceil(expert_bytes/64)
    return dict(
        schema='opentallas.dsrom.mtp-p2-transport.v1', adopted=False,
        source='tools/hdc_golden_v41.py dspark expert sum; released width5120 TP4',
        arithmetic='FP32 zero then each expert FP32 output in sorted expert-id order, then shared FP32, then BF16',
        shape=dict(rows_parallel=5, ranks=4, packages=20, stages=3,
                   selected_experts_per_row=3, rank_output_values=rank_width),
        MACs_per_cycle_unchanged=True, compute_intensity_unchanged=True,
        ports=dict(UCIe_bits_per_cycle=512, UCIe_bytes_per_cycle=64,
                   primary_request_BF16_vector_bytes=5120*2,
                   GU_local_BF16_values=576, GU_full_BF16_values=2304,
                   GU_local_BF16_bytes=1152, GU_full_BF16_bytes=4608,
                   GU_TP4_allgather_received_bytes_per_rank=3456,
                   per_expert_return_FP32_bytes=expert_bytes,
                   per_expert_return_flits=flits),
        boundaries=dict(individual_expert_payload_bits_per_cycle=512,
                        identity_bits=74, selected_expert_bits=27, word_index_bits=7,
                        A_B_input_lanes=2, merger_input_bits_per_lane=606,
                        protected_output_bits=671,
                        identity_header_bits='74 transaction bits plus9 expert/7 word/shared/last; exact link framing required'),
        replicas=dict(A_die=20, B_die=20, UCIe_pairs=20),
        mux_demux_fanout=dict(A_sorted_expert_merge_inputs=3,
                             B_return_selection_inputs=3,
                             A_adder_order='must stall until next golden expert arrives; no B pre-sum'),
        storage=dict(A_individual_expert_row_bytes_upper=3*expert_bytes,
                     A_shared_last_row_bytes=expert_bytes,
                     A_total_buffered_rows=4,
                     A_protected_row_payload_bytes=4*expert_bytes,
                     B_pending_expert_row_bytes_upper=3*expert_bytes,
                     pair_row_buffer_bytes_upper=7*expert_bytes,
                     array_row_buffer_bytes_upper=20*7*expert_bytes,
                     protection=dict(code='8 SECDED72 slices per512-bit flit',
                         protected_flit_bits=576, SRAM_bits_per_word=768,
                         SRAM_words=128, live_words_per_row=80,
                         SRAM_master='ot_sram_1r1w_128x256_m1_r2c2',
                         SRAM_macros_per_row=3, A_SRAM_macros=12,
                         B_pending_SRAM_macros=9,
                         metadata_and_flow_state='duplicate control state with mismatch fault; immutable identity',
                         output_consumer='must decode/correct SECDED and abort UE before arithmetic'),
                     actual_minimum_FIFO_implementation_required=True),
        routing=dict(tracks=512, channel_capacity=None),
        area=dict(A_buffer_macro_inventory=12, B_pending_buffer_macro_inventory=9,
                  macro_outline_um=[94.824,41.04],
                  A_raw_SRAM_area_um2=12*94.824*41.04,
                  B_raw_SRAM_area_um2=9*94.824*41.04,
                  A_candidate_slot_um=[400,360],
                  protected_output_FIFO_words=8, protected_output_FIFO_bits=4608,
                  output_FIFO_FF_cell_floor_um2=4608*.2916,
                  finite_merge_cell_area=None,
                  floorplan_slot_fit=False),
        ordered_consumer=dict(initial_accumulator='FP32 +0',
            receipt_order=['expert0', 'expert1', 'expert2', 'shared'],
            selected_experts='strict ascending IDs, three distinct receipts',
            shared_source='among97 excluded primary headers; actual packed producer still absent',
            output_distribution='disjoint1280 FP32 rows/rank; output gather, no output allreduce',
            GU_distribution='TP4 allgather2304 weighted BF16 terms on chosen A/B side before W2',
            rejects=['duplicate', 'wrong expert', 'wrong transaction identity', 'wrong word or last', 'missing shared'],
            arithmetic_RTL_binding_qualified=False),
        stages=[dict(stage=0, B_experts=0, B_return_flits=0),
                dict(stage=1, B_experts=3, B_return_flits=3*flits),
                dict(stage=2, B_experts_range=[0,3], B_return_flits_upper=3*flits)],
        latency=dict(clock_GHz=1.2, old_summed_return_flits=flits,
                     stage1_additional_return_flits=2*flits,
                     stage2_additional_return_flits_upper=2*flits,
                     stage1_extra_serialization_us=2*flits/1200,
                     stage2_extra_serialization_us_upper=2*flits/1200,
                     critical_row_extra_serialization_us_upper=4*flits/1200,
                     ordered_expert_plus_shared_flits=4*flits,
                     protected_buffer_encoder_cycles=1,
                     SRAM_read_cycles=1,
                     consumer_SECDED_decode_cycles=2,
                     per_complete_row_drain_lower_bound_cycles=4*flits+3,
                     multiply_by_5_parallel_rows=False,
                     headers_endpoint_credit_and_ordering_stalls_unmeasured=True,
                     historical_P2_point2us_budget_qualified=False),
        qualification='model-before-build; full-shape output ordering and finite transport gates required')
