#!/usr/bin/env python3
"""Source-bound before/after ledger; separate physical measures from allowances."""
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'results/uarch/dsrom_4096_comparable_capacity_20261002';PINS={}
def get(rev,path):
 b=subprocess.check_output(['git','show',rev+':'+path],cwd=ROOT);PINS[rev+':'+path]=hashlib.sha256(b).hexdigest();return json.loads(b)
def main():
 old=get('4b6708348f3938e0830c3549fbbecadbce18e798','results/uarch/dsrom_l20_hierarchical_reservation_20261002/model.json');outline=get('4b6708348f3938e0830c3549fbbecadbce18e798','results/uarch/dsrom_l20_hierarchical_reservation_20261002/reservation_outline.json');cap=get('f0ead6d60','results/uarch/dsrom_4096_comparable_capacity_20261002/model.json');reticle=get('54d46eff8','results/uarch/dsrom_l20_reticle_prerequisite_20261002/model.json')
 a=old['attention_audit'];idx=old['indexer'];r41=next(r for r in cap['capacity_rows'] if r['stages']==41);r66=cap['comparable_full_no_credit_sensitivity'];ledger=[]
 def row(name,before,after,basis,replicas,ports,buffers,counting):ledger.append(dict(block=name,before_mm2=before,after_mm2=after,area_evidence=basis,replicas=replicas,ports=ports,buffers=buffers,counting_rule=counting))
 row('L20 attention64tiles, QE and service',a['original_39p23175_mm2'],a['attention_service_corrected_placed_proxy_mm2'],'Source-counted cell proxy at50pct; no same-source hard tile exists',64,{'PWORDS':1,'ILV':0,'REPL':0,'NSTAGE':1,'QK_then_PV':True},{'engine_stage_FF_bits':a['engine_stage_FF_bits'],'stationary_FF_bits':a['stationary_FF_bits_counted_once'],'PV_ring_bits':a['PV_ring_bits_additional_counted_once'],'QE_state_bits':a['QE_full_params_state_bits'],'quantizer_children_bits':a['QE_quantizer_children_state_bits']},'Remove TOPK payload from attention and charge once to X_SEL; replace legacy encoder once; add missing960QK+5120PV adders/conditional-write muxes. Existing arrays retained, no optional SRAM branch credit.')
 row('Actual pooled indexer',21.677,idx['placed_proxy_mm2'],'Historical scalar before; source hierarchy/state/arithmetic proxy after; not timing qualification',idx['replicas'],{'HBM_reader_ports':128,'MACs_pc':1024,'input_payload_Bpc_peak':4096,'quarterjoin_Bpc_peak':4352,'NPC':32,'WB':32,'GA':24},{'state_bits':idx['state_bits_subtotal'],'ROB_inferred_SRAM':False},'Historical21.677 replaced by proved actual hierarchy, not silently omitted. Four readers, quarterjoin,batch,finish,keywriter all retained.')
 row('Collector banked service',None,a['banked_collector_island_gross_included_once_mm2'],'Measured existing SRAM outline/OBS plus construction control/escape reservation; proposed service not built',{'banks':4,'SRAM_slices_per_bank':9,'total_macros':36,'peerTXskids':3},{'per_bank_read_ports':1,'per_bank_write_ports':1,'track_obligation':20909},{'selected_seats':512,'WINDOW_rows':128,'own_row_write_bursts':9},'Included once inside attention/service subtotal, never add again to it. Arbitration, visible-write ACK and physical drain remain mandatory source gates.')
 row('X_SEL/TOPK',a['TOPK_524288bits_reassigned_to_X_SEL_mm2'],old['co_resident_reservations_mm2']['X_SEL_TOPK_store'],'Source FF/gate proxy',1,{'selection_count':512},{'TOPK_payload_bits':524288},'Moved out of attention subtotal; still retained in hub total, no storage reduction.')
 row('Prospective common controller cut',0,old['co_resident_reservations_mm2']['common_controller_cut'],'Explicit diagnostic state/mux allowance; not a measured minimum',1,{'added_cycles_per_QK_or_PV_job':2},{'finite_skid_credit_protocol_bound':False},'Included in hub reservation. Separate mandatory correctness repairs from optional timing cut; no certification of2cycles asminimum.')
 component=sum(x['gross_mm2'] for x in outline['components']);routes=sum(x['gross_mm2'] for x in outline['clear_route_bands'])
 row('All clear hub route bands',0,routes,'Source widths and actual native M2/M4 phase/pitch capacity with50pct non-signal reservation',len(outline['clear_route_bands']),old['refit']['route_bands'],{},'Route area added once outside component rectangles; collector local escape remains inside collector island. Halos/PG/vias are not free reusable space.')
 row('Existing attention slot -> total new island',41.09350185216,outline['gross_mm2'],'Old measured source floorplan rectangle; new analytical component+route rectangle',1,{'all_current_source_ports_preserved':True},{},'This is geometric gross area, not an additional charge on top of its component subtotals.')
 for region in old['all_retained_hub_regions']:
  if region['name']=='HUB_ATTENTION':continue
  row(region['name'],region['gross_mm2'],region['gross_mm2'],'Retained source floorplan reservation; not a new hard abstract',1,{'unchanged_source_provider_obligation':True},{},'Preserved once; source SU lane proxy6.074509mm2 is not separately added to the retained SU_VECTOR rectangle.')
 row('4096 mixed q field strips at41',r41['integer_mixed_field_need_mm2'],r41['integer_mixed_field_need_mm2'],'Payload density+integer source pair count; calibrated W10b q/column footprint sizing, no physical transfer',{'q_pairs':3749,'BF16_pairs':1024,'4096_PP_macros':19092},{'q_MACs_pc':128,'BF16_MACs_pc':32,'effective_ROM_Bpc_per_pair':68.5,'physical_ROM_ports_per_pair':4},{'q_XF':4,'BF16_WAKEXF':8},'Includes original strip state and arithmetic. FullBF proxy749.229mm2 is not the mixed product456.258mm2; original8192 two-macro slot is not an actual4096 inventory.')
 row('Full return138469120bit construction',0,cap['return_FF_construction']['area_mm2'],'Explicit FF construction allowance at50pct; actual dataflow store area is not established',{'required_bits':138469120},{'actual_return_bank_port_contract_bound':False},{'all_bits_retained':True},'Conservative gross addition with no embedded-slot credit. Some original strip storage is already priced: named FF/provider ledger must reconcile it before any subtraction. This is not proof that105mm2 is necessary or minimal.')
 row('Mandatory WAKE growth at41',0,r41['WAKE_increment_mm2'],'Source fullgoal register/FIFO/control construction bound; physical SSFF still open',{'q_pairs':3749,'BF16_pairs':1024},{'external_port_fanout_delta':0,'wake_leaf_fanout':1,'wake_next_fanout':8},{'column_XF':8,'extra_column_FIFO_bits_per_pair':2128},'Only incremental cost added; original strip remains once. No throughput/capacity or golden-tree change.')
 row('Mandatory shared RNE growth',0,cap['RNE_construction']['per_die_increment_mm2'],'Source-decomposed conservative NAND construction bound, not mapped/measured delta',{'BF16_pairs':1024,'multiplier_leaves':32768},{'stages':5,'new_pipeline_cycles':0},{'new_state_bits':0},'BF16 leaves only; q BF16-disabled mode does not acquire a fullBF leaf charge. Original multiplier area remains in strip once. Actual repair may map smaller; no timing closure transfer.')
 padding=outline['gross_mm2']-component-routes;assert padding>=0
 row('Hub rectangle geometric padding',0,padding,'Difference between source-sized outer rectangle and component/route rectangles',1,{}, {},'Not usable free cell or routing credit. Explicitly retained once in gross island area.')
 assert abs(component+routes+padding-outline['gross_mm2'])<1e-6
 options=[]
 for S in [41,43,66]:
  r=next(r for r in cap['capacity_rows'] if r['stages']==S);hops=S-41
  options.append(dict(stages=S,total_dies=r['total_dies'],die_envelope_mm=[26,33],stitching=False,BF16_pairs=1024,q_pairs=r['q_pairs'],physical4096macros=r['current4096_PP_macros'],ROM_storage_bits=r['physical_ROM_storage_bits'],required_payload_bits=r['required_payload_bits'],full_return_required_bits=138469120,full_conservative_need_mm2=r['full_conservative_need_mm2'],usable_field_mm2=r['usable_field_mm2'],gross_capacity_margin_mm2=r['usable_field_mm2']-r['full_conservative_need_mm2'],gross_capacity_screen=r['full_no_credit_sensitivity_fit'],conditional_added_source_stage_dependency_us=hops*cap['latency']['source_stage_dependency_hop_us'],compiler_ownership_verified=False,legal_composed_fit_verified=False,optimal_per_user_latency_certified=False))
 x=dict(schema='opentallas.DSROM4096.before-after-ledger.v1',pins=PINS,binding_die_envelope_mm=[26,33],stitching_allowed=False,ledger=ledger,hub_component_rectangle_mm2=component,hub_clear_route_rectangle_mm2=routes,field_debit_fixed815_mm2=outline['fixed815_field_debit_mm2'],reticle_constrained_added_overhead_mm2=reticle['constrained_alternative']['added_die_overhead_reservation_mm2'],baseline_basis=dict(source28='Historical busiest-macro reference/standard-pair geometry; raw6985pairs at28 does not reproduce the current mixed4096 product41-stage fit',product41='Current mixed W10b4096 product:1024BF16 pairs, q remainder;208dies retainedcomparison',reported_r4='224stages940dies baseline28 reported by user; exact r4 source file not intaken; no equal-basis reproduction claimed'),options=options,optimal_qualified_option=None,why_no_full_composed_option='Every option lacks actual compiler-stage ownership, source-matched repaired element abstract/OBS/PG/SSFF, full return-provider dedup/finite-port ledger, finite jointREADY/physical-drain service bounds and actual token-event repricing. Capacity screen cannot replace these proofs.',original_failures_preserved=True,no_capacity_shrunk=True,no_RTL_PnR=True,generator_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest())
 p=OUT/'before_after_ledger.json';b=(json.dumps(x,indent=2,sort_keys=True)+'\n').encode()
 if p.exists():assert p.read_bytes()==b
 else:p.write_bytes(b)
 print(json.dumps(dict(block_ledger_rows=len(ledger),hub_component_mm2=component,hub_routes_mm2=routes,qualified_full_composed_options=0,stitching=False)))
if __name__=='__main__':main()
