"""Minimum shared-W2 arithmetic vehicle; sized before build, no system credit."""
def model():
    return dict(schema='opentallas.mtp-shared-qelem.v1',adopted=False,
        source='fa27bd60819f9bf61483d5605a02837fe6a34088',
        shape=dict(K=2304,rows=2,rank_rows=1280,TP=4,positions=6),
        MACs_per_issue_cycle=64,compute_intensity_MACs_per_weight_byte=1,
        reads=dict(issues=72,rowbank_reads=144,weight_payload_bytes=4608,
            activation_blocks=72,quantisers=2),
        ports_bytes_per_cycle=dict(ROM_payload=64,ROM_carrier=68.5,
            quantiser_testbench_feed=256,native_VM='unbound; no 256B/cycle VM claim'),
        boundaries_bits_per_cycle=dict(ROM_carrier=548,quantiser_testbench_feed=2048,
            element_root=64,rounded_widened_output=64),
        replicas=dict(minimum_NB2_elements=1,production_engine_count='unqualified',
            measured_rows_per_run=2),
        mux_demux='one configured phase; two independent rowbank roots and actual return rounders',
        fanout='one clock domain; one activation stream per rowbank',
        routing=dict(element_slot_um=[510.84,221.4],new_route=False,
            channel_capacity='existing selected native master; no new physical claims'),
        area=dict(native_master='ot_v41_rom_elem_q_qxpq_w10',physical_closed=False,
            return_rounders=2,return_rounder_parameters=dict(D=16,QD=16)),
        latency=dict(issue_cycles=72,quantiser_input_cycles=36,configuration_words=25,
            PQ_shadow_replay='wait actual sh_free/walking plus existing six-cycle guard',
            root_and_round_fill='must measure actual RTL',six_position_sharing='no production extrapolation',
            W1_W3_GU='golden fixture generation only; not measured RTL or production input'),
        arithmetic='golden chunk8 FP8 exact block32 dot, native raw FP32 root, actual ot_v41_ret_root RNE BF16 then widen',
        fixture='released shared W1/W3/W2, scoped backbone L38 h_in[0] BF16 sample; NOT MTP shared GU capture',
        qualification=dict(field_descriptor=False,production_VM_binding=False,
            actual_MTP_input=False,native_arithmetic=False,physical=False))
