"""Mandatory DSpark seed capture, sized before implementation; no adoption credit."""
def model():
    return {
        'schema': 'opentallas.dsrom.hc-mean-capture.v1',
        'source': 'tools/hdc_golden_v41.py:main_hidden_part; input residuals L37,L38,L39',
        'shape': {'hidden': 5120, 'HC': 4, 'TP': 4, 'rank_dimensions': 1280,
                  'captures': 3, 'lanes': 8, 'input_beats_per_capture': 160,
                  'output_flits_per_capture': 40, 'output_flits_per_rank': 120},
        'arithmetic': 'RN(RN(RN(h0+h1)+h2)+h3); RN(sum*0.25); BF16 RNE',
        'MACs_per_cycle': 0,
        'compute_intensity': {'FP32_adds_per_input_byte': 3/8,
                              'FP32_multiplies_per_input_byte': 1/8},
        'ports_bytes_per_cycle': {'HC_input_when_accepted': 64, 'mean_SRAM_write': 72,
                                 'mean_SRAM_read': 72, 'seed_output': 64},
        'boundary_bits_per_cycle': {'HC_input': 512, 'seed_output': 512,
                                   'identity': 37, 'stage': 2, 'beat': 8},
        'replicas': {'capture_units_per_TP4_group': 4, 'adders_per_unit': 8,
                     'multipliers_per_unit': 8, 'SRAM256x256_per_unit': 3},
        'mux_demux': {'adder_inputs': '4 residual copies, registered stage select',
                     'SRAM_address': 'capture*40+frame, 0..119'},
        'fanout': {'clock_arithmetic_lanes': 16, 'identity_local_sinks': 8},
        'routing': {'input_tracks': 560, 'output_tracks': 560,
                    'floorplan_pin_capacity_per_face': 2400,
                    'pin_pitch_um': 0.4, 'face_um': 960},
        'area': {'slot_um': [1000, 1000], 'planning_cells_um2': 300000,
                 'cell_utilization_limit': 0.55, 'slot_fit_planning': True,
                 'SRAM_macro_area_um2': 3*94.824*41.040,
                 'qualification': 'planning bound; synthesis and contextual floorplan must confirm'},
        'storage': {'payload_bytes': 7680, 'protected_bits_per_flit': 576,
                    'physical_bits': 3*256*256, 'rows_used': 120,
                    'ECC': '8 SECDED(72,64) per 512b frame; CE corrected, UE stops delivery'},
        'latency': {'adder_stages': 7, 'multiplier_stages': 7,
                    'chunk_cycles_upper': 48, 'three_captures_cycles_upper': 3*160*48,
                    'drain_cycles_upper': 120*6,
                    'total_unoverlapped_cycles_upper': 23760,
                    'total_unoverlapped_us_at_1p2GHz': 19.8,
                    'composition': 'mandatory added seed cost; HC input VM reads and CDC not included'},
        'clock': {'domain': 'stream', 'frequency_GHz': 1.2,
                  'setup_uncertainty_ps': 60, 'hold_uncertainty_ps': 25,
                  'acceptance': 'TT setup>=0, FF hold>=0, DRC0; SS sensitivity'},
        'integration': {'default_enabled': False, 'adopted': False,
                        'pending': ['actual pre-hc_pre H VM read adapter',
                                    'layer37/38/39 stage dispatch', 'seed QX delivery',
                                    'exact released h_in gate', 'negative controls',
                                    'contextual physical closure']}}
