"""Primary shared-expert publication, sized before RTL; no execution credit."""
def model():
    return dict(schema='opentallas.dsrom.mtp-shared-producer.v1', adopted=False,
        golden='expert W2 linear_q rounds BF16; widened FP32 shared contribution is added LAST to ordered routed prefix; final sum rounds BF16 once',
        shape=dict(TP=4, rank_rows=1280, row_origin='1280*rank', W2_K=2304,
            W2_fmt_fp32=False, input_native_widened_FP32_flits=80, output_widened_FP32_flits=80,
            positions=6, resident_contexts=1, six_position_sharing='serial command/capture/drain; next context waits for last handshake'),
        context=dict(bits=74, transaction=[0,32], user=[32,10], position=[42,21],
            epoch=[63,4], stage=[67,2], rank=[69,2], draft_frame=[71,3],
            word_bits=7, output_word_range=[0,79], input_word_range=[0,79]),
        MACs_per_cycle=0, compute_intensity=0,
        ports_bytes_per_cycle=dict(native_field_return=64, SRAM_write=72,
            SRAM_read=72, SU_shared_delivery=64),
        boundaries_bits_per_cycle=dict(field_payload=512, field_context=74,
            field_word=7, SU_payload=512, SU_context=74, SU_word=7),
        replicas=dict(primary_rank_units=4, SRAM256x256_per_rank=3,
            total_SRAM256x256=12, output_multiplexer='single512bit native widenedFP32 SRAM row'),
        storage=dict(mathematical_BF16_bytes_per_rank=2560,native_payload_bytes_per_rank=5120, rows_used=80,
            physical_bits_per_rank=196608, ECC='8SECDED72/64 per512bit SRAM row; CEcorrected/UEblocksoutput',
            protection='context/state/counters duplicated with complement guards; no ROM ECC'),
        mux_demux=dict(write='single ordered80flit capture',read='single ownedcontext, ordered80 widenedflits'),
        fanout=dict(clock_macro_pins=3, ECC_lanes=8, context_sinks=4),
        routing=dict(field_tracks=594,SU_tracks=596,face_capacity_tracks=800,
            pin_pitch_um=.4,face_um=320),
        area=dict(slot_um=[320,320],SRAM_macro_um=[172.824,41.064],
            SRAM_area_um2_per_rank=3*7096.844736,planning_cells_um2=20000,
            utilization_limit=.55,planning_fit=True,physical_closed=False),
        latency=dict(input_frame_II=3,input_frames=80,read_prepare_cycles=3,
            output_frames=80,unoverlapped_endpoint_cycles_upper=562,
            selected_ECC_pipe=True,ECC_decoder_stages=2,
            selected_endpoint_cycles_upper=722,selected_endpoint_nominal_ns_upper=722/1.2,
            six_positions_endpoint_cycles_upper=6*722,
            excluded=['native sharedW1/W3/GU/W2 arithmetic','field dispatch and returngaps','linkstation hops','consumerbackpressure']),
        clock=dict(domain='stream',GHz=1.2,setup_uncertainty_ps=60,hold_uncertainty_ps=25,
            acceptance='TTsetup>=0 FFhold>=0 DRC0; SS sensitivity'),
        native_field_abi='spine pq396-399/pqc607: o_we/o_addr/o_data scalar32 perregion, BF16format selects{r_bf16,16zero}; first512bitpublisher requires actualVMreader, not assumed packedfieldflits',
        qualification=dict(native_shared_arithmetic=False,actual_field_return_binding=False,
            endpoint_exact=False,contextual_physical=False))

def reader_model():
    return dict(schema='opentallas.dsrom.mtp-shared-native-reader.v1',default_enabled=False,
        shape=dict(rank_rows=1280,native_VM_rows=80,words_per_row=16,row_bits=512),
        port=dict(existing_reserved_slot='read1, shared through ds_control arbiter',
            native_ready=False,facade_req_ready='actual arbiter grant',
            response='actual native rsp_v routed by finite outstanding owner',
            outstanding_reads=1,additional_native_ports=0),
        lease=dict(context_bits=74,base_bits=14,range_bits=15,
            lifetime='command acceptance until endpoint final80th output handshake',
            required='matching valid range lease and nativeW2 VMwrite-retired fence before command'),
        MACs_per_cycle=0,compute_intensity=0,
        ports_bytes_per_cycle=dict(VM_response=64,endpoint_delivery=64),
        boundaries_bits_per_cycle=dict(request_address=14,request_context=74,request_word=7,
            response_payload=512,response_owner_context=74,response_word=7),
        replicas=dict(primary_ranks=4,protected_response_buffer_bits=1024),
        mux_demux='one outstanding response buffer, no response accepted under another lease',
        fanout=dict(clock_protected_bits=1254),
        routing=dict(request_tracks=98,response_tracks=598,capacity_tracks=800),
        area=dict(planning_cells_um2=10000,slot_um=[200,200],utilization_limit=.55,closed=False),
        latency=dict(request_grant_and_response_latency='actual owner input; no native II assumed',
            response_to_delivery_register_cycles=1,delivery_handshake_cycles=1,
            requests_per_context=80,overlap='one buffer, next request after prior delivery'),
        source_namespace=dict(symbolic='E3, o_base+decodedo_d, rank-origin from selected dispatch',
            numeric_base_bound=False,selected_phase_bound=False,native_write_visibility_bound=False,
            reserved_read1_owner_bound=False),
        qualification=dict(minimum_facade=False,native_binding=False,physical=False))
