"""Source-pinned PINREG1 closure proposal; no RTL or routed verdict changes."""

def model():
    from dsrom_markov_model import model as row_model
    base = row_model(k=256, pinreg=1)
    return dict(
        schema='opentallas.dsrom.markov.pinreg1-closure-proposal.v1',
        status='CLAUDE_FAST_REVIEW_REQUIRED_BEFORE_REPAIR_PILOT_OR_NEW_ROUTE',
        base=base,
        RTL_source_commit='38f22c6d8', terminal_evidence_commit='45e29a281',
        proposal='Existing RTL only: source-pinned TT/FF clone repair feasibility first, then selective LVT on capture-enable data cone and local output delay anchors if measured feasible.',
        measured=dict(TT_setup_ps=-28.62, FF_hold_ps=-66.87, SS_sensitivity_ps=-307.79,
            DRC=0, TT_output_setup_headroom_ps=304.588257, FF_reg_to_reg_ps=-12.51,
            TT_start='in_valid', TT_end='g_pin.embed_q[240]$_DFFE_PP_',
            FF_start='out_bits[3]$_DFFE_PN0P_', FF_end='out_bits[3]',
            TT_input_delay_ps=907, TT_calibration_insertion_ps=657,
            FF_input_min_ps=546, FF_output_min_ps=-596,
            FF_output_clock_arrival_ps=416.99, FF_output_data_arrival_ps=554.13,
            FF_output_required_ps=621, TT_capture_enable_cone_ps=412.23,
            routed_standard_cells=172017, routed_cell_area_um2=22418.6,
            sequential_cells=42587),
        selective_LVT=dict(max_fraction=0.02, maximum_routed_cells=3440,
            worst_path_gate_seed_count=14,
            worst_path_gate_seeds=['input1816','place10471','place10469','_124225_',
                'rebuffer10535','_124226_','rebuffer16774','place7657','place7655',
                'place7647','rebuffer16768','place7644','_124852_','_124853_'],
            target='Data-only union of actual failing capture-enable cones; no clocks, flops, arithmetic, or output hold path VT swap.',
            gain_required_ps=28.62, gain_measured=False,
            pin_and_footprint_equivalence='Must validate each actual LVT master before swapping; no equivalence assumed.',
            leakage_energy='Unmeasured incremental LVT leakage/dynamic power, report actual switched count and cell area; no energy credit.'),
        hold_repair=dict(
            feasibility='Not yet measured. Existing TT output slack304.59 exceeds FF delay deficit66.87, but loaded buffer/corner ratios and all endpoints must be measured on cloned routed objects.',
            pilot='After Claude FAST review: admitted remote clone of pinned 6_final.odb/SPEF, exact existing TT833/60 and FF833/25 effective SDC; local output delay/anchor repair plus register hold repair, protected setup endpoints. Preserve original objects.',
            measurement_basis='Same actual source-pinned TT and FF libraries and final SDC; no old SS virtual insertion, no new latency, no relaxed IO or clock.',
            illustrative_output_anchor_count=136,
            illustrative_output_anchor_basis='At most four physical delay anchors per34 output payload/valid/fault pins; estimate only, not an execution or convergence cap.',
            planning_output_anchor_area_um2=71,
            planning_output_anchor_area_basis='136 x routed average cell area22418.6/172017 x4 conservatism, rounded upward; actual chosen cell sizes and count override estimate.',
            other_hold_repair_area_um2='Unknown until all actual FF violating endpoints are measured; reg-to-reg-12.51 is separately required.',
            pilot_PASS='TTsetup>=0, FFhold>=0, original IO budgets/833.333/60/25 unchanged, followed by required reroute/DRC0 qualification.',
            pilot_failure_action='No selective-LVT new route if actual FF output hold cannot be repaired under the current TT budget.'),
        latency=dict(added_cycles=0, accepted_beat_stage_change=0,
            first_result_cycles=178, bubble_case_cycles=190,
            token_rate_gain_claimed=False),
        resources=dict(MACs_per_cycle=16, weight_bytes_per_cycle=32,
            embed_bytes_per_cycle=32, output_bytes_per_cycle=4,
            boundary_bits_unchanged=True, replicas_unchanged=True,
            added_FFbits=0, added_macros=0, new_control_integrity_layers=0,
            slot_um=[600,600], core_area_um2=354956,
            output_anchor_planning_cell_area_um2=22489.6,
            output_anchor_planning_utilization=0.0634,
            full_hold_repair_slot_fit='Pending actual measured repair inventory; no gross outline change proposed.'),
        exact_gate='Existing48 fullK256 released/stress rows +bubbles/outputstalls+faultcases and separate-logit-add mutant remain source-pinned, RTL byte-identical.',
        rejected='No baseline restart, no PINREG2 successor, no fault-cone staging without an actual fault path, no relaxed constraints.',
        qualified=False)
