"""Finite exact FP32 prefix consumer, sized before candidate RTL."""
def model():
    return dict(schema='opentallas.dsrom.mtp-p2-prefix-arithmetic.v1',adopted=False,
        shape=dict(rank_values=1280,flits_per_expert=80,experts=3,lanes=16,contexts=1),
        arithmetic='RN(RN(RN(+0,E0),E1),E2), each E is BF16-rounded W2 widenedFP32',
        primitive=dict(master='ot_v41_fadd',CUT='1_0111_1011',SPLIT9=0,
            latency_cycles=8,primitive_II=1,clock_domain='stream',clock_GHz=1.2,
            contextual_timing_qualified=False),
        MACs_per_cycle=0,FP32_adds_per_issue=16,
        intensity=dict(adds_per_input_byte=.25,actual_consumer_II_upper=24),
        memory=dict(accumulator_SRAM='ot_sram_1r1w_128x256_m1_r2c2',
            macros=3,word_bits=768,protected_bits=576,live_words=80,
            port_read_bytes_per_active_cycle=96,port_write_bytes_per_active_cycle=96,
            arithmetic_read_payload_bytes_per_active_cycle=64),
        protection=dict(SECDed_slices=8,code='Hsiao SECDED72 systematic {check8,data64}; same ot_secded_cols.svh as ordered transport',decode_cycles=2,
            encode_cycles=1,UE='poison transaction; no subsequent output',
            control='duplicated identity, expert index and word state; mismatch fault'),
        boundary=dict(input_protected_bits=576,output_protected_bits=576,
            identity_bits=74,word_bits=7,expert_bits=9,credit_depth=1),
        replicas=dict(prefix_engines=20,adder_lanes_per_engine=16),
        mux_demux=dict(accumulator_first_input='constant +0 only for E0; SRAM otherwise',
            within_word_order='three expert-major stages, no pre-sum/copy-first shortcut'),
        fanout=dict(clock_adders=16,identity_sinks=1),
        routing=dict(input_tracks=671,output_tracks=671,channel_capacity=None),
        area=dict(slot_um=[500,500],raw_SRAM_um2=3*94.824*41.04,
            reference_other_adder_area_um2=385.524,adder_planning_multiplier=2,
            lane_adder_planning_um2=16*2*385.524,
            whole_logic_planning_upper_um2=90000,planning_total_utilization=.407,
            measured_actual_area=None,physical_slot_fit_qualified=False),
        latency=dict(one_flit_service_cycles_upper=24,
            all_three_experts_cycles_upper=240*24,
            final_read_decode_output_cycles_upper=80*6,
            unoverlapped_cycles_upper=6240,unoverlapped_us_at1p2GHz=5.2,
            transport_overlap_credit=0,
            composition='candidate upper bound replaces unpriced A-prefix consumer; add actual primary shared-last and board/CDC costs separately'),
        integration=dict(default_enabled=False,
            predecessor_transport='PRIMARY_SHARED=1 three-bank protected ordered rows',
            contribution_low16_zero_required=True,
            pending=['real released contribution gate and signedzero control',
                'actual consumer decode/UE correction and state-injection gate',
                'native prefix publisher and existing transaction namespace',
                'contextual mapped master and clock/pin budgets']))
