#!/usr/bin/env python3
"""Deterministic affine IEEE reflected CRC source; originals never edited."""
from pathlib import Path
import zlib
ROOT=Path(__file__).resolve().parents[1]
def generated():
    zero=zlib.crc32(bytes(36))
    rows=[]
    for chunk in range(6):
        masks=[0]*32
        for bit in range(48):
            msg=bytearray(36);n=chunk*48+bit;msg[n//8]=1<<(n%8)
            influence=zlib.crc32(msg)^zero
            for out in range(32):
                if (influence>>out)&1:masks[out]|=1<<bit
        for out,mask in enumerate(masks):
            rows.append(f" assign partial[{chunk}][{out}] = ^(message[{chunk*48}+:48] & 48'h{mask:012x});")
    return '''`timescale 1ns/1fs
// Generated by tools/emb_boot_crc_sources.py. Six independent48bit affine chunks.
// Outputvalid at second edge; engine consumesCRC+mod32sum at third edge.
module ot_qfd_emb_boot_crc #(parameter integer MUT=0)(
 input wire clk,rst_n,i_v,input wire [24:0] i_e,input wire [255:0] i_data,
 output wire busy,output reg o_v,output reg [31:0] o_crc);
 wire [287:0] message={i_data,7'd0,i_e};
 wire [31:0] partial[0:5];reg [31:0] captured[0:5];reg v1;
 assign busy=v1|o_v;
'''+ '\n'.join(rows)+f'''
 integer k;
 always @(posedge clk or negedge rst_n)
 if(!rst_n)begin v1<=0;o_v<=0;o_crc<=0;for(k=0;k<6;k=k+1)captured[k]<=0;end
 else begin
 v1<=i_v;o_v<=v1;
 if(i_v)for(k=0;k<6;k=k+1)captured[k]<=partial[k];
 if(v1)o_crc<=captured[0]^captured[1]^captured[2]^captured[3]^captured[4]^captured[5]^32'h{zero:08x}^32'(MUT!=0);
 end
endmodule
'''
def successor():
    p=ROOT/'rtl/qwen_sys/emb_hbm_20261008/ot_qfd_emb_strip.sv'
    s=p.read_text().replace('module ot_qfd_emb_strip #(', 'module ot_qfd_emb_strip_crc #(')
    s=s.replace('parameter integer MUT = 0','parameter integer CRC_PIPE = 0,\n    parameter integer CRC_MUT = 0,\n    parameter integer MUT = 0')
    insert='''
    wire crc_accept = st==B1 && bl[25] && bl[24:23]==2'(STK) &&
        ((TWIN!=0)?ge2[bl[22:18]]:(cred[bl[22:18]]!=0));
    wire crc_busy,crc_valid;wire [31:0] crc_result;
    generate if(CRC_PIPE!=0)begin:g_crc
      ot_qfd_emb_boot_crc #(.MUT(CRC_MUT)) pipe(.clk(clk),.rst_n(rst_n),
        .i_v(crc_accept),.i_e(be),.i_data(bd),.busy(crc_busy),.o_v(crc_valid),.o_crc(crc_result));
    end else begin:g_original
      assign crc_busy=1'b0;assign crc_valid=1'b0;assign crc_result=32'd0;
    end endgenerate
'''
    s=s.replace('    integer p;\n',insert+'    integer p;\n',1)
    s=s.replace('            dec = 0; dec2 = 0;', '            dec = 0; dec2 = 0;\n            if(CRC_PIPE!=0 && crc_valid)csum<=csum+crc_result;')
    s=s.replace('if (allf && !stat_v)', 'if (allf && !stat_v && !crc_busy)')
    s=s.replace('csum <= csum + crc_sector(be, bd); wcnt <=', 'if(CRC_PIPE==0)csum <= csum + crc_sector(be, bd); wcnt <=')
    return s
if __name__=='__main__':
    d=ROOT/'rtl/qwen_sys/emb_hbm_20261008'
    (d/'ot_qfd_emb_boot_crc.sv').write_text(generated())
    (d/'ot_qfd_emb_strip_crc.sv').write_text(successor())
