#!/usr/bin/env python3
"""Deterministically emit the additive raw-flop 8-PC transport node (V20/X2)."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SOURCE = r'''// Generated by tools/emb_hbm_group_sources.py; plain flop queues under V20/X2; no ECC or control mirrors.
module ot_qfd_emb_group_node #(parameter integer ENABLE=0,PCBASE=0)(
 input wire clk,rst_n,
 input wire [349:0] cmd_i,
 output wire [349:0] cmd_o,
 output wire [287:0] cmd0,
 output wire [287:0] cmd1,
 output wire [287:0] cmd2,
 output wire [287:0] cmd3,
 output wire [287:0] cmd4,
 output wire [287:0] cmd5,
 output wire [287:0] cmd6,
 output wire [287:0] cmd7,
 input wire [259:0] ret0,
 input wire [259:0] ret1,
 input wire [259:0] ret2,
 input wire [259:0] ret3,
 input wire [259:0] ret4,
 input wire [259:0] ret5,
 input wire [259:0] ret6,
 input wire [259:0] ret7,
 input wire [265:0] upstream_i,
 output wire upstream_credit,
 output wire [265:0] reply_o,
 input wire downstream_credit,
 output wire fault
);
 generate if(ENABLE!=0)begin: enabled
  reg [349:0] trunk;
  reg [264:0] mem[0:71]; // Exactly 9 x 8 raw flop slots; no hidden ninth slot.
  reg [2:0] rp[0:8],wp[0:8];reg [3:0] used[0:8];
  reg [2:0] outstanding[0:7];
  reg [3:0] credits,rr;
  reg [264:0] out_data;reg out_valid,up_credit;
  reg sticky_fault;
  wire [259:0] returns[0:7];
  assign returns[0]=ret0;
  assign cmd0=sticky_fault ? 288'b0 : {trunk[318+PCBASE+0],trunk[286+PCBASE+0],trunk[285:0]};
  assign returns[1]=ret1;
  assign cmd1=sticky_fault ? 288'b0 : {trunk[318+PCBASE+1],trunk[286+PCBASE+1],trunk[285:0]};
  assign returns[2]=ret2;
  assign cmd2=sticky_fault ? 288'b0 : {trunk[318+PCBASE+2],trunk[286+PCBASE+2],trunk[285:0]};
  assign returns[3]=ret3;
  assign cmd3=sticky_fault ? 288'b0 : {trunk[318+PCBASE+3],trunk[286+PCBASE+3],trunk[285:0]};
  assign returns[4]=ret4;
  assign cmd4=sticky_fault ? 288'b0 : {trunk[318+PCBASE+4],trunk[286+PCBASE+4],trunk[285:0]};
  assign returns[5]=ret5;
  assign cmd5=sticky_fault ? 288'b0 : {trunk[318+PCBASE+5],trunk[286+PCBASE+5],trunk[285:0]};
  assign returns[6]=ret6;
  assign cmd6=sticky_fault ? 288'b0 : {trunk[318+PCBASE+6],trunk[286+PCBASE+6],trunk[285:0]};
  assign returns[7]=ret7;
  assign cmd7=sticky_fault ? 288'b0 : {trunk[318+PCBASE+7],trunk[286+PCBASE+7],trunk[285:0]};
  assign cmd_o=sticky_fault ? 350'b0 : trunk;
  assign reply_o=sticky_fault ? 266'b0 : {out_valid,out_data};
  assign upstream_credit=!sticky_fault && up_credit;
  assign fault=sticky_fault;
  reg [8:0] incoming;
  reg [264:0] packet[0:8];
  reg range_bad,protocol_bad,overflow_bad,have,tentative,pop;
  reg [264:0] head;
  integer selected,idx,n;
  always @* begin
   incoming=0;
   for(n=0;n<8;n=n+1)begin incoming[n]=returns[n][259]|returns[n][258];packet[n]={5'(PCBASE+n),returns[n]};end
   incoming[8]=upstream_i[265];packet[8]=upstream_i[264:0];
   range_bad=(credits>8)||(rr>8)||!(PCBASE==0||PCBASE==8||PCBASE==16||PCBASE==24);
   for(n=0;n<9;n=n+1)begin
    if(used[n]>8 || 3'(wp[n]-rp[n])!=used[n][2:0])range_bad=1;
   end
   protocol_bad=upstream_i[265] && !(upstream_i[259]||upstream_i[258]);
   for(n=0;n<8;n=n+1)begin
    if(outstanding[n]>4)range_bad=1;
    if(returns[n][259] && outstanding[n]==0)protocol_bad=1;
    if(trunk[318+PCBASE+n] && outstanding[n]==4 && !returns[n][259])protocol_bad=1;
   end
   have=0;selected=0;
   for(n=0;n<9;n=n+1)begin
    idx=rr+n;if(idx>=9)idx=idx-9;
    if(!have && idx<9 && used[idx]!=0)begin selected=idx;have=1;end
   end
   head=mem[selected*8+rp[selected]];
   tentative=have && credits!=0 && !range_bad && !protocol_bad && !sticky_fault;
   overflow_bad=0;
   for(n=0;n<9;n=n+1)if(incoming[n] && used[n]==8 && !(tentative && selected==n))overflow_bad=1;
   if(downstream_credit && credits==8 && !tentative)protocol_bad=1;
   pop=tentative && !overflow_bad && !protocol_bad;
  end
  integer q;
  always @(posedge clk or negedge rst_n)
   if(!rst_n)begin
    trunk<=0;credits<=8;rr<=0;out_data<=0;out_valid<=0;up_credit<=0;sticky_fault<=0;
    for(q=0;q<9;q=q+1)begin rp[q]<=0;wp[q]<=0;used[q]<=0;end
    for(q=0;q<8;q=q+1)outstanding[q]<=0;
   end else begin
    trunk<=cmd_i;
    out_valid<=0;up_credit<=0;
    if(range_bad||protocol_bad||overflow_bad)sticky_fault<=1;
    if(!sticky_fault && !range_bad && !protocol_bad && !overflow_bad)begin
     credits<=credits+downstream_credit-pop;
     for(q=0;q<8;q=q+1)outstanding[q]<=outstanding[q]+trunk[318+PCBASE+q]-returns[q][259];
     for(q=0;q<9;q=q+1)begin
      used[q]<=used[q]+incoming[q]-(pop && selected==q);
      if(incoming[q])begin mem[q*8+wp[q]]<=packet[q];wp[q]<=wp[q]+1'b1;end
      if(pop && selected==q)rp[q]<=rp[q]+1'b1;
     end
     if(pop)begin
      // Raw flop head capture precedes visible retirement credit; no ECC claim.
      out_data<=head;out_valid<=1;up_credit<=selected==8;
      rr<=selected==8 ? 0 : selected+1;
     end
    end
   end
 end else begin: disabled
  assign cmd_o=350'b0;assign upstream_credit=1'b0;assign reply_o=266'b0;assign fault=1'b0;
  assign cmd0=288'b0;
  assign cmd1=288'b0;
  assign cmd2=288'b0;
  assign cmd3=288'b0;
  assign cmd4=288'b0;
  assign cmd5=288'b0;
  assign cmd6=288'b0;
  assign cmd7=288'b0;
 end endgenerate
endmodule
'''
def generate():
    (ROOT/'rtl/qwen_sys/emb_hbm_20261008/ot_qfd_emb_group_node.sv').write_text(SOURCE)
if __name__=='__main__': generate()
