#!/usr/bin/env python3
"""Emit additive wire-only far endpoint wrapper; native source is immutable."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def generate():
    text='''// Generated by tools/emb_hbm_far_port_sources.py. No new registers or cycles.
module ot_qfd_link_far_bus #(
 parameter integer ENABLE=0, CR=128, OD=8, ECR=4, KCR=4, TQ=4, AD=8
)(
 input wire ck,lclk,rst_n,
 input wire [527:0] hub_i, output wire [527:0] hub_o,
 input wire [524:0] emb_i, output wire [524:0] emb_o,
 input wire [524:0] kv_i, output wire [524:0] kv_o,
 output wire fault
);
 generate if (ENABLE != 0) begin: enabled
  ot_qfd_link_far #(.CR(CR),.OD(OD),.ECR(ECR),.KCR(KCR),.TQ(TQ),.AD(AD)) core(
   .ck(ck),.lclk(lclk),.rst_n(rst_n),.l_i(hub_i),.l_o(hub_o),
   .e_v(emb_o[524]),.e_d(emb_o[523:1]),.t_cr(emb_o[0]),
   .t_v(emb_i[524]),.t_d(emb_i[523:1]),.e_cr(emb_i[0]),
   .k_v(kv_o[524]),.k_d(kv_o[523:1]),.kt_cr(kv_o[0]),
   .kt_v(kv_i[524]),.kt_d(kv_i[523:1]),.k_cr(kv_i[0]),
   .fault(fault));
 end else begin: disabled
  assign hub_o=528'b0; assign emb_o=525'b0; assign kv_o=525'b0;
  assign fault=1'b0;
 end endgenerate
endmodule
'''
    (ROOT/'rtl/qwen_sys/emb_hbm_20261008/ot_qfd_link_far_bus.sv').write_text(text)
if __name__=='__main__': generate()
