#!/usr/bin/env python3
"""Additive protection sizing; encoded boundary and elastic-source joins required."""
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def bank(words):return (words+5)*72+2
def model():
 flights=[]
 for name,w,d,n in [('hub',544,35,2),('delivery',545,35,4),('forward',560,7,2),('return',16,7,2)]:
  words=(w+1+63)//64;flights.append(dict(name=name,payload_bits=w,valid_bits=1,depth=d,replicas=n,encoded_frame_bits=words*72,state_bits=n*d*bank(words),nominal_latency_cycles=d,nominal_II=1,stall='All stages freeze when any bank repairs or output blocked; no finite correction latency guarantee under repeated faults',boundary_bits_per_cycle=n*words*72,boundary_bytes_per_cycle=n*words*9))
 paths=['rtl/hbm_accel/ha2_ar/ot_ha2_truecredit.sv','rtl/hbm_accel/ha2_ar/ot_ha2_parent_quiet_prims.sv','rtl/hbm_accel/collective_flight_20261007/ot_hbm_collective_protected_flight.sv','rtl/hbm_accel/integrated_20261005/w2_parent/ot_hbm_w2_protected_bank.sv']
 return dict(schema='opentallas.ha2.mutable_protection.prebuild.v1',default_enabled=False,adopted=False,physical_build_ready=False,source_sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in paths},MACs_per_cycle=0,
 flights=flights,receiver=dict(injectors=2,slots_per_injector=64,payload_and_tag_bits=560,codewords_per_slot=9,encoded_bits_per_slot=648,protected_bank_state_bits_per_slot=bank(9),slot_banks_state_bits=2*64*bank(9),control_state='wp7,rp7,expect_arrival16,expect_retire16 packed46bits; protected72bit word plus5repairwords+2fault rails perinjector',control_state_bits=2*bank(1),output_data_tag_valid_bits=561,output_bank_state_bits=2*bank(9),total_state_bits=2*(64*bank(9)+bank(1)+bank(9)),selected_row_mux2_equivalents=2*648*63,nominal_latency_delta_cycles=0,latency_status='Combinational checked row select and same-edge protected output load candidate; physical feasibility not established',write_bytes_per_cycle=162,read_bytes_per_cycle=162),
 sender=dict(control_bits_per_injector=46,control_fields='reserved7,sent7,next_send16,next_return16; all permission from checked state',output_bits_per_injector=561,total_state_bits=2*(bank(1)+bank(9)),nominal_latency_delta_cycles=0),
 composed=dict(total_candidate_protected_state_bits=sum(f['state_bits'] for f in flights)+2*(64*bank(9)+bank(1)+bank(9))+2*(bank(1)+bank(9)),FF_area_lower_bound_um2=(sum(f['state_bits'] for f in flights)+2*(64*bank(9)+bank(1)+bank(9))+2*(bank(1)+bank(9)))*.2916,area_scope='FF-only floor; excludes parallel syndrome trees, encoding, row mux/control, clock/hold/route. No fit claim.',floorplan_slot=None,routing_tracks_status='Encoded648-bit frame replaces raw544/560 bit boundary; actual track/channel capacity must be bound by physicalowner',fault_free_added_token_cycles_candidate=0,latency_scope='Preserve phase/valid/retirement on fault-free path; correction stalls consume held reservations and must be measured, never modeled free'),
 protocol=dict(reserve='Reserve64 destination slots at actual accepted hub read; issue_v must imply hub protected-flight in_r and valid source ownership',retire='Return credit only on checked receiver row transfer into a reserved protected output; no return on ECC repair or uncorrectable row',CE='Suppress valid/grant/pop/return before action; bank performs protected five-edge repair; all relevant transaction state remains held',UE='Sticky dualrail fault quarantine; never silently erase outstanding reservations',reset='Cold common reset only with all encoded valid paths discarded; warm reset cannot fabricate completion or credits',encoded_chain='Encode at trusted producing register; carry original648/72bit code through transport, queue and held outputs. Decode/re-encode across an unprotected stored or transported boundary is forbidden.',current_reuse_gap='Existing protected_flight raw in/out ports require additive encoded-interface variant for this chain. Do not wire unstallable hub issue directly to elastic in_r, and do not claim current helper alone closes boundary protection.'),
 prerequisites=['Unified model registration before RTL','Specify encoded port ABI and producer/consumer capture ownership with collective owner','Targeted faults on stored payload,valid,tag,pointer,credit counts,repair state and held outputs','Prove no corruption laundering at every encoded handoff','Fullwidth fault-free exact timing plus CE/UE quarantine and reset gates','Physical sizing of syndrome fanout/rowmux/clock and complete parent interface'],outside_scope=['half-rate shell FD8 queues','mutable partial launch8x546','reducer arithmetic/context protection','other16 protected link flight paths owned by collective'])
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--out',type=Path,required=True);a=p.parse_args();a.out.parent.mkdir(parents=True,exist_ok=True)
 with a.out.open('x') as f:json.dump(model(),f,indent=2);f.write('\n')
