#!/usr/bin/env python3
"""Source-bound prebuild obligations; never manufacture an unmeasured parent clock."""
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def model():
 paths=['rtl/hbm_accel/tu/ot_hbm_accel_tu_endpoint_owner_truecredit.sv','rtl/hbm_accel/ha2_ar/ot_ha2_truecredit.sv','rtl/hbm_accel/ha2_ar/ot_ha2_parent_quiet_prims.sv','physical/ha2_truecredit_20261007/model.json']
 return dict(schema='opentallas.ha2.parent_clock_obligation.v1',adopted=False,physical_build_ready=False,
  source_sha256={n:hashlib.sha256((ROOT/n).read_bytes()).hexdigest() for n in paths},
  evidence_commit='2b5a45a9b',clock=dict(period_ps=833.333,setup_uncertainty_ps=60,hold_uncertainty_ps=25,required_margin_ps=15),
  actual_source_join=dict(launch='g_hub[i].u_h circular mem[ptr] selected-slot output (D35), not a fixed final relay',capture='g_truecredit.u_tx.send_data',domain='shared clk, 1.2GHz',physical_launch_coordinates=None,launch_clock_SS_FF_min_max_ps=None,capture_clock_SS_FF_min_max_ps=None,parent_clock_branch=None,qualified=False),
  measured_failed_screen=dict(corner='WC placement parasitics; not final routed SS/FF',virtual_launch_latency_ps=0,input_min_ps=0,input_max_ps=316.666626,data_min_internal_ps=151.546432,capture_clock_data_min_ps=681.895020,hold_cell_ps=26.305510,data_min_required_ps=733.200562,data_min_slack_ps=-581.654114,valid_max_internal_ps=1481.095581-316.666626,valid_max_required_ps=1377.336426,valid_max_slack_ps=-103.759109),
  boundary_obligations=dict(hold='L_launch_early + CQ_min + wire_min + internal_min >= L_capture_late + hold_cell + 25ps + 15ps',setup='L_launch_late + CQ_max + wire_max + internal_max <= 833.333ps + L_capture_early - setup_cell - 60ps - 15ps',failed_screen_data_external_min_needed_ps=733.200562+15-151.546432,failed_screen_valid_external_max_allowed_ps=1377.336426-15-(1481.095581-316.666626),scope='These are obligations from different measured endpoints, not assumed parent timing. A scalar virtual-clock shift cannot repair the high-fanout logic.'),
  structural_candidate=dict(default_off=True,action='Unconditional payload capture; keep send_v/tags/reservation checks unchanged. Replace D35 circular hub delay with D34 circular delay plus D1 local launch register sharing TX clock subtree; prove unchanged delay.',payload_registers_retained=1088,payload_enable_muxes_removed=1088,arrival_valid_payload_enable_loads_removed=1088,registers_added=0,logic_cycles_added=0,forward_payload_bits_per_cycle=1088,forward_payload_bytes_per_cycle=136,MACs_per_cycle=0,replicas=2,queue_slots_per_injector=64,queue_and_credit_protocol_unchanged=True,existing_tx_slot_um=[840.024,40.176],hub_payload_storage_before_bits=2*35*544,hub_payload_storage_after_bits=2*(34+1)*544,hub_valid_storage_before_bits=70,hub_valid_storage_after_bits=70,hub_pointer_before_bits=64,hub_pointer_after_bits='D34 retains two32-bit sourceinteger ptr variables; D1 pointer constant eliminates in synthesis, mapped control must be measured',hub_mux_change='35:1 selected-slot mux becomes34:1 plus local544-bit register per injector; no free physical hop assumed',area_caveat='Source D35 is a circular buffer, not35 spatial relays. Split34+1 is a structural replacement with preserved storage count and changed decode/mux ownership. No timing gain or placement fit is claimed.',token_delta_cycles=0,proof_required='Compare valid payloads/tags and finite-credit retirement with unchanged golden; invalid-cycle output switching is not a protocol transaction.',power_caveat='Unconditional capture may increase switching on invalid cycles; price activity before energy claims.'),
  reroute_prerequisites=['Actual parent launch and capture clock SS/FF early/late envelopes','Real launch clk-to-Q and final wire min/max, including pin placement','Complete shared-subtree source manifest and register inventory','Model-priced control/register placement and signal routing capacity','Exact component gate for unconditional capture; no inherited physical qualification'])
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--out',required=True,type=Path);a=p.parse_args();a.out.parent.mkdir(parents=True,exist_ok=True)
 with a.out.open('x') as f:json.dump(model(),f,indent=2);f.write('\n')
