"""Pre-build sizing of the full PWT545, QAW7, RXAW8 SRAM collective port."""
def model():
    mw,mh,gap,dw,dh=94.824,41.040,24,480,540
    aw,ah=3*mw+2*gap,6*mh+5*gap
    return dict(schema='opentallas.uarch.hcoll_port_interior.v1',
        adopted=False,enabled_default=False,physical_closed=False,headline_rate_credit=0,
        inherited_source_commit='7bebd6b4e42df9fe8ca135e2c624a43519262f28',
        failure='FLOORPLAN_MARGIN: four SRAMs abut N/W pins; occupied 8um macro gap',
        shape=dict(port_replicas_per_endpoint=8,port_width_bits=545,
            SRAMs_per_port=18,SRAM_rows=128,SRAM_word_bits=256,
            transmit_queue_depth=128,receive_queue_depth=256,wire_stages=14),
        compute=dict(MACs_per_cycle=0,FP_ops_per_cycle=0,
            integer_work='Fixed queue arbitration, credits and serializer pacing',
            communication_intensity='Five 545bit input/output buses; no arithmetic data reuse'),
        memory_ports_bytes_per_cycle=dict(per_macro_read=32,per_macro_write=32,
            aggregate_read_capacity=18*32,aggregate_write_capacity=18*32,
            scope='Peak capacity; not all queues and wire-stage banks active simultaneously'),
        boundary_bits_per_cycle=dict(three_input_payloads=3*545,two_output_payloads=2*545,
            control_and_clock_reset=11),
        replica_cost=dict(dynamic_mux='Existing 2:1 partial/result arbiter; unchanged',
            demux='Existing bank/address decode; unchanged',added_fanout=0,
            added_register_bits=0,added_buffers_measured=None),
        routing=dict(macro_cols=3,macro_rows=6,inter_macro_gap_um=gap,
            minimum_edge_corridors_um=[(dw-aw)/2,(dh-ah)/2],
            pin_layers_H=['M4','M6'],pin_layers_V=['M3','M5'],
            left_bits_per_um_per_layer=1092/420/2,
            right_bits_per_um_per_layer=1094/420/2,
            bottom_bits_per_um_per_layer=546/360/2,
            pin_capacity_target_bits_per_um_per_layer=6,
            macro_channel_tracks_per_two_layers=int(gap*2/.08),
            macro_read_write_address_tracks=256+256+7+7+2,
            layers_added=0,pin_density_and_sliver_lint_verified=False),
        area=dict(macro_um2_total=18*mw*mh,die_um=[dw,dh],die_um2=dw*dh,
            baseline_rows_die_um=[340,520],baseline_rows_die_um2=340*520,
            port_die_area_ratio=dw*dh/(340*520),
            eight_port_slot_area_delta_um2=8*(dw*dh-340*520),
            macro_area_fraction=18*mw*mh/(dw*dh),
            inherited_cell_area_um2=None,measured_utilization=None,
            outline_legality='Internal hard port master; endpoint die fit still required'),
        latency=dict(added_cycles_per_port=0,added_cycles_per_token=0,
            scheduling='Identical RTL and clocks; queue capacity and serialization unchanged',
            clock_GHz=1.2,wire_delay_qualified=False),
        power=dict(measured_W=None,energy_J_per_token=None,
            qualification='Changed physical wire/clock lengths must be measured'),
        qualification=dict(SS_setup=False,FF_hold=False,DRC0=False,die_context=False))
