"""Production TA15 composition before integration RTL/physical build."""
def model():
 return dict(default_enabled=False, adopted=True,
  selected_digital_body=dict(source_commit='1f77ae2d0e313d86c7e515f85259978a45efe8e7',
   source='rtl/hbm_accel/control/ot_hbm_production_clock_digital_body_cl.sv',
   collars='rtl/hbm_accel/control/ot_hbm_clock_reset_collars_rs.sv',
   sdc='physical/hbm_accel_die_views/clock_boundary/production_body_cl.sdc',
   decision='CONFIRMED review0443 X5: Claude body_cl closed first; DATA H15 evidence only',
   added_token_cycles=0, reset_release_destination_edges=3, ready_return_AON_edges=2,
   evidence='results/uarch/hbm_ta15_body_cl_adoption_20261009',
   scope='selected isolated digital body; analog PLL and die loaded clock/reset integration remain unqualified'),
  mechanism='AON ordered qualification -> analog PLL output clocks -> destination reset collars -> synchronized released readiness',
  clock_period_ns=dict(stream=5/6,serial=10/9,hbm=1.024,link=5/6),
  digital_body_successor=dict(top='ot_hbm_production_clock_digital_body',
   area_slot_um=[100.224,99.36],AON_pathfinding_period_ns=3,
   boot_mask='Destination intents remain low across raw POR deassertion until actual sequenced PLL/PHY/link/BIST admission.',
   raw_status_obligations='Analog lock and all provider readiness are explicit inputs; no constant qualification. Recovery/removal remains visible; AON3ns is a provisional external-source contract.',
   added_FF_bits=0,added_token_cycles=0),
  AON_ready_successor=dict(top='ot_hbm_production_clock_digital_body_ready_aon',
   mechanism='All actual released resets enter existing2AON synchronizer; ready rises solely from AON sync/state. Raw POR/lock/fatal veto asserts asynchronously without cross-domain collar outputs on ready.',
   added_FF_bits=0,added_token_cycles=0,
   raw_reset_recovery_qualified=False),
  replicas=dict(PHY=4,links=9,reset_collars=17),
  sequential_bits=dict(AON_status=34,AON_state=4,destination_collars=51,AON_ready=2),
  FF_area_floor_um2=91*0.2916,
  readiness_latency='3 destination clock edges after reset intent plus2 AON edges after all actual resets release',
  steady_state_token_latency_cycles=0, MACs_per_cycle=0,memory_bytes_per_cycle=0,
  status_input_bits=19,control_output_bits=23,
  route_tracks='Actual clocks/reset trees and PHY/link status routes require contextual extraction',
  qualification='Composition sizing only; analog macro area and die boundary integration remain unqualified')
