from pathlib import Path
import json,hashlib,math,re,subprocess,collections,shutil
root=Path.cwd();out=root/'results/uarch/hbm_qwen_cxx_r10_20261002';out.mkdir();old=Path('/tmp/hbm-qwen-frontend-calibration-parent-20261002-r9-r1');obj=old/'Qwen/obj';parent=Path('/home/ubuntu/OpenTallas/results/rtl/hbm_qwen_r9_parent_terminal_checkpoint_20261002');checkpoint=out/'parent_checkpoint';checkpoint.mkdir();checkpoint_pins={}
for p in parent.iterdir():
 if p.is_file():
  rel='results/rtl/hbm_qwen_r9_parent_terminal_checkpoint_20261002/'+p.name
  b=subprocess.check_output(['git','show','98af942fa:'+rel]);assert b==p.read_bytes();(checkpoint/p.name).write_bytes(b);checkpoint_pins[p.name]=hashlib.sha256(b).hexdigest()
import sys;sys.path.insert(0,'tools');import hbm_cxx_thin_archive_gate_r7 as A
allinv=[json.loads(x)for x in(root/'results/rtl/hbm_qwen_r9_terminal_owner_20261002_r1/output_inventory.jsonl').read_text().splitlines()];by={x['path']:x for x in allinv};kit=[x for x in allinv if x['path'].startswith('Qwen/obj/')and Path(x['path']).suffix in ('.cpp','.h','.mk','.dat')]
for x in kit:
 assert (old/x['path']).stat().st_size==x['bytes']
kitbytes=sum(x['bytes']for x in kit);want=A.generated_objects(obj);have=[n for n in want if 'Qwen/obj/'+n in by];missing=sorted(set(want)-set(have));family=lambda n:re.sub(r'__\d+(?:__Slow)?$','',Path(n).stem);rat={};globalmax=0;compiledsource=0;sourcebytes=0;measuredobj=0
for n in want:
 s=by['Qwen/obj/'+str(Path(n).with_suffix('.cpp'))]['bytes'];sourcebytes+=s
 if n in set(have):
  o=by['Qwen/obj/'+n]['bytes'];measuredobj+=o;compiledsource+=s;r=o/max(1,s);rat[family(n)]=max(rat.get(family(n),0),r);globalmax=max(globalmax,r)
missingprojection=sum(math.ceil(by['Qwen/obj/'+str(Path(n).with_suffix('.cpp'))]['bytes']*rat.get(family(n),globalmax))for n in missing)
expected=list(sorted(want));(out/'expected_archive_objects.json').write_text(json.dumps(expected,indent=2)+'\n');(out/'missing_at_failure.json').write_text(json.dumps(missing,indent=2)+'\n')
with(out/'frontend_inventory.jsonl').open('x')as f:
 for x in kit:f.write(json.dumps(x,sort_keys=True)+'\n')
v=json.loads((checkpoint/'verdict.json').read_text());p=json.loads((checkpoint/'proposal.json').read_text());g=json.loads((checkpoint/'GO.json').read_text());end=json.loads((checkpoint/'Qwen-frontend-end.json').read_text())
manifest=dict(original_output=str(old),original_source_root='/home/ubuntu/OpenTallas-hbm-qwen-r9',original_source_commit=v['source_commit'],original_GO_commit=v['GO_commit'],original_GO_record_path=g['admission_record_path'],original_proposal_sha256=g['proposal_sha256'],parent_checkpoint_commit='98af942fa',parent_checkpoint_path=str(parent.relative_to('/home/ubuntu/OpenTallas')),parent_checkpoint_pins=checkpoint_pins,frontend_inventory_sha256=hashlib.sha256((out/'frontend_inventory.jsonl').read_bytes()).hexdigest(),frontend_files=len(kit),frontend_bytes=kitbytes,source_sha256=p['source_sha256'],gate_tool_sha256=p['gate_tool_sha256'],verified_toolchain=p['verified_toolchain'],frontend_argv=end['argv'],expected_archive_objects_sha256=hashlib.sha256((out/'expected_archive_objects.json').read_bytes()).hexdigest(),original_frontend_end_sha256=checkpoint_pins['Qwen-frontend-end.json'],original_frontend_source_frame='All original source/tool/proposal/committed GO pins remain mandatory; completed frontend only; no old .o .d .gch archive or binary copied',absolute_path_policy='Generated filenames/diagnostics may retain original source/output paths; make frame uses explicit fresh -C, -B, DEPS=, VM_USER_DIR=, OBJCACHE= and fixed VPATH. Do not invoke baked .dat frontend command. Existing old output retained immutable.')
(out/'frontend_manifest.json').write_text(json.dumps(manifest,indent=2,sort_keys=True)+'\n')
pch=sum(x['bytes']for x in allinv if x['path'].endswith('.gch'));runtime=sum(x['bytes']for x in allinv if x['path'].startswith('Qwen/obj/')and x['path'].endswith('.o')and Path(x['path']).name not in set(want));projected_obj=math.ceil((measuredobj+missingprojection)*1.10)+runtime
# Each thin member must remain a reference; DS measured metadata per member conservatively applied to Q names with explicit margin.
thin=math.ceil(len(want)*max(16384,88174452/11383*2));elf=projected_obj+64*1024**2;logs=256*1024**2
components=dict(generated_frontend=kitbytes,PCH=pch,objects=projected_obj,thin_archive=thin,linked_ELF=elf,logs_receipts_and_dependencies=logs);GiB=1024**3;aggregate=math.ceil(sum(components.values())/GiB)*GiB;fsize=math.ceil(max(elf,thin,max(x['bytes']for x in kit),pch)/GiB)*GiB
wall=v['phases'][1]['wall_s'];countprojection=wall*len(want)/len(have);sourceprojection=wall*sourcebytes/compiledsource;CXXcap=math.ceil(2*max(countprojection,sourceprojection)/60)*60
model=dict(schema='opentallas.H1.Qwen.cold-CXX-r10.resource-model.v1',geometry_unchanged=True,NC=16,SIMD_lanes=128,expected_archive_objects=len(want),observed_expected_objects=len(have),observed_runtime_objects=3,absent_expected_objects=len(missing),observed_expected_object_bytes=measuredobj,observed_PCH_bytes=pch,source_bytes=sourcebytes,source_bytes_with_observed_objects=compiledsource,group_max_ratio_projection_bytes=measuredobj+missingprojection,family_max_observed_object_to_source_ratio=rat,unobserved_family_fallback_ratio=globalmax,projection_margin=1.10,output_components_bytes=components,aggregate_output_bytes=aggregate,per_file_bytes=fsize,ELF_estimate_basis='Sum projected object disk bytes plus64MiB linker metadata; conservative empirical envelope, not measured final binary. Partial allocatable file sections >1GiB warn old FSIZE insufficient; actual link remains mandatory.',thin_estimate_basis='max(16KiB/member,2x DS observed88174452/11383 metadata/member) times actual35684 expected members',projection_limit='Per-family observed ratios with10% margin are empirical; unseen compiler complexity/linker sizes may exceed caps. Preserve failure; no geometry or flags changed.',measured_partial_CXX_wall_s=wall,count_weighted_completion_projection_s=countprojection,source_weighted_completion_projection_s=sourceprojection,CXX_limit_s=CXXcap,CXX_budget_basis='2x max(count-weighted,source-weighted) measured partial wall projection, rounded60s; cost per TU/critical path not individually measured; no completion guarantee',caps=dict(cpus=list(range(8,24)),build_jobs=16,memory_bytes=96*GiB,swap_bytes=0,per_file_bytes=fsize,aggregate_output_bytes=aggregate,disk_headroom_bytes=aggregate+12*GiB,whole_wall_s=300+CXXcap+30,kill_grace_s=5,poll_s=1,sequential_targets=True),memory_policy='Retain admitted96GiB for bounded calibration; measured prior CXX peak <=service71.48GiB and cold frontend copy/pagecache accounted. Fresh fleet admission required.',phase_limits_s=dict(reuse_frontend=300,CXX=CXXcap),frontend_repeated=False,partial_objects_reused=False,fulltoken_credit=False,physical_credit=False)
(out/'model.json').write_text(json.dumps(model,indent=2,sort_keys=True)+'\n');print(json.dumps({k:model[k]for k in ['expected_archive_objects','observed_expected_objects','output_components_bytes','aggregate_output_bytes','per_file_bytes','CXX_limit_s','caps']},indent=2))
