"""Additive source plan preparation only; existing records cannot be overwritten."""
import sys,json,pathlib,hashlib,copy
sys.path.insert(0,'tools');import prepare_observer_explicit_widths as w
root=pathlib.Path.cwd();out=root/w.OUT;out.mkdir(exist_ok=False)
def write(n,j):(out/n).write_text(json.dumps(j,indent=2)+'\n')
priorbytes=(root/w.PRIOR).read_bytes();prior=json.loads(priorbytes)
write('source_field_authority.json',w.source_field_authority(root,prior))
write('inverse_and_bit_mapping.json',w.validate_inverse_to_real(root))
write('classification.json',dict(source_commit=prior['source_commit'],failure_commit='8ee4069ba40f4c9feaddeb3771a810a84ba3f1ea',failure_receipt_path='results/rtl/observer_resource_lint_execution_d1b55a45_20261002/receipt.json',failure_receipt_sha256=w.digest((root/'results/rtl/observer_resource_lint_execution_d1b55a45_20261002/receipt.json').read_bytes()),scope='Simulation-only added wrappers; original RTL and failed copies untouched',changes=[dict(site='L0 copy111/original107',before=".att_packed_kv_w('0)",after=".att_packed_kv_w(16960'd0)",semantics='Context-sized unbased unsized zero fills every port bit; explicit unsigned sized zero identical at FULL_SHAPE1.',warning='WIDTHCONCAT replication16960',unverified='New literal may still trigger tool warnings; fresh actual lint required.'),dict(site='L0 copy141/original137',before='31bit unsigned dbg_faults concat',after='32bit concat: leading11zeros ->12zeros',semantics='Original assignment adds one zero at bit31. Data field offsets unchanged.',warning='WIDTHEXPAND31to32'),dict(site='L0 copy151/original147',before='60bit unsigned dbg_state concat',after='64bit concat with4leadingzeros',semantics='Original assignment adds four zeros at bits63:60. Sticky faults stay bits59:28, other fields retain exact offsets.',warning='WIDTHEXPAND60to64')],proof='symbolic per-bit identity includes 0/1/X/Z; no signed extension introduced',CKV='Same three original expressions and source-bound widths in actual L20; prepare explicit-width L20 copy for future real full-hierarchy baseline/path/parameter mutants.',default_observation=0,causal_deadlines='BOUND_MISSING',no_warning_waiver=True,no_compile=True))
p=copy.deepcopy(prior);p.update(base_commit='8ee4069ba40f4c9feaddeb3771a810a84ba3f1ea',unchanged_plan_path=w.PRIOR,unchanged_plan_sha256=w.digest(priorbytes),modes=w.expected_modes(root,prior),runner='tools/run_observer_explicit_width_lint.py',qualification='EXPLICIT_WIDTH_IDENTITIES_ONLY_AWAIT_FRESH_GO_NO_LINT_PASS',width_derivative=dict(tool='tools/prepare_observer_explicit_widths.py',record=w.OUT+'/classification.json',exact_protected_copy_and_original_inverse=True,warning_policy_unchanged=True,resource_caps_unchanged=True,observation_bit_mapping_unchanged=True))
for f in ['tools/prepare_observer_explicit_widths.py','tools/run_observer_explicit_width_lint.py','tools/plan_observer_explicit_width_gate.py']:p['preparation_tools'][f]=w.digest((root/f).read_bytes())
write('resource_delta.json',dict(source_commit=prior['source_commit'],actual_baseline_commit='8ee4069ba40f4c9feaddeb3771a810a84ba3f1ea',actual_WINDOW_peak_rss_kib=33432832,actual_WINDOW_wall_seconds=303.445,changes='Three explicit zero-width spellings plus new top namespace only; no unrolled count/parent/parameter/observation state change.',source_bytes_delta=[m['source_bytes']-old['source_bytes'] for m,old in zip(p['modes'],prior['modes'])],caps=p['caps'],model='Retain reviewed64GiB AS/600s baseline, twoCPU/serial,30s mutants,16MiB logs and existing reserve/readmission. No measured new variant or CKV sufficiency.',causal_deadlines='BOUND_MISSING',full_model_build=False,no_compile=True))
p['resource_evidence_sha256'].update({str(f.relative_to(root)):w.digest(f.read_bytes()) for f in out.iterdir() if f.name in ['classification.json','source_field_authority.json','inverse_and_bit_mapping.json','resource_delta.json']})
write('plan.json',p)
g=json.loads((root/'results/rtl/observer_frontend_resource_model_4e383_20261002/GO.template.json').read_bytes());g.update(plan_sha256=w.digest((out/'plan.json').read_bytes()),explicit_width_mapping_reviewed=False)
write('GO.template.json',g)
for m in p['modes']:(out/(m['name']+'.f')).write_text('\n'.join(a for a in m['argv'] if a.endswith(('.sv','.v')))+'\n')
