#!/usr/bin/env python3
"""Read-only source/data/inventory preparation; no download, build or token execution."""
import json,os,sys,subprocess
from pathlib import Path
from qwen_trained_byte_provider import ROOT,ARTIFACT,native,refs,immutable_refs,extents,sha,canonical
PINS=['tools/qwen_trained_page_continuation.py','tools/qwen_trained_byte_provider.py','tools/qwen_trained_native_run.py','tools/prepare_qwen_trained_native.py','tools/model_qwen_trained_byte_provider.py','tests/test_qwen_trained_byte_provider.py','tools/h3_qwen_complete_native.py','tools/qwen_hbm_complete_executor.py','tools/qwen_hbm_complete_reference.py','tools/qwen3_deployment_quality.py','compiler/models/qwen3-8b/checkpoint_source.json',ARTIFACT]
OUT=ROOT/'results/uarch/qwen_trained_byte_provider_20261002'
def prepare():
 n=native();lock=json.loads((ROOT/'compiler/models/qwen3-8b/checkpoint_source.json').read_text());snapshot=Path('/home/ubuntu/.cache/huggingface/hub/models--Qwen--Qwen3-8B/snapshots')/lock['revision'];needed=[x for x in lock['expected_files']if x['path'].endswith('.safetensors')or x['path']in ('config.json','model.safetensors.index.json')];missing=[x['path']for x in needed if not(snapshot/x['path']).is_file()];ex=extents(n);selected=immutable_refs(n)
 from qwen_trained_byte_provider import matrix_inventory
 matrix_inventory(n)
 return dict(schema='opentallas.Qwen.trained-native.prepared.v1',base_source_commit='41eef76fa',model_commit='18ff7ccc5',execution_root=str(ROOT),source_sha256={f:sha(ROOT/f)for f in PINS},native_artifact_sha256=sha(ROOT/ARTIFACT),provider_binding_pin=n['provider_binding_pin'],checkpoint_revision=lock['revision'],checkpoint_snapshot=str(snapshot),required_checkpoint_files=needed,missing_checkpoint_files=missing,readiness='BLOCKED_CHECKPOINT_DATA_AND_FRESH_FLEET_ADMISSION'if missing else 'PREPARED_REQUIRES_RELOCATED_BOUNDED_MODULE_AND_FRESH_FLEET_ADMISSION',source_coverage=dict(PCs=1737,classes=21,matrix_descriptors=290,external_refs=len(refs(n)),immutable_image_refs=len(selected),mutable_native_refs=len(refs(n)-selected),all_refs_bound=not refs(n)-ex.keys()),inventory=dict(images_bytes=sum(ex[r]['bytes']for r in selected),checkpoint_transfer_bytes=sum(x['size_bytes']for x in needed),small_output_capture_bytes=36*4096*4+4096*4+151936*4,producer_page_rows=128,quantizer_repetition='Both column-sharded ranks quantize source full rows identically; CPUcost explicit, no shard-local quantization'),policy=dict(wall_limit=None,FSIZE='unlimited',RLIMIT_AS='unlimited',aggregate='fresh inventory plus actual receipt footprint and fleet disk reserve',memory='fresh measured fleet reservation; includes shard pagecache, producer Torch scratch and native word backing; no pilot cap',local_D1_reserved_GiB=96,PVE2_PVE3_launch=False),commands=dict(produce=['/usr/bin/python3','tools/qwen_trained_byte_provider.py','--snapshot',str(snapshot),'--out','<immutable-image-root>','--admission','<exact-parent-GO.json>','--go-commit','<parent-GO-commit>'],execute=['/usr/bin/python3','tools/qwen_trained_native_run.py','--images','<immutable-image-root>','--out','<fresh-runtime-output>','--admission','<exact-parent-GO.json>','--go-commit','<parent-GO-commit>','--bounded-module','<Popper-relocated-bounded-module.py>','--token','9707']),scope=dict(layers=36,TP=2,tokens=1,full_config=True,fixture_weights=False,postexecution_reference_only=True,no_oracle_values_into_DUT=True,actual_RTL=False,physical_credit=False,rate_credit=False),bounded_module_join=dict(status='WAITING_POPPER_ADDITIVE_RELOCATION',original_file_import_refused=True,required='new relative module path+commit+SHA in actual admission source_sha256; byte/provider ABI tests rerun against relocated module'),calendar_handoff=dict(provider_data='r17 provider_ref/base/codec and <=128 byte ranges, <=4096B payload, one serialized reader with validated copy/ACK then release',additional_costs='checkpoint conversion is offline; runtime addressed transport and verification observer reads counted separately; all physical costs remain unqualified',Popper_source_untouched=True),fresh_GO_fields=['schema','admitted','source_commit','source_sha256','unit','admission_record_path','cpus','memory_bytes','fresh_host_headroom_bytes','aggregate_output_bytes','disk_headroom_bytes','wall_limit_s','FSIZE','RLIMIT_AS'])
if __name__=='__main__':
 if sys.argv[1:]!=['--review-only']:raise SystemExit('review-only preparation required')
 OUT.mkdir(exist_ok=True,parents=True);p=OUT/'prepared.json';p.write_bytes(canonical(prepare()));print(p)
