import pathlib,subprocess,json,hashlib,argparse
ap=argparse.ArgumentParser();ap.add_argument('--source-root',type=pathlib.Path,default=pathlib.Path(__file__).resolve().parents[1]);ap.add_argument('--out',type=pathlib.Path,required=True);args=ap.parse_args();r=args.source_root;out=args.out;out.mkdir(parents=True,exist_ok=False)
src=[r/f for f in ['rtl/physical/ot_qwen_die_cdc_ch.sv', 'rtl/physical/ot_qwen_die_link_fwd_full_tmr.sv', 'rtl/lib/ot_async_fifo.sv', 'rtl/lib/ot_reset_sync.sv', 'rtl/physical/ot_qwen_ctrl_pc_protected.sv', 'rtl/physical/ot_qwen_ctrl_pc_shift.sv', 'rtl/physical/ot_hbm_r14_stream_pc_shift.sv', 'rtl/physical/ot_qwen_kvc_hub_cdc.sv', 'rtl/physical/ot_qwen_kvc_write_link_bridge_cancel.sv', 'rtl/physical/ot_qwen_kvc_packet_codec_parallel.sv', 'rtl/physical/ot_qwen_die_hub_identity.sv', 'rtl/physical/ot_qwen_ctrl_write_cancel.sv', 'rtl/physical/ot_qwen_ctrl_write_cancel_service_pc.sv', 'rtl/test/tb_qwen_kvc_ctrl_cancel_bridge.sv']]
rows=[]
for hops,neg,inflight,fence in [(54,0,0,0),(55,0,0,0),(54,1,0,0),(54,0,1,0),(54,0,1,1)]:
 name=f'h{hops}_n{neg}_i{inflight}_f{fence}'
 c=subprocess.run(['iverilog','-g2012','-s','tb_qwen_kvc_ctrl_cancel_bridge',f'-Ptb_qwen_kvc_ctrl_cancel_bridge.HOPS={hops}',f'-Ptb_qwen_kvc_ctrl_cancel_bridge.NEG={neg}',f'-Ptb_qwen_kvc_ctrl_cancel_bridge.INFLIGHT={inflight}',f'-Ptb_qwen_kvc_ctrl_cancel_bridge.FENCE={fence}','-o',str(out/'sim')]+list(map(str,src)),capture_output=True,text=True);(out/(name+'.compile.log')).write_text(c.stdout+c.stderr);assert c.returncode==0,c.stderr
 t=subprocess.run(['vvp',str(out/'sim')],capture_output=True,text=True);(out/(name+'.log')).write_text(t.stdout+t.stderr);print(name,t.returncode,t.stdout,flush=True);assert bool(t.returncode)==bool(neg)
 rows.append(dict(hops=hops,negative=bool(neg),inflight=inflight,unsafe_fence=fence,returncode=t.returncode,log=name+'.log'))
(out/'hub_receipt.json').write_text(json.dumps(dict(pass_all=True,tests=rows,source_sha256={str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in src},scope='Actual identity hubs54/55forwarded stages,bridge,native protected150 controller+ledger. Completion exactly17ticks afteractual WR.16writesdone+4acceptedunissuedtypedcanceledowned. Typed canceled ownership remains live until qualified global fence. No falsefence/restart orrefreshowner claim.',negative='PHY emulator sends completion one tick early; receiving-edge timing assertion must reject'),indent=2)+'\n')
