"""In-band SECDED sidecar fallback; physical API qualification is not native JEDEC closure."""
def model():
    return dict(schema='opentallas.qwen.protected_phy.v1', default_enabled=False,
        adopted=False, MACs_per_cycle=0, domain_period_ps=1024,
        replicas_per_stack=32, stacks_per_die=4,
        physical_sector_bytes=32, protected_sector_bits=288,
        logical_payload_bits=256, check_bits=32, sidecar_checks_per_sector=8,
        embedding_data_rows=[24427,24575], embedding_sidecar_rows=[24576,24594],
        embedding_sidecar_reserved_bytes=19*32*1024*128,
        embedding_sidecar_logical_bytes=19457304*4,
        kv_data_layer_rows=[0,35], kv_sidecar_rows=[64,99],
        kv_sidecar_sectors_per_layer_per_PC=128,
        kv_sidecar_reserved_bytes=36*128*32*128,
        address_aperture_qualified=False,
        read_physical_transactions=2, read_physical_bytes=64,
        write_physical_transactions=5, write_physical_bytes=160,
        write_sequence=['sidecar RD','data WR','sidecar RMW WR','same-sector data RD fence','same-sector sidecar RD fence'],
        write_done='both tagged readback fences match; never request acceptance',
        active_logical_requests_per_PC=1, physical_outstanding_reads_per_PC=1,
        write_RMW_exclusion='all clients sharing a PC sidecar word must use this sole provider; external bypass invalidates qualification',
        mutable_register_payload_bits=288+256+256+19+5+5+17+8+64+31+31+16+1+1+4,
        register_area_proxy_um2=(288+256+256+19+5+5+17+8+64+31+31+16+1+1+4)*.32,
        area_basis='flop proxy only; parity, mux, control, CTS and routing additional; no slot/P&R qualification',
        boundaries=dict(logical_request_bits=1+1+1+19+5+5+17+8+64+19+5+5+288,
            logical_return_bits=1+1+1+17+8+64+19+5+5+288,
            physical_request_bits=1+1+31+5+16+256,physical_return_bits=1+5+16+4+256),
        communication_intensity='read64 physical bytes /32 logical bytes; write160/32',
        mux_fanout='one selected PC return from32; no payload broadcast;32 per-PC request sources require admitted physical arbiter',
        routing_tracks_needed='sum listed boundary bits at actual placement; no floorplan slot claimed',
        latency='read two serialized matched physical reads + request/output edges; write five serialized transactions with actual request-ready and fence latency; component gate measures cycles, no token speed credit',
        native_JEDEC_binding=False, physical_qualified=False,
        obligations=['allocator excludes both sidecar regions','native controller schedules extra ACT/PRE/RD/WR and protected metadata','all writers serialized here','actual tag/cohort source ownership','SS/FF in context and real PHY integration'])
