#!/usr/bin/env python3
"""Full released Qwen DSpark native missing-element sizing before RTL."""
def model():
    H,V,K,L,TP=4096,151936,256,5,4
    dense_layer=2*H*H+2*H*1024+3*H*12288
    payload=H*(5*H)+L*dense_layer+2*V*K
    return {'schema':'opentallas.qwen.dspark.native.v1','released_drafter_revision':'03326e5043815da1f81b109078b2889737c26017','geometry':{'hidden':H,'layers':L,'heads':32,'kv_heads':8,'head_dim':128,'ffn':12288,'vocab':V,'markov_rank':K,'TP':TP,'block_positions':7,'S3_independent_program_adopted':False},'weights':{'INT8_matrix_payload_bytes':payload,'FC_bytes':H*(5*H),'five_layer_bytes':L*dense_layer,'Markov_W1_W2_bytes':2*V*K,'scales_and_constants':'must inventory released BF16scales separately; targetsharedembed/head countedonce','field_installation':'missing; historical field_offset20016 is placementproposal only'},'argmax':{'macs_per_cycle':0,'FP32_compares_per_cycle':64,'compute_intensity':'64comparisons/256bytes','memory_read_bytes_cycle':256,'boundary_bits_cycle':{'input_logits':2048,'input_metadata':64+18+2+1+1,'output':18+32+64+1},'rows_per_rank':37984,'beats':594,'final_lane_mask':(1<<32)-1,'replicas':4,'mux_demux_fanout':{'firstlevel_pairs':32,'tree_total_comparators':63,'runningwinner':1,'registered_tree_levels':6,'metadatafanout':32},'outline_um':[1000,1000],'slot_area_mm2_per_rank':1,'logic_estimate':'<8000registerbits,<65000twoinputgateequivalents; actualcells/area pendingroute','routing':{'track_pitch_um':0.064,'escape_layers':2,'tracks_face':31250,'required_input_tracks':2134,'capacity_sufficient_necessary_only':True},'latency':{'domain_GHz':0.9,'accepted_stream_cycles':594,'pipeline_tail_cycles':7,'unoverlapped_cycles':601,'critical_token_cost':'S7*601=4207serialcycles=4674.444ns if separatepass; nativeSUoutputtap canoverlapMKVpass onlyafter measuredproducerbinding','hypothetical_overlap_credit':0},'comparison_contract':'FP32realorder,-0equals+0,lowestglobalIDties; nonfinitefailclosed','physical':'TTsetup>=0 FFhold>=0 DRC0 SSsensitivity at actualproducerdomain; no physicalclaim'},'open':['releasedS7 BF16exactdeploymentgolden','W1macroreadlookup','productionFCfeatureexports/hiddennorm/contextingest','actualfive-layerfieldbanks/scales','MarkovlogitsnativeSUtap','crossdieexactargmaxgather','nativecohortidentityacceptcommit/drainrollback'],'adopted':False}
if __name__=='__main__':
    import json
    print(json.dumps(model(),indent=2))
