// Selected full-parent source closure; root-relative paths. Bacon alone owns formatter body.
+incdir+rtl/test
rtl/gpu/w6/ot_gpu_w6_secded_pkg.sv
physical/hbm_die_abstracts_20261006/memory_control/ot_hbm_integrated_formatter_provider.sv
rtl/hbm_accel/index/ot_hbm_accel_index_w15_planemajor_formatter.sv
rtl/chip/ot_w15_coll_dma.sv
rtl/hbm_accel/integrated_20261005/ot_hbm_integrated_w2_sector_adapter.sv
rtl/hbm_accel/su/ot_hbm_accel_su_parent_exec.sv
rtl/gpu_sys/ot_gpu_bd_line.sv
rtl/gpu_sys/ot_gpu_cdc_fifo.sv
rtl/gpu_sys/ot_gpu_cmdproc.sv
rtl/gpu_sys/ot_gpu_coll_endpoint.sv
rtl/gpu_sys/ot_gpu_coll_fabric.sv
rtl/gpu_sys/ot_gpu_coll_mux.sv
rtl/gpu_sys/ot_gpu_hbm_partition.sv
rtl/gpu_sys/ot_gpu_hbm_system.sv
rtl/gpu_sys/ot_gpu_host_bridge.sv
rtl/gpu_sys/ot_gpu_l2_slice.sv
rtl/gpu_sys/ot_gpu_memsys.sv
rtl/gpu_sys/ot_gpu_mreq_cdc.sv
rtl/gpu_sys/ot_gpu_reset_ctrl.sv
rtl/gpu_sys/ot_gpu_simt_divlane.sv
rtl/gpu_sys/ot_gpu_simt_lane.sv
rtl/gpu_sys/ot_gpu_simt_sm.sv
rtl/gpu_sys/ot_gpu_sys_glue.sv
rtl/gpu_sys/ot_gpu_xbar.sv
rtl/gpu/ot_gpu_sm.sv
rtl/gpu/ot_gpu_bulk_copy.sv
rtl/gpu/ot_gpu_fadd.sv
rtl/gpu/ot_gpu_barrier_node.sv
rtl/hdc/ot_hdc_fp32_add_lat.sv
rtl/hdc/ot_hdc_fp32_mul_lat.sv
rtl/hdc/ot_hdc_fastfp.sv
rtl/gpu/ot_gpu_tree.sv
rtl/gpu/ot_gpu_issue.sv
rtl/gpu/ot_gpu_stack.sv
rtl/gpu/ot_gpu_tc_col.sv
rtl/hdc/ot_hdc_fpu.sv
rtl/hdc/ot_hdc_fp32_mul_pipe.sv
rtl/proto/ot_fp32_add_rne_pipe.sv
rtl/hdc/ot_hdc_sfu.sv
rtl/hdc/ot_hdc_delay.sv
rtl/hdc/ot_hdc_prefix.sv
rtl/abi3/ot_a3_fp32_div_rne_pipe.sv
rtl/abi3/ot_a3_fp32_sqrt_rne.sv
rtl/gpu/ot_gpu_sm_bd.sv
rtl/gpu/ot_gpu_bd_col.sv
rtl/hdc/v41/ot_hdc_blockdot.sv
rtl/v41rom/ot_v41_bterm.sv
rtl/v41rom/ot_v41_bterm2.sv
rtl/link/ot_link_afifo.sv
rtl/link/ot_link_nvls_switch.sv
rtl/hdc/kv/ot_hdc_hbm_model.sv
rtl/host/ot_host_if.sv
rtl/experimental/w2_nc6_completion_20261003/ot_hdc_qwen_pc_exact_completion.sv
rtl/gpu_sys/ds_hbm_full20/ot_ds_hbm_cmdproc20.sv
rtl/gpu_sys/ds_hbm_full20/ot_ds_hbm_simt_sm20.sv
rtl/gpu_sys/ds_hbm_full20/ot_ds_hbm_cluster20.sv
rtl/hbm_accel/integrated_20261005/ot_ds_hbm_cluster20_integrated.sv
rtl/hbm_accel/integrated_20261005/ot_hbm_integrated_cp_reset.sv
rtl/hbm_accel/integrated_20261005/ot_hbm_integrated_prior_debt.sv
rtl/hbm_accel/integrated_20261005/ot_hbm_integrated_sm0_borrow.sv
rtl/hbm_accel/integrated_20261005/ot_hbm_integrated_gather_bridge.sv
rtl/hbm_accel/integrated_20261005/ot_hbm_integrated_gather_owner.sv
rtl/hbm_accel/integrated_20261005/ot_hbm_integrated_su_cp_bind.sv
rtl/hbm_accel/integrated_20261005/ot_hbm_integrated_su_cp_association.sv
rtl/hbm_accel/integrated_20261005/ot_hbm_integrated_header_decode.sv
rtl/hbm_accel/integrated_20261005/ot_hbm_integrated_w15_store.sv
rtl/hbm_accel/integrated_20261005/ot_hbm_integrated_w2_result_sink.sv
rtl/hbm_accel/integrated_20261006/ot_hbm_integrated_su_provider_adapter.sv
rtl/hdc/v41x/ot_hdc_v41x_sfu.sv
rtl/hdc/v41x/ot_hdc_v41x_vec_lane.sv
rtl/hdc/v41x/ot_hdc_v41x_vec_side.sv
rtl/hdc/v41x/ot_hdc_v41x_vec_red.sv
rtl/hdc/v41x/ot_hdc_v41x_vec.sv
rtl/hdc/ot_hdc_cg.sv
rtl/hdc/ot_hdc_fastfp_lat.sv
rtl/hdc/ot_hdc_fastfp_lat_f12.sv
rtl/hdc/ot_hdc_fp32_f12.sv
rtl/hdc/v41/ot_hdc_fsqrt.sv
rtl/hdc/v41/ot_hdc_fdiv.sv
rtl/hdc/v41/ot_hdc_softplus.sv
rtl/hdc/v41/ot_hdc_actquant.sv
rtl/hdc/v41x/ot_dsrom_su_norm.sv
rtl/hdc/v41x/ot_dsrom_su_hcpost.sv
rtl/hdc/v41x/ot_dsrom_su_swiglu.sv
rtl/hbm_accel/su/ot_hbm_accel_su_fused_stream.sv
rtl/hbm_accel/su/ot_hbm_accel_su_fused_vm.sv
rtl/chip/ot_chip_v41x_coll_transpose.sv
rtl/chip/ot_coll_topk_merge.sv
