`timescale 1ps/1fs
// Additive integrated-stage fixture, not a token or physical closure claim.
module tb_hbm_integrated_minimum_parent #(
 parameter integer COMBINED_ENABLE=1,SFU_C12_ENABLE=1,SFU_NATIVE_VM_ENABLE=1,NORM_C12_ENABLE=1,NORM_NATIVE_VM_ENABLE=1,NORM_NATIVE_INPUT_CP=1,SU_ENABLE=1,SU_REGISTERED_OUTPUTS=1,SU_REGISTERED_STATUS=1,SU_REGISTERED_BOUNDARY=1,SU_BALANCED_OWNER_BOUNDARY=1,SU_FOUR_COMBINATIONAL_CUTS=1,SU_FAST_OWNER_FRONTIER=1,SU_PARALLEL_PHASE_VALIDATION=0,SU_PROVIDER_ADAPTER=1,W2_RESULT_ENABLE=1,W2_SECTOR_ENABLE=1,FORMATTER_ENABLE=1,NORMAL_GATHER_ENABLE=1,LOCAL_CP_RESET_ENABLE=1,VM_AW=21,
 parameter integer NORM_KIND=0,NORM_N=64,NORM_D=5120,NORM_RD=0,NORM_AW=24,NORM_PUBLISH_QUANT=1,
 parameter integer ENABLE=1, TW=17, PW=20, CONTEXT_POSITIONS=1048576, ND=2, NSM=2, NL=128, IMW=14,
 parameter integer CB=8, NS=2, NPC=2, MEM_WORDS=2097152,
 parameter integer SW_PIPE=8, USE_W2=0, HAS_DIV=1, HAS_BD=1,
 parameter integer W2_PROTECTED_TRANSACTION_PIPELINE=0
)(
 input wire por_n, clk_host, clk_sm, clk_mem, clk_link,
 // Local reset is deferred; it never resets shared credit or the provider.
 input wire [ND-1:0] cp_reset_req,output wire [ND-1:0] cp_reset_ack,
 input wire [ND-1:0] cmd_we,
 input wire [ND*CB-1:0] cmd_addr,
 input wire [ND*64-1:0] cmd_wdata,
 input wire [ND-1:0] db_v, output wire [ND-1:0] db_rdy,
 input wire [ND*TW-1:0] db_token,
 input wire [ND*PW-1:0] db_pos,
 input wire [ND*32-1:0] db_job,
 input wire [ND*4-1:0] db_generation,
 output wire [ND-1:0] cpl_v, input wire [ND-1:0] cpl_rdy,
 output wire [ND*(TW+PW+72)-1:0] cpl_data,
 input wire [ND*NSM-1:0] im_we,
 input wire [IMW-1:0] im_addr, input wire [63:0] im_data,
 // Actual finite SFU operation caller. Full73 must match the held CP context;
 // accepted exclusive allocation is explicit, never inferred from an address.
 input wire [ND-1:0] sfu_enroll_v,sfu_allocation_valid,sfu_publication_r,
 input wire [ND*73-1:0] sfu_enroll_frame,sfu_allocation_frame,sfu_publication_owner,
 input wire [ND*32-1:0] sfu_pc,sfu_op,sfu_source_addr,sfu_dest_addr,
 input wire [ND*32-1:0] sfu_source_base,sfu_source_limit,sfu_dest_base,sfu_dest_limit,sfu_local_tag,
 input wire [ND*16-1:0] sfu_source,
 input wire [ND*9-1:0] sfu_expert,sfu_count,input wire [ND-1:0] sfu_matrix,
 input wire [ND*12-1:0] sfu_row,input wire [ND*3-1:0] sfu_fn,
 output wire [ND-1:0] sfu_enroll_r,sfu_publication_v,sfu_retained,sfu_fault,sfu_warm_ack,
 output wire [ND*73-1:0] sfu_held_frame,
 // Native VM root caller ABI, one existing 32-SRAM root per die.
 input wire [ND*1-1:0] sfu_vm_bind_v,
 output wire [ND*1-1:0] sfu_vm_bind_r,
 input wire [ND*73-1:0] sfu_vm_bind_frame,
 input wire [ND*7-1:0] sfu_vm_bind_rank,
 input wire [ND*32-1:0] sfu_vm_bind_base,
 input wire [ND*32-1:0] sfu_vm_bind_span,
 input wire [ND*1-1:0] sfu_vm_retire_v,
 output wire [ND*1-1:0] sfu_vm_retire_r,
 input wire [ND*73-1:0] sfu_vm_retire_frame,
 output wire [ND*73-1:0] sfu_vm_held_frame,
 output wire [ND*1-1:0] sfu_vm_retained,
 output wire [ND*1-1:0] sfu_vm_warm_ack,
 output wire [ND*1-1:0] sfu_vm_fault,
 input wire [ND*1-1:0] sfu_vm_activation_wr_v,
 output wire [ND*1-1:0] sfu_vm_activation_wr_r,
 input wire [ND*73-1:0] sfu_vm_activation_wr_frame,
 input wire [ND*1-1:0] sfu_vm_activation_wr_bank,
 input wire [ND*7-1:0] sfu_vm_activation_wr_addr,
 input wire [ND*2063-1:0] sfu_vm_activation_wr_data,
 input wire [ND*192-1:0] sfu_vm_activation_wr_owner,
 output wire [ND*1-1:0] sfu_vm_activation_ACK_v,
 input wire [ND*1-1:0] sfu_vm_activation_ACK_r,
 output wire [ND*73-1:0] sfu_vm_activation_ACK_frame,
 output wire [ND*192-1:0] sfu_vm_activation_ACK_owner,
 input wire [ND*1-1:0] sfu_vm_activation_rd_v,
 output wire [ND*1-1:0] sfu_vm_activation_rd_r,
 input wire [ND*73-1:0] sfu_vm_activation_rd_frame,
 input wire [ND*1-1:0] sfu_vm_activation_rd_bank,
 input wire [ND*7-1:0] sfu_vm_activation_rd_addr,
 input wire [ND*192-1:0] sfu_vm_activation_rd_owner,
 output wire [ND*4-1:0] sfu_vm_tap_v,
 input wire [ND*4-1:0] sfu_vm_tap_r,
 output wire [ND*8252-1:0] sfu_vm_tap_data,
 output wire [ND*768-1:0] sfu_vm_tap_owner,
 output wire [ND*292-1:0] sfu_vm_tap_frame,
 output wire [ND*4-1:0] sfu_vm_tap_source_clk,
 input wire [ND*4-1:0] sfu_vm_tap_ACK_v,
 output wire [ND*4-1:0] sfu_vm_tap_ACK_r,
 input wire [ND*768-1:0] sfu_vm_tap_ACK_owner,
 input wire [ND*292-1:0] sfu_vm_tap_ACK_frame,
 output wire [ND*1-1:0] sfu_vm_activation_release,
 input wire [ND*1-1:0] sfu_vm_activation_release_r,
 output wire [ND*73-1:0] sfu_vm_activation_release_frame,
 output wire [ND*192-1:0] sfu_vm_activation_release_owner,
 input wire [ND*1-1:0] sfu_vm_su_pub_v,
 output wire [ND*1-1:0] sfu_vm_su_pub_r,
 input wire [ND*73-1:0] sfu_vm_su_pub_frame,
 input wire [ND*32-1:0] sfu_vm_su_pub_addr,
 input wire [ND*1024-1:0] sfu_vm_su_pub_data,
 output wire [ND*1-1:0] sfu_vm_su_ACK_v,
 input wire [ND*1-1:0] sfu_vm_su_ACK_r,
 output wire [ND*32-1:0] sfu_vm_publication_ACK_addr,
 output wire [ND*73-1:0] sfu_vm_publication_ACK_frame,
 input wire [ND*1-1:0] sfu_vm_index_read_v,
 output wire [ND*1-1:0] sfu_vm_index_read_r,
 input wire [ND*73-1:0] sfu_vm_index_read_frame,
 input wire [ND*7-1:0] sfu_vm_index_read_rank,
 input wire [ND*32-1:0] sfu_vm_index_read_addr,
 input wire [ND*6-1:0] sfu_vm_index_read_words,
 input wire [ND*8-1:0] sfu_vm_index_read_tag,
 output wire [ND*1-1:0] sfu_vm_index_rsp_v,
 input wire [ND*1-1:0] sfu_vm_index_rsp_r,
 output wire [ND*1024-1:0] sfu_vm_index_rsp_data,
 output wire [ND*8-1:0] sfu_vm_index_rsp_tag,
 output wire [ND*73-1:0] sfu_vm_index_rsp_frame,
 output wire [ND*7-1:0] sfu_vm_index_rsp_rank,
 // Actual selected norm endpoint; real clock-held vectorVM supplier ABI.
 output wire [ND*(1)-1:0] norm_warm_ack,
 input wire [ND*(1)-1:0] norm_enroll_v,
 output wire [ND*(1)-1:0] norm_enroll_r,
 input wire [ND*(72+1)-1:0] norm_enroll_frame,
 input wire [ND*(31+1)-1:0] norm_enroll_pc,
 input wire [ND*(31+1)-1:0] norm_enroll_op,
 input wire [ND*(15+1)-1:0] norm_enroll_source,
 input wire [ND*(8+1)-1:0] norm_enroll_expert,
 input wire [ND*(1)-1:0] norm_enroll_matrix,
 input wire [ND*(11+1)-1:0] norm_enroll_row,
 input wire [ND*(8+1)-1:0] norm_enroll_count,
 input wire [ND*(1)-1:0] norm_allocation_valid,
 input wire [ND*(72+1)-1:0] norm_allocation_frame,
 input wire [ND*(1)-1:0] norm_landing_reserved,
 input wire [ND*(72+1)-1:0] norm_landing_frame,
 input wire [ND*(1)-1:0] norm_provider_drained,
 input wire [ND*(1)-1:0] norm_publication_checked,
 input wire [ND*(72+1)-1:0] norm_publication_frame,
 output wire [ND*(1)-1:0] norm_publication_v,
 input wire [ND*(1)-1:0] norm_publication_r,
 input wire [ND*(72+1)-1:0] norm_publication_owner,
 input wire [ND*(NORM_AW-1+1)-1:0] norm_xbase,
 input wire [ND*(NORM_AW-1+1)-1:0] norm_ubase,
 input wire [ND*(NORM_AW-1+1)-1:0] norm_wbase,
 input wire [ND*(NORM_AW-1+1)-1:0] norm_ybase,
 input wire [ND*(NORM_AW-1+1)-1:0] norm_gain_base,
 input wire [ND*(511+1)-1:0] norm_comb,
 input wire [ND*(127+1)-1:0] norm_post_pre,
 input wire [ND*(31+1)-1:0] norm_n_f,
 input wire [ND*(31+1)-1:0] norm_eps,
 input wire [ND*(31+1)-1:0] norm_lim,
 input wire [ND*((NORM_RD?NORM_RD/2:1)*32)-1:0] norm_cos_t,
 input wire [ND*((NORM_RD?NORM_RD/2:1)*32)-1:0] norm_sin_t,
 output wire [ND*(4*NORM_N*NORM_AW-1+1)-1:0] norm_rd_addr,
 output wire [ND*(4*NORM_N-1+1)-1:0] norm_rd_re,
 output wire [ND*(8*NORM_N-1+1)-1:0] norm_rd_src,
 input wire [ND*(4*NORM_N*32-1+1)-1:0] norm_rd_q,
 output wire [ND*(NORM_N-1+1)-1:0] norm_vm_we,
 output wire [ND*(NORM_N*NORM_AW-1+1)-1:0] norm_vm_waddr,
 output wire [ND*(NORM_N*32-1+1)-1:0] norm_vm_wdata,
 output wire [ND*(1)-1:0] norm_q_valid,
 output wire [ND*(7+1)-1:0] norm_q_index,
 output wire [ND*(NORM_N*8-1+1)-1:0] norm_q_codes,
 output wire [ND*((NORM_N/32)*10-1+1)-1:0] norm_q_exp,
 output wire [ND*(NORM_N*16-1+1)-1:0] norm_q_bf16,
 output wire [ND*(15+1)-1:0] norm_reserve_events,
 output wire [ND*(72+1)-1:0] norm_held_frame,
 output wire [ND*(1)-1:0] norm_retained,
 output wire [ND*(1)-1:0] norm_fault,
 output wire [ND*(1)-1:0] norm_ce,
 output wire [ND*(1)-1:0] norm_due,
 // Owned combined callbacks. Descriptor/GO must originate from the actual
 // installed recipe; absent 96x512 source/entry remains compiler-failclosed.
 input wire [ND-1:0] gather_desc_v,gather_start_v,gather_book_valid,gather_req_v,gather_rsp_r,
 input wire [ND*3-1:0] gather_desc_index,input wire [ND*64-1:0] gather_desc_data,
 input wire [ND*649-1:0] gather_req,
 output wire [ND-1:0] gather_desc_r,gather_start_r,gather_req_r,gather_rsp_v,
 output wire [ND*637-1:0] gather_rsp,
 input wire [ND-1:0] gather_release_v,gather_result_published,gather_reverse_done,
 input wire [ND*73-1:0] gather_release_frame,output wire [ND-1:0] gather_release_r,
 output wire [ND-1:0] gather_retained,gather_arena_visible,gather_sink_visible,
 // Original normal W15 synchronous VM / collective ports; no ready/data ties.
 input wire [ND-1:0] normal_go,normal_id_plane,normal_e_ready,normal_o_valid,normal_o_last,normal_o_err,normal_engine_fault,
 input wire [ND*16-1:0] normal_command_tag,input wire [ND*32-1:0] normal_source_word,
 input wire [ND*512-1:0] normal_vm_rq,normal_o_data,input wire [ND*7-1:0] normal_o_rank,
 output wire [ND-1:0] normal_busy,normal_done,normal_vm_re,normal_e_valid,normal_e_last,normal_e_mode,normal_o_ready,
 output wire [ND*32-1:0] normal_vm_raddr,output wire [ND*512-1:0] normal_e_data,output wire [ND*16-1:0] normal_e_tag,
 // Ordered adapter request85 low tag16/word6/rank7/pos20/gen4/job32.
 // Response599 low UE1/checked1/data512/tag16/word6/rank7/pos20/gen4/job32.
 input wire [ND-1:0] formatter_start_v,index_pair_v,index_pairs_r,formatter_release_v,
 // TOKEN comes from the retained request caller, not the live CP launch.
 input wire [ND*85-1:0] index_pair,input wire [ND*17-1:0] index_pair_token17,
 output wire [ND-1:0] formatter_start_r,index_pair_r,index_pairs_v,formatter_release_r,
 output wire [ND*599-1:0] index_pairs,output wire [ND*73-1:0] index_pairs_frame73,
 // Existing caller rv/rop/rrow NC8 fields, held installed output extents.
 input wire [ND-1:0] w2_reserve_v,w2_output_installed,w2_pair_op,w2_result_v,w2_native_done,w2_assembly_drained,
 input wire [ND*2-1:0] w2_rows_a,w2_rows_b,
 input wire [ND*32-1:0] w2_op_a,w2_op_b,w2_output_base_a,w2_output_limit_a,w2_output_base_b,w2_output_limit_b,w2_result_op,
 input wire [ND*16-1:0] w2_output_tag,input wire [ND*12-1:0] w2_result_row,
 input wire [ND*256-1:0] w2_result_data,
 output wire [ND-1:0] w2_reserve_r,w2_source_permit,w2_output_done,
 input wire [ND-1:0] w2_lease_v,w2_release_v,w2_quiet,w2_req_v,w2_rsp_r,
 input wire [ND*73-1:0] w2_lease_frame,w2_release_frame,
 input wire [ND*337-1:0] w2_req,output wire [ND*273-1:0] w2_rsp,
 output wire [ND-1:0] w2_lease_granted,w2_release_r,w2_req_r,w2_rsp_v,
 // Existing readyless native caller and literal installed compact-sector map.
 // weights_installed comes only after loading Erdos w2_p0/p1 overlays into
 // the selected NS2 provider; CSV addresses/tags are never derived by truncation.
 input wire [ND-1:0] w2_weights_installed,w2_native_req_v,w2_native_delivery_permit,w2_map_valid,
 input wire [ND*32-1:0] w2_native_req_addr,w2_map_native_addr,
 input wire [ND*10-1:0] w2_native_req_tag,
 input wire [ND*73-1:0] w2_map_frame,
 input wire [ND*3-1:0] w2_map_sm,w2_map_count,
 input wire [ND*16-1:0] w2_map_compact_offset,
 input wire [ND*4-1:0] w2_map_lanes,
 input wire [ND*192-1:0] w2_map_byte_addresses,
 input wire [ND*96-1:0] w2_map_tags,w2_map_cfg,
 output wire [ND-1:0] w2_native_req_r,w2_native_rsp_pending,w2_native_rsp_v,w2_sector_drained,w2_sector_fault,w2_sector_foreign_rsp,
 output wire [ND*10-1:0] w2_native_rsp_tag,
 output wire [ND*1088-1:0] w2_native_rsp_data,
 output wire rst_sm_n, output wire sys_fault,
 output reg [31:0] fixture_cp_requests,fixture_cp_returns,fixture_ACKs,fixture_final_ACK_addr,fixture_bind_accepts,fixture_enroll_accepts,fixture_read_accepts,fixture_rsp_accepts,fixture_retire_accepts,fixture_db_accepts,fixture_cpl_accepts,
 output reg [31:0] fixture_sfu_enroll_accepts,fixture_sfu_cp_requests,fixture_sfu_cp_returns,fixture_sfu_ACKs,fixture_sfu_TXs,fixture_sfu_releases,
 output reg fixture_observer_fault
);

// Bench-only observation of die0 in the exact selected ND2 parent. All other
// ports are forwarded unchanged. No provider, grant, ACK, output or state writes.
 ot_ds_hbm_cluster20_integrated #(
  .COMBINED_ENABLE(COMBINED_ENABLE),
  .SFU_C12_ENABLE(SFU_C12_ENABLE),
  .SFU_NATIVE_VM_ENABLE(SFU_NATIVE_VM_ENABLE),
  .NORM_C12_ENABLE(NORM_C12_ENABLE),
  .NORM_NATIVE_VM_ENABLE(NORM_NATIVE_VM_ENABLE),
  .NORM_NATIVE_INPUT_CP(NORM_NATIVE_INPUT_CP),
  .SU_ENABLE(SU_ENABLE),
  .SU_REGISTERED_OUTPUTS(SU_REGISTERED_OUTPUTS),
  .SU_REGISTERED_STATUS(SU_REGISTERED_STATUS),
  .SU_REGISTERED_BOUNDARY(SU_REGISTERED_BOUNDARY),
  .SU_BALANCED_OWNER_BOUNDARY(SU_BALANCED_OWNER_BOUNDARY),
  .SU_FOUR_COMBINATIONAL_CUTS(SU_FOUR_COMBINATIONAL_CUTS),
  .SU_FAST_OWNER_FRONTIER(SU_FAST_OWNER_FRONTIER),
  .SU_PARALLEL_PHASE_VALIDATION(SU_PARALLEL_PHASE_VALIDATION),
  .SU_PROVIDER_ADAPTER(SU_PROVIDER_ADAPTER),
  .W2_RESULT_ENABLE(W2_RESULT_ENABLE),
  .W2_SECTOR_ENABLE(W2_SECTOR_ENABLE),
  .FORMATTER_ENABLE(FORMATTER_ENABLE),
  .NORMAL_GATHER_ENABLE(NORMAL_GATHER_ENABLE),
  .LOCAL_CP_RESET_ENABLE(LOCAL_CP_RESET_ENABLE),
  .VM_AW(VM_AW),
  .NORM_KIND(NORM_KIND),
  .NORM_N(NORM_N),
  .NORM_D(NORM_D),
  .NORM_RD(NORM_RD),
  .NORM_AW(NORM_AW),
  .NORM_PUBLISH_QUANT(NORM_PUBLISH_QUANT),
  .ENABLE(ENABLE),
  .TW(TW),
  .PW(PW),
  .CONTEXT_POSITIONS(CONTEXT_POSITIONS),
  .ND(ND),
  .NSM(NSM),
  .NL(NL),
  .IMW(IMW),
  .CB(CB),
  .NS(NS),
  .NPC(NPC),
  .MEM_WORDS(MEM_WORDS),
  .SW_PIPE(SW_PIPE),
  .USE_W2(USE_W2),
  .HAS_DIV(HAS_DIV),
  .HAS_BD(HAS_BD),
  .W2_PROTECTED_TRANSACTION_PIPELINE(W2_PROTECTED_TRANSACTION_PIPELINE)) dut (
  .por_n(por_n),
  .clk_host(clk_host),
  .clk_sm(clk_sm),
  .clk_mem(clk_mem),
  .clk_link(clk_link),
  .cp_reset_req(cp_reset_req),
  .cp_reset_ack(cp_reset_ack),
  .cmd_we(cmd_we),
  .cmd_addr(cmd_addr),
  .cmd_wdata(cmd_wdata),
  .db_v(db_v),
  .db_rdy(db_rdy),
  .db_token(db_token),
  .db_pos(db_pos),
  .db_job(db_job),
  .db_generation(db_generation),
  .cpl_v(cpl_v),
  .cpl_rdy(cpl_rdy),
  .cpl_data(cpl_data),
  .im_we(im_we),
  .im_addr(im_addr),
  .im_data(im_data),
  .sfu_enroll_v(sfu_enroll_v),
  .sfu_allocation_valid(sfu_allocation_valid),
  .sfu_publication_r(sfu_publication_r),
  .sfu_enroll_frame(sfu_enroll_frame),
  .sfu_allocation_frame(sfu_allocation_frame),
  .sfu_publication_owner(sfu_publication_owner),
  .sfu_pc(sfu_pc),
  .sfu_op(sfu_op),
  .sfu_source_addr(sfu_source_addr),
  .sfu_dest_addr(sfu_dest_addr),
  .sfu_source_base(sfu_source_base),
  .sfu_source_limit(sfu_source_limit),
  .sfu_dest_base(sfu_dest_base),
  .sfu_dest_limit(sfu_dest_limit),
  .sfu_local_tag(sfu_local_tag),
  .sfu_source(sfu_source),
  .sfu_expert(sfu_expert),
  .sfu_count(sfu_count),
  .sfu_matrix(sfu_matrix),
  .sfu_row(sfu_row),
  .sfu_fn(sfu_fn),
  .sfu_enroll_r(sfu_enroll_r),
  .sfu_publication_v(sfu_publication_v),
  .sfu_retained(sfu_retained),
  .sfu_fault(sfu_fault),
  .sfu_warm_ack(sfu_warm_ack),
  .sfu_held_frame(sfu_held_frame),
  .sfu_vm_bind_v(sfu_vm_bind_v),
  .sfu_vm_bind_r(sfu_vm_bind_r),
  .sfu_vm_bind_frame(sfu_vm_bind_frame),
  .sfu_vm_bind_rank(sfu_vm_bind_rank),
  .sfu_vm_bind_base(sfu_vm_bind_base),
  .sfu_vm_bind_span(sfu_vm_bind_span),
  .sfu_vm_retire_v(sfu_vm_retire_v),
  .sfu_vm_retire_r(sfu_vm_retire_r),
  .sfu_vm_retire_frame(sfu_vm_retire_frame),
  .sfu_vm_held_frame(sfu_vm_held_frame),
  .sfu_vm_retained(sfu_vm_retained),
  .sfu_vm_warm_ack(sfu_vm_warm_ack),
  .sfu_vm_fault(sfu_vm_fault),
  .sfu_vm_activation_wr_v(sfu_vm_activation_wr_v),
  .sfu_vm_activation_wr_r(sfu_vm_activation_wr_r),
  .sfu_vm_activation_wr_frame(sfu_vm_activation_wr_frame),
  .sfu_vm_activation_wr_bank(sfu_vm_activation_wr_bank),
  .sfu_vm_activation_wr_addr(sfu_vm_activation_wr_addr),
  .sfu_vm_activation_wr_data(sfu_vm_activation_wr_data),
  .sfu_vm_activation_wr_owner(sfu_vm_activation_wr_owner),
  .sfu_vm_activation_ACK_v(sfu_vm_activation_ACK_v),
  .sfu_vm_activation_ACK_r(sfu_vm_activation_ACK_r),
  .sfu_vm_activation_ACK_frame(sfu_vm_activation_ACK_frame),
  .sfu_vm_activation_ACK_owner(sfu_vm_activation_ACK_owner),
  .sfu_vm_activation_rd_v(sfu_vm_activation_rd_v),
  .sfu_vm_activation_rd_r(sfu_vm_activation_rd_r),
  .sfu_vm_activation_rd_frame(sfu_vm_activation_rd_frame),
  .sfu_vm_activation_rd_bank(sfu_vm_activation_rd_bank),
  .sfu_vm_activation_rd_addr(sfu_vm_activation_rd_addr),
  .sfu_vm_activation_rd_owner(sfu_vm_activation_rd_owner),
  .sfu_vm_tap_v(sfu_vm_tap_v),
  .sfu_vm_tap_r(sfu_vm_tap_r),
  .sfu_vm_tap_data(sfu_vm_tap_data),
  .sfu_vm_tap_owner(sfu_vm_tap_owner),
  .sfu_vm_tap_frame(sfu_vm_tap_frame),
  .sfu_vm_tap_source_clk(sfu_vm_tap_source_clk),
  .sfu_vm_tap_ACK_v(sfu_vm_tap_ACK_v),
  .sfu_vm_tap_ACK_r(sfu_vm_tap_ACK_r),
  .sfu_vm_tap_ACK_owner(sfu_vm_tap_ACK_owner),
  .sfu_vm_tap_ACK_frame(sfu_vm_tap_ACK_frame),
  .sfu_vm_activation_release(sfu_vm_activation_release),
  .sfu_vm_activation_release_r(sfu_vm_activation_release_r),
  .sfu_vm_activation_release_frame(sfu_vm_activation_release_frame),
  .sfu_vm_activation_release_owner(sfu_vm_activation_release_owner),
  .sfu_vm_su_pub_v(sfu_vm_su_pub_v),
  .sfu_vm_su_pub_r(sfu_vm_su_pub_r),
  .sfu_vm_su_pub_frame(sfu_vm_su_pub_frame),
  .sfu_vm_su_pub_addr(sfu_vm_su_pub_addr),
  .sfu_vm_su_pub_data(sfu_vm_su_pub_data),
  .sfu_vm_su_ACK_v(sfu_vm_su_ACK_v),
  .sfu_vm_su_ACK_r(sfu_vm_su_ACK_r),
  .sfu_vm_publication_ACK_addr(sfu_vm_publication_ACK_addr),
  .sfu_vm_publication_ACK_frame(sfu_vm_publication_ACK_frame),
  .sfu_vm_index_read_v(sfu_vm_index_read_v),
  .sfu_vm_index_read_r(sfu_vm_index_read_r),
  .sfu_vm_index_read_frame(sfu_vm_index_read_frame),
  .sfu_vm_index_read_rank(sfu_vm_index_read_rank),
  .sfu_vm_index_read_addr(sfu_vm_index_read_addr),
  .sfu_vm_index_read_words(sfu_vm_index_read_words),
  .sfu_vm_index_read_tag(sfu_vm_index_read_tag),
  .sfu_vm_index_rsp_v(sfu_vm_index_rsp_v),
  .sfu_vm_index_rsp_r(sfu_vm_index_rsp_r),
  .sfu_vm_index_rsp_data(sfu_vm_index_rsp_data),
  .sfu_vm_index_rsp_tag(sfu_vm_index_rsp_tag),
  .sfu_vm_index_rsp_frame(sfu_vm_index_rsp_frame),
  .sfu_vm_index_rsp_rank(sfu_vm_index_rsp_rank),
  .norm_warm_ack(norm_warm_ack),
  .norm_enroll_v(norm_enroll_v),
  .norm_enroll_r(norm_enroll_r),
  .norm_enroll_frame(norm_enroll_frame),
  .norm_enroll_pc(norm_enroll_pc),
  .norm_enroll_op(norm_enroll_op),
  .norm_enroll_source(norm_enroll_source),
  .norm_enroll_expert(norm_enroll_expert),
  .norm_enroll_matrix(norm_enroll_matrix),
  .norm_enroll_row(norm_enroll_row),
  .norm_enroll_count(norm_enroll_count),
  .norm_allocation_valid(norm_allocation_valid),
  .norm_allocation_frame(norm_allocation_frame),
  .norm_landing_reserved(norm_landing_reserved),
  .norm_landing_frame(norm_landing_frame),
  .norm_provider_drained(norm_provider_drained),
  .norm_publication_checked(norm_publication_checked),
  .norm_publication_frame(norm_publication_frame),
  .norm_publication_v(norm_publication_v),
  .norm_publication_r(norm_publication_r),
  .norm_publication_owner(norm_publication_owner),
  .norm_xbase(norm_xbase),
  .norm_ubase(norm_ubase),
  .norm_wbase(norm_wbase),
  .norm_ybase(norm_ybase),
  .norm_gain_base(norm_gain_base),
  .norm_comb(norm_comb),
  .norm_post_pre(norm_post_pre),
  .norm_n_f(norm_n_f),
  .norm_eps(norm_eps),
  .norm_lim(norm_lim),
  .norm_cos_t(norm_cos_t),
  .norm_sin_t(norm_sin_t),
  .norm_rd_addr(norm_rd_addr),
  .norm_rd_re(norm_rd_re),
  .norm_rd_src(norm_rd_src),
  .norm_rd_q(norm_rd_q),
  .norm_vm_we(norm_vm_we),
  .norm_vm_waddr(norm_vm_waddr),
  .norm_vm_wdata(norm_vm_wdata),
  .norm_q_valid(norm_q_valid),
  .norm_q_index(norm_q_index),
  .norm_q_codes(norm_q_codes),
  .norm_q_exp(norm_q_exp),
  .norm_q_bf16(norm_q_bf16),
  .norm_reserve_events(norm_reserve_events),
  .norm_held_frame(norm_held_frame),
  .norm_retained(norm_retained),
  .norm_fault(norm_fault),
  .norm_ce(norm_ce),
  .norm_due(norm_due),
  .gather_desc_v(gather_desc_v),
  .gather_start_v(gather_start_v),
  .gather_book_valid(gather_book_valid),
  .gather_req_v(gather_req_v),
  .gather_rsp_r(gather_rsp_r),
  .gather_desc_index(gather_desc_index),
  .gather_desc_data(gather_desc_data),
  .gather_req(gather_req),
  .gather_desc_r(gather_desc_r),
  .gather_start_r(gather_start_r),
  .gather_req_r(gather_req_r),
  .gather_rsp_v(gather_rsp_v),
  .gather_rsp(gather_rsp),
  .gather_release_v(gather_release_v),
  .gather_result_published(gather_result_published),
  .gather_reverse_done(gather_reverse_done),
  .gather_release_frame(gather_release_frame),
  .gather_release_r(gather_release_r),
  .gather_retained(gather_retained),
  .gather_arena_visible(gather_arena_visible),
  .gather_sink_visible(gather_sink_visible),
  .normal_go(normal_go),
  .normal_id_plane(normal_id_plane),
  .normal_e_ready(normal_e_ready),
  .normal_o_valid(normal_o_valid),
  .normal_o_last(normal_o_last),
  .normal_o_err(normal_o_err),
  .normal_engine_fault(normal_engine_fault),
  .normal_command_tag(normal_command_tag),
  .normal_source_word(normal_source_word),
  .normal_vm_rq(normal_vm_rq),
  .normal_o_data(normal_o_data),
  .normal_o_rank(normal_o_rank),
  .normal_busy(normal_busy),
  .normal_done(normal_done),
  .normal_vm_re(normal_vm_re),
  .normal_e_valid(normal_e_valid),
  .normal_e_last(normal_e_last),
  .normal_e_mode(normal_e_mode),
  .normal_o_ready(normal_o_ready),
  .normal_vm_raddr(normal_vm_raddr),
  .normal_e_data(normal_e_data),
  .normal_e_tag(normal_e_tag),
  .formatter_start_v(formatter_start_v),
  .index_pair_v(index_pair_v),
  .index_pairs_r(index_pairs_r),
  .formatter_release_v(formatter_release_v),
  .index_pair(index_pair),
  .index_pair_token17(index_pair_token17),
  .formatter_start_r(formatter_start_r),
  .index_pair_r(index_pair_r),
  .index_pairs_v(index_pairs_v),
  .formatter_release_r(formatter_release_r),
  .index_pairs(index_pairs),
  .index_pairs_frame73(index_pairs_frame73),
  .w2_reserve_v(w2_reserve_v),
  .w2_output_installed(w2_output_installed),
  .w2_pair_op(w2_pair_op),
  .w2_result_v(w2_result_v),
  .w2_native_done(w2_native_done),
  .w2_assembly_drained(w2_assembly_drained),
  .w2_rows_a(w2_rows_a),
  .w2_rows_b(w2_rows_b),
  .w2_op_a(w2_op_a),
  .w2_op_b(w2_op_b),
  .w2_output_base_a(w2_output_base_a),
  .w2_output_limit_a(w2_output_limit_a),
  .w2_output_base_b(w2_output_base_b),
  .w2_output_limit_b(w2_output_limit_b),
  .w2_result_op(w2_result_op),
  .w2_output_tag(w2_output_tag),
  .w2_result_row(w2_result_row),
  .w2_result_data(w2_result_data),
  .w2_reserve_r(w2_reserve_r),
  .w2_source_permit(w2_source_permit),
  .w2_output_done(w2_output_done),
  .w2_lease_v(w2_lease_v),
  .w2_release_v(w2_release_v),
  .w2_quiet(w2_quiet),
  .w2_req_v(w2_req_v),
  .w2_rsp_r(w2_rsp_r),
  .w2_lease_frame(w2_lease_frame),
  .w2_release_frame(w2_release_frame),
  .w2_req(w2_req),
  .w2_rsp(w2_rsp),
  .w2_lease_granted(w2_lease_granted),
  .w2_release_r(w2_release_r),
  .w2_req_r(w2_req_r),
  .w2_rsp_v(w2_rsp_v),
  .w2_weights_installed(w2_weights_installed),
  .w2_native_req_v(w2_native_req_v),
  .w2_native_delivery_permit(w2_native_delivery_permit),
  .w2_map_valid(w2_map_valid),
  .w2_native_req_addr(w2_native_req_addr),
  .w2_map_native_addr(w2_map_native_addr),
  .w2_native_req_tag(w2_native_req_tag),
  .w2_map_frame(w2_map_frame),
  .w2_map_sm(w2_map_sm),
  .w2_map_count(w2_map_count),
  .w2_map_compact_offset(w2_map_compact_offset),
  .w2_map_lanes(w2_map_lanes),
  .w2_map_byte_addresses(w2_map_byte_addresses),
  .w2_map_tags(w2_map_tags),
  .w2_map_cfg(w2_map_cfg),
  .w2_native_req_r(w2_native_req_r),
  .w2_native_rsp_pending(w2_native_rsp_pending),
  .w2_native_rsp_v(w2_native_rsp_v),
  .w2_sector_drained(w2_sector_drained),
  .w2_sector_fault(w2_sector_fault),
  .w2_sector_foreign_rsp(w2_sector_foreign_rsp),
  .w2_native_rsp_tag(w2_native_rsp_tag),
  .w2_native_rsp_data(w2_native_rsp_data),
  .rst_sm_n(rst_sm_n),
  .sys_fault(sys_fault));
 initial if(ND!=2||NSM!=2||NS!=2||NPC!=2||MEM_WORDS!=2097152||TW!=17||PW!=20||NORM_KIND!=0||NORM_N!=64||NORM_D!=5120||NORM_AW!=24||NORM_RD!=0||!NORM_PUBLISH_QUANT||!ENABLE||!COMBINED_ENABLE||!NORM_C12_ENABLE||!NORM_NATIVE_VM_ENABLE||!NORM_NATIVE_INPUT_CP||!SFU_C12_ENABLE||!SFU_NATIVE_VM_ENABLE||!FORMATTER_ENABLE||!LOCAL_CP_RESET_ENABLE)
  $fatal(1,"minimum parent fixture selected graph/geometry mismatch");
 reg [1:0] seen_sfu_ACK;
 reg [399:0] seen_ACK;
 integer slot;
 always @(posedge clk_sm) begin
  if (!rst_sm_n) begin
   fixture_cp_requests<=0;
   fixture_cp_returns<=0;
   fixture_ACKs<=0;
   fixture_final_ACK_addr<=0;
   fixture_bind_accepts<=0;
   fixture_enroll_accepts<=0;
   fixture_read_accepts<=0;
   fixture_rsp_accepts<=0;
   fixture_retire_accepts<=0;
   fixture_db_accepts<=0;
   fixture_cpl_accepts<=0;
   fixture_observer_fault<=0;seen_ACK<=0;seen_sfu_ACK<=0;
   fixture_sfu_enroll_accepts<=0;fixture_sfu_cp_requests<=0;fixture_sfu_cp_returns<=0;fixture_sfu_ACKs<=0;fixture_sfu_TXs<=0;fixture_sfu_releases<=0;
  end else begin
   if(db_v[0]&&db_rdy[0])fixture_db_accepts<=fixture_db_accepts+1;
   if(cpl_v[0]&&cpl_rdy[0])fixture_cpl_accepts<=fixture_cpl_accepts+1;
   if(sfu_vm_bind_v[0]&&sfu_vm_bind_r[0])fixture_bind_accepts<=fixture_bind_accepts+1;
   if(norm_enroll_v[0]&&norm_enroll_r[0])fixture_enroll_accepts<=fixture_enroll_accepts+1;
   if(sfu_vm_index_read_v[0]&&sfu_vm_index_read_r[0])fixture_read_accepts<=fixture_read_accepts+1;
   if(sfu_vm_index_rsp_v[0]&&sfu_vm_index_rsp_r[0])fixture_rsp_accepts<=fixture_rsp_accepts+1;
   if(sfu_vm_retire_v[0]&&sfu_vm_retire_r[0])fixture_retire_accepts<=fixture_retire_accepts+1;
   if(dut.g_on.g_die[0].norm_cp_req_v&&dut.g_on.g_die[0].p_req_rdy[1]&&dut.g_on.g_die[0].norm_route)begin
    fixture_cp_requests<=fixture_cp_requests+1;
    if(dut.g_on.g_die[0].norm_cp_req[336]||dut.g_on.g_die[0].norm_cp_req[335:304]>=102400||dut.g_on.g_die[0].norm_cp_req[308:304]!=0)fixture_observer_fault<=1;
   end
   if(dut.g_on.g_die[0].p_rsp_v[1]&&dut.g_on.g_die[0].norm_cp_rsp_r&&dut.g_on.g_die[0].norm_route)
    fixture_cp_returns<=fixture_cp_returns+1;
   if(dut.g_on.g_die[0].norm_ACK_v&&dut.g_on.g_die[0].norm_ACK_r)begin
    fixture_ACKs<=fixture_ACKs+1;
    fixture_final_ACK_addr<=sfu_vm_publication_ACK_addr[31:0];
    if(sfu_vm_publication_ACK_frame[72:0]!=norm_held_frame[72:0]||sfu_vm_publication_ACK_addr[31:0]<3584||sfu_vm_publication_ACK_addr[31:0]>16352||sfu_vm_publication_ACK_addr[4:0]!=0)fixture_observer_fault<=1;
    else begin
     slot=(sfu_vm_publication_ACK_addr[31:0]-3584)/32;
     if(seen_ACK[slot])fixture_observer_fault<=1;
     seen_ACK[slot]<=1;
    end
   end
   if(norm_publication_v[0]&&(!(&seen_ACK)||fixture_ACKs!=400))fixture_observer_fault<=1;
   // Read-only observation of actual CASE1 native SFU transport/checked SRAM.
   if(sfu_enroll_v[0]&&sfu_enroll_r[0])fixture_sfu_enroll_accepts<=fixture_sfu_enroll_accepts+1;
   if(dut.g_on.g_die[0].sfu_req_v&&dut.g_on.g_die[0].p_req_rdy[1]&&dut.g_on.g_die[0].sfu_route)begin
    fixture_sfu_cp_requests<=fixture_sfu_cp_requests+1;
    if(dut.g_on.g_die[0].sfu_req[336]||dut.g_on.g_die[0].sfu_req[335:304]<32'ha0000||dut.g_on.g_die[0].sfu_req[335:304]>=32'ha0100||dut.g_on.g_die[0].sfu_req[308:304]!=0)fixture_observer_fault<=1;
   end
   if(dut.g_on.g_die[0].p_rsp_v[1]&&dut.g_on.g_die[0].sfu_rsp_r&&dut.g_on.g_die[0].sfu_route)
    fixture_sfu_cp_returns<=fixture_sfu_cp_returns+1;
   if(dut.g_on.g_die[0].nv_tx_v&&dut.g_on.g_die[0].nv_tx_r)begin
    fixture_sfu_TXs<=fixture_sfu_TXs+1;
    if(dut.g_on.g_die[0].nv_tx_owner!=sfu_held_frame[72:0]||dut.g_on.g_die[0].nv_tx_index!=fixture_sfu_TXs||dut.g_on.g_die[0].nv_tx_last!=(fixture_sfu_TXs==2))fixture_observer_fault<=1;
   end
   if(dut.g_on.g_die[0].g_sfu_native_vm.u_vm.result_ACK_v&&dut.g_on.g_die[0].g_sfu_native_vm.u_vm.result_ACK_r)begin
    fixture_sfu_ACKs<=fixture_sfu_ACKs+1;
    if(sfu_vm_publication_ACK_frame[72:0]!=sfu_held_frame[72:0]||(sfu_vm_publication_ACK_addr[31:0]!=64&&sfu_vm_publication_ACK_addr[31:0]!=96))fixture_observer_fault<=1;
    else begin
     slot=(sfu_vm_publication_ACK_addr[31:0]-64)/32;
     if(seen_sfu_ACK[slot])fixture_observer_fault<=1;
     seen_sfu_ACK[slot]<=1;
    end
   end
   if(dut.g_on.g_die[0].sfu_release_v&&dut.g_on.g_die[0].peer_releases[0]&&dut.g_on.g_die[0].sfu_route)
    fixture_sfu_releases<=fixture_sfu_releases+1;
   if(sfu_publication_v[0]&&(!(&seen_sfu_ACK)||fixture_sfu_ACKs!=2||fixture_sfu_TXs!=3))fixture_observer_fault<=1;
  end
 end
endmodule
