unset_input_delay [all_inputs]
unset_output_delay [all_outputs]
set_input_delay 166.667 -clock ck [get_ports {x3_v x3_d[*] x3_tag[*] ar_cr ea_v ea_kind ea_addr[*]}]
set_output_delay 166.667 -clock ck [get_ports {l0_o[*] l1_o[*] l2_o[*] l3_o[*] x3_cr ar_v ar_d[*] fault fault_cause[*] ea_cr eq_v eq_d[*] emb_ready emb_fault emb_fault_code[*]}]
set_input_delay 166.667 -clock fck0 [get_ports {l0_i[*]}]
set_input_delay 166.667 -clock fck1 [get_ports {l1_i[*]}]
set_input_delay 166.667 -clock fck2 [get_ports {l2_i[*]}]
set_input_delay 166.667 -clock fck3 [get_ports {l3_i[*]}]
set_false_path -from [get_ports {rst_n}]
