`timescale 1ns/1ps
module tb;
 reg  clk;
 reg  por_n;
 reg  rst_n;
 reg  run_enable;
 reg  source_fault;
 reg  rf_write_accept;
 reg [54:0] rf_write_owner55;
 reg  wr_binding_valid;
 reg  wr_KV_related;
 reg [63:0] wr_identity;
 reg [19:0] wr_key;
 wire  wr_permit;
 reg  wr_continuation_valid;
 reg  wr_continuation_source;
 reg  rd_continuation_valid;
 reg  rd_continuation_source;
 reg [54:0] rd_context_owner55;
 reg  simd_context_accept;
 reg  simd_binding_valid;
 reg  simd_KV_related;
 reg [54:0] simd_context_owner55;
 reg [63:0] simd_identity;
 reg [19:0] simd_key;
 wire  simd_context_permit;
 reg  simd_context_retire;
 reg [54:0] simd_retire_owner55;
 reg  rf_ack_valid;
 reg  rf_ack_accept;
 reg [54:0] rf_ack_owner55;
 reg  rf_ack_fault;
 wire  rf_ack_allow;
 reg  rf_read_accept;
 reg [8:0] rf_read_a;
 reg [8:0] rf_read_b;
 reg  rd_binding_valid;
 reg  rd_KV_related;
 reg [63:0] rd_identity;
 reg [19:0] rd_key;
 wire  rd_permit;
 reg  rf_rsp_valid;
 reg  rf_rsp_accept;
 wire  rf_rsp_allow;
 reg  w6_request_accept;
 reg [54:0] w6_request_owner55;
 reg  w6_binding_valid;
 reg  w6_KV_related;
 reg  w6_internal_SIMD;
 reg [63:0] w6_identity;
 reg [19:0] w6_key;
 wire  w6_permit;
 reg  w6_host_ACK_accept;
 reg  w6_SIMD_ACK_accept;
 reg [54:0] w6_ACK_owner55;
 reg  w6_consumer_accept;
 reg [54:0] w6_consumer_owner55;
 reg  w6_child_accept;
 reg [54:0] w6_child_owner55;
 reg  w6_parent_accept;
 reg [54:0] w6_parent_owner55;
 reg  w6_CDC_accept;
 reg [54:0] w6_CDC_owner55;
 reg  w6_retire_accept;
 reg [54:0] w6_retire_owner55;
 reg [54:0] w6_local_drain_owner55;
 reg  w6_local_drain_has_owner;
 reg  w6_local_drain_reset_scope;
 reg  drain_req_valid;
 wire  drain_req_ready;
 reg [63:0] drain_req_identity;
 reg [19:0] drain_req_key;
 reg  drain_hold;
 wire  drain_rsp_valid;
 reg  drain_rsp_ready;
 wire [63:0] drain_rsp_identity;
 wire [19:0] drain_rsp_key;
 wire  drain_rsp_empty;
 wire  drain_retained;
 wire  write_retained;
 wire  read_retained;
 wire  w6_retained;
 wire  w6_local_RF_empty;
 wire  fault;
 ot_gpu_qwen_rf_ack_drain_r2 #(.ENABLE(1)) dut(
.clk(clk),.por_n(por_n),.rst_n(rst_n),.run_enable(run_enable),.source_fault(source_fault),.rf_write_accept(rf_write_accept),.rf_write_owner55(rf_write_owner55),.wr_binding_valid(wr_binding_valid),.wr_KV_related(wr_KV_related),.wr_identity(wr_identity),.wr_key(wr_key),.wr_permit(wr_permit),.wr_continuation_valid(wr_continuation_valid),.wr_continuation_source(wr_continuation_source),.rd_continuation_valid(rd_continuation_valid),.rd_continuation_source(rd_continuation_source),.rd_context_owner55(rd_context_owner55),.simd_context_accept(simd_context_accept),.simd_binding_valid(simd_binding_valid),.simd_KV_related(simd_KV_related),.simd_context_owner55(simd_context_owner55),.simd_identity(simd_identity),.simd_key(simd_key),.simd_context_permit(simd_context_permit),.simd_context_retire(simd_context_retire),.simd_retire_owner55(simd_retire_owner55),.rf_ack_valid(rf_ack_valid),.rf_ack_accept(rf_ack_accept),.rf_ack_owner55(rf_ack_owner55),.rf_ack_fault(rf_ack_fault),.rf_ack_allow(rf_ack_allow),.rf_read_accept(rf_read_accept),.rf_read_a(rf_read_a),.rf_read_b(rf_read_b),.rd_binding_valid(rd_binding_valid),.rd_KV_related(rd_KV_related),.rd_identity(rd_identity),.rd_key(rd_key),.rd_permit(rd_permit),.rf_rsp_valid(rf_rsp_valid),.rf_rsp_accept(rf_rsp_accept),.rf_rsp_allow(rf_rsp_allow),.w6_request_accept(w6_request_accept),.w6_request_owner55(w6_request_owner55),.w6_binding_valid(w6_binding_valid),.w6_KV_related(w6_KV_related),.w6_internal_SIMD(w6_internal_SIMD),.w6_identity(w6_identity),.w6_key(w6_key),.w6_permit(w6_permit),.w6_host_ACK_accept(w6_host_ACK_accept),.w6_SIMD_ACK_accept(w6_SIMD_ACK_accept),.w6_ACK_owner55(w6_ACK_owner55),.w6_consumer_accept(w6_consumer_accept),.w6_consumer_owner55(w6_consumer_owner55),.w6_child_accept(w6_child_accept),.w6_child_owner55(w6_child_owner55),.w6_parent_accept(w6_parent_accept),.w6_parent_owner55(w6_parent_owner55),.w6_CDC_accept(w6_CDC_accept),.w6_CDC_owner55(w6_CDC_owner55),.w6_retire_accept(w6_retire_accept),.w6_retire_owner55(w6_retire_owner55),.w6_local_drain_owner55(w6_local_drain_owner55),.w6_local_drain_has_owner(w6_local_drain_has_owner),.w6_local_drain_reset_scope(w6_local_drain_reset_scope),.drain_req_valid(drain_req_valid),.drain_req_ready(drain_req_ready),.drain_req_identity(drain_req_identity),.drain_req_key(drain_req_key),.drain_hold(drain_hold),.drain_rsp_valid(drain_rsp_valid),.drain_rsp_ready(drain_rsp_ready),.drain_rsp_identity(drain_rsp_identity),.drain_rsp_key(drain_rsp_key),.drain_rsp_empty(drain_rsp_empty),.drain_retained(drain_retained),.write_retained(write_retained),.read_retained(read_retained),.w6_retained(w6_retained),.w6_local_RF_empty(w6_local_RF_empty),.fault(fault)
);
 always #5 clk=~clk;
 localparam [54:0] OWNER={7'd3,3'd0,32'h123,4'd2,9'd19};
 task tick;begin @(posedge clk);#1;end endtask
 task check(input bit ok,input string message);begin if(!ok)$fatal(1,"%s",message);end endtask
 task cold;begin
 por_n='0;
 rst_n='0;
 run_enable='0;
 source_fault='0;
 rf_write_accept='0;
 rf_write_owner55='0;
 wr_binding_valid='0;
 wr_KV_related='0;
 wr_identity='0;
 wr_key='0;
 wr_continuation_valid='0;
 wr_continuation_source='0;
 rd_continuation_valid='0;
 rd_continuation_source='0;
 rd_context_owner55='0;
 simd_context_accept='0;
 simd_binding_valid='0;
 simd_KV_related='0;
 simd_context_owner55='0;
 simd_identity='0;
 simd_key='0;
 simd_context_retire='0;
 simd_retire_owner55='0;
 rf_ack_valid='0;
 rf_ack_accept='0;
 rf_ack_owner55='0;
 rf_ack_fault='0;
 rf_read_accept='0;
 rf_read_a='0;
 rf_read_b='0;
 rd_binding_valid='0;
 rd_KV_related='0;
 rd_identity='0;
 rd_key='0;
 rf_rsp_valid='0;
 rf_rsp_accept='0;
 w6_request_accept='0;
 w6_request_owner55='0;
 w6_binding_valid='0;
 w6_KV_related='0;
 w6_internal_SIMD='0;
 w6_identity='0;
 w6_key='0;
 w6_host_ACK_accept='0;
 w6_SIMD_ACK_accept='0;
 w6_ACK_owner55='0;
 w6_consumer_accept='0;
 w6_consumer_owner55='0;
 w6_child_accept='0;
 w6_child_owner55='0;
 w6_parent_accept='0;
 w6_parent_owner55='0;
 w6_CDC_accept='0;
 w6_CDC_owner55='0;
 w6_retire_accept='0;
 w6_retire_owner55='0;
 w6_local_drain_owner55='0;
 w6_local_drain_has_owner='0;
 w6_local_drain_reset_scope='0;
 drain_req_valid='0;
 drain_req_identity='0;
 drain_req_key='0;
 drain_hold='0;
 drain_rsp_ready='0;
 run_enable=1;rst_n=1;por_n=0;tick;por_n=1;tick;
 wr_binding_valid=1;rd_binding_valid=1;w6_binding_valid=1;simd_binding_valid=1;
 wr_KV_related=1;rd_KV_related=1;w6_KV_related=1;simd_KV_related=1;
 wr_identity=64'h77;rd_identity=64'h77;w6_identity=64'h77;simd_identity=64'h77;
 rf_write_owner55=OWNER;rf_ack_owner55=OWNER;w6_request_owner55=OWNER;
 simd_context_owner55=OWNER;simd_retire_owner55=OWNER;rd_context_owner55=OWNER;
 w6_ACK_owner55=OWNER;w6_consumer_owner55=OWNER;w6_child_owner55=OWNER;
 w6_parent_owner55=OWNER;w6_CDC_owner55=OWNER;w6_retire_owner55=OWNER;
 w6_local_drain_owner55=OWNER;w6_local_drain_has_owner=1;#1;
 end endtask
 task old_simd_read;begin
 check(simd_context_permit,"new SIMD context cannot be accepted");
 simd_context_accept=1;tick;simd_context_accept=0;
 rd_continuation_valid=1;rd_continuation_source=1;#1;
 check(rd_permit,"accepted SIMD paired read continuation denied");
 rf_read_accept=1;rf_read_a=17;rf_read_b=18;tick;rf_read_accept=0;
 drain_req_valid=1;drain_hold=1;drain_req_identity=64'h77;
 check(drain_req_ready,"drain request denied");tick;drain_req_valid=0;
 rf_rsp_valid=1;repeat(2)begin tick;check(!drain_rsp_valid,"drain escaped held read response");end
 rf_rsp_accept=1;tick;rf_rsp_accept=0;rf_rsp_valid=0;rd_continuation_valid=0;#1;
 end endtask
 initial begin clk=0;cold;old_simd_read;
 wr_continuation_valid=0;#1;check(!wr_permit,"NEW matching key write bypassed drain");
 check(!simd_context_permit,"NEW matching SIMD bypassed drain");
 wr_continuation_valid=1;wr_continuation_source=1;rf_write_owner55=OWNER^55'd1;#1;
 check(!wr_permit,"wrong retained SIMD destination was permitted");
 rf_write_owner55=OWNER;#1;check(wr_permit,"OLD SIMD write deadlocked under drain");
 repeat(7)begin tick;check(wr_permit&&!drain_rsp_valid&&!fault,"ALU/provider stall lost owned continuation");end
 rf_write_accept=1;tick;rf_write_accept=0;#1;check(write_retained,"accepted old write not retained");
 rf_ack_valid=1;repeat(3)begin tick;check(rf_ack_allow&&!drain_rsp_valid,"held old ACK did not retain drain debt");end
 rf_ack_accept=1;simd_context_retire=1;tick;rf_ack_accept=0;rf_ack_valid=0;simd_context_retire=0;#1;
 check(drain_rsp_valid&&!fault,"old ACK/retire did not unblock drain");
 check(drain_rsp_identity==64'h77&&drain_rsp_key==0,"drain identity changed");
 repeat(2)tick;drain_rsp_ready=1;tick;drain_rsp_ready=0;#1;
 check(drain_retained&&!simd_context_permit,"leaf reply released ALLcohort hold early");
 drain_hold=0;tick;#1;check(!drain_retained&&simd_context_permit&&!fault,"actual parent release failed");
 $display("PASS_OLD_SIMD_CONTINUATION_STALL_DRAIN");
 cold;old_simd_read;wr_continuation_valid=1;wr_continuation_source=1;rst_n=0;#1;
 check(fault&&!wr_permit&&!drain_rsp_valid,"runtime reset bypassed retained context");
 tick;rst_n=1;tick;check(fault&&drain_retained&&!wr_permit,"warm reset discarded debt or cleared fault");
 $display("PASS_RESET_RETAINS_OLD_CONTEXT");
 cold;old_simd_read;wr_continuation_valid=1;wr_continuation_source=1;source_fault=1;#1;
 check(fault&&!wr_permit&&!drain_rsp_valid,"source fault permitted continuation");
 tick;source_fault=0;tick;check(fault&&drain_retained&&!wr_permit,"fault release cleared old debt");
 $display("PASS_FAULT_RETAINS_OLD_CONTEXT");
 cold;check(w6_permit,"W6 parent admission failed");w6_request_accept=1;tick;w6_request_accept=0;
 drain_req_valid=1;drain_hold=1;drain_req_identity=64'h77;tick;drain_req_valid=0;
 wr_continuation_valid=1;wr_continuation_source=0;#1;
 check(wr_permit&&!w6_permit,"old W6 continuation/new admission distinction failed");
 rf_write_accept=1;tick;rf_write_accept=0;rf_ack_valid=1;rf_ack_accept=1;tick;
 rf_ack_valid=0;rf_ack_accept=0;#1;check(!wr_permit,"second W6 write reused old continuation");
 w6_host_ACK_accept=1;tick;w6_host_ACK_accept=0;w6_consumer_accept=1;tick;w6_consumer_accept=0;
 w6_child_accept=1;tick;w6_child_accept=0;w6_parent_accept=1;tick;w6_parent_accept=0;
 w6_CDC_accept=1;tick;w6_CDC_accept=0;#1;check(!drain_rsp_valid,"W6 reverse was substituted for actual retire");
 w6_retire_accept=1;tick;w6_retire_accept=0;#1;check(drain_rsp_valid&&!fault,"matching W6 retire failed drain");
 $display("PASS_W6_OLD_ONE_WRITE_AND_REVERSE_RETIRE");
 $display("PASS_DIRECTED_STALL_DRAIN_RESET_FAULT");$finish;
 end
endmodule
