// Physical macro symbol only. Link the accompanying actual retained LEF
// and SS/FF timing libraries. Use real engine RTL for functional simulation.
// Fixed hardened ABI; no shape parameters or guessed pins/clock/protection.
(* blackbox, keep_hierarchy *) module ot_su12_full (
 inout wire VDD,
 inout wire VSS,
 input wire [23:0] aibase,
 input wire [1:0] aind,
 input wire bank,
 input wire [2:0] ca_ad,
 input wire [31:0] ca_imm2,
 input wire [1:0] ce_e2,
 input wire [31:0] ce_imm1,
 input wire [2:0] ci_sfu,
 input wire clk,
 input wire [31:0] cm_imm1,
 input wire [2:0] cm_m1,
 input wire [1:0] cm_m2,
 input wire [2:0] cm_qm,
 input wire [1:0] co_dst,
 input wire co_rnd,
 output wire coll,
 input wire [31:0] cp_imm1,
 input wire [2:0] cp_m1,
 input wire cpair,
 input wire [2:0] cs_e1,
 input wire [31:0] cs_imm2,
 input wire [2:0] cs_sfu,
 input wire cx_amin,
 input wire cx_arelu,
 input wire cx_arnd,
 input wire cx_cclip,
 input wire [31:0] cx_imm3,
 input wire [1:0] dst,
 input wire emit,
 output wire fault,
 input wire [4:0] gsh,
 input wire [23:0] i_v,
 input wire [23:0] krow,
 output wire [23:0] kv_waddr,
 output wire [31:0] kv_wdata,
 output wire kv_we,
 input wire ld,
 input wire ld_bank,
 input wire [1199:0] ld_c,
 input wire [3:0] ls,
 input wire [3:0] lvw,
 input wire [23:0] ni,
 input wire [23:0] no,
 input wire [23:0] o_v,
 input wire [23:0] obase,
 output wire [95:0] rd_addr,
 input wire [127:0] rd_q,
 output wire [3:0] rd_re,
 output wire [7:0] rd_src,
 output wire ro_v,
 output wire [31:0] ro_x,
 input wire rst_n,
 output wire side_v,
 output wire [31:0] side_x,
 input wire [31:0] side_y,
 input wire [7:0] srcs,
 input wire [119:0] vb,
 output wire [23:0] vi_addr,
 input wire [31:0] vi_q,
 output wire vi_re,
 output wire [23:0] vm_waddr,
 output wire [31:0] vm_wdata,
 output wire vm_we
);
endmodule
