export DESIGN_NICKNAME = opentallas_ot_hgi_quant_decode_asap7_qdm_hgi_quant_pd50_7202d4ec4_tc_cx
export DESIGN_NAME = ot_hgi_quant_decode
export PLATFORM = asap7
export VERILOG_FILES = /src/rtl/hbm_accel/generic/ot_hgi_quant_decode.sv /src/physical/hbm_accel_die_views/common/ot_hfd_oreg1.sv /src/physical/hbm_accel_die_views/quant/rtl/ot_hfd_actquant_m.sv /src/rtl/hbm_accel/generic/ot_hgi_fp4qdq.sv /src/rtl/hdc/ot_hdc_delay.sv /src/rtl/hdc/ot_hdc_fpu.sv /src/rtl/hdc/ot_hdc_fp32_mul_pipe.sv /src/rtl/hdc/ot_hdc_sfu.sv /src/rtl/hdc/ot_hdc_fastfp.sv /src/rtl/hdc/ot_hdc_fastfp_lat_f12.sv /src/rtl/hdc/ot_hdc_fp32_f12.sv /src/rtl/hdc/ot_hdc_prefix.sv
export VERILOG_DEFINES = -DSYNTHESIS
export SDC_FILE = /work/constraint.sdc
export DIE_AREA = 0 0 1800 600
export CORE_AREA = 2.16 2.16 1797.84 597.84
export PLACE_DENSITY = 0.5
export PLACE_DENSITY_LB_ADDON = 0.05
export SYNTH_REPEATABLE_BUILD = 1
export SYNTH_HIERARCHICAL = 0
export SYNTH_MEMORY_MAX_BITS = 65536
export LEC_CHECK = 0
export TNS_END_PERCENT = 100
export HOLD_SLACK_MARGIN = 0
export SETUP_SLACK_MARGIN = 0
export SKIP_REPORT_METRICS = 0
export REPORT_CLOCK_SKEW = 1
export CORNER = WC
export ADDER_MAP_FILE = 
export ASAP7_USE_VT = RVT
export CTS_ARGS = -sink_clustering_enable -repair_clock_nets -delay_buffer_derate 0.75
export IO_PLACER_H = M4 M6
export IO_PLACER_V = M5 M7
export NUM_CORES = 12
export OT_HOLD_MM = 1
export OT_IO_HOLD_SKEW = 50
export OT_IO_INTER = *
export OT_IO_SKEW = 90
export OT_IO_SKEW_INTER = 150
export OT_MM_FF_SDC = /src/physical/qwen_die_masters/signoff/hgi_quant_pd50.sdc
export OT_REF_GLOB = *valid_pipe*
export PLACE_PINS_ARGS = -min_distance 2 -min_distance_in_tracks
export QDM_SDC_DIR = /src/physical/qwen_die_masters
export SDC_FILE = /src/physical/qwen_die_masters/die_p770.sdc
export WC_NLDM_LIB_FILES = $(TC_NLDM_LIB_FILES)
export SLEW_MARGIN = 30
export HOLD_SLACK_MARGIN = 10
export CORNERS = WC BC
export WC_LIB_FILES = $(WC_NLDM_LIB_FILES)
export BC_LIB_FILES = $(BC_NLDM_LIB_FILES)
export IO_CONSTRAINTS = /work/io_constraints.tcl
export MIN_ROUTING_LAYER = M2
export MAX_ROUTING_LAYER = M7
export POST_CTS_TCL = /work/hooks/post_cts_post_plain.tcl
export PRE_GLOBAL_ROUTE_TCL = /work/hooks/pre_global_route_pre_ref_skew.tcl
export POST_GLOBAL_ROUTE_TCL = /work/hooks/post_global_route_post_plain.tcl
export PRE_DETAIL_ROUTE_TCL = /work/hooks/pre_detail_route_pre_ref_skew.tcl
export POST_DETAIL_ROUTE_TCL = /work/hooks/post_detail_route_post_plain.tcl
export PRE_FILLCELL_TCL = /work/hooks/pre_fillcell_pre_ref_skew.tcl
export POST_FILLCELL_TCL = /work/hooks/post_fillcell_post_plain.tcl
export SYNTH_CANONICALIZE_TCL = /src/physical/common_flow/ot_keep_regs.tcl
export PRE_CTS_TCL = /work/hooks/pre_cts_ot_cts_fix.tcl
